### ISSUE TITLE
Rugged Tactic not working 

### ISSUE THREAD

**Issue by DirtySIN** [WarEmu/WarBugs#14034] opened 2019-05-07 04:58 UTC
For some reason when loading in and out of scenarios and sometimes when changing zones the tank tactic "Rugged" seems to turn off even when equipped. In the attached screenshots you will notice i have the "Rugged" tactic equipped but one shows 513 and then after coming out of a scenario it shows 389. which is exactly the amount of toughness my "Rugged" tactic gives me. When you unslot "Rugged" and reslot it the problem resolves giving you the full stats back. 

Not sure if this issue is because im not rank 40 (Im rank 31 at the moment) but once I hit 40 I'll be sure to check it again and update this as needed. 

![Dirtiest_001](https://user-images.githubusercontent.com/50351273/57272711-d68a3b00-7062-11e9-8fe5-10e7666fbca2.jpg)
![Dirtiest_002](https://user-images.githubusercontent.com/50351273/57272736-eb66ce80-7062-11e9-9a69-75c41227e804.jpg)

**Comment by DirtySIN** [comment] 2019-05-07 05:02
https://github.com/WarEmu/WarBugs/issues/14003

Just noticed this falls under this issue. So maybe its all of the different class stat tactics

**Comment by sioding** [comment] 2019-05-07 16:46
Duplicate of #14003

**Closed by sioding** 2019-05-07 16:46 UTC
