### ISSUE TITLE
DoK's melee/dps green renown weapons have Blackguard class requirement

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#10634] opened 2017-10-19 16:29 UTC
First image shows the weapons (two of the same) that I was using before; both were in backpack when I logged in.

Second shows what's available to buy at vendor. They're all healing-oriented or defensive.

This is the same for T1 wc vendor and the Elite vendors; haven't checked them all though.

![pic1](https://user-images.githubusercontent.com/10598420/31782382-a9c010c2-b4f2-11e7-920d-4d5432e534fd.png)
![pic2](https://user-images.githubusercontent.com/10598420/31782414-bf0f21b6-b4f2-11e7-9759-3f84db301976.png)

**Comment by SparkyTheOld** [comment] 2017-10-21 14:45
The problem is with all the IC vendors, can't get any dps DoK Xiphos swords (but you can get armor though) for DoK of any kind, while one can still buy full dps DoK weapons and armor at emblem vendors.

**Comment by sioding** [comment] 2018-02-02 18:32
Fixed with patch from 2.2.2018

**Closed by sioding** 2018-02-02 18:32 UTC
Labels: Database, Item
