### ISSUE TITLE
[Leonine Frenzy] Proc Only on Pet White HIT

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#14104] opened 2019-05-16 17:14 UTC
Test Do on the Dummy

[Leonine Frenzy] Proc Only on Pet White HIT its a bug 

SO [Leonine Frenzy] can proc only Max 5 time in 10 sec

![leo](https://user-images.githubusercontent.com/43276959/57873427-82bfe480-780e-11e9-8b3f-7ccd018b6b21.png)
![Léonine frenzie](https://user-images.githubusercontent.com/43276959/57873440-894e5c00-780e-11e9-8ef6-94db5dec31fd.png)

Look LF proc only after a pet White HIT !

![leo 2](https://user-images.githubusercontent.com/43276959/57873534-cb779d80-780e-11e9-8c93-1bc6849ab8a5.png)

**Comment by Nfkillz** [comment] 2019-05-16 17:29
<img src="https://monosnap.com/image/Y8UXRbLChhA7vrahW35gC7pCvzzwDF"/>

**Comment by admaska2** [comment] 2019-05-17 12:01
![Leo 3](https://user-images.githubusercontent.com/43276959/57926710-3f1bb800-78ac-11e9-9757-3803b13ad939.png)

**Comment by Nfkillz** [comment] 2019-05-17 12:38
how about this bug and fix https://github.com/WarEmu/WarBugs/issues/13442 Or it was fixed by decreasing icd lol

**Comment by Nfkillz** [comment] 2019-05-17 12:47
and why internak cooldown of LF is 0.5s or 1s? it should be 2 sec. Cause cooldown was reduced in patch 04.11.2017
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23732 
<img src="https://monosnap.com/image/9Lvml95CFaYnZ2lZdRLrK2OFTAgdHr"/>
but this patch was revert in sentember 2018

**Comment by grunbag** [comment] 2019-05-18 06:46
Working as intended until WL balance thread is over

**Closed by grunbag** 2019-05-18 06:46 UTC
Labels: Ability
