### ISSUE TITLE
Quest accepted, available and complete markers on npcs don't seem to work properly

### ISSUE THREAD

**Issue by Asderas27** [WarEmu/WarBugs#16941] opened 2020-05-24 13:29 UTC
Quest markers are not showing properly on npcs.
The main locations where it is happening is in scenarios and the sc quest completion npc.

**Comment by Kaelang** [comment] 2020-05-24 13:39
Hi - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16910.

**Closed by Kaelang** 2020-05-24 13:39 UTC

**Comment by Asderas27** [comment] 2020-05-24 13:43
Oh my bad
