### ISSUE TITLE
Sinister Schythe Alt App not working

### ISSUE THREAD

**Issue by 13jack13** [WarEmu/WarBugs#5195] opened 2016-04-05 18:03 UTC
If you try to use the Alternate appearence of the Schythe on a (example) Martial Direblade, after the ok doesn't slot it and doesn't change it. 

Already try with other weapons. Same problem. So far only with the Schythe.

http://i63.tinypic.com/2wdw0uf.jpg

**Comment by Evildoor** [comment] 2016-04-05 18:21
Because Scythe is an axe, and you have sword.

**Comment by 13jack13** [comment] 2016-04-05 21:26
Ok, but before I did it with the Renown medals axe and the direblade of the lady. Or passwatch deathaxe and 2h sword. Thought wasn't a problem.

**Comment by Evildoor** [comment] 2016-04-06 05:22
Such possibility was removed at some point because of certain problems which lead to introduction of item type check.

**Comment by 13jack13** [comment] 2016-04-06 08:49
[http://i63.tinypic.com/2wdw0uf.jpg](url)

No. I already wrote I try with other weapon types. It doesn't work. Here you have the proof.
I am wielding a martial axe, axe item type, and whel I try to slot the Schythe you can read the error msg in the chat.

**Comment by Evildoor** [comment] 2016-04-06 10:06
"Main Hand or Off Hand". Must be "Main Hand" only, like Scythe.

**Comment by 13jack13** [comment] 2016-04-06 10:13
So basically only Swords, since axes are all for Mara as well and all support offhand. Can you give a solution or fix it, since all the other weapons work fine?

**Comment by Evildoor** [comment] 2016-04-06 13:27
Read my comment to #1703 for a workaround.

**Comment by 13jack13** [comment] 2016-04-06 13:30
I try that as well before even using the bugtracker :D

Believe me, bro. It just doesn't fit :D

**Comment by Evildoor** [comment] 2016-04-06 13:33
No, i don't believe you.
![chosen_001](https://cloud.githubusercontent.com/assets/11015074/14318400/503d400c-fc15-11e5-9bb6-a53d58d0bdbc.jpg)

**Comment by 13jack13** [comment] 2016-04-07 06:29
What weapon did you use in the beginning?

**Comment by 13jack13** [comment] 2016-04-07 06:47
I mean, an axe only main hand item type. Because according to what you told me, this has to be the starting item for having that appearance. As you can see by my first screen, on vendor weapons is not working. Just read the chat message.

**Comment by Evildoor** [comment] 2016-04-07 08:24
I can equip main hand only axe, apply Scythe to it, and equip main hand / off hand axe before confirming. Or i can equip main hand / off hand only axe, apply main hand / off hand axe to it, and swap the latter with Scythe in inventory before confirming.

**Comment by 13jack13** [comment] 2016-04-07 09:47
Ok i see what you mean, but can't apply on the weapons I wanted. For example if I have a direblade with no aa supported, there is no chance with this trick to make it a Sinister Scythe. I made it with the two Axes. 

Looks a bit ridiculous though that you can't simply give an axe another axe appearance, when both are one-handed weapons

**Comment by Evildoor** [comment] 2016-04-07 11:10
> Ok i see what you mean, but can't apply on the weapons I wanted. For example if I have a direblade with no aa supported, there is no chance with this trick to make it a Sinister Scythe. 

Because of different types, axe and sword. Some time ago it was possible to apply AA in such case as long as you could wield both weapons, but it was disabled because of certain problems.

> Looks a bit ridiculous though that you can't simply give an axe another axe appearance, when both are one-handed weapons

Well, thanks Mythic for retarded decisions, as always. This workaround is the best we have.

Closing as not a bug.

**Closed by Evildoor** 2016-04-07 11:10 UTC
Labels: Dubious
