### ISSUE TITLE
Booted to Select screen upon joining Scenario 

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#13406] opened 2019-02-19 07:05 UTC
![snaptz_003](https://user-images.githubusercontent.com/25346641/52996202-bd370280-3414-11e9-8ef0-2ac9b7e01d87.jpg)
Could only see one posted regarding this from 2015, i was in black crag when i had a scenario prompt, selecting join, kicked me to a semi half blank character select screen, a minute later i was teleported back to IC and the UI for the selection screen still remained.

**Comment by sioding** [comment] 2019-02-19 07:35
Duplicate of #11224

**Closed by sioding** 2019-02-19 07:35 UTC
