### ISSUE TITLE
Dwarfs chapter 8  tie point reward bug

### ISSUE THREAD

**Issue by Firetotem133** [WarEmu/WarBugs#18597] opened 2021-03-07 09:45 UTC
The simple tie point reward at Barin Oathsmiter is not redeemable.

As can be seen in the screenshot, the area of the simple reward is empty.

![Grogyn Dwarf Chapter 8](https://user-images.githubusercontent.com/79789043/110235761-19085180-7f32-11eb-9431-35f9fcf6b323.jpg)
![Grogyn Dwarf Chapter 8_1](https://user-images.githubusercontent.com/79789043/110235765-1dcd0580-7f32-11eb-8240-096664d28714.jpg)

**Comment by Lheana** [comment] 2021-03-21 17:44
Duplicate of #13988

**Closed by Lheana** 2021-03-21 17:44 UTC
