### ISSUE TITLE
[Bug] Raid frames not showing raid members true health - Crippling raidhealing issue

### ISSUE THREAD

**Issue by nat3s** [WarEmu/WarBugs#11811] opened 2018-05-27 15:33 UTC
I couldn't see that someone else had reported this which is odd as it's probably the biggest healing issue the server has. My original forum post can be found here:

https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=26819

Expected behavior and actual behavior:

Raid frames (default, squared, healgrid, enemies et al) should show the health of each raid member as well as indicate whether they are close to you.

Steps to reproduce the problem:

Join a warband or SC as a healer, try to heal a bit. You'll find that:

1. Health is displayed incorrectly, frame may show raid member at 40% when they're actually at 100%. Similarly will show them at 100% when actually they might be almost dead.
2. People in range are shown as out of range
3. People out of range are shown as in range.

Most evident when viewing your own name in the WB frame.

Also reproducible when when in a team within a WB which is not full.

Screenshots/Videos or archive.org evidences:

https://ibb.co/fyo3vy

I'm Defrat in the above screenshot, warband frame (Squared in this example but it's the same with them all including the default UI), shows me as out of range incorrectly.

**Comment by nat3s** [comment] 2018-05-27 15:40
Posts on the forums are suggesting this bug was introduced following a patch in November 2017. Unable to verify this myself.

**Comment by sioding** [comment] 2018-05-27 16:49
Duplicate of #11277

**Closed by sioding** 2018-05-27 16:49 UTC
