### ISSUE TITLE
Ralkuth the Rally Master

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14711] opened 2019-08-03 07:05 UTC
Expected behavior and actual behavior:
Ralkuth is missing his basic rewards. I have the impression he's also missing half of the advanced and elite rewards.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_011](https://user-images.githubusercontent.com/53320075/62408738-de934180-b5a3-11e9-8f52-f6acdf369554.jpg)
![Austherus_012](https://user-images.githubusercontent.com/53320075/62408739-de934180-b5a3-11e9-9f81-c3f1abc5f35a.jpg)

**Comment by sioding** [comment] 2019-08-03 13:23
Duplicate of #10205

**Closed by sioding** 2019-08-03 13:23 UTC
