### ISSUE TITLE
Guild Tab in game not working 

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#14952] opened 2019-09-22 04:48 UTC
Hello 
I don't know if anynone is having this issue but me, for a wile now I have had to put up with the Guild Tab in game not working like it should. Right now the only thing i seen when I open my guild tab is that I'm the only 1 in the guild and I'm the only one online. This has been gong on for 7 months now on and off. I have not been able to doing thing with the guild Tab for abo 1 week now. Can yo help me and other people is may be happening to. Here is 2 photos to show what in talking about. I am the leader of the guild also.
Thank you    
![Yogibear_001](https://user-images.githubusercontent.com/47046345/65382348-51ca5180-dcd1-11e9-8c48-b194fa8f36ae.jpg)
![Yogibear_000](https://user-images.githubusercontent.com/47046345/65382349-54c54200-dcd1-11e9-945d-67a9ba2282b8.jpg)

**Comment by sioding** [comment] 2019-09-22 16:48
Duplicate of #13377

**Closed by sioding** 2019-09-22 16:48 UTC
