### ISSUE TITLE
Witch Hunter(& Witch Elf?) Stealth breaking

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1093] opened 2015-08-15 21:40 UTC
When a ranged class starts casting a spell at me and you get into stealth before it hits or before it finishes casting the attack still goes off and knocks you out of stealth.

Possible workaround could be to add a 3-5 second grace period at the start of stealth where attacks won't knock you out of it, possibly only ranged attacked so melee could still do it, for balance.

**Comment by Evildoor** [comment] 2015-10-05 11:48
The problem here is that any direct damage (dunno about DoTs) knocks you out of stealth 100% of time - same effect if someone hits you while spamming AoE at someone else. IIRC, on live the chance was lower than 100%.

**Comment by Zealote** [comment] 2015-10-05 12:09
I seem to remember that projectiles that were in the air when you stealthed, and then hit you afterwards, did indeed break stealth. Since st direct damage always knocked you out of stealth (requiring someone to have detected you with ini), maybe it was just the same code that checked to see the type of dmg you received: if it was st dd, it broke stealth, regardless of whether the attack was initiated before you entered stealth, or after when someone detected you.

I think it'd be worth discussing changing it as it's really annoying, given it's cd, when it's immediately broken, but it's not, afaik, a bug.

**Comment by ozarmidrashim** [comment] 2015-10-20 14:29
Closing per Zealote. If it's not a bug, discuss it on the forum.

**Closed by ozarmidrashim** 2015-10-20 14:29 UTC
Labels: Ability

**Comment by Nfkillz** [comment] 2015-10-28 14:06
why closed it s a bug

**Comment by Evildoor** [comment] 2015-10-28 14:37
Uh, isn't it written above? Is it unfair that shots already in the air kick you out of stealth just as you entered it? Yes. Is it a bug? No, it is a balance issue, which should be discussed on forum.
