### ISSUE TITLE
Magnet inge

### ISSUE THREAD

**Issue by Diezhix** [WarEmu/WarBugs#13578] opened 2019-03-09 08:14 UTC
Hi, yesterday i was magneted inside a keep
1st time i was blocked in the door and the second inside. 

Thx

![Armadha_001](https://user-images.githubusercontent.com/38187436/54068283-7f770e00-424b-11e9-93eb-e1a576ffb3bd.jpg)

**Comment by sioding** [comment] 2019-03-09 12:59
Duplicate of #12350

**Closed by sioding** 2019-03-09 12:59 UTC
