### ISSUE TITLE
Renown - Improved Flee is not working properly.

### ISSUE THREAD

**Issue by Althesian** [WarEmu/WarBugs#19102] opened 2021-06-08 21:29 UTC
Once learned from the trainer, it will do exactly like stated on the tooltip. once zoned to another area, both improved flee I and improved flee II do not apply anymore.

**Comment by xpander69** [comment] 2021-06-09 03:41
yeah. duplicate of https://github.com/WarEmu/WarBugs/issues/18241

**Closed by xpander69** 2021-06-09 03:41 UTC
