### ISSUE TITLE
BB/BE

### ISSUE THREAD

**Issue by Jonees123** [WarEmu/WarBugs#13875] opened 2019-04-13 22:48 UTC
Majority of the puddles The Bile Lord spawns aren't visible, I don't have any evidence, but I did BB twice today and same thing happened both times.
I also killed Korthuk the Raging twice today and didn't get the kill for the quest, but both times we got a lag spike in middle of the kill, so that's maybe why.
(I had all ability effects on and other puddles were showing just fine and for Korthuk the Raging no one had lockouts the first kill and I was the only one with lockouts the second time.)
![kuva](https://user-images.githubusercontent.com/47939256/56086073-ab437000-5e57-11e9-9a38-525db850e344.png)

**Comment by sioding** [comment] 2019-04-14 05:23
Duplicate of #13865

**Closed by sioding** 2019-04-14 05:23 UTC
