### ISSUE TITLE
WE's kisses proc from siege weapons or damaging potions.

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#10948] opened 2017-12-03 18:47 UTC
As title says.

![mashka_034](https://user-images.githubusercontent.com/16030337/33528559-86da704e-d873-11e7-8cb5-23bc321e3fb4.jpg)

**Comment by sioding** [comment] 2017-12-03 20:10
Duplicate of #10807

**Closed by sioding** 2017-12-03 20:10 UTC
