### ISSUE TITLE
EU Lag (pet death)

### ISSUE THREAD

**Issue by soliticks** [WarEmu/WarBugs#12430] opened 2018-10-08 18:21 UTC
Hey team, I've been noticing that EU prime has been increasingly laggy lately. Just wanted to report that pets die instantly during every spike whether they are getting hit or not. You can even replicate this while mounted and riding past a keep at times.

**Comment by sioding** [comment] 2018-10-08 18:53
We know that - and wir working on it. Since the lag itself not that reproducable i do close this report. Be sure we are working on it - cause we do play also. :)

**Closed by sioding** 2018-10-08 18:53 UTC
