### ISSUE TITLE
Wyrmbreaker Quest Bugged on last step

### ISSUE THREAD

**Issue by Sorutz** [WarEmu/WarBugs#17454] opened 2020-08-06 16:51 UTC
**Expected behavior and actual behavior:**
On the last part of the Epic Quest Wyrmbreaker there are 3 parts.
1. You have to enter The Senthoi Pool PQ.
2. Use an item quest called Summonglass to summon the dragon.
3. Defeat the Dragon Eldraugnir The Black. 

There are 2 errors on the actual Behavior:
1. When you enter that PQ it doesn't count on your quest. 
2. When you use the summonglass it counts on your quest but the dragon is not summoned, so u can't kill him.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2020-08-06 16:59
Duplicate of #12982

**Closed by Lheana** 2020-08-06 16:59 UTC
