### ISSUE TITLE
Scenario entry pushes to Altdorf with UI bug

### ISSUE THREAD

**Issue by Chezyban** [WarEmu/WarBugs#11799] opened 2018-05-24 03:49 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Entered Scenario reikland factory(clicked enter scenario button)
After load screen am in Altdorf, UI gone and replaced with buttons from character select screen.

Steps to reproduce the problem:
Happened twice on joining Scenarios.

Screenshots/Videos or archive.org evidences:
![chezyban_025](https://user-images.githubusercontent.com/39578032/40463540-d9ed5c28-5ee3-11e8-86f6-cd851bc9e5e8.jpg)

**Comment by sioding** [comment] 2018-05-24 07:28
Duplicate of #11224

**Closed by sioding** 2018-05-24 07:28 UTC
