### ISSUE TITLE
Teleportation?

### ISSUE THREAD

**Issue by stuffrish** [WarEmu/WarBugs#711] opened 2015-05-01 12:02 UTC
![stuffrish_001](https://cloud.githubusercontent.com/assets/9819354/7429901/73e041e8-f00a-11e4-9e9d-e6b244fdf24b.jpg)

I was in T1 RvR and was standing on top of a witch hunter while fighting. Then suddenly teleported to the order base (image) then died of guards. 

Afterwards i spawned like usual in the destru base and all was well.

**Comment by Evildoor** [comment] 2015-09-25 11:45
I do believe this was caused by super knockback bug, which was fixed. Closing.

**Closed by Evildoor** 2015-09-25 11:45 UTC
