### ISSUE TITLE
Attacking ram/players through keep door

### ISSUE THREAD

**Issue by Brizhul** [WarEmu/WarBugs#16511] opened 2020-04-26 05:43 UTC
**Expected behavior and actual behavior:**
You shouldn't be able to auto-attack targets through doors. By doing this, you could literally kill a ram safely through a door.

**Steps to reproduce the problem:**
Select a ram or player as a target, then go to the keep door (with the target on the other side) and auto-attack them through the door. (In my case, I used abilities such as Brutal Pounce and Leonine Frenzy to begin the auto-attack startup)

**Testing Screenshots/Videos/Evidences (always needed):**
I do not have screenshots, but it is very easy to replicate.

**Comment by Kaelang** [comment] 2020-04-26 12:25
Duplicate of https://github.com/WarEmu/WarBugs/issues/10242.

**Closed by Kaelang** 2020-04-26 12:25 UTC
