### ISSUE TITLE
Pet attack command resets NPC position

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#952] opened 2015-07-10 10:28 UTC
If you command your pet (squig in this case) to attack and you do not attack yourself, every time you press the attack command the NPC is getting teleported back to the place he spawned at. You can solo champs like this easily without them ever touching your squig, just by constantly resetting their position.

**Comment by magter3001** [comment] 2015-07-12 00:17
Since this is a squig pet issue I will add this.

Spiked squig doesn't receive the correct value of stats from your equipped items. The other squigs seem to get the correct bonus from the items. The Spiked squig for example is supposed to get 150% bonus to ballistics from your gear but only receives 31 for me.

**Comment by Evildoor** [comment] 2015-09-25 17:22
Seems to be fixed, since i cannot reproduce it. Closing.

**Closed by Evildoor** 2015-09-25 17:22 UTC
