### ISSUE TITLE
mass bought dev. gloves for salvaging

### ISSUE THREAD

**Issue by kandusemig** [WarEmu/WarBugs#11255] opened 2018-02-04 13:57 UTC
i wanted to raise my salvaging skill , so i shift "mass" bought 20 dev WE gloves.
 i had enough space in my bag for it, cost was 20x 8 meds - i lost the meds, but didt get the items.
Sorry if already know issue

i was on my WE called Fraekkefrida

**Comment by sioding** [comment] 2018-02-04 15:31
Duplicate of #10703

**Closed by sioding** 2018-02-04 15:31 UTC
