### ISSUE TITLE
Event: Keg's End from december 2018

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13934] opened 2019-04-22 13:19 UTC
**Expected behavior and actual behavior:**
Influence rewards are once again available from the keg's end event Knight in Altdorf. This includes the keg tapper which gives a stat boost for 60 days.

**Comment by sioding** [comment] 2019-04-22 13:20
Duplicate of #13927

**Closed by sioding** 2019-04-22 13:20 UTC
