### ISSUE TITLE
Gaining renown in PQ

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#12451] opened 2018-10-14 19:02 UTC
Just ran some Ruin farming in Eataine (Da Orcwerks) and we were getting +20 renown for every PQ kill.

**Comment by Kweedko** [comment] 2018-10-15 03:50
sure for every, not for heals after kills.

**Comment by sioding** [comment] 2018-10-15 17:58
could not reproduce that. My best guess is that someone in the group joins fresh from the rvr into the group and the heals getting your some renown. Since we can not reproduce it - we can not fix something. So thanks for the report - but do close it now.

**Closed by sioding** 2018-10-15 17:58 UTC
