### ISSUE TITLE
Potion making gone wrong

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#12550] opened 2018-11-05 22:53 UTC
Expected behavior and actual behavior:
I was crafting lvl 20 potions for my fellow greenskins, I used as vial "Artisan glass vial"+"Worn feline tooth"+"Pristine Arboreal resine"+"Taut Gobswort"x2

I expected to create a 2 hour potion(I've seen them, I know they exist ingame) but I got this error:
[https://i.imgur.com/uQlJiae.jpg](https://i.imgur.com/uQlJiae.jpg)

Also, apotecary menu got completely unsuable and had to reload the game to use it again.

**Comment by sioding** [comment] 2018-11-06 12:49
Duplicate of #4118

**Closed by sioding** 2018-11-06 12:49 UTC
