### ISSUE TITLE
Declare Anathema - still parryable

### ISSUE THREAD

**Issue by dadkkak** [WarEmu/WarBugs#14870] opened 2019-08-31 07:01 UTC
Just happened to me with a Choppa. Declare Anathema was parried, didn't devs said it shouldn't be? Please look at it, thanks

**Comment by sioding** [comment] 2019-08-31 08:18
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2019-08-31 08:18
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by dadkkak** [comment] 2019-08-31 10:14
![DA-parried](https://user-images.githubusercontent.com/47615878/64062613-c3d6db80-cbe8-11e9-97bf-0b0983b5b195.jpg)

Simple as that, a choppa with high parry chance simply parried it (it was in Thunder Mountain)

**Comment by dadkkak** [comment] 2019-08-31 10:53
Also, it can be blocked. Pic attached

![2](https://user-images.githubusercontent.com/47615878/64062976-59289e80-cbee-11e9-8259-4251c087f786.jpg)

**Comment by Nfkillz** [comment] 2019-10-08 00:57
witch elf has the same issue
<img src="https://monosnap.com/image/pMzmZQUF8nMQmpUSZrXViOklFbZkrT"/>

**Comment by grunbag** [comment] 2020-04-05 09:54
Fixed with next patch

**Closed** 2020-04-19 13:35 UTC
Labels: Ability, Fix Pending
