### ISSUE TITLE
Inventory visualisation bug with talisman making

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#8993] opened 2017-01-26 11:28 UTC
To reproduce this you need more than one stack of containers in your bag.
Steps:
1) Have both tali window and inventory opened.
2) Select container to use.
3) As you release the mouse button you'll see that the first container stack now has quantity of all stacks summed up.

![exhibit1](https://cloud.githubusercontent.com/assets/25364850/22329648/3fbb6712-e3d3-11e6-9c22-a4a64f05ad8a.jpg)
![exhibit2](https://cloud.githubusercontent.com/assets/25364850/22329649/3fbd1d3c-e3d3-11e6-8db2-09c3671a0c17.jpg)

**Comment by d3BugErr** [comment] 2017-01-26 11:42
Quick addition: repeating steps 2-3 in succession will continue to increase first stack size.

**Comment by Luth-RoR** [comment] 2017-01-26 13:46
Tried and can't reproduce it.

**Comment by d3BugErr** [comment] 2017-01-26 14:13
Well, seems that dat's my bad. Too used to my addon stack. Further testing elicited that it is an EXCraftX  addon side effect. Not repeatable with standard UI and standard container selection via dragging to tali window.
Sorry for inconvenience.

**Comment by Luth-RoR** [comment] 2017-01-26 14:15
Closing then.

**Closed by Luth-RoR** 2017-01-26 14:15 UTC
Labels: Could Not Reproduce
