### ISSUE TITLE
Public Quest - Grimbeard Station - Stage 2

### ISSUE THREAD

**Issue by DominoPrime** [WarEmu/WarBugs#11817] opened 2018-05-29 21:09 UTC
When i was doing the Grimbeard Station public quest, specifically the second stage with the sappers, the Hammerstriker Ironbreakers and Apprentice Railhand kept attacking me, nearly killing me once and causing me to fail the public quest.

**Comment by NorKalli** [comment] 2018-05-29 21:10
Order mobs attack order players on stage 2

**Comment by NorKalli** [comment] 2018-05-29 21:11
![buggy](https://user-images.githubusercontent.com/19868634/40685846-3263b4aa-634a-11e8-92f9-7eb5336c97d8.jpg)

**Comment by Lheana** [comment] 2020-02-27 21:06
Duplicate of #9880

**Closed by Lheana** 2020-02-27 21:06 UTC
Labels: Public Quests
