### ISSUE TITLE
Fort, no loot roll for reserved

### ISSUE THREAD

**Issue by Krakybear** [WarEmu/WarBugs#13608] opened 2019-03-11 16:44 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
First of, Defenders spawned on top of the fort, where they usually spawn during stage 2.
They spawned there in stage 3 as well. Few if any went to prison.
We kept them there by aoe spamming on spawn, while the lord went down.
When lord went down, no loot roll happened for people with reserved, but people who got in after reserved reported getting loot. People with reserved didn't get any invaders or rp either.
I specifically got 3k renown, a vanquishers medallion and a Seal of the Exemplar. Not the typical fort loot.
This has happened before to me as well, for the last 3 forts. No loot roll in the end, and no medallions.

**Steps to reproduce the problem:**
Seems to be every fort now, keep an eye on the next one. This has happened in Fell landing, Reikwald, and lastly Butchers pass.

**Screenshots/Videos or archive.org evidences:**
Did not grab any screenshots, was busy trying to figure out what happened.

Here is a screenshot by someone else showing some contribution
https://cdn.discordapp.com/attachments/329292495336767488/554703837147955206/unknown.png

**Comment by Krakybear** [comment] 2019-03-11 16:52
Did some thinking, it may be due to reserved people not participating in the "PQ" so to speak, they are just entering the zone.

**Comment by sioding** [comment] 2019-03-11 17:00
Duplicate of #13605

**Closed by sioding** 2019-03-11 17:00 UTC

**Comment by Krakybear** [comment] 2019-03-11 17:27
Sorry about posting a dupe then, just figured that since it happened in a different fort, from different faction I should post it as another issue! :)

**Comment by sioding** [comment] 2019-03-11 17:45
All fine - but the technical thing behind is the same so i merged it into one report. better for the dev who fixes it
