### ISSUE TITLE
No renown and medaillons in Fort - Zealot Bug

### ISSUE THREAD

**Issue by FCT-ROR** [WarEmu/WarBugs#16681] opened 2020-05-05 21:50 UTC
**Expected behavior and actual behavior:**
2 days ago i was in 2 forts <see screens> The announcement was that the contribution system was not working correctly and we should report the bug when something happend. But i got in in both forts and didnt got any contribution no Renown tick and no invader Medallions. In 1 fort (empire) i was killed and send back to an island?
Furthermore i could not use abilities it didnt show cooldowns and didnt show mouseovers. Even the pots didnt show the stats on it. Once i used it i could see it on my character.

**Steps to reproduce the problem:**

I never have mouseovers of items anymore and yes i checked everything off on etc in targetting tab.

**Testing Screenshots/Videos/Evidences (always needed):**

I was unable to make screens. but i hope Fctt my destro character gets the medallions and renown.

**Comment by Kaelang** [comment] 2020-05-05 21:53
Duplicate of https://github.com/WarEmu/WarBugs/issues/16409.

**Closed by Kaelang** 2020-05-05 21:53 UTC
