### ISSUE TITLE
Black Orc "You Wot!?!!!" 

### ISSUE THREAD

**Issue by Bladepower** [WarEmu/WarBugs#14687] opened 2019-07-29 12:14 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Should Increase Armor and Resistances by 30% plus defences by 15%
Instead increase just Armor and defences but not the Resistances.

**Steps to reproduce the problem:**

Happens in every area, both PVE and RVR when using the skill

**Testing Screenshots/Videos/Evidences (always needed):**

2 screens before and after the use of You Wot!?!!!
![Bladeboss_038](https://user-images.githubusercontent.com/53433798/62047570-cb9c0c80-b245-11e9-94ad-f0fafa53f3e2.jpg)
![Bladeboss_039](https://user-images.githubusercontent.com/53433798/62047571-cc34a300-b245-11e9-85cd-6444ed8e9dfb.jpg)

**Comment by sioding** [comment] 2019-07-29 12:22
Duplicate of #13241

**Comment by sioding** [comment] 2019-07-29 12:25
After a talk with @grunbag i reopen this one cause it can get fixed.

**Comment by grunbag** [comment] 2019-07-31 07:22
fixed with next patch

**Comment by sioding** [comment] 2019-08-03 13:33
Fixed with patch from 03.08.2019

**Closed by sioding** 2019-08-03 13:33 UTC
Labels: Ability, Fix Pending
