### ISSUE TITLE
Missing gear after the patch - 5/6/20

### ISSUE THREAD

**Issue by MordecaiEth** [WarEmu/WarBugs#16697] opened 2020-05-06 22:58 UTC
**Expected behavior and actual behavior:**  Gear is missing.

**Steps to reproduce the problem:** The problem is ongoing.

Today I logged in after the new patch and saw my black orc with no sovereign shoulders on - they were equipped when I logged out last night on 5/5/20 it is also not in my bag.

I checked the armory and searched up my character. They still show as if they are equipped.

[https://youtu.be/4ZnWEBNRwOc](url)
(Video is of me refreshing the armory and shoulders still shown as equipped. I am also playing the account to verify that they aren't equipped and are gone.)

![wtf my shoulder](https://user-images.githubusercontent.com/64931458/81236093-6fcb9480-8fca-11ea-9dcd-0ea1c8620d1a.jpg)

![war-64](https://user-images.githubusercontent.com/64931458/81236229-b620f380-8fca-11ea-8655-0114b5470ae3.jpg)

I've also used the "Repair" option in the launcher after the patch today. No dice.

**Comment by Kaelang** [comment] 2020-05-06 23:08
Duplicate of https://github.com/WarEmu/WarBugs/issues/16688.

**Closed by Kaelang** 2020-05-06 23:08 UTC
