### ISSUE TITLE
Gork Sez Stop in PvE

### ISSUE THREAD

**Issue by Palitelj** [WarEmu/WarBugs#12931] opened 2018-12-23 20:22 UTC
Shamy M1 in PvE, I noticed while doing dungeons shamy M1 is working different then in PvP. When I hit morale on bosses if they are not moving morale will procing like they are moving. Also when they start moving morale stop working. Seems it is completly different in PvE.

![skkar_004](https://user-images.githubusercontent.com/21026133/50387284-b2077500-06f8-11e9-8318-077f4a5dbaca.jpg)
![skkar_005](https://user-images.githubusercontent.com/21026133/50387286-b6cc2900-06f8-11e9-8af4-9117d568b99d.jpg)

2 pictures where bosses were stacionary

**Comment by sioding** [comment] 2018-12-23 20:40
Duplicate of #1879

**Closed by sioding** 2018-12-23 20:40 UTC
