### ISSUE TITLE
Ram Behaviour

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13363] opened 2019-02-14 06:59 UTC
Yesterday during high population rvr action in TM one problem, but in two a bit different instances were seen:
1) it was lagging backwards, while approaching inner keep door (player tries to pull it but it starts lagging and in the end teleporting backwards further away).
2) when it was approaching closer to door - it could not be moved under AOE, it seemed as if sever was not able to process if carier was trully dehorsed by so much AOE happening and preemptively stoped the ram on border of AOE hellpit. 
What backs up conclusion made in 2nd point is that third ram (first two died due to mentioned problems) was in the end put to door, but to do that carrier had to circle around main area of AOE.

With Forts on horizon this problem can be crucial as rightly placed AOE can deny ram approach when it should not.

Described problem partly adressed in now closed ticked #10773 , sorry if this one can be considered as duplicate.

**Comment by sioding** [comment] 2019-02-15 17:58
I reactivate the original one. Thanks for the report @Rockalypse 
Duplicate of #10773

**Closed by sioding** 2019-02-15 17:58 UTC
