### ISSUE TITLE
Dwarf Chapter Eight. Missing Basic Rewards from PQ Inf bar.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10869] opened 2017-11-19 10:02 UTC
Missing basic rewards for Chapter Eight Dwarf. 

(Sorry not really sure what else to put in here do to the title saying it.) 

-Nolan

**Comment by sioding** [comment] 2017-11-19 10:12
Duplicate of #10005

**Closed by sioding** 2017-11-19 10:12 UTC
