### ISSUE TITLE
Receiving the wrong bag and its not open able

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10929] opened 2017-11-29 12:04 UTC
I won a gold bag last night but today in the mail I found a white bag that I cannot open, every other bag in my inventory is open able with choice of loot, this mysterious white bag shown in the screenshot should be a gold bag and I cannot open it or do anything with it, its just there in my bag taking up space xD.

Screenshot: 
https://i.imgur.com/ECMkrhh.jpg

**Comment by sioding** [comment] 2017-11-29 17:16
Duplicate of #10695

**Closed by sioding** 2017-11-29 17:16 UTC
