### ISSUE TITLE
jevelry

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#5071] opened 2016-03-27 17:11 UTC
Hi i have WH lvl 16 and i am not able to use more than 2 same jevels. I buyed 4 s+ws jevels and i can put just two of them.

**Comment by Tiggonos** [comment] 2016-03-28 13:10
wich jewels in particular? screeshot?

**Comment by genisaurus** [comment] 2016-03-28 23:43
Going to bet that this is not a bug. Those jewelry pieces are likely flagged as unique, meaning you can only have 1 equipped at a time.

**Comment by Kouba85** [comment] 2016-03-29 17:18
so i must change what i wrote before i can use just one jevel from vendor (same type)
![kubajs_000](https://cloud.githubusercontent.com/assets/15944509/14116990/d05fe49e-f5e2-11e5-
86e8-86c65a9dfcfd.jpg)

![kubajs_001](https://cloud.githubusercontent.com/assets/15944509/14117019/04760344-f5e3-11e5-9c8c-cb421919c069.jpg)

**Comment by Kouba85** [comment] 2016-03-29 17:19
but i can put another
![kubajs_003](https://cloud.githubusercontent.com/assets/15944509/14117061/2c53a4c0-f5e3-11e5-8a7c-4701cce9b57c.jpg)

**Comment by Kouba85** [comment] 2016-03-29 17:20
same when i use for example toughness jevel from renown vendor

**Comment by genisaurus** [comment] 2016-03-29 17:21
Correct. A "unique" item means that you can only have one of it equipped. This is not a bug, so I'm closing the issue.

**Closed by genisaurus** 2016-03-29 17:21 UTC
Labels: Confirmation Request, Item

**Comment by Kouba85** [comment] 2016-03-29 20:22
my second character have two jevels unique equipped 
![snorrri_034](https://cloud.githubusercontent.com/assets/15944509/14122592/b6ab4b1e-f5fc-11e5-8431-7f58428ef5e7.jpg)

**Comment by Evildoor** [comment] 2016-03-30 07:11
Because they were equipped before the patch was implemented?

**Comment by Kouba85** [comment] 2016-03-30 07:53
oh so sorry for spaming and keep the good work and sorry for my bad english.
