### ISSUE TITLE
Shadowlands PQ The Griffon Gate

### ISSUE THREAD

**Issue by Shemrock3267** [WarEmu/WarBugs#11239] opened 2018-01-31 12:42 UTC
To proceed on the Epic Quest "A Lord's Game" i have to kill _8 Griffon Defenders_ and _8 Griffon Guards_ at Public Quest "The Griffon Gate" (Location: **Shadowlands**)

**Expected behavior and actual behavior:**

**Expected**: Complete at least first stage of this PQ, it will then spawn so badly needed NPCs. 

**Actual**: PQ bugged on the first stage with no PQ's NPC "Eagle Claw"(balista) present in the required zone  (from what i can recall they were situated on the marked areas: second screenshot).

Steps to reproduce the problem:
Come over to observe it is actually bugged.

Screenshots/Videos or archive.org evidences:
![nobguzzlah_000](https://user-images.githubusercontent.com/10697124/35623416-3f56f734-0694-11e8-8725-afa4b8f78724.jpg)
![nobguzzlah_001](https://user-images.githubusercontent.com/10697124/35623417-3f7f0d78-0694-11e8-9785-ee762a048915.jpg)
![nobguzzlah_002](https://user-images.githubusercontent.com/10697124/35623418-3f9f34fe-0694-11e8-9ae5-167339cb816b.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-01-31 13:42
Duplicate of #10862

**Closed by sioding** 2018-01-31 13:42 UTC
