### ISSUE TITLE
Neverending Agony stacking again with Choppafasta

### ISSUE THREAD

**Issue by Focusthehealer** [WarEmu/WarBugs#20376] opened 2022-08-29 06:04 UTC
Good morning, I was playing orvr 30 mins ago and I noticed that infernal wave became spammable again with choppafasta.

https://www.youtube.com/watch?v=3W7WNVG6Gk0

**Comment by Haojun-Phalanx** [comment] 2022-08-29 09:58
From the same patchnotes 30/09/2017 https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117#p258569

_Black Orc

Cant Hit Me moved back to original place of 9 pts
Down Ya Go moved to original place of 13 points
**Down Ya Go now grants Chop fasta to your group reducing cooldowns by 5seconds for 10s so long as they are within 100ft**

Abilities unaffected by this cooldown reduction effect are as follows:
- Rending Blade
- Da Waaagh! Is Coming
- Shades of Death
- Infernal Wave is affected but will not be reduced to less than 5s if using the tactic Neverending Agony._

NA changed when BO had CD decreaser; since BO CD decreaser is gone, there is no reason NA doesn't stack with CF again.

**Comment by D4W0lf** [comment] 2022-09-01 07:24
https://github.com/WarEmu/WarBugs/issues/12437

Fixed in 2019... But today the same thing is not a bug ?

**Comment by D4W0lf** [comment] 2022-09-01 07:28
https://github.com/WarEmu/WarBugs/issues/16746

Kaelang commented on May 9, 2020

This is intended.

**Comment by lilimx** [comment] 2022-09-03 20:26
fixed with patch 03/09/2022

**Closed by lilimx** 2022-09-03 20:26 UTC
Labels: Ability
