### ISSUE TITLE
RvR Influence Not Given from Zone Lock

### ISSUE THREAD

**Issue by Axerker** [WarEmu/WarBugs#11023] opened 2017-12-18 14:41 UTC
**Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.**
_No other results found in search._

**Expected behavior and actual behavior:**
_When a Zone locks (on win or loss), chat log shows you receive an influence reward. This reward is currently not being applied to your Tier Influence, as it should. This was noticed on Saturday, but current influence levels would give evidence that this has not worked for at least several weeks. (I currently have no Tiers even to the first reward unlock, which is a very low amount of influence. This is causing players to miss out on rewards in a timely fashion - they can still achieve them through the few influence points from holding Battle Objectives, but it will take much, much longer - when the gear received is relatively unusable due to having better gear by then_

**Steps to reproduce the problem:**
_Go into an RvR Zone and check your Influence for that Zone prior to Zone locking. On lock, check Chat log to see how much Influence should have been received, and check Influence bar to see that no influence was actually received._

**Screenshots/Videos or archive.org evidences:**
_None taken at this time. I will attempt to take a video on next Zone lock._

**Comment by sioding** [comment] 2017-12-18 16:48
Duplicate of #9438

**Closed by sioding** 2017-12-18 16:48 UTC
