### ISSUE TITLE
Consume Strength

### ISSUE THREAD

**Issue by Griffithfalcon** [WarEmu/WarBugs#16444] opened 2020-04-20 12:45 UTC
It doesn't give strength.
![CS](https://user-images.githubusercontent.com/60180313/79753764-22d79500-831f-11ea-9e78-e2fd37a2c0e9.png)

![nocons](https://user-images.githubusercontent.com/60180313/79753018-ea838700-831d-11ea-8b31-b166707e12dc.png)
![cons](https://user-images.githubusercontent.com/60180313/79753030-ee170e00-831d-11ea-800f-df337fff6c29.png)

UPD. It DOES give str in pvp, it DOESNT give str in pve. tested on mobs in eataine and on sc's.

**Comment by Kaelang** [comment] 2020-04-20 12:48
Adding this as supporting evidence and tagging.

![image](https://user-images.githubusercontent.com/60117106/79753281-8d7fd500-830d-11ea-8499-99720e73a0f3.png)

**Comment by Kaelang** [comment] 2020-04-20 12:59
I've just tested this using .getstats and the skill is working as intended. It is likely the character stat screen bugged out. You can type .getstats before you use the ability, close the window, and then .getstats once you have the buff.

**Comment by Griffithfalcon** [comment] 2020-04-20 13:04
> I've just tested this using .getstats and the skill is working as intended. It is likely the character stat screen bugged out. You can type .getstats before you use the ability, close the window, and then .getstats once you have the buff.

I retested it, in pvp it shows in stats, in pve doesnt, dont know if in pve its just visual bug or not.

**Comment by Kaelang** [comment] 2020-04-20 13:11
Here's two .getstats before and after using the ability on a PvE target.

![getstats 1](https://user-images.githubusercontent.com/60117106/79755304-d422fe80-8310-11ea-8614-5882d6635a09.png)
![getstats 2](https://user-images.githubusercontent.com/60117106/79755312-d5ecc200-8310-11ea-8049-3411a9ff1060.png)

Are you closing the .getstats window and re-opening before and after the buff is applied? Also make sure you're your defensive target.

**Comment by Vayra** [comment] 2020-04-20 13:18
Also, on this screenshot, what potions do you have equipped? Pretty sure str pots do not stack with Consume Strength.

**Comment by Griffithfalcon** [comment] 2020-04-20 13:51
ooooooh, i didnt know.

**Comment by Kaelang** [comment] 2020-04-20 14:19
Was you using strength pots in the test? Please can you retest without the strength pot active.

**Comment by dalen** [comment] 2020-04-22 07:58
Without str pot this does give you strength, on the stat doll window as well. So I'll close this

**Closed by dalen** 2020-04-22 07:58 UTC
Labels: 2 Week Ultimatum, Confirmation Request
