### ISSUE TITLE
Punishing Knock ( IB tactic) does not work

### ISSUE THREAD

**Issue by Romgaard** [WarEmu/WarBugs#17212] opened 2020-06-24 11:29 UTC
Ironbreaker tactic "punishing knock" is bugged

Been running this tactic for several months now. I mainly play scenarios.
Debuffing the enemy healers and i can see they have the healdebuff on them.
There does not seem to be any difference in the heal output with or without the healdebuff

**Steps to reproduce the problem:**
Log in 
Create an ironbreaker ( or choose an excisting one)
Choose tactic " punishing knock" 
drag into your tacticsbar
Go into scenario ( or befriend an enemy healer)
Hit them with " inspiring attack"
Check if they have the healdebuff on them
watch the heal output

repeat without "punishing knock"
watch the healoutput

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by funnytroll** [comment] 2020-06-24 12:30
For me its worked.
Mb you have this problem too 
https://github.com/WarEmu/WarBugs/issues/15857

**Comment by Kaelang** [comment] 2020-06-24 12:31
Duplicate of https://github.com/WarEmu/WarBugs/issues/15857

**Closed by Kaelang** 2020-06-24 12:31 UTC

**Comment by Romgaard** [comment] 2020-06-24 12:50
this is NOT a duplicate..even if i have it slotted in the first slot, it still does not healdebuff

**Comment by Kaelang** [comment] 2020-06-24 12:52
It is a duplicate - there is an issue with Punishing Knock - read the reports and comments on the merged report. 

Additional reports that have been merged:

https://github.com/WarEmu/WarBugs/issues/16313
https://github.com/WarEmu/WarBugs/issues/16148

There's an evident problem with the tactics, and how they're setup with IB's.

So I've merged them.

**Comment by Romgaard** [comment] 2020-06-24 13:05
ah ok, my bad..sorry for the inconvience

**Comment by Kaelang** [comment] 2020-06-24 13:05
No worries - easily missed.
