### ISSUE TITLE
'Special Delivery' Quest - Order - Talabecland

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#16048] opened 2020-03-20 09:52 UTC
![Izikael_000](https://user-images.githubusercontent.com/62262476/77152608-37aad980-6a90-11ea-93ad-882661e91051.jpg)
Special Delivery - Quest, Talabecland

**Expected behavior and actual behavior:**
Expected - able to find 'iron box' to progress quest, cant, Smithy mob does not drop, scoured entire area
Actual - Expected item does not exist

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2020-03-20 17:57
Duplicate of #15451

**Closed by Lheana** 2020-03-20 17:57 UTC
