### ISSUE TITLE
Gamecrash at specific spot in altdorf

### ISSUE THREAD

**Issue by Xiquid** [WarEmu/WarBugs#12390] opened 2018-10-01 19:56 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The game should not be impacted, but one gets a disconnect for no actual reason.

Steps to reproduce the problem:
1. Travey to altdorf.
2. Move to Location: 20000/45000 (Map coordinates).
3. The moment one passes the corner the game crashes.
(4. In approximate 50% of the cases one gets another crash after logging in.)

Tested by more than 10 different players. 

This is literally a game breaking bug, please fix it and i would highly appreciate a bug report token.
(IGN: Xiquid/Jessicapearson)

Kind Regards, Alex

**Comment by sioding** [comment] 2018-10-02 08:31
Duplicate of #12301

**Closed by sioding** 2018-10-02 08:31 UTC
