### ISSUE TITLE
[Chosen] Discordant Fluctuation not working with DoTs

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#1474] opened 2015-09-21 21:52 UTC
When a DoT ability (at least from an AM) is cast within range of the Discordant Fluctuation aura it does not trigger. I am not sure if this is what is supposed to happen. I know that it works with single target (where it hits as the end of the cast) and channeled spells (where it hit each time the channel hits). 

Also I have noticed that if I am dead it still hits targets who are casting spells within 30ft of my body

Thank you

**Comment by magter3001** [comment] 2015-09-22 00:54
I can confirm this as well. Seems like only direct damage effects the ability (dunno if that's how it was on live or not) Also don't know if KotBS have the same issue with melee DoTs (like Choppa AoE Dot)

**Comment by Silentguard** [comment] 2015-09-22 15:36
Thats because of waremu dont count dot apply as attack.

**Comment by Tesq** [comment] 2015-09-23 23:12
well it should be fix and split then in dot and direct attack

**Comment by ozarmidrashim** [comment] 2015-10-21 16:00
Already fixed on live.

**Closed by ozarmidrashim** 2015-10-21 16:00 UTC
Labels: Ability, Confirmation Request
