### ISSUE TITLE
Orcy Vandalism quest in Black Fire Pass

### ISSUE THREAD

**Issue by warwalker** [WarEmu/WarBugs#11274] opened 2018-02-09 02:49 UTC
Cannons in quest Orcy Vandalism not working, They show no health and cannot be engaged. Didnt see any other report, so thought I would pass it on. Thanks for all your work again.

**Comment by sioding** [comment] 2018-02-09 06:53
Duplicate of #11095

**Closed by sioding** 2018-02-09 06:53 UTC
