### ISSUE TITLE
Elves on Reikland boat

### ISSUE THREAD

**Issue by oroxor** [WarEmu/WarBugs#11567] opened 2018-04-08 14:04 UTC
As i write in the last ticket the aggro zone is not enough high, before the aggro zone was good cause when i go near them, they aggro me now its impossible, and i only can throw a knife at a distance which is far.
ANd with my chosen with the aura of aggro nothing happens too
Im near them and nothing happens : 

![jeanclode_002](https://user-images.githubusercontent.com/38176487/38468437-2ce67214-3b46-11e8-86df-d5af28e71edf.jpg)

Just need to made the aggro zone bigger like before

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-04-08 14:55
Duplicate of #11566

**Closed by sioding** 2018-04-08 14:55 UTC
