### ISSUE TITLE
K8P's "An Anvil like no other!"/Death Peak/Grom Rodrin PQ

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#19446] opened 2021-09-19 13:37 UTC
Questline from K8P sending you to Death Peak for Grom Rodrin PQ is bugged. Making the teleport to K8P unobtainable. 
![123](https://user-images.githubusercontent.com/18510648/133929527-902387c3-b33b-48eb-9e19-f3229bd8473a.jpg)

Stage 2@Grom Rodrin PQ in Death Peak, where you have to kill 3 statues, only two statues spawn currently.

**Comment by dkoerner85** [comment] 2021-09-25 21:42
I did this quest today. The third statue does spawn, but it is invisible or below terrain. It can be targeted and destroyed however, allowing to advance the PQ and complete the quest.

**Comment by ekalime** [comment] 2021-09-26 14:28
which statue? 
![Zipper_259](https://user-images.githubusercontent.com/91421798/134812050-2d12049c-79a8-43f7-856a-40ca0549eca1.jpg)

**Comment by dkoerner85** [comment] 2021-09-26 15:50
The rightmost one.

**Comment by Lheana** [comment] 2021-10-09 15:14
Duplicate of #18092
It's the same dwarf statue, and there is an issue when it's destroyed/clicked on, it does not reappear.

**Closed by Lheana** 2021-10-09 15:14 UTC
Labels: Database, World Object, Quests, Public Quests, Karak-Eight-Peaks
