### ISSUE TITLE
Archmage: Wind Blast in PvE

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11769] opened 2018-05-16 18:51 UTC
I recorded buggy and incosisten behaviour of Wind Blast when used in PvE, when used at the beggining of the fight mobs are stunned and don't move even after KD duration runs out while my DoTs are still on them and can be attacked. Notice how on video it is pretty random (2 out of 3 mobs don't move).

Location: Grovod Caverns
Mobs: Clan Skyre Clanrats

vid here:
https://www.youtube.com/watch?v=5uAoB2qjY38

**Comment by sioding** [comment] 2018-05-21 13:26
Duplicate of #2627

**Closed by sioding** 2018-05-21 13:26 UTC
Labels: Ability, NPC
