### ISSUE TITLE
Talabecland, Epic Quest, Step 16 Cleansing an Empire

### ISSUE THREAD

**Issue by LusciousLucius** [WarEmu/WarBugs#16229] opened 2020-04-04 09:35 UTC
Wiki :
"Click on 3 different cage around the village at 33k/45k.

Return to Lucius Hausen when complete."

Cant click on cages

**Comment by Lheana** [comment] 2020-04-04 13:34
Duplicate of #15441

**Closed by Lheana** 2020-04-04 13:34 UTC
Labels: Database, Quests
