### ISSUE TITLE
[ Slayer ] Rage Meter pegged out

### ISSUE THREAD

**Issue by Wyvernmoon** [WarEmu/WarBugs#15762] opened 2020-02-22 23:57 UTC
My rage meter is pegged out and I can't quit game... says I am in combat.  I am alone, not in WB, not fighting and sitting still for over 5 minutes.

![Image1](https://user-images.githubusercontent.com/41122586/75101099-6757e600-55a5-11ea-9571-c835c28c492e.jpg)

**Comment by bosli42** [comment] 2020-02-23 09:36
Bug from the last patch. If it keeps happening, try to find the cause of getting stuck in combat.
Also, you can try .unlock which should free you, but it didn't help the people I told to try it in /advice.

**Comment by Ootootoo** [comment] 2020-02-23 10:29
Are you using Power Through? https://builder.returnofreckoning.com/career/slayer/s?l=17&r=10&tl=1&mp=0&pA=3&pB=0&pC=0&m1=false&m2=false&m3=false&m4=false&ma=&mm=&mt=4073&t=4073

**Comment by Wyvernmoon** [comment] 2020-02-23 16:23
I tried the .u and that didn't work.

I am not using Power Through.

I tried using abilities that "exhaust rage" and the meter would drop, but then fill right back up.

I couldn't use book of binding or guild scrolls, so I had to alt tab out to close the program.

**Comment by Wyvernmoon** [comment] 2020-02-23 20:46
I was on cannon.  I hit the enemy and my rage bar instantly pegged out.  Now it's full, won't go down and there is no enemy around and I'm not using any abilities.  Tried .u again and nothing.

![Image2](https://user-images.githubusercontent.com/41122586/75119732-a6447500-5653-11ea-8488-dbcabcc06cdb.jpg)

**Comment by bosli42** [comment] 2020-02-23 22:45
As information: this has little to do with your rage bar, the problem is that you are simply locked as in-combat, that is why it keeps filling up.

**Comment by Wyvernmoon** [comment] 2020-02-23 22:51
First post I stated I was NOT fighting.  I picked up a supply, ran it to keep, turned it in and my rage meter was pegged out.  Somehow it pegged out without me getting into combat or fighting or being hit or using an ability.

**Comment by SecretsOTheP** [comment] 2020-02-24 04:42
Fixed as of Hotfix #2 2/23/2020

**Closed by SecretsOTheP** 2020-02-24 04:42 UTC
