### ISSUE TITLE
[T1][Blighted Isle][PQ]

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14519] opened 2019-07-05 13:11 UTC
**Expected behavior and actual behavior:**
The PQ doesn't seem to reset properly. No mobs to be found.
![Aluvya_040](https://user-images.githubusercontent.com/17249318/60724576-18d2da00-9f37-11e9-901d-f7c788b3ea4d.jpg)

**Comment by Lheana** [comment] 2019-07-05 13:14
Duplicate of #10862

**Closed by Lheana** 2019-07-05 13:14 UTC
