### ISSUE TITLE
Beast Lord Tokens

### ISSUE THREAD

**Issue by BeatingYou** [WarEmu/WarBugs#10721] opened 2017-10-30 23:54 UTC
I posted this on forums but Secrets told me I should post it here as well.  I have completed all 5 of the "kill x" destro quests after killing the beast lords but only have 4 tokens.  I'm not sure which quest I did not receive one from or when it happened.  I have gone to the quest NPCs multiple times thinking that I hadn't completed a quest or maybe it bugged and would reset, but have not been able to.  I also do not have anything for beast lord in my quest log.  I'm not able to get the pocket item due to this

**Comment by sioding** [comment] 2018-05-08 07:37
checked all active Beatlord Quests - the token is assigned

**Comment by Mandulis999** [comment] 2018-07-29 02:50
I have the same isue with my engie.

**Comment by Zurgoth76** [comment] 2018-07-31 12:37
Same issue with my Chosen :-( can you check mine too please? That's my main and really want to complete the BL set :-\

**Comment by AmakusaROR** [comment] 2020-02-22 15:20
Same issue with my SM Kenshin

**Comment by AmakusaROR** [comment] 2020-03-02 15:14
> Same issue with my SM Kenshin

Do i have to roll a new SM?

**Comment by AmakusaROR** [comment] 2020-03-30 22:19
:(

**Comment by Kaelang** [comment] 2020-04-27 00:24
The Beast Lord quest is working as intended - the only issues that arise from this chain is when there is a server crash around the time people are handing in quests / receiving tokens. We appreciate it sucks when this happens, however at this time we don't have the capacity to start returning items to those claiming loss based off of server stability.

If you believe there is a fundamental issue within the quest itself, I'll give this issue 2 weeks to supply evidence. After that, I'm going to close this up and class this bug as down to a server crash as opposed to the quest not working as intended.

**Comment by Kaelang** [comment] 2020-05-06 14:42
Closing - belief this was a result of instability.

**Closed by Kaelang** 2020-05-06 14:42 UTC
Labels: 2 Week Ultimatum, Confirmation Request
