### ISSUE TITLE
[Quest] Falling Stars

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14626] opened 2019-07-22 18:43 UTC
In the quest Falling Stars located in Praag the map markers for Yegor Kovalyov and Tankred Paine are reversed, making the quest very annoying if you do not note their locations before killing one of them. Image evidence here https://imgur.com/a/r3t2hrG .

**Comment by Lheana** [comment] 2019-11-27 17:15
Duplicate of #14377

**Closed by Lheana** 2019-11-27 17:15 UTC
Labels: Database, Quests
