### ISSUE TITLE
Apothecary Crafting Issue

### ISSUE THREAD

**Issue by FAmeloon** [WarEmu/WarBugs#12946] opened 2018-12-24 22:50 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Being able to place Skill Level 1 Apothecary container in crafting window. Unable to craft.

Steps to reproduce the problem:
- Log in
- Craft Strength Potion with Wispy Beardweed, Apprentice Glass Vial, and Cloudy Water
- Stop at any point, or when run out of 1 single stack of ingredient
-Attempt to replace that ingredient with another stack of that ingredient
-Be unable to put ingredient in crafting window.
- Does not fix on reloadui, but does fix on relog, then breaks again following the steps listed above.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-25 08:06
Duplicate of #9383

**Closed by sioding** 2018-12-25 08:06 UTC
