### ISSUE TITLE
High Elf Face Texture Issue With Shield Equipped

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15372] opened 2019-12-30 19:14 UTC
**Expected behavior and actual behavior:**
Male high elf facial textures should be applied to the 3D model in a manner similar to what is displayed during character creation/barber shop changes.
In reality, the left side (from character's perspective) of the male high elven facial texture is wrapped differently from the right, causing one eye to get "squished". This occurs with any face choice, and doesn't appear to be related to items/armor.
While somewhat amusing, it does seem to be an easily reproducible visuals bug, hopefully an easy model adjustment.

**Steps to reproduce the problem:**
Be a male high elf. Look closely at your face.

**Testing Screenshots/Videos/Evidences (always needed):**
Face in game:
![image](https://user-images.githubusercontent.com/26975895/71596768-2643d800-2b06-11ea-8e98-679f55ee9956.png)

Face in barber shop:
![image](https://user-images.githubusercontent.com/26975895/71596775-2d6ae600-2b06-11ea-8fa1-4c4437f0c146.png)

**Comment by CircuitByrd** [comment] 2019-12-30 19:30
After further testing, it seems it only happens in certain poses/animations. Standing still in Altdorf, the eye is "crushed." Mounted in Altdorf, it is not.
![image](https://user-images.githubusercontent.com/26975895/71597364-7328ae00-2b08-11ea-9ae9-8d598f973c66.png)

During the "angry face" of combat animation, the eye is fine as well.

**Comment by CircuitByrd** [comment] 2019-12-30 19:49
Okay, further testing suggests this only occurs with a shield equipped and weapon unsheathed. Greatsword is unaffected, most combat animations are unaffected, just idle holding shield.

**Comment by Lheana** [comment] 2020-01-01 20:52
Duplicate of #14858

**Closed by Lheana** 2020-01-01 20:52 UTC
Labels: Visual
