### ISSUE TITLE
WL: Brutal Pounce

### ISSUE THREAD

**Issue by korhill** [WarEmu/WarBugs#8789] opened 2017-01-04 16:09 UTC
Hello,

i did many tests and the skill does not do the correct damage. My Skillbar says 435 damage but it does arround 215. On PVE mobs it was like 170 damage (45 mitigated).  Therefore it does about 50% less damage. 

Thank you

**Comment by Luth-RoR** [comment] 2017-01-04 16:21
It could be that the ability shows the damage value of the WL player stats, but as it is executed by the lion his stats are used.

**Comment by Blaqwar** [comment] 2017-01-04 19:38
My tests suggest something different, that those abilities actually use WL player stats and not pet stats. I will admit that I don't know what the situation was on live, if player-activated pet-induced abilities scaled off the player's stats or the pet's. I don't know if that's intended on RoR either. All I can do is submit how I tested and what the result was:

I had the pet Throat Bite/Brutal Pounce on a level 39 mob first without any contributing stats from the player through Trained to Threaten (which only gives the pet Toughness and Wounds) and then I tested it with full STR/WS contribution from the player through Trained to Kill (which gives the pet 100% of the player's STR/WS, 345 STR contributed in my case).

**Throat Bite in TTT: 95 (35 mitigated)
Throat Bite in TTK: 99 (31 mitigated)**
Both at 130 damage total, tooltip value is 340 (it is showing scaling off player stats, tested by taking off STR gear).

**Brutal Pounce in TTT: 142 (53 mitigated)
Brutal Pounce in TTK: 149 (46 mitigated)**
Both at 195 damage total, tooltip value is at 405 (same scaling)

You can see that the only thing that changes is the mitigated value, which leads me to believe that the pet is only receiving a small amount of armor pen from weaponskill when landing those attacks.

I then tested lowering my STR by dropping gear down to 248 STR contributed by TTK (closest to 100 STR I could get). _This also dropped my WS contribution from TTK by 25 (from 154 to 129)._

**Throat Bite in TTT: 95 (35 mitigated)
Throat Bite in TTK: 99 (31 mitigated)**
Both at 130 damage total, tooltip value is 311

**Brutal Pounce in TTT: 142 (53 mitigated)
Brutal Pounce in TTK: 148 (47 mitigated)**
Both at 195 damage total, tooltip value is at 376

Taking of my weapon reduced the STR contribution in TTK down to 291.

**Throat Bite in TTT: 95 (35 mitigated)
Throat Bite in TTK: 97 (33 mitigated)**
Both at 130 damage total, tooltip value is 324

**Brutal Pounce in TTT: 142 (53 mitigated)
Brutal Pounce in TTK: 146 (49 mitigated)**
Both at 195, tooltip value is at 389

Weapon DPS has 0 effect on these abilities.

**My conclusions:**

- Brutal Pounce and Throat Bite abilities either have 0 STR contribution from the _player_ or contribution low enough to not register a 100 STR swing.
- Brutal Pounce and Throat Bite abilities either have 0 STR contribution from the _pet_ or contribution low enough to not register a 100 STR swing.
- Neither Brutal Pounce nor Throat Bite have weapon DPS contribution from the _player_ (I believe this is intended).
- Both Brutal Pounce and Throat Bite have some weapon skill contribution from the _pet_.

Screenshots can be provided but since I can't give any indication of what damage I got with what setup I think it's better tested personally.

**Comment by Luth-RoR** [comment] 2017-01-04 20:00
Nice testing; maybe the pet has just very low base stats and the attack is executed with those without factoring any additional stats from it's owner (the WL stance and weapon DPS). 
Though we have to wait for Dev confirmation.

**Comment by korhill** [comment] 2017-01-04 20:47
Many thanks for the great testing Blaqwar. There is for sure something wrong with the petskill damage. Wonder what Devs will say.

**Comment by Luth-RoR** [comment] 2017-01-05 01:06
About weapon DPS contribution: https://github.com/WarEmu/WarBugs/issues/8539#issuecomment-264731350
Though there is still the difference from tooltip damage to real damage.

**Comment by Blaqwar** [comment] 2017-01-07 14:05
I'll just leave this here since I don't know if it warrants opening a separate report:

Leonine Frenzy is a player invoked buff on the pet that makes it deal additional damage with each auto attack. It seems to act as a proc from the player themselves as opposed to Brutal Pounce and Throat Bite, whose damage shows up in white in the combat log (indicating pet damage), LF appears in orange (indicating player damage). It also causes threat to go to the player instead of the pet (I'm 95% sure BP and TB give aggro to the pet).

The above suggests Leonine Frenzy should scale off player stats, which it does, it scales off player's STR and WS but weapon DPS is being ignored. Since everything in the game suggests that this is _not_ a pet ability it should scale off weapon DPS as well. I'd chalk it off as a bug.

**Comment by Koryu199X** [comment] 2017-02-07 14:56
Pounce seems to still be usable even while airborne.

**Comment by Blaqwar** [comment] 2017-02-07 15:55
Pounce and Brutal Pounce are two completely different White Lion abilities so you'll have to open a separate bug report for "Pounce" as this one is about "Brutal Pounce".

**Comment by sioding** [comment] 2019-01-27 12:03
Duplicate of #13207

**Closed by sioding** 2019-01-27 12:03 UTC
Labels: Ability, Confirmation Request
