### ISSUE TITLE
Diminishing Rations Debuff when defending keep

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#12569] opened 2018-11-11 16:55 UTC
When defending a keep in BV, the defenders had the "Diminishing Rations Debuff" 

This had the effect of reducing a players health by almost 2000, as far as i know when defending a keep this debuff should not take affect

This has happen before when defending the keep in BV.

![bulgy_152](https://user-images.githubusercontent.com/44948480/48315702-970df500-e5d1-11e8-95c9-63d7fac250c1.jpg)

**Comment by sioding** [comment] 2018-11-11 17:39
Duplicate of #11508

**Closed by sioding** 2018-11-11 17:39 UTC
