### ISSUE TITLE
Candy quest dup

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#12690] opened 2018-11-23 12:24 UTC
Take quest Zombocalypse and kill 50 ppl. found only one candy and take five coins after complete. take quest and kill 50 ppl go NPS sell candy and byuout - quest complete! easy dup tokens! plz dix this bugg.ty.

**Comment by sioding** [comment] 2018-11-23 13:06
Duplicate of #12525

**Closed by sioding** 2018-11-23 13:06 UTC
