### ISSUE TITLE
Weekly guildquest not completing on orvr locks

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#14575] opened 2019-07-14 06:17 UTC
Yesterday in EU prime we had an almost full guild-only warband. And atleast 2/4 groups were guildies only. When Highpass, and later Praag locked and we got bag rolls. None of us who had picked up the weekly guild-quest for orvr locking completed.

Got a bastion stairs run in 4hours and can check if the pve version counts. But all of them should be working, ofc.

**Comment by sioding** [comment] 2019-07-14 08:12
Duplicate of #14569

**Closed by sioding** 2019-07-14 08:12 UTC
