### ISSUE TITLE
Argog the Unstoppable Bugged

### ISSUE THREAD

**Issue by darksoulscrazed** [WarEmu/WarBugs#13677] opened 2019-03-18 20:21 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
After killing Argog the Unstoppable as part of the Raven Vanguard public quest, he just keeps on looping his voice lines. The chest doesn't spawn, and the quest fails after timing out.

**Steps to reproduce the problem:**
To the best of my knowledge, everyone did what they were supposed to. We  killed the mooks, protected the priest and killed Argog. No dice.

**Screenshots/Videos or archive.org evidences:**
![Screenshot (2)](https://user-images.githubusercontent.com/48695417/54560815-8fa09300-4999-11e9-98df-5bae94501c1c.png)

**Comment by sioding** [comment] 2019-03-19 06:29
Duplicate of #12685

**Closed by sioding** 2019-03-19 06:29 UTC

**Comment by WO-RoR-Exile** [comment] 2019-12-03 12:23
Why was this closed? The Public Quest is still bugged.

12/03/2019

![Argog Bug](https://user-images.githubusercontent.com/58471571/70050764-56469c80-1595-11ea-9b22-056d5b26d957.png)

**Comment by WO-RoR-Exile** [comment] 2019-12-03 12:26
Why was this closed? The Public Quest is still bugged.

12/03/2019

![Argog Bug](https://user-images.githubusercontent.com/58471571/70050986-d0772100-1595-11ea-88f1-3c31fd6353bd.png)
