### ISSUE TITLE
[BG] Endless Pursuit doesn't work.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#12720] opened 2018-11-26 11:59 UTC
Expected behavior and actual behavior:
Should give you AP and speed boost every time you disrupt enemy ability. 

Doesn't work when you channel Rebounding Hatred.

Screenshots/Videos or archive.org evidences:
https://youtu.be/27vjZgfxgDo

**Comment by sioding** [comment] 2018-11-26 12:12
Duplicate of #12043

**Closed by sioding** 2018-11-26 12:12 UTC
