### ISSUE TITLE
[Slipping the Skin] Quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5332] opened 2016-04-13 16:14 UTC
1) White lion Pelt Dont drop from the White Lion  mob.
2) White Lion Mob is bugged. A) Its like they remain at 0 life and they dont die. B) They dont attack when at 0 and you cant attack him. C) They dont respwn they just stay at 0 forever.

![bloodsign_016](https://cloud.githubusercontent.com/assets/18271436/14500595/65a9933c-01ab-11e6-9087-fa02cb867b76.jpg)

Location on Map
![bloodsign_017](https://cloud.githubusercontent.com/assets/18271436/14500678/aad76fc4-01ab-11e6-8abf-99ff521c855d.jpg)

White lion on 0 life.
![bloodsign_015](https://cloud.githubusercontent.com/assets/18271436/14500589/60f4f0e8-01ab-11e6-9cf3-3d12f5699a7f.jpg)

**Comment by DiamondExplosion** [comment] 2016-04-14 12:57
Duplicate of : North Chrace Dark Elf #5267

**Closed** 2016-04-14 14:11 UTC
Labels: Database, NPC, Quests
