### ISSUE TITLE
[AM] Funnel Essence bug

### ISSUE THREAD

**Issue by Isharchmage** [WarEmu/WarBugs#13836] opened 2019-04-10 13:31 UTC
Greetings and thanks for the help

The skill "Funnel Essence" does not work. If I use it on me, it works. You can see it in this gif

https://gyazo.com/2d57f5b52ae3a7f9e8f77fa297395500

But if I use the skill in other players, it does not work. You can see it in this gif

https://gyazo.com/16bf464f29fb7181569c73637ad8ebb5

In the last gif I try to heal a dwarf named Fakey, and nothing appears in the combat log

What can I do to fix it?

Thanks so much for the help

**Comment by sioding** [comment] 2019-04-10 13:38
Duplicate of #11846

**Closed by sioding** 2019-04-10 13:38 UTC
