### ISSUE TITLE
Dwarf Chapter 22 Rally point

### ISSUE THREAD

**Issue by mrSVS** [WarEmu/WarBugs#6135] opened 2016-05-17 09:07 UTC
NPC Rally Master Gav Hallmundr: "Set Rally Point" function don't work.
Display error:
"ERROR: Unknown Rally point NPC (6990)"

P.S.: No flymaster at most PVE chapters

**Comment by Evildoor** [comment] 2016-05-17 09:08
One issue per problem. Lack of flightmasters is not a bug.

**Comment by saupreusse** [comment] 2016-05-18 11:06
rally point is fixed in the next patch

**Closed** 2016-05-20 06:40 UTC
Labels: Database, Fix Pending
