### ISSUE TITLE
started pvp-flaged

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11120] opened 2018-01-09 09:55 UTC
Actually i tried to create a new toon and after creating i started pvp flaged, after login with any other toon i was flaged also without activate or stay in pvp. to deflag i've to wrote /pvp and stay 10mins withot any pvp-action or take fly to any other tier. maybe bug.

**Comment by sioding** [comment] 2018-01-09 10:44
Duplicate of #10794

**Closed by sioding** 2018-01-09 10:44 UTC
