### ISSUE TITLE
All charakter history, unlock, influece etc.

### ISSUE THREAD

**Issue by pawel2001** [WarEmu/WarBugs#15422] opened 2020-01-05 17:14 UTC
Hello,
today after logging in to the character (horrrigan) I found that there is no unlock, influences from combat zones, title, quests etc. only lvl and RR remained. earlier I left some niche guild, I hit the team for a beastlord, I did a respec. After completing the tasks, I logged out in the traditional way. please help.

**Comment by raptrr** [comment] 2020-01-05 17:26
Duplicate of #15371

**Closed** 2020-01-05 17:27 UTC
