### ISSUE TITLE
Dungeons: Sewers of Altdorf

### ISSUE THREAD

**Issue by ProsperoTempest** [WarEmu/WarBugs#13245] opened 2019-01-31 17:18 UTC
Not deblostered when entering Sewers of Altdorf Dungeon solo or in a party
Expected behaviour: debolsetered to appropriate level 
Actual behaviour: Stay level 40 with access to all abilities

Steps to reproduce the problem:  Enter the dungeon 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2019-01-31 20:52
Duplicate of #13169

**Closed by sioding** 2019-01-31 20:52 UTC
