### ISSUE TITLE
Smoking Pyre Ivy seeds/ molotov potion ingredient.

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#11847] opened 2018-06-06 20:31 UTC
Level 1 smoking pyre ivy seeds purchased from crafting merchants can not be converted back to seeds after they are cultivated. Furthermore I believe the seeds currently can not have a special moment to become a higher level seed, as out of the 80 or so seeds I've tried to cultivate I have not gotten a single special moment from the level 1 seed. 
The cultivated plant can not be used as an ingredient to make the potions, trying to add smoking pyre ivy to the potion crafting menu does nothing.

**Comment by sioding** [comment] 2018-06-07 07:03
Duplicate of #10092

**Closed by sioding** 2018-06-07 07:03 UTC
