### ISSUE TITLE
Losing squig armor buff when changing zone

### ISSUE THREAD

**Issue by tr806042** [WarEmu/WarBugs#14107] opened 2019-05-17 11:09 UTC
Hi,

i'm losing my (SH) armor buff granted by my horned squig when i cross over  into a nother zone. I noticed it in ostland/Troll country and checked it with ".getstats". Makes the whole zone kinda unplayable.

**Comment by sioding** [comment] 2019-05-17 11:25
Are you below level 40?

**Comment by tr806042** [comment] 2019-05-17 12:52
no, im lvl40/rr75

**Comment by sioding** [comment] 2019-05-18 08:16
Please add your testing screenshots with the .getstats output

**Comment by tr806042** [comment] 2019-05-18 11:04
![Matyllda_000](https://user-images.githubusercontent.com/3294961/57968588-e52ef700-796c-11e9-9a71-1aa73e5a614e.jpg)
![Matyllda_001](https://user-images.githubusercontent.com/3294961/57968586-da746200-796c-11e9-89e8-6ee27c2619ea.jpg)
 when crossing over into the new zone the squig respawns (might changes color, shortly disappears) this might cause the problem. It also kills the pathing/orders for the pet, makeing fighting at a boarder very anyoing

**Comment by sioding** [comment] 2019-05-18 12:07
Duplicate of #10597

**Closed by sioding** 2019-05-18 12:07 UTC
Labels: 2 Week Ultimatum, Confirmation Request
