### ISSUE TITLE
[Choppa] Shrug it Off not working

### ISSUE THREAD

**Issue by Gorgust** [WarEmu/WarBugs#2007] opened 2015-11-27 12:40 UTC
Currently the Choppa ability Shrug it Off is not working as intended. Whenever it is used you can still get slowed unlike what the tooltip stated that roots and snares will have no effect on you.

**Comment by ozarmidrashim** [comment] 2015-11-27 18:02
If SIO is broken, every single other snare immunity in the game is also broken against every single snare in the game.

I'd like to see some evidence of this happening, with the name of the debuffing effect that causes the problem.

**Comment by Morksezstop** [comment] 2015-11-28 17:08
please add [choppa] at the title before shrug it off. Shamans also got such skill and the name of the issue is misleading on 1st look

**Comment by Evildoor** [comment] 2015-12-29 10:58
No confirmation, closing.

**Closed by Evildoor** 2015-12-29 10:58 UTC
Labels: Confirmation Request
