### ISSUE TITLE
joining an SC

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13230] opened 2019-01-29 16:04 UTC
Expected behavior and actual behavior:
I went to join an SC on my lvl 2 WE, and this happened (screenshot attached) I don't really know what it is, but I cant do anything now.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/51921524-2fd03780-23ad-11e9-8f2f-6bb63b89c4da.png)

**Comment by sioding** [comment] 2019-01-29 17:06
Duplicate of #11224

**Closed by sioding** 2019-01-29 17:06 UTC
