### ISSUE TITLE
Wrong Type of Loot from OrRvR Gold Bag

### ISSUE THREAD

**Issue by FAmeloon** [WarEmu/WarBugs#12873] opened 2018-12-16 20:27 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Expected to get a gold loot item for Witch Hunter class, instead received a golden item for Chosen class.

Steps to reproduce the problem: Received golden loot bag from zone lockout, right clicked bag to open, received golden armor from bag.

Screenshots/Videos or archive.org evidences:
![bug](https://user-images.githubusercontent.com/45919568/50058499-83652980-014f-11e9-809e-5691c6174d09.png)

**Comment by sioding** [comment] 2018-12-18 10:22
Duplicate of #11739

**Closed by sioding** 2018-12-18 10:22 UTC
Labels: Item, ORvR
