### ISSUE TITLE
Turning into a chicken outside the T1 RvR zone

### ISSUE THREAD

**Issue by Haggal** [WarEmu/WarBugs#11515] opened 2018-03-26 13:45 UTC
I've been running the dwarf storyline with a CR18 IB, outside the T1 RvR zone. Still, every time I log off in Ekrund and Mount Bloodhorn, when I log back in the character is turned into a chicken. Taking a flight master to another racial area solves the problem, as expected. Once back to Ekrund/Mt.Bloodhorn I can run the quests without turning into a chicken, until next login. Apparently, the game is either considering the RvR zone as being larger than the actual area, or it's not seeing exactly where my character is within the whole area (being outside the RvR zone). Not a big issue, but I don't know if that can cause other problems.

![image](https://user-images.githubusercontent.com/37532240/37909807-488b73de-30e2-11e8-80e6-a0b75eb3c07d.png)

**Comment by sioding** [comment] 2018-03-26 14:45
Duplicate of #10794

**Closed by sioding** 2018-03-26 14:45 UTC
