### ISSUE TITLE
Altdorf stage 3 respawn bug for destro

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#15749] opened 2020-02-22 01:44 UTC
**Expected behavior**
Respawn in spawn area
**Actual behavior:**
Respawn in spawn, then immediately die and have to wait for a 2nd respawn

**Steps to reproduce the problem:**
Die in stage 3 as destro

**Comment by dalen** [comment] 2020-02-22 15:00
Duplicate of https://github.com/WarEmu/WarBugs/issues/15718

**Closed by dalen** 2020-02-22 15:00 UTC
