### ISSUE TITLE
Appearances Of Hammers Were Mixed Up

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5138] opened 2016-04-02 00:50 UTC
So Dull Holy Hammer has appearance of Pilfered Sledge and it has appearance of Dull Holy Hammer. Weird bug. lol.
![sigmurican_000](https://cloud.githubusercontent.com/assets/18152938/14223266/6032724a-f885-11e5-8bfd-7403a32ec792.jpg)
![sigmurican_001](https://cloud.githubusercontent.com/assets/18152938/14223267/60368952-f885-11e5-9f1e-fb7245053768.jpg)

**Comment by Evildoor** [comment] 2016-04-02 15:58
Is this about icons?

**Comment by Ryanfawkez** [comment] 2016-04-03 18:10
Well yeah some icons aren't truly designed/linked up with their actual appearance at this time. Nothing we can do about that yet. Also shouldn't be much of an issue, to be honest.

**Comment by letumexordo** [comment] 2016-04-04 10:03
It would be either about icons or skins of weapons. I don't know which one problem at.

**Comment by Evildoor** [comment] 2016-04-04 10:12
For the future - icons are not to be trusted, for example, tons of chest armor pieces for all classes have the same icon of generic human plate, so reporting such things is unnecessary.
One situation where icons can help sometimes is spotting broken items - for example, gloves having a boots icon indicate possible problem with their model. Not always, though - IIRC, mara's starting armor has the same icon as shaman's shoulders.

**Comment by Evildoor** [comment] 2016-04-18 11:03
Closing as not a bug.

**Closed by Evildoor** 2016-04-18 11:03 UTC
Labels: Cannot Fix Yet, Dubious
