### ISSUE TITLE
Improved Flee II

### ISSUE THREAD

**Issue by SkabZz** [WarEmu/WarBugs#18319] opened 2021-01-08 17:10 UTC
The Improved Flee II renown ability is not functioning. It drains the AP pool and prevents it from generating points and it also only lasts for 10 seconds instead of 15.

**Comment by grunbag** [comment] 2021-01-11 07:10
i think it's disabled

**Comment by xpander69** [comment] 2021-05-30 09:08
duplicate of: https://github.com/WarEmu/WarBugs/issues/18241

**Closed by xpander69** 2021-05-30 09:08 UTC
