### ISSUE TITLE
[Quest] And thus with traitors (Saphery)

### ISSUE THREAD

**Issue by desolator87loc** [WarEmu/WarBugs#11940] opened 2018-06-24 10:00 UTC
When you kill arkaneth turncoat he should become neutral for you to complete quest. He disappears, than respawns hostile again

![image](https://user-images.githubusercontent.com/40502641/41817977-4f1afa22-77ae-11e8-97bf-5c85a4642006.png)

**Comment by sioding** [comment] 2018-06-24 14:33
Duplicate of #11615

**Closed by sioding** 2018-06-24 14:33 UTC
