### ISSUE TITLE
[PQ] [EMPIRE] Nurenmir Lancersa missing PQ counter

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15691] opened 2020-02-15 05:22 UTC
**Expected behavior and actual behavior:**

Maybe it's just me, but I have done this PQ a couple times, and the PQ tracker seems to be missing from it every time that I try this specific one. Influence and experience are rewarded, and stages seems to move on normally, but not even the final scoreboard appear once you complete it.

**Steps to reproduce the problem:**

Try to do this PQ located in the South of Ostland

**Testing Screenshots/Videos/Evidences (always needed):**
![Marajade_011](https://user-images.githubusercontent.com/50114048/74582411-3713b480-4fb3-11ea-9a4b-fac466339a6e.jpg)

**Comment by Kabucoror** [comment] 2020-02-16 15:16
For me everything is fine. Sometimes leaving the area and returning to it might make it appear again.

**Comment by Lheana** [comment] 2020-02-18 18:04
Duplicate of #10498

**Closed by Lheana** 2020-02-18 18:04 UTC
Labels: User Interface

**Comment by Ootootoo** [comment] 2020-02-18 19:25
I tried exiting and entering again, several times and with different characters, and it did'nt work. That's why I created the report, cause was unusual, but apparently it only happens to me.

**Comment by Lheana** [comment] 2020-02-18 19:28
No, see the old report related to the same issue.
