### ISSUE TITLE
Troll Country Keep Lord Bug (New Event) 

### ISSUE THREAD

**Issue by Torgrimmerr** [WarEmu/WarBugs#13840] opened 2019-04-10 19:06 UTC
Today at 2:00 pm est. the Keep Lord in Troll Country, did the same as my first report in ticket #13837 but in this ticket i have a screenshot. and Dxdiag.

Expected Behavior is to stay in the keep, not while the WB is outside with ram knocking on door

Steps to reproduce the is in an active T2 RvR siege Destro keep with order attacking destro keep, with ram outside

Josh

![Keep lord](https://user-images.githubusercontent.com/49354178/55906318-ff252f00-5ba1-11e9-9329-316d72a4a0d9.PNG)

[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/3065434/DxDiag.txt)

**Comment by sioding** [comment] 2019-04-10 19:18
Duplicate of #13588

**Closed by sioding** 2019-04-10 19:18 UTC
