### ISSUE TITLE
Event Mount Mountable while holding Dragon Orb in Dragon's Bane

### ISSUE THREAD

**Issue by Reld0n** [WarEmu/WarBugs#16455] opened 2020-04-21 18:43 UTC
Fairly Self Explanatory. Eastern Wyvern Hatchling mount is able to be used while holding orb in Dragon's Bane Scenario.

**Expected behavior and actual behavior:**
Mounts are to not be able to be used while holding orb.

**Steps to reproduce the problem:**
Grab orb from your factions area
Mount the Eastern Wyvern Hatchling Mount.

**Testing Screenshots/Videos/Evidences (always needed):**

![Reldon_000](https://user-images.githubusercontent.com/64096778/79901726-df8c2d80-83d5-11ea-9c95-67ff098a5517.jpg)
![Reldon_001](https://user-images.githubusercontent.com/64096778/79901730-e0bd5a80-83d5-11ea-9bb8-ddef53865308.jpg)
![Reldon_002](https://user-images.githubusercontent.com/64096778/79901732-e155f100-83d5-11ea-8554-b971b80a2ab3.jpg)

**Comment by Kaelang** [comment] 2020-04-21 18:47
Thank you for the report - however this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16427 so I'm going to go ahead and close this.

**Closed by Kaelang** 2020-04-21 18:47 UTC
