### ISSUE TITLE
Runepriest visual effect bug

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#14484] opened 2019-06-27 17:29 UTC
**Expected behavior and actual behavior:**
You get attacked by a runepriest with Rune of Fate dot BUT the visual effect gets stuck in you after the dot stopped having any effect

This is extremely annoying because its HUGE and it only goes away when you change zone or go back to the login screen, please fix this as soon as possible

**Testing Screenshots/Videos/Evidences (always needed):**

![Babalu_051](https://user-images.githubusercontent.com/36811878/60287194-91bbab80-9911-11e9-9cc0-a82e7dde5ec6.jpg)

**Comment by sioding** [comment] 2019-06-27 17:30
Duplicate of #14470

**Closed by sioding** 2019-06-27 17:30 UTC
