### ISSUE TITLE
Lack of rewards on the siege of the city #16488

### ISSUE THREAD

**Issue by Gimmen** [WarEmu/WarBugs#16490] opened 2020-04-24 00:34 UTC
But the rewards were NOT LOST. They were not received. This is a mistake in the distribution of awards.

**Comment by Kaelang** [comment] 2020-04-24 00:37
Appreciate that, but the fact is that the initial report was a duplicate of https://github.com/WarEmu/WarBugs/issues/16323. Which is why it was locked.

The message to close, was letting you know that regardless of distribution failing as a report of a bug, the team don't get involved with returning items.

Again, closing this.

**Closed by Kaelang** 2020-04-24 00:37 UTC
