### ISSUE TITLE
Guild Heraldry Issue

### ISSUE THREAD

**Issue by Waffulz3178** [WarEmu/WarBugs#9295] opened 2017-03-09 19:25 UTC
GM Marly suggested I post this here,

I am trying to set my guilds heraldry on Destro, <The Hidden Hand> and cannot.

The guild is rank 15, I am the guild leader, and I have over 100 gold on the guild leader character. When I go to design the guild heraldry and save the images posted occur and the heraldry is not set as designed and the 100 gold is not removed. I have also tried placing over 100 gold in the guild vault as an attempt to set the herald, which was unsuccessful. Any help would be appreciated.

<a href="http://imgur.com/fEbvFNz"><img src="http://i.imgur.com/fEbvFNz.jpg" title="source: imgur.com" /></a> 
<a href="http://imgur.com/eN9NEn6"><img src="http://i.imgur.com/eN9NEn6.jpg" title="source: imgur.com" /></a>

The last image says to redesign the herald and save no sooner than 5 seconds after saving and no more than 30 seconds later, which I have done and it does not work

**Comment by Luth-RoR** [comment] 2017-03-12 18:47
>emblem reservation works from lvl 10 on; at 20 your emblem will show the right pattern
(at least it did when coded it like 1 year ago ^^ )

just a warning first chose is 10g all other next changes will cost 500g it was made that way that guilds don't change there heraldry like underwear it it keeps something you can identify guilds with

From https://github.com/WarEmu/WarBugs/issues/7776#issuecomment-247409916

**Comment by ArdzofPT** [comment] 2017-03-24 03:40
I have the same problem. The message I get tells me to do the whole operation again in less than 5 seconds, not more than 30 seconds - impossible with the heraldry i chose. My guild is rank 20, and this is the first time I have tried to set heraldry.

**Comment by ArdzofPT** [comment] 2017-03-25 05:57
Screen shots have some of the same messages, but this is with a guild with no heraldry set and too many guild leaders some how:
![darzy_019](https://cloud.githubusercontent.com/assets/15960258/24319840/31911184-10e5-11e7-823b-ba502bd4de01.jpg)
![darzy_020](https://cloud.githubusercontent.com/assets/15960258/24319837/318c36dc-10e5-11e7-985d-248037002520.jpg)
![darzy_021](https://cloud.githubusercontent.com/assets/15960258/24319838/318cb6ac-10e5-11e7-961d-f98dba20ce05.jpg)
![darzy_022](https://cloud.githubusercontent.com/assets/15960258/24319839/31909ede-10e5-11e7-81ab-e6e25a67659a.jpg)

**Comment by Ufurious** [comment] 2017-12-04 20:19
I am still having the same issues and it's been almost a week with the only help from the GM's is "wait for server restart".....I still can't change my Heraldry colors, and my gold was deducted for the change....any and all help will be appreciated.  
Thank you

**Comment by sunspearhonor** [comment] 2018-01-07 02:16
Same issue for me as well. I'm down 200 gold already and do not wish to repeat. 

I was using Empire emblem 22/111. Which appears that perhaps it's not available in the game resources.

**Comment by sioding** [comment] 2019-05-28 07:00
Duplicate of #9791

**Closed by sioding** 2019-05-28 07:00 UTC
Labels: Database, Guilds

**Comment by Whitebeardcz** [comment] 2020-11-05 11:56
Hello. I just tried to change our guild heraldry. The same problem. It took me first 10g and only colors and pattern was changed. No emblem. So i tried it second time, because i read it costs 100g. But the same. So it took me now 110g. I wanted to take number 85. Can you please repair it?
And what are costs for guild heraldry? Is it 10g or 100g then? Can you give me 100g back if it is only 10g then?
Guild Bohemia, my ingame nick Gudmunnd.
