### ISSUE TITLE
Bramble witch adds in Khorgash Manbreaker boss cave

### ISSUE THREAD

**Issue by Mozey042** [WarEmu/WarBugs#19330] opened 2021-07-18 19:24 UTC
**Expected behavior and actual behavior:**
I was waiting for Khorgash to respawn when we were killed by what looked to be Bramble Witch adds.

**Steps to reproduce the problem:**
We killed bramble wicth right before coming to Khorgash. We wiped twice to bramble witch. one of our choppas did aoe her adds in CW. When we came to Khorgash, he was not up. So while we waited we killed a few of the mobs. When we came to the mob right behind the spikes on the left, we were attacked by invisible mobs. After they killed me I was able to see them and they were Bramble Daemonvines. I was rezed and they were just chilling in between the spikes. It seems like they were aggroed/spawned? after the choppa aoed but thats just a shot in the dark. If I rezed at the warcamp and ran back, i couldnt see them but if I was rezzed by a healer I could. Feel free to reach out to me on discord Mozey#7253 if you have any questions!

![Invisable Brambles](https://user-images.githubusercontent.com/87617564/126079445-ee32dbe1-3cf6-486a-8bba-d8d9bce057e3.png)
![Brables attacking](https://user-images.githubusercontent.com/87617564/126079453-78bd32d3-7b85-42b4-aa20-77efeb08dc3a.png)
![Bramble in wrong lair](https://user-images.githubusercontent.com/87617564/126079456-f8d3e4b2-4f38-4b1f-85f0-a5c886c754f5.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by valkeera** [comment] 2021-07-19 17:26
I've noticed these daemonvines appear several times as well, this has been happening for weeks.

**Comment by Lheana** [comment] 2021-07-24 13:37
Duplicate of #18709

**Closed by Lheana** 2021-07-24 13:37 UTC
Labels: Database, Dubious, NPC
