### ISSUE TITLE
Tactic set

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#15942] opened 2020-03-10 14:59 UTC
Week  ago i equip long held grudge to check is this work after i place my old tactic and when i do rel or equip item from backpack this tactic be equip in tactic sets
https://youtu.be/sFN9EsLOjmg
I try to delete  yakui and use vinyui nothing change the same bug

**Comment by funnytroll** [comment] 2020-03-12 15:54
And when i log in current tactic set is empty so i need to swap 
https://youtu.be/GFcsDN5SOX8
Also when i enter sc tactic Stoutness of stone dont work if i get knockdown of 3 sec i lay all 3 sec not 1.5 mb some tactic in active set dont work too but i only noticed this
https://imgur.com/JvA1KpP
This all happen after i equip long held grudge,mb serv lagging and its bugging for me dont know
Mb i have the same bug like this topic
https://github.com/WarEmu/WarBugs/issues/15857

**Comment by raptrr** [comment] 2020-03-15 16:09
As this seems to be a duplicate of https://github.com/WarEmu/WarBugs/issues/15857 I'm gonna close this issue

**Closed by raptrr** 2020-03-15 16:09 UTC
Labels: Ability
