### ISSUE TITLE
No kill reward with message: damage dealt was greater than damage taken

### ISSUE THREAD

**Issue by Jojo1337** [WarEmu/WarBugs#1770] opened 2015-10-30 13:17 UTC
On an rvr kill sometimes no reward is given (at least renown, i guess also xp/influence) with the message:
Damage dealt (x) was greater than damage taken (y), no XP given...

This happens on my BW occasionally but only in 1v1 fights (e.g. see sshot below).
![jojooo_026](https://cloud.githubusercontent.com/assets/15436264/10846292/d0227316-7f0e-11e5-9c9c-21f07f5a58cd.jpg)

Here's a sorc with the same thing: https://twitter.com/xptavares/status/654444253951737856
I also have one more report of a person who claims it happened on a BW too.

We are not sure what the intended use of this is. We assume it occurs as a bug on regular kills as BW/sorc and has something to do with the Combustion backlash damage.

**Comment by Evildoor** [comment] 2015-10-30 14:28
Combustion - wrong, i got it on my mara. I don't know exactly what this thing does, but i'm pretty sure it is a mechanic implemented to prevent unfair leveling by constantly killing a character controlled by player's friend who does not resists and just lets you kill them. In that case it's not a bug.

**Comment by Jojo1337** [comment] 2015-10-30 15:04
hm, you damaged yourself somehow?
maybe if we know what exactly triggers this mechanic (message does not make sense) we can say more

**Comment by Evildoor** [comment] 2015-10-30 15:07
No, i had no way to damage myself, and i do believe that this has nothing to do with damaging yourself.

**Comment by ozarmidrashim** [comment] 2015-10-31 10:40
This triggers if the total damage you dealt to a target significantly exceeds the total damage the target received before dying.

**Comment by MKorin** [comment] 2015-10-31 11:48
I got this after fight 1 vs 1 when we both die

**Comment by sioding** [comment] 2017-10-14 20:42
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)

**Closed by sioding** 2017-10-14 20:42 UTC
