### ISSUE TITLE
zelot harbringer off doom int and crit from weapon dont transfer to willpower heal crit

### ISSUE THREAD

**Issue by jusva321** [WarEmu/WarBugs#19005] opened 2021-05-19 08:52 UTC
3 screen shots with dagger without and with tooltip easy to do yourslef if you try it ingame 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

[
![1](https://user-images.githubusercontent.com/72552430/118784126-072b1f00-b890-11eb-82c0-38909dfde18a.png)
![2](https://user-images.githubusercontent.com/72552430/118784130-085c4c00-b890-11eb-8f16-1443fc057d60.png)
![3](https://user-images.githubusercontent.com/72552430/118784317-3477cd00-b890-11eb-88ea-626a2e9066ec.png)

](url)

**Comment by jusva321** [comment] 2021-05-19 23:25
this is better screen shots with and without the dominator belt wilpower never change and heal power never change 
![143 heal bonus 43 damage bonus](https://user-images.githubusercontent.com/72552430/118897240-29fa1980-b90a-11eb-9fc8-b830e78fe855.png)
![belt off still 590 wilpower](https://user-images.githubusercontent.com/72552430/118897244-2c5c7380-b90a-11eb-9992-56fed0405872.png)
![belt on 590 wilpower](https://user-images.githubusercontent.com/72552430/118897249-2d8da080-b90a-11eb-86d3-a27e7abd5f98.png)
![heal bonus same damge bonus 38](https://user-images.githubusercontent.com/72552430/118897250-2e263700-b90a-11eb-8ecf-51829b66a210.png)
![with dominator belt](https://user-images.githubusercontent.com/72552430/118897255-2f576400-b90a-11eb-914d-51ddba5f72af.png)

**Comment by jusva321** [comment] 2021-05-19 23:25
same gos for genesis gems they dont work aswell with the harbringer off doom

**Comment by jusva321** [comment] 2021-05-19 23:42
dont seam to work with set bonus aswell 
![with armor bonus sentinal](https://user-images.githubusercontent.com/72552430/118898333-983fdb80-b90c-11eb-9bea-0f4493499398.png)
![without armor bonus](https://user-images.githubusercontent.com/72552430/118898334-9aa23580-b90c-11eb-8081-a6b11ffcf124.png)

**Comment by lilimx** [comment] 2021-05-20 08:45
It works as intended, just use .getstats

![1](https://user-images.githubusercontent.com/23266079/118948077-3e650300-b958-11eb-9920-082aa0039d77.png)
(first blue is without mainhand/offhand second one with Bloodlord Mainhand Harbinger off)

**Comment by jusva321** [comment] 2021-05-20 13:11
Yea i tryed no willpower change for me using nihilist skinflayer of tyranny this is with and with out main hand and off handSendt fra Mail til Windows 10 Fra: lilimxSendt: 20. maj 2021 10:45Til: WarEmu/WarBugsCc: jusva321; AuthorEmne: Re: [WarEmu/WarBugs] zelot harbringer off doom int and crit from weapon dont transfer to willpower heal crit (#19005) It works as intended, just use .getstats(first blue is without mainhand/offhand second one with Bloodlord Mainhand Harbinger off)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xpander69** [comment] 2021-05-27 12:45
confirmed he was wrong on the https://github.com/WarEmu/WarBugs/issues/19035
closing

**Closed by xpander69** 2021-05-27 12:45 UTC
Labels: Confirmation Request
