### ISSUE TITLE
[MAGUS] Tzeentch Firestorm skill forgotten when removing an item

### ISSUE THREAD

**Issue by karatak** [WarEmu/WarBugs#11569] opened 2018-04-08 20:17 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When i remove an equipped item, i should still have Tzeentch Firestorm skill. But currently, when i remove any of my equipped item, the game gives me back a skill point and a i loose my Tzeentch Firestorm skill. Putting back the removed item have no effect and does not restore the lost skill so i need to learn it again at the NPC to have it back. 

Steps to reproduce the problem:
- To have the Tzeentch Firestorm skill
- Remove an equipped item

Screenshots/Videos or archive.org evidences:
![baalkoth_000](https://user-images.githubusercontent.com/26520450/38472013-c018bcc6-3b79-11e8-94f9-b058f05ae86c.jpg)

![baalkoth_001](https://user-images.githubusercontent.com/26520450/38472017-c455ccb6-3b79-11e8-9db6-773c4a24b50e.jpg)

![baalkoth_002](https://user-images.githubusercontent.com/26520450/38472019-c7d19f78-3b79-11e8-85e3-7fa8726ae0e6.jpg)

**Comment by cimator** [comment] 2018-04-08 21:27
#11480 same issue here

**Comment by sioding** [comment] 2018-04-09 06:50
Duplicate of #11480

aaaand again thx @cimator

**Closed by sioding** 2018-04-09 06:50 UTC
