### ISSUE TITLE
Consume Essence: Lifetap does not match damage dealt against Keep Lords

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16481] opened 2020-04-23 15:34 UTC
**Expected behavior**
Consume Essence against a Keep Lord should heal for 125%  of the damage dealt with Transferred Essence slotted. 
When I do 302 damage to the Lord, it should heal for 302x1.25 = 377

**Actual behavior:**
Consume essence heals for about 25% of the damage done.
302 damage  gives 75 healing (~25%). 

Issue does not appear against other players. 

**Steps to reproduce the problem:**
Use Consume Essence (with Transferred Focus slotted) against a Keep Lord.

**Testing Screenshots/Videos/Evidences (always needed):**

See combat log on bottom left of the screen for damage and healing values
Reduced healing from Keep Lord (302 dmg, 75 healing):
![Forkrul_031](https://user-images.githubusercontent.com/1183293/80118061-32a5e200-8588-11ea-8363-904ebf216851.jpg)

Normal healing from a Warrior Priest player (356 dmg, 447 healing):
![Forkrul_032](https://user-images.githubusercontent.com/1183293/80118213-63861700-8588-11ea-94c4-c0095a24689f.jpg)

**Comment by Kaelang** [comment] 2020-04-23 21:20
Duplicate of https://github.com/WarEmu/WarBugs/issues/15218.

Closing.

**Closed by Kaelang** 2020-04-23 21:20 UTC
Labels: Ability
