### ISSUE TITLE
Parry not working correctly with Guard damage. 

### ISSUE THREAD

**Issue by witc0m** [WarEmu/WarBugs#17563] opened 2020-08-18 20:31 UTC
**Expected behavior and actual behavior:**
Using a 2H, a tank should be able to Parry Guard damage of all sources equivalent to the tank's Parry percentage or, at least, this supposed 25% cap.

Parry against Guard damage isn't working properly. At best, when I'm running 2H Ironbreaker, I'm Parrying 3-5% of all incoming Guard damage. I have several images reproduced over a long period of time. One of which shows a sequence of 66 attacks and only 3 were Parried. 

Link to my original forum post: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=40425&start=10

**Steps to reproduce the problem:**
Take a look at how 2H Guard damage Parry is supposed to work and make sure it's working properly on all tank classes. I can't speak for other classes, but on Ironbreaker this issue makes 2H tank completely not viable. 

**Testing Screenshots/Videos/Evidences (always needed):**

![1](https://user-images.githubusercontent.com/66286733/90562417-1ef23d00-e170-11ea-92e9-8e5f3c0100b8.jpg)
![2](https://user-images.githubusercontent.com/66286733/90562418-1f8ad380-e170-11ea-9ee7-132b433211dc.jpg)
![3](https://user-images.githubusercontent.com/66286733/90562419-1f8ad380-e170-11ea-8c8e-ae93b3db4611.jpg)
![4](https://user-images.githubusercontent.com/66286733/90562420-1f8ad380-e170-11ea-9361-90204a863061.jpg)

**Comment by dalen** [comment] 2020-08-18 21:42
What does .getstats say?

And what type of attacks is this, melee attacks, ranged or spells?

**Comment by witc0m** [comment] 2020-08-18 21:46
Paperdoll stats put me at 51% Parry unbuffed, 76% Parry with Oathbound, or 61% if just Earthshatter procs. .getstats shows me at 31% Parry unbuffed. 

These snapshots are all from fort/keep situations so the damage is all types. I've also monitored it without snapshots during other oRvR events and it happens the same way, although without the constant stream of damage from a keep/fort it's hard to capture it all in a nice snapshot like this.

**Comment by Zomega-WAR** [comment] 2020-08-18 21:57
I wonder if strikethrough is being applied after this 25% cap rather than before it?

**Comment by TenhiYT** [comment] 2020-08-18 23:29
The cap isnt 25%. The BASE is 25%. The cap is 75%. With his stats he should see way more parries. And while the sample size isnt huge... it still seems suspicious.

**Comment by witc0m** [comment] 2020-08-19 01:36
I should add, the second link of screenshots is with Oathbound active, putting my paperdoll Parry above 75% (.getstats not sure).

**Comment by CornerbackAC** [comment] 2020-08-30 14:03
Small addition: yesterday we figured out that I parry 100% of guard hits from level 1 rats on my IB (75% parry).
Higher mobs however have a much lower chance for guard damage to be parried.

Do the attackers stats or level actually influence the parry rate for guard damage?

**Comment by dalen** [comment] 2020-08-30 14:06
yes, attacker stats influence it on RoR, it doesn't seem to work at all as it did back on live. This might be some intentional change from a long time ago, I'm not sure. Need to look into it a bit.

**Comment by CornerbackAC** [comment] 2020-08-30 14:08
Would be great if you looked into this. The speed at which def tanks melt on guard damage is beyond anything I've ever seen on live.

**Comment by iantheace** [comment] 2020-09-01 11:29
2H Black guard is also unplayable at the moment due to this issue, as soon as you come close to any kind of melee blob, you die faster than the DPS you are guarding, and thats with 84% parry.

**Comment by Rivenspeak** [comment] 2020-09-03 14:44
Does it maybe have something to do with DOTs and not having a chance to defend against each DOT tick?  Looks like a lot of 22 or 19 damage hits in a row, which makes me think your guard target might be taking damage from a DOT and somehow it's passed through to tank as undefendable (?).  (I think DOT mechanism is chance to defend against DOT landing, but if it lands there's all ticks are undefendable)

**Comment by Tesq** [comment] 2020-09-06 02:10
2h bg is playable,  altough you need 70%+ of parry or zergy sich are a no go, still i never was able to push trough funnel like a s+b, anyway it's from around a year or more that i noticed that on my chosen i were taking more hits from guard but i never give it a test or bothered.

anyway those ankward changes posted on forum are total madness if those are confirmed they total disadvantage s+b destru tank (no bias) as order in s+b are block based tank it mean that the changes influenced them less than 2/3 des tank since they are parry based (so they basic avoidance work only vs melee instead order basic avoidance work vs all souce of dmgs).
On top of that there is the sich of all 2h tank; alredy 2h tanks in rvr are pretty much restricted to kobs/bg in the viable range (with soem BO exeption). Just revert to live formula indeed. Guard should be an easy thing not a hard one.......you should incentive to guard.....not the opposite.

**Comment by kyraith** [comment] 2020-11-12 10:46
This looks a lot like damage from guarding a Brightwizard

**Comment by dalen** [comment] 2020-11-12 11:04
This has been fixed now. Guard damage from damage procs is defendable now.

**Closed by dalen** 2020-11-12 11:04 UTC
Labels: Combat Mechanics
