### ISSUE TITLE
Live Event-Keg End (Warrior Priest)

### ISSUE THREAD

**Issue by Psychoxell** [WarEmu/WarBugs#12903] opened 2018-12-22 15:21 UTC
The Elite achievment for Warrior Priest in the Keg End event ist false.
The item cannot be used by a Warrior Priest.

Image:
![keg end](https://user-images.githubusercontent.com/46071136/50375920-95d6db80-0605-11e9-9608-78d92274d8c1.png)

**Comment by sioding** [comment] 2018-12-22 16:55
Duplicate of #12895

**Closed by sioding** 2018-12-22 16:55 UTC
