### ISSUE TITLE
PQs for Order and Destro get mixed up in Stages and ToK

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#17537] opened 2020-08-15 13:43 UTC
Entering PQ areas that are "shared" between Order and Destro in MoM and BV maps is showing statistics for the opposite realm (at least playing on Order, you see the stage milestones that apply to Destro).

First screenshot is from "Blood Fen" PQ, second "Marsh Conquest" PQ, and third "Bar Dawazbak" PQ

![Caiquenil_100](https://user-images.githubusercontent.com/58527250/90313578-fa972600-df0d-11ea-9f3b-605f56b860ee.jpg)

![Caiquenil_101](https://user-images.githubusercontent.com/58527250/90313583-fec34380-df0d-11ea-9dd6-9203c8067697.jpg)

![Caiquenil_102](https://user-images.githubusercontent.com/58527250/90313587-0256ca80-df0e-11ea-9025-87bcc639b6f0.jpg)

**Comment by valkeera** [comment] 2020-08-20 20:23
Another PQ with switched statisics is "" in Badlands.

![Caiquenil_104](https://user-images.githubusercontent.com/58527250/90821799-c8356080-e333-11ea-83b0-4337bc86ea54.jpg)

**Comment by valkeera** [comment] 2020-08-26 16:11
Another issue, while traveling through Destro pve zone in Ostland, I crossed the Silkens PQ, got bitten by a spider, and after a while received 1st place and blue bag for "participating" in it. Chaos storyline got unlocked in my ToK afterwards.

![Caiquenil_004](https://user-images.githubusercontent.com/58527250/91328707-8d19ae00-e7c7-11ea-913e-340a222c1d28.jpg)

![Caiquenil_005](https://user-images.githubusercontent.com/58527250/91328723-9145cb80-e7c7-11ea-9458-690a22bb6620.jpg)

**Comment by Lheana** [comment] 2020-08-29 15:27
Duplicate of #17313

**Closed by Lheana** 2020-08-29 15:27 UTC
Labels: Public Quests, Sourcecode
