### ISSUE TITLE
[Quest] Wyrmbreaker

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14619] opened 2019-07-22 18:10 UTC
In the quest Wyrmbreaker you are instructed to enter the Senthoi pool, use the Summonglass and then kill the Black Dragon you summon. Entering the pool does not register in the quest log, you can use the Summonglass however it does not summon the dragon (possibly related to the fact that entering the pool part of quest is incomplete), so you are unable to kill it. Images relating to this quest can be found here https://imgur.com/a/5RMZCdI .

**Comment by Lheana** [comment] 2019-07-22 20:51
Duplicate of #12982

**Closed by Lheana** 2019-07-22 20:51 UTC
