### ISSUE TITLE
Party trees (glowing trees)

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4811] opened 2016-03-07 23:53 UTC
The greenskins are having a party in Mount Bloodhorn near chapter 2. A bunch of trees are glowing as if you could interact with them (but you can not).

![dark](https://cloud.githubusercontent.com/assets/16590792/13587364/1899bf18-e4c8-11e5-8977-694e7de0b7bc.jpg)
![light](https://cloud.githubusercontent.com/assets/16590792/13587371/1de78f40-e4c8-11e5-9e21-4a462d9835d5.jpg)

**Comment by Torquemadra** [comment] 2016-03-08 00:07
They are part of the pq if I am not mistaken, which is currently not altogether functional

**Comment by Evildoor** [comment] 2016-05-04 13:12
Closing as not a bug, and PQ not workins is reported elsewhere.

**Closed by Evildoor** 2016-05-04 13:12 UTC
Labels: Not Implemented, Public Quests
