### ISSUE TITLE
No Ram spawning in The Maw Fortress

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13414] opened 2019-02-20 04:59 UTC
We (Order) just opened The Maw after we locked Chaos Waste (No renown xp after lock btw), and there's no ram to open the first door. So we can't get in. The portal seems to be working now, though

**Comment by Natherul** [comment] 2019-02-21 08:19
this issue should have been fixed with the last hotfix. Issue was caused by the method that teleported people out that were in the fortress before the fight began

**Closed by Natherul** 2019-02-21 08:19 UTC
Labels: Fortresses, Sourcecode
