### ISSUE TITLE
[Expert Skirmisher] reducing all cast times on Squig Herder unconditionally

### ISSUE THREAD

**Issue by myvalidusername** [WarEmu/WarBugs#6150] opened 2016-05-17 18:27 UTC
When equipping the Expert Skirmisher tactic (on a rank 15 character) all cast times are reduced by 50% regardless of the condition implied (20 ft of your target).

**Comment by Evildoor** [comment] 2016-05-17 18:47
Proof.

**Comment by roadkillrobin** [comment] 2016-05-17 21:20
It's working as intended
![narfeg_010](https://cloud.githubusercontent.com/assets/16356956/15339703/fd77eeda-1c85-11e6-8d90-e90ccde3f79a.jpg)

**Comment by Abolition** [comment] 2016-05-18 06:51
I just did some testing and it is working as intended.

**Comment by myvalidusername** [comment] 2016-05-18 21:16
It's a UI bug then (see screens). Squig summons in 1 sec as it says, Plink shoots for normal time, even if UI says it's halved. The intended or unintended no-target 50% off cast time is kinda cool though.
![bizgib_000](https://cloud.githubusercontent.com/assets/19414859/15375297/f267e762-1d56-11e6-8de6-845ab2f601bd.jpg)
![bizgib_001](https://cloud.githubusercontent.com/assets/19414859/15375298/f267ff68-1d56-11e6-8d87-de486bb55aa0.jpg)

**Comment by Evildoor** [comment] 2016-05-19 07:20
> Edit: If you don't have a target it treats it as if point blank (wthin 20 feet)

My memory agrees with this. Closing.

**Closed by Evildoor** 2016-05-19 07:20 UTC
Labels: Confirmation Request
