### ISSUE TITLE
In game ui is just main menu tabs (picture included)

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16509] opened 2020-04-25 19:49 UTC
![oops](https://user-images.githubusercontent.com/64330047/80289363-4d8f7680-8781-11ea-8ff6-a4916ddc8839.png)

Just before transitioning to an scenario, screen went green with only the main menu tabs on the bottom then it reloaded me back into the city where i originally was but no ui apart from the main menu tabs.

**Comment by Kaelang** [comment] 2020-04-25 19:55
This is a duplicate of https://github.com/WarEmu/WarBugs/issues/12576.

**Closed by Kaelang** 2020-04-25 19:55 UTC
