### ISSUE TITLE
Greenskin Chapter 10 

### ISSUE THREAD

**Issue by DaHiff** [WarEmu/WarBugs#18599] opened 2021-03-07 10:15 UTC
Not able to select the 1st reward from the chapter had the same issue with chapter 8 and maybe 9 too not 100% on 9 tho 
![Hiff_000](https://user-images.githubusercontent.com/80197936/110236506-160b6200-7f2e-11eb-87d8-bfb2adebc66a.jpg)

**Comment by DaHiff** [comment] 2021-03-09 03:09
chapter 13 and 14 too seems alot of the greeenskins need a look at

**Comment by Lheana** [comment] 2021-03-21 17:46
Duplicate of #7687
Also one issue per report please.

**Closed by Lheana** 2021-03-21 17:46 UTC
