### ISSUE TITLE
Engineer Grenadier path abilities and damage needs attention.

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#2602] opened 2016-01-01 11:03 UTC
Damage of grenades thrown specially after acid bomb,suppsedly should have wrecked peoples magic defenses is laughable at best.example i spam 2 acidbombs at dok 1 before he cleanse and 1 after ,load him up with corporeal damage and still see hits for 41dmg(49mitigated) in damage log what is going on,feels like damage is not increased 1 bit by my 662 ballistic skill as it should be,and that acid bomb is indeed not wrecking enemies corporeal  resists at all. did a test with magus the napalm grenades vs the mist from magus and magus with less intelligence then my engineers ballistic skill hits twice as hard....what the...

**Comment by Evildoor** [comment] 2016-01-01 11:21
Information not clear. 41(49) - what ability? Under what conditions it was used? Without that info i don't see any glaring problems with DoK having 54% corporeal mitigation (stacked toughness, resist buff countering your resist debuff, possible level difference, etc).
Napalm and mist are supposed to be equal in terms of damage. Screens of combat log and .getstats of both chars?

**Comment by ozarmidrashim** [comment] 2016-01-01 12:32
https://github.com/WarEmu/WarBugs/issues/2594

**Comment by ozarmidrashim** [comment] 2016-01-01 12:33
Post proof, with calculations (info is available). I'm not going to do your work for you.

**Comment by HtGeist** [comment] 2016-01-01 12:49
![hrafgrim_005](https://cloud.githubusercontent.com/assets/16508090/12070863/9fed312a-b0c0-11e5-8d02-9087f7ee2557.jpg)
![hrafgrim_003](https://cloud.githubusercontent.com/assets/16508090/12070864/b912c4f8-b0c0-11e5-9047-b611b412ab7d.jpg)

**Comment by HtGeist** [comment] 2016-01-01 12:52
dok was wearing a armor potion and a str potion,resists soft cap at 40 and since he had stalker gear+0 resists on that i highly doubt he had any ability to resist buff counter,chosen resist aura as example will help cap 40% cap for you,not completly negate any debuffs or am i wrong?

**Comment by HtGeist** [comment] 2016-01-02 15:19
![hrafgrim_006](https://cloud.githubusercontent.com/assets/16508090/12074859/6e4d876c-b19e-11e5-9995-d777cd0c351d.jpg)
what is going on with that crappy dmg?? acid bomb ticks has their resists debuffed yet they still mitigate above 50% tanks maaaybe if they run 800 toughness fine,i guess...but the sorcs? the doks??? whaaat? where is engi damage hiding?? up the dmg on abilities cos this apparent ballistic skill boost does 0.

**Comment by bloodi** [comment] 2016-01-02 18:07
So is this a bug report or just you asking for a damage increase?

**Comment by Torquemadra** [comment] 2016-01-03 04:25
[quote]what is going on with that crappy dmg??[/quote]

Every character listed in that screenie is a tank in end game armour........

http://www.returnofreckoning.com/armory.php?character_id=165176&character_name=Fonix

http://www.returnofreckoning.com/armory.php?character_id=77627&character_name=Tsors

http://www.returnofreckoning.com/armory.php?character_id=174668&character_name=Satock

http://www.returnofreckoning.com/armory.php?character_id=34113&character_name=Yaren

**Comment by HtGeist** [comment] 2016-01-04 06:03
i see around 250ish corp resists on those people which acid bomb has more then negated,which again fortifies my claim its not debuffing correctly,or chosen/kotbs aura are double cheat helping you cap resists and negating the debuffing etc softcap is 40% magic resists at around 500ish acidbomb drops 286 of those leave you quickly estimated with around 22ish??? reduction before toughness reduction of what 800 toughness to be wild reduce how much 150dps 662 ballistic adds 130ish so minus 20 dps.
what accountant do i need to hire for 22% resist and minus 20 dps to result in above 50% mitigation and 1/3 of tooltip dmg ?? i wonder.

**Comment by genisaurus** [comment] 2016-01-09 18:34
Closing, because there is nothing here to indicate that there is a bug in play. Engineer damage has always been known to be subpar, but this is a balance issue, not a bug. 

Once the Engineer is being addressed for balance changes, OP is advised to participate in those balance discussions on the forums in a thoughtful and thorough manner, if he wishes to provide insight into addressing the problem.

**Closed by genisaurus** 2016-01-09 18:34 UTC
Labels: Dubious
