### ISSUE TITLE
Tome of Knowledge Entry (Chaos Starting Zone)

### ISSUE THREAD

**Issue by Gazdakka** [WarEmu/WarBugs#11710] opened 2018-05-02 23:44 UTC
Small issue, but hopefully easy to fix:

The Chaos starting zone of Norsca does not give the Chaos Portal Tome Unlock that it used to on the Live server. The large portal that is positioned behind the player when they first create a character would trigger this unlock (I believe through clicking on it or moving to the precipice of the rocky platform that extends to the portal).

Picture of the starting zone portal in question:
![appelliakra_001](https://user-images.githubusercontent.com/38927890/39554322-af8a4852-4e61-11e8-9cc3-f44d8df3bff8.jpg)
Picture of the rocky outcrop next to the portal that walking on may have triggered the unlock.
![appelliakra_002](https://user-images.githubusercontent.com/38927890/39554410-24e474a6-4e62-11e8-8a24-39b39dfc80b9.jpg)
The Tome Unlock that it should trigger (Under "History and Lore">"Empire VS Chaos">Tier 1>"Norsca") The first entry.
![gazamork_008](https://user-images.githubusercontent.com/38927890/39554408-200410ae-4e62-11e8-8325-ca3b1843bcda.jpg)

Thanks for anything that can be done to resolve this issue.

**Comment by sioding** [comment] 2018-05-03 07:04
Duplicate of #8417

**Closed by sioding** 2018-05-03 07:04 UTC
Labels: Tome of Knowledge
