### ISSUE TITLE
No rewards on kills after scenario end

### ISSUE THREAD

**Issue by ZGG51** [WarEmu/WarBugs#2194] opened 2015-12-07 08:56 UTC
People are just playing classes adept at getting last hits like sw/sh and just running around stealing db's to farm medals, stealing them from everyone and gimping RR across the board.

seen them get 10+ solo kills almost every sc we won, and they usually get 5-8x the renown of everyone else.

**Comment by Evildoor** [comment] 2015-12-07 09:26
While i agree that this may be annoying, it is not a bug, since it was exactly the same on live. Plus healers going out of party to leech renown.

**Comment by Morksezstop** [comment] 2015-12-07 18:08
nope it wasnt that way on live. Not for healing neither for dps. 
At Ror when out of group dps take the last hit it take ALL the renown, loot, exp, etc. On live when oog dps took last hit he got only kill blow statistic and some small renown based on damage done but NOT ALL. On live never the person that made the last hit took all the prizes from the kills. That is way on live when u punt someone to the guards you get some renown, on ROR u got 0 cos the killing blow is made from NPC

**Comment by Evildoor** [comment] 2015-12-07 18:27
Well, maybe i'm wrong about DB then.

**Comment by gittoaster** [comment] 2015-12-07 20:12
I think MOrkeszstop is right but that would mean it's not just a scenario issue but a issue related to play in the zones as well.  
I can recall killing mobs in PvE and getting a small portion of XP+coin.

**Comment by Evildoor** [comment] 2015-12-07 20:15
Yes, there is a general issue with deathblows in RoR. There are reports about pets stealing XP/RR/etc with deathblows, and about guards doing the same.

**Comment by Morksezstop** [comment] 2015-12-07 20:26
yes it is different at ror, i just wasnt sure if it is intented or not. The renown contribution based on damage dealt was working quite differently on live. 
Here we got the exactly opposite situation where healers stay at group becouse they dont have benefits from oog healing while dps gain full benefit from kill blows out of group. 
And yes, this is not sc isolated issue. It is effecting all kills at all zones, everywhere.
I like how the devs removed the iniciatives for healers to heal oog, i hope they will do the same with dps classes aswell

**Comment by ozarmidrashim** [comment] 2015-12-08 22:22
This was fixed in today's update.

**Comment by Evildoor** [comment] 2015-12-19 11:43
It seems that now you are counted as a solo player if you queued solo and landed a DB on someone after sc has ended. Needs to be tested - what happens if you queued in party.

**Comment by Evildoor** [comment] 2015-12-21 16:35
Update: if you are in party before sc, then you correctly get xp and other stuff on DBs after sc end.

**Comment by Evildoor** [comment] 2016-06-02 13:25
Update: now you don't get rewards on deathblow after scenario end even if you are in party.

**Closed** 2017-10-30 13:25 UTC
Labels: Scenarios, Trivial
