### ISSUE TITLE
Continued Slow Walking After Lava-Death in Tor Anroc and After Scenario

### ISSUE THREAD

**Issue by landgoat** [WarEmu/WarBugs#12551] opened 2018-11-06 13:37 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
After a Lava-Death in Tor Anroc, speed is restored. In this particular case, speed reduction caused by lava stuck to me after respawn, and continued after I zoned out of the Scenario.

Steps to reproduce the problem:
Get punted into Lava in Tor-Anroc, respawn. (has only occurred once in my history of playing)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-11-06 15:03
Duplicate of #12472

**Closed by sioding** 2018-11-06 15:03 UTC
