### ISSUE TITLE
Suderholm Reusable Tinder 

### ISSUE THREAD

**Issue by oddmage** [WarEmu/WarBugs#10666] opened 2017-10-24 00:19 UTC
During the part of this PQ where you have to burn the houses down, you can use the the house behind the main hall, on the right side, over and over again.

**Comment by Lheana** [comment] 2017-10-24 09:44
Could you give coord?

**Comment by oddmage** [comment] 2017-10-24 10:56
Norsca, 25413, 50434 or 25559, 51380.  Though I just tried it again and it didn't happen.  There must be a step I'm missing.  This time through I just tried by myself and before we had usually gotten the ones around the entrance to the hall first.

**Comment by Lheana** [comment] 2017-10-24 11:14
I already noticed you could time by time interact 2 or 3 times with a GO, but this bug is really not consistent.
Though, I tried all Kindling in Destro PQ Suderholm, did not notice some that were spammable.

**Comment by oddmage** [comment] 2017-10-24 11:45
Yeah I wasn't happy I couldn't reproduce this morning. I can send you my
character name if you can look through logs with it.

On Oct 24, 2017 7:14 AM, "Lheana" <notifications@github.com> wrote:

I already noticed you could time by time interact 2 or 3 times with a GO,
but this bug is really not consistent.
Though, I tried all Kindling in Destro PQ Suderholm, did not notice some
that were spammable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WarEmu/WarBugs/issues/10666#issuecomment-338956553>,
or mute
the thread

**Comment by oddmage** [comment] 2017-10-25 12:20
Tried again last night with hitting the ones near the town hall first (the circle where the boss spawns) then going down.  Didn't happen again.  Wonder if it matters what position it's in when the previous win scenario happens.

**Comment by Lheana** [comment] 2017-10-26 11:39
I close it as the problem is not really the GO of this PQ.

**Closed by Lheana** 2017-10-26 11:39 UTC
Labels: Public Quests, World Object
