### ISSUE TITLE
Granted Mastery from Items.

### ISSUE THREAD

**Issue by Skoll888** [WarEmu/WarBugs#16886] opened 2020-05-20 14:55 UTC
Found a bug which give you 15 Mastery abilities points 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:** 
go to the trainer, opene the skill tree respecialize, unequip 2 parts of the keeper set now you can train all abilities in tis tree

**Testing Screenshots/Videos/Evidences (always needed):**

![Solefera_000](https://user-images.githubusercontent.com/46657401/82460935-1d09d680-9aba-11ea-91ce-90f7534b6d4e.jpg)

![Solefera_001](https://user-images.githubusercontent.com/46657401/82460980-2bf08900-9aba-11ea-9cd6-7f8fdb640d05.jpg)

![Solefera_011](https://user-images.githubusercontent.com/46657401/82461105-504c6580-9aba-11ea-9aa3-4829d02dd0f8.jpg)

![Solefera_009](https://user-images.githubusercontent.com/46657401/82461255-7eca4080-9aba-11ea-92c2-aa09d9ddf9c8.jpg)

**Comment by Skoll888** [comment] 2020-05-20 15:41
I tested it with with my dok and its the same

**Comment by Kaelang** [comment] 2020-05-20 15:43
I'm really struggling to replicate this on dev. Could you elaborate on replication steps, because doing what you said simply removes the top skill from the tree for me.

**Comment by Skoll888** [comment] 2020-05-20 15:57
it only works with the full keepers set i think. just like i says go to the trainer and open the skill tree window and klick on respecialize now unequip two parts of the keeper set and now the full tree is available and you can skill all abilities

**Comment by Skoll888** [comment] 2020-05-20 16:02
![Clokwork_007](https://user-images.githubusercontent.com/46657401/82469150-f2bd1680-9ac3-11ea-8f39-7b5408f4ae2c.jpg)

**Comment by Kaelang** [comment] 2020-05-20 16:07
I'm going to need a video - no idea how you guys are managing to do this.

**Comment by Skoll888** [comment] 2020-05-20 16:11
can you recommend a video recording program to me

**Comment by Kaelang** [comment] 2020-05-20 16:12
Windows - Press Windows Key and G at the same time. Capture - Record.

**Comment by Skoll888** [comment] 2020-05-20 16:49
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/WarEmu/WarBugs/files/4658202/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by aaearon** [comment] 2020-05-20 17:19
I have the same experience also with the Keeper set.

**Comment by velenne** [comment] 2020-05-20 17:26
I'm a 35cr/40rr Witch Hunter.  I have a full Annihilator set which gives +1 to Judgement skill tree abilities.  This morning I was missing an ability in Judgement tree I'd purchased using the extra point.  
When I went to a Career Trainer to fix it, I tried to just Respecialize but didn't get the bonus point back.  So (if I remember correctly) I took off the armor and Respecialized again.  This time the entire Judgement Tree was filled up. I couldn't buy any more ranks if I wanted to, but I still had my full skill points to spend!
So I spent my points on some abilities in Judgement, and others in Confession.  Hit Train.  I now have way more abilities than I should!!  
If I put the armor back on, all the skill points disappear from the Judgement tree but I still retain the abilities.  Very strange.  My toon is named Takindra if you want to see online.

**Comment by velenne** [comment] 2020-05-20 17:52
I think I may have done Worn Armor (+1 mastery point) -> Hit Respecialize button -> Take off armor -> See full skill tree in mastery window -> bought points -> Hit Train button.  Hope that helps with recreating the issue.

**Comment by tlitschye** [comment] 2020-05-20 19:07
so replication: 
1. respec at trainer example im getting 29 points back
2. remove one SOV part
3. bääm i get 15 points in first three

**Comment by igvgithb** [comment] 2020-05-20 19:18
It can be replicated on Sorc using Obliterator. It does not work on Chosen with Annihilator.

**Comment by Jaffawer** [comment] 2020-05-20 20:53
Ye I just noticed this too when I logged on my WL, since I had one point missing and was looking where it went.

I am wearing full Ruin set (4-piece set bonus gives +1 to hunter)

reproduce:
every time I replace ANY 2 of those armor pieces (with any armor) it bugs out and gives free 15 points into Path of the Hunter tree, and you still have your original 25 points you can spend.  

You loose these points when you re-equip those two Ruin pieces back.

**Comment by darckimp** [comment] 2020-05-22 09:13
The same here, but in completion, my character lose 1 Mastery Point. 
I'm a shaman with the Mercenary Set (Name : Olbrenna)

**Comment by Kaelang** [comment] 2020-05-22 13:29
This should've been fixed as of today's restart. Please re-open if issue persists.

**Closed by Kaelang** 2020-05-22 13:29 UTC
Labels: High Priority
