### ISSUE TITLE
Untouchable M1

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10917] opened 2017-11-27 14:02 UTC
Untouchable gives values not corresponding with the description, both with .getstats command and in the character sheet. The stats should be doubled.

Skill Description: Your chance to defend attacks is increased by 100% for 5 seconds
Images using .getstats
Without buffs, raw stats
![sheykis_065](https://user-images.githubusercontent.com/18032193/33270272-bd9a0206-d383-11e7-8a95-878b12239183.jpg)
With Untouchable popped up (buff icon missing here, but got screenshot of just before geting stats)
![sheykis_067](https://user-images.githubusercontent.com/18032193/33270273-bdbcd894-d383-11e7-8f6f-7609973b3390.jpg)

Images with character sheet
![sheykis_070](https://user-images.githubusercontent.com/18032193/33270305-e5b4553e-d383-11e7-848b-daaa23a46299.jpg)
![sheykis_072](https://user-images.githubusercontent.com/18032193/33270306-e5d9f230-d383-11e7-9fef-6857aef8902a.jpg)

**Comment by sioding** [comment] 2017-11-27 20:42
We had that discussion already

**Comment by sioding** [comment] 2017-11-27 20:42
Duplicate of #2598

**Closed by sioding** 2017-11-27 20:42 UTC
