### ISSUE TITLE
Being attacked by friendly NPC

### ISSUE THREAD

**Issue by zasdman** [WarEmu/WarBugs#12281] opened 2018-09-08 02:45 UTC
I was killing some Dwarves, because thats what you do, when this fellow Green skin runs up and starts hitting me. He does not seem to be able to kill me though... 

Expected behavior and actual behavior: Friendly NPC's should not attack you, This Orc thinks he should attack friendlies

Steps to reproduce the problem: I have not tried to reproduce this, but I sill have more Dwarves to kill so I will try
 Edit: I got attacked again, this time I stayed where I was when being attacked to show where the orc was, this is his spawn point on top of that tree stump.

Screenshots/Videos or archive.org evidences:
[Video](https://youtu.be/oRqqm-WcUPU)
[Video2](https://youtu.be/msZgpaxZBHU)

**Comment by sioding** [comment] 2018-09-08 07:10
Duplicate of #12271

**Closed by sioding** 2018-09-08 07:10 UTC
