### ISSUE TITLE
Dead Loot Rolls

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15380] opened 2020-01-01 20:42 UTC
**Expected behavior and actual behavior:**
When your dead if you roll for loot in a WB, the game doesn't register your roll, it doesn't take it as a pass, need or greed, it just closes the window. Not sure how to screenshot this, but it is very easy to reproduce.

**Comment by Kaelang** [comment] 2020-04-21 23:49
Duplicate of https://github.com/WarEmu/WarBugs/issues/6885.

**Closed by Kaelang** 2020-04-21 23:49 UTC
