### ISSUE TITLE
black orc equipmen loot by order

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13488] opened 2019-02-26 02:44 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
black orc equipement shouldn't be loot by order (serpent's passage scenario)

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![thorbolt_766](https://user-images.githubusercontent.com/16274785/53383658-b3fbe780-3978-11e9-88b5-c722b5692cc1.jpg)
![thorbolt_765](https://user-images.githubusercontent.com/16274785/53383680-c118d680-3978-11e9-8f53-cdf89df3290a.jpg)

**Comment by sioding** [comment] 2019-02-26 18:37
Duplicate of #11739

**Closed by sioding** 2019-02-26 18:37 UTC
