### ISSUE TITLE
Engi - Turrets/daemons having no abilities and unable to use them either.

### ISSUE THREAD

**Issue by Dundara** [WarEmu/WarBugs#12452] opened 2018-10-15 08:00 UTC
This has been a real long standing issue since I first started playing on Krumbo, and have been working around it bc I'm lazy but that's ended up costing me more time and lives during fights. 

The bug is that after a turret has been built, rebuilding it another time or again after that, will cause the turret to spawn without abilities, the only temporary fix is that if it gets destroyed, and then rebuilt again, it will have its abilities... until you rebuild it again and you're back to 0 abilities. It's a problem because the turret does not cast its secondary ability in this mode, and rarely even casts its first ability, meaning the gun turret ability (core armor debuff ability of rifleman) cant be used when required. And there's no way of manually casting the abilities since you don't have them, or risk losing 4 stacks to rebuild another turret.

this happens to all turrets/daemons in the same manner, seriously inhibits the clunky mechanism of engineer/magus even more when proper pet control is not allowed.

the bug is easier reproduced with the instant turret/daemon tactic but it bugs out either way if you rebuild a turret whilst you currently have one active, occurs almost always during combat.

screen attached
![dundara_030](https://user-images.githubusercontent.com/38449710/46937055-01537880-d0ac-11e8-8cbe-c51edbded71f.jpg)

**Comment by sioding** [comment] 2018-10-15 17:56
Duplicate of #11987

**Closed by sioding** 2018-10-15 17:56 UTC
