### ISSUE TITLE
Bugged quest: And Thus with Traitors

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12232] opened 2018-08-29 18:22 UTC
Saphery quest "And Thus with Traitors" is bugged - after you kill Arkaneth Turncoat (34k:60k) and loot him - quest is considered completed BUT, after that, waypoint says that you need to talk to same mob, you've just killed.

**Comment by sioding** [comment] 2018-08-29 18:42
Duplicate of #11615

**Comment by Rockalypse** [comment] 2018-08-30 22:28
Is there any chance that quest finisher will be applied to some item placed near Traitor to fix chain quest?

**Comment by Rockalypse** [comment] 2018-08-30 22:28
@sioding

**Comment by sioding** [comment] 2018-08-31 07:09
I will discuss that with my lead - a temp fix seems to be a good idea until we have that scripting.

**Comment by sioding** [comment] 2018-09-01 06:34
Hey - discussed it with my lead and this change would really change the lore of the quest. Since we can not change the faction of Arkaneth Turncoat while you are talking to him - i can not change this (even with a temp fix) we will wait for the possibility to do that. Since then the original tasks remains open: #11615

**Closed by sioding** 2018-09-01 06:34 UTC
Labels: Database, Quests
