### ISSUE TITLE
Quest: Choose your Fate - Highelf Eataine - can not be finished

### ISSUE THREAD

**Issue by Latemoon83** [WarEmu/WarBugs#10911] opened 2017-11-25 16:38 UTC
Dear Supporter...

It's not possible to complete the Quest to klick one of the 8 objekts of fate. If you want to complete the Quest, you must klick to the NPC ("Forgotten Seer") in the middel of the 8 fates. But the Quest-Info say... choose one of this fates to complete the quest.

The second issue is, its not possible to finish the quest and get the reward. The Map shows me a red circle around the NPC named "Forgotten Seer" to finished it, but there is nothing.

Thank you...

![latemoon_012](https://user-images.githubusercontent.com/33985355/33232458-25095fbe-d207-11e7-9735-041b44d14283.jpg)
![latemoon_013](https://user-images.githubusercontent.com/33985355/33232462-2d326c3a-d207-11e7-9635-be60f09cb342.jpg)
![latemoon_014](https://user-images.githubusercontent.com/33985355/33232463-307be038-d207-11e7-860f-742e371f30a0.jpg)

**Comment by thorbolt80** [comment] 2017-11-26 05:22
Already report : Quest: Choose Your Fate #6523

**Comment by sioding** [comment] 2017-11-26 06:11
Duplicate of #6523

**Closed by sioding** 2017-11-26 06:11 UTC
Labels: Database, Quests
