### ISSUE TITLE
Unable to Progress t1 Epic Quests that require killing monsters in PQ areas while in group

### ISSUE THREAD

**Issue by Joerosion** [WarEmu/WarBugs#16811] opened 2020-05-14 00:09 UTC
Hello!

While in a group, we were trying to do "Da Stick's Da Fing" and "Legend and Infamy," two t1 epic quests. For Da Stick's Da Fing, one of the first stills is to kill vermin in the Sharpthorn Mine. Despite killing the vermin, I wasn't getting quest credit.

So, we left to do Legend and Infamy in The Blighted Isle. There, we had a quest to kill Nimosar Elves. Again, we were not getting quest credit for our kills. Then, we dropped group and tried again — and we got quest credit.

I'm going to go kill Mine Vermin solo to see if that works for Da Stick's Da Fing, too.

Strange behavior!

**Comment by Lheana** [comment] 2020-05-16 15:38
Duplicate of #12470

**Closed by Lheana** 2020-05-16 15:38 UTC
Labels: Public Quests, Quests
