### ISSUE TITLE
Bug, game broken, cant do anything.

### ISSUE THREAD

**Issue by Florcituzz** [WarEmu/WarBugs#13640] opened 2019-03-14 08:16 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Cant do anything, just use right click, and nothing more.

**Steps to reproduce the problem:**
Te evidence is on the video.

**Screenshots/Videos or archive.org evidences:**
https://youtu.be/sNqV0aOWFPE
Only can use right click, nothing more.

**Comment by sioding** [comment] 2019-03-14 17:30
Duplicate of #11224

**Closed by sioding** 2019-03-14 17:30 UTC
