### ISSUE TITLE
Bolster not working on Ironclad

### ISSUE THREAD

**Issue by GlokyDW** [WarEmu/WarBugs#14082] opened 2019-05-12 22:38 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Players should get bolstered to balance scenario, they don't. Tested in T1 scenarios

**Steps to reproduce the problem:**
Just enter scenario

**Screenshots/Videos or archive.org evidences:**

![issue](https://user-images.githubusercontent.com/50557544/57588633-42631c80-7517-11e9-94a5-d8b0f59e6b27.png)

**Comment by sioding** [comment] 2019-05-13 05:34
Duplicate of #12600

**Closed by sioding** 2019-05-13 05:34 UTC
