### ISSUE TITLE
Auto attack, none crit for 10k+

### ISSUE THREAD

**Issue by Parallell86** [WarEmu/WarBugs#14335] opened 2019-06-03 19:17 UTC
**Expected behavior and actual behavior:**

Not much to say. I am a deftard Knight. I got hit by none-ability damage for 10k in total. 6.4k damage mitigated. Screenshot shows it.

**Steps to reproduce the problem:**

Ask this guy to hit you?

**Testing Screenshots/Videos/Evidences (always needed):**

https://imgshare.io/image/2nqOY

**Comment by sioding** [comment] 2019-06-04 05:29
Duplicate of #14334

**Closed by sioding** 2019-06-04 05:29 UTC

**Comment by Parallell86** [comment] 2019-06-04 14:07
No, my case was an auto attack. I think it has more to do with the player than a class/ability related bug...
________________________________
Från: Alexander Eckert <notifications@github.com>
Skickat: den 4 juni 2019 07:29
Till: WarEmu/WarBugs
Kopia: Parallell86; Author
Ämne: Re: [WarEmu/WarBugs] Auto attack, none crit for 10k+ (#14335)


Closed #14335<https://github.com/WarEmu/WarBugs/issues/14335>.
