### ISSUE TITLE
Level 5 Green Strength potions do not create for Apothecary

### ISSUE THREAD

**Issue by Disturbedend** [WarEmu/WarBugs#11785] opened 2018-05-20 01:01 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected: create level 5 green strength potion
Actual: creates " another junk item"

Steps to reproduce the problem:
combine a bottle the plant and a few stabilizers to get the potion make to be 100 percent chance

Screenshots/Videos or archive.org evidences:
I dont have that ability currently

**Comment by sioding** [comment] 2018-05-20 03:56
Duplicate of #10660

**Closed by sioding** 2018-05-20 03:56 UTC
