### ISSUE TITLE
T3 Epic Quest - Cleansing an Empire broken

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15542] opened 2020-01-25 12:57 UTC
This quest is broken for weeks now at the following part:

![t3epicq](https://user-images.githubusercontent.com/59058934/73121437-7897dd80-3f7a-11ea-9f2d-13911b8a7ba2.jpg)

**Comment by Kabucoror** [comment] 2020-01-25 13:29
Duplicate of ##15441

**Closed by Kabucoror** 2020-01-25 13:29 UTC
