### ISSUE TITLE
[Fortress} Reservation after crash while in fortress still not working

### ISSUE THREAD

**Issue by Mercenery** [WarEmu/WarBugs#13587] opened 2019-03-10 01:23 UTC
Like i said in the title the reservation after crash is not working. Its really annyoing when your group is in and you cant join after crash esp when you are the healer

**Comment by Frostlatte** [comment] 2019-03-10 02:00
sign...

after crash you cannot port into fort. After 5Min you gain the announcement, that yor reservation is expired ... and you were clicking outside.

**Comment by sioding** [comment] 2019-03-10 06:16
Duplicate of #13583

**Closed by sioding** 2019-03-10 06:16 UTC
