### ISSUE TITLE
Dragon's bane scenario mount escamotage

### ISSUE THREAD

**Issue by Balinorr** [WarEmu/WarBugs#16437] opened 2020-04-19 23:01 UTC
Hello, i've discover that in the "Dragon's bane" scenario, if you have the event's mount "Eastern Wyvern hatchling mount", you can mount it whyle carrying the dragon's beacon.
![Balinor_012](https://user-images.githubusercontent.com/62892299/79702084-5fb17680-82a2-11ea-9dd8-5ad3fb1f8e67.jpg)
![Balinor_013](https://user-images.githubusercontent.com/62892299/79702086-6213d080-82a2-11ea-95cb-81f2d6efa171.jpg)
![Balinor_014](https://user-images.githubusercontent.com/62892299/79702088-650ec100-82a2-11ea-8e7a-13989b5a59bd.jpg)
![Balinor_017](https://user-images.githubusercontent.com/62892299/79702095-6f30bf80-82a2-11ea-8836-cdc026ed6b67.jpg)

**Comment by Kaelang** [comment] 2020-04-19 23:04
Duplicate of https://github.com/WarEmu/WarBugs/issues/16427.

**Closed by Kaelang** 2020-04-19 23:04 UTC
