### ISSUE TITLE
Marauder - Gift of Montrosity bug

### ISSUE THREAD

**Issue by sinadin** [WarEmu/WarBugs#11203] opened 2018-01-23 15:58 UTC
after the ability "Gift of Monstrosity" is used while bolstered in T4, it heals for the full bolstered amount all the time until you switch to a different Gift or relog, even if you are back to pve to your usual leveling

**Comment by sioding** [comment] 2018-01-23 17:13
Duplicate of #10231

**Closed by sioding** 2018-01-23 17:13 UTC
