### ISSUE TITLE
visual bug engineer and ironbreaker look naked if they wear full conqueror

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12583] opened 2018-11-14 09:04 UTC
Screen of the warrior priest who see me naked and mine screen (with clothes) (for ironbreaker is the same)

![thorbolt_538](https://user-images.githubusercontent.com/16274785/48471525-5cd06d80-e7f4-11e8-98d3-3cd7ab7cf963.jpg)

![image](https://user-images.githubusercontent.com/16274785/48471561-770a4b80-e7f4-11e8-9a4a-7ffa3457ee30.png)

**Comment by sioding** [comment] 2018-11-14 13:10
Duplicate of #12341

**Closed by sioding** 2018-11-14 13:10 UTC
