### ISSUE TITLE
Edit: Casting heals on chracter not in line of sight bugs casting on that character even if It get back in sight 

### ISSUE THREAD

**Issue by Rongard** [WarEmu/WarBugs#928] opened 2015-07-02 17:33 UTC
So, as a healer (played runepriest nad zealot) if you have someone in defensive target out of range of your spells and you start cast spells. The animation goes out but heals dont. That is OK (well not completely ok, but you can live with that :) ), but from that point on no heals go through even if you get back in range of your target. 
You have to clear your target and retarget him again. Than you can heal again.

Edited: so I kept trying to find out and the range is not problem. It is the line of sight.

**Comment by Silentguard** [comment] 2015-07-08 10:58
Should be same with any case where you targeting frined not in LOS and when he become visible spells stay still retargeted to you.

**Comment by ozarmidrashim** [comment] 2015-07-09 16:30
Cannot reproduce this on the test server.

**Comment by xyeppp** [comment] 2015-07-09 17:53
Start healing somebody and make them run out of range, now when he comes back in range even though you still have him targeted every heal will redirect to you anyways.

**Comment by ozarmidrashim** [comment] 2015-07-10 08:26
It's behaving differently on the test server.

**Comment by mickeye** [comment] 2015-07-10 09:22
I have very same experience on Shaman, and same goes for my friend Runepriest. Healing won't go off unless you retarget character again.

**Comment by Rongard** [comment] 2015-07-11 19:35
I edited the bug, because it is not the range that causes that, but line of sight

**Comment by ozarmidrashim** [comment] 2015-07-13 09:46
Fixed in next.

**Closed** 2015-07-13 11:55 UTC
Labels: Fix Pending
