### ISSUE TITLE
Guild Vault 3 Issue

### ISSUE THREAD

**Issue by Madgrimm** [WarEmu/WarBugs#16537] opened 2020-04-28 08:27 UTC
I got a problem to buy the third Guild Vault. I guess it could not be, that the price is actually real? 
Is it?

! [Vault02](https://user-images.githubusercontent.com/64464218/80464852-abb38980-893a-11ea-8a45-1c7b46e1031f.jpg)

Thanks for answers.
Greetings Madgrimm

**Comment by thorbolt80** [comment] 2020-04-28 11:48
For my guild it's impossible vault 3 cost : 160 023 gold !

**Comment by Kaelang** [comment] 2020-04-28 13:46
Duplicate of https://github.com/WarEmu/WarBugs/issues/16297.

**Closed by Kaelang** 2020-04-28 13:46 UTC
