### ISSUE TITLE
Questlinks broken

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15482] opened 2020-01-13 21:10 UTC
Questlinks don't show rewards anymore.
https://wiki.returnofreckoning.com/index.php/Empire_T1_Epic_Quest_The_Emperor%27s_Mandate

**Comment by Kaelang** [comment] 2020-05-05 23:10
Duplicate of https://github.com/WarEmu/WarBugs/issues/15217

**Closed by Kaelang** 2020-05-05 23:10 UTC
Labels: Sourcecode
