### ISSUE TITLE
SC Teleported to Altdorf followed by Character Select UI

### ISSUE THREAD

**Issue by Akkere** [WarEmu/WarBugs#12966] opened 2018-12-28 01:55 UTC
Expected behavior and actual behavior:
Instead of going to the SC (Black Crag Keep), was teleported to Altdorf. Oddly enough, the interface was now overlayed with the character select UI. 
While in this state, I was able to move around and take screenshots. My party confirmed that at least one of the people there (the player Cowboybebop) was apparently in the SC on their end, though I was not able to verify anyone else, nor was I able to see my party members. 
Clicking 'Play' didn't seem to do anything; clicking 'Delete' brought up the confirmation message (Are you sure you want to delete <Character Name>)  which I did not pursue further (probably shouldn't have clicked 'Delete' to begin with). Clicking 'Settings' brought up the appropriate menu. Clicking everything else (Servers, Create, Quit, Play) does nothing. 
Time of occurrence was around 8:20 PM 
I forcibly closed and re-launched the game with no issues; logging back into the character took me back to Altdorf. 

Steps to reproduce the problem:
Approximate steps that lead to this problem;
Was queued with a party for SCs while also doing an RvR in Barak Varr. Eventually, the SC queue 'popped' for Black Crag Keep, and I was able to confirm attendance of the SC. Instead of going to the SC, the underlined issue happened. 
Unfortunately, I don't really know of any other factors that could be considered specifically to replicate this issue. I do have the logs copied over to a seperate folder before I re-launched.

Screenshots/Videos or archive.org evidences:

![screenshot 2 - 8 39 pm 12272018](https://user-images.githubusercontent.com/8823422/50499606-f22c6780-0a18-11e9-9d54-e5127825af2f.png)
![untitled](https://user-images.githubusercontent.com/8823422/50499608-f22c6780-0a18-11e9-9452-b68ced0ffb4b.png)

**Comment by sioding** [comment] 2018-12-28 15:15
Duplicate of #11224

**Closed by sioding** 2018-12-28 15:15 UTC
