### ISSUE TITLE
Order unlocks Chaos Story in Nordland

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#465] opened 2014-11-15 17:16 UTC
reproduction - as order, just walk to Chaos Chapter 4 in Nordland and you will unlock the Chaos story.

**Comment by milosxe** [comment] 2015-09-21 18:35
This is working as intended. You can unlock the story lines of the opposing faction by approaching the quest hubs. It was the same on live too. Closing.

**Closed by milosxe** 2015-09-21 18:35 UTC
