### ISSUE TITLE
Alternate appearence doesnt work for cloak

### ISSUE THREAD

**Issue by Ladypsyco** [WarEmu/WarBugs#19418] opened 2021-09-01 14:46 UTC
![F06C8607-6249-41B1-9AA5-CD19922298BD](https://user-images.githubusercontent.com/42930467/131692587-fd126c5c-c38c-4f02-b1d4-3724b48e636a.jpeg)
![FAC53518-5961-4755-9C21-01C9BBF1BB73](https://user-images.githubusercontent.com/42930467/131692597-dc4e21e1-18a7-4292-8946-b467c31ae023.jpeg)

As you can see both of us are wearing alternate appearence cloaks but they will show just for us, anyone else see the appearence of the original cloak we're wearing, we could test this issue on destruction side as well, it's bugged on that side too. We also checked if the items could have alternate appearence, and from the tooltip of the mouse over the items it say we can.

Thank you.

**Comment by CrimsonFenris** [comment] 2021-09-08 23:14
Related to https://github.com/WarEmu/WarBugs/issues/19266

**Comment by dalen** [comment] 2021-09-14 07:40
duplicate of #18556

**Closed by dalen** 2021-09-14 07:40 UTC
Labels: Item, Visual
