### ISSUE TITLE
Ill Omens Tome Unlock Missing

### ISSUE THREAD

**Issue by SecretsOTheP** [WarEmu/WarBugs#15761] opened 2020-02-22 23:12 UTC
**Expected behavior and actual behavior:**

There is a tome unlock at 45k, 25k in Nordland

**Steps to reproduce the problem:**
Observe the lack of object to interact with

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/319552/75100676-e4cc2800-559e-11ea-9a1e-b0951d4e2f77.png)

**Comment by Lheana** [comment] 2020-02-23 14:54
This is a proximity unlock which can not be implemented for now.
Duplicate of #8401

**Closed by Lheana** 2020-02-23 14:54 UTC
