### ISSUE TITLE
Knight of the Blazing Sun (Huge AuraBug)

### ISSUE THREAD

**Issue by Jubok21** [WarEmu/WarBugs#13211] opened 2019-01-27 15:14 UTC
On Your Guard is bugged a lot 👎  you can despawn all monster with this... it can a level 1 mob be or a level 50 lord. All time u use this Aura you can despawn mobs and raid so easy Warcamps etc,.
![kotbs](https://user-images.githubusercontent.com/19917328/51802871-8a9f4d00-224e-11e9-8420-7965a8ef66ad.png)

**Comment by sioding** [comment] 2019-01-27 15:16
Duplicate of #13206

**Closed by sioding** 2019-01-27 15:16 UTC
