### ISSUE TITLE
Cant login in altdorf

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#10953] opened 2017-12-04 13:06 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 
Can't re-login when u logged out near the SC mission NPC in altdorf. 
It will shut down the game when u re-login to the game

PS. Other characters is fine, when i use other character and log out near that NPC zone, the problem will occur too.
 
That zone may be around the market zone of altdorf

Steps to reproduce the problem: N/A

Screenshots/Videos or archive.org evidences: N/A

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2017-12-04 13:58
Duplicate of #10951

**Closed by sioding** 2017-12-04 13:58 UTC
