### ISSUE TITLE
Raven Host Vanguard PQ - Second Stage seems to be bugged - cannot progress

### ISSUE THREAD

**Issue by zamoysky** [WarEmu/WarBugs#13263] opened 2019-02-02 22:11 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Mobs should spawn. The quest seems stuck at the end of the second stage, I can see dead mobs, but the quest doesn't reset? We checked up on the quest after 10-20 minutes, it was in the same state. 

Steps to reproduce the problem:

Enter the PQ area. 

Screenshots/Videos or archive.org evidences:

https://imgur.com/a/wjw2DGV

**Comment by sioding** [comment] 2019-02-03 03:40
Duplicate of #12685

**Closed by sioding** 2019-02-03 03:40 UTC

**Comment by WO-RoR-Exile** [comment] 2019-12-03 12:31
Still an issue. 12/03/2019.
![Argog Bug](https://user-images.githubusercontent.com/58471571/70051396-922e3180-1596-11ea-9a9d-88a3bfb0632a.png)
