### ISSUE TITLE
Guild Heraldry Issue

### ISSUE THREAD

**Issue by Kruelistik** [WarEmu/WarBugs#15625] opened 2020-02-04 14:09 UTC
When I chose the heraldry for my guild Unsainted it didn't take, after a re-log, I tried again and only the pattern and colour took but not the emblem. I re-logged again and even spent the 100g trying to get the heraldry to implement. Still after many tries I can't get the emblem I choose to stay. Please advise/fix and maybe reimburse :D

**Comment by Kaelang** [comment] 2020-04-19 16:36
Duplicate of https://github.com/WarEmu/WarBugs/issues/9791.

**Closed by Kaelang** 2020-04-19 16:36 UTC
Labels: Guilds
