### ISSUE TITLE
Barak Var - keep lord bugged.

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13662] opened 2019-03-17 13:46 UTC
![Elflord_043](https://user-images.githubusercontent.com/48329663/54492035-2f93e900-48d4-11e9-9dc4-160dc6446399.jpg)
Lord runs out of his room

**Comment by sioding** [comment] 2019-03-17 16:04
Duplicate of #13588

**Closed by sioding** 2019-03-17 16:04 UTC
