### ISSUE TITLE
bypassing the cooldown on items with cooldown

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#11258] opened 2018-02-04 20:58 UTC
Items that reset cooldowns on zone change or entering an instance/scenario: 

-Subjugator cloak
-Beastlord Book
-Book of Binding
-Battlebrew backpack
-the beer that transports you to a tavern in Altdorf, I cannot remember the name

Possibly all items with CD's like potions aswell. 

On transitioning zones or entering instances reset the CD's on these items but the CD is displayed on the item as it should.

**Comment by sioding** [comment] 2018-02-05 08:35
Duplicate of #10382

**Closed by sioding** 2018-02-05 08:35 UTC
