### ISSUE TITLE
[Shadow warrior] Devastator helm

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#2238] opened 2015-12-08 20:26 UTC
Hair
![ripliel_012](https://cloud.githubusercontent.com/assets/16005849/11667441/2c1eeff8-9e0b-11e5-8e05-bd26df370da9.jpg)

**Comment by Torquemadra** [comment] 2016-02-15 03:26
Thats not the devastator helm as it stands in the database this is and helmet type sw helms generally have hair flowing. 

![torquesw_000](https://cloud.githubusercontent.com/assets/16200780/13039187/edf4c2ea-d369-11e5-99ca-9486534338f9.jpg)

**Comment by Evildoor** [comment] 2016-03-02 11:18
Closing as not a bug.

**Closed by Evildoor** 2016-03-02 11:18 UTC
Labels: Confirmation Request, Database, Item, Visual
