### ISSUE TITLE
dungeon quests do not register boss kills

### ISSUE THREAD

**Issue by Tenaciousbufhel** [WarEmu/WarBugs#16844] opened 2020-05-16 00:35 UTC
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

![image](https://user-images.githubusercontent.com/65429915/82105853-8a4cee80-96eb-11ea-9437-13d4e08d0063.png)

![image](https://user-images.githubusercontent.com/65429915/82105863-96d14700-96eb-11ea-8815-97675c6d995b.png)

![image](https://user-images.githubusercontent.com/65429915/82105868-a0f34580-96eb-11ea-998b-4a1e1f61ba41.png)

**Comment by Kaelang** [comment] 2020-05-16 00:53
![image](https://user-images.githubusercontent.com/60117106/82106233-96e73c00-9717-11ea-9212-a13559e1d754.png)
![image](https://user-images.githubusercontent.com/60117106/82106279-dada4100-9717-11ea-9f45-5c9931f2d8af.png)
![image](https://user-images.githubusercontent.com/60117106/82106310-f6dde280-9717-11ea-8077-29cb65c9ab32.png)

Just tested all three - working as intended.

You was potentially locked out of some of the boss' and/or died during the encounter and wasn't given credit based on time spent out of the fight.

Your screenshots don't suggest you have killed Barakus, and thus the quest wouldn't trigger.

Closing.

**Closed by Kaelang** 2020-05-16 00:53 UTC

**Comment by turki79** [comment] 2020-10-10 13:45
this issue is back again
