### ISSUE TITLE
Guild Roster

### ISSUE THREAD

**Issue by zeuspwner** [WarEmu/WarBugs#11184] opened 2018-01-21 19:49 UTC
![guildroster](https://user-images.githubusercontent.com/35667443/35198281-e0c1690a-feb1-11e7-91c2-b9c8ce68d6a8.jpg)
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When logged in, myself and other within guild cannot view guild roster. at profile screen, shows 1/1. however, we can still chat in guild.

Steps to reproduce the problem:
Login and log out?

Screenshots/Videos or archive.org evidences:
![guildprofile](https://user-images.githubusercontent.com/35667443/35198278-de4febce-feb1-11e7-92bc-43017d987dae.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by zeuspwner** [comment] 2018-01-21 19:51
bug with enemy addon

**Comment by zeuspwner** [comment] 2018-01-23 01:02
my mistake, i thought was from an addon, i removed the addon, logged in following day, and issue has returned. others in guild say still same issue, cannot view guild roster(displaying 1/1)

**Comment by szejoza** [comment] 2018-01-26 08:07
Same was reported here, seems quite known:
https://github.com/WarEmu/WarBugs/issues/1438

**Comment by sioding** [comment] 2018-01-26 14:03
Duplicate of #1438

**Closed by sioding** 2018-01-26 14:03 UTC
