### ISSUE TITLE
Rank 9 jewelry Flameguard's Feeble Mark has 82 armor

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4837] opened 2016-03-09 13:11 UTC
Got it from a PQ bag in Troll Country, either from Slayer's Demise or Plague Trolls.

![verdammt_018](https://cloud.githubusercontent.com/assets/6838946/13636180/c28ed696-e600-11e5-96c3-d0c0a1cb4734.jpg)

**Comment by Evildoor** [comment] 2016-03-09 13:13
Same item as in #4822, but the problem is different, so not closing this.

**Comment by wargrimnir** [comment] 2017-04-11 18:29
Removed armor and Skill requirement.

**Closed** 2017-04-16 12:29 UTC
Labels: Database, Fix Pending, Item
