### ISSUE TITLE
Irobreaker tactic "Punishing Knock" bugged

### ISSUE THREAD

**Issue by Balinorr** [WarEmu/WarBugs#16148] opened 2020-03-30 14:20 UTC
Hello. I' ve realized that recently the irobreaker tactic "punishing knock" stop working whenever i change zone ( travel or enter/exit scenario). To let it working again i must to remove it and to put it back. How i' ve already told it' s something recent, before it was ok. Thanks for the attention.

**Comment by funnytroll** [comment] 2020-03-30 14:25
You re not alone)
https://github.com/WarEmu/WarBugs/issues/15857
Some of us waiting 4 weeks the fix)

**Comment by Zouldato** [comment] 2020-04-03 13:59
Hi guys

Just wanted to add in as I have coem across this bug as well playing my IB recently. I had to do two identical tactic bars and jjust switch to the other once zoning. But I have been zoning and playing SCs now putting Punishing Knock as the 4th tactic on the tactic bar (last tactic to the right) and that seems to have fixed the issue for me. 

/BR

**Comment by Kabucoror** [comment] 2020-04-03 14:05
duplicate of #15857

**Closed by Kabucoror** 2020-04-03 14:05 UTC
