### ISSUE TITLE
gold bag empty

### ISSUE THREAD

**Issue by Gstarhk** [WarEmu/WarBugs#10712] opened 2017-10-29 17:30 UTC
![gstark_028](https://user-images.githubusercontent.com/30270344/32146385-e6b21a8e-bcd6-11e7-98a5-7db7183be1d5.jpg)

Gold bag from t4 eataine but no conqueror gear...

**Comment by sioding** [comment] 2017-10-29 19:16
Duplicate of #10279

**Closed by sioding** 2017-10-29 19:16 UTC
