### ISSUE TITLE
"Bugman's XXXXXX" quest item

### ISSUE THREAD

**Issue by JeFawk** [WarEmu/WarBugs#116] opened 2014-05-10 12:33 UTC
Dropped by Kruk'tar the Drunken but I'm not sure if the drop is correct...as stated here, it shouldn't happen. http://warhammeronline.wikia.com/wiki/Kruk%27tar_the_Drunken

Item should start a quest I believe ? Also the name is wrong.

![image](https://cloud.githubusercontent.com/assets/7268697/2935965/eae58f48-d83a-11e3-832c-91e676e6550b.png)

**Comment by Reggaewaldo** [comment] 2015-09-21 07:27
The Bugman's XXXXXX is dropped by Kruk'tar as intended and is part of Quest Woebegone III:
http://warhammeronline.wikia.com/wiki/Woebegone_III

Set object level to 3.

This will roll over to the live server with the next hotfix.

Closing.

**Closed by Reggaewaldo** 2015-09-21 07:27 UTC
Labels: Database, Item, Low Priority, Quests
