### ISSUE TITLE
Caledor Woods' flag

### ISSUE THREAD

**Issue by Minipuce** [WarEmu/WarBugs#11808] opened 2018-05-26 18:21 UTC
The flag in the scenario "Caledor woods" seems buggued : taken by the destruction, it didn't change when all the destruction were dead and all the order wb was on the flag

Expected behavior and actual behavior:
Flag was expected to become blue for order.. and remained red for destruction

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![minipuce_078](https://user-images.githubusercontent.com/39655844/40579182-2e1d9020-6122-11e8-9679-c53f273a73c7.jpg)

**Comment by sioding** [comment] 2018-05-26 20:38
Duplicate of #11478

**Closed by sioding** 2018-05-26 20:38 UTC
