### ISSUE TITLE
Fly to Garden of Qu'aph

### ISSUE THREAD

**Issue by eeppuJ** [WarEmu/WarBugs#20174] opened 2022-06-10 12:45 UTC
**Expected behavior and actual behavior:**

When I fly to the Garden of Qu'aph, I should be teleported to the Garden of Qu'aph.
But, when I fly to the Garden of Qu'aph, I'm teleported to the rally master at IC.

**Steps to reproduce the problem:**

Use the TP or the fly in the city.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/9798696/173066974-142d7a85-ac0a-4f7f-b3da-81572dbe59ae.mp4

https://user-images.githubusercontent.com/9798696/173066978-d8722b2e-b33b-49f2-8766-74fbabb0fbc8.mp4

**Comment by MaxHayman** [comment] 2022-06-20 19:03
Seems to work fine. Please reopen if this is not the case.

**Comment by lilimx** [comment] 2022-06-27 17:51
Looks like it doesn't work: #20221

**Comment by GamesBondd** [comment] 2022-06-28 17:37
@MaxHayman apparently on Destruction side, it always takes you to where your book is bound.

**Comment by Rubyeclipse-war** [comment] 2022-06-29 23:12
> @MaxHayman apparently on Destruction side, it always takes you to where your book is bound. Even when it's on cooldown and when the bound rally master changes.

Tested and confirmed this is the same on Order's side. Using either the teleporter in Altdorf or flying to Garden will both send you to wherever your Book of Binding is set to.

**Comment by Kaelang** [comment] 2022-07-20 01:55
Tested on Dev and seems to be working fine? Is this still broken?

**Comment by Rubyeclipse-war** [comment] 2022-07-20 04:39
> Tested on Dev and seems to be working fine? Is this still broken?

Just tested on Live on both factions and confirmed the bug is still present. Got a short video: https://www.youtube.com/watch?v=RZWpDV5emNU

**Comment by MaxHayman** [comment] 2022-09-09 18:59
This should be fixed. Please reopen if not.

**Closed by MaxHayman** 2022-09-09 18:59 UTC
Labels: Garden of Qu'aph
