### ISSUE TITLE
KotBS Stay Focused!

### ISSUE THREAD

**Issue by Skoll888** [WarEmu/WarBugs#14147] opened 2019-05-21 16:35 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Stay Focused! automatically activated if you change the tactic slot from Focused Mending to anything else.
The result is you can have 4 auras active

**Steps to reproduce the problem:**

![Solefald_004](https://user-images.githubusercontent.com/46657401/58113912-e83d1800-7bf6-11e9-852f-ebd12301985a.jpg)
![Solefald_007](https://user-images.githubusercontent.com/46657401/58113920-ed9a6280-7bf6-11e9-9dbb-83db686ed528.jpg)

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment] 2019-05-21 16:44
Duplicate of #13368

**Closed by sioding** 2019-05-21 16:44 UTC
