### ISSUE TITLE
the Griffon Gate

### ISSUE THREAD

**Issue by frankystein65** [WarEmu/WarBugs#13515] opened 2019-03-02 04:24 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
in order to complete the epic quest a lords game, you must kill mobs in the chapter 7 elf pq the griffon gate.  status of the pq is stage 1; kill eagle claws.  no eagle claws are spawned.  no npcs are spawned

**Steps to reproduce the problem:**
access the pq.  the status in the upper right corner shows stage 1, 0/8.  

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment] 2019-03-02 06:11
Duplicate of #10862

**Closed by sioding** 2019-03-02 06:11 UTC
