### ISSUE TITLE
Auction House : Cant sell anything

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#3841] opened 2016-01-19 09:28 UTC
When I try to put up an Item on the Auction House it says Auction Cancelled,
this bug started today.

**Comment by Torquemadra** [comment] 2016-01-19 09:58
There is a cap of 50 items up per person, are you at that cap?

**Comment by Tiggonos** [comment] 2016-01-20 15:23
i recommend to alter the text from "auction cancelled" to "maximum limit of auctions reached" if possible.

**Comment by Evildoor** [comment] 2016-01-20 15:43
@Tiggonos - what's the point? If he reached the limit then it's not a bug and i'll just close this.

**Comment by Tiggonos** [comment] 2016-01-20 15:49
Well the bug is, that the msg you get is wrong or at least not useful. 



Vitus Hoffmann
Vorstand

vh@wmpag.de
Office: +49 89 5527 5025
Fax: +49 89 5527 5026
Web Media Publishing AG
Baierbrunner Str. 3, 81379 München

www.gameswelt.de | www.gameswelt.tv | www.mann.tv | www.film.tv
Vorstand: Vitus Hoffmann (Vorsitz), Sören Lohse, Michael Moser
Aufsichtsratsvorsitz: Marco Casanova lic.rer.pol
Eingetragen beim Amtsgericht München HRB 171919
 -----Ursprüngliche Nachricht-----
Von: Evildoor <notifications@github.com>
Gesendet: Mit 20 Januar 2016 16:44
An: WarEmu/WarBugs <WarBugs@noreply.github.com>
CC: Vitus Hoffmann <vh@wmpag.de>
Betreff: Re: [WarBugs] Auction House : Cant sell anything (#3841)

@Tiggonos - what's the point? If he reached the limit then it's not a bug and i'll just close this.

**Comment by Evildoor** [comment] 2016-01-20 15:52
I misunderstood you and already realized that and deleted my comment.

**Comment by geezereur** [comment] 2016-01-21 05:48
Yes its 50 up you can close this.

**Closed** 2016-01-21 06:56 UTC
Labels: Confirmation Request
