### ISSUE TITLE
[GCD] Sword Master cannot switch stances with AoE skills

### ISSUE THREAD

**Issue by JackHollowPoint** [WarEmu/WarBugs#20107] opened 2022-05-18 10:36 UTC
**Expected behavior: Using skills like Warth of Hoeth or Wispering Wind should fire, even if no targets nearby and switch stances 

**Actual behavior:  Character gets locked in the animation, skill does not fire.

Seem the issue is that skills are considered melee and single-target

**Steps to reproduce the problem: 

As SM try to use any AoE ability when not directly close to target.

**Testing Screenshots/Videos/Evidences:

https://user-images.githubusercontent.com/25168701/169019885-c7452a0d-fc43-4775-ab4d-343c912f3998.mp4

**Comment by JackHollowPoint** [comment] 2022-05-18 10:38
This one is even better showing WW not firing.
https://user-images.githubusercontent.com/25168701/169020238-820da5c8-2b35-4796-a622-0e60dd628416.mp4

**Comment by Solganis** [comment] 2022-05-18 23:37
> Hey,
> 
> could you re-check if the issue persists?

Issue still persist

**Comment by XmatXergon** [comment] 2022-05-19 06:36
The issue is not with changing stances, issue is that AoE abilities that suppose not require target, suddenly do require target (Wrath of Hoeth and Pheonix Wings) which cause issue not letting ability to fire off. If you get close to your target ability will fire off, but it will only affect stuff around but not your primary target.

There is no issue with Sudden Swift or abilities like Protection of Hoeth or Gustling Winds, those abilities does not require target and do fire off properly.

**Comment by dalen** [comment] 2022-05-20 09:20
Fixed in hotfix

**Closed by dalen** 2022-05-20 09:20 UTC
Labels: Ability, High Priority

**Comment by JackHollowPoint** [comment] 2022-05-21 19:31
Phoenix wing is still bugged
https://github.com/WarEmu/WarBugs/issues/20120
