### ISSUE TITLE
Mourkain Temple objective spawns in a random location

### ISSUE THREAD

**Issue by Bregual** [WarEmu/WarBugs#15717] opened 2020-02-18 08:33 UTC
The order player holding the objective was punted into their own secure zone. Immediately upon entering the zone the objective despawned and reappeared outside of the temple. Players on both teams were unable to pick up the objective at this point; as it was no longer interactable. The objective never respawned after this.
 
![Toolittle_001](https://user-images.githubusercontent.com/42259577/74717685-0c617000-51ee-11ea-9ba2-e12753d19f2d.jpg)

**Comment by Kaelang** [comment] 2020-04-21 23:33
Duplicate of https://github.com/WarEmu/WarBugs/issues/9542.

**Closed by Kaelang** 2020-04-21 23:33 UTC
