### ISSUE TITLE
Can't Deploy Standard

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#14546] opened 2019-07-08 18:19 UTC
Good day!
Our guild has reached level 26. Because of this, the last slot of tactics on the Warrior's Battle Standard was opened.
All three tactics on the Warrior's Battle Standard are filled and saved.
https://pastenow.ru/612U5
https://pastenow.ru/612UD
https://pastenow.ru/612UM
But while trying to call this standard displays a message about missing rights:
https://pastenow.ru/612UO
In view of the foregoing, we ask you to clarify: this is a game bug or there are additional requirements for activating the Warrior's Battle Standard.
The Recruit's Battle Standard works without complaints.
Thank.

**Comment by sioding** [comment] 2019-07-09 08:52
Duplicate of #13289

**Closed by sioding** 2019-07-09 08:52 UTC
