### ISSUE TITLE
[Quest] Trade Wars

### ISSUE THREAD

**Issue by Ywhi** [WarEmu/WarBugs#16494] opened 2020-04-24 13:25 UTC
Hello,

The quest "Trade Wars" is apparently not attached to a creature anymore.

This is the quest to have this dye:  Oathbearer Cheese Yellow Dye.

I checked the bug tracker and it was remove in 2016, i don't know why. Is it possible to have it back or atleast a way to have this Dye ?

FashionHammer purpose.

Thank you

**Comment by Kaelang** [comment] 2020-04-24 13:38
The Chapter quests are being reviewed and reworked where necessary. 

As this looks to be intended, i.e. there was a bug report you have quoted that has been closed and confirmed, I'm going to close this up but direct you to the Suggestions & Feedback Forum. 

https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Closed by Kaelang** 2020-04-24 13:38 UTC
