### ISSUE TITLE
Can Open White Loot Bags

### ISSUE THREAD

**Issue by OgiWanBG** [WarEmu/WarBugs#12736] opened 2018-11-27 18:42 UTC
Hello, I can Open White Loot Bags. Right click on them but nothing happens/appear.

Thanks,
![ogimir_012](https://user-images.githubusercontent.com/42701165/49103797-fc760d00-f284-11e8-8e26-b1b43a2e890f.jpg)

**Comment by sioding** [comment] 2018-11-27 19:32
Duplicate of #12659

**Closed by sioding** 2018-11-27 19:32 UTC
