### ISSUE TITLE
disappearing mouse.

### ISSUE THREAD

**Issue by popcornhearts** [WarEmu/WarBugs#7107] opened 2016-07-11 01:08 UTC
I logged onto the game and saw or saw a lack of a mouse pointer. It was so weird and it was very hard to click on anything without being able to see the mouse. I took some pictures of the bug. I saw other people were having this issue, but didn't see it on the bugtracker and I wanted to bring attention to it because its really hard to play. I also took a picture of my settings to show it wasn't me. Below is proof of the problem on two different characters.
![emershell_033](https://cloud.githubusercontent.com/assets/20388645/16717327/3c51d310-46e2-11e6-9973-430651c204fd.jpg)
![emershell_034](https://cloud.githubusercontent.com/assets/20388645/16717328/40d5fccc-46e2-11e6-9dc5-221dcf9f2a06.jpg)
![emrihill_003](https://cloud.githubusercontent.com/assets/20388645/16717329/4542772c-46e2-11e6-80e1-160e7c09b8ed.jpg)
![emershell_036](https://cloud.githubusercontent.com/assets/20388645/16717331/4bb22008-46e2-11e6-9e2b-9d11a1feaf24.jpg)
![emrihill_006](https://cloud.githubusercontent.com/assets/20388645/16717332/527ccff0-46e2-11e6-9c12-909f9cb6276d.jpg)

In the images I show a highlighted war image (Top screen) My settings and the mouse setting checked I also show a two abilites (Windowed Exile and Magical salvaging)

Hope this helps.

**Comment by Luth-RoR** [comment] 2016-07-11 06:40
The problem is that this is completely handled by the client and it's the mythic 1.4.8 client.
Maybe some addon could cause this?

**Comment by popcornhearts** [comment] 2016-07-11 21:44
I do not use addons

**Comment by popcornhearts** [comment] 2016-07-11 21:45
if you look closely at the last image. Magical salvaging is highlighted by the invisible mouse cursor which can't be seen.

**Comment by Elvenalthur** [comment] 2016-07-12 15:54
As Luth already mentioned, it's handled by the client. Check your UI settings and general configurations.

**Comment by xyeppp** [comment] 2016-07-16 10:50
Have you got a Logitech mouse?

**Comment by sioding** [comment] 2017-10-24 10:31
No answer is given - i´ll close this now.

**Closed by sioding** 2017-10-24 10:31 UTC
Labels: Confirmation Request, User Interface
