### ISSUE TITLE
RVR unflag in DW

### ISSUE THREAD

**Issue by pobratim** [WarEmu/WarBugs#14591] opened 2019-07-15 12:48 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by pobratim** [comment] 2019-07-15 12:49
![Orthodoxia_000](https://user-images.githubusercontent.com/42023389/61217322-15e69f00-a718-11e9-82ed-b5d1bb757b69.jpg)

**Comment by pobratim** [comment] 2019-07-15 12:50
You can easily unflag from rvr status in this place.Did it few times with same result.

**Comment by sioding** [comment] 2019-07-15 12:51
Duplicate of #9419

**Closed by sioding** 2019-07-15 12:51 UTC
