### ISSUE TITLE
Pot making Failuer

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#12535] opened 2018-11-03 09:28 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Apothecary character was Lv 18 Slayer
Buturing + Apothecary
Expect Lv1Glass+ 25 Str+Lv25Resin+Lv25 Stabilizer make some Str Pot
behabior made "Another Junk"
Stabilizer and Resin were made by my Alt (Cultivation)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![apothecary failure](https://user-images.githubusercontent.com/43213086/47950471-39a4f300-df96-11e8-9ca7-ddfd146f9afa.jpg)

**Comment by sioding** [comment] 2018-11-03 11:36
Duplicate of #10660

**Closed by sioding** 2018-11-03 11:36 UTC
