### ISSUE TITLE
Guild bug is still active - Blocking players from Logon.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#14459] opened 2019-06-22 11:55 UTC
Please reopen the bug ticket as the guildbug is still active.
I need something like 6-8 tries to logon or change a zone.

It was fixed back then when guild infos were send 20 seconds after logon.

Related bugreport is here, but needs reopening and more solving:
[https://github.com/WarEmu/WarBugs/issues/14019](url)

**Comment by sioding** [comment] 2019-06-23 13:46
Duplicate of #14019

**Closed by sioding** 2019-06-23 13:46 UTC
