### ISSUE TITLE
White bag sitting in inventory can not be opened.  

### ISSUE THREAD

**Issue by grymfyr** [WarEmu/WarBugs#12811] opened 2018-12-05 03:56 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I should be able to open the Awarded white bag

Steps to reproduce the problem:

It is sitting in my bank..it can not be opened in inventory.  I placed it in bank to hold.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-05 18:41
Duplicate of #12659

**Closed by sioding** 2018-12-05 18:41 UTC
