### ISSUE TITLE
Tor Sethai Ch22PQ - Missing purple bags

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13975] opened 2019-04-29 01:37 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
During the PQ Tor Sethai at ch 22 in Caledor, the PQ "announces" that 5 purple bags will be given to people, as seen in the first picture. If you look at the second picture, you can see that only 3 purple bags are given and that 2 persons are given nothing even tough they have a high ranking. After talking with the groupmates in question, they confirmed that they didnt received a bag. While writing this, I've figured out what's wrong. If you look at the last line chat i've got from Katalmach in the second picture, he says that he's received a purple bag and from the first picture, it says he should have won a gold bag. I know that he "opt out" of the gold bag, the same as me. It looks like to me that the system considers the request of the player that "opt out" and since they won a gold loot bag, gives them an inferior one that was amongs the 5 originally given. In that case, the 7th and 9th person who were suppose to have a purple bag are given nothing.

We've done it multiple times and it seems that it is always the 7th and the 9th position that are given nothing. Not sure on why those two specifically tough.

Greetings,

**Steps to reproduce the problem:**
Finish the PQ Tor Sethai and finish in 7th or 9th place.

**Screenshots/Videos or archive.org evidences:**
![Rasila_000](https://user-images.githubusercontent.com/16641170/56873014-30ed2100-69fd-11e9-9a72-d14762bfeef1.jpg)
![Rasila_002](https://user-images.githubusercontent.com/16641170/56873015-30ed2100-69fd-11e9-970e-d225f347a948.jpg)

**Comment by sioding** [comment] 2019-04-29 16:41
Duplicate of #13976

**Closed by sioding** 2019-04-29 16:41 UTC

**Comment by sioding** [comment] 2019-04-29 16:44
@benitoben20 i moved both of your reports into one cause i guess the opt out brings out the missing purple bags. so as you stated out: if you opt out you don't get a golden bag but a purple one - so the amount of purple bags are given out - but the ppl who opted out do also count as given out purple bags.
