### ISSUE TITLE
Sc Gates of Ekrund T1, teleported to PVE T1 dwarfs, still in sc party.

### ISSUE THREAD

**Issue by Estigia59** [WarEmu/WarBugs#16504] opened 2020-04-25 12:15 UTC
Hi,
I was supposed to appear in the sc Gates of Ekrund with my T1 char, but I appeared in the PVE zone T1 dwarfs. I was in the sc party though, but not in the sc. 
Thank you.
![Josefa_000](https://user-images.githubusercontent.com/29825413/80279577-8d5d4c00-86f6-11ea-8260-ab18ca83ef04.jpg)

**Comment by Kaelang** [comment] 2020-04-25 12:21
Duplicate of https://github.com/WarEmu/WarBugs/issues/16500.

**Closed by Kaelang** 2020-04-25 12:21 UTC
