### ISSUE TITLE
[Quest] Lionsbane banner, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1746] opened 2015-10-28 01:41 UTC
Hello,

I kill the Gaethin Whitemane NPC but he won't drop his shield (quest item).

**Comment by Meralors** [comment] 2015-10-28 10:12
Same as #1747 and #1737 , I'm trying to figure out why its happening

**Comment by Reggaewaldo** [comment] 2015-11-06 14:07
It will be fixed with next update that should happen rather soon. The issue is that the quest DB has not been updated.

**Closed by Reggaewaldo** 2015-11-06 14:07 UTC
Labels: Database, Quests
