### ISSUE TITLE
Message for report by system

### ISSUE THREAD

**Issue by Fealle** [WarEmu/WarBugs#16484] opened 2020-04-23 20:30 UTC
I was in fortress and something was wrong with my contribution : message system with screenshot here.
thanks for your help

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-04-23 20:38
Duplicate of https://github.com/WarEmu/WarBugs/issues/16409

**Closed by Kaelang** 2020-04-23 20:38 UTC
