### ISSUE TITLE
[Zealot] Waves of chaos - never crit with Ritual of Superiority - when the other rituals crit.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15771] opened 2020-02-23 11:04 UTC
For unknown reason dmg from tact does't crit with  Ritual of Superiority -  it's kida simmilar to magus Dissolving mist.

+ in terms of ballance dmg proc is required a tactic slot, but doest benefit from int as other similar abilities.

ps. this abil still got wrong base dmg issue https://github.com/WarEmu/WarBugs/issues/12454 u can see that in that times it critted.(https://user-images.githubusercontent.com/13465031/46957171-7032d080-d0b0-11e8-8ff1-8cf5d81ca837.jpg)

![image](https://user-images.githubusercontent.com/13465031/75110854-1d2e3d80-5655-11ea-8ca6-6e6130b32c0e.png)

**Comment by RoR-Zomega** [comment] 2020-02-23 12:46
It crits fine. Your harbinger might be bugged after changing zone though which could have have your magic crit chance at 0% unless you disabled/re-enabled Harbinger (that issue is on the bug tracker). I just tried the tactic a moment ago and got crits immediately.

![Zomega_154](https://user-images.githubusercontent.com/60266177/75112304-750b7b00-563a-11ea-8756-7227125d516d.jpg)

**Comment by RoR-Zomega** [comment] 2020-02-23 12:54
I've deleted my first reply as I've now tested the tactic with all 3 rituals. It crits fine with Ritual of Lunacy and Ritual of Innervation but it doesn't crit with Ritual of Superiority.

**Comment by Kweedko** [comment] 2020-02-23 12:59
> I've deleted my first reply as I've now tested the tactic with all 3 rituals. It crits fine with Ritual of Lunacy and Ritual of Innervation but it doesn't crit with Ritual of Superiority.

Ty for clarifying. Tunned a issue name.

**Comment by grunbag** [comment] 2020-03-27 22:40
Proc never crit since 1.2.0 . This work as intended. I’ll fix the ritual that crit with it

**Comment by grunbag** [comment] 2020-04-03 08:05
Fixed with next patch . I also fixed an issue causing ritual of lunacy heal to not crit . The heal will correctly crit

**Comment by RoR-Zomega** [comment] 2020-04-08 23:28
@grunbag Ritual of Lunacy still does not heal crit

**Closed** 2020-04-19 13:35 UTC
Labels: Ability, Fix Pending
