### ISSUE TITLE
Ground targeted AoE "leaking" underneath keep doors

### ISSUE THREAD

**Issue by kalmatar** [WarEmu/WarBugs#13424] opened 2019-02-21 12:34 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Keep door is an obstacle that is there is to behave as a barrier, so damage should not be leaking through or below it. 
This issue started appearing last July, and I have repeatedly posted it on RoR Discord but looks like over past 7 months or so no one has actually bothered to make bug report over it, and I tried searching if someone has, but couldn't at least find any. 

spells that for example leak through; Sorc PoS , BW RoF, Engi/Magus ground targeted spells, Magus Firestorm etc... partially even Shaman/AM snare puddles can slightly leak through when placed just at the piece of land where door meets ground. 
Technically it's "balanced" as both realms do it, but most likely it is not intended behaviour. (also allows defenders to soak up weak hits from fail aoe and build morales so in theory this bug favours them - and they can use ground targeted AoE from inside, placing it right at doors edge to hit enemies that close to the door on the outside while in safety of keep)

Steps to reproduce the problem:

place ground targeted aoe as close to the door as you can
certain portion of it is now effectively affecting the ground behind the door 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2019-02-21 18:20
Duplicate of #5323

**Closed by sioding** 2019-02-21 18:20 UTC

**Comment by kalmatar** [comment] 2019-02-22 12:14
I think this is slightly different than that thread, as this issue only started last July. (before that a door properly prevented ground targeted aoe from leaking through)
And this is about ground targeted aoe having part of the ground effect placed so that it appears behind door. 
The other thread is about spells/ranged dmg somehow still travelling through the door obstacle. (in my experience, only in very laggy fights if the missile is still "moving" and due to lag server doesnt stop movement due to barrier blocking it)

But, they could stem from same issue, dunno.
