### ISSUE TITLE
[Brutal Ring of the Horned Rat] ring glitch skill point refund on removal 

### ISSUE THREAD

**Issue by abandonctrl** [WarEmu/WarBugs#9091] opened 2017-02-06 00:11 UTC
So each time I take this ring off it unskills my last mastery in my carnage tree . If i put it on it says i gained a skill point if I take the ring off it says I lost a skill Point?

http://imgur.com/a/TkHkW is the ring equipped

http://imgur.com/a/EOE0d is when i take it off it refund back a skill point? 

weird its been happening since the last update. It should only be the case if I remove a piece of ruin gear but im not.

**Comment by Blaqwar** [comment] 2017-02-06 15:06
This is a known issue that's been present since the T4 sets were introduced (afaik). It's because of how the server avoids having to recheck your whole gearset for the +1 to mastery bonus, this is bypassed by simply resetting the +1 bonus every time you equip/unequip _any_ piece of gear.

Easiest way to deal with this is to use an addon to be able to retrain the mastery point on the spot.

#8189

**Comment by Luth-RoR** [comment] 2017-02-06 16:31
The addon name is "anywheretrainer". Closing as Blaquar pointed out everything else.

**Closed by Luth-RoR** 2017-02-06 16:31 UTC

**Comment by abandonctrl** [comment] 2017-02-06 21:16
even with the addon off the issue still happens we already tested it with and without addons

**Comment by Luth-RoR** [comment] 2017-02-06 22:51
Yes, because as Blaqwar already wrote
> I don't think this can be fixed right now. Easiest way to deal with this is to use an addon to be able to retrain the mastery point on the spot.

The addon doesn't fix anything, it allows to allocate the reset mastery point where ever you are, without the need to visit the mastery trainers every time. 
The problem is the original set bonus was a different, much weaker one and the RoR mastery point set bonus was never in the game; therefore the weird behavior.
