### ISSUE TITLE
T1 Chaos: Marked Completion reward incorrect.

### ISSUE THREAD

**Issue by TVBrowntown** [WarEmu/WarBugs#19180] opened 2021-06-19 01:14 UTC
**Expected behavior and actual behavior:**
When completing the Epic Chaos quest chain a unique epic item should be rewarded after its completion. Instead it is a green item or a potion. Typing <LINK data="QUEST:40090" text="[Marked]" color="243,228,103"> into the chat shows that you will not receive the correct reward upon completion.

**Steps to reproduce the problem:**
Follow the Marked quest line as written hree --> https://wiki.returnofreckoning.com/Chaos_T1_Epic_Quest_Marked

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/32625383/122626736-2e714800-d0eb-11eb-949c-e4ceef00983a.png)

**Comment by TVBrowntown** [comment] 2021-06-19 01:19
Looking at the other Epic quest rewards - they all seem to be broken and not rewarding the correct items too.

**Comment by lilimx** [comment] 2021-06-19 13:13
Hey,

sorry for the delay, Im just waiting for a feedback to categorize this ticket. (Not that you feel like the ticket has been ignored or overlooked.)

**Comment by lilimx** [comment] 2021-06-19 15:27
maybe related #15217

**Comment by Lheana** [comment] 2021-06-20 14:07
What do you mean by "other Epic quests seem to be broken"?

**Comment by TVBrowntown** [comment] 2021-06-21 04:08
> What do you mean by "other Epic quests seem to be broken"?

Even when pasting in the link data in to chat to seethe reward the incorrect rewards are displayed.
<LINK data="QUEST:40090" text="[Marked]" color="243,228,103">

Furthermore, even when handing in the final part of the chain different gear will be offered. I thought perhaps this was just an appearance issue - but when I handed in the final part of the epic quest I got a lvl 7 green quality shield. It can probably be assumed that any epic quest that links the incorrect item for its chain will also be broken in the same way. I checked the T2 Chaos link data and it also was incorrectly linking to the proper rewards.

**Comment by Lheana** [comment] 2021-06-26 12:15
I don't understand what you want to report:
- the fact that using the link to see the rewards is broken and it does not display correctly the real rewards?
- or that the rewards are green item?

**Comment by TVBrowntown** [comment] 2021-06-28 00:22
I'd assume both are an issue that are related to each other? The Link Data is showing the incorrect item as a reward, but also the reward you get when you hand in is incorrect to the Link Data AND the correct item reward - so both do not work correctly and likely means that the reward to the quest is pulling from a table of item rewards - but the table it is pointing to is wrong. I would assume.

Since the code is not open source, it's hard for me to make a better guess than that.

**Comment by Lheana** [comment] 2021-07-14 17:03
The rewards are correct because these are the ones that were given on official. They might need to be reviewed but this is a suggestion and not a bug. So I close this ticket.

**Closed by Lheana** 2021-07-14 17:03 UTC
Labels: Database, Item, Quests
