### ISSUE TITLE
Travelling between locations bug

### ISSUE THREAD

**Issue by Reaynez** [WarEmu/WarBugs#14416] opened 2019-06-13 18:24 UTC
Hi, i've been travelling from Troll Country to Talabecland on the road near Trollhaugen, when i entered the portal between locations, i alt-tabbed, then i came back and appeared in Inevitable City with character selection interface instead of my ingame interface, and i couldn't do anything, had to alt+f4

**Comment by sioding** [comment] 2019-06-14 06:55
Duplicate of #11224

**Closed by sioding** 2019-06-14 06:55 UTC
