### ISSUE TITLE
Witchbrew not working with tactics "Taste of blood" + witch elf 

### ISSUE THREAD

**Issue by Krimalicious** [WarEmu/WarBugs#5884] opened 2016-05-12 03:05 UTC
Taste of blood dmg bonus + 15% is not boosting witchbrew.. should not be like that.

**Comment by Evildoor** [comment] 2016-05-12 06:50
If i understand correctly, Witchbrew is a proc damage, so it's not affected by some things, including 15% damage tactic.

**Comment by Krimalicious** [comment] 2016-05-12 13:55
It worked on live, its good to use as a defensive build witch elf, Stack parry, wounds, 
Swift Blades + Riposte + Flanking + Taste of blood, your dmg output comes from witchbrew + % of tatics.. right now the only way to play witch elf is glass canon dps.. which its not fun. just my 2 cents.

**Comment by Evildoor** [comment] 2016-05-12 14:50
> It worked on live

Proof.

**Comment by Evildoor** [comment] 2016-05-27 12:08
No proof, closing.

**Closed by Evildoor** 2016-05-27 12:08 UTC
Labels: Dubious

**Comment by Krimalicious** [comment] 2016-05-30 23:23
https://www.youtube.com/watch?v=RWinqLdtlAo

Sec 0.23 of the video.. I had taste of blood + flanking hits the white lion for 471, without flanking hiting for 421 ....Im using WSCT, witchbrew damages says only (w) on the side of the dmg.. quality its bad but you can see, use 720P...

**Comment by Evildoor** [comment] 2016-05-31 06:57
Tested, Flanking correctly affects Witchbrew on RoR.

**Comment by Krimalicious** [comment] 2016-05-31 16:25
Hi Evildoor, thanks for your attention!

yes, flanking is working but taste of blood its not.. on live witchbrew could hit 400-500 with tactics.. 
For example my video:
Witchbrew + Taste of blood + flanking = 471 dmg 
Witchbrew + Taste of blood = 421 dmg 
Witchbrew only = 360 DMG.. 

If flanking is working taste of blood should work also.. both tatics are basicly the same, it ads 15% dmg to your atacks including witchbrew. 

Ive used this setup on live for years ..had 90 days of gameplay on my WE, this is something im 100% sure.. sorry for bad english.

**Comment by Evildoor** [comment] 2016-05-31 16:55
> both tatics are basicly the same, it ads 15% dmg to your atacks

I agree with this logic, but the problem is that you can't be sure about logic when dealing with original WAR... Shame that your video only shows Flanking difference on both AM and WL, not Taste of Blood difference on one target... @ozarmidrashim , what do you think about this issue?

Side note - as said in the rules, there are some reasons why such statements:

> Ive used this setup on live for years ..had 90 days of gameplay on my WE, this is something im 100% sure.. sorry for bad english.

have no weight in this place. I feel your pain, but that's how it stands.
