### ISSUE TITLE
Overflow Bag not emptying

### ISSUE THREAD

**Issue by Makali524** [WarEmu/WarBugs#13777] opened 2019-04-01 03:25 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Kind of difficult to take a screenshot for you but if you need one, please let me know. 

The overflow bag will NOT empty even if I have room in my inventory and in my crafting bag. It's a talisman main fragment that is not going into either bag. I can not manually move it nor can I sell it or discard it on the ground.

**Comment by dalen** [comment] 2019-04-01 10:14
Duplicate of #11937 

There is a workaround listed there as well

**Comment by sioding** [comment] 2019-04-01 17:06
Thanks @dalen

**Closed by sioding** 2019-04-01 17:06 UTC
