### ISSUE TITLE
Marauder Terrible Embrace

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16891] opened 2020-05-20 17:17 UTC
This pull is very buggy, if the target runs out of range, the skill still goes off and doesn't pull, but will throw the skill on cooldown, but other caster skills don't go on cooldown when this happens. Sometimes they don't even have to be out of range though, it just doesn't work randomly (not because they parried it or anything like that)

**Comment by Kaelang** [comment] 2020-05-20 18:31
I'll need more to go off than this. Videos of it failing to work in circumstances where it should etc would be nice.

**Comment by Xicoz** [comment] 2020-05-20 19:10
here is just a simple demonstration of pve (tried to get quick as possible, can replicate in rvr if needed)
https://www.youtube.com/watch?v=v4qr5qy4hxM&feature=youtu.be

**Comment by Xicoz** [comment] 2020-05-20 19:48
here is rvr https://www.youtube.com/watch?v=HyfJS7RpTQ4&feature=youtu.be

**Comment by Foofmonger** [comment] 2020-05-20 21:33
Can confirm I experience this constantly (figured it was intentional), you really can't pull anyone unless you are moving forwards towards them, or you are very close to begin with. Can provide further video evidence if necessary.

**Comment by Amagawd-NottheAI** [comment] 2020-05-26 21:12
Can confirm it sometimes doesn't work even if I am chasing someone. I begin channeling the spell, i maintain the distance - running in a straight line - the animation happens, the character emits his BAH sound, but the actual relocation of the character does not happen. When the target hides from LoS fails too - but I assume that is working as intended.

**Comment by Kaelang** [comment] 2020-06-19 19:33
This was fixed in the hotfix today.

**Closed by Kaelang** 2020-06-19 19:33 UTC
Labels: Ability, Fix Pending
