### ISSUE TITLE
Reikland Factory. Some places where you can get stuck.

### ISSUE THREAD

**Issue by EnmityOzZ** [WarEmu/WarBugs#11523] opened 2018-03-28 17:25 UTC
As the title say I'm posting some places where I got stuck during this sc.
![screenshot 2018-03-28 19 16 41](https://user-images.githubusercontent.com/36923127/38045606-86c5ab24-32bd-11e8-8c72-1d077dfe77d8.png)
![screenshot 2018-03-26 15 50 18](https://user-images.githubusercontent.com/36923127/38045660-b0681098-32bd-11e8-91bd-f9cf440e0e20.png)

**Comment by sioding** [comment] 2018-03-28 18:37
Duplicate of #9520

**Closed by sioding** 2018-03-28 18:37 UTC
Labels: Map/Area, Scenarios
