### ISSUE TITLE
Altdorf Sewers - Debolster gone after Lvl up

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#14779] opened 2019-08-16 05:57 UTC
Yesterday I´ve done Altdorf Sewers within a group. We were all correctly debolstered when entering. 

I got a Level-up from 33 to 34 while we are inside and after it, the debolster was gone. 
All my skills and tactics are available from this point. 

![Shaevra_001](https://user-images.githubusercontent.com/52664952/63146510-6e50db00-bffb-11e9-87cb-95f0f3ce3cc9.jpg)

**Comment by sioding** [comment] 2019-08-16 14:20
Duplicate of #14750

**Closed by sioding** 2019-08-16 14:20 UTC
