### ISSUE TITLE
 fortress lord on bottom floor

### ISSUE THREAD

**Issue by anazarelle** [WarEmu/WarBugs#13398] opened 2019-02-18 12:47 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

https://image.noelshack.com/fichiers/2019/08/1/1550494026-josianne-001.jpg

**Comment by sioding** [comment] 2019-02-18 12:58
Duplicate of #13396

**Closed by sioding** 2019-02-18 12:58 UTC
