### ISSUE TITLE
[Stop hittin' Da Runts] 25% to trigger on Da Toughest even if buff is allready up.

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6151] opened 2016-05-17 18:27 UTC
If Da Toughest War Bellow allready proced. You have 25% chance to gain AP anyway.

**Comment by Evildoor** [comment] 2016-05-17 18:58
Uh... I can ask "how it was on live", but i doubt that we'll find any info on that...
Bit of logic (yeah, i know that original WAR and logic are not going on well sometimes) - if we follow the tooltip and fix this, Da Toughest will only get you 40 AP per 10 seconds or less, which is garbage and completely outclassed by Da Biggest and Da Greenest - sounds weird if we consider that Da Toughest and the tactic belong to the same tree.
Ok, let's see what Aza says on this.

**Comment by ozarmidrashim** [comment] 2016-05-17 18:58
Agreed with Evildoor.

**Comment by Evildoor** [comment] 2016-05-17 19:05
Ok then, closing as not a bug.

**Closed by Evildoor** 2016-05-17 19:05 UTC
Labels: Ability
