### ISSUE TITLE
runtime error at BL Boss

### ISSUE THREAD

**Issue by Hattiro** [WarEmu/WarBugs#10930] opened 2017-11-29 12:20 UTC
Hi now i have two BL Bosses with the same problem, the game make a runtime error. I`ve talk with an GM and they now about this. Any got a idea what i can do, to get this quest done? Happens at SNizzort and Khorgash.
greetings Yip
![snizzort](https://user-images.githubusercontent.com/33959832/33374821-f6d9bc0c-d507-11e7-8f9a-9a027596e6e0.jpg)

**Comment by sioding** [comment] 2017-11-29 17:15
Duplicate of #10679

**Closed by sioding** 2017-11-29 17:15 UTC
