### ISSUE TITLE
Gamebreaking HP bug with recent patch

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#4886] opened 2016-03-12 15:20 UTC
After recent patch i noticed that i lost around 300 hp on my slayer Ggnore. I decided to unequip all my clothes, weapons and acessories. And got 85k+ hp. And this is not visual bug 
![ggnore_008](https://cloud.githubusercontent.com/assets/17799901/13723740/057d3c24-e87f-11e5-9e3b-09b941a8b2f2.jpg)

**Comment by Ktaan** [comment] 2016-03-12 15:22
I tested it in high pass rvr- a lot of destro (around WB) managed to take me down but it took them for about 5 mins

**Comment by Ktaan** [comment] 2016-03-12 15:26
I checked it just now again without engagingh in pvp just standing in WC - removing all my armor increased my hp to 85000 hp

**Comment by Ktaan** [comment] 2016-03-12 15:32
ok when i try to full equip my slayer jewerly slot 3, jewerly slot 4 and offhand are not available. meaning i cant place anything there which explains at least missing 300 hp i've noticed after this patch

**Comment by Ryanfawkez** [comment] 2016-03-12 18:57
Jewelry is now Unique, you can only wear one type of jewel.

**Comment by taccr** [comment] 2016-03-12 19:02
I can confirm that there is a bug with bolstering. (At least bolstering up)
I'm in t2 r21 and I get bolstered to 26.

If I unequip my gear i gain a crazy amount of wounds. (This is not just visual, I have a getstats more than 18k wounds)

If I equip any item WITHOUT wounds the HP will stay that high. It also does not seem to affect the high hp if the item has less than 10(?) wounds. I only have a few pieces of gear to test but this is definitely a bug in the bolster formula.

**Comment by taccr** [comment] 2016-03-12 19:13
Unequipped my 3 pieces of gear with >= 10 wounds.

![Wounds](http://img0.uploadhouse.com/fileuploads/22214/2221479080f5823a12a0803268f32b83a8c8bb8d.png)

**Comment by taccr** [comment] 2016-03-13 07:22
Looks like this has been fixed with the latest patch tonight.

**Comment by Evildoor** [comment] 2016-03-16 11:55
Closing then.

**Closed by Evildoor** 2016-03-16 11:55 UTC
Labels: Major
