### ISSUE TITLE
Bulk purchase of devastator gear

### ISSUE THREAD

**Issue by fleshsaber** [WarEmu/WarBugs#11942] opened 2018-06-24 15:45 UTC
I attempted to bulk purchase 20 pair of devastator gloves in order to break them down to level my magic salvaging, but while the purchase did take the 160 soldier's medallions, I did not receive any gloves in return.  This happened at aproximately 11:30 am (EST) on Sunday, June 24 in IC.

**Comment by sioding** [comment] 2018-06-24 16:44
Duplicate of #8174

**Closed by sioding** 2018-06-24 16:44 UTC
