### ISSUE TITLE
Guild Hearaldry Bug More Information that might help

### ISSUE THREAD

**Issue by Richardwarhawk** [WarEmu/WarBugs#12393] opened 2018-10-02 17:05 UTC
When you join an alliance you can't use the script to make a guild heraldry.  When you push enter it does nothing and dos not even give you a warning. We had to leave our alliance to make one when we hit guild rank 20.

Steps to reproduce the problem:
When you leave the alliance you usually have to wait for a server restart to fix this issue.  I say again you have to be out of the alliance with a fresh restart to be able to use the script.

**Comment by sioding** [comment] 2018-10-03 04:44
Duplicate of #9295

**Closed by sioding** 2018-10-03 04:44 UTC
