### ISSUE TITLE
duplicating mails - open/delete issue

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#11828] opened 2018-06-01 06:13 UTC
I sent a mail from my main toon to an alt with just one item in it. I logged in with the alt after several weeks (like 2-4) to open the mail, which was shown as usual in the inbox.

Expected behavior and actual behavior:

When clicking "open" the mail did not show with content, but the message appeared that said "item has been successfully deleted", while it still showed up in inbox, but i was not able to open it. I clicked "open" once again and while nothing more happened, I closed the mailbox and reopened it. This time the mail did not show up again, like it has been deleted actually.

I then logged to my main and the actual mail was there TWICE. I was able to open both and extract the items in it TWICE, so there was a fully working duplicate of the original mail.

I assume there were two mails on my main because I tried to open it twice on my alt.
If this is the case. one could endlessly clone items this way, but that is just an assumption atm.

Steps to reproduce the problem:

I could not reproduce the issue with a fresh mail on several toons, so maybe the issue occurs only when mails are somewhat older and I will try it out with some more mails that last like 1, 2, 3 and 4 weeks at the recipient's mailbox to see whether it occurs or not.

Screenshots/Videos or archive.org evidences:

Not yet sadly, next time I can reproduce I make a video of it.

**Comment by sioding** [comment] 2018-06-01 07:08
Thanks for the report but if you are not able to reproduce the problem - and saw also no errors in chat we can not do anything against this issue and it would also not help to leave this open. I will close this one now and we have it in our archive for research situations.

**Closed by sioding** 2018-06-01 07:08 UTC
