### ISSUE TITLE
Altdorf Sewers -  de-bolster is missing

### ISSUE THREAD

**Issue by Tibdum** [WarEmu/WarBugs#13371] opened 2019-02-15 12:56 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Altdorf Sewers - character above lv 20 is not de-bolstered to designated rank,

Steps to reproduce the problem:

- Entered in dungeon at rank 40 
- All abilities enabled
- HP is reduced to normal lv 20 
- Character should be de-bolstered to rank 20 and only with available abilities at that rank, 
- Tested with a group (1st pic)
- Tested solo (2nd pic)

Screenshots/Videos or archive.org evidences:

![tibdum_379_li](https://user-images.githubusercontent.com/47664666/52858044-b6b53c00-3131-11e9-8a2a-ce1653f6ed97.jpg)

![tibdum_380](https://user-images.githubusercontent.com/47664666/52858051-bb79f000-3131-11e9-88f2-92b8de911712.jpg)

**Comment by sioding** [comment] 2019-02-15 17:49
Duplicate of #13169

**Closed by sioding** 2019-02-15 17:49 UTC
