### ISSUE TITLE
Influens still bugget 

### ISSUE THREAD

**Issue by Evilchosen** [WarEmu/WarBugs#20020] opened 2022-04-13 13:28 UTC
Hi influens is till bugget 
![image](https://user-images.githubusercontent.com/82473452/163191011-086dd738-4df0-428f-af91-d3307207183e.png)

![image](https://user-images.githubusercontent.com/82473452/163191062-a7c21d17-a9ce-41d2-8ac7-a854cca6c63b.png)

![image](https://user-images.githubusercontent.com/82473452/163191102-d9d10924-5b82-4142-8aaa-f9587eb2dc67.png)
 this are from wc t3 emp

**Comment by lilimx** [comment] 2022-04-13 15:11
Hey,

uhm, what's the issue?

**Comment by Evilchosen** [comment] 2022-04-13 15:17
The influens rewords for rvr zones

Den ons 13 apr. 2022 17:11lilimx ***@***.***> skrev:

**Comment by lilimx** [comment] 2022-04-13 18:21
Hey,

I mean, what's the issue with the gear? I don't see any issues....it's equip for all people between lvl 16-40.
Did I miss something?

**Comment by Evilchosen** [comment] 2022-04-13 18:24
First influens rewords is a lev 27 belt for taks best till lev 38 influens
belt from t4

Den ons 13 apr. 2022 20:21lilimx ***@***.***> skrev:

**Comment by Evilchosen** [comment] 2022-04-13 23:41
this is the lev 27 belt for dps from t3 emp and tanks get the def side of
it influence

[image: image.png]

Den ons 13 apr. 2022 kl 20:23 skrev Kari Ylivirta ***@***.***>:

**Comment by Zomega-WAR** [comment] 2022-04-13 23:50
The influence rewards have been intentionally changed and are not based on the tier of the zone anymore. The first reward is for Tier 2 characters, the second reward is for Tier 3 characters, the final reward is for Tier 4 characters.

**Comment by lilimx** [comment] 2022-04-14 10:51
Hey,

I asked the database dudes and dudettes and they found something weird esp. about BGs.
So they are on it.

**Comment by Evilchosen** [comment] 2022-04-14 11:00
ty sir


Den tors 14 apr. 2022 kl 12:51 skrev lilimx ***@***.***>:

**Comment by Rubyeclipse-war** [comment] 2022-09-11 22:09
Hi @Evilchosen , I'll be jumping in to work on this one if it's still bugged.

I've taken a look at these rewards for Black Guard and compared them to Chosen, but I'm seeing almost the same rewards for each, so I think they may be working as intended.

**Could you let me know very specifically exactly what you feel is bugged here, and what it should be instead, so that I can test and confirm?** Thank you!

**Comment by lilimx** [comment] 2022-10-04 17:43
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.

**Closed by lilimx** 2022-10-04 17:43 UTC
Labels: Database, Item, 2 Week Ultimatum
