### ISSUE TITLE
The Fall of Night - Public Quest Empire Chapter 22

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9769] opened 2017-06-05 14:35 UTC
Southwest of the PQ there are some Gorhorns but they dont count for PQ.

**Comment by grunbag** [comment] 2017-06-07 13:53
Fixed on next patch

**Closed** 2017-06-10 08:57 UTC
Labels: Database, NPC, Public Quests

**Comment by Gnashspike** [comment] 2017-06-11 15:13
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Razielhell [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAIZEAHICOEMG5ABUABW3RTEBQ4AVSAZT4EQGTSZIXBVMYW6BOMR5HLSDQEIMKWMFWKXVUVPYIUIOKIILDJQQE24CCYYRLQRCML4UBZBKG3BY3CYBABKSEFIAHMAHIACMAAMAADAALAFGZ6AC5IBGUANYZH4GIURFRAEQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:13:18 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp a190si1634791ywf.113 - gsmtp:
    retry timeout exceeded
