### ISSUE TITLE
Infinite Salvaging

### ISSUE THREAD

**Issue by charlysixb86** [WarEmu/WarBugs#11427] opened 2018-03-07 14:05 UTC
Well i'm going to explain what happened to me yesterday while i was lvling up my salvaging skill in Inevitable City.
I was buying a bunch of devastator gloves off the rvr vendor for salvaging. When finished the salvaging, i filled my bags with some gloves and repeated the same process. Till this everything was working as intended. Buy item, salvage item, get essences and item is gone. 
Ok, the problem come here. Server crashed WHILE i was buying more devastator gloves for salvaging and after server went up i found this surprise. That i could salvage without losing the item... getting infinite essences and stones for talisman making with only an item.

I dont know... maybe its an isolated case but somehow i bugged the devastator gloves unintentionally with server crashing and buying pieces just before it did. And if it can be done with devastator it may be done with more items.
Sorry for my bad english. 
In game nick: Peckman or Chifli 

https://youtu.be/Sv9mMsmnrx0

**Comment by sioding** [comment] 2018-05-12 03:14
Duplicate of #11219

**Closed by sioding** 2018-05-12 03:14 UTC
Labels: Crafting
