### ISSUE TITLE
No renown point received after fighting in TM from almost the beginning

### ISSUE THREAD

**Issue by andrasragany** [WarEmu/WarBugs#14039] opened 2019-05-07 20:05 UTC
Character name is Bicska. (40/60) renown was at 48%  when arriving in TM. 2019. may the 7th, around 21h CET. 

**Expected behavior and actual behavior:**
I noticed first when defeating Lord in order keep, that no renown was received. After that, no renown received in fight at one of the BOs and none at lock, no bags, nothing.

**Comment by sioding** [comment] 2019-05-08 17:44
Duplicate of #13413

**Closed by sioding** 2019-05-08 17:44 UTC
