### ISSUE TITLE
AH Bug

### ISSUE THREAD

**Issue by zolio1236** [WarEmu/WarBugs#16684] opened 2020-05-06 08:23 UTC
I cant not list level 38 armor pots (unguent) on the AH, I have tried 12 times of listing the item and it does not show up in the search. I had a random stranger look for me, and also a few guild mates with the same result ( NOT FOUND ). After trying to list other items it just seems to be armor , I listed HoT pots and insta heal pots fine , also aversion absorb pots fine, just armor pots as fare as i can tell. Need GM to look please.

**Comment by bloodmeat4370** [comment] 2020-05-06 11:07
I have the same bug with my AH. I can list everything in AH but some of the items dont appear on sale and other people cannot find them. This goes for 1500 HP pots/+20 talismans(these 2 items are the ones i can confirm that dont appear in AH,there are probably some more items that are bugged this way).

**Comment by Kaelang** [comment] 2020-05-06 12:00
duplicate of https://github.com/WarEmu/WarBugs/issues/14566.

**Closed by Kaelang** 2020-05-06 12:00 UTC
