### ISSUE TITLE
Quest unmasking the enemy, bug.

### ISSUE THREAD

**Issue by Florcituzz** [WarEmu/WarBugs#13824] opened 2019-04-08 21:03 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I did the epic t4 quests before with my main. but im doing them right now with an alter. Im on Unmasking the enemy. Kill masked shade in a tent and drop one quest item. But the item doesnt drop. tried this evening and now. many times . seems bugged?

**Comment by sioding** [comment] 2019-04-09 10:54
Duplicate of #13821

**Closed by sioding** 2019-04-09 10:54 UTC
