### ISSUE TITLE
[SH] Dodge strikethrough doesn't convert into parry strikethrough

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#18215] opened 2020-12-17 17:30 UTC
Squig armor converts all ranged stats into their melee counterparts, except for the strikethrough;

Without squig armor;

![outofarmor](https://user-images.githubusercontent.com/17130290/102521475-08b8a700-40a6-11eb-99dd-5f57d9eccf91.jpg)

With the squig armor;

![insidearmor](https://user-images.githubusercontent.com/17130290/102521540-1f5efe00-40a6-11eb-9b3d-5f480824dcec.jpg)

As you can see everything else gets converted, strikethrough stays the same.( I got %7 dodge strikethru from gear, %10 parry strikethru is Horned Squig's buff)

A side note: It is likely SW's assault stance is also bugged the same way, but I dont have a SW, so couldnt test.

**Comment by grunbag** [comment] 2020-12-17 18:30
Not sûre where squig Armor state ut should concert this stat

**Comment by cimator** [comment] 2020-12-17 18:45
I dont see why it should exclude 1 of the ranged stats, but convert everything else, it only seemed logical that it should convert strikethrough aswell.
Was the same on live and the only reason I can think of is because the original devs on live forgot about strikethrough.

**Comment by grunbag** [comment] 2020-12-17 19:46
I mean it’s not a bug since tooltip doesn’t mention it in the exchanged stats. Not sure we have a handler in client to exchange strikes through

**Comment by grunbag** [comment] 2020-12-17 19:47
Here what tooltip says : While in your Squig Armor; your armor is increased by the amount of armor gained from items, your Ballistic Skill from items also counts as Strength, your Ranged Power from items also counts as Melee Power, and your Ranged Critical chance from items also counts as Melee Critical chance.

What you ask seems more a balance change

**Comment by cimator** [comment] 2020-12-17 20:08
Yeah, I know it doesnt say in the tooltip either, but it felt like a bug to me. If its really intended, you can close this post I guess, I will type in balance forum then.

**Comment by grunbag** [comment] 2020-12-17 20:09
I am closing this one as we will discuss it internally .

**Closed by grunbag** 2020-12-17 20:09 UTC
