### ISSUE TITLE
More NPCs in Norsca that should be fighting

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14666] opened 2019-07-27 23:12 UTC
Expected behavior and actual behavior:
These guys are just staring at each other, they should be fighting.

Steps to reproduce the problem:
Just get to the location and look at them.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_004](https://user-images.githubusercontent.com/53320075/62000336-c5255d80-b0aa-11e9-9ae8-bd7842d8a457.jpg)
![Austherus_005](https://user-images.githubusercontent.com/53320075/62000337-c5255d80-b0aa-11e9-92e0-4e2f8f660159.jpg)
![Austherus_006](https://user-images.githubusercontent.com/53320075/62000338-c5255d80-b0aa-11e9-89f4-1b7519ebb726.jpg)
![Austherus_007](https://user-images.githubusercontent.com/53320075/62000339-c5255d80-b0aa-11e9-94c1-22dcc73ba76d.jpg)

**Comment by sioding** [comment] 2019-07-28 01:56
Duplicate of #14661

**Closed by sioding** 2019-07-28 01:56 UTC
