### ISSUE TITLE
In Game renown builder bugged

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#19465] opened 2021-09-26 16:28 UTC
e.g. i press lv 2 might, it stucks at lv 2 and can not learn lv3....

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment] 2021-09-26 19:06
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by lilimx** [comment] 2021-09-27 08:54
Hey,

I close this ticket, because there is a proper one now

**Closed by lilimx** 2021-09-27 08:54 UTC
Labels: Confirmation Request, 2 Week Ultimatum
