### ISSUE TITLE
Book of Binding No CD

### ISSUE THREAD

**Issue by Drstrangeone** [WarEmu/WarBugs#10935] opened 2017-12-01 05:29 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: I can use my book of binding over and over without a CD. I can do it on all of my accts. 

Steps to reproduce the problem:
Click the book and tele and then do it again and again with no wait time. 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2017-12-01 07:26
Duplicate of #7086

**Closed by sioding** 2017-12-01 07:26 UTC
