### ISSUE TITLE
Influence rewards switched classes.

### ISSUE THREAD

**Issue by KeeperOfSecrets** [WarEmu/WarBugs#4220] opened 2016-02-03 20:20 UTC
Some of the T3 Inf rewards have suddenly switched classes. Mainly these two:
http://i.imgur.com/T5P7OZK.jpg
These were both equipped on a witch elf until the patch about 3 days ago.

**Comment by Torquemadra** [comment] 2016-02-03 22:16
This is a result of a wide reaching influence item fix, attempt to contact a GM on the forums to swap them for you.

**Comment by Evildoor** [comment] 2016-02-04 07:44
Not a bug, but collateral damage caused by bug fixing. Closing.

**Closed by Evildoor** 2016-02-04 07:44 UTC
