### ISSUE TITLE
Heal lion

### ISSUE THREAD

**Issue by muraloo** [WarEmu/WarBugs#19700] opened 2021-12-25 11:57 UTC
How is it?

![Heal Lion](https://user-images.githubusercontent.com/47424013/147384385-a764ed91-c3ef-48b3-9c1e-3a9ad2285947.png)

**Comment by Rubyeclipse-war** [comment] 2021-12-25 19:57
Hi @muraloo - I'm not staff but I think you need to include a lot more information here instead of just a question and screenshot.

Can you list out specifically what the issue is, along with details and steps to try to recreate it, so the staff can better understand? The template for your bug report when posting should have all the sections you need to include.

**Comment by muraloo** [comment] 2021-12-26 03:46
How can the lion class be treated so much?
Nickname Ubivashka

**Comment by Rydiak** [comment] 2021-12-26 16:06
Duplicate of #19663

**Comment by muraloo** [comment] 2021-12-28 13:36
ty very much

**Comment by lilimx** [comment] 2022-01-02 20:06
Thanks Rydiak!

**Closed by lilimx** 2022-01-02 20:06 UTC
