### ISSUE TITLE
Squig Herder SSquig Taunt

### ISSUE THREAD

**Issue by DominoPrime** [WarEmu/WarBugs#11781] opened 2018-05-18 22:32 UTC
I have been playing a squig herder for a day now and I have played one before and the taunt doesn't work on it, or the aggro.

Expected behavior and actual behavior:
When i use my normal squig, it should take aggro off me and taunt mobs, but whenever i attack, even if it's a basic attack, it just attacks me.

Steps to reproduce the problem:
I let my squig attack the mob I wanted to kill first, used it's taunt then attacked, and the mob instantlyu started coming after me.
![beardnicka_001](https://user-images.githubusercontent.com/39421796/40260641-a697606a-5af3-11e8-8563-b0c7e8dee772.jpg)
![beardnicka_002](https://user-images.githubusercontent.com/39421796/40260643-a6c9502a-5af3-11e8-87db-c433ec8e12c7.jpg)

**Comment by sioding** [comment] 2018-05-19 06:17
Duplicate of #11777

**Closed by sioding** 2018-05-19 06:17 UTC
