### ISSUE TITLE
[PQ] Missing items in T4 PQ bags

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5837] opened 2016-05-10 22:46 UTC
All lower tier PQs had crafting containers for apoth/tali making in them, but the T4 PQs and Keep bags do not. This seems like an oversight.

**Comment by Evildoor** [comment] 2016-05-11 06:23
Almost the same as #5377 but this part of the problem is much easier to fix, if i understand correctly, so not closing this.

**Closed** 2017-10-14 15:29 UTC
Labels: Database, Public Quests
