### ISSUE TITLE
Reikland's north keep (Wilhelm's Fist) bugged ram

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#14540] opened 2019-07-07 07:09 UTC
**Expected behavior and actual behavior:**
Destro was being sieged by order (with a dwarf ram) in Reikland, north keep. Normally you can't hit or damage ram from within the keep using melee attacks but ram got bugged and started to get damage by aoe melee attacks, regardless to say it didn't last a minute.

**Steps to reproduce the problem:**
Be order fighting in Reikland, place a dwarf ram in destro keep (north keep), destro is able to melee hit it from within the keep without the need to exit.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tadpoledancer_435](https://user-images.githubusercontent.com/36811878/60765209-d1635f80-a096-11e9-9758-b937059865bb.jpg)
![Tadpoledancer_436](https://user-images.githubusercontent.com/36811878/60765210-d6281380-a096-11e9-8933-1f07e323f588.jpg)
![Tadpoledancer_437](https://user-images.githubusercontent.com/36811878/60765212-daecc780-a096-11e9-992c-eed97d055461.jpg)
![Tadpoledancer_438](https://user-images.githubusercontent.com/36811878/60765213-df18e500-a096-11e9-8fc9-892891910b4d.jpg)

**Comment by sioding** [comment] 2019-07-07 10:21
Don't get it - you can hit a ram. yes - it will die - yes. But what is the real problem here - the screenshots doesn't help cause they don't show a problem - only the result. Can you bring in more information ?

**Comment by Jandeporas** [comment] 2019-07-09 07:29
The thing is, while the ram was placed on the outer door to bring it down, for some weird reason destro players were able to attack the ram with AOE attacks from inside the keep.

I think it is not intended that the ram can take damage UNLESS you exit the door to attack the ram

![bug_croquis](https://user-images.githubusercontent.com/36811878/60867808-f1785780-a22b-11e9-893d-a1d4dc002654.jpg)

**Comment by sioding** [comment] 2019-07-09 08:49
Duplicate of #10242

**Comment by sioding** [comment] 2019-07-09 08:50
Thanks for the info - i merged it with an existing ticket

**Closed by sioding** 2019-07-09 08:49 UTC
Labels: 2 Week Ultimatum, Confirmation Request
