### ISSUE TITLE
lvl 13 guild, assigned bannerbearer, have unlocked warped banner and slotted tactics for it + equipped warped banner. But cannot deploy it

### ISSUE THREAD

**Issue by Zurbak** [WarEmu/WarBugs#13692] opened 2019-03-21 10:39 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The banner should deploy - it doesnt.

**Steps to reproduce the problem:**
be in a lower lvl guild - equip banner, try to deploy.

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/48727657/54747011-f8705100-4bcd-11e9-8b1c-ad8f4901e9fa.png)
![image](https://user-images.githubusercontent.com/48727657/54747019-fefec880-4bcd-11e9-8ebf-132eea830bf6.png)

**Comment by sioding** [comment] 2019-03-21 18:44
Duplicate of #13289

**Closed by sioding** 2019-03-21 18:44 UTC
