### ISSUE TITLE
Squig Pets 

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#4900] opened 2016-03-12 19:01 UTC
Dont know if its mentioned before but, squig's damage doesnt count in Scs even if I can see the damage of my squig when hitting people. And it can steal mobs and wont give any credit to me.

**Comment by Evildoor** [comment] 2016-03-12 19:12
> Dont know if its mentioned before

Aaand we have 11th duplicate of #1229.

**Closed by Evildoor** 2016-03-12 19:12 UTC
