### ISSUE TITLE
Gloomridge Copse

### ISSUE THREAD

**Issue by Exmortis66** [WarEmu/WarBugs#8959] opened 2017-01-22 04:44 UTC
So the PQ in T2 High Elf/Dark Elf Gloomridge Copse is bugged, that is known.  An issue that I have come across during that PQ is quite intriguing.

During the Final Phase (3) of that PQ:

1. The 5 Branch wraiths that need to be killed to complete them, are hiding up tree's! (I know right, tree people hiding in tree's!) Making it incredibly difficult to find them

2. The Branch Wraith's themselves, are untargetable.  Making those "Treekin" (As they prefer to be called now) nearly impossible to kill.  (You need to AoE them down)

3. The Champion you need to kill there, (I have forgotten his name, and he will be none to pleased, i'm sure) Also has the same bug as the Branch Wraith's, untargetable.  Therefore only able to kill them using AoE attacks (Rather challenging, as it is a Champion)

I did search around to see if anyone else has posted this particular issue, and didn't notice anyone as posted it.

Regards
Exmortis, your not-so-friendly DoK

**Comment by wargrimnir** [comment] 2017-01-25 21:06
This is a specific mob state. Untargetable until attacking.

If you aggro them, once they attack you and become your target automatically, you should be able to use skills normally. We've left mobs in this state since that's how we found them and it's helpful to keep the weird mobs around in case we find a reason to use them later.

It's not really a bug.

**Comment by LadyCereus** [comment] 2017-03-12 05:12
In this case it doesn't seem to be working as intended.  Even if you use an AOE to try attacking them, you can't target them further to kill them.  This is true of all the stage 3 guys I tried to fight in Gloomridge Copse PQ.

**Comment by grunbag** [comment] 2017-06-22 12:25
Fixed in next patch

**Comment by grunbag** [comment] 2017-07-18 19:10
close it please

**Closed** 2017-10-02 17:50 UTC
Labels: Database, NPC, Public Quests
