### ISSUE TITLE
Tzeentch's Firestorm

### ISSUE THREAD

**Issue by Dizzltron00** [WarEmu/WarBugs#16194] opened 2020-04-02 05:31 UTC
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Dizzltron00** [comment] 2020-04-02 05:32
at lvl 26 - 33 renown.. casting the "Tzeentch's Firestorm" from the mastery tree as a magus is bugged.
in Rvr it just wont go off.. but in pve where im not bolstered it works just fine.
Character name is Dizzlgus

**Comment by Vdovics** [comment] 2020-04-15 08:52
Same issue. It was already reported 10 March.

Evidence: https://imgur.com/a/jYlZZjx

**Comment by Kaelang** [comment] 2020-04-19 18:54
Looks like a bolster issue. Duplicate of https://github.com/WarEmu/WarBugs/issues/15941.

**Closed by Kaelang** 2020-04-19 18:54 UTC
