### ISSUE TITLE
Set rally point DRAGONWAKE

### ISSUE THREAD

**Issue by Bufitos** [WarEmu/WarBugs#10992] opened 2017-12-12 13:15 UTC
Set rally point on DRAGONWAKE (Warcamp) have fail :  
If  you bind on him and use book to return , you teleported to CALEDOR .....

**Comment by sioding** [comment] 2017-12-12 19:50
checked that on my own ... sad but true :)

**Comment by Lheana** [comment] 2017-12-21 11:32
This is not a bug, I explain: For now we can not set different rally masters as giving the same influence rewards, like in T4 RvR zones that share the same influence rewards for Caledor, Dragonwake and Eataine for example, but that have 3 different rally masters (one for each warcamp). Thus to enable players to take their influence rewards in each warcamp, we added the rally master of Caledor in warcamps of Dragonwake and Eataine. Thus if you talk to Aethalas Flowingmane (the real rally master of Caledor) in Dragonwake, it will bind you to Caledor. To bind to Dragonwake, talk to the rally master of Dragonwake 'Renth Goldleaf' in a tent at the north of the warcamp.

**Comment by MaxHayman** [comment] 2019-03-24 11:24
Added support for this.

**Comment by sioding** [comment] 2019-03-30 13:56
Fixed with patch from 30.03.2019

**Closed by sioding** 2019-03-30 13:56 UTC
Labels: Database, Fix Pending, Known Issue - Review again., NPC
