### ISSUE TITLE
Bloodlord Andsplate

### ISSUE THREAD

**Issue by DypfrystBram** [WarEmu/WarBugs#14951] opened 2019-09-22 00:20 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
The Andsplates that belong to the bloodlord set should give the parry bonus in the picture and should be highlighted acknowledging it being worn. It doesnt recognise it or give any bonus. 

I have 4 other identicle andsplates all that do the same. 

**Steps to reproduce the problem:**
Make it so it contributed to the bonus

**Testing Screenshots/Videos/Evidences (always needed):**
![eljefe hands](https://user-images.githubusercontent.com/55640980/65380632-a1853900-dd22-11e9-8e21-164accec258b.png)

**Comment by Kabucoror** [comment] 2019-09-22 13:36
Duplicate of #14917

**Closed by Kabucoror** 2019-09-22 13:36 UTC
