### ISSUE TITLE
Guild party quest

### ISSUE THREAD

**Issue by kayfynn** [WarEmu/WarBugs#15804] opened 2020-02-26 01:37 UTC
Destro guild party quest "conspirator of destinies" and "order undone" cannot be completed at this time ie... doing the quest as a 6 man guild I am not given credit for finishing quest. Side note, so at this time a guild has to pay for a zone and lock said zone to receive credit?

**Comment by Lheana** [comment] 2020-02-26 10:56
Duplicate of #15591

**Closed by Lheana** 2020-02-26 10:56 UTC
