### ISSUE TITLE
level 5 Battle Brew Backpack-Cannot be used for alternate appearance

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#18444] opened 2021-02-02 22:16 UTC
**Expected behavior and actual behavior:**
I have not played my Ironbreaker in a while and I just upgraded his cloak to a level 28 Green cloak.  I have a level 5 Battle Brew Backpack from the event and it says the backpack cannot be used for alternate appearances.  Please note last line of text in chat box.  Everyone I talked to said all level of the Battle Brew Backpack are allowed to be used to alter cloak appearances, except the level 5 Backpack.  Since all other levels are allowed to alter the appearance of the cloak the level 5 should also.

![Bolgrig_000](https://user-images.githubusercontent.com/66458029/106670080-6e32fb00-6561-11eb-8858-25b8d19d4792.jpg)

**Comment by Lheana** [comment] 2021-03-21 17:04
Duplicate of #18401

**Closed by Lheana** 2021-03-21 17:04 UTC
