### ISSUE TITLE
Stealth Classes

### ISSUE THREAD

**Issue by gman4gov** [WarEmu/WarBugs#18901] opened 2021-04-25 09:43 UTC
Stealth is being easily detected with classes that have less initiative from other classes. Tested with another class and it was apparent this is a recent bug.

**Comment by lilimx** [comment] 2021-06-08 13:45
Hey,

thank you for your ticket. 
But I need screenshots or a video with a proper description to reproduce your assumption.

**Comment by lilimx** [comment] 2021-06-24 06:11
Hey,

due to the lack of information, I'll close this ticket now.

**Closed by lilimx** 2021-06-24 06:11 UTC
