### ISSUE TITLE
Pyrewind potion not working

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#14522] opened 2019-07-05 14:08 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
should cause firebreath  no action happen , the potion does not trigger

**Steps to reproduce the problem:**
Make pot, place in bar , select item to use

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/leH2JoLDcG0

**Comment by sioding** [comment] 2019-07-06 05:50
Duplicate of #14081

**Closed by sioding** 2019-07-06 05:50 UTC
