### ISSUE TITLE
White Lion Pet despawns at every Bolster trigger

### ISSUE THREAD

**Issue by Emissaryx** [WarEmu/WarBugs#20216] opened 2022-06-24 01:25 UTC
Can we look at a different bolster for the White Lion as every time we come in or out of the lakes we lose the lion for 30 esc? Thank you for the bolster change

**Expected behavior and actual behavior:**

Not de-spawn the lion and if it does give us an instant recall to get it back. 

**Steps to reproduce the problem:**

Bolster a white lion in RVR

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment] 2022-06-24 13:08
Hey,

Thank you for your feedback. But your ticket doesn't sound like a bug, more like a suggestion. 
I will give the information to our team, but however it's not a bug, so I will close this ticket until further orders.

**Closed by lilimx** 2022-06-24 13:08 UTC
