### ISSUE TITLE
Lair Drops 

### ISSUE THREAD

**Issue by DavidWAAAGH** [WarEmu/WarBugs#5303] opened 2016-04-12 01:06 UTC
Hello, I just wanted to say that almost a 50% of the times that you kill a Lair boss in T1, the drop is almost the same items like double helm for swordmaster or double weapons for the same class etc.

Idk if its a bug or something but I just wanted to report that.

**Comment by Evildoor** [comment] 2016-04-12 07:11
> almost a 50% of the times

You killed X bosses and Y times the drop was double, like you say. What are X and Y?

**Comment by Renork** [comment] 2016-04-12 09:06
Do you have two of the same class in your group?

**Comment by Yellowpillow** [comment] 2016-04-12 11:35
sometimes it happened, sometimes it dont. On live it happened too, so it not bug. On RoR drop even better, because it drop gear for somebody in the group, on live it was total random.

**Comment by genisaurus** [comment] 2016-04-12 18:25
Closing, not a bug. You're guaranteed two items usable by at least one member of the group. There is a chance they might both be usable by the same person, that's just luck.

**Closed by genisaurus** 2016-04-12 18:25 UTC
Labels: Confirmation Request
