### ISSUE TITLE
Casting While Poppin in and Out of Posterns

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#12164] opened 2018-08-14 16:15 UTC
Good Morning. 
Ive seen people initiating a cast before entering a postern and entering right as the spell is about to fire to do quick burst damage or insta rez people with little to no resistance...
I feel like this is breaking keep fights somewhat

Ive tested this myself a few times to confirm

**Comment by sioding** [comment] 2018-08-14 18:16
Duplicate of #10891

**Closed by sioding** 2018-08-14 18:16 UTC
