### ISSUE TITLE
My Enggine turret hitting people when im not flagged for rvr

### ISSUE THREAD

**Issue by Weedmans** [WarEmu/WarBugs#11042] opened 2017-12-23 04:39 UTC
When u are in a pve are and u meet an destro,ur turret will hit him,but u will not be flagged for rvr

**Comment by Torquemadra** [comment] 2017-12-23 06:06
General pet issue they need to inherit status of their owner properly.

**Comment by sioding** [comment] 2017-12-23 06:50
Duplicate of #8105

**Closed by sioding** 2017-12-23 06:50 UTC
