### ISSUE TITLE
[BW] Wildfire tactic

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#10327] opened 2017-08-31 13:04 UTC
Doesn't apply on the initial hit of Flame Breath.

**Comment by nohh** [comment] 2017-09-01 12:20
Reported already #1940

**Comment by Scrilian** [comment] 2017-09-01 12:28
Yea, I saw that report, but it's not clear on whether Flame Breath interaction was fixed to apply the tactic dot. Surely Backdraft or Spreading Flames aren't affected since they have an initial hit.

**Comment by sioding** [comment] 2017-11-18 09:13
Duplicate of #1940

**Closed by sioding** 2017-11-18 09:13 UTC
Labels: Ability
