### ISSUE TITLE
Halloween capes and Dyes

### ISSUE THREAD

**Issue by alxxqp** [WarEmu/WarBugs#10789] opened 2017-11-07 22:10 UTC
So the isuue is you can dye the halloween event capes, but only you will see it dyed, other players will still see the original colors. Hope you guys can fix this, much <3

There's a screenie :)

https://imgur.com/a/VWWBB

**Comment by MaxHayman** [comment] 2018-12-10 09:04
Duplicate of 8186. Although I have done some testing and should have a fix for next patch.

**Closed by MaxHayman** 2018-12-10 09:04 UTC
Labels: Item, Visual
