### ISSUE TITLE
T2 Epic (Barrak Varr) NPC Gnashfang 31k, 6k - cannot be interacted with

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#13848] opened 2019-04-11 16:50 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Cannot progress T2 epic quest as cannot interact with Gnashfang (31k, 6k BV). Tried several times all day. What happens is see "thinking" icon when hovering mouse on him but cannot click him.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
Cannot attach screenshot for some reason but it doesnt show mouse cursor anyway. What happen is mouse cursor shows as thinking... and thinking... and so it stays.

**Comment by Lheana** [comment] 2019-04-11 17:00
Duplicate of #13806

**Closed by Lheana** 2019-04-11 17:00 UTC
