### ISSUE TITLE
Every quest in the game reset

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5667] opened 2016-05-08 15:09 UTC
Just before T4 release, each and every quest in my log on Eusebeus has been deleted and reset to incomplete!
Is there anyway that the quest completed status can be reset for the PVE chains - I did every quest in the game, and now they're showing as green dots again! Damned infuriating. I just want them marked as done again.

**Comment by Evildoor** [comment] 2016-05-08 15:24
#2001?

**Comment by Eusebeus82** [comment] 2016-05-08 15:26
Seems to be the same issue, yes. I logged onto another toon, and no issue as well.

**Comment by Evildoor** [comment] 2016-05-08 15:36
Closing then, since the problem is known and has no solution so far.

**Closed by Evildoor** 2016-05-08 15:36 UTC
Labels: Confirmation Request
