### ISSUE TITLE
Quest "Wyrmbreaker" can't be completed

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15840] opened 2020-02-29 11:08 UTC
The last step of the epic quest Wyrmbreaker (45141) cannot be completed.
If you are in the pool. the Summonglass item can be used and will be ticked off, but the step to enter the pool won't activate and the dragon that needs to be killed won't spawn.

**Comment by Lheana** [comment] 2020-02-29 11:09
Duplicate of #12982

**Closed by Lheana** 2020-02-29 11:09 UTC
