### ISSUE TITLE
Bow icon, effect, and skin

### ISSUE THREAD

**Issue by ufthakk** [WarEmu/WarBugs#17839] opened 2020-09-25 09:39 UTC
My Bow Sniper's Shoota of Anathema became invisible yesterday. Also the icon changed. When i try to use abilitys they fire off while saying a bow required.
![bow](https://user-images.githubusercontent.com/50882522/94251998-9d868b00-ff23-11ea-9632-8a8c4f9d65d2.png)

-->

**I think it happend while i get my first royal crest in rvr:**

**Comment by dalen** [comment] 2020-09-25 10:37
duplicate of https://github.com/WarEmu/WarBugs/issues/17821

**Closed by dalen** 2020-09-25 10:37 UTC
Labels: Fix Pending
