### ISSUE TITLE
UV City Fight Stage 1 Shortcut

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#16369] opened 2020-04-13 12:40 UTC
I reported the Bug a while ago via GM, but nothing changed, so i thought I create a regular Issue.
**Expected behavior and actual behavior:**
Throught the rubberband feature at the bridge in Stage 1 UV it is possible to circumvent any deffing Party at the bridge. 
You only have do move throught the Plattform of the flying fortress and jump from there. 
Your land between the cannons. 
If someone tryes this after the sun dragon and the canoneers are called, the Stage should be lost for Destruction.
** Expected Behavior**
Be rubberbanded back to the Plattform.

**Steps to reproduce the problem:**
I tryed it at various Instances, it works everytime.

**Testing Screenshots/Videos/Evidences (always needed):**
![Randae_024](https://user-images.githubusercontent.com/62266826/79121452-a597a780-7d95-11ea-99da-9151f6afbefa.jpg)
![Randae_026](https://user-images.githubusercontent.com/62266826/79121461-a9c3c500-7d95-11ea-968b-faed510de488.jpg)
![Randae_028](https://user-images.githubusercontent.com/62266826/79121463-ae887900-7d95-11ea-9815-668d088c04de.jpg)
![Randae_032](https://user-images.githubusercontent.com/62266826/79121488-bc3dfe80-7d95-11ea-9ad5-b08739c7bf26.jpg)
![Randae_034](https://user-images.githubusercontent.com/62266826/79121492-bea05880-7d95-11ea-9d21-457c6482a08f.jpg)
![Randae_036](https://user-images.githubusercontent.com/62266826/79121495-bfd18580-7d95-11ea-970a-7bda797b6096.jpg)

**Comment by Gunlingers** [comment] 2020-04-13 20:29
https://github.com/WarEmu/WarBugs/issues/16164

**Comment by Kaelang** [comment] 2020-04-19 16:23
Duplicate of https://github.com/WarEmu/WarBugs/issues/16164.

**Closed by Kaelang** 2020-04-19 16:23 UTC
