### ISSUE TITLE
Sent back to character screen

### ISSUE THREAD

**Issue by ninjau** [WarEmu/WarBugs#14450] opened 2019-06-20 17:01 UTC
Get sent back to character screen after trying to log into RP but no characters just a black background. Have tried /stuck and hasn't worked and when i log onto a different character it says i'm on both

i Was just trying to fly to HP

https://imgur.com/IvFuybw

**Comment by sioding** [comment] 2019-06-23 13:51
Duplicate of #11224

**Closed by sioding** 2019-06-23 13:51 UTC
