### ISSUE TITLE
Gunbad - Masta Mixa kill count does not count.

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#13571] opened 2019-03-08 02:00 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Dobzse** [comment] 2019-03-08 02:02
Expected behavior and actual behavior:
After killing Masta Mixa kill count does not count. 

Steps to reproduce the problem:
Kill Masta Mixa in gunbad right wing.

Screenshots/Videos or archive.org evidences:
![dreadnari_017](https://user-images.githubusercontent.com/41837044/54002361-92f07f00-414e-11e9-8ed3-9e7cd1effa93.jpg)

**Comment by sioding** [comment] 2019-03-08 08:56
Duplicate of #13563

**Closed by sioding** 2019-03-08 08:56 UTC
