### ISSUE TITLE
Zimmeron's Hold Oil

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12827] opened 2018-12-08 20:53 UTC
Expected behavior and actual behavior:
Zimmeron's Oil is appearing on the ground, making it much easier for Order to destroy our Oil, rendering it worthless.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/49690582-f1c73d80-faf8-11e8-8180-e57bff2dd0b7.png)

**Comment by sioding** [comment] 2018-12-08 20:56
Duplicate of #11200

**Closed by sioding** 2018-12-08 20:56 UTC
