### ISSUE TITLE
Unread messages in auction

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12773] opened 2018-11-30 23:13 UTC
Expected behavior and actual behavior:
whenever you buy anything from auction house, or sell anything, the message stays showed up that there is currently stuff in your mailbox when there is not.

Steps to reproduce the problem:
buy something from the auction house, receive and delete the message.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/44329952/49319621-4cdaae00-f4c3-11e8-82a1-b84f6f8509a0.png)

**Comment by Lheana** [comment] 2020-01-04 18:29
Duplicate of #1109

**Closed by Lheana** 2020-01-04 18:29 UTC
Labels: Mail, Sourcecode
