### ISSUE TITLE
#1677 again with evidence

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#11805] opened 2018-05-26 10:27 UTC
Again fall at middle flag to the "ground", i was under the actual Gates and could freely move around and capture flag easily without interference, same as issue #1677, but now i made a screenshot as evidence.

What happend to me was that i got cornered on middle flag by a WP from front and Knight from behind, i guess collision made me fall down maybe.

Screenshots/Videos or archive.org evidences:

![solutar_003](https://user-images.githubusercontent.com/25050452/40575172-e6231bc4-60df-11e8-946f-067213f3fc18.jpg)

**Comment by sioding** [comment] 2018-05-26 12:11
Duplicate of #1677

**Closed by sioding** 2018-05-26 12:11 UTC
