### ISSUE TITLE
Troll Country  Keep Lord Bug

### ISSUE THREAD

**Issue by Torgrimmerr** [WarEmu/WarBugs#13837] opened 2019-04-10 13:53 UTC
Today at 5:25 am est. the Keep Lord in Troll Country, did the same issue, but I will add he came outside of keep and attacked WB with keep door still up will ram hitting door still attack players outside keep freely. Sorry did not react in time to take screenshot. :(

Expected Behavior is to stay in the keep, not while the WB is outside with ram knocking on door 

Steps to reproduce the is in an active T2 RvR siege Destro keep with order attacking destro keep, with ram outside

Sorry no screenshot due to nature of surprise of attack and panic but i will supply my DxDiag.

Josh

[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/3064130/DxDiag.txt)

**Comment by sioding** [comment] 2019-04-10 19:17
Duplicate of #13588

**Closed by sioding** 2019-04-10 19:17 UTC
