### ISSUE TITLE
Not receiving AH mail

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#557] opened 2015-01-19 13:38 UTC
Hey,

I recently posted this: http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2057 on RoR forum. 

Basically, AH mail isn't appearing in AH inbox on one of my chars (all others seem fine), neither when I buy something from AH nor the money when someone buys something I put on. But the chat box notification ("You have X messages in your auction mailbox") *does* increase and show the right number, they're just not there in AH mailbox tab.

I've followed Elven's advice and tried using PacketLogger while buying something - just hope I've done it properly! The log file should be here: http://www.mediafire.com/view/uakzz4iwr6a3w7w/sniff_h13m05.txt

Hope that helps but let me know if I need to do anything different.

**Comment by MaxHayman** [comment] 2015-01-21 15:23
Was the item Gale-Runner's Torment Cloak

**Comment by Zealote** [comment] 2015-01-22 08:30
That was one of the items that I had on AH but later cancelled after this happened - it didn't arrive in mail though. And it's not just one item, it started with 19 items that I bought that weren't there when I checked mailbox, and it's applied to everything bought/sold/cancelled since (there's nothing on AH anymore as I cancelled everything - the chat box message increased correctly but none of the items were in mail).

I've just logged that char again to check, it's saying there's 100 (!) items in my auction mailbox (which is right given the stuff I bought originally, the test stuff I bought, and the stuff I cancelled), but there's only 80 previously opened messages (with the ones since this started having no item/money/cancelled item). 

New Tests: 
I just bought "Initiate's Nightrobe" for 75 brass, checked mail immediately after and the new message *(which was already opened)* is an "Auction Won!" one but which says I've won the auction for "Gale-Runner's Carcass-Guard", with no item attached. So there seems to be a general problem/confusion going on somewhere? I've sold "GR Carcass-Guards" on there in the past so maybe that has something to do with it?
Did a 2nd test and exactly the same thing except the item it's saying I've won is "GR Darkboots", also something I've had on AH a few times in the past, if that's of any help :)

P.S. The same thing started happening on another (new) char of mine yesterday, after working for a while with no problems. I updated forum saying I tend to use one char to keep all my gear/AH stuff etc, don't know if it's possible there's some limit on AH transactions per toon or something like that?

**Comment by MaxHayman** [comment] 2015-01-22 08:48
What's your character name btw? I'm gonna check thought it.

**Comment by Zealote** [comment] 2015-01-22 10:13
Original one was Shamisch, second was Shleafee (both shamans).

Thanks for help btw :)

**Comment by MaxHayman** [comment] 2015-02-16 08:49
You had over 300 mails, correct?

**Comment by Evildoor** [comment] 2015-09-23 11:52
What's the status of this problem? Was it resolved?

**Comment by Zealote** [comment] 2015-09-23 12:17
Yeah Max fixed it. Was just due to there being a limit on the number of mail msgs you could have I believe.

http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2057

**Comment by Evildoor** [comment] 2015-09-23 12:18
Good. Closing.

**Closed by Evildoor** 2015-09-23 12:18 UTC
Labels: Confirmation Request, Mail

**Comment by defleshed2** [comment] 2015-11-19 01:24
Hey MaxHayman,  

Can you go onto my character, "defleshed" lvl 26 shaman. The AH mailbox was bugged for 3 days now. and Ive read all the posts on how to fix it by deleting the previous mail but the problem is it acually says "0 messages" 

[img]http://i63.tinypic.com/a2qedk.jpg[/img]

**Comment by defleshed2** [comment] 2015-11-21 08:36
Hello is someone looking at this?

**Comment by defleshed2** [comment] 2015-11-28 23:05
When is this getting fix? you guys said next patch?

**Comment by Evildoor** [comment] 2015-11-29 08:32
Asking this kind of questions is pretty much useless. As Azarael said in another issue, "Please don't ask for status updates on the tracker - none will be given. I get to it when I get to it.", and i do believe that other devs follow the same reasoning.

**Comment by Stefanosgr18** [comment] 2015-12-22 08:42
![war 2015-12-22 10-40-00-78](https://cloud.githubusercontent.com/assets/16375224/11951312/9e5c2c4c-a898-11e5-9e6e-a3dc15e9a516.jpg)

**Comment by Evildoor** [comment] 2015-12-22 08:43
@Stefanosgr18, This is a different bug. #1109.
