### ISSUE TITLE
PQ NPC are not available

### ISSUE THREAD

**Issue by Shmerrick** [WarEmu/WarBugs#10862] opened 2017-11-19 05:04 UTC
PQ Not spawning mobs. Affecting the ability to complete elf epic quest.

https://imgur.com/a/v5Wo3

**Comment by Lheana** [comment] 2017-11-19 11:16
Had the same problem with different PQs on dev server. It is not due to DB as it is well set. This issue is for Secrets I think ;)
If a GM uses the command .pq reset it should fix it.

**Comment by orderr** [comment] 2018-01-05 01:57
still not working((

**Comment by TibbyB** [comment] 2018-02-10 09:08
I can confirm. Photo took today on Blighted Isle ELF PQ T1 
![tiberiusultany_000](https://user-images.githubusercontent.com/32936075/36060454-aec5abe0-0e52-11e8-875a-e463debdc1af.jpg)

**Comment by Aduneth** [comment] 2019-03-24 14:54
Griffon Gate is bugged. Can't progress through my epic delf t2 questline.

**Comment by Lheana** [comment] 2019-09-14 16:26
This has been fixed with today's patch.

**Closed by Lheana** 2019-09-14 16:26 UTC
Labels: Public Quests
