### ISSUE TITLE
WL pet ignores gcd on his ability's

### ISSUE THREAD

**Issue by knickk** [WarEmu/WarBugs#19657] opened 2021-12-07 14:14 UTC
**Expected behavior and actual behavior:**
pet respects the physics of  ulthuan and fires abilitys after gcd. Actual it uses dark magic and fires all abilitys at once.

**Steps to reproduce the problem:**
 swicht between the stances and see how pet uses all of his ability's in less than 0.02 seconds 

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=An_9tly_rv8

![Knick_008](https://user-images.githubusercontent.com/25160644/145045428-1ff7e64d-0fd6-4f46-97e4-8de6549eb799.jpg)

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->

**Comment by lilimx** [comment] 2021-12-07 15:55
Hey,

I can't reproduce your issue. Could you please provide more information, like your skills/tactic, how was your rotation?

**Comment by lilimx** [comment] 2021-12-07 16:05
So after a few tests.....It has nothing to do with switching the stances, the Lion ignores the GC in general.

**Comment by stonetradex** [comment] 2021-12-17 16:14
![image](https://user-images.githubusercontent.com/72578743/146574641-f895290a-e147-4a72-8fca-6339286b3a07.png)

True

**Comment by johnsmith534** [comment] 2021-12-17 20:59
is there any proof that it should have a gcd?

**Comment by lilimx** [comment] 2021-12-19 16:40
Fixed with Patch 19/12/2021

**Closed** 2021-12-19 17:09 UTC
Labels: Ability

**Comment by Bejkon** [comment] 2022-08-14 22:56
Hej,

This is back. 

Pets(=NPCs?) does currently ignore GCD. 

I've only tested this on WL atm, but last time it was bugged it was the same for all the pet classes.

Not sure when it got rebugged, havent played daily lately and noticed it yesterday.

Could it be the mysterious combat changes here?:
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=48865

They atleast followed GCD 14days-ish ago.

Unrelated note: Before they started ignoring GCDs, they felt pretty clunky around stance swaps and most of the time would get hung up on a massive "GCD" after swapping stances, firing no abilities in the new stance for several seconds even tho they were all off CD. This has been the case for as long as they respected GCD. Its a hard thing to outline exactly tho, just a clunk ive noted.

/Bejk
