### ISSUE TITLE
No XP for kills with 400 AAO

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#14940] opened 2019-09-18 20:02 UTC
I killed 2 player in T2 with 400% AAO and did not get the XP because it was too much? -.-
The you should decrease the amount with 400% AAO but getting no XP is bad :/

![Knochenhexe_003](https://user-images.githubusercontent.com/45398873/65181719-f6ddf380-da5f-11e9-9307-f4352d154175.jpg)
![Knochenhexe_002](https://user-images.githubusercontent.com/45398873/65181720-f6ddf380-da5f-11e9-92a9-e81b6ecc8583.jpg)

**Comment by sioding** [comment] 2019-09-19 16:22
Duplicate of #10925

**Closed by sioding** 2019-09-19 16:22 UTC
