### ISSUE TITLE
knight of the blazing sun

### ISSUE THREAD

**Issue by jucawar** [WarEmu/WarBugs#16524] opened 2020-04-27 01:45 UTC
Hi

You are doing a great job with the game!!! (I love to play it)  

I have (I think) found two bugs on the knight of the blazing sun: 

1 - the morale 2 - Emperor's champion - when activated, should be on per 30 seconds, but stay on only 15 seconds.  
2 - block chance - I have been comparing with the other tanks and realized that the block chance is too low. 
I made a compacion with a IB, the "knight of the blazing sun" has half of the block chance. (similiar shield)
Additionally, I found a site the make this calcutions etc.. .to see the damage reduction etc... and there show me a different number for block chance. (comparade to game) 
https://tools.idrinth.de/tank/?

I hope you can check it. 

BR

KN

**Comment by SilverWF** [comment] 2020-04-27 02:07
Poor Kaelang...

**Comment by Kaelang** [comment] 2020-04-27 02:08
Your first point is a bug, which is a duplicate of the report here: https://github.com/WarEmu/WarBugs/issues/13665

The second point is a suggestion / feedback so I'd suggest writing up here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

Closed.

**Closed by Kaelang** 2020-04-27 02:08 UTC
