### ISSUE TITLE
Fell through the floor in TV

### ISSUE THREAD

**Issue by xFailsafeNY** [WarEmu/WarBugs#16386] opened 2020-04-14 18:08 UTC
While capping the firing range BO, i fell through the floor into lava

![image](https://user-images.githubusercontent.com/18269402/79258585-5c109080-7e59-11ea-80fe-c3892f6d616d.png)

**Comment by Kaelang** [comment] 2020-04-19 15:51
Duplicate of https://github.com/WarEmu/WarBugs/issues/13715

**Closed by Kaelang** 2020-04-19 15:51 UTC
