### ISSUE TITLE
Cant click war wagon Stonetroll country. Death on the steppes east vs west event quest

### ISSUE THREAD

**Issue by mendi92** [WarEmu/WarBugs#20421] opened 2022-09-17 08:37 UTC
Expected behavior: Click on the war wagon, complete quest objective 
Actual behavior: Cant click on War wagon

Can click on troll stone but no war wagon

**Steps to reproduce the problem:**
Join stonetroll country scenario with Death on the steppes east vs west event quest and try to click war wagon.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/92628518/190848316-b5f6193b-3343-42b6-a3ee-4d5da191613e.png)

![image](https://user-images.githubusercontent.com/92628518/190848251-5de0df3e-1c07-449e-885e-7423d55a375f.png)

**Comment by wulfgen760** [comment] 2022-09-17 15:17
I can confirm. Bugged the exact same way with me

**Comment by lilimx** [comment] 2022-09-17 15:31
Hey,

thx. Max will take a look at it.

**Comment by JadeCobraz** [comment] 2022-09-17 17:45
Same issue here, cant complete events quests if its impossible.

**Comment by JadeCobraz** [comment] 2022-09-18 18:45
Can confirm this is now fixed and working as intended today. TY

**Comment by MaxHayman** [comment] 2022-09-18 18:46
Thank you

**Closed by MaxHayman** 2022-09-18 18:46 UTC
Labels: Scenarios, World Object, Events

**Comment by lilimx** [comment] 2022-09-19 17:03
Hotfix 18/09/2022
