### ISSUE TITLE
Runepriest in "dps" spec

### ISSUE THREAD

**Issue by pawel2001** [WarEmu/WarBugs#14999] opened 2019-10-01 17:08 UTC
good morning, playing runepriest in the "dps" specialization, I noticed a huge difference in the damage inflicted, namely:
when changing zones, the damage changes a lot into smaller damage. (first screenshot)
![Heartofsteel_003](https://user-images.githubusercontent.com/51489596/65983489-e117f780-e47d-11e9-90f8-4a7bfc52454b.jpg)

when you disable and enable the "rune of breaking" skill, the damage increases. (
second screenshot)
![Heartofsteel_004](https://user-images.githubusercontent.com/51489596/65983640-4cfa6000-e47e-11e9-9e31-47c25f1ca3c8.jpg)

granie runepriest w konfiguracji na robieniu uszkodzeń jest bardzo ciężkie, każda zmiana strefy, wejście scenariusze, potem, wyjście. zawsze trzeba pilnowac tego problem, proszę o pomoc.

**Comment by globalgame** [comment] 2019-10-08 10:29
https://github.com/WarEmu/WarBugs/issues/14717 it is all the same

**Comment by sioding** [comment] 2019-10-08 12:04
Duplicate of #14717

**Closed by sioding** 2019-10-08 12:04 UTC
Labels: Ability
