### ISSUE TITLE
[quest] wicked things 

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#11838] opened 2018-06-04 03:05 UTC
talked to Vorque and took this quest but sacks are not spawning ; relogged but nothing changed, sacks still missing.

**Comment by sioding** [comment] 2018-06-04 03:18
Duplicate of #2157

**Closed by sioding** 2018-06-04 03:18 UTC

**Comment by zak68** [comment] 2018-06-04 03:53
One month ago this quest was working; sacks were popping and you were able to finish the quest.
