### ISSUE TITLE
[Squig Herder] Cut ya! not usable in Squig Armor

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13499] opened 2019-02-27 15:46 UTC
I don't know if intended but you cannot use the spell "Cut ya!" as melee spell from "Path of Bouncin'" in Squig Armor. It is greyed out

(on Level 12 SH)

**Comment by hrothgar22** [comment] 2019-02-28 19:09
not a gm but since live cut ya has never worked while in squig armor

**Comment by grunbag** [comment] 2019-03-01 09:35
never been usable in squig armor. it's not a bug. closing

**Closed by grunbag** 2019-03-01 09:35 UTC
Labels: Ability

**Comment by xaraxdestr** [comment] 2019-03-01 22:27
ok i thought it was one, 
was my first SH ;)

**Comment by SilverWF** [comment] 2019-11-24 06:25
Please, consider to change this.
Yes, it always were like that (not usable while in armor) at Live, but you changed so many skills here and even created new ones, so I don't see a reasons to keep this single skill like it was at Live.
"Don't Hit me!" didn't worked while in the Squig armor too at Live, but here it does and this is fine.
Why do I think it must be changed:
1. This is melee skill with 5 ft range
2. This skill is from Bouncin' (melee) tree
3. This skill benefits greatly from STR stat and SH has a lot of it only in the Squig Armor

305 STR vs 797 STR
Cut Ya! became 1,5 times stronger, but I can't use that melee skill while being melee focused and in the special melee stance.

![2019 11 24-09 00](https://user-images.githubusercontent.com/16439840/69490598-9c1baa80-0e9b-11ea-82a2-b5cce3857c16.jpg)

Please, make it possible.
