### ISSUE TITLE
PVE - Ork chapter 1 and rvr flag

### ISSUE THREAD

**Issue by KasperHawker** [WarEmu/WarBugs#11528] opened 2018-03-30 09:36 UTC
Hi guys,

I'm currently doing the 100,000 squigs challenge and the easiest source is chapter 1 of the orc staging area. I logged out in the zone, and when i logged back in i was in the pve chapter 1 warcamp flagged for rvr and turned into a chick. I subsiquently cannot use any scroll to zone out of the region.

Unless this intentional it seems like a bizare bug to me, that pve flags you for rvr when logging in. 

![bug](https://user-images.githubusercontent.com/36804013/38133218-30397a5c-3406-11e8-9e3e-e83eea2714aa.JPG)

**Comment by sioding** [comment] 2018-03-30 10:20
Duplicate of #10794

**Closed by sioding** 2018-03-30 10:20 UTC
