### ISSUE TITLE
The door porting lever seems to be behaving a little erratic when you try to port through the door.

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#119] opened 2014-05-10 19:23 UTC
I know this is just a temp quick fix for the time being. But lately it's been acting erratic and causing a few issues with clipping really badly into the building.

Usually I just keep clicking the lever until it finally ports me in safely.

This time it clipped badly that I fell through the building underground.

![door porting lever](https://cloud.githubusercontent.com/assets/7492543/2936878/73cb4ed2-d878-11e3-8d26-e51637667339.png)

![door porting lever causes clipping](https://cloud.githubusercontent.com/assets/7492543/2936879/8d2f3a5a-d878-11e3-83dd-5e9d116b500a.png)

**Comment by Evildoor** [comment] 2015-10-29 10:53
Closing as not a bug. As said above, teleporting through doors instead of opening them is a temporary fix, which is not perfect, but will have to do until doors are implemented properly.

**Closed by Evildoor** 2015-10-29 10:53 UTC
Labels: Emulator, Low Priority, World Object
