### ISSUE TITLE
Quest can not be completed - Nordland  - Empire - T1 - Grimmenhagen Village > Destroy Hellcanons

### ISSUE THREAD

**Issue by dvbrada** [WarEmu/WarBugs#18860] opened 2021-04-19 01:44 UTC
**Expected behavior and actual behavior:**
QUEST > Return Fire

Destroy 2xHellcanons > destroy 2xHellcanons using Empire cannons or any other way.

After destroying 2xHellcanons the quest won't be finished the tracker shows 0/2 , this was confirmed with 2 more player on the scene.

**Steps to reproduce the problem:**
Take the quest and destroy 2x Hellcannons

**Testing Screenshots/Videos/Evidences (always needed):**

N\A

**Comment by avalus** [comment] 2021-04-20 16:02
I confirm that this quest is not finishable in its actual state, whether you destroy both Hellcannons with Empire cannons (takes some time) or yourself.

**Comment by Lheana** [comment] 2021-04-20 16:46
Duplicate of #18769

**Closed by Lheana** 2021-04-20 16:46 UTC
