### ISSUE TITLE
enemy oil on frendly keep

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16002] opened 2020-03-16 02:29 UTC
enemy spawned oil inside our keep
![Frankenstien_014](https://user-images.githubusercontent.com/44329952/76718232-12bb0d00-6704-11ea-8e35-50a7b92e939b.jpg)

**Comment by Kaelang** [comment] 2020-04-21 13:09
Duplicate of https://github.com/WarEmu/WarBugs/issues/15838.

**Closed by Kaelang** 2020-04-21 13:09 UTC
