### ISSUE TITLE
Blood of my blood is not healing 

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13523] opened 2019-03-02 20:05 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

to heal people arround me in 100ft

**Steps to reproduce the problem:**
just casting the spell ,,, takiing dmg but none is getting any heal

**Screenshots/Videos or archive.org evidences:**

**Comment by Tazo83** [comment] 2019-03-02 20:09
![image](https://user-images.githubusercontent.com/42385505/53687017-21749300-3d40-11e9-8c8f-2667af4e962a.png)

**Comment by Tazo83** [comment] 2019-03-02 21:12
Your Restore Essence heals Madmekz for 461 points.
Your Lingering Restore Essence heals Madmekz for 119 points.
Your Lingering Restore Essence critically heals Madmekz for 230 points.
Your Soul Infusion heals Poxi for 0 points. (448 overhealed)
Your Lingering Restore Essence heals Madmekz for 148 points.
Your Covenant of Vitality heals Abis for 0 points. (57 overhealed)
Your Blood of my Blood hits you for 380 damage.
Your Lingering Restore Essence heals Madmekz for 148 points.
Your Khaine's Vigor heals Gemork for 382 points.
Your Khaine's Vigor heals you for 380 points. (2 overhealed)
Your Blood of my Blood hits you for 380 damage.
Your Khaine's Vigor heals Rdx for 0 points. (382 overhealed)
Your Khaine's Vigor heals Abis for 198 points. (184 overhealed)
Your Khaine's Vigor critically heals Blumnmoscha for 275 points. (273 overhealed)
Your Lingering Restore Essence heals Madmekz for 148 points.
Your Soul Infusion heals Poxi for 0 points. (448 overhealed)
Your Blood of my Blood hits you for 380 damage.
Your Blood of my Blood hits you for 380 damage.
Your Blood of my Blood hits you for 380 damage.
Your Khaine's Vigor heals Blumnmoscha for 382 points.
Your Khaine's Vigor heals Gemork for 382 points.
Your Khaine's Vigor heals you for 382 points.
Your Khaine's Vigor critically heals Rdx for 533 points.
Your Khaine's Vigor heals Abis for 0 points. (382 overhealed)
Your Covenant of Vitality heals Gemork for 57 points.
Ability failed

**Comment by grunbag** [comment] 2019-03-02 21:51
Did you made your test on group members or allies ?

**Comment by Tazo83** [comment] 2019-03-02 22:34
group members ofc i know it doesn't work on wb other parties  so yes answering your question i did use it to heal my party member

**Comment by grunbag** [comment] 2019-03-02 22:36
Fixed at next patch

**Comment by sioding** [comment] 2019-03-03 05:50
Duplicate of #12782

**Closed by sioding** 2019-03-03 05:50 UTC
