### ISSUE TITLE
Cascades of thunder resource drop

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13699] opened 2019-03-22 15:22 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

the banner is order and named order resource drop  inside destro keep

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Deadbabyface_010](https://user-images.githubusercontent.com/42385505/54833587-6ea8ac80-4ccf-11e9-9bbd-0ad88e1216fc.jpg)

**Comment by sioding** [comment] 2019-03-22 15:44
Duplicate of #12786

**Closed by sioding** 2019-03-22 15:44 UTC
