### ISSUE TITLE
Magnet over the fence? bug or not?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11708] opened 2018-05-01 20:29 UTC
My character was standing from the opposite of the fence and get magnet over the fence. Bug or not?
![meteore_019](https://user-images.githubusercontent.com/16274785/39492170-0c6ca32c-4d8f-11e8-9658-34bfb5fc3cc4.jpg)

**Comment by LestiArdisson** [comment] 2018-05-01 20:59
From Engineer Point of view:
Magneting through a fence usually draws the enemy into the fence.

From Magus Point of view:
In High Pass Tower on the flag is a fence above the stairs. A MAgus standing directly below the fence on the stairs can pull you over the fence on top and then down to them one level below.

So my assumption would be that magus pulls somehow the target first more up and then to you. But as far as I know both pulls should work the same.

**Comment by sioding** [comment] 2018-05-02 12:44
Duplicate of #10889

**Closed by sioding** 2018-05-02 12:44 UTC
