### ISSUE TITLE
Don't Bawk

### ISSUE THREAD

**Issue by Rlp110747** [WarEmu/WarBugs#17137] opened 2020-06-15 15:26 UTC
This issue STILL EXISTS although it is marked as resolved. It IS NOT resolved, as it still does not work. It can be completed on a T1 character but NOT on a character that actually will run the gauntlet AS a chicken. If it is not going to be fixed please let us know and if it IS going to be fixed please fix it. I still love this game after all these years but these quest bugs are really annoying.

**Comment by Kaelang** [comment] 2020-06-15 15:36
What's wrong with it?

**Comment by Lheana** [comment] 2020-06-16 10:50
Duplicate of #16725
As you've already commented on the existing issue, it means you knew there was a ticket still opened for this issue. In case you did not know, an opened issue means **it is not fixed**.
Don't create duplicates, and don't comment an issue to say "it's not fixed. When will it get fixed?".

**Closed by Lheana** 2020-06-16 10:50 UTC
Labels: 2 Week Ultimatum, Confirmation Request

**Comment by Rlp110747** [comment] 2020-06-17 14:58
It's designed to run blighted isle As A Chicken and explore the BOs, but no matter how many times tried it will not complete a single BO. I've tried when active pvp is on, when the isle is locked, and when it first opens up on multiple characters from lvl 16 up, and you cannot compete one BO much less all four. Without the quest this would be normal I guess but with the quest you should be able to complete the exploration of each BO to satisfy the quest requirements. Please see if this can be fixed as there is an achievement involved too called Run, Don't Bawk from Avelorn.

Sent from AT&T Yahoo Mail on Android 
 
  On Mon, Jun 15, 2020 at 10:36 AM, Kaelang<notifications@github.com> wrote:   


What's wrong with it?
