### ISSUE TITLE
High Elf Chapter 7 Basic Influence Reward's

### ISSUE THREAD

**Issue by cwsmitty11** [WarEmu/WarBugs#18026] opened 2020-11-02 01:45 UTC
**Expected behavior and actual behavior:**
Basic influence rewards shown be visible.
The entire row of basic rewards is invisible.
**Steps to reproduce the problem:**
Gain influence to be able to choose basic reward for High elf chapter 7 from Liradean Swiftarm.

**Testing Screenshots/Videos/Evidences (always needed):**

Not able to load screen/video because that happens is game says "taking a screenshot" but doesnt actually take the screen shot.

**Comment by Kaelang** [comment] 2020-11-02 18:18
Print Screen, paint.

**Comment by Lheana** [comment] 2020-11-07 18:29
Duplicate of #14553

**Closed by Lheana** 2020-11-07 18:29 UTC
