### ISSUE TITLE
Ram not spawning in T2/T3 

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#13780] opened 2019-04-01 06:49 UTC
Yesterday and today tried to spawn a ram when keep was 2 star, ellyrion T2 and in highpass T3, ram goes on cooldown and nothing spawns. Was using heavy chaos ram, others tried other ones so not specific to one object.

**Comment by sioding** [comment] 2019-04-01 17:08
Duplicate of #13407

**Closed by sioding** 2019-04-01 17:08 UTC
