### ISSUE TITLE
Summon Blue Horror

### ISSUE THREAD

**Issue by Billpullman** [WarEmu/WarBugs#16470] opened 2020-04-22 18:30 UTC
**Expected behavior and actual behavior:**
Summon Blue Horror doesn't increase Dodge/disrupt chance of magus by any %

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-04-22 18:32
Please can you provide .getstats / statdoll screenshots before and after summon.

**Comment by Billpullman** [comment] 2020-04-22 18:53
After checking .getstats, it actually increases dodge/disrupt but doesnt't shows in character stats

**Comment by Kaelang** [comment] 2020-04-22 18:58
The character stats screen can be misleading, but this is a known issue. As the ability is working as intended I'm going to close this for now. Thanks.

**Closed by Kaelang** 2020-04-22 18:58 UTC
Labels: 2 Week Ultimatum, Confirmation Request
