### ISSUE TITLE
[Quest] Darkelf Chapter 14 "And Thus With Traitors"

### ISSUE THREAD

**Issue by Coretin** [WarEmu/WarBugs#12198] opened 2018-08-22 20:19 UTC
Expected behavior and actual behavior:
In this step of the Questline I should talk to a Arkaneth Turncoat, so far so good. OK you 
can't talk to him, so you had to kill him. And after that, the quest seems completed, but there is nothing i can do. The spot to complete the Quest is right there where i killed the Turncoat, but there is no one i can turn in the quest. Thats it.

Steps to reproduce the problem:
Dunno anymore, seems a lot

Screenshots/Videos or archive.org evidences:

![calaniera_009marked](https://user-images.githubusercontent.com/42323967/44488539-4e414280-a659-11e8-8e3b-4ebadd497120.jpg)
![calaniera_008marked](https://user-images.githubusercontent.com/42323967/44488540-4e414280-a659-11e8-8fa1-36289d389a1d.jpg)
![calaniera_007](https://user-images.githubusercontent.com/42323967/44488541-4e414280-a659-11e8-8cdb-104f499f0d13.jpg)

**Comment by sioding** [comment] 2018-08-23 10:38
Duplicate of #11615

**Closed by sioding** 2018-08-23 10:38 UTC
