### ISSUE TITLE
I don't have a quest item.

### ISSUE THREAD

**Issue by DDebosh** [WarEmu/WarBugs#19553] opened 2021-10-29 21:15 UTC
in the task:a skull unlike any other. I don't have a quest item. that I need to complete the quest
![image](https://user-images.githubusercontent.com/93408106/139513829-9029b09f-a567-400c-8295-f7a973ad2d12.png)

![image](https://user-images.githubusercontent.com/93408106/139502343-4212ffd4-848e-4f52-9524-ea923bd27d52.png)

i can't take the quest skull, help me take the quest item, i have it not active.

**Comment by DDebosh** [comment] 2021-10-29 21:17
i can't take the quest skull

**Comment by Lheana** [comment] 2021-10-30 11:43
Duplicate of #19524

**Closed by Lheana** 2021-10-30 11:43 UTC
Labels: Database, Quests, Item, Karak-Eight-Peaks
