### ISSUE TITLE
bug with lava snare

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12568] opened 2018-11-11 16:53 UTC
hi after dying in lava in tor anroc scenario i was still snare even with my horse even with /rel and even after the scenario in sigmar s hammer 

![capture d ecran 27](https://user-images.githubusercontent.com/44948395/48315756-8910a200-e5da-11e8-8172-b9a9a0d02182.png)
![capture d ecran 28](https://user-images.githubusercontent.com/44948395/48315757-8910a200-e5da-11e8-9c5e-60a0fd2954bb.png)
![capture d ecran 29](https://user-images.githubusercontent.com/44948395/48315758-8910a200-e5da-11e8-94c1-80fcd991e4b0.png)
![capture d ecran 30](https://user-images.githubusercontent.com/44948395/48315759-8910a200-e5da-11e8-9d36-7320d6b4c562.png)
![capture d ecran 31](https://user-images.githubusercontent.com/44948395/48315760-89a93880-e5da-11e8-80ad-6e1aab034e44.png)

thanks

**Comment by sioding** [comment] 2018-11-11 17:34
Duplicate of #12472

**Closed by sioding** 2018-11-11 17:34 UTC
