### ISSUE TITLE
Raven Host Vanguard PQ

### ISSUE THREAD

**Issue by xero180** [WarEmu/WarBugs#13287] opened 2019-02-04 20:03 UTC
This PQ is bugged and will not progress past stage 2

**Comment by sioding** [comment] 2019-02-04 20:06
Duplicate of #12685

**Closed by sioding** 2019-02-04 20:06 UTC

**Comment by WO-RoR-Exile** [comment] 2019-12-03 12:32
Still an issue. 12/03/2019.
![Argog Bug](https://user-images.githubusercontent.com/58471571/70051424-9eb28a00-1596-11ea-8f13-3a3b50b483cb.png)
