### ISSUE TITLE
Missing royal crests from city

### ISSUE THREAD

**Issue by TheOctagon322** [WarEmu/WarBugs#18229] opened 2020-12-19 22:04 UTC
**Expected behavior and actual behavior:**
Got 3 crests from winning stage 1
Stage 2 + stage 3 missing + wasn't in on the bag rolls

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/64733933/102700509-cf736900-4256-11eb-8586-3ce5db0b8d60.png)

Picture doesn't say much tbh, but I don't have any other proof

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->

**Comment by Denteron** [comment] 2020-12-20 19:31
Hello/ What ppl may to see on your screenshot ?  How to reproduce bug/ and where is bug?

**Comment by dalen** [comment] 2020-12-20 23:09
if it was due to crash & reconnect it should be fixed now since Hotfix 2.

**Closed by dalen** 2020-12-20 23:09 UTC
