### ISSUE TITLE
Sacellum Dungeons:High lvl abbilities can bug all low/high lvl skills and therefore none of them will work.

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#12097] opened 2018-07-28 16:30 UTC
Expected behavior and actual behavior: If you press any of your high lvl skills (the ones that are red), you wont be able to use any low level enabled skills. Workaround is if you go out and re enter the dungeon.

Steps to reproduce the problem: press any skills that you shouldn't be allowed to use

Screenshots/Videos or archive.org evidences: -

**Comment by sioding** [comment] 2018-07-29 03:46
any errormessages?

**Comment by Dobzse** [comment] 2018-07-30 07:31
Only Invalid Target.

**Comment by sioding** [comment] 2018-07-30 11:12
Duplicate of #12100

**Closed by sioding** 2018-07-30 11:12 UTC
Labels: 2 Week Ultimatum, Confirmation Request
