### ISSUE TITLE
Stealth Issue for both WH and WE's

### ISSUE THREAD

**Issue by rook75** [WarEmu/WarBugs#20368] opened 2022-08-23 01:19 UTC
**Expected behavior and actual behavior:**
Forced Cooldown to drop stealth - Cant capture points/Mount/ DO anything.  This is game breaking for stealth classes.  Please fix

**Steps to reproduce the problem:**
Stealth and try to unstealth

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/53187907/186047240-5da80818-f714-408d-8078-42bb6672a116.png)

**Comment by rook75** [comment] 2022-08-23 01:20
Cooldown is 30 seconds to DROP stealth.

**Comment by xpander69** [comment] 2022-08-23 06:20
This is not a bugreport. Thats how it has always worked, unless i understand you wrong somehow.
In case of WE, you can use Elixir of Shadows, if you spec into it to get a instant stealth for 2 seconds and faster run speed.

**Comment by Zomega-WAR** [comment] 2022-08-23 08:39
> 

It's not about trying to stealth up again, it's about the ability being bugged and not letting you leave stealth.

What should happen is once you enter stealth, the stealth ability is toggled on but not yet on cooldown. This allows you to press it again to leave stealth, at which point it goes on cooldown (also goes on cooldown if you leave stealth from other means).

Currently the stealth ability is bugged, and when you use it to enter stealth, it also immediately goes on cooldown so you cannot use it again to end your stealth early. You're forced to stay stealthed until the cooldown expires.

It's also a duplicate of https://github.com/WarEmu/WarBugs/issues/20302 :)

**Comment by xpander69** [comment] 2022-08-23 08:48
Ahh, thank you for clarifying. the Original post was kinda confusing and lacked information

**Comment by xpander69** [comment] 2022-08-23 08:49
Closing because dupliocate of https://github.com/WarEmu/WarBugs/issues/20302

**Closed by xpander69** 2022-08-23 08:49 UTC
Labels: Confirmation Request, 2 Week Ultimatum

**Comment by rook75** [comment] 2022-08-23 12:45
You misunderstand.  It's the reverse cool down of going into stealth.  You can't unstealth for 30 seconds.  It's never been like that except for the last two patches.  Sounds silly but it completely breaks the game for a stealthier.On Aug 23, 2022 01:20, xpander69 ***@***.***> wrote:
This is not a bugreport. Thats how it has always worked, unless i understand you wrong somehow.
In case of WE, you can use Elixir of Shadows, if you spec into it to get a instant stealth for 2 seconds and faster run speed.

**Comment by rook75** [comment] 2022-08-23 12:53
I am mildly offended hah, it was perfectly clear.  I laid out the issue in
concise terms.

I was unable to find the other report, sorry.  Do we have an ETA on a
resolution for this bug?  I mean it really is game breaking for stealthers.

Thanks!

Colin Gray

**Comment by xpander69** [comment] 2022-08-23 12:57
Yeah sorry. English isnt my native so i completely got your first message wrong :D but Omegus cleared it up.
No ETA currently to share.

**Comment by rook75** [comment] 2022-08-23 13:11
No worries man!  I understand prioritization, but I just want to ensure you
understand this breaks core functionality of certain classes.

Extremely frustrating.

Thanks!

Colin Gray
"Freedom isn't Free"
