### ISSUE TITLE
Malgrog down't have Rewards Choise in Chapter 8

### ISSUE THREAD

**Issue by cooler-SAI** [WarEmu/WarBugs#14813] opened 2019-08-20 17:01 UTC
Go to Greenskins chapter 8 and talk to Malgrog! He doen't have first choise rewards!
![Vikkz_001](https://user-images.githubusercontent.com/812439/63367817-5378c080-c385-11e9-98d6-581a727354a2.jpg)

**Comment by sioding** [comment] 2019-08-20 19:44
Duplicate of #12835

**Closed by sioding** 2019-08-20 19:44 UTC
