### ISSUE TITLE
Sigmar's Grace heals people at full health and acts as a aoe heal

### ISSUE THREAD

**Issue by offdensen** [WarEmu/WarBugs#12719] opened 2018-11-26 05:27 UTC
In regards to the ability "Sigmar's Grace"
Expected behavior and actual behavior:
Expected: Applies buff upon buff being given and adding wounds. 
Actual: It appears to heal based on the amount of wounds added. You can use it over and over again to heal everyone in the warband even if they already have the buff, because the ability heals people who already have it. It heals for 760 as on my character at level 40. You can use it to heal people at full health. In my test it heals everyone in a scenario and can be used to inflate numbers and be an aoe heal for the whole scenario.  Based on the tooltip, it doesn't seem like this was intended to be an aoe heal

Steps to reproduce the problem:
Don't let it heal people at full health or people whom already have the buff

Screenshot: I tested it in a small scale engagement as shown. I wasn't able to get back into a scenario to test it there, but you can still see it acts as an aoe heal in ORVR
![augustus_000](https://user-images.githubusercontent.com/45347914/48994562-d3287600-f0f8-11e8-94f4-e6e116a609a8.jpg)

**Comment by sioding** [comment] 2018-11-26 12:11
Duplicate of #11425

**Closed by sioding** 2018-11-26 12:11 UTC
