### ISSUE TITLE
The Bully title

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#18488] opened 2021-02-12 12:48 UTC
According to Tome Titan and forum there is a title unlock The Bully (if you play destro) in High Pass, 18.3 - 23.3 I've been killing and running around in the area for 1 hour now but the unlock won't come.

**Comment by Lheana** [comment] 2021-03-21 17:06
Duplicate of #8706

**Closed by Lheana** 2021-03-21 17:06 UTC
