### ISSUE TITLE
T3 RvR Influence Cloak Ghrond's Greatcloak

### ISSUE THREAD

**Issue by meleriex** [WarEmu/WarBugs#4223] opened 2016-02-03 23:26 UTC
has had "Blackguard" affix added it to it for some reason.  I am a Witch Elf, I am unable to wear it now.

:(

character name = Cnote R32RR37 witch elf

**Comment by Styrkarr** [comment] 2016-02-03 23:58
[#4207](https://github.com/WarEmu/WarBugs/issues/4207)

**Comment by meleriex** [comment] 2016-02-04 00:35
so im out of a cloak or?

**Comment by Torquemadra** [comment] 2016-02-04 05:32
pm a gm on the forums

**Comment by Evildoor** [comment] 2016-02-04 07:41
Not a bug, but collateral damage caused by bug fixing. Closing.

**Closed by Evildoor** 2016-02-04 07:41 UTC
