### ISSUE TITLE
Sometimes the melee enemies are far away

### ISSUE THREAD

**Issue by Garrulillo** [WarEmu/WarBugs#19174] opened 2021-06-18 18:50 UTC
Since the patch 18/06/21, I realize that sometimes, not often but sometimes, in the middle of a fight some melee attacks begins to execute but not end, being aborted in the process as if foe were too far away... but actually is stick to you. As if the game were not able to especify for moments where the foe is.

**Comment by lilimx** [comment] 2021-06-18 19:46
Hey,

I know it's a weird issue, but I need a bit more information, screenshots or so to reproduce this issue or to find a hint what went wrong.

**Comment by Tesq** [comment] 2021-06-19 23:52
seems like range of all melee atk and initial first atk in case of channeling got reduces somehow, i felt this too playing these days litteraly.

**Comment by lilimx** [comment] 2021-07-03 13:01
Hey,

sorry, but I have to close this ticket now. I need a proper evidence otherwise we can't reproduce issue.

**Closed by lilimx** 2021-07-03 13:01 UTC
