### ISSUE TITLE
[Fort] DC reservation system still not functional

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#13602] opened 2019-03-10 21:33 UTC
I crashed out of Reikwald, and upon logging back in and clicking on the portal nothing happens. No error messages about resources, nothing.  After 5 minutes I got a system notice that my reservation had expired, but clicking on the portal after that still did not give any resource messages.  Nothing.

![Rydiak_427](https://user-images.githubusercontent.com/15963532/54091789-2fcf3a00-4352-11e9-8149-b8e2d4faf13f.jpg)

**Comment by sioding** [comment] 2019-03-11 16:55
Duplicate of #13536

**Closed by sioding** 2019-03-11 16:55 UTC
