### ISSUE TITLE
[PQ][Item] Cross-faction item in PQ reward bag

### ISSUE THREAD

**Issue by jmm327** [WarEmu/WarBugs#14388] opened 2019-06-09 19:19 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
T2 PQ "Welcome to Troll Country" completed as Order Ironbreaker, received a blue reward bag which contained Hrue Bigloppa, a rare Black Orc/Choppa 2h axe.

**Steps to reproduce the problem:*
Receive blue loot bag on Ironbreaker from this PQ for a chance to see this drop

**Testing Screenshots/Videos/Evidences (always needed):**
![Lionbeard_000](https://user-images.githubusercontent.com/51540289/59163111-1d3bdc80-8aca-11e9-91e2-07adfe546e3f.jpg)

**Comment by sioding** [comment] 2019-06-10 08:19
Duplicate of #11739

**Closed by sioding** 2019-06-10 08:19 UTC
