### ISSUE TITLE
Broken PQ Pure Power - High Elf Chapter 22

### ISSUE THREAD

**Issue by Mhagrim** [WarEmu/WarBugs#13718] opened 2019-03-24 16:38 UTC
Its broken pq pure power, no mobs are visible. Visible is only one champion - screen 3.

Second problem is that in area of this pq is a part of epic quest unmasking the enemy and its impossible end this part of epic quest.

![Gilead_000](https://user-images.githubusercontent.com/48887867/54882546-61202d80-4e5b-11e9-9c06-f867590a4955.jpg)

![Gilead_001](https://user-images.githubusercontent.com/48887867/54882557-7c8b3880-4e5b-11e9-896c-46ce2ecc3269.jpg)

![Gilead_002](https://user-images.githubusercontent.com/48887867/54882567-a2b0d880-4e5b-11e9-8b03-a07b3b176a3d.jpg)

Tx for solve this problem.

**Comment by Lheana** [comment] 2019-03-24 16:52
Duplicate of #10862

**Closed by Lheana** 2019-03-24 16:52 UTC
