### ISSUE TITLE
Serpent passage salvage not able to cap

### ISSUE THREAD

**Issue by Kelthas** [WarEmu/WarBugs#7012] opened 2016-06-28 20:19 UTC
Currently both order and destruction dont seem to be able to cap the
salvage part.

Played self Destro T3 and couldnt cap and Order had same issue.

**Comment by genisaurus** [comment] 2016-06-29 22:09
Duplicate of https://github.com/WarEmu/WarBugs/issues/7001

**Closed** 2016-06-29 22:09 UTC
Labels: Scenarios, World Object
