### ISSUE TITLE
PQ's giving double credit for kills

### ISSUE THREAD

**Issue by Psyk16** [WarEmu/WarBugs#11234] opened 2018-01-30 05:13 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Yesterday I noticed multiple PQ's were giving double credit for kills towards the overall count. For example, if you needed to kill 8 of enemy x for stage 2, if you killed 1 of enemy x, the counter would go up by two. I noticed this happening for Lursa's Blight in Troll Country, and  Ironrock Point in Barak Varr.

Steps to reproduce the problem:
I believe this was only happening in Stages 2 of both PQ's, but I'm not positive. 

Screenshots/Videos or archive.org evidences:

Hope this helps! Feel free to reach me in-game on Psynned, Destro

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-01-30 08:50
Duplicate of #11161

**Closed by sioding** 2018-01-30 08:50 UTC
