### ISSUE TITLE
FPS Drop due to Altdorf Airship

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#11599] opened 2018-04-13 23:20 UTC
Upon entering rendering distance from the airsip in altdorf, client suffers huge lag spike and FPS drop due to the high poly count, moving airship model. Unavoidable due to its position over the flightmaster.

The airship model was added in live when LOTD was introduced.

Suggesting it be removed to reduce strain/lag/crashes

https://youtu.be/gvAgqDnbP58

**Comment by sioding** [comment] 2018-04-14 04:35
Duplicate of #11576

**Closed by sioding** 2018-04-14 04:35 UTC
