### ISSUE TITLE
Melee Squig - Pet ability damage not scaling with "He's A Biggun" tactic 

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#13898] opened 2019-04-16 20:12 UTC
**Expected behavior and actual behavior:**

You should be able to slot this tactic for 160 more pet strength and increase ability damage and tactic damage as it increases the pets base strength by 160.

When you slot tactic. Pet AA increases but pet ability damage remains the same. 

**Steps to reproduce the problem:**

Summon horned squig, use gore ability without 160 pet str tactic. Now slow pet 160 str tactic and the damage on AA's increases, but the pet ability damage does not. 

**Screenshots/Videos or archive.org evidences:**

Picture without tactic 
https://imgur.com/OvylrL8

Picture with tactic 
https://imgur.com/S3FewdD

**Comment by grunbag** [comment] 2019-04-19 15:24
@natherul or @secret need to look into code, cause pet abilities should scale with str

**Comment by Lumberjackscoot** [comment] 2019-05-24 01:07
Should this ability also increase the players Stat's when they have Squig Armor applied to them? When I slot the tactic "He's A Biggun" while having the ability Squig Armor applied to myself my Toughness and Strength are increased by 1 point. Even without the my character being in Squig Armor I still get the increased 1 point into Strength and Toughness. 

Thought I just post this here for more information. Hope this helps!

**Comment by Kaelang** [comment] 2020-05-16 18:18
![image](https://user-images.githubusercontent.com/60117106/82127265-11609c00-97aa-11ea-9432-66d32d77f52a.png)

Start is tactic equipped.
End is tactic not equipped.

Looks like this is working as intended.

**Comment by Kaelang** [comment] 2020-05-16 18:20
Ok confirmed, abilities aren't scaling with strength gained from tactic.

**Comment by Rildetarma** [comment] 2020-08-01 13:38
What is the result of this?  It doesn't seem the scaling problem has been addressed.  Has any action been taken?

**Comment by grunbag** [comment] 2020-12-15 17:36
Fixed with next patch

**Closed by grunbag** 2020-12-15 17:36 UTC
Labels: Ability, Fix Pending
