### ISSUE TITLE
Misisng BeastLord Token

### ISSUE THREAD

**Issue by Hattiro** [WarEmu/WarBugs#11163] opened 2018-01-17 12:34 UTC
Hi my Rp Gieselle do all Steps for the BL Quest , only one Last kill quest is open, but i have only 3 Token at my inventory. Ive checked all Quest giver, but there is no Quest to get. but i need all 5 Tokens to get the pocket item :(.

Cheers 

Yip

**Comment by sioding** [comment] 2018-01-17 14:18
Duplicate of #10721

**Closed by sioding** 2018-01-17 14:18 UTC
