### ISSUE TITLE
Taking the last zones often ends in a bugged lock - forexample - earlier today we fought Order in Black Crag, defended, took BO's and repelled Order as best we could till zone lock. No Bags for us, and fort instantly was taken in orders favour. Resulting in 4 Emblems and bags for order on top of getting loot in the previous zone (Black Crag) While destro got nothing of either.

### ISSUE THREAD

**Issue by Zurbak** [WarEmu/WarBugs#13689] opened 2019-03-20 13:04 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
When a Zone locks, both sides should get RR, INF and EXP. And both factions should get loot bags.

**Steps to reproduce the problem:**
Fight in ORVR - take a zone (oftentimes happen in the last zone in T4 - like Black Crag) Then when the zone locks you should not get rewards as intended. This has happened to me on at least 4 occasions within a week, and is now (imo) a confirmed issue. The

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/48727657/54686172-f5675900-4b18-11e9-81b2-161be7700e32.png)

**Comment by sioding** [comment] 2019-03-20 17:03
Duplicate of #13653

**Closed by sioding** 2019-03-20 17:03 UTC
