### ISSUE TITLE
Crash During Fort No Medallions

### ISSUE THREAD

**Issue by randallbcotter** [WarEmu/WarBugs#14539] opened 2019-07-07 00:49 UTC
I was taking part in a fort @ Shining Way on my Sorc Rootagast on July 6th ~ 7pm EST. Crashed 3 times during that fort, and the last crash was with 1 minute left (we weren't going to win). When I logged back in I received the renown, but didn't receive any Invader Medallions. Nothing in the mail, no bags / tokens. Just frustrating spending an hour in there (and putting up with the game crashing over and over) and not getting anything medallions for my effort. 

**Expected behavior and actual behavior:**
Expected to receive 6(?) Invader Medallions for failing to take fort, received none because of crash to desktop.

**Steps to reproduce the problem:**
CTD with ~1min left on fort and recieve no medallions

**Testing Screenshots/Videos/Evidences (always needed):**
![Capture](https://user-images.githubusercontent.com/18149268/60762485-91b55d00-a02f-11e9-9abc-7c955a8841a3.PNG)

**Comment by sioding** [comment] 2019-07-07 10:17
Duplicate of #14072

**Closed by sioding** 2019-07-07 10:17 UTC
