### ISSUE TITLE
Siege weapon unlimited

### ISSUE THREAD

**Issue by retkeszaju** [WarEmu/WarBugs#10515] opened 2017-09-27 22:10 UTC
Hy, i had an old char that head siege weapons from back when u could hold multiple number of siege weapons in 1 inventory slot. Issue is that u can spawn probably endlessly whit this bug like i had 2 single target cannon and i spawned 4 from it and it still wrote i have 2 from it (quality on the cannon aint decreased) tryied it whit single, aoe and oil, oil working as it should, aoe and single is bugged and can be abused. (to be more specific i used heavy chaos hellcannon, and heavy greenskin lobba)

EDIT: i destroyed the bugged cannons, bought new ones (bought 2-2 from single+aoe they where on separeted inventory slot) and still it wont move from my inventory if i deploy em.

**Comment by Titoos** [comment] 2017-10-23 12:53
Duplicate of #10352

**Comment by sioding** [comment] 2017-10-23 13:02
Thanks @Titoos

**Closed by sioding** 2017-10-23 13:02 UTC
Labels: ORvR
