### ISSUE TITLE
Guild Standard

### ISSUE THREAD

**Issue by gman4gov** [WarEmu/WarBugs#18622] opened 2021-03-11 17:58 UTC
Guild Standard will not stow away once deployed.

**Comment by Caduceus42** [comment] 2021-03-11 19:26
Having the same issue. It seems this bug has been in the game for a while now.

**Comment by dalen** [comment] 2021-03-17 14:47
duplicate of https://github.com/WarEmu/WarBugs/issues/18521

**Closed by dalen** 2021-03-17 14:47 UTC
