### ISSUE TITLE
Constantly crashes in Altdorf

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#12894] opened 2018-12-22 09:26 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Every time I go from bank or career master or any place @ Altdorf to the center (auctioneer or flight master) my game crashes. My guild mates also experience this problem. It started from the last patch I guess.

Steps to reproduce the problem:
Move from bank or any side of the Altdorf to the center (ah for example)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-22 09:41
Duplicate of #12301

**Closed by sioding** 2018-12-22 09:41 UTC
