### ISSUE TITLE
Carrier Trainer

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#12325] opened 2018-09-17 22:48 UTC
I found a bug in the carrier trainer when we select all the points in 1 tree and we turn on Dreadful Fear its maximum power of this aura will remain even after the reset then you can repeat it with 2 and 3 trees and then we have OP chosen. 

![warchosen_036](https://user-images.githubusercontent.com/18600019/45653965-143d5200-bada-11e8-8d62-9f26ffb38457.jpg)
![warchosen_034](https://user-images.githubusercontent.com/18600019/45653976-1a333300-bada-11e8-91f5-e19ff47871c6.jpg)
![warchosen_035](https://user-images.githubusercontent.com/18600019/45653978-1c958d00-bada-11e8-923e-168279bec3ad.jpg)

**Comment by sioding** [comment] 2018-09-18 05:38
Duplicate of #12297

**Closed by sioding** 2018-09-18 05:38 UTC
