### ISSUE TITLE
Hotbar Button Mapping

### ISSUE THREAD

**Issue by LordMort** [WarEmu/WarBugs#7253] opened 2016-08-14 11:44 UTC
RoR
Server: Martyrs Square
Version 1.4.8 Build 573

After setting up a new character and using the initial key mappings / bindings, the "Hotbar Button 12"-mapping for the keyboard button "=" does not work. This includes the alternate mappings to this key, i.e. with the "CTRL"-key pressed at the same time.

The keyboard is set in the OS, Windows 10 x64, as an US International layout. On this layout the '='-key is set on the key directly to the left of the "Backspace"-key, respectively the 2nd key to the right from the "0"-key in the top row.

Upon checking whether it was possible to figure out the reason for this behaviour the following was found:
In the "Main Menu > Key Mapping > Hotbar"-menu the key mapping for the "Hotbar Button 12", as well as it's alternate mappings, was set to the "="-key, which was as expected. Pressing the '='-key on the keyboard unfortunately did not activate the assignes ability.

The next step taken was to try and see whether the keyboard layout was being interpreted as the one set in the OS, US International layout. This was done by setting up the "Hotbar Button 12"-binding again. When doning so the '='-key was being shown as being interpreted as the "PREVTRACK"-key.

An issue which appears to have basic simmilarities is the following (closed) one:
"Summon Squig: Death From Above #3979"

**Comment by Luth-RoR** [comment] 2016-08-18 18:04
Does the "=" key work for different bindings (e.g. hotbar button 11) or not at all?

**Comment by LordMort** [comment] 2016-08-18 22:10
Dear Luth-RoR,
Thank you for your reply.

To asnwer your question:
Yes and no.

Yes in the sense that by using the "Main Menu > Key Mapping > Hotbar" menu to bind the "Hotbar Button 12" to the same physical key again in-game, I was able to make the ablitites accessable again.

No in the sense that I am unable to use the "="-key in-game, seeing as it is being rcognized as another key.

When noticing this behavior for the first time I  tried with another application, latest version of Notpad++ at the time of playing and writing, wether or not this was something only happening in-game, or wether is was something "system-wide". In Notepad++ my keyboard was and is "behaving normally", meaning that when I press the "="-key on it, the "=" -character is being displayed.

What I did notice though is the following:
On my keyboard there is a second "="-key atop the numerical keys on the right hand side of the keyboard.

Before seeing whether or not rebinding the key for the "Hot Button 12" I tried if this key was being interpreted differently than it's counterpart in-game. This unfortunately was not the case, though not different than expected.

After this I tried to see wether the key was operational in-game by re-mapping it through the according menu. When doing so the "standard" "="-key was being recognized by the game as to be the "PREVTRACK"-button. By "standard" key I mean the '='-key which set on the key directly to the left of the "Backspace"-key, respectively the 2nd key to the right from the "0"-key in the top row.

After this successful "re-mapping" I tried whether the 2nd "="-key, the one atop the numerical keys, would be interpreted differently this time. It wasn't, meaning the it now also was being interpreted as the "PREVTRACK"-key in-game.

I don't think that this is anything like a mayor issue, but wanted to make sure that it was reported.

Regarding this issue, I do have one question that maybe you can help me with:
Could you tell me which file holds the definition for which keyboard layout is to be used in-game?
With this information I could conclusively tell whether or not the keyboard layout is being interpreted as being another one in-game than defined in the OS.
Thanking you in advance for your reply and time taken.

**Comment by Luth-RoR** [comment] 2016-08-19 14:55
Ok, i tested this a bit.
It seems that there is nothing wrong with your keyboard and any language settings.
Afaik the server/the database doesn't accept special symbols/characters for names and i think this is the case for keybinds too.
I further guess the server checks/saves the scancodes sent by the keyboard instead of the actual characters. This would explain why several keys don't work regardless of the language/layout settings and why = works on the german layout (it's over the zero key - shift+zero).

In the case of names it is justified, but should be fixed for keybindings if possible.

As i just guessed this, it needs confirmation from a develpoer.

**Comment by Luth-RoR** [comment] 2016-08-19 15:09
I just got info from a dev that the client interprets keystrokes as hotbar buttons and these hotbar buttons are stored on the server. So the issue is maybe client sided and can't be fixed atm.
Though you could try to create a new character and check if the problem is the same on him to be sure.

**Comment by LordMort** [comment] 2016-08-19 15:55
Hi Luth-RoR,

Thank you for your reply.

I have already created another character, with which I also have played for a bit. I have been able to confirm that the same issue also exists with this character.

What I can try is to download the client again, re-install it, and see whether or not that would help.

**Comment by LordMort** [comment] 2016-08-22 09:57
Hi there Luth,

I have yet to download the game once more to see whether or not a diffrenet / new installation would resolve the issue.

I have been playing a bit over the weekend and have tried to see whether or not I would find some hint to why the keyboad layout is interpreted differently in the game then it is in the rest of the OS and software. During this I came across the following interesting behaviour.

When using the chat in-game I was surprised to see that the "="-key was being interpreted "normally", meaning that it was reckognized as being the "="-key, and not as the "PREVTRACK"-key, as is still the case for the "Hot Buttong 12".

I find this behaviour quite interesting, seeing as this offers the following interpretation:
The "Hot Button"-keys are interpreting the keyboard, as well as it's layout, differently than they are in the "Chat"/ comm in-game.
Would this mean that the "Hot Buttons", as you stated above, are checked server-side, whereas the "Chat" / comm checks the key client-side?
Could you confirm this interpretation?

Note:
I have also verified this behaviour in my other character. Here the same issue happens as well. The "Hot Button 12" is assigned to the "="-key, which is interpreted as being the "PREVTRACK"-key. In the comm / "Chat" the same key is being interpreted as having it's actual value "=".

**Comment by Luth-RoR** [comment] 2016-08-22 19:02
I think redownloading won't solve the issue, but you could try it to be sure. Maybe someone else who reads this can remember if it didn's work on the mythic server(s) too.

**Comment by LordMort** [comment] 2016-08-29 18:13
Hi Luth,

Apologies for my late reply.

I've downloaded the game client once more. As you already suspected, using this client instead of the one originally downloaded did not solce the issue.

I did find a screenshot from my character from the original / old game from the Karak-Norn server. On this screenshot, see the attache picture below, I was able to make out the key mapping dor the "Hot Button" bar. The "="-key was configured for "Hot Button 12", and working.

Screenshot from character from Karak-Norn server:
![gotreksson_000](https://cloud.githubusercontent.com/assets/21020953/18061868/b957f984-6e24-11e6-812c-979881c2a245.jpg)

**Comment by Luth-RoR** [comment] 2016-08-29 18:43
So it's an issue with the RoR server; i think it's going to be fixed one day with more knowledge.
If it's very important to you to bind that key:
If you have any macro hard- or software, you could try to solve this issue by binding another (working) key to the = key. This way everytime you press =, they other key should be pressed too.

**Comment by LordMort** [comment] 2016-08-31 11:20
Hi Luth,

Thanks for your reply and solution provided / offered.

The solution of remapping to another key due to macros is not necessay, at least not for me. See my comment from nine days ago:
"
...
Note:
I have also verified this behaviour in my other character. Here the same issue happens as well. The "Hot Button 12" is assigned to the "="-key, which is interpreted as being the "PREVTRACK"-key. In the comm / "Chat" the same key is being interpreted as having it's actual value "=".
"

This in turn means that any macro, hard- or software, is working, as long as I "re-map" the "="-key for the "Hot Button"-part of the game, accepting that this part interprets it as the "PREVTRACK"-key, which I have not mapped anything to in the game. Seeing that the key is interpreted with it's right value for the rest of the game, i.e. the chat, this is something I can live with.

**Comment by LordMort** [comment] 2016-09-15 15:24
Hi Luth,

I'm not sure what happened, but since a few days the "="-key is being recognized as the "="-key again.
 Seeing as this has resolved the issue for me, I am going to closed this ticket.

Thank you for your replies and time taken!

**Closed** 2016-09-15 15:24 UTC
Labels: Minor
