### ISSUE TITLE
No dismount in water

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16135] opened 2020-03-29 00:37 UTC
After last patch I've noticed that after jumping to water while being mounted, my character visually became dismounted but keeps mount buff and moving with increased speed by his legs
Also it's possible to summon mount in the water while swimming

**Expected behavior and actual behavior:**
Exp: being dismounted removes speed buff
Act: it's not

**Steps to reproduce the problem:**
Summon mount,
jump on him to water,
make sure your character lost his mount,
check buffs

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/xM9_RfKUolU

**Comment by Lheana** [comment] 2020-04-01 12:51
Duplicate of #16037

**Closed by Lheana** 2020-04-01 12:51 UTC
