### ISSUE TITLE
Found sc bug

### ISSUE THREAD

**Issue by Rantric** [WarEmu/WarBugs#15056] opened 2019-10-23 15:22 UTC
This is my first time reporting a bug or issue, just wanted to let you guys know of it.

So logging into a Scenario I have been twice sent to the character selection screen, kinda. It shows the create new, quit , ect. buttons but I am in game and can't exit or do anything really but run around.

I will include a screen shot I took of the second time because I thought it was odd and worth bringing up to you guys!

Edit: also may be worth mentioning that both times were when I joined Thunder Mountain.

![Untitled](https://user-images.githubusercontent.com/56928787/67408694-64ad9b80-f587-11e9-89e5-918c0ce2fc9a.png)

**Comment by sioding** [comment] 2019-10-23 17:13
Duplicate of #11224

**Closed by sioding** 2019-10-23 17:13 UTC
