### ISSUE TITLE
Dark Elf Chapter 11 Influence Rewards

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11991] opened 2018-07-05 20:44 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Chapter influence rewards should appear at Rally Master once influence has been reached. The Basic Rewards are missing.

Steps to reproduce the problem:

Add Basic Rewards

Screenshots/Videos or archive.org evidences:

![ithilsyn_450](https://user-images.githubusercontent.com/22262165/42347039-7d72807e-809c-11e8-9d1d-6faf15cce9f5.jpg)

**Comment by sioding** [comment] 2018-07-06 15:37
Duplicate of #4821

**Closed by sioding** 2018-07-06 15:37 UTC
Labels: Database, Item
