### ISSUE TITLE
ORvR EXP gain prevented

### ISSUE THREAD

**Issue by blakkkout** [WarEmu/WarBugs#11784] opened 2018-05-19 23:37 UTC
Today I've spent more than half of my day in Kadrin Valey, in the end I got this message:

https://cdn.discordapp.com/attachments/334632350560419840/447541302113075211/Marmeladova_002.jpg

Quite disapointed atm for my wasted time :(

**Comment by sioding** [comment] 2018-05-20 00:17
Duplicate of #10925

**Closed by sioding** 2018-05-20 00:17 UTC
