### ISSUE TITLE
Gunbad 

### ISSUE THREAD

**Issue by Pentolino** [WarEmu/WarBugs#16338] opened 2020-04-10 14:33 UTC
**Expected behavior and actual behavior:**

Middle run, when you taunt a mob every mob in the instance appear and attack you
Public quest steps not showing 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-04-10 14:41
This has already been reported. Issue: 16317

**Comment by Kaelang** [comment] 2020-04-19 16:41
Duplicate of https://github.com/WarEmu/WarBugs/issues/16317.

**Closed by Kaelang** 2020-04-19 16:41 UTC
