### ISSUE TITLE
Squig herder pet issue attacking his owner

### ISSUE THREAD

**Issue by yacoucou** [WarEmu/WarBugs#12831] opened 2018-12-09 11:21 UTC
Happened to me several Times since 3 patchs. Appears in T2/T3 zones when u zone between the both opened zones. The pet attack his owner dismounting yourself and youre loosing hps and enter in combat (morales growing). It cant actually kills yourself, tested, it let you at 1hp.
This issue most being annoying can ne used bu some bas intented players to grow morales.
This will end if you kill the pet or summon another.
Noticed this bug in Ellyrion, high pass, barak var.

**Comment by sioding** [comment] 2018-12-09 13:12
Duplicate of #12216

**Closed by sioding** 2018-12-09 13:12 UTC
