### ISSUE TITLE
"Moonfang Stickointa" mobs not spawning

### ISSUE THREAD

**Issue by Buzhak** [WarEmu/WarBugs#18667] opened 2021-03-16 22:57 UTC
Quest "Will of the Warboss" is broken.
Mob "Moonfang Stickointa" is not spawning.
These mobs spawn to the public quest: "Revoltin' Gobbos"

**Comment by Lheana** [comment] 2021-03-18 19:38
Duplicate of #18666

**Closed by Lheana** 2021-03-18 19:38 UTC
