### ISSUE TITLE
[BW]Wildfire and Choking Smoke

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#11513] opened 2018-03-26 11:31 UTC
Currently it doesn't proc Wildfire dot and probably should.
I'm ok with Wildfire tactic not procing from dot spells in Conflag tree, but Choking Smoke is a targeted aoe spell with silence component.

**Comment by sioding** [comment] 2018-03-26 11:43
Duplicate of #1940

**Closed by sioding** 2018-03-26 11:43 UTC
