### ISSUE TITLE
Buffs underlying portrait staying up forever or not showing up

### ISSUE THREAD

**Issue by Hideyokidz** [WarEmu/WarBugs#13550] opened 2019-03-05 09:13 UTC
On all of my characters certain buffs indicators will stay on under your character portrait and sometimes they will duplicate or not show up entirely, can be super frustrating checking in stats to see if you have your buff or not.

**Comment by sioding** [comment] 2019-03-05 09:24
Duplicate of #12570

**Closed by sioding** 2019-03-05 09:24 UTC
