### ISSUE TITLE
Battle brew backpack isn't bop/boe unable to transmog

### ISSUE THREAD

**Issue by TheOctagon322** [WarEmu/WarBugs#18959] opened 2021-05-07 23:00 UTC
**Expected behavior and actual behavior:**
Actual behaviour: Unable to use battle brew backpack as appearance since it's not bop/boe.

Expected: Should be bop/boe so one can use it as an appearance item.

**Steps to reproduce the problem:**
Make it bop/boe like it used to be I think it's a bug.

**Testing Screenshots/Videos/Evidences (always needed):**
![Grossman_001](https://user-images.githubusercontent.com/64733933/117516211-2cbb4d00-afa1-11eb-9281-317d207b05ff.jpg)

**Comment by Rydiak** [comment] 2021-05-08 00:07
Interesting.  My BBBP is BoP.  I wonder why yours isn't.

**Comment by Lheana** [comment] 2021-05-13 15:15
Duplicate of #12491

**Closed by Lheana** 2021-05-13 15:15 UTC
