### ISSUE TITLE
issue with the quest "Get Dat Stunty Tunnel!" unable to complete

### ISSUE THREAD

**Issue by LeonardoFurci** [WarEmu/WarBugs#19141] opened 2021-06-13 15:58 UTC
**Expected behavior and actual behavior:**
AS the title says, the quest "Get Dat Stunty Tunnel!" in Kadrin Valley, in which you have to scout Ice Hearth Crossing, cannot be completed when you get to the objective. I tried with 3 different characters, both when the zone is active for RvR or locked, and all different levels (at the flag, below, and all levels above, even in PvE area --> check screenshot)

**Steps to reproduce the problem:**
- Fly to Kadrin Valley
- Take the quest from the NPC Krung de Mada
- Go to Ice Hearth Crossing (any level of it)
- Quest fails to update and cannot be completed

**Testing Screenshots/Videos/Evidences (always needed):**

![RoR quest bug](https://user-images.githubusercontent.com/73412085/121814345-805d3c80-ccab-11eb-938a-9d0f59196ac3.png)

**Comment by xpander69** [comment] 2021-06-13 16:04
Does it work when the zone is not locked? might be issue with the zone not active

**Comment by Lheana** [comment] 2021-06-13 16:41
Duplicate of #18591

**Closed by Lheana** 2021-06-13 16:41 UTC
Labels: 2 Week Ultimatum, Confirmation Request, Map/Area, Quests
