### ISSUE TITLE
Automatic Guild leader transferral after Inactivity for more than 1 month (Not Working)

### ISSUE THREAD

**Issue by Bendogss** [WarEmu/WarBugs#17031] opened 2020-06-05 13:09 UTC
**Expected behavior and actual behavior:**
Automatic Guild leader transferral after Inactivity for more than 1 month (Not Working)

After 1 month + server restart, the automated system should swap guild leader to next active player suggested by Wargrim doesn't seem to be working. He told me to report it.

**Steps to reproduce the problem:**
Spoke to GM's and Dev's on the discord that told me to log it as a bug.

**Testing Screenshots/Videos/Evidences (always needed):**
![guild leader automated system](https://user-images.githubusercontent.com/66476923/83879526-1bf6cb80-a781-11ea-89eb-53d3e8dd1140.PNG)

See the dates below for leader and recent players to the top.

**Comment by wargrimnir** [comment] 2020-06-14 21:14
Fairly certain this is indeed bugged. Another example.
![image](https://user-images.githubusercontent.com/12942408/84604230-76b7b380-ae62-11ea-89f4-f50e76bbf553.png)

**Comment by jundii** [comment] 2021-02-10 22:29
**I also have this issue.... However I have more to add that might make this different.**

Expected behavior and actual behavior: _Expected to become guild leader, actual events do not follow expectation._

![Discvader_000](https://user-images.githubusercontent.com/35981863/107580231-41678f00-6bc4-11eb-8fdf-b0275e1aac66.jpg)

My twist on this same issue is when I log into my character his guild information is bugged. Where you would expect to see other members listed... he is ALWAYS by himself until I reloadui... (only then do the other members show up)
![Discvader_001](https://user-images.githubusercontent.com/35981863/107580706-f5691a00-6bc4-11eb-9120-d65d52a43ff3.jpg)
(Mrdj = Discvader, recent name change... problem existed both before and after name change)

**Comment by mirosat** [comment] 2021-10-06 22:27
I have same issue, GM Uwellcrownsh hasn't logged on since 8/29 

![image](https://user-images.githubusercontent.com/92052368/136292206-b8cbfdaf-db25-4321-aa66-b9f1cfa9d337.png)

It's just me and 2 more people active, my character name is Perditia.

**Comment by MaxHayman** [comment] 2022-04-04 22:58
This should be fixed

**Closed by MaxHayman** 2022-04-04 22:58 UTC
Labels: Guilds
