### ISSUE TITLE
Dark Elf Ch 11 Heart of the Wild quest - exception thrown - can't complete

### ISSUE THREAD

**Issue by Akenatoth** [WarEmu/WarBugs#11279] opened 2018-02-10 04:05 UTC
### Expected behavior and actual behavior:

**Expected behavior:** Take the quest from Syth Orealian in Dark Elf ch 11 camp.  Go to the marked area around 31k 39k and kill 4 Wrathborn Branchwraiths. After that move to the Pool of Elthrai to offer a sacrifice (I guess it's an item to click).

**Actual behavior:** When trying to kill the Wrathborn Branchwraiths, they disappear and a bubble comes up with the following exception: [Wrathborn Branchwraith] says: InvalidCastException was thrown from HealTarget. This object will be destroyed. 
This happen whether I pull by taunt or proximity and whether I hit the target or not. My healing target doesn't make a difference (tried to target myself or nothing). In the same area, the Wrathborn terrors (spites) behave normally, while Wrathborn Dryad (not just Branchwraiths) have the same problem.
It seems to be related to the ability rotation of those Dryads/Branchwraiths (maybe they boost themselves with some ability but with wrong target).
See the pictures attached where I pull a group with a Branchwraith, a Dryad and a Terror (pic 2).
The Branchwraith and the Dryad disappear throwing an exception, the Terror behaves normally.

This makes it impossible to kill the needed NPCs and to progress with the quest.

### Steps to reproduce the problem:

Pick up the quest as indicated in the expected behavior and try to kill Wrathborn Branchwraiths.

Screenshots/Videos or archive.org evidences:

![thalet_001](https://user-images.githubusercontent.com/35481383/36058411-a6b4cf90-0e1f-11e8-92af-c90d6cced704.jpg)
![thalet_000](https://user-images.githubusercontent.com/35481383/36058412-ac789d9e-0e1f-11e8-9cfe-07ab356353ce.jpg)
![thalet_002](https://user-images.githubusercontent.com/35481383/36058417-b20d9d18-0e1f-11e8-83f1-6f4b586ece42.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Akenatoth** [comment] 2018-02-10 04:07
I want to add that earlier this year I completed this quest without any problems on my DOK, so this problem is probably related to some recent changes.

**Comment by sioding** [comment] 2018-02-10 07:29
Duplicate of #11282

**Closed by sioding** 2018-02-10 07:29 UTC
