### ISSUE TITLE
Alternate appearance T4 epic quests items

### ISSUE THREAD

**Issue by Disturbedst** [WarEmu/WarBugs#5984] opened 2016-05-14 11:53 UTC
Hello,
first time reporting soo im sorry for any mistakes. Some T4 epic quest weapons have alternate appearance available and some dont for instance Chaos shield Goreblock has it but Menace and Dementia don't. 
![goreblock](https://cloud.githubusercontent.com/assets/19360409/15268300/5d418c08-19da-11e6-8041-c7fe128065c3.PNG)
![menace](https://cloud.githubusercontent.com/assets/19360409/15268301/68186b9c-19da-11e6-8115-963e70c868ad.PNG)
![dementia](https://cloud.githubusercontent.com/assets/19360409/15268302/6f9c2840-19da-11e6-857b-4ac7345a9466.PNG)

Blackguard shields all have them:
![darkelf](https://cloud.githubusercontent.com/assets/19360409/15268303/861ce5e6-19da-11e6-9b27-1ecadd898be9.PNG)

KoTB shields all have them:
![kotb](https://cloud.githubusercontent.com/assets/19360409/15268314/d1f50ade-19da-11e6-9751-cc0458fad673.PNG)

Some other items ive found thanks to user Github and others in advice chat:
![1](https://cloud.githubusercontent.com/assets/19360409/15268333/2af05530-19db-11e6-984e-5de9cacee0a9.PNG)

**Comment by Ryanfawkez** [comment] 2016-05-14 12:30
As long as items are Bind on Pickup. they can be used for appearance regardless of their 'alternate appearance available' tooltip.

**Comment by Disturbedst** [comment] 2016-05-14 12:54
Dementia for some reason isn't Bind on Pickup as stated in the screenshot.

**Comment by Ryanfawkez** [comment] 2016-05-14 13:10
Fixed in next patch.

**Comment by Disturbedst** [comment] 2016-05-14 13:16
Thank you very much!

**Comment by Sersaypygan** [comment] 2016-05-14 13:21
I can confirm this is a problem. Witch elf daggers have this issue because they are designated as main hand daggers only, and not main or offhand. Due to other daggers being main OR offhand daggers, they are not considered the same type of weapon, and alternate appearance is not allowed.

**Comment by Torquemadra** [comment] 2016-05-14 14:30
That is not a bug, its a restriction of the appearance system, for DW weapons without the appearance message simply drag and drop into the slot as opposed to waiting for the message prompt. Please do not hijack specific threads with additional "issues".

**Closed** 2016-05-15 07:09 UTC
Labels: Database, Fix Pending, Item, Visual
