### ISSUE TITLE
can't redeploy ram

### ISSUE THREAD

**Issue by Zuyanna** [WarEmu/WarBugs#6244] opened 2016-05-20 15:06 UTC
![zuyanna_026](https://cloud.githubusercontent.com/assets/19364515/15431969/40b06c22-1e7a-11e6-9b5d-03204908de5f.jpg)

I've been told this is a known issue, but can't find it on the bugtracker, so sorry if it's a repeat post. 
the ram died a few times, then wouldn't let me redeploy after 3+ minutes, not from a lack of trying
I was the only person in the warband as far as I know trying to deploy, so I wasn't thwarted by one already being there, and I did try different positions generally around where the first ram allowed me to spawn it

**Comment by Soulwhisper** [comment] 2016-05-20 15:11
#6006 
- And adding that trying to deploy 2nd ram after the first one is destroyed it gives a message : Door is blocked by another ram

**Comment by Evildoor** [comment] 2016-05-20 17:04
#6002 and #6006 are currently about rams dealing no damage. This is about redeploying.

**Comment by Soulwhisper** [comment] 2016-05-20 17:26
/t4: the rams _should_ be redeployable, but they have a 3minute cooldown once they got destroyed
I guess this is not a bug...you have to wait 3 minutes.

**Comment by noisestorm** [comment] 2016-05-20 20:50
Was the ram properly destroyed, or was it another Exception (i see one in the log, but after they tried to place a new ram)? Being precise on what happened to the ram can help resolving the issue

**Comment by Zuyanna** [comment] 2016-05-23 15:48
i didn't try it at other keeps. i'm aware rams take time until you can redeploy, that's why I included time stamps on my log.  I don't know if the ram was properly destroyed, it was killed by oil before the last patch, today the ram seemed to live through oil fine, but i'm unsure if the problem of not being able to redeploy is still an issue.

**Comment by sioding** [comment] 2017-10-15 15:38
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Closed** 2017-10-24 09:44 UTC
Labels: ORvR
