### ISSUE TITLE
BackPack Overflow

### ISSUE THREAD

**Issue by Dragon586** [WarEmu/WarBugs#12256] opened 2018-09-02 13:00 UTC
Update (Edit)
This is duplicate of Issues 11937 and 12060
----

I.- Expected behavior and actual behavior:

-Executed magic salvage when crafting backpack was likely full, while main back pack had at least one free slot.
- After execution got an "overflow" warning/label below backpack.
-Also, got a "Full" label below the backpack icon located at the top of the window.
-Both labels are persitent, even after the following actions were further executed:  
---Getting free slots in both main backpack and crafting backpack (by selling dumping etc)
---Login out and relogin the toon
---Quit and Restarting ROR 

On previous executions of magic salvage (with crafting backpack full) the product of salvage was being stored on main backpack as expected.

-Issue was oberved seconds before 05:13 GMT-5 (Lima time)

--------

II.- Steps to reproduce the problem:

I expect the bug can be reproduced by getting crafting backpack full and executing magic salvage.
The product of salvage would trigger the overflow instead of being stored in main backpack

Yet, I had not tried to reproduce it with another character.

--------

III.- Screenshots/Videos or archive.org evidences:

Attached 3 screenshots with details. 

-First screenshot was taken some seconds after the issue appeared.
It shows the "overflow" label below backpack and the "Full" label below the icon.

![zadionne_000e](https://user-images.githubusercontent.com/41530703/44955927-2f288900-ae81-11e8-93a1-b3891b9a46d9.jpg)

-Second screenshot was also taken some seconds after the issue appeared.
It shows the text message that name the crafting material created by magic salvage 
(the one linked to overflow)

![zadionne_001e](https://user-images.githubusercontent.com/41530703/44955929-364f9700-ae81-11e8-9f72-ab880b847c22.jpg)

-Third screenshot was taken several minutes later, after trying the actions detailed above ( making free space in backpack, login out, restarting RoR)

As it can be observed in the screenshot, the "overflow" label is persistent and the backpack icon at the top is still labeled as "full" even when backpack now has many free slots. 

![zadionne_004e](https://user-images.githubusercontent.com/41530703/44955934-51baa200-ae81-11e8-8b4f-468f03b69486.jpg)

Regards

**Comment by Dragon586** [comment] 2018-09-02 13:47
Just in case :)

![search_overflow](https://user-images.githubusercontent.com/41530703/44956638-bfb89680-ae8c-11e8-83ef-dd639bebaf82.jpg)

**Comment by sioding** [comment] 2018-09-03 06:59
Duplicate of #11937

**Closed by sioding** 2018-09-03 06:59 UTC
