### ISSUE TITLE
Subjugator Cloak

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11679] opened 2018-04-26 17:10 UTC
Subjugator Cloak can be used directly from inventory (it isn't required to wear it) making it a bit worse version of CW

sorry for stretched resolution :D changed videocard and stuff happened
https://www.youtube.com/watch?v=ZKLdSjAHp_c

as a side note, and not seen on video, cooldown on subjugator cloak gets reset after using flight master (similair to the already reported case of porting items such as scroll of altdorf or keg)

**Comment by sioding** [comment] 2018-04-26 18:41
Duplicate of #10382

**Closed by sioding** 2018-04-26 18:41 UTC
Labels: Ability, Item
