### ISSUE TITLE
the 4th set bonus of annihilator

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#10295] opened 2017-08-28 15:20 UTC
the extra skill point of the 4th set bonus of annihilator resets when moving a set unrelated item such as a pocket item.

**Comment by Titoos** [comment] 2017-10-25 07:39
Duplicate of #7024

**Comment by sioding** [comment] 2017-10-25 08:38
Thanks @Titoos #7024

**Closed by sioding** 2017-10-25 08:38 UTC
