### ISSUE TITLE
Bl Quest Khorgash and the mobs

### ISSUE THREAD

**Issue by Bafilan** [WarEmu/WarBugs#13208] opened 2019-01-27 12:19 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

 We went on the Order side to the Beast Lord in a group. And hit mobs + the Boss. Then the all Monsters disapeared. My Name on the Side is : Bafilan and the class is Slayer. Unfortunately i forgot to make a screenshot. I hope u can help

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2019-01-27 12:21
Duplicate of #13206

**Closed by sioding** 2019-01-27 12:21 UTC
