### ISSUE TITLE
.gestats don't show disrupt/parry/dodge

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11603] opened 2018-04-14 11:34 UTC
.gestats don't show disrupt/parry/dodge

![thorbolt_179](https://user-images.githubusercontent.com/16274785/38767806-a50b466a-3fe8-11e8-8c5d-155ffdc6c1e1.jpg)

I got a turret x8 give 32% disrupt and dodge with no renow points and naked

They should be in .getstats :

Parry 32% + 4.1 = 36.1
Dodge 32% + 7.5 = 39.5
Disrupt 32% +4.7 = 36.7

.getstats only show 32%

**Comment by sioding** [comment] 2018-04-15 16:13
Duplicate of #11604

**Closed by sioding** 2018-04-15 16:13 UTC
Labels: Source Code
