### ISSUE TITLE
[fortress gold  bag] incorrect reward

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#14576] opened 2019-07-14 08:18 UTC
recived on "my chosen "tesq" a gold bag from "fell landing" fortress of 13/07/2019; 15:05:02 UTC

but inside there was a vanquisher piece and vanquisher currency instead  invader....

best course of action is check logs and see what gone wrong so that it wont repeat.

**Comment by sioding** [comment] 2019-07-14 08:47
No its not from fell landing - its from the the zone before. once a fort is reached _every_ bag come from the fort zone. Known issue - low prio to fix

**Comment by sioding** [comment] 2019-07-14 08:48
Duplicate of #13844

**Closed by sioding** 2019-07-14 08:48 UTC
Labels: Sourcecode

**Comment by Tesq** [comment] 2019-07-14 14:25
it's impossible it was the previusly zone, i won another bag in cale this came today after yest fortress crash.

**Comment by gittoaster** [comment] 2020-01-04 22:21
Happened today.  Bag from Caledor keep gives Fell Landing bag.  
![keepbag](https://user-images.githubusercontent.com/7898608/71772270-88814c00-2efd-11ea-92d5-766cb8ffae0c.jpg)
