### ISSUE TITLE
[Quest] An Eye for Trouble (Caledor, destro) NPC offering two quests with the same name at the same time

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13049] opened 2019-01-04 19:19 UTC
The NPC "Axais Dwelrath" is offering two quests with the same name at the same time. Identical names usually are usually used in chained quests.

![quillog_002](https://user-images.githubusercontent.com/30193675/50706363-e286d180-105d-11e9-819c-a683727f6ab8.jpg)

Note: One of the quests is available after another NPC in the warcamp sends you to Axais.

**Comment by Kabucoror** [comment] 2019-01-04 19:58
is fixed with #12993 and #12992

**Comment by Kabucoror** [comment] 2019-01-04 20:02
Duplicate of #12993

**Closed** 2019-01-04 20:36 UTC
Labels: Database, Fix Pending, Quests
