### ISSUE TITLE
Ere We Go! - Buff stacks and allows instand Kills !

### ISSUE THREAD

**Issue by ranzinus** [WarEmu/WarBugs#18997] opened 2021-05-16 10:55 UTC
**Expected behavior and actual behavior:**

The Path of Da Green Core ability:

"Ere We Go!" can be combined with the Tactic "Ere We Goes Again" out of the Path of Gork Three and does additional 150 elemental damage +  for all attacks groupmembers deal for their next two attacks.

For a party of 6 - this is about 300*6=1800dmg for 1 shamen (simplyfied: without mitigation or resis or anyting).

The Problem: The buff is stackable!

If we add 4 Shamens to the group it Stacks.This Buff-Damage goes out of line, as its an instant kill by  4 Shamens

Par example:
1800 per shamen  x 4 = 7200 dmg with just 1 buff per char. without any other actions taken!

**Steps to reproduce the problem:**

Ere we go should not Stack with other Ere we go Buffs inside the Same Group.

**Testing Screenshots/Videos/Evidences (always needed):**

![ere we go](https://user-images.githubusercontent.com/73936724/118394578-c63fca00-b645-11eb-9a30-2b19ccdba73c.png)

**Comment by bloodmasked** [comment] 2021-05-17 07:33
Being attacked by the same ability 4 times is not a bug

**Comment by Delegator2** [comment] 2021-05-17 22:25
As much of a bug as multiple stacks of broadhead arrow from multiple SWs...

**Comment by ranzinus** [comment] 2021-05-20 17:57
Thanks for the Fix in the latest patch :)

**Comment by xpander69** [comment] 2021-05-27 10:27
fixed, closing

**Closed by xpander69** 2021-05-27 10:27 UTC
