### ISSUE TITLE
Not able to use the Guild Standard

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#13415] opened 2019-02-20 08:30 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: 
I'm the Leader of my guild and when I try to use the guild Warped Battle Standard I'm told ( You are not in a Guild ) When I am the Guild Leader 

![yogibear_001](https://user-images.githubusercontent.com/47046345/53077374-d5b02700-34bf-11e9-9dc4-43a3e50ee3c7.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2019-02-20 12:23
Duplicate of #13289

**Closed by sioding** 2019-02-20 12:23 UTC
