### ISSUE TITLE
T-2 Shadow Lands RVR- Destro Gold Bag Issue

### ISSUE THREAD

**Issue by CoReWolf** [WarEmu/WarBugs#12771] opened 2018-11-30 15:53 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I got a gold loot bag from The Shadow Lands T-2 RvR.  I opened the bag and got White Lions Glove Oblitorator Wristguards 
I was expecting DoK Gear?

Steps to reproduce the problem: Win a Gold Bag at The Shadow Lands during a T-2 RvR.

Screenshots/Videos or archive.org evidences:

![exercist_001](https://user-images.githubusercontent.com/43544564/49299475-71b03080-f485-11e8-8289-2a84d16e6ebc.jpg)

**Comment by sioding** [comment] 2018-11-30 17:20
Duplicate of #11739

**Closed by sioding** 2018-11-30 17:20 UTC
