### ISSUE TITLE
Guild Heraldry Still Incorrect

### ISSUE THREAD

**Issue by Geizty** [WarEmu/WarBugs#11318] opened 2018-02-17 19:56 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

There are a ton of these but I do not see resolutions to it and they reference other bugs.

Expected behavior and actual behavior:  Originally for my guild, I chose a heraldry but this was back when there were the database issue where it kicked out half the guild.  When we got to guild level 15 it never changed to what I set it.  I bit the bullet and did the 100g to change the heraldry but it never changed, even after log out.

Steps to reproduce the problem:  Click on reserve heraldry to redo it, set it to what you want and click save, hit ok to the amount and do it again the exact same way within 30 seconds and hit ok on the money.  It took the 100g and my heraldry did not change at all.

Guild is on Order - Malleus Maleficarum, leader Geizt

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-02-17 20:19
Duplicate of #10417

**Closed by sioding** 2018-02-17 20:19 UTC
