### ISSUE TITLE
Quest in Nordland: A Stickey Situation

### ISSUE THREAD

**Issue by SpiceyTim** [WarEmu/WarBugs#11326] opened 2018-02-18 15:45 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.* - searched for this quest name or npc name, no results

Expected behavior and actual behavior:

Upon freeing NPC Gavin Scherer from a cocoon he should run out of the webworks or register as being freed as for the quest A Sticky Situation. However the NPC becomes stuck in a rock.

Steps to reproduce the problem:

Adjust spawn location to a few meters forward? or update quest when he is freed

Screenshots/Videos or archive.org evidences:

Screenshot from immediately after being freed from cocoon

![28207780_10213706781736861_1742564960_o](https://user-images.githubusercontent.com/36602493/36353800-a2f90f70-14c2-11e8-874c-0c2843e2021f.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-02-18 17:45
Duplicate of #11301

**Closed by sioding** 2018-02-18 17:45 UTC
