### ISSUE TITLE
Melee Squig attacked by Horned Squig after using Outa My Way

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#12347] opened 2018-09-20 17:32 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

If one is in Squig Armor, has a horned squig active and uses "Outa My Way", after the ability has run its course, the horned squig will begin to attack the SH.   I know early on, after the melee squig rework, there were instance of horned squig attacks against their masters, but I think it was addressed.  I don't know if those instances were in any way tied to using Outa My Way. 

Steps to reproduce the problem:

If the horned squig is dismissed and resummoned, the hostile behavior from the horned squig ends.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-09-20 17:39
Duplicate of #12216

**Closed by sioding** 2018-09-20 17:39 UTC
