### ISSUE TITLE
[Jewel] Exquisite Gunbad Ruby STR Value

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20360] opened 2022-08-20 09:16 UTC
Hello RoR Team,
Exquisite Gunbad Ruby (Purple STR  jewel) gives 15str instead of 30str. Please see pictures below. Thanks

**Testing Screenshots/Videos/Evidences (always needed):**
STR Value without jewel (str: 1072)
![Sirzero_115](https://user-images.githubusercontent.com/45720515/185738455-4c3aac9c-b45b-4349-ac59-85bfa7835d9a.jpg)

STR Value with jewel (str: 1087)
![Sirzero_117](https://user-images.githubusercontent.com/45720515/185738459-2762a9d5-2187-4e2d-bbef-2d078e22be3e.jpg)

**Comment by Undrsiege** [comment] 2022-08-20 10:30
This is not a bug.  Once you go beyond 1050 STR the value is only worth 50% value.

**Comment by xpander69** [comment] 2022-08-20 11:38
yeah, after softcap you just get 50%. closing, not a bug

**Closed by xpander69** 2022-08-20 11:38 UTC
