### ISSUE TITLE
Banner Bug (cant pickup and perma stats bonus)

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#18754] opened 2021-04-02 18:08 UTC
**Expected behavior and actual behavior:**
After you plant your own banner you should be able to pick it up - owner of banner cannot pick it up.
After Banner is gone, bonus stats should disappear - stats persist after planting banner, when u move away from it (
getstats shows bonus stats).

**Steps to reproduce the problem:**
Plant banner and try to pick it up.
Use banner to get bonus stats.

**Testing Screenshots/Videos/Evidences (always needed):**

cant pick up:
https://clips.twitch.tv/WealthyFancyGaurAMPEnergy-ZqKLLORODqXuKd-n1

perma stats:
https://clips.twitch.tv/FurtiveLuckyDumplingsFailFish-YcVcH7ESGC5Xdk-g

replicated bug:
https://clips.twitch.tv/PunchyTalentedHerbsCharlieBitMe-rzhrEsEJGLP7Mtzy

also, after someone picking up banner, banner return on mail as 2 pieces:
https://clips.twitch.tv/RudeSullenShrimpPrimeMe-9JU_-DO1jPf6HZav

**Comment by Lheana** [comment] 2021-04-03 10:14
Duplicate of #18745

**Closed by Lheana** 2021-04-03 10:14 UTC
