### ISSUE TITLE
Pig vs flag

### ISSUE THREAD

**Issue by NabaroNya** [WarEmu/WarBugs#11051] opened 2017-12-24 18:55 UTC
U can run with flag in pig form. So u take move speed buff. Maybe pig need to be with mount buff.

![chaklunka_047](https://user-images.githubusercontent.com/32055507/34328650-51fc8d32-e8ed-11e7-8b1d-0a02e54c5767.jpg)

**Comment by sioding** [comment] 2017-12-25 22:15
Duplicate of #11058

**Closed by sioding** 2017-12-25 22:15 UTC
Labels: Ability, Scenarios
