### ISSUE TITLE
Apothacary bugged??

### ISSUE THREAD

**Issue by devo9** [WarEmu/WarBugs#11183] opened 2018-01-21 17:22 UTC
i have leveled apothecary from scratch, currently on 55, all of my pots have failed, using lvl 1 vials and now 50, 1-25-50 main ingredients and resin, still all failing

Expected behavior and actual behavior:
shold be giving me 1-25-50 potiosn but nothing but junk

Steps to reproduce the problem:

lvl 1  vial, 1 main ing, 1 resin, using X1 X2 X3, or lvl 1 vial 25 main, 1X 2X 3X resin and same for 50 mats with a 50 vial

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by devo9** [comment] 2018-01-21 17:40
Update, it only seems to be the 25 and 50 str main ingr,

**Comment by sioding** [comment] 2018-01-21 18:05
Duplicate of #10660

**Closed by sioding** 2018-01-21 18:05 UTC
