### ISSUE TITLE
[KOTBS] Stay Focused proc while not being active.

### ISSUE THREAD

**Issue by Upem** [WarEmu/WarBugs#14043] opened 2019-05-08 04:39 UTC
**Expected behavior and actual behavior:**
With All Out Assault, On Your Guard, Stand Strong activated I only expect to have those buffs. But I am getting Stay Focused procs and it is indeed healing me and giving me AP.

Last night my friend (slayer) and I were doing PvE and I noticed he had Stay Focused buff under his name while very far out of my range. Then I also realized I was getting Stay Focused procs as well. (Buff doesnt actually show up for me but the proc does: see image below)

**Steps to reproduce the problem:**
Activate All Out Assault, On Your Guard, Stand Strong, and let a mob attack you. 

I thought it maybe Focused Mending tactic causing bug but I removed all tactics and still got the Stay Focused procs. Also, I havent used Stay Focused in this session or any today.

**Screenshots/Videos or archive.org evidences:**
https://i.imgur.com/e9mbL8S.jpg

After playing a bit the actual buff icon is now showing for my character.
https://i.imgur.com/MwUg7lL.png
https://i.imgur.com/jbQd7sf.jpg

**Comment by Upem** [comment] 2019-05-08 04:44
Also a note: I have Focused Mending equipped in the picture but this bug happens with no tactics equipped as well.

**Comment by sioding** [comment] 2019-05-08 17:42
Duplicate of #13368

**Closed by sioding** 2019-05-08 17:42 UTC
