### ISSUE TITLE
Quest "Armor of the Ancestors"

### ISSUE THREAD

**Issue by warwalker** [WarEmu/WarBugs#11052] opened 2017-12-24 19:33 UTC
There is a problem with the "piles of rubble" gameobjects in this quest "armor of the Ancestors" out of Lorkinson's Excavation (Dwarf chpt 17) from Durlin Kanstone NPC in Thunder Mountain. There are what look like piles of rubble at coords 15K/12.9K and 1.4K/14.5K that I believe were the GO's to click on in the original game. They do not mouseover to function now. 

Expected behavior and actual behavior:
mouseover "hand" and click function to complete objective expected .... no function at all.

Thank you and many thanks for all the work ... very nice for my wife and I to enjoy the game again.

**Comment by sioding** [comment] 2017-12-24 19:58
Thanks for the report but please use the search fuction before creating a new one.

Duplicate of #10462

**Closed by sioding** 2017-12-24 19:58 UTC
