### ISSUE TITLE
RVR Bolster 

### ISSUE THREAD

**Issue by Ramsie33** [WarEmu/WarBugs#18991] opened 2021-05-15 22:31 UTC
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by HokoBugTracker** [comment] 2021-05-16 18:08
Expected behavior and actual behavior: 

RvR bolster for sub 40 characters should turn on when entering the rvr lake. At the moment it's turning on and off in the whole rvr lake (i think only in tier 2 and tier 3 rvr lakes), it randomly (?) turns off and back on in different areas of the rvr lake (i think it triggers when you're close to battlefield objectives). That causes some massive loading lags for sub 40 characters and makes rvr in the lakes nearly unplayable!

Steps to reproduce the problem:

I've tested it on many different characters sub 40 and i think it's even worse with 30-40 characters. The bolster turns on and off randomly in rvr lakes. It also triggers when entering a keep. 

Testing Screenshots/Videos/Evidences (always needed):

Test with a 37 Swordmaster in Troll Country rvr lake:
[https://youtu.be/jbgRRnRyvJA](url)

[https://ibb.co/9hc2GVv](url)

**Comment by L0hki** [comment] 2021-05-18 07:19
It's already reported here https://github.com/WarEmu/WarBugs/issues/18988

**Comment by xpander69** [comment] 2021-05-27 10:30
duplicate of: https://github.com/WarEmu/WarBugs/issues/18988

**Closed by xpander69** 2021-05-27 10:30 UTC
