### ISSUE TITLE
Experience earned in sc isn't equal to the amount showed in the xp section of the scenario summary

### ISSUE THREAD

**Issue by sniperseal** [WarEmu/WarBugs#12823] opened 2018-12-08 11:47 UTC
The screenshot show the scenario summary and the combat lot showing the real xp gained after the sc, The difference between the two amount is high.
the scenario was logrin's forge and i was solo queued.
![cocaine_002](https://user-images.githubusercontent.com/19274122/49685639-3b0e9180-fae7-11e8-93c7-e98623fdbbe8.jpg)

**Comment by sioding** [comment] 2018-12-08 16:56
Duplicate of #12677

**Closed by sioding** 2018-12-08 16:56 UTC
