### ISSUE TITLE
Rimewing Eagle NPC

### ISSUE THREAD

**Issue by YourArchRival** [WarEmu/WarBugs#13558] opened 2019-03-06 01:17 UTC
While in Chrace near Lyriana's Mansion, a Rimewing Eagle NPC that you cannot target, one shot both my teammate and myself. 

Attached are the combat log and the map of the area where it was found. 

![img_20190305_200629408](https://user-images.githubusercontent.com/48265788/53848760-984d9e00-3f83-11e9-813c-51f8228f9603.jpg)
![img_20190305_200923507](https://user-images.githubusercontent.com/48265788/53848761-98e63480-3f83-11e9-9499-e96368f437bd.jpg)

**Comment by sioding** [comment] 2019-03-06 08:21
Duplicate of #13557

**Closed by sioding** 2019-03-06 08:21 UTC
