### ISSUE TITLE
Rvr bag yields the wrong rewards

### ISSUE THREAD

**Issue by Marawo** [WarEmu/WarBugs#11773] opened 2018-05-17 09:51 UTC
After losing BFP&BL map I recieved a Gold bag.
Normally I would get a piece of Obliterator armor appropriate for my rank and class.
I did indeed get an Obliterator piece but for the Black Orc class. (I am an IB)

![bombil_002](https://user-images.githubusercontent.com/29643742/40170325-6bc2118c-59c8-11e8-8ba6-40c0185bb1b1.jpg)

(I don't want or need any refund I took the alternative reward of 5 scout's medallions)

edit: mixed up the words emblems and medallions

**Comment by sioding** [comment] 2018-05-17 10:50
Duplicate of #11739

**Closed by sioding** 2018-05-17 10:50 UTC
