### ISSUE TITLE
[Quest][Dwarf Chap 21] The Grudges of Karak Drazh - enemy NPC missing

### ISSUE THREAD

**Issue by gamerlenny** [WarEmu/WarBugs#18462] opened 2021-02-06 19:03 UTC
Quest The Grudges of Karak Drazh is a quest chain in Dwarf chapter 21 in Black Crag. In one of the last parts of the quest you're supposed to kill a character named Prung the Squig King.
He is supposed to be near Redfang's squig stomping grounds in B.C. but he is nowhere to be found in the area marked on the map. 
The area marked on the map is correct since all the squigs around there are all called "Prung's [something]".

**Expected behavior and actual behavior:**
Prung should be in the area shown on the map (squig pens around 47500, 58000 in Black Crag), but he is not there and I couldn't find him anywhere.

**Testing Screenshots/Videos/Evidences (always needed):**
![Acey_010](https://user-images.githubusercontent.com/2891053/107127279-6652be00-68b5-11eb-8e89-ebfb836aa383.jpg)

![Acey_009](https://user-images.githubusercontent.com/2891053/107127309-94380280-68b5-11eb-8bea-7089bd375582.jpg)

**Comment by gamerlenny** [comment] 2021-06-04 18:39
UPDATE: found him! He is currently standing at the top of the ruined tower to the right of the squig pens! However, he is very hard to see and almost unreachable from the ground, I had to go to the area with a Destro character and enter the nearby greenskin camp to be able to view the area from above, and finally spotted him. I'm not sure he's supposed to stand there above the roof of the tower, I think originally he was supposed to be inside that tower or next to it... 
Might be related to issue #16938 (NPCs get pulled to unexpected locations when aggroing players)?

**Comment by Lheana** [comment] 2021-06-04 18:41
Thanks for the update.
Duplicate of #16938

**Closed by Lheana** 2021-06-04 18:41 UTC
Labels: Database, NPC, Quests
