### ISSUE TITLE
Goblin Green Dye

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8929] opened 2017-01-16 15:17 UTC
- Exact same Dye but cant stack them. No diferrence. I think first one with level requirment should be removed. There are some more with the exact same problem. Looking forward to hear ya @Luth-RoR 
![warhammer online age of reckoning 01 16 2017 - 17 16 20 02](https://cloud.githubusercontent.com/assets/16864486/21988380/beaac2e6-dc0f-11e6-9106-8e87bbdc6a42.png)
![warhammer online age of reckoning 01 16 2017 - 17 16 22 03](https://cloud.githubusercontent.com/assets/16864486/21988379/beaa0630-dc0f-11e6-8506-5b27ea13e208.png)

**Comment by Luth-RoR** [comment] 2017-01-16 16:15
Probably different item IDs.

**Comment by Ryanfawkez** [comment] 2017-01-18 18:04
Lovely. Three different items, all with the same appearance, rarity and effect. Will need to determine which can be purged.

**Comment by sioding** [comment] 2018-04-23 10:42
Duplicate of #4890
thanks @szejoza

**Closed by sioding** 2018-04-23 10:42 UTC
Labels: Database, Item
