### ISSUE TITLE
[WL] pet pulling through gate

### ISSUE THREAD

**Issue by Skoupie** [WarEmu/WarBugs#11025] opened 2017-12-18 22:35 UTC
In Highpass scenario, white lion pet can pull through the side of the wall at the stag BO (probably the same can occur on the other side of the map too but didn't test it).

**Comment by Torquemadra** [comment] 2017-12-18 23:28
you can shoot through you can pull through, both sides, nothing that will be getting fixed any time soon

**Comment by sioding** [comment] 2017-12-19 08:22
Duplicate of #10889

**Closed by sioding** 2017-12-19 08:22 UTC
