### ISSUE TITLE
Gunbad: AM Funnel Essence doesnt work

### ISSUE THREAD

**Issue by Latemoon83** [WarEmu/WarBugs#13673] opened 2019-03-18 11:13 UTC
Dear Supporter,

the AM Funnel Essence do not working in Gunbad. Its possible to activate it, the cast bar is also working but the selected partymember dont get any heals. I speak with guildees... the same problem.
Pleace check that.

Sincerly yours

Late

**Comment by Lefze** [comment] 2019-03-18 13:51
Because you/target aren't pvp flagged. Same goes for certain other channels.

**Comment by sioding** [comment] 2019-03-18 14:00
Duplicate of #11846

**Closed by sioding** 2019-03-18 14:00 UTC
