### ISSUE TITLE
Garrison of Skulls camera clipping error

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11387] opened 2018-02-26 14:30 UTC
In the Garrison of Skulls, left-hand platform upon entry of the main entrance. The platform after the first flight of stairs has some strange clipping error that allows you to see through the walls, ceiling, etc. You can see this in the following attached video...

https://youtu.be/Mikj9A42mLA

**Comment by sioding** [comment] 2018-02-26 15:34
Duplicate of #10813

**Closed by sioding** 2018-02-26 15:34 UTC
