### ISSUE TITLE
[Gunbad/Quest] Dat Solithex's a threat

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#11367] opened 2018-02-24 00:48 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Upon killing solithex no quest progress was logged

Steps to reproduce the problem:
Get the quest and kill solithex

Screenshots/Videos or archive.org evidences:
![solithex](https://user-images.githubusercontent.com/19287032/36623414-d42a3a92-1904-11e8-9e99-a3f2a9a8cadc.png)

**Comment by thorbolt80** [comment] 2018-02-24 05:19
Already report : #11343

**Comment by sioding** [comment] 2018-02-24 07:03
Duplicate of #11343

**Closed by sioding** 2018-02-24 07:03 UTC
