### ISSUE TITLE
Vanquisher steeltoes engineer : This item can not be dyed

### ISSUE THREAD

**Issue by Gruikhan** [WarEmu/WarBugs#15106] opened 2019-11-08 17:04 UTC
Hi,

Vanquisher steeltoes engineer : This item can not be dyed

![be dyed](https://user-images.githubusercontent.com/48930133/68496324-4ebffc00-0252-11ea-9791-878224f46596.jpg)

Bye

**Comment by Kabucoror** [comment] 2019-11-09 08:42
Duplicate of #13249

**Closed by Kabucoror** 2019-11-09 08:42 UTC
Labels: Database, Item
