### ISSUE TITLE
Quest: A Sticky Situation

### ISSUE THREAD

**Issue by Peleliu** [WarEmu/WarBugs#11301] opened 2018-02-14 05:00 UTC
This quest appears to be bugged again.

The quest requires you kill spiders then free Gavin Scherer. I completed the quest then turned it in. I was able to take it again, but the spider kills were not required; just the free Gavin portion. I was unable to interact with Gavin this time. Dropped and repeated the mission several times with the same result. The mission shows as uncompleted in the TOK even though I did complete it the first time around.

Similar issues were previously reported by others and the reports were eventually closed.

**Comment by ArchWarhammer** [comment] 2018-03-18 14:19
The quest still doesn't work, I tried 5 times with my main character and switched to by secondary character and still no luck. I even called one of my friends over to do it to see if it was just a problem for me, his doesn't work either.

**Comment by LeonVic** [comment] 2018-04-04 13:36
That quest still dont work.
The issue is that the npc to get free from spider cave, is struck on stonewall. No way to unstruck by the players. 
I mean , solve is easy. just put the spawn point a bit more far from the stonewall.
see the screenshot
![immagine](https://user-images.githubusercontent.com/38075110/38310826-d607bb40-381d-11e8-8894-149b2b9c2366.png)
![immagine1](https://user-images.githubusercontent.com/38075110/38310889-fb0a89ae-381d-11e8-804d-784f6541a167.png)

**Comment by sioding** [comment] 2018-04-11 17:07
fixed with next patch

**Comment by sioding** [comment] 2018-04-14 08:04
fixed with patch from 14.04.2018

**Closed by sioding** 2018-04-14 08:04 UTC
Labels: Database, Fix Pending, Quests
