### ISSUE TITLE
Magus's Resummon

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#14890] opened 2019-09-07 13:35 UTC
When try to resummon pink horror or flamer after pet does not move and you getting disconnect all time but exept blue horror.

**Comment by globalgame** [comment] 2019-09-07 14:16
and engi's redeploy the same i tested

**Comment by sioding** [comment] 2019-09-07 14:32
Duplicate of #14889

**Closed by sioding** 2019-09-07 14:32 UTC
