### ISSUE TITLE
Destruction PQ Objective in Kron Komar Gap 

### ISSUE THREAD

**Issue by Reknarok** [WarEmu/WarBugs#17984] opened 2020-10-25 12:35 UTC
The Phase 1 objective for Kron Komar Gap is showing Order objectives rather than Destruction. I am a Black Orc.
![kronkomargapqp](https://user-images.githubusercontent.com/39253672/97107269-c795bd80-171a-11eb-85df-bbb3ded1a503.png)

**Comment by Lheana** [comment] 2020-10-25 12:54
Duplicate of #17313

**Closed by Lheana** 2020-10-25 12:54 UTC
