### ISSUE TITLE
ToK unlock 'A Matching Set'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8738] opened 2016-12-28 23:22 UTC
This bestiary unlock for Bray Shamans should be triggered by right-clicking on 'Bray Shaman Horns', which drops on Twisted Bray-Shamans (Saphery, 47k 10k). As destro Twisted Bray-Shamans are not attackable. I tried on order side, these mobs don't count as Bray Shamans and don't seem to drop the item needed.

**Comment by Ryanfawkez** [comment] 2017-01-16 15:10
Set faction hostile to all, fixed subtype, made item drop and added corresponding tome unlock.

**Comment by Blaqwar** [comment] 2017-01-21 18:02
This item seems to erroneously drop from players (T3 and T4 confirmed, not sure about others) after today's patch.

On a related note, it provides the unlock but not the title (title shows up as ??? and no title is unlocked in the rewards section of the ToK).

**Comment by Luth-RoR** [comment] 2017-01-21 20:58
Yes, known; will be fixed soon™.

**Comment by Lheana** [comment] 2017-01-28 11:51
Killing Bray Shamans triggers the unlock 'A Matching Set', but not the title. They don't seem to drop 'Bray Shaman Horns'.

**Comment by Luth-RoR** [comment] 2017-01-28 12:12
It seems like the fix to stop the ToK item drops wasn't pushed to live yet.

**Comment by Lheana** [comment] 2017-01-28 13:00
Oh thought it was fixed :)

**Comment by Lheana** [comment] 2017-02-07 17:06
Twisted Bray-Shamans still seem not to drop 'Bray Shaman Horns'.

**Closed** 2017-02-24 05:36 UTC
Labels: Database, Fix Pending, Item, NPC, Tome of Knowledge

**Comment by Blaqwar** [comment] 2017-02-24 12:56
I guess the way this ToK unlock was implemented is a workaround because the proper implementation is not possible atm?

You get the unlock by killing the Bray Shaman but the title isn't awarded, you get the title by equipping Bray Shaman Horns. I'm pretty sure there should be no unlock for killing Bray Shaman themselves, only for equipping Bray Shaman Horns (http://stuntystomper.blogspot.se/2008/12/missing-horns-for-matching-set.html - the image).

**Comment by Lheana** [comment] 2017-05-28 09:57
Yes Blaqwar, it is not possible yet to link unlock + title to one item. So the only solution is to link the mob to the unlock, and the item (pocket item) to the associated title.
