### ISSUE TITLE
zombocaplypse: Tricks & Treats, candy obtain

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12693] opened 2018-11-24 03:11 UTC
if you had Corrupted Candy already in your backpack, 
passing candy roll still update you quest success.
quest alarm says 4/1 if you had 4 candies in your backpack and passed new roll.
failed greed, need roll also update quest i think.
doesn't matter whether you actually won roll or not.

**Comment by sioding** [comment] 2018-11-24 08:32
Duplicate of #12525

**Closed by sioding** 2018-11-24 08:32 UTC
