### ISSUE TITLE
Eataine Order Warcamp - Duplicate NPC

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16654] opened 2020-05-04 01:16 UTC
As shown in the video, two Lanril Elderborn NPCs in the Order Warcamp.

https://www.youtube.com/watch?v=QA3aLSNuhio

Cheers,
Tes

**Comment by Kaelang** [comment] 2020-05-04 10:38
Duplicate of https://github.com/WarEmu/WarBugs/issues/13370.

**Closed by Kaelang** 2020-05-04 10:38 UTC
