### ISSUE TITLE
[Visual Bug] Ruin's set blue default dye carrying over to alt appearance

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#6098] opened 2016-05-16 15:41 UTC
Devastator Chestplate using Alt Appearance||||||||||||||||||||||||||||||||||||||||                               Ruin Chestplate using A. App

![sin titulo](https://cloud.githubusercontent.com/assets/14275335/15294526/eb5ea418-1b8c-11e6-942f-9b5f607345be.png)

It's better to explain it with a picture. As you can see, when you equip an undyed Ruin chestplate (or any other part of the set), and you apply some item as alt appearance, no matter what item it is,  the alt appearance dyes itself in the manner of the Ruin chestplate -aka blue-. This bug doesn't happen with any other item. It was fine with Martial Gear, and with Deva and Stalker. It only happens in the Ruin set.

It doesn't look really good, because you now see Destro races wearing blue armor: Chosen, DoK's, SH...I think every class is affected by this bug.

**Comment by Torquemadra** [comment] 2016-05-16 16:06
This is not a bug, this is how it is for every single piece of armour in game and was explained to you by a in game GM.

The base armour will retain its colouring unless the item being used as appearance has hard coded colouring. The earlier sets did NOT have colours assigned to them by virtue of them not being picked up on database build hence did not carry over.

To reiterate, this is NOT a bug and is WORKING as intended.

**Closed** 2016-05-16 16:06 UTC
Labels: I can't believe someone reported this
