### ISSUE TITLE
Crown of Fire / Frozen Fury not working when 2x BW or 2x Sorc

### ISSUE THREAD

**Issue by kalmatar** [WarEmu/WarBugs#12743] opened 2018-11-28 21:58 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Crown of Fire + Frozen Fury, 75% chance to proc Flames of Rhuin + Frozen Touch, career tactics for BW + Sorc
works normally fine when ONLY ONE BW or Sorc is using said tactic to improve their damage proc rates.

Problem is, running 2 BW or 2 Sorcs, in which case the original caster of the FoR/FT might be that BW 1 buffs BW 2 with dmg proc, but BW 2 is running tactic to get 75% trigger chance than normal 25%.... in which case things get weird. 
Or, in case of Sorc 1 giving Sorc 2 dmg proc, but both running FF tactic, might be that Sorc 2 has actual 75% chance to proc FT but Sorc 1 remains at 25% proc chance despite both using same tactic.
It's buggy, as there was nerf to how damage procs behave, previously CoF/FF would give 75% proc trigger chance to whole party, this was nerfed in early 2017 patch notes,  "breaking proc meta", so now things are buggy. 
Issue isn't even who was original caster of FoR/FF enchantment, but game RANDOMLY choosing only one of the BWs/Sorcs to have 75% proc chance (as tactic works), but other getting only 25% chance (tactic bugs out),
Issue is also related to zones, and travelling between various areas inside of zone, as the game will occasionally somehow switch between BW 1 and BW 2, deciding somehow that one tactic is working and other is getting overrun by other BWs tactic (due to proc meta nerf where somehow CoF/FF will then ensure rest of party has just 25% normal proc rate compared to 75% tactic given proc rate)
Same then for Sorcs, with Crown of Fire and Frozen Fury being mirrors. 

Steps to reproduce the problem:

Running 2 BW or 2 Sorcs and running CoF/FF tactics, moving around on maps with the game then somehow "re-establishing" which player has functional tactic and which has bugged one. 

Screenshots/Videos or archive.org evidences:

Evidence is based on hundreds of hours spent on my Sorc + BW in AoE specs, both my Sorc Nynaewe rr79 and BW Moreina rr79 have tried to figure out exact behaviour of this weird tactic bug... even with lot of gameplay recorded, I would have hard time finding "best material" from recordings as evidence.... but so far evidence from all hours spent on BW/Sorc points out that the tactics are very buggy, and only when running 2x BW or 2x Sorc.

**Comment by sioding** [comment] 2019-04-22 14:17
Duplicate of #11745

**Closed by sioding** 2019-04-22 14:17 UTC
Labels: Ability
