### ISSUE TITLE
Character Invisible

### ISSUE THREAD

**Issue by Alfinnete** [WarEmu/WarBugs#13483] opened 2019-02-25 11:36 UTC
After last Fortress update (Sat Feb 23, 2019 12:48 pm) one new bugg appear: THE INVISIBLE MAN! 

The character is invisible, only for those who are playing with him.

After bugg start you are forced die to fix.

**Comment by sioding** [comment] 2019-02-25 19:06
Duplicate of #13444

**Closed by sioding** 2019-02-25 19:06 UTC
