### ISSUE TITLE
tracer round +15% crit engineer tactic not working anymore 

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13632] opened 2019-03-13 08:51 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
see also #12478
![Thorbolt_792](https://user-images.githubusercontent.com/16274785/54265410-7ea8e980-4575-11e9-8f14-c72ae842de68.jpg)

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment] 2019-03-13 11:14
it's not showing in get stats but the tactic works i just set it to 100% crit rate instead of 15% and i did crit on all attack.

**Comment by sioding** [comment] 2019-03-13 13:34
Duplicate of #12478

**Closed by sioding** 2019-03-13 13:34 UTC
