### ISSUE TITLE
Game Kicked me then got this.

### ISSUE THREAD

**Issue by Krokodeilos** [WarEmu/WarBugs#11649] opened 2018-04-21 18:47 UTC
after game "crashed " and logged back in got this 
![krokodeilos_009](https://user-images.githubusercontent.com/38592305/39087704-9abad6ec-45ad-11e8-8332-e6c8f42d28b0.jpg)

**Comment by sioding** [comment] 2018-04-21 20:07
Duplicate of #11224

**Closed by sioding** 2018-04-21 20:07 UTC
