### ISSUE TITLE
Perma Fueled from Withi

### ISSUE THREAD

**Issue by TanithScout** [WarEmu/WarBugs#13658] opened 2019-03-16 17:51 UTC
Equip Fueled from Within with Endless Knowledge and Crown of Fire. Kill a mob (R38 Dustback Squig) from 54k/15k Black Crag. Change Fueled from Within to something else (Close Quarters) and kill more mobs. Flames of Ruin has same dmg in log but without tactic. 
![Vonrad_001](https://user-images.githubusercontent.com/42501475/54479390-14fa3b00-4814-11e9-88a8-1580fb84eb7a.jpg)
![Vonrad_002](https://user-images.githubusercontent.com/42501475/54479391-14fa3b00-4814-11e9-9c10-5cef6dc917b1.jpg)
![Vonrad_000](https://user-images.githubusercontent.com/42501475/54479392-14fa3b00-4814-11e9-9bcb-b480277106eb.jpg)

**Comment by TanithScout** [comment] 2019-03-16 17:52
Especially now when the forts have been released and many people are rolling BW's, a 5th tactic on top of this would be pretty gamebreaking. Hope its a bug? Let me know if you need anything. 

Cheers

**Comment by TanithScout** [comment] 2019-03-16 17:54
Effect persists after death lol...

**Comment by sioding** [comment] 2019-04-22 14:20
Duplicate of #13658

**Comment by sioding** [comment] 2019-05-05 13:27
Duplicate of #13224

**Closed by sioding** 2019-05-05 13:27 UTC
Labels: Ability
