### ISSUE TITLE
Crafting icons switching between seed and plant

### ISSUE THREAD

**Issue by Remmingtonz** [WarEmu/WarBugs#11712] opened 2018-05-03 14:04 UTC
When i logged in, I was trying to cultivate lvl 200 napalm mats. but instead of harvesting them the icons in my backpack switch between the spore and the reagent. and when i harvest the number doesn't increase, just jumps between the spore and the cultivated product but stays at 1 not 8 or more (was successful at growing so x 2 should have been rewarded once broken back down) 

Expected behavior and actual behavior:
should have had at least 4 fully grown lvl 200 seeds/fungi after cultivation, but due to error have none

Steps to reproduce the problem:
I tried cultivating some lvl 175 parsley seeds and now the same thing happens and the icon switched between the seed and the plant and appears not in the next empty slot but in pack 2 replacing some other craft items i have 

Screenshots/Videos or archive.org evidences:
![anaerionz_002](https://user-images.githubusercontent.com/38742275/39581282-4f6e7d74-4f3f-11e8-9129-4cb3515abbd8.jpg)
![anaerionz_003](https://user-images.githubusercontent.com/38742275/39581285-4fb613c8-4f3f-11e8-8b9f-675e3f1f0564.jpg)

Note. I have re-logged and the issue still persists

thanks for your time 

Remmi/Anaerionz

**Comment by sioding** [comment] 2018-05-03 14:38
Duplicate of #10776

**Closed by sioding** 2018-05-03 14:38 UTC
