### ISSUE TITLE
Displayed and acting "dead" when knocked down ORvR/Fort

### ISSUE THREAD

**Issue by Malvaine** [WarEmu/WarBugs#15072] opened 2019-10-28 13:17 UTC
Expected behavior and actual behavior:
Expected: After knockdown, my char stands up and is able to move and use skills. Actual: When knocked down at the fort in Reikwald, "You are dead" was displayed on the screen while my char was still at full hp. Unable to respawn, use skills or move until someone actually killed the char.

Steps to reproduce the problem: Joined a warband in Reikland one day later, we laid siege to the order keep and I got the same bug. After relogging, everything was back to normal.

**Testing Screenshots/Videos/Evidences (always needed):**![Eldire_008](https://user-images.githubusercontent.com/57098865/67681179-19332d00-f98d-11e9-9f84-e34f677ff7df.jpg)

**Comment by sioding** [comment] 2019-10-28 13:18
Duplicate of #11407

**Closed by sioding** 2019-10-28 13:18 UTC
