### ISSUE TITLE
Boss kill quests: no kill count

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13951] opened 2019-04-26 12:24 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected King Meatball aka 'aard ta feed to be killed and registred in the quest but it was not
same behavior from solithex, and in sentinel dungeons so far this past week

**Steps to reproduce the problem:**
take quest, kkll boss, shed a tear for ur teammates who need gear

**Screenshots/Videos or archive.org evidences:**
https://www.youtube.com/watch?v=BDdUj3aZKUI&feature=youtu.be
video of me and a group killing king meatball aka ard to feed and no boss kill : u see boss kill count on the right

**Comment by sioding** [comment] 2019-04-26 13:02
Duplicate of #13563

**Closed by sioding** 2019-04-26 13:02 UTC
