### ISSUE TITLE
Guild Vault Stash Price

### ISSUE THREAD

**Issue by dekadd** [WarEmu/WarBugs#16392] opened 2020-04-15 15:44 UTC
Hi, i need 162201 gold to purchase another one Guild vault stash.

And we don't receive an stash for level Up our guild.

Can you help me ?

Thanks.
![Komateux_005](https://user-images.githubusercontent.com/63735947/79357737-b3d5f700-7f40-11ea-930d-709cd651b3df.jpg)

**Comment by Kaelang** [comment] 2020-04-19 15:46
Duplicate of https://github.com/WarEmu/WarBugs/issues/16297.

**Closed by Kaelang** 2020-04-19 15:46 UTC
