### ISSUE TITLE
Replaced talismans in 2-slotted item do not fuse correctly

### ISSUE THREAD

**Issue by nailinthehead** [WarEmu/WarBugs#11385] opened 2018-02-26 06:40 UTC
Reproduced issue #9765
Beginning state: Had +18 str and +18 ws talis in a great hammer.
Chain of events:
1. Replaced str tali with armour and second one with + 18 ini. Armour got fused ok, ini did not fuse and ws one remained in the slot, although the ini tali disappeared from my bag.
2. Then I took +22 ini and attempted to replace the ws tali again. Unfortunately after fusing the ws tali turned into +18 ini and the +22 one disappeared from the bag.
3. In order to test it further I replaced the +18 ini one with +12 wounds tali, hoping it will turn into the +22 ini I lost, but it fused ok. So I had +124 armour and +12 wounds talis in the weapon.
4. Replaced wounds tali with +18 ini and it fused ok again.

Summary: looks like there's some problem with refreshing second slot with new tali in two-slots gear after replacing both talismans at once or in a short span of time.

**Comment by sioding** [comment] 2018-02-26 11:29
Duplicate of #9765

**Closed by sioding** 2018-02-26 11:29 UTC
