### ISSUE TITLE
NPC´s can be dragged from spawn -  even if they want to return

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#12208] opened 2018-08-25 16:41 UTC
A roaming mob can not be killed if it is to far away from its 'original' position. It keeps resetting to its 'current' position.

Example
Praag. Reinforcing Magus Location: 5680,45755

Expected behavior and actual behavior:
Roaming mobs can be killed while roaming around and are not to far away from their original position

**Comment by sioding** [comment] 2018-08-26 05:58
Correct handling - don´t be too far away from the NPC.

**Comment by Arlen88** [comment] 2018-08-26 07:46
Maybe that was unclear, let me try to desribe it:

A mob/npc is roaming from its ORIGINAL location to its CURRENT location and the CURRENT location is to far away from its ORGIINAL location (reset-range or how do you call that) and keeps staying there.

You are not able to kill that mob/npc DIRECTLY at its CURRENT location, because it keeps resetting to its CURRENT location.

**Comment by sioding** [comment] 2018-08-26 07:50
I have tried to reproduce it - but i can kill every mob. Please add a video to show us th problem. Since there is only one report - i am not sure it a a real problem. I do reopen it but you have to add more info´s like a video or something.

**Comment by Arlen88** [comment] 2018-08-26 07:51
I'll do, if it happens again! Thank you

**Comment by Arlen88** [comment] 2018-08-26 08:03
I see, it is the same problem like roaming realmguards ... They are not aggressive initially but you can't kill them, because they keep resetting.

![0001](https://user-images.githubusercontent.com/33158303/44626087-1a934080-a917-11e8-8d65-b5ff9485eee1.PNG)
![0002](https://user-images.githubusercontent.com/33158303/44626088-1a934080-a917-11e8-9efe-e235edb5662a.PNG)
![Uploading 0003.PNG…]()

**Comment by Arlen88** [comment] 2018-08-26 08:10
![0004](https://user-images.githubusercontent.com/33158303/44626161-321ef900-a918-11e8-97d0-d101313782a5.PNG)

**Comment by sioding** [comment] 2018-08-26 10:30
OK i tried it with exactly the same NPC and yes - this is resetting - and its not a roaming one - if you have a look at the others at that place - they are not roaming. I tried a roaming NPC and can not reproduce it.

**Comment by sioding** [comment] 2018-08-26 16:41
Tried more on this NPC but still can not reproduce anything you said.

**Comment by Arlen88** [comment] 2018-08-26 18:30
Reproducable ...
1. Pull a mob from its ORIGINAL location
2. When the mobs is to far away from its ORIGINAL Location and wants to return, kite it a little bit further
3. Mob looses its ORIGINAL location (somehow, i think) and stays at a NEW loacation
4. Mob cannot be killed anymore but keeps resetting at its NEW location

![0008](https://user-images.githubusercontent.com/33158303/44631597-a6848700-a96e-11e8-9310-04ef17239f96.PNG)
![0009](https://user-images.githubusercontent.com/33158303/44631598-a71d1d80-a96e-11e8-9b43-2dff75689622.PNG)

**Comment by sioding** [comment] 2018-08-26 18:32
Thanks for the details.

**Comment by Arlen88** [comment] 2018-08-26 18:33
YW and thank you!

**Comment by Arlen88** [comment] 2018-08-27 07:54
One update, it seems that this is not a minor bug, cause it is possible to drag around realmguard-heroes and position them into keep doors.

**Comment by Natherul** [comment] 2018-08-27 08:36
please confirm if this still happens after todays most recent hotfix.

**Comment by Arlen88** [comment] 2018-08-27 15:45
When ist the hotfix going to happen? I can still drag mobs/npc away from their ORIGINAL location

**Comment by Natherul** [comment] 2018-08-27 15:51
the hotfix was shortly before my last comment.

That hotfix was intended to fix the biggest of those issues but was still a hack. A more permanent solution is now in the pipe for patching and should be patched tomorrow morning. So hopefully tomorrow morning all these issues will be resolved

**Comment by Arlen88** [comment] 2018-08-27 15:58
Okay, I just tested it for you, thank you for looking at this :)

![0010](https://user-images.githubusercontent.com/33158303/44670282-90d09980-aa22-11e8-9eeb-776b90f3f5a1.PNG)
![0011](https://user-images.githubusercontent.com/33158303/44670283-90d09980-aa22-11e8-99c0-b8ea871443b2.PNG)

**Comment by Natherul** [comment] 2018-08-28 09:11
should have been fixed as of todays hotfix, if the issue persist please comment on this ticket again

**Comment by Arlen88** [comment] 2018-08-28 16:12
I'm afraid it is still possible, but it's a little harder now. 
You have to drag the mob/npc continuously, after a while it looses its original location.

Didn't try it with a Realm Guard yet.


![0012](https://user-images.githubusercontent.com/33158303/44735729-89c28d80-aaed-11e8-9cf3-019d4960d2ca.PNG)

**Comment by MaxHayman** [comment] 2021-03-29 10:20
I think this was fixed due to some changes when we implemented pathfinding. Anyone had this issue recently?

**Closed** 2021-05-27 12:28 UTC
Labels: NPC, Possibly Fixed, Sourcecode
