### ISSUE TITLE
Ashreaver PQ Stage 1 - no enemy npcs  to kill

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#14812] opened 2019-08-20 11:17 UTC
Cinderfall PQ Ashreaver Triber Stronghold 

 
Stage 1 - Kill Ashreaver Gnoblars

    There arent any, just their pack animals, the whole area is empty

**Comment by Lheana** [comment] 2019-08-20 12:17
Duplicate of #10862.
Wait for a server restart hoping it will work after.

**Closed by Lheana** 2019-08-20 12:17 UTC
