### ISSUE TITLE
Bloodlord set doesn't give Superior Ward fragments

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14405] opened 2019-06-12 12:57 UTC
**Expected behavior and actual behavior:**

Ward fragments were fixed today for Lesser ward and Greater ward. But it doesn't seem like Bloodlord gives any superior ward fragments like it should.

**Steps to reproduce the problem:**

Equip pieces of Bloodlord gear and check wards section in ToK.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_212](https://user-images.githubusercontent.com/7400/59353212-bd8c3e00-8d22-11e9-8e98-53e3d9d19137.jpg)

**Comment by Natherul** [comment] 2019-06-12 13:11
works as intended and will be apparent once client gets patched.

**Comment by sioding** [comment] 2019-06-16 16:03
Fixed with patch from 15.06.2019

**Closed by sioding** 2019-06-16 16:03 UTC
Labels: Fix Pending
