### ISSUE TITLE
Account that bug an entire Warband.

### ISSUE THREAD

**Issue by Alfinnete** [WarEmu/WarBugs#11499] opened 2018-03-24 13:28 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

**Expected behavior and actual behavior:**

Warband UI should show groups and the status of each player correctly.

Warband UI bug as soon as I enter.

**Steps to reproduce the problem:**

Warband UI bug as soon as I enter, players report that they add some groups, my HP is around 250k (only visually), people who enter after I join do not appear in WB, healers report not being able to use resurrection, WB no longer updates status of players, just by pressing L you can see the actual amount of players in the WB.

>> The problem is in acc, once logged in another is not see the bug. <<

**Screenshots/Videos or archive.org evidences:**

![noisetoy_002](https://user-images.githubusercontent.com/19777804/37864454-e683640c-2f4d-11e8-9d63-3f3f6794ccc8.jpg)
![noisetoy_004](https://user-images.githubusercontent.com/19777804/37864455-e6a99078-2f4d-11e8-9046-2f71da9f6479.jpg)

**Comment by szejoza** [comment] 2018-03-24 13:40
Always try to see if it happens with standard interface, it might actually be addon that causes it to bug

**Comment by Alfinnete** [comment] 2018-03-24 13:45
Both accounts are exactly the same addon. Only the account Alfinnete has the problem with any character.

**Comment by sioding** [comment] 2018-03-24 14:25
Standard Interface means: no addon activated. Please check if the issue is the same with the old Mythic WB interface.If not - something is wrong with your addon. And i am sure we would have tons of reports if this happens to all players.

**Comment by Alfinnete** [comment] 2018-03-24 14:51
Zero Addon. Original UI of Mythic and same problem.
See in the chat what a player is responding after I ask if any bug happened to them after I joined WB.
![noisetoy_006](https://user-images.githubusercontent.com/19777804/37865286-5c6b6704-2f59-11e8-807b-10fe2790923b.jpg)

**Comment by Alfinnete** [comment] 2018-03-24 20:49
It looks like the problem may be location, a friend who lives in the same country has the same problem.

Latitude	-16.7010
Longitude	-49.2668
Country	Brazil
Region	Goias
City	Goiania

**Comment by sioding** [comment] 2018-03-26 13:13
Since you are also discussing it inside the forum - i will close this here.
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=25907

**Closed by sioding** 2018-03-26 13:13 UTC
Labels: Dubious, Party, User Interface

**Comment by Alfinnete** [comment] 2018-03-31 11:19
Folks.

If your Guild contains any special characters the members will break the WB UI as soon as they enter.

This will happen to all of WB, so if you have this problem, check the guild name.
