### ISSUE TITLE
Shaman - still missing healing weapon for oppressor emblems

### ISSUE THREAD

**Issue by NihilAbalham** [WarEmu/WarBugs#14085] opened 2019-05-13 19:04 UTC
Hello,
The heal weapon for shaman with oppressor emblems is still missing.
![Capuche_043](https://user-images.githubusercontent.com/19999643/57647102-6b8cb700-75c2-11e9-8a23-a117a7b1fa00.jpg)
Weapon besides completely useless because without AP so take your time ^^

Thanks !

**Comment by sioding** [comment] 2019-05-13 19:09
Duplicate of #14026

**Closed by sioding** 2019-05-13 19:09 UTC
