### ISSUE TITLE
Scenario Can't move after Respawn

### ISSUE THREAD

**Issue by Pazzlack** [WarEmu/WarBugs#14294] opened 2019-06-01 21:53 UTC
Hello,

I was in the scenario Reikland Hills and got killed, after Respawn I cant use any abillity or move. I tried to enable Move by Mouse but doesnt work too.
![da29dca2e2cd9e8c368903c3283d0ecf](https://user-images.githubusercontent.com/51275331/58753987-64254300-84c8-11e9-8901-a82c924c758b.jpg)

This was the position where I was stuck

**Comment by sioding** [comment] 2019-06-02 05:00
Duplicate of #10632

**Closed by sioding** 2019-06-02 05:00 UTC
