### ISSUE TITLE
Phoenix gate scenario 48/0 and no domination. bug?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11958] opened 2018-06-27 03:22 UTC
![thorbolt_321](https://user-images.githubusercontent.com/16274785/41951237-18e3b9a8-79ca-11e8-9700-da38b40bff72.jpg)

**Comment by Natherul** [comment] 2018-06-30 09:44
Been discussing this with Sio.

Essentially this is not a bug but by design domination needs spawn killing to happen to trigger.

This ticket lacks the data, but I assume no spawn killing was done as the underdog kept running in. Now this is something Im very weary of changing as tightening the rules for domination further risks closing scenarios needlessly.

**Closed by Natherul** 2018-06-30 09:44 UTC
Labels: Scenarios
