### ISSUE TITLE
Constantly falling after Scenario 

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11559] opened 2018-04-06 14:42 UTC
Played a Tor Anroc Scenario and was punted right before I hit the leave button. Respawned in Avelorn Warcamp in falling animation and couldn't move (see video below). Relogged and was still stuck in this location and animation. Only the Book of Binding was able to cancel this. 

**Steps to reproduce the problem:**
Leave SC during a punt flight.

**Screenshots/Videos or archive.org evidences:**
https://www.twitch.tv/videos/247271244 - if you need this for longer, let me know. Video will be deleted in a month.

**Comment by sioding** [comment] 2018-04-06 15:08
Duplicate of #10682

**Closed by sioding** 2018-04-06 15:08 UTC
