### ISSUE TITLE
[Quest] Distillation of Hate

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1418] opened 2015-09-16 20:33 UTC
in 2ed step Elyrion Steeds dont drop Hides

**Comment by Reggaewaldo** [comment] 2015-09-28 06:39
Added the Hides as quest item and added the quest item to the loot table. Change will be active with next update.

**Comment by Reggaewaldo** [comment] 2015-09-28 06:42
#1537 the follow-up of this does not currently work as intended.

Closing this ticket.

**Closed by Reggaewaldo** 2015-09-28 06:42 UTC
Labels: Database, Quests
