### ISSUE TITLE
Character bugged, stuck in purgatory throwing Null Reference Exceptions.

### ISSUE THREAD

**Issue by deeldoze** [WarEmu/WarBugs#7813] opened 2016-09-18 06:12 UTC
Each time I try to log in to my Ironbreaker, Bootus, I'm booted back to character select after logging in. If I try to log in again it will succeed, although I will be stuck in a skybox with absolutely nothing visible, no gear visible, an empty inventory, no abilities, and 0 to all stats. In my chat log there are two null reference exception errors from database tables. I had logged in on my Warrior Priest prior and have started seeing Warrior Priest UI elements whenever I log in. Tactics and morale bars are completely missing.
With the assistance of Grandpa I had my character moved to other zones several times which while giving me freedom of control, left me with absolutely nothing available despite everything appearing normal (gear being equipped) to Grandpa. Attached are screenshots. The last is after teleportation.
![bootus_010](https://cloud.githubusercontent.com/assets/19521607/18613271/e1b9c35e-7d3c-11e6-874c-ad6365561301.jpg)
![bootus_011](https://cloud.githubusercontent.com/assets/19521607/18613272/e1bab3b8-7d3c-11e6-85c9-97a22d2ac517.jpg)
![bootus_012](https://cloud.githubusercontent.com/assets/19521607/18613275/e1be45c8-7d3c-11e6-9cb3-9baa5ac74fb0.jpg)
![bootus_013](https://cloud.githubusercontent.com/assets/19521607/18613274/e1be26d8-7d3c-11e6-83a0-553bff85b69c.jpg)
![bootus_014](https://cloud.githubusercontent.com/assets/19521607/18613273/e1bd811a-7d3c-11e6-8c8b-522218acdd7b.jpg)

**Comment by Torquemadra** [comment] 2016-09-18 06:42
Can you go to your warhammer install folder then user>settings>Martyrs Square and delete the folder Bootus from within there and let us know if this did anything. This is where your profile settings are stored and it can become corrupted.

Beyond that its likely to require someone going into the character database on the live server.

**Comment by deeldoze** [comment] 2016-09-18 07:04
Doing as requested reset my UI to the proper class, however no luck in functionality. Compass is showing me in 'Zone 0.'
![bootus_015](https://cloud.githubusercontent.com/assets/19521607/18613636/434dd41e-7d44-11e6-9ead-22a5c04d8a54.jpg)

**Comment by deeldoze** [comment] 2016-09-19 17:45
Decided to fidget with it a bit more, turns out that after being booted to the character select screen after logging in the first time, any character I try to log in with afterwards will be subject to the same issue until I restart my client.

**Comment by FlexArc** [comment] 2016-09-20 16:32
Confirmed!
My character [Meingre:chosen] also bugged.
Last visited 09.17

**Comment by Jixxx** [comment] 2016-09-20 20:23
Hello,

Grandpa asked me to post here.

It seems that my SW Jixz has the same issue #7813

I don't know what screenshot could help you because unlike to Bootus I'm always back to the selection character page after loading.

**Comment by deeldoze** [comment] 2016-09-22 01:52
By some good grace, Bootus is once again functional. I logged on successfully with another machine and since then I've had no issues. Leaving the report open for the other guys for the time unless a member of RoR staff sees fit for this to be closed.

**Comment by Jixxx** [comment] 2016-09-24 23:08
I  tried to log in with another machine. It worked once and then, still the same situation...go back to character selection screen after loading my main.

**Comment by Luth-RoR** [comment] 2017-05-07 06:20
Closing as it is a user hardware/software issue and not related to the RoR server/client.

**Closed by Luth-RoR** 2017-05-07 06:20 UTC
