### ISSUE TITLE
Proc dmg from weapon enlaged with dmg buff fom turret

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12417] opened 2018-10-07 04:07 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

turret buff on engi enlarging the proc damage from weapon

Steps to reproduce the problem:

get an engi with proc weapon hitting you with dmg buff from turret, till it proc the proc form weapon

Screenshots/Videos or archive.org evidences:

![leapingtoad_007](https://user-images.githubusercontent.com/13465031/46578128-21ca6580-ca10-11e8-86c8-f12ac789ba64.jpg)

**Comment by sioding** [comment] 2018-10-07 08:40
Thats not a bug. RoR Wiki:
https://wiki.returnofreckoning.com/index.php/Engineer

> Turrets grant up to 8 Improvised Upgrades stacks every 2s when within 30ft of your turret. Damage is increased by 5% per stack for a max of 40% damage. 4 stacks of Improvised Upgrades are lost when a turret is destroyed for any reason. All stacks of Improvised Upgrades are lost when a turret of a different type than the last is constructed.

I do not see any "Damage of mastery abilities" - its just a pure "Damage is increased".

**Comment by Kweedko** [comment] 2018-10-07 08:55
It's a bug and disbalance. On an overperforming career vs all other carres who don't have dmg increasing buffs. Proc hitttng 500 dmg when you hitting engi with skills with 300 dmg it's a total bullshit. 

With Coordinated Fire(15%) + (Trench Fighting) 15% + 40% from turret - procs will be even harder it's a total imbalance.

**Comment by sioding** [comment] 2018-10-07 09:27
moved to leads decision - we have to wait for them.

**Comment by Natherul** [comment] 2018-10-07 16:59
Procs should after next patch not apply damage % increase stat.

**Comment by sioding** [comment] 2018-10-08 18:54
fixed with patch from 08.10.2018

**Closed by sioding** 2018-10-08 18:54 UTC
Labels: Ability, Fix Pending
