### ISSUE TITLE
Dwarf Chapter ten. Missing Basic Rewards from Inf PQ Bar.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10870] opened 2017-11-19 10:03 UTC
Same as before not sure what else to put in here. 

It's just missing the basic rewards for Chapter Ten Dwarf. 

-Nolan

**Comment by sioding** [comment] 2017-11-19 10:12
Duplicate of #10006

STOP just posting - follow the rules.

**Closed by sioding** 2017-11-19 10:12 UTC
