### ISSUE TITLE
Tome Entry The Key to Success not working

### ISSUE THREAD

**Issue by Sigbertus** [WarEmu/WarBugs#14721] opened 2019-08-04 15:00 UTC
The Tomeentry The Key to sucess for Bloodletter of Khorne is not Working 

Got that needed  Talisman Key from a Previous entery 
if i click that chest it spawns a smaller Chest (as it should)
and if i click that one , nothing happens  (it should give me a Bejeweled Skull)
![Auctoritas_000](https://user-images.githubusercontent.com/53393282/62425243-4eefaf00-b6d9-11e9-924c-a799c55bbb0f.jpg)
![Auctoritas_001](https://user-images.githubusercontent.com/53393282/62425245-52833600-b6d9-11e9-9bd3-acb8c50be67e.jpg)
![Auctoritas_002](https://user-images.githubusercontent.com/53393282/62425252-54e59000-b6d9-11e9-9c74-cb773de08a54.jpg)
![Auctoritas_003](https://user-images.githubusercontent.com/53393282/62425255-5a42da80-b6d9-11e9-872b-04114b87c4b5.jpg)

**Comment by Lheana** [comment] 2019-08-04 15:05
Duplicate of #6102

**Closed by Lheana** 2019-08-04 15:05 UTC
