### ISSUE TITLE
Keep: Chest/Lootbag issues

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#4804] opened 2016-03-07 16:42 UTC
After sieging 3 keeps succesfully (being top roller at all times), here's the score: 
1 bag got looted as intended.
1 chest did not appear at all. (Dark Elf keep)
1 chest could not be interacted with, looting not possible (High Pass Chaos)

So far I've not received anything in mailbox.

**Comment by fiazco** [comment] 2016-03-08 11:18
Recieved a Lesser Loot Bag from Keep take. Got it in the mail. But cant open it.

Screenshot of the Bag. Didnt say anything about open.
[http://www.pic-upload.de/view-29968928/Corporal_002.jpg.html](url)

**Comment by Pumatouch** [comment] 2016-03-08 13:49
Did some more keep sieging to confirm, seems to be as noted above; Greenskin keep works fine, the other two keeps have issues.

**Comment by Natherul** [comment] 2016-03-11 21:43
So far I have not gotten any bag from any of the keeps, but I dont think I have done the orc/dorf one yet... 

Also each time on the scoreboard Im placed as first and when opening the box for it im not on the list so I think that part is bugged as well

**Comment by Dirtyburger1338** [comment] 2016-03-18 16:43
Ive done 3 keeps and each time the roll said i was placed first and won a massive loot bag. I do not get anything at all from clicking the chest and im not actually in the top of the list.

**Comment by Natherul** [comment] 2016-03-19 06:46
Indeed, it seems the issue is not the chests or bags themselves but the tracker does not seem to show properly, always showing you as #1

**Comment by wargrimnir** [comment] 2017-01-12 23:38
Should be fixed.

**Closed** 2017-01-13 20:04 UTC
Labels: ORvR, Public Quests
