### ISSUE TITLE
missing character

### ISSUE THREAD

**Issue by Gokudou** [WarEmu/WarBugs#18664] opened 2021-03-16 14:04 UTC
after today's server reboot, the character disappeared (marauder 8 lvl)
instead, magus 2 lvl appeared (previously created but deleted/changed to a marauder)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment] 2021-03-16 16:19
What were the character names?

**Comment by Gokudou** [comment] 2021-03-16 17:32
Character name Gokudou, played for about 4-5 hours (8 or 9 LVL)

**Comment by Gokudou** [comment] 2021-03-18 01:16
do not restore the previous character, created a new one. I hope there will be no more such bug...

**Comment by MaxHayman** [comment] 2021-03-29 14:10
I've managed to find the root cause of the issue so this shouldn't happen to anyone in the future.

**Comment by Lheana** [comment] 2021-04-18 14:15
This has been fixed with the patch of 31/03/2021.

**Closed by Lheana** 2021-04-18 14:15 UTC
Labels: Fix Pending
