### ISSUE TITLE
Bug (Backpack)

### ISSUE THREAD

**Issue by afa555** [WarEmu/WarBugs#12060] opened 2018-07-20 16:25 UTC
Hello. I describe the bug found recently:
Yesterday I performed a public quest in Ekrund (T1)
Killing monsters, I collected a lot of things, and then parsed them into component components, with the help of their profession (Talisman + Parser)
Then, when my rucksack was full, I disassembled the next thing and I had an alert (Overflow (4 items)) at the bottom of the inventory window.
After I cleaned the inventory, I still can not remove this notification. These 4 items refuse to fall into the inventory, or to be destroyed, when the mouse is moved to an empty area, outside the inventory window.
I ask you to solve this problem. Blinds the eyes. I think others could also face such a problem.
Screenshots I enclose:
![image](https://user-images.githubusercontent.com/41484111/43013575-029e7e7c-8c52-11e8-8dab-155918a2c46e.png)
![image](https://user-images.githubusercontent.com/41484111/43013595-19a05cd0-8c52-11e8-9919-b331e6d9030f.png)
![image](https://user-images.githubusercontent.com/41484111/43013613-2832c40e-8c52-11e8-9e7b-b5e172326447.png)
![image](https://user-images.githubusercontent.com/41484111/43013632-363c2ee6-8c52-11e8-9d5a-60c243127d57.png)
Perhaps, that such a problem has arisen only in me. My play nickname "Edifier". Thank you.

**Comment by sioding** [comment] 2018-07-25 06:07
are you using the filters on the backpack?

**Comment by CrimsonFenris** [comment] 2018-08-07 15:02
Issue previously reported here : https://github.com/WarEmu/WarBugs/issues/11937

**Comment by sioding** [comment] 2018-08-07 15:54
Duplicate of #11937

**Closed by sioding** 2018-08-07 15:54 UTC
Labels: Item
