### ISSUE TITLE
rr44 and got 5 officer medals from gold bag

### ISSUE THREAD

**Issue by CaledorTree** [WarEmu/WarBugs#11270] opened 2018-02-08 00:18 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
![war 2018-02-08 02-07-12](https://user-images.githubusercontent.com/25325181/35948622-198644b4-0c76-11e8-90bb-fda48b3ac09a.png)
![war 2018-02-08 02-07-09](https://user-images.githubusercontent.com/25325181/35948623-19e51d22-0c76-11e8-83f9-5038777bcac9.png)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-02-08 06:42
Duplicate of #11250

**Closed by sioding** 2018-02-08 06:42 UTC
