### ISSUE TITLE
Game not playable

### ISSUE THREAD

**Issue by EssentialOrder** [WarEmu/WarBugs#14934] opened 2019-09-16 17:16 UTC
The last weeks till now game is mostly unplayable.
lag every minute
dc 10 times an hour
dc from scenarios
in general we are mostly out of the game watching the screen

**Comment by sioding** [comment] 2019-09-16 17:49
I close this one here. Its not helpful - we know about the situation cause we do play on our own. Since this report doesn't contain any helpful information how we can reproduce the problem or any information we could use to get out of it its a: close

**Closed by sioding** 2019-09-16 17:49 UTC
