### ISSUE TITLE
Nordland Quest Hearts and Minds NPC weird spawning

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#10478] opened 2017-09-21 23:02 UTC
In Nordland this quest requires us to speak to these farmers and they turn into enemies that we have to kill, but since they are all so grouped up they end up killing each other before we can get the kill counted for the quest.

https://youtu.be/21hy-mKpyfk

**Comment by Razielhell** [comment] 2017-09-22 08:28
Ty for the report.

**Comment by Lheana** [comment] 2018-09-16 21:01
Closing this as from what I can see, the issue is no longer happening.

**Closed by Lheana** 2018-09-16 21:01 UTC
Labels: Quests, Scripting
