### ISSUE TITLE
[Quest] Daemonic Strength Invincible NPCS

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14914] opened 2019-09-11 01:21 UTC
An introduction:

The npcs that I have to kill to complete this quest are invincible?

Details:

NPC's should be killable but now they aren't.

Evidence:

https://youtu.be/kBFCUj56a3g

How to reproduce the bug:

I don't know why they are invincible now.

**Comment by Lheana** [comment] 2019-09-21 21:14
Duplicate of #14895

**Closed by Lheana** 2019-09-21 21:14 UTC
Labels: Database, NPC
