### ISSUE TITLE
Gork sez stop works on all dungeons bosses (Gundbad and City Dungeons)

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#12640] opened 2018-11-19 11:46 UTC
Don't know if intended or not.

If Gork Sez Stop (Shaman Moral 1) is used on one of the bosses in either Gunbad or the new city dungeons it runs for the whole 30 seconds even when the boss is not moving.

Will try to make a video in the next run.

**Comment by sioding** [comment] 2018-11-19 12:19
Duplicate of #12640

**Comment by sioding** [comment] 2018-11-19 12:19
Duplicate of #1879

**Closed by sioding** 2018-11-19 12:19 UTC
