### ISSUE TITLE
Tok unlock for entering sewers?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11821] opened 2018-05-31 05:06 UTC
I don't have Tok unlock when I entered sewers. They have a tok unlock like when you enter bastion stairs?

**Comment by Ryanfawkez** [comment] 2018-05-31 08:06
There's no influence entry for the Sewers of Altdorf, so I doubt it.

**Comment by sioding** [comment] 2018-05-31 10:39
So @thorbolt80  - if you have any proof for it - it would be great to see it.

**Comment by sioding** [comment] 2018-05-31 19:01
Duplicate of #9653

**Closed by sioding** 2018-05-31 19:01 UTC
Labels: 2 Week Ultimatum, Confirmation Request, Tome of Knowledge
