### ISSUE TITLE
Are we in season 2 in ranked ? can't buy stuff.

### ISSUE THREAD

**Issue by Layinolias** [WarEmu/WarBugs#17073] opened 2020-06-09 17:55 UTC
Hello guys,
Maybe i miss some info and we are in season 2 in ranked so if that is just close this 🈂️ 
But if we are not, i maybe have an issue with the way for can buy stuff.

You will see on pic i can't buy because i don't play enooth sc for this season, But i played 201 sc(ref Armory)

My character name Ig : Layinolas

![Layinolias_088](https://user-images.githubusercontent.com/14100625/84182583-ed336a80-aa8a-11ea-9ed6-fcac1769f6f5.jpg)

Thx you for helping me )

**Comment by Kaelang** [comment] 2020-06-09 18:01
We are in Season 1 - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16785.

**Closed by Kaelang** 2020-06-09 18:01 UTC
