### ISSUE TITLE
new and it is still not working magic power willpower int from genesis gems most weapons and armor dont transfer over on zelot harbringer off doom

### ISSUE THREAD

**Issue by jusva321** [WarEmu/WarBugs#19035] opened 2021-05-22 21:09 UTC
i have allready posted screen shoots and you replyed it is working ill go agian then because it is not working like you said in your email i used .getsstats and you will agian see my willpower and healing power dont move when i take the gem off and on 
![1 with genesis 166 8 heal bonus](https://user-images.githubusercontent.com/72552430/119240813-96fff000-bb52-11eb-8364-0f5a183577a1.png)
![2](https://user-images.githubusercontent.com/72552430/119240814-98311d00-bb52-11eb-9b90-e445406c2644.png)

**Comment by jusva321** [comment] 2021-05-22 21:10
willpower 661 with and without healingpower 86 with and without hope you try and fix this

**Comment by jusva321** [comment] 2021-05-22 21:12
![3](https://user-images.githubusercontent.com/72552430/119240888-1c83a000-bb53-11eb-93a0-e057a9d58d5e.png)


harbringer off doom will change your int and magic power to willpower and healpower ....

**Comment by jusva321** [comment] 2021-05-22 21:32
![4](https://user-images.githubusercontent.com/72552430/119241328-e72c8180-bb55-11eb-8abe-8f9d9a898828.png)
![5](https://user-images.githubusercontent.com/72552430/119241331-e98edb80-bb55-11eb-925e-c18fb9684dc1.png)


agian willpower dont transfer over and crit stay as magic crit

**Comment by jusva321** [comment] 2021-05-22 21:33
613 willpower 13 heal crit nothing change

**Comment by lilimx** [comment] 2021-05-23 15:25
Toggler off:
The first blue one are my stats without my jewelry.

The second blue are with 2 Scholar jewelry and int and magic power got converted right into willpower/heal power.

![1](https://user-images.githubusercontent.com/23266079/119266302-87cc8100-bbea-11eb-813c-137708a80d63.png)

Toggler on:
The first blue one are my stats without my jewelry.

The seconnd blue are with 2 Curative jewelry and the willpower and healpower got converted right into int/magic power.

![2](https://user-images.githubusercontent.com/23266079/119266635-e1817b00-bbeb-11eb-9f42-0d398bed57c1.png)

**IT WORKS AS INTENDED!**

**Comment by jusva321** [comment] 2021-05-23 17:32
this is not about toggle on and off if you put a int item on with it toggled off it will give you int not willpower

**Comment by jusva321** [comment] 2021-05-23 17:33
if you put a magic power item on it dont give heal power ... yes it change some stats when you toggle on and off but it is not the right amount

**Comment by jusva321** [comment] 2021-05-23 17:36
both screenshots i got harbringer off doom toggled off only thing i change it to put on int item and it dont give me willpower 
![11](https://user-images.githubusercontent.com/72552430/119270681-31693d80-bbfe-11eb-9768-fb725df8c77a.png)
![22](https://user-images.githubusercontent.com/72552430/119270682-3201d400-bbfe-11eb-8dca-198cace746d5.png)

**Comment by jusva321** [comment] 2021-05-23 17:37
it give me int i hope you can see this but if it is anothere IT WORKS AS INTENDED! i give up :) but thx for doing all this

**Comment by jusva321** [comment] 2021-05-23 17:39
![33](https://user-images.githubusercontent.com/72552430/119270764-82793180-bbfe-11eb-985c-2fe23b308653.png)


this is the item i change

**Comment by jusva321** [comment] 2021-05-23 17:39
realy hope you can see it give me int with it toggled off and not willpower

**Comment by jusva321** [comment] 2021-05-23 17:40
it shoud not matter if i use half int half willpower gear it shoud be converted

**Comment by jusva321** [comment] 2021-05-23 17:52
nvm i got it wrong :) just have to toggle off and on to make it work sorry :)

**Comment by xpander69** [comment] 2021-05-27 10:36
you had another bugreport about same thing
closing duplicate: https://github.com/WarEmu/WarBugs/issues/19005

**Closed by xpander69** 2021-05-27 10:36 UTC
