### ISSUE TITLE
Misled quest bug

### ISSUE THREAD

**Issue by MasenderBR** [WarEmu/WarBugs#11841] opened 2018-06-04 23:12 UTC
In Norsca there is a quest where you help a deserter in some missions. In one of the missions given by him, we have to destroy a Talisman in the Altar of Corruption, the Talisman is suposed to be in the Quest Items section of the inventory, but it is never given to us. The Altar is also not clickable.
![20180604201018_1](https://user-images.githubusercontent.com/39930260/40946390-9073bbc4-6833-11e8-82d6-e7c045493d05.jpg)

**Comment by sioding** [comment] 2018-06-05 06:41
Duplicate of #10827

**Closed by sioding** 2018-06-05 06:41 UTC
