### ISSUE TITLE
All The King's Men PQ Broken

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18942] opened 2021-05-04 16:58 UTC
**Expected behavior and actual behavior:**

The All the King's Men PQ (level 40 Chaos Hard PQ) is stuck at stage 1 with 37/40 protectors killed, but no MOBs in the entire castle or area to make it progress.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2021-05-13 13:40
Duplicate of #18794

**Closed by Lheana** 2021-05-13 13:40 UTC
