### ISSUE TITLE
Can'[t move

### ISSUE THREAD

**Issue by Ladylissa** [WarEmu/WarBugs#10689] opened 2017-10-27 19:28 UTC
Trokkir and myself were in Talabec Dam Scenario and after we died we could not move, or do anything. We couldn't even quit the scenario. Trokkir was knocked down after he was dead also. 
![smoke_013](https://user-images.githubusercontent.com/33042601/32121652-75fa8a30-bb2b-11e7-9284-1f4b18556f85.jpg)
Sorry to bother you guys again.

**Comment by Ladylissa** [comment] 2017-10-27 19:32
Even after the scenario I had to completely exit the game and reenter to move or do anything. Again, sorry to be a bother.

**Comment by Lokenoth** [comment] 2017-10-27 19:40
# #10682  Same issue

**Comment by Ladylissa** [comment] 2017-10-27 19:56
After the scenario all of my quests disappeared from the tracker and my book. Screenshot attached. 
![smoke_016](https://user-images.githubusercontent.com/33042601/32122682-35b5a4b0-bb2f-11e7-9a1c-be9821877a18.jpg)
![smoke_017](https://user-images.githubusercontent.com/33042601/32122691-3baa0a3c-bb2f-11e7-8614-c8837836aaf6.jpg)

The second picture is after I completely logged completely out and even restarted my computer. Please help.

**Comment by Ladylissa** [comment] 2017-10-28 01:16
Smoke is an alt.  under Ladylisa.

**Comment by sioding** [comment] 2017-10-29 18:14
Duplicate of #10682

**Closed by sioding** 2017-10-29 18:14 UTC
