### ISSUE TITLE
Chapter 14 Order side "sacrifice" Talabecland no basic reward for influence in war diary

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9995] opened 2017-07-20 12:18 UTC
Chapter 14 Order side "sacrifice" Talabecland no basic reward for influence in war diary

advanced and elite works fine.

The reward should be the choice between 2 potions

categories : database, item, Tok

**Comment by Lheana** [comment] 2020-02-20 20:33
Duplicate of #7252

**Closed by Lheana** 2020-02-20 20:33 UTC
Labels: Database, Item
