### ISSUE TITLE
Leaving Scenario Freeze Bug

### ISSUE THREAD

**Issue by conan1977** [WarEmu/WarBugs#19317] opened 2021-07-14 03:25 UTC
I left a scenario and the score list permanently stayed on my screen.  I waited several minutes and nothing happened-the game froze.  I had to cancel the game through task manager and reload it.  This has happened on multiple occasions.

**Comment by lilimx** [comment] 2021-07-14 07:20
Hey,

can you bring a bit more information, so we have a chance to reproduce it. (SC names, win/lose, any abnormalities)
Also please check your install, try the repair function and check your addons.

**Comment by xpander69** [comment] 2021-07-14 17:31
system specs. amount of VRAM and RAM of  would be good info to have also..
you can try with Lilim suggested and on top of that..clearing the cache folder from your RoR folder, trying from Other drive if you have, maybe tour HDD/SSD is starting to go etc... can be multiple reasons

**Comment by lilimx** [comment] 2021-07-28 08:24
Hey,

Im closing this ticke now due to no feedback.

**Closed by lilimx** 2021-07-28 08:24 UTC
Labels: 2 Week Ultimatum, Confirmation Request
