### ISSUE TITLE
(fighting chance) engineer tactic

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#6469] opened 2016-05-26 13:07 UTC
the  engineer tactic (fighting chance) provide +120 strenght + 120 weapon skill + 120 ballistic skill.
BUT when you equip this tactic they **don't raise your parry chance** as he should do ( +120 weapon skill)

**Comment by ozarmidrashim** [comment] 2016-05-26 14:28
Visual, and effective dupe of #6196 . I won't fix it for the same reason I gave in that report. Parry chance increases on the server.

**Comment by Evildoor** [comment] 2016-05-26 15:29
Duplicate, closing.

**Closed by Evildoor** 2016-05-26 15:29 UTC
Labels: Visual
