### ISSUE TITLE
[SH] Run Away Ability is Bugged

### ISSUE THREAD

**Issue by Knowthyourself** [WarEmu/WarBugs#11694] opened 2018-04-29 21:41 UTC
Run Away is an ability taken from Squig Herder's Quick Shooting tree which gives you a speed boost with the condition of having an active pet normally. However, you can keep using it at the moment after loosing your pet. SO I think it is bugged. 

Here is a link for the video I recorded as an evidence
https://youtu.be/GUzdtUnxAhc

Character name: Nomore

**Comment by sioding** [comment] 2018-04-30 03:52
Duplicate of #9252

**Closed by sioding** 2018-04-30 03:52 UTC
