### ISSUE TITLE
scenario and warband health bar glitches

### ISSUE THREAD

**Issue by twiztidkill** [WarEmu/WarBugs#840] opened 2015-06-24 22:35 UTC
scenario party function will not show entire group(witch makes it difficult for healers) and also while in a war band the health bar is displayed as either distant or dead,.( also makes it difficult to heal a group.)

**Comment by xyeppp** [comment] 2015-06-24 22:38
Sometimes the warband UI also disappears completely and doesn't display anyone, even though the WB is there.

**Comment by Alteren** [comment] 2015-06-25 00:04
I can confirm the same thing as the above 2 comments

**Comment by Jestus** [comment] 2015-08-19 01:08
What does the "Unable to Implement Correctly"/"Cannot Fix Yet" label mean? Is it hard coded or something? Obviously it's still a thing as it still occurs in game, but I'm just curious how difficult this issue is to resolve. It makes healing a bit hard, is all.

**Comment by xyeppp** [comment] 2015-08-19 01:26
It - most likely - means the inability to do it yet without knowing what the root cause of the issue is, or some obscure piece of packet information that is not yet known.

**Comment by ozarmidrashim** [comment] 2015-08-19 10:21
xyeppp is correct.

**Comment by Lindisfarne** [comment] 2015-09-02 12:00
I have found that scenario parties bug when one of the party's (usually party 1) gets full and other people join the full party, they will bug and no show up in party. If you fill another party, and then let party 1 get full everything works as it should

**Comment by Evildoor** [comment] 2015-10-05 12:24
In one of the patches fixes for warbands (out of scenario) were implemented. Scenario groups are unaffected for now, and still do not refresh correctly.
Problem mentioned by @xyeppp happened to me in scenarios several times, so far doing /reloadui helped.

**Comment by Evildoor** [comment] 2015-12-07 11:09
I'm closing this since warbands were fixed and health glitches in scenarios are better described here: #947.

**Closed by Evildoor** 2015-12-07 11:09 UTC
Labels: Cannot Fix Yet
