### ISSUE TITLE
Beastlord blockage..

### ISSUE THREAD

**Issue by Deadto0** [WarEmu/WarBugs#13762] opened 2019-03-31 00:56 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
Tried to damage the Wood Pikes
 SW with 110 range to shoot him through pikes.

**Screenshots/Videos or archive.org evidences:**

![Felimalorn_001](https://user-images.githubusercontent.com/48745875/55283302-f7010000-5314-11e9-98c8-95ed170b54dd.jpg)

**Comment by dalen** [comment] 2019-03-31 01:58
same as https://github.com/WarEmu/WarBugs/issues/13753

**Comment by sioding** [comment] 2019-03-31 05:56
Duplicate of #13753

**Closed by sioding** 2019-03-31 05:56 UTC
