### ISSUE TITLE
[Empire Chapter 7] Influence Reward Missing 

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#14581] opened 2019-07-14 21:26 UTC
Demona Gaertner wants me to choose my reward, but theres none for "simple" 
![Katianka_000](https://user-images.githubusercontent.com/52664952/61189521-c9a34c80-a68e-11e9-88c0-ea51f9df5a3c.jpg)

**Comment by sioding** [comment] 2019-07-17 17:34
Duplicate of #12084

**Closed by sioding** 2019-07-17 17:34 UTC
