### ISSUE TITLE
Liniment of Boundless Sight not working on my MSH

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#16456] opened 2020-04-21 19:05 UTC
**Expected behavior and actual behavior:**
The 60 wounds buff of liniment of boundless sight is not applied on my MSH (Don't know if it works on other classes). The 60 initiative part still works. 
Tried it 3 times in different zones, never worked. 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![aaaaa](https://user-images.githubusercontent.com/16682919/79903591-a1adfa00-8413-11ea-8a90-c1667d8d9b1a.png)
![bbbbb](https://user-images.githubusercontent.com/16682919/79903631-af637f80-8413-11ea-9e94-1f5a1c179cf9.png)
![ccccc](https://user-images.githubusercontent.com/16682919/79903647-b68a8d80-8413-11ea-9a0d-8ac69e02ec36.png)

**Comment by Kaelang** [comment] 2020-04-21 19:10
I've just tested this on my DoK - the character sheet does not update with the increased Wound stat - however if you used .getstats before and after you apply the liniment you can see the increase there.

**Comment by RoR-Zomega** [comment] 2020-04-21 19:16
Squig Armour provides a wounds buff as well and generally ability buffs and potion buffs don't stack together.

Do get the bonus from the liniment when not in Squig Armour? If so then it looks like it's just that Squig Armour provides a bigger bonus than the liniment so the Squig Armour bonus is used instead.

**Comment by engharat** [comment] 2020-04-21 19:26
Squig Armour bonus stack with potions, or a MSH would be un-buffable by anything with its squig armour str/wounds/tough bonus :)
Instead, str/tough potions work, and I tried also another liniment which correctly buffed my wounds. 
Kaelang is right, .getstats correctly report the right wounds value after liniment. it is weird that only that liniment has that paperdoll bug.

**Comment by Kaelang** [comment] 2020-04-21 19:29
Confirmed that the liniment is working as intended - so going to go ahead and close this. The visual update on the character sheet is a known issue. 

Cheers.

**Closed by Kaelang** 2020-04-21 19:29 UTC
Labels: 2 Week Ultimatum, Confirmation Request
