### ISSUE TITLE
Magus Mout it does not work.

### ISSUE THREAD

**Issue by schokoladenman** [WarEmu/WarBugs#12523] opened 2018-10-31 22:15 UTC
Hi . At moment i have problem can´t use my Magus Mout.
I buy the 60% today use in city and camp and go RvR.
But in the center of RvR country and in Sc i can´t use again.

Before i go RvR, i can use "ride" in , and after it does not work.
My Magus are Rang 38, so i dont know why .

Maybe Event, mabye its only by Magus.

I Hope she can fix problem.

Thx and good Day

greeting

**Comment by sioding** [comment] 2018-11-01 07:35
Duplicate of #12184

**Closed by sioding** 2018-11-01 07:35 UTC
