### ISSUE TITLE
Greenskin Tier 3 Influence 1 reward Chosen.

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#4216] opened 2016-02-02 22:59 UTC
![lokenoth_002](https://cloud.githubusercontent.com/assets/17035321/12767579/ecab2aee-ca01-11e5-900a-526163f95a38.jpg)
The Ring I was wearing and received from the Greenskin Tier 3 Influence reward become a Blackguard specific ring. Any help?

**Comment by Styrkarr** [comment] 2016-02-02 23:36
The Chosen ring is "Thickmuck Chaos seal". "Dark Band" is for BG. It was a bug which was fixed with the last patch.

Ask a GM to change this item with the real Chosen one.

**Comment by Evildoor** [comment] 2016-02-03 05:33
Not a bug, but collateral damage caused by bug fixing. Closing.

**Closed by Evildoor** 2016-02-03 05:33 UTC
