### ISSUE TITLE
Magus mastery ability Tzeentch's Firestorm rvr bug

### ISSUE THREAD

**Issue by CyphDK** [WarEmu/WarBugs#16465] opened 2020-04-22 16:59 UTC
I am currently combat rank 26 and renown rank 26 and picked the skill Tzeentch's Firestorm from the Path of Changing, when in a pve area the skill can fire normally, but whenever inside an rvr lake the skill will not cast.
I do not have recording software on my computer so I cannot record this happening.
Several relogs, mastery respecializing and going in and out of the rvr lakes do not solve this issue.

**Comment by Kaelang** [comment] 2020-04-22 17:01
Duplicate of https://github.com/WarEmu/WarBugs/issues/15941.

**Closed by Kaelang** 2020-04-22 17:01 UTC
