### ISSUE TITLE
Sticky feetzs/Motm

### ISSUE THREAD

**Issue by Vdovics** [WarEmu/WarBugs#9525] opened 2017-04-28 18:59 UTC
My last post was closed by Londo with link to old patch notes which doesnt explain, why Sticky feetz/Motm radius is only 5ft insted of at least 20ft. Issue is that current state of skill slows for about 2 seconds in so small radius that doesnt even worth mastery point. This particular skill is what define Shammy and AM cc abbility. We have tested it today again and here is what we have found. 
Test 1: https://youtu.be/7O6xrRdeOww
Test 2: https://youtu.be/UUNt9phbqzE
And another video shows how properly skill should work(4:32, 5:00): https://www.youtube.com/watch?v=iNARqOj ... u.be&t=272

**Comment by Symbelmyne** [comment] 2017-04-28 19:39
The 3rd link to WAR live shammy fight using sticky feetz to kite slayer at 4.32:
https://www.youtube.com/watch?v=iNARqOjsfiA&feature=youtu.be&t=272
Clearly snare proc starts the moment slayer touches edge of puddle, in opposite to RoR version, when snare proc starts when char is in a middle of puddle.

**Comment by Luth-RoR** [comment] 2017-04-28 19:53
The last report wasn't closed by Londo, it was closed by me

**Comment by Luth-RoR** [comment] 2017-04-28 20:11
The last post wasn't closed by Londo, it was closed by me: https://github.com/WarEmu/WarBugs/issues/9518

>With the aid of Londo's analysis of the client's ability tables, we have determined the true nature of the AoE radius check in Warhammer, and Return of Reckoning's version is too wide.

From the already linked patch notes: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17634&p=191833
The data was obviously taken by decoding the client, which is data that is based on facts. On the other side it's well known that a characters position that is shown on the client doesn't have to be necessarily the position where he actually is. 
The patchnotes state very clearly that the AoE radii correction was intended and why it was intended by the developers.
The forum is the place to discuss abilities etc, the bugtracker is the place for discussing bugs on RoR.

**Closed by Luth-RoR** 2017-04-28 20:11 UTC
