### ISSUE TITLE
Unlimited Magical Salvaging bug

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#11219] opened 2018-01-26 17:10 UTC
My R30 Magus is Level 137 in Magical Salvaging. When he salvages the following items, I get the fragments/Essences/gold, but the items don't disappear. So I can basically salvage them again and again.

FRENZIED CHOPPA - Item Level 29
OUTLAW'S STOMPAS - Item Level 31

![outlawsstompas](https://user-images.githubusercontent.com/13045932/35451613-1b30ac02-02c4-11e8-82a7-f6425979fb85.PNG)
![frenziedchoppa](https://user-images.githubusercontent.com/13045932/35451618-1e2eb494-02c4-11e8-8e04-faff3f452bb7.PNG)

p.s. I just tried to move these 2 items to another part of my bag and it said in Chat, "Item move failed: attempted to move 1 of the item Frenzied Choppa while only having 0."

**Comment by sioding** [comment] 2018-05-21 13:20
Duplicate of #1278

**Closed by sioding** 2018-05-21 13:20 UTC
Labels: Crafting
