### ISSUE TITLE
fort issues

### ISSUE THREAD

**Issue by Kalalilon** [WarEmu/WarBugs#16700] opened 2020-05-06 23:58 UTC
i joined a fort on my 30 RP today and i got the following message and didn't get any renown or exp for locking/defending. the same thing happened yesterday on my 32 swordmaster. i got no renown for killing the lord in a warband.
![Wts_002](https://user-images.githubusercontent.com/64934538/81239875-f8026780-8fd3-11ea-8bf8-30f0b65a3f5f.jpg)

**Comment by Kaelang** [comment] 2020-05-07 00:01
Duplicate of https://github.com/WarEmu/WarBugs/issues/16409.

**Closed by Kaelang** 2020-05-07 00:01 UTC
