### ISSUE TITLE
[Influece] High Pass. Grizela Hirtzel.

### ISSUE THREAD

**Issue by axisd** [WarEmu/WarBugs#13895] opened 2019-04-16 09:26 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
when receiving all rewards, the quest mark is not turned off

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
![Sundread_014](https://user-images.githubusercontent.com/2901788/56198019-b9a1af80-6042-11e9-8670-e69834d574db.jpg)

**Comment by sioding** [comment] 2019-04-17 19:00
Duplicate of #10001

**Closed by sioding** 2019-04-17 19:00 UTC
