### ISSUE TITLE
[Scenario] Black crag Keep - Flags missing

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12727] opened 2018-11-26 18:05 UTC
No Flags to tap, flags on minimap are  greyed out. Sc can only be ended through kills or timer

![drengur_013](https://user-images.githubusercontent.com/40274248/49032905-1690ec00-f1ae-11e8-9632-6d5f5188ec38.jpg)

**Comment by sioding** [comment] 2018-11-27 16:36
Duplicate of #12722

**Closed by sioding** 2018-11-27 16:36 UTC
Labels: Scenarios
