### ISSUE TITLE
Norland travel bug

### ISSUE THREAD

**Issue by Dra3gm** [WarEmu/WarBugs#10980] opened 2017-12-10 14:29 UTC
Soo today i wanted to travel with my chosen character from highpass to nordland
I went to flight master selected norland pressed and in the loading screen the game closed
I tried to open the game 2-3 times and when i finally did it i was in norland transformed into a chicken and this is the second time happening.
![drageen_001](https://user-images.githubusercontent.com/34137217/33805804-40b21244-ddc7-11e7-8722-740ac275bb3e.jpg)
![drageen_002](https://user-images.githubusercontent.com/34137217/33805806-478e80e8-ddc7-11e7-9365-722943d8225e.jpg)

**Comment by sioding** [comment] 2017-12-10 15:18
Duplicate of #10794

**Closed by sioding** 2017-12-10 15:18 UTC
