### ISSUE TITLE
"You are dead" after ressing in Scenario

### ISSUE THREAD

**Issue by Panzarpaddan** [WarEmu/WarBugs#15015] opened 2019-10-08 15:27 UTC
**Expected behavior and actual behavior:**
You take the ress and play the game.
I ressurected from the timed ress in a scenario while a channeled ability was still targeting me.
So when I ressurected I couldnt move or cast any spells.

**Steps to reproduce the problem:**
Die from a channeled ability, in my case Focus Fire from Engineer then ressurect with the timed scenario ress before it finishes.

**Testing Screenshots/Videos/Evidences (always needed):**
https://imgur.com/a/8yAhko4

**Comment by sioding** [comment] 2019-10-08 17:12
Duplicate of #11407

**Closed by sioding** 2019-10-08 17:12 UTC
