### ISSUE TITLE
efficient slaughter tactic visual bug

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11586] opened 2018-04-11 17:39 UTC
hello i saw there are 2 thread's from this 1 from 2016(open) 2017(closed<fixed>) so i asked a gm if it helped to posted it and he said sure so here it goes.

the tactic seems to have visual bug with almost all of the hate skills

all of the blackguard skills down below:

shield of rage:
![nighteyes_583](https://user-images.githubusercontent.com/16551075/38632635-ffae655e-3dc5-11e8-96c9-bccb79d0d839.jpg)
![nighteyes_584](https://user-images.githubusercontent.com/16551075/38632637-01d41644-3dc6-11e8-9d97-17405cd648a3.jpg)
bolstering anger:
![nighteyes_585](https://user-images.githubusercontent.com/16551075/38632748-4dc4762a-3dc6-11e8-9899-effc9df658a1.jpg)
![nighteyes_586](https://user-images.githubusercontent.com/16551075/38632753-4f618e8c-3dc6-11e8-9179-e4c797279099.jpg)
driven by hate:
![nighteyes_587](https://user-images.githubusercontent.com/16551075/38632822-85ca3302-3dc6-11e8-9fee-b5dba325c9c2.jpg)
![nighteyes_588](https://user-images.githubusercontent.com/16551075/38632824-878b9348-3dc6-11e8-9dee-9b3aa71ab48a.jpg)
furious howl:
![nighteyes_589](https://user-images.githubusercontent.com/16551075/38632903-c3c63d86-3dc6-11e8-953d-1ef21738fce4.jpg)
![nighteyes_590](https://user-images.githubusercontent.com/16551075/38632904-c401ab14-3dc6-11e8-8e7c-70f504bb5076.jpg)
pitiless strike:
![nighteyes_591](https://user-images.githubusercontent.com/16551075/38632977-f2dd4290-3dc6-11e8-8e9d-dd30522dbfae.jpg)
![nighteyes_592](https://user-images.githubusercontent.com/16551075/38632982-f5f06c6e-3dc6-11e8-9f47-12b9ff33fdff.jpg)
chocking fury:
![nighteyes_597](https://user-images.githubusercontent.com/16551075/38633085-435e5c18-3dc7-11e8-8246-4537ad084360.jpg)
![nighteyes_598](https://user-images.githubusercontent.com/16551075/38633094-48014de8-3dc7-11e8-8c0b-66f07b066866.jpg)
monstrous rending:
![nighteyes_599](https://user-images.githubusercontent.com/16551075/38633234-ae0cc612-3dc7-11e8-9f3c-825a78321c18.jpg)
![nighteyes_600](https://user-images.githubusercontent.com/16551075/38633235-ae7129f4-3dc7-11e8-960e-92f9e11f3019.jpg)

**Comment by sioding** [comment] 2018-04-11 18:00
Duplicate of #7466

**Closed by sioding** 2018-04-11 18:00 UTC
