### ISSUE TITLE
[Item] Ravack's shroud

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6587] opened 2016-06-01 05:28 UTC
This item has chaos only as requirement. Is it supossed to have that?
![ravack s shroud](https://cloud.githubusercontent.com/assets/19287032/15699060/6e4d1ca8-27ca-11e6-9705-495d9cd02c83.png)

**Comment by Ryanfawkez** [comment] 2016-06-01 11:02
As weird as it seems, all Ravack cloaks have stats aimed towards a specific archetype within its own racial restriction. This would be the Marauder cloak, but it can just as easily be used by a Chosen.

**Comment by stillwaterww** [comment] 2016-06-01 11:14
Ah well  that's crappy, was looking forward to equipping it on my WE when she dinged r36, only to find out about that chaos restriction >.<

**Comment by Evildoor** [comment] 2016-06-01 15:27
Closing as not a bug.

**Closed by Evildoor** 2016-06-01 15:27 UTC
