### ISSUE TITLE
Problem with an item in the set Invader for Slayer

### ISSUE THREAD

**Issue by Screwgrim** [WarEmu/WarBugs#15122] opened 2019-11-10 23:06 UTC
I post this report for a guild member who has a problem with the helm of the Invader set for his slayer.
The bonus given by the helm is +3 intelligence and not +3 armour perforation as indicated.
Could you look at for this problem thank you?
The player who has the problem is "Derniersoupir" from the FUREUR Guild.

Thank you a lot

**Comment by Kabucoror** [comment] 2019-11-11 19:54
Duplicate of #14970

**Closed by Kabucoror** 2019-11-11 19:54 UTC
