### ISSUE TITLE
Pounces seem to override Champion's Challenge

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#19331] opened 2021-07-19 12:28 UTC
Possible related issue https://github.com/WarEmu/WarBugs/issues/9872
**Expected behavior:**
Champion's Challenge (ChCh) should root the enemy in place and disable all movement.

**Actual behavior:**
Using pounce like abilities still work while in ChCh.

**Steps to reproduce the problem:**
Gain M1 on any tank, ChCh e.g. a WE that enters stealth, and she can still pounce out.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=wApqBEFCVU4

**Comment by lilimx** [comment] 2021-07-20 19:55
Hey,

so we did a few tests and that's the result:
Only the WE ability "Shadow Leap" and the SM M1 "Wings of Haeven" are able to leave the Champion's Challenge. But even when you pounced out, you are still rooted on the landing spot.

- SH pounce and
- WL pounce working as intended

**Comment by lilimx** [comment] 2021-07-22 19:17
Fixed with Patch 22/07/2021

**Closed by lilimx** 2021-07-22 19:17 UTC
Labels: Ability, Fix Pending
