### ISSUE TITLE
Capitol Bug

### ISSUE THREAD

**Issue by Jeliel80** [WarEmu/WarBugs#14747] opened 2019-08-10 08:59 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Jeliel80** [comment] 2019-08-10 09:00
Looks like capitol bug is back, can't log in in Altdorf, had to double /stuck on loading screen to get in and can't teleport back to Altdorf in any way possible, nor scroll, book and flight.
Take care.

**Comment by Sigbertus** [comment] 2019-08-10 09:09
got the same problem now

**Comment by pobratim** [comment] 2019-08-10 10:01
Got the same problem.All my character are in Capital.So i cant log in.

**Comment by Jeliel80** [comment] 2019-08-10 10:09
well, if you type two times /stuck on loading screen, you can login, getting teleported to nordland, but still...

**Comment by pobratim** [comment] 2019-08-10 10:10
Thank you

сб, 10 авг. 2019 г., 19:09 Jeliel80 notifications@github.com:

**Comment by sioding** [comment] 2019-08-10 11:42
Duplicate of #14746

**Closed by sioding** 2019-08-10 11:42 UTC
