### ISSUE TITLE
Wild Healing does not affect Funnel Essence

### ISSUE THREAD

**Issue by CeridianX** [WarEmu/WarBugs#2002] opened 2015-11-27 08:37 UTC
Wild Healing tactic should also lower the AP cost of Funnel Essence healing skill (Isha tree). That's how it was working on live server at least. At the moment it's not the case.

**Comment by ozarmidrashim** [comment] 2015-11-29 12:28
The tooltip disagrees with you.

**Comment by CeridianX** [comment] 2015-11-29 12:43
I remember when on live server each tick of Funnel Essence cost 13AP (instead of 20) when Wild Healing was triggered. Besides Funnel Essence is a healing ability as per WH tooltip.

**Comment by ozarmidrashim** [comment] 2015-11-29 14:02
Wild Healing reduces costs of heals by 50%. I'm not convinced.

**Comment by CeridianX** [comment] 2015-11-29 14:30
That's ok. Let's leave it there.

**Comment by ozarmidrashim** [comment] 2015-11-29 20:16
Will check.

**Comment by Joiec** [comment] 2015-12-03 11:22
Didnt pay attention to this, as i thought it will get fixed soon. Just saw that it has moved to dubios. I am 100% sure funnel essence was affected by WH and CeridianX is right about it.

"Whenever you critically heal someone, your healing abilities will cost 50% less action points for 10 seconds." despite been a channel heal, Funnel Essence is still an healing Ability.

**Comment by Evildoor** [comment] 2016-04-07 11:18
I suppose that this can be closed as not a bug.

**Closed by Evildoor** 2016-04-07 11:18 UTC
Labels: Ability, Dubious
