### ISSUE TITLE
No Cooldown on Cooldown Skills

### ISSUE THREAD

**Issue by Hermann12345** [WarEmu/WarBugs#10643] opened 2017-10-20 12:05 UTC
Zone: Caledor
PQ: The Fortress of Caledor
Bug: No Cooldown on Cooldown Skills.
set def target and be infight. On the bridge and in the Fortress you can quite often cast all sorts of skills without cooldown as long as Actionpoints or Classpoints are enough to spam. After APs are empty the natural cooldown on skills are normal again. Showed the bug to Gambero.
Account: Hermann
Character: Felliz
Class: Disciple of Khaine

**Comment by sioding** [comment] 2017-10-20 12:12
Duplicate of #10642

**Closed by sioding** 2017-10-20 12:12 UTC
