### ISSUE TITLE
Mounting while walking backwards

### ISSUE THREAD

**Issue by Darkshadov** [WarEmu/WarBugs#16253] opened 2020-04-05 19:48 UTC
**Expected behavior and actual behavior:**

Currently you can walk backwards while mounting and still get mounted.
When running forward and mounting it gets cancelled.
Expected behaviour should be that you have to stand still and not move your character to get mounted.

**Steps to reproduce the problem:**

Walk backwards, press button to mount.
Or: Press button to mount, hold down key to walk backwards.

**Comment by Lheana** [comment] 2020-04-05 20:11
Duplicate of #16136

**Closed by Lheana** 2020-04-05 20:11 UTC
