### ISSUE TITLE
Khaine's Refreshment

### ISSUE THREAD

**Issue by korwrath** [WarEmu/WarBugs#11793] opened 2018-05-22 05:09 UTC
The DoK ability 'Khaine's Refreshment' fails to work on my DoK 'Telalis'.  I noted the problem a week ago, but thought it was just a bug that would require a server reboot/restart, so I didn't really think it was a pressing issue.  Later on had my Chosen on soloing in rvr and had other doks apparently able to cast it with no issues.  Tonight I logged on my DoK and was healing someone in my alliance in pve and the spell would not work.  The character does the casting animation, but the casting bar does not decrease, soul pool remains where it is before the spell was cast and nobody, caster included, gets no healing from the spell/ability

**Comment by sioding** [comment] 2018-05-22 05:33
Duplicate of #11741

**Closed by sioding** 2018-05-22 05:33 UTC

**Comment by sioding** [comment] 2018-05-22 05:39
Would be great if you can add testing screens to the report: https://github.com/WarEmu/WarBugs/issues/11741
