### ISSUE TITLE
[Squig Herder] Squig can attack non rvr-flagged players

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1077] opened 2015-08-12 15:29 UTC

**Comment by magter3001** [comment] 2015-08-13 16:19
Also turrets, daemons, and lion pet can attack non flagged players. Know issue for months now if not more.

**Comment by xyeppp** [comment] 2015-08-14 12:50
Duplicate of https://github.com/WarEmu/WarBugs/issues/919

**Comment by milosxe** [comment] 2015-09-21 19:03
Closing since it's a duplicate.

**Closed by milosxe** 2015-09-21 19:03 UTC
