### ISSUE TITLE
Raven Host Vanguard PQ Spawning more them one champion.

### ISSUE THREAD

**Issue by GilbertBeilschmid** [WarEmu/WarBugs#10686] opened 2017-10-27 05:36 UTC
The Raven Host Vanguard PQ in the Empire starting area is spawning more then one Champion, Argog the Unstoppable. They kill the Priest you are suppose to protect in the second part in under a couple seconds and cause the PQ to fail without chance of low level players being able to kill the champions fast enough. 
![tiimmo_000](https://user-images.githubusercontent.com/32606500/32089296-027deeb8-ba9e-11e7-9504-90870f692fa4.jpg)

**Comment by Lheana** [comment] 2017-11-08 19:00
In fact Argog the Unstoppable will spawn (a constant spawn) if second stage fails. Afaik the second stage uses script, and I think it may be related to this.

**Comment by Lheana** [comment] 2017-12-21 15:30
Tried to reproduce the bug, I could not. Would need confirmation this bug still happens or not.

**Comment by Hargrim** [comment] 2018-01-03 13:37
I tried too and it looks like it doesn't.

**Comment by sioding** [comment] 2018-01-22 10:18
#11124
The report abouve mentioned that Father Sigwald should be a champion. That would help to reduce the chance that stage 2 fails that fast. I can´t find any evidence for it - and so the OP also doesn´t bring any in.

**Comment by Duckgrrl** [comment] 2018-02-12 20:05
The doubling of Argog seemed to stop a couple patches ago (or at least within 1-2 weeks ago), but Father Sigwald still dies unreasonably fast unless 2-3 players are already crowded around him waiting to take the aggro from him.  This should probably go under a new bug ticket.

**Comment by sioding** [comment] 2018-04-18 18:38
Also this is fixed now,

**Closed by sioding** 2018-04-18 18:38 UTC
Labels: NPC, Public Quests
