### ISSUE TITLE
Guild Heraldry - Wrong emblem displayed

### ISSUE THREAD

**Issue by LordMort** [WarEmu/WarBugs#7776] opened 2016-09-15 15:57 UTC
RoR Server: Martyrs Square Version
1.4.8 Build 573

Hi there!

I have the following issue with the emblem on our guild's heraldry:
After having initially set up the heraldry to be reserved,
![gottrekson_123](https://cloud.githubusercontent.com/assets/21020953/18556830/eef79a5e-7b6c-11e6-8482-65ebfe70dff3.jpg)

I clicked on the save button.
When looking at the heraldry afterwards, I see the following:
![gottrekson_147](https://cloud.githubusercontent.com/assets/21020953/18556780/c22659e8-7b6c-11e6-887d-435c9071593e.jpg)
Apparently the emblem is not being remebered correctly.
This is being confirmed when looking into the heraldry reservation / change screen:
![gottrekson_149](https://cloud.githubusercontent.com/assets/21020953/18556926/3a764ff2-7b6d-11e6-8c73-340e5d5bd559.jpg)
The selected shape and pattern are being remembered, but the emblem has been reset to the value "1".

I have already tried whether or not it is possible to correct this by changing the emblem through the option of paying the fee for changing it (having enough gold to be able to pay the 10G needed for the 1st change). This did not solve this issue neither.

Any help on getting the emblem selection to be remembered correctly is appreciated.

*UPDATE*
Before having opened this issue, I have looked whether or not it is similar to either one of these four:
#6149
#4409
#5545
#5369
Neither one of these appears to be a good match.

**Comment by Luth-RoR** [comment] 2016-09-15 16:04
It's not a bug: at guild rank 10 you can choose the shape and the background heraldry, but you need guild rank 20 for the guild symbol. 
Until then only an ugly basic symbol will be shown.

**Comment by LordMort** [comment] 2016-09-15 16:07
Hi Luth,

Thanks for your reply.

Just to verify:
can the emblem be reserved at level 10, or is it only possible to do that at level 20?

**Comment by Luth-RoR** [comment] 2016-09-15 16:29
The _guild emblem reservation_ feature high likely doesn't work yet.
I'm trying to get some more info how it's handled atm.

**Comment by LordMort** [comment] 2016-09-15 16:46
Hi Luth,
Hi nalgol,

Thanks for your response.
In case you need any information from my side, I'll try and get it a.s.a.p..

**Comment by nalgol** [comment] 2016-09-15 18:24
emblem reservation works from lvl 10 on at 20 your emblem will show the right pattern
(at least it did when coded it like 1 year ago ^^ )

**Comment by Luth-RoR** [comment] 2016-09-15 18:47
Ok, closing it then. Thanks for clarification.

**Comment by LordMort** [comment] 2016-09-15 18:48
Hi nalgol,

Thanks for your reply.

I can confirm that my guild and I were able to start reservation for the guild heraldy upon reaching guild rank 10. I also understand that the the emblem chosen at rank 10 will only be displayed upon reaching guild rank 20.

What I am wondering is this:
How is the chosen emblem "remembered" / stored?
The reason for this is that the Heraldry Editor, see also the 1st and the 2nd screenshot in my original post above, "seems" to forget the emblem chosen. By "this I mean that even in the Heraldry Editor I am unable to see the choice having been made for the emblem.

Could you tell me whether or not the following assumption is correct:
Though an emblem for the guild heraldry is chosen at guild rank 10, this emblem is only shown anywhere (!) until the guild reaches rank 20.
The "shown anywhere" is meant to mean that the emblem chosen is stored in the DB from rank 10 on, but that any part of the client interprets this as the default value until rank 20.

**Closed by Luth-RoR** 2016-09-15 18:47 UTC
Labels: Confirmation Request

**Comment by nalgol** [comment] 2016-09-15 19:08
since its very hard to find actual packets for this the server has it coded like if guild lvl below 20 send emblem 1 this this affect the heraldry selector as well

**Comment by LordMort** [comment] 2016-09-15 19:12
Hi nalgol,

Thanks for your reply.
Now it makes perfetct sense to me.

Thank you for the clarification :)
