### ISSUE TITLE
[Quest] Return Fire -Empire Starting Zone-

### ISSUE THREAD

**Issue by Finklyby** [WarEmu/WarBugs#18769] opened 2021-04-04 09:20 UTC
**Expected behavior and actual behavior:**

Expected : Destroying hellcanons using the nearby empire cannons should advance the quest
Actual : Destroying the hellcanons directly or with cannons do not update the quest

**Steps to reproduce the problem:**

Create a new character on order side, advance through the first few quests until reaching "Return Fire", try destroying the hellcanons.

**Comment by Pixelated-Dom** [comment] 2021-04-04 21:33
Can confirm this is replicable - just rolled an empire character and tried all 3 Order cannons and even going up and hitting the hellcannons myself, no options seem to currently advance the credit for this quest.

**Comment by Favestus** [comment] 2021-04-07 10:12
Same for me, i don't know what cause the issue

**Comment by Kythas01** [comment] 2021-04-11 20:52
The Hellcannons also used to destroy in 1-2 shots. Now they are Level 10, and take a out 10 shots to destroy 1.

**Comment by Autodlak** [comment] 2021-04-13 15:27
Some news about this quest? I can't go further in questline.
I thought the issue is cause someone dmg these cannons and thats why quest doesn't update. But I can't proof this.

**Comment by Rodulv** [comment] 2021-04-16 00:01
Order Quest: Return Fire Chapter 1 is still bugged. Taking 10+ shots to take a Hellcannon down and it still doesn't complete the quest 0/2 Destroyed Hellcannons.

**Comment by MaxHayman** [comment] 2021-04-22 15:13
Seems to be working for me on our development enviorment.

**Comment by Fellipe92** [comment] 2021-04-22 22:40
Just tested the quest again, it is not fixed in live server, the cannons can be killed but they are not counted as completed in the quest journal.

**Comment by jandro199** [comment] 2021-04-23 09:47
I have Created a new character and the task is not working, you can´t complete the task

**Comment by Lazerez** [comment] 2021-04-24 20:47
I ran into this same issue today. I don't know if it the same issue, but the quest "Ignoble Weapons" on the Order side of the blighted isles seems to have same issue with the Reaper Bolt Thrower. They are much higher level than the other mobs in that area and when they are destroyed you don't get credit for them.

**Comment by Chknmasala** [comment] 2021-04-25 04:05
Yeah came to report  "Ignoble Weapons" not giving credit in High elf starting zone. The Reaper bolts are hard to kill and give no credit.

**Comment by sambonz** [comment] 2021-04-26 12:44
Confirmed on live - cannot complete the quest 'Return Fire'. The Hellcannons are L10 and when eventually destroyed they do not count towards the quest.
Cannot continue in the zone as further progress is dependent upon completion of Return Fire.
Is there a way to skip it with console commands or similar?

**Comment by GabbaMan** [comment] 2021-04-26 15:38
Unfortunatelly Quest doesn't work, I've tested it with 2 other random players.

**Comment by Kaliselia** [comment] 2021-04-27 20:59
Still having this issue with the quest not giving credit for destroyed cannons.  I have destroyed several and even tried to abandon the quest and trying again.

As above the Cannons are level 10 and require many shots to kill and when you do destroy one you do not get credit for it.

**Comment by Kaliselia** [comment] 2021-04-28 17:38
Oh and the same is happening to the High Elf quest to destroy the Reaper Bolt Throwers - I.E. Ignoble Weapons quest.

**Comment by MaxHayman** [comment] 2021-04-28 22:58
Good news guys. I spent some time debugging it and got a fix which will most likely go live in the morning.

**Comment by sambonz** [comment] 2021-04-29 02:42
> Good news guys. I spent some time debugging it and got a fix which will most likely go live in the morning.

Thank you so much! 🙏😊

**Comment by Fellipe92** [comment] 2021-04-29 02:54
> Good news guys. I spent some time debugging it and got a fix which will most likely go live in the morning.

By the Emperor! Sigmar bless you my friend! 🙏😊

**Comment by PixelMasterNZ** [comment] 2021-04-29 02:54
> Good news guys. I spent some time debugging it and got a fix which will most likely go live in the morning.

Thanks for that!

**Comment by Kaliselia** [comment] 2021-04-30 02:43
The fix is working though those cannons are still Level 10 Champions so taking over 20 shots to destroy one, but people can complete the quest how.
Thanks
    On Wednesday, April 28, 2021, 07:55:04 PM PDT, PixelMasterNZ ***@***.***> wrote:  
 
 



Good news guys. I spent some time debugging it and got a fix which will most likely go live in the morning.


Thanks for that!

**Comment by Kaliselia** [comment] 2021-04-30 02:44
Just got done doing the quest so the fix is working.  Though they are still level 10 Champion so it going to take quite a lot of shooting at them.

**Comment by Lheana** [comment] 2021-05-13 15:28
This has been fixed few patches ago.

**Closed by Lheana** 2021-05-13 15:28 UTC
Labels: Fix Pending, NPC, Quests, Sourcecode
