### ISSUE TITLE
Live Event-Keg End (engineer)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12908] opened 2018-12-22 16:50 UTC

**Comment by thorbolt80** [comment] 2018-12-22 16:51
![thorbolt_599](https://user-images.githubusercontent.com/16274785/50376761-2e735880-0612-11e9-957e-258fe04c7b52.jpg)

**Comment by sioding** [comment] 2018-12-22 16:56
Duplicate of #12895

**Closed by sioding** 2018-12-22 16:56 UTC
