### ISSUE TITLE
Auction mail causes the new mail icon to stay on the minimap until relogging

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15533] opened 2020-01-24 16:11 UTC
edit: character name is Zomega

**Expected behavior and actual behavior:**

Expected: once all unread mail items - both normal mail and auction mail - have been read, the new mail icon by the minimap should vanish.

Actual: this works for normal mail, but for auction mail even once I have read each mail, taken items and deleted mail the icon remains. Changing zone doesn't fix it and I don't believe /reloadui fixed it either. The only way I found to make it go away was to go back to character select once all the mails had been read/cleared and log back in.

This occurs consistantly on my account since the past week or so. No auction or mail addons are in use. I have since installed shinies in the past 24 hours and the behaviour has remained the same.

**Steps to reproduce the problem:**

Send me an auction mail?

**Testing Screenshots/Videos/Evidences (always needed):**

Because I'm an idiot I forgot to take a screenshot of the empty auction mail list. Here's me mousing over the icon in RvR after clearing out all of the mails. Something somewhere still thinks there's a mail outstanding.

![Zomega_009](https://user-images.githubusercontent.com/60266177/73084016-17adce00-3ec4-11ea-9c82-1044fca6b140.jpg)

**Comment by Lheana** [comment] 2020-01-24 18:21
Duplicate of #1109

**Closed by Lheana** 2020-01-24 18:21 UTC
