### ISSUE TITLE
Dying to get into Fangbreaka Swamp Keep

### ISSUE THREAD

**Issue by TheRealReginn** [WarEmu/WarBugs#2677] opened 2016-01-04 23:40 UTC
Not sure if this has been reported, but the front entrance to Fangbreaka Swamp Keep is bugged.  While trying to enter from the front, I get a loading screen that ends up with me falling through the world and dying.

**Comment by genisaurus** [comment] 2016-01-05 04:26
Could not reproduce on dev environment, may have been a problem with lag on live.

**Comment by saupreusse** [comment] 2016-01-05 10:02
max hayman already said it was his fault... should be fixed in next patch ;)

**Comment by Evildoor** [comment] 2016-01-18 12:31
Seems to be fixed.

**Closed by Evildoor** 2016-01-18 12:31 UTC
Labels: Could Not Reproduce, Dubious
