### ISSUE TITLE
SC Objectives not tracking position on map.

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16835] opened 2020-05-15 03:22 UTC
Moveable objectives do not track where the objective currently is correctly, or at all sometimes, or doesn't even show on map.

Currently tested SC's:

Howling Gorge
Phoenix Gate
Talabec Dam
![Dracula_091](https://user-images.githubusercontent.com/44329952/82008027-44335480-9631-11ea-99de-63e6c9d99c45.jpg)
![Dracula_090](https://user-images.githubusercontent.com/44329952/82008036-49909f00-9631-11ea-80d7-595c70cc8fa7.jpg)
![Dracula_089](https://user-images.githubusercontent.com/44329952/82008047-4f868000-9631-11ea-8527-15557b42578c.jpg)
![Dracula_088](https://user-images.githubusercontent.com/44329952/82008054-54e3ca80-9631-11ea-8b7a-6197b8cf5443.jpg)

**Comment by Xicoz** [comment] 2020-05-15 03:24
the howling gorge one btw, was like 5 seconds before they capped the obj

**Comment by Kaelang** [comment] 2020-05-15 12:25
![image](https://user-images.githubusercontent.com/60117106/82049894-13920000-96af-11ea-89cd-2aa3ce89638b.png)
![image](https://user-images.githubusercontent.com/60117106/82049906-1987e100-96af-11ea-82fb-5d986292ae03.png)

Seems to work in some Instances, but not others.

For example, above in Talabec - not working.
Below, in Black Fire Basin - working.

![image](https://user-images.githubusercontent.com/60117106/82050152-88fdd080-96af-11ea-8f01-6dc2ee0f2859.png)

**Comment by Xruptor** [comment] 2020-09-04 15:22
I've been having this same issue.  The objectives are just not properly tracked on the Minimap and on the Map.  It's very inaccurate and at times it will show the bomb in the middle but in reality the bomb is all the way near the dam already in Talabec.  Sometimes it shows the bomb across the river spawned, but in reality it's at the center of the map.  There seems to be A LOT of inaccuracies with the Objective Tracker and the Map/Minimap.  This is somewhat vital for people whom rely on it to intercept objectives and such.  It's kind of hard to do when you really don't know where it is unless you are literally next to it.

I made a thread here on it.
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=40586&p=435483#p435483

**Comment by Xruptor** [comment] 2020-09-04 15:23
@Kaelang @MaxHayman
I can confirm that this is still a bug.

**Comment by dalen** [comment] 2020-12-03 13:07
this is fixed now

**Closed by dalen** 2020-12-03 13:07 UTC
Labels: Scenarios, Sourcecode
