### ISSUE TITLE
Kadrin Valley: misaligned steps on Kazad Dammaz outer wall

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15999] opened 2020-03-16 01:32 UTC
**Expected behavior and actual behavior:**

The steps on this segment of the north wall surrounding Kazad Dammaz keep in Kadrin Valley (the south keep) are misaligned with the raised area they join on to making them useless as actual steps. The only way to move from the lower area to the upper area is to jump up directly or jump onto the slope either side of the steps.

The steps need to be moved out of the adjoining structure so the connect properly like all the other steps on the outer wall. If the steps cannot be moved then are you able to manaully add new/correct collision instead?

**Steps to reproduce the problem:**

Go th Kazad Dammaz in Kadrin Valley and find the steps in the screenshot below (approx 34k x 44k in map coordinates). Try to walk up them and you will hit the side of the raised area the steps are supposed to take you to.

**Testing Screenshots/Videos/Evidences (always needed):**

The steps in question. See minimap for location on outer wall.

![steps](https://user-images.githubusercontent.com/60266177/76715875-0e075080-6726-11ea-8a81-3e2cd772986e.jpg)

**Comment by Lheana** [comment] 2020-03-24 16:30
Duplicate of #14166

**Closed by Lheana** 2020-03-24 16:30 UTC
