### ISSUE TITLE
Pet abilities ignoring gcd

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#8902] opened 2017-01-13 14:59 UTC
https://github.com/WarEmu/WarBugs/issues/1640  says closed, many a time turrets. squigs, lions and im also guessing demons but cant confirm, ignore GCD, this happens alot.
Below are 2 ss can make more ss if needed but a quick test should confirm this

![pet damage](https://cloud.githubusercontent.com/assets/8299081/21933856/05b8f306-d99f-11e6-8368-3a95d1e47b3f.png)

Fang and claw being the pet attack and brutal pounce being a pet ability triggered from the player all hit at the same time.

![turret damage](https://cloud.githubusercontent.com/assets/8299081/21934038/d06ac732-d99f-11e6-856a-e63d23831a04.png)

Steam vent and flamethrower hitting at the same time.

I will make another report if needed but first would like some conformation as to whether the dps contribution to pet damage is currently bugged again because 1143 damage in a single gcd from a lion pet seems a tad ridiculous.
Also should flame turrets be able to auto attack ?

**Comment by Luth-RoR** [comment] 2017-01-13 20:45
The abilities used by the pet pet and the master use different GCDs; iirc if, for instance a WL, used "coordinated strike" while the pet GCD was running, the ability failed. This was fixed here.
"Fang and claw" does damage 2x times in a row and "brutal pounce" is an ability used by the player and executed by the pet. "Leonine frenzy": http://waronlinebuilder.org/#career=wl;0;0;13;;;13:;;0:0:0:0:

All engi turrets do autoattacks (why shouldn't they?).
"Steam vent" is a channeling ability that was over in second 33; afaik as soon as a channeling ability is done, the autoattack hits (same for players) and in this case, the turret executed another ability because the GCD didn't run.
I can't see anything wrong here.

**Comment by Blaqwar** [comment] 2017-01-14 17:27
As Luth points out, Brutal Pounce and Leonine Frenzy (and Throat Bite) are simple on-hit buffs that are put on the pet by the player (and can all be active at the same time). They will fire independently of any abilities used by the pet and are triggered by auto attacks, you might consider them 100% chance procs if you will (although on-hit buff seems a better wording).

For example, if a player is in a group with a Shaman who uses 'Ere We Go! and a Chosen who uses Tooth of Tzeentch and then uses one of this own abilities to hit a target you will see the two buff abilities mentioned above dealing damage at the same time as the player's own ability and autoattack. I don't think you'd say there's anything wrong with the GCD in that situation and it's identical as the one you point out with the WL, except it's the pet delivering the hits and the White Lion buffing.

**Comment by Luth-RoR** [comment] 2017-01-15 09:39
According to Aza working as intended; closing then.

**Closed by Luth-RoR** 2017-01-15 09:39 UTC
Labels: Confirmation Request, Dubious

**Comment by M0rf** [comment] 2017-01-24 14:53
![sh gcd](https://cloud.githubusercontent.com/assets/8299081/22251688/9977b378-e243-11e6-9425-1914fa70e72e.png)

It took far to long to get it right as it requires absolute perfect timing but here it is, you would prolly have better results using a program like auto clicker but not using that myself i cant be 100% certain. Having a player ability that works from the pet seems to make it alot easier to do.

Further evidence of gcd skip
![choppa gcd](https://cloud.githubusercontent.com/assets/8299081/22251858/31067a62-e244-11e6-9d48-55c1e3eea721.png)

Dont go nowhere and cant stop da chop used at exactly the same time, check the skill cd's, both skills have a 10 sec cd so its impossible to have them both with a 7 sec cd at the same time, this bug existed on mythic servers and again requires absolute perfect timing, the same bug exists for slayers when using deep wound and slow down and im guessing you can do this with other classes. Appears to be linked to the skill animations.

**Comment by Luth-RoR** [comment] 2017-01-24 18:30
The second picture shows both abilities with a 7 second cooldown left on the bar, nevertheless only one of the two debuffs is left on the enemy (can't stop da chop). The combat log shows nothing about the two abilities unfortunatelly.
My guess is that you managed to trigger both ability cooldowns on the client, but the server only accepted one as the server GCD was running after the first ability.
I lack any detailed knowledge on SH + SH pet abilities atm to make a comment on the first pic.

**Comment by M0rf** [comment] 2017-01-24 20:05
The icon on the mob with 8 seconds is slasha, cant stop da chop is the icon which shows 0, dont go no where was parried. 
Given the difficulty of having both skills go off at the same time its hard to see whether both apply or not especially on an npc, sadly i wasnt able to get another player to help me test it to confirm if both the heal debuff and snare apply though in the past when i have seen this bug occur my feeling is they do.
The choppa ss was just to try and make it clear that my initial report wasnt a load of rubbish and that it is possible.

**Comment by Luth-RoR** [comment] 2017-01-24 20:15
According to Aza and others, there is nothing wrong with the SH screenshot. 
Quote from chat:
_poisoned spine is a dot
drop that! is a proc off next attack, granted by the master
when invoking drop that, brutal pounce or anything else,
the auto attack cd is immediately reset on the pet  
so if the pet is within range it will immediately apply the effect
for a spiked squig that means the disarm is instant, at least_

About the choppa one: i think you can trick the client somehow with ability spam to trigger both abilities synchronously, but the server will only accept one ability. If both abilities do damage at the same time, it should be logged. But the server is authorative over the client ofc, as otherwise it would be easy to circumvate the GCD.

**Comment by M0rf** [comment] 2017-01-24 20:53
Check the time on the combat log between poisoned spine hits and tell me something isnt wrong, its not as if im making it up, the choppa ss should be enough evidence that, whether you are tricking the client or not you can skip the gcd with perfect timing.

If i manage to get someone with the patience to test this with me i will try and get even more proof.

**Comment by Luth-RoR** [comment] 2017-01-25 17:28
That's what i meant: the client and the server use different GCDs; if you trick the client with ability spam, it doesn't mean that the server allows two synchronous abilities at the same time too.
For the SH: 
The dot was cast by the squig (poisoned spine).
The squig used his channeling attack (spine fling) and at the same time, the SH player used one of _his own_ abilities (drop that) which is _executed by the pet_ as soon as possible; this is intended and was a fix as i already wrote above. Iirc on the mythic server the player induced ability failed, if the pet used one of its own abilities at the same time, which made player induced pet abilities a game of luck.
