### ISSUE TITLE
All Quests Lost 

### ISSUE THREAD

**Issue by Shademortal** [WarEmu/WarBugs#11035] opened 2017-12-21 08:58 UTC
I was in game viewing my quests in the tomb of knowledge and was disconnected from the game, upon reconnecting all my quests and quest statuses were lost. 

I have tried reloading the UI and also re-logging out and in, none of which bring back the quests?

**Comment by sioding** [comment] 2017-12-21 11:06
Duplicate of #10421

**Closed by sioding** 2017-12-21 11:06 UTC
