### ISSUE TITLE
Respawned Dead in SC Highpass Semitery

### ISSUE THREAD

**Issue by OgiWanBG** [WarEmu/WarBugs#12210] opened 2018-08-25 17:40 UTC
Hello, today I played SC in which I was killed and respawned dead in my(Order WC).
Could do anything, relog,use book of binding , move etc etc .

Please find attached Screen shot related to my problem , thanks.
![ogimir_007](https://user-images.githubusercontent.com/42701165/44620996-1f201080-a8a7-11e8-8bce-30b3ae00ee38.jpg)
![ogimir_008](https://user-images.githubusercontent.com/42701165/44620997-221b0100-a8a7-11e8-9e12-17c84da59d56.jpg)

**Comment by sioding** [comment] 2018-08-26 06:00
Duplicate of #10682

**Closed by sioding** 2018-08-26 06:00 UTC
