### ISSUE TITLE
joining SC and getting quitter 

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#14111] opened 2019-05-18 05:57 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

once I join SC after loading I should be inside SC but I get kicked to char select screen and get quitter debuff for 10 min and this is happening to me a lot 
if there is a fix for it someone tells me how to avoid this from happening 

**Steps to reproduce the problem:**

just clicking join SC button

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment] 2019-05-18 12:14
Duplicate of #11224

**Closed by sioding** 2019-05-18 12:14 UTC
