### ISSUE TITLE
Guild vault/bank page 4 only 3 rows. Not able to purchase more.

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#16321] opened 2020-04-09 10:08 UTC
**Expected behavior and actual behavior:**
Should be able to buy all rows of Vault 4, can not purchase more than 3. Alltough already having 3 rows in Vault 5. Guild is lvl 40.

**Steps to reproduce the problem:**
Not a clue.

**Testing Screenshots/Videos/Evidences (always needed):**

Vault4:
![Vancee_030](https://user-images.githubusercontent.com/14907399/78884068-a7dac880-7a5a-11ea-8436-79f3415e1d98.jpg)

Vault5:
![Vancee_031](https://user-images.githubusercontent.com/14907399/78884102-b2955d80-7a5a-11ea-9398-127a4c87c332.jpg)

**Comment by Senthoi** [comment] 2020-04-11 09:50
![vault](https://user-images.githubusercontent.com/22262165/79040661-f070be00-7be1-11ea-8591-adacbd6d12f7.png)

We're experiencing this too. The option to purchase more rows has disappeared. You will see it gives us an option to purchase Vault 5, but at a much lower price than what it should be.

**Comment by Kaelang** [comment] 2020-04-19 17:58
Duplicate of https://github.com/WarEmu/WarBugs/issues/15848.

**Closed by Kaelang** 2020-04-19 17:58 UTC
