### ISSUE TITLE
[Gunbad][NPC-Ability] Bad Gas!

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#17286] opened 2020-07-09 11:47 UTC
**Expected behavior and actual behavior:**
Squigs like Skewerin' Squig are casting an ability called "Bad Gas!" which is described as a Hex  - but can't be removed by abilities that remove hex (also highlights the ability, as if it was ready to cast- but ability uncastable to that moment). As this is just a regular mob the debuff should be cleanseable. Probably has either a wrong describtion or wrong debuff class.
<img width="163" alt="Unbenannt" src="https://user-images.githubusercontent.com/17249318/87035801-26760c00-c1ea-11ea-8280-1ac6915c553c.png">

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-07-09 12:51
Duplicate of https://github.com/WarEmu/WarBugs/issues/13886

**Closed by Kaelang** 2020-07-09 12:51 UTC
