### ISSUE TITLE
Every log in get removed abilities from action bar

### ISSUE THREAD

**Issue by Whoareyouagain** [WarEmu/WarBugs#1086] opened 2015-08-14 08:06 UTC
I noticing that every time I log in my character, I get a few missing abilities from the action bar. Then the next log in will have more missing abilities from my action bar.

**Comment by Radiantknight** [comment] 2015-08-14 10:24
Be patient, it is caused by recent patch. The only existing workaround for now - use Nerfed Buttons add-on, this way abilities will stay in place

**Comment by Whoareyouagain** [comment] 2015-08-14 16:23
which recent patch you are speaking off? I have this issue for three weeks.

**Comment by Radiantknight** [comment] 2015-08-14 19:57
Well, yesterday ppl were losing ALL abilities on ALL bars, but you seem to have that old annoying bug, which affected bar 1, like i said, use Nerfed buttons to glue abilities in place, or just use another hotbar other than 1

**Comment by ozarmidrashim** [comment] 2015-08-15 16:48
Recent patch should fix

**Comment by Green-Wolf** [comment] 2015-08-15 21:41
This appears to have been fixed with the latest patch

**Closed** 2015-08-17 17:29 UTC
Labels: Dubious
