### ISSUE TITLE
Guild Window - Roster not updating member status and information

### ISSUE THREAD

**Issue by iiiLollo** [WarEmu/WarBugs#16410] opened 2020-04-17 11:12 UTC
The roster tab in the guild window is not updating members information like location or the in wb/party status.

To reproduce the issue, while being in a guild, open the guild window, in the roster tab then:
- Join a party, the roster will show the party icon 
- Change zone, the roster will show the last zone you where in

Workaround for now is to /rel

The following action will update the member information:
- changing a member note
- assigning or unassigning standard bearer 
- promote/demote

**Comment by Kaelang** [comment] 2020-04-19 15:43
Duplicate of https://github.com/WarEmu/WarBugs/issues/10453.

**Closed by Kaelang** 2020-04-19 15:43 UTC
Labels: Guilds, User Interface
