### ISSUE TITLE
Quest "The Great Hunt" Dark Elf Chapter 20 

### ISSUE THREAD

**Issue by Absolute86** [WarEmu/WarBugs#12202] opened 2018-08-24 17:40 UTC
The second part of the quest when you are sent to talk to Kortul Darkspear, in the quest text it states he is going to kill you and take credit for your hard work.  However the game does not flag him as hostile and you are unable to kill him to complete the quest.

**Comment by sioding** [comment] 2018-08-24 20:04
Duplicate of #12148

**Closed by sioding** 2018-08-24 20:04 UTC
