### ISSUE TITLE
Ground AoE / Rain of Fire for examples are stacking. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16089] opened 2020-03-24 20:49 UTC
**Expected behavior and actual behavior:**

If multiple Bright Wizards or Engineers are using their ground AoE ability, a player should only be taking damage from 1 source. However, these are stacking recently causing order BW groups to destroy pushes in Keeps etc due to massive AoE damage. 

Multiple BW's and use their floor AoE ability on one player. 

Unfortunately I was in the city when we noticed this and wasn't able to grab a screenshot due to so many skills / abilities.

**Comment by emailkook** [comment] 2020-03-27 09:47
I’m a BW and not true. In zerg fights I hardly hit a few targets with RoF in there are others around. Ability itself is working as intended unless there’s a issue w the city specifically.

**Comment by SilverWF** [comment] 2020-03-29 03:36
As BW player I could confirm, that if I set RoF to some spot, where another BW already casting RoF, I wouldn't see any damage numbers: not from RoF, neither from any procs.

**Comment by Kaelang** [comment] 2020-03-30 13:11
Hmm, this is odd then - I'll try to get a screenshot next time as we're definitely seeing multiple BW's hitting us with RoF.

**Comment by grunbag** [comment] 2020-03-31 09:25
Closing for now , feel free to reopen with more infos

**Closed by grunbag** 2020-03-31 09:25 UTC
Labels: Ability
