### ISSUE TITLE
Murderous Intent tactic not purchaseable

### ISSUE THREAD

**Issue by flowingsnake** [WarEmu/WarBugs#19351] opened 2021-07-25 12:17 UTC
The tactic Murderous Intent in the DoK path of Torture tree is unpurchasable. I had it working and then when I added another mastery point it just vanished. I have relogged and reset mastery points. I also reset mastery points and just purchased murderous intent, but it doesn't appear in my puchased tactics.

**Comment by lilimx** [comment] 2021-07-25 13:03
Hey,

what's your current lvl? Did you spend an extra point into the tactic? Did you check your addons? What equip are you currently wearing?

because it's works as intended on my end. I spent my points into the tactic. I saved the current state, did a /rel and a relog and everything works as intended. Even wehen I try to spent into the tactic and more points into the tree.

![grafik](https://user-images.githubusercontent.com/23266079/126900025-5b5943c9-99ec-47e5-80e4-1da6b8e2abce.png)

**Comment by flowingsnake** [comment] 2021-07-25 13:27
currently level 26/27 
I have not checked any addons.
Armour of the challenger equipped.
![image](https://user-images.githubusercontent.com/63324367/126900683-6ef69812-2baf-4fd6-942c-86e92305f79a.png)

I have tried only purchasing in the tree and just buying that tactic still no luck.
When it first stopped working I was getting a message "invalid tactic" and an error code 9XXX cant remember the rest of the number

**Comment by flowingsnake** [comment] 2021-07-25 13:29
![image](https://user-images.githubusercontent.com/63324367/126900815-e92aaa70-f06d-40dd-9a8e-af0c89a5b505.png)

**Comment by Ordoch** [comment] 2021-07-25 16:45
![Sigrath_000](https://user-images.githubusercontent.com/87943815/126906777-1dfe0054-6270-4618-9ca0-c81b800ff129.jpg)
Looks like we're both using the same addon pack.  I never noticed an error code if I got one.

**Comment by Ordoch** [comment] 2021-07-25 18:47
Did the next step:  backed up (renamed) folders User, Cache & Interface.  Got into game still had Murderous Intent purchased and still not selectable or visible on Abilities pages.  Did a /rel with no change too after a couple of respecs too.

**Comment by Ordoch** [comment] 2021-07-25 19:34
Alright!  To quote The Big Lebowski, "New lksd has come to light, man"

I found a temporary fix and possibly a lead to work off of.  I have Murderous intent trained as above, if I step foot into an RvR lake it magically appears and is usable.  This persists through loading to IC.  I respec'd (at IC) and previous inoperable Murderous Intent behavior returns.  Step into RvR lake and proper functionality is restored.  Performed a /rel after exiting RvR lake and proper functionality has remained.   So far I can only break it if I respec and reacquire Murderous Intent.

Just before entering RvR lake:
![Sigrath_003](https://user-images.githubusercontent.com/87943815/126911092-5cad5189-6be8-44f8-8a0a-8d370d335e09.jpg)

Immediately upon entering RvR lake:
![Sigrath_004](https://user-images.githubusercontent.com/87943815/126911106-03abd9ab-88e7-431e-89a0-35f18f56bf13.jpg)

**Comment by flowingsnake** [comment] 2021-07-25 22:07
Fantastic work Ordoch.
Yes, can confirm this is the case on entering and exiting an RvR zone.
Just also to confirm, this works in all the RvR zones I have checked.

**Comment by flowingsnake** [comment] 2021-07-25 23:27
Update: Once murderous intent tactic is equipped but the above rvr zone method, if a further mastery change happens then it unequips and if you try to re-equip it you get "Invalid tactic: 9586 Murderous intent"
![image](https://user-images.githubusercontent.com/63324367/126916782-3ec6644b-fc4a-46ec-8f4d-684a5ef7f2b1.png)

**Comment by Ordoch** [comment] 2021-07-26 01:58
Soooo the temporary fix is more temporary than first reported.  Did a bit of pve after applying talent to talent bar and somewhere between beating up some high elves and turning in the quest the talent removed itself from the talent bar.. it's still visible in Abilities but cannot reinstall it until I get to RvR area.

**Comment by Ordoch** [comment] 2021-07-26 02:18
Could think of two more things to try:

Performed Repair function from RoR launcher settings.. did not see any files repaired or fetched/replaced - Did not fix talent
And then "C:\Users\namehere\appdata\local\Return_of_Reckoning" folder deleted - Did not fix talent

**Comment by lilimx** [comment] 2021-07-30 13:09
Fixed with Patch 30/07/2021

**Closed by lilimx** 2021-07-30 13:09 UTC
Labels: Fix Pending
