### ISSUE TITLE
Bolster in RVR lakes is not working under bridges

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11028] opened 2017-12-19 16:50 UTC
Expected behavior and actual behavior:
When a player under level 40 enters the RVR lake Bolster should be applied
However when going under bridges the bolster disappears for that few meters
This is really annoying for characters with pets or buffs, because pets disappear and buffs have to be reapplied as well.

Steps to reproduce the problem:
Black Crag bridges over the RVR zone
Thunder Mountain the bridge near the Order Warcamp
Kadrin Valley: bridge at GJ bo, the two bridges between the keeps
Dragonwake: The bridge above FS bo, bridge east of MM bo

**Comment by sioding** [comment] 2017-12-19 16:56
Duplicate of #9419

**Closed by sioding** 2017-12-19 16:56 UTC
