### ISSUE TITLE
5 Piece Knight Mercenary Armor Bug

### ISSUE THREAD

**Issue by Qwack** [WarEmu/WarBugs#6398] opened 2016-05-23 14:36 UTC
When all 5 pieces of a Knight's Mercenary Armor are on, if you change weapons, rings, belt or cape it will dismount you and drop all auras.  Sometimes it will actually 0 out all training as if you respecialized.  It is likely related to the 5th tier +1 Path Conquest enhancement.   4 piece or less does not create a bug.  This occurs both in tagged RvR and non-pvp tagged PvE.

I have not tested this for other classes.

**Comment by Evildoor** [comment] 2016-05-23 15:35
I'm closing this as not a bug. Yes, it occurs because of the 5th bonus. It's a method to prevent its abuse.

**Closed by Evildoor** 2016-05-23 15:35 UTC
