### ISSUE TITLE
Shadow warrior cant hold swords new char

### ISSUE THREAD

**Issue by Ethelord23** [WarEmu/WarBugs#14939] opened 2019-09-17 16:29 UTC
I try to make a new char a SW but I cant hold sword only shields 
![Esseral_000](https://user-images.githubusercontent.com/55454892/65060825-4994ae00-d981-11e9-892b-80a60493883e.jpg)

**Comment by sioding** [comment] 2019-09-17 17:18
Duplicate of #14905

**Closed by sioding** 2019-09-17 17:18 UTC
