### ISSUE TITLE
[Influence] Missing first reward in High Elf Chap 17

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14997] opened 2019-10-01 08:59 UTC
![HE_chap17](https://user-images.githubusercontent.com/40274248/65948421-86a97780-e43a-11e9-803f-62c7ab104293.jpg)

**Comment by Lheana** [comment] 2019-10-01 14:19
Duplicate of #10003

**Closed by Lheana** 2019-10-01 14:19 UTC
