### ISSUE TITLE
Kotbs Auras 

### ISSUE THREAD

**Issue by kirraha** [WarEmu/WarBugs#16014] opened 2020-03-16 15:43 UTC
After latest patch imo, the auras keeps bugging up for me. Stay focused usually can't be used. Often in scenarios all or some of the auras reset themselves, but biggest issue atm is to even be able to use some of them. Tried reloading, but dont seem to be that issue.

**Comment by Shooshpanzerer** [comment] 2020-03-18 23:43
Same issue in cities. When using stay focused with focused mending on in scenarios or city instances, system message "failed to spread aura"

**Comment by Kaelang** [comment] 2020-04-20 17:30
Duplicate of https://github.com/WarEmu/WarBugs/issues/15493.

**Closed by Kaelang** 2020-04-20 17:30 UTC
