### ISSUE TITLE
siege cannons

### ISSUE THREAD

**Issue by Aelice** [WarEmu/WarBugs#4096] opened 2016-01-28 20:34 UTC
siege cannons stopped working around T3 deso wc.

**Comment by noisestorm** [comment] 2016-01-28 21:09
They did serverwide, not sure why though.

**Comment by genisaurus** [comment] 2016-01-29 18:13
Root cause identified in https://github.com/WarEmu/WarBugs/issues/4112, closing this ticket as it contains less info.

**Closed by genisaurus** 2016-01-29 18:13 UTC
Labels: ORvR, World Object
