### ISSUE TITLE
Warrior Priest anger reg.

### ISSUE THREAD

**Issue by Plautze83** [WarEmu/WarBugs#13878] opened 2019-04-14 12:06 UTC
Hello, me and also a friendly Warrior Priest have the problem that the scenario books the anger reg. do not grant and in the book "Tome of the Smuggler" anger reg. not with me either.
Thank you for reading.

**Comment by sioding** [comment] 2019-04-14 13:13
Duplicate of #13707

**Closed by sioding** 2019-04-14 13:13 UTC
