### ISSUE TITLE
Items keep disappearing

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#2261] opened 2015-12-10 17:31 UTC
Today logged in my BG, lost my Devastator Gloves and a +21 Toughness Talisman from the backpack, my DoK lost the equipped T2 influence chalice. Not too long ago I lost my Sorc Scenario Staff. I know it's Alpha and all that, but it's really not funny anymore. Is it possible to find out why items keep disappearing,  and how to prevent it from happening?

**Comment by Tesq** [comment] 2015-12-10 18:42
aza it's from long that i abserve this but i really never lost anything appart 1 npc helm form my char, could be that this influence some account and not others, possibly newer account?

**Comment by ozarmidrashim** [comment] 2015-12-10 18:51
I lose very few items as well (about 4 over the course of my play), but I need to find the cause just the same.

**Comment by Evildoor** [comment] 2015-12-10 18:56
Good luck with this, Azarael. I've only lost green shoulders once, but i can imagine how painful it is to lose a SC twohander, or set item, or appearance item from quest/influence which cannot be restored.

**Comment by wiscel** [comment] 2015-12-10 19:02
Thanks for looking into it guys, really appreciate it :-)

**Comment by Tesq** [comment] 2015-12-10 19:20
no i mean maybe there is a sort of  DB databse disposition from older to newer account and look if newer account loose more itiems than older one, maybe it could help find the issue.

**Comment by wiscel** [comment] 2015-12-10 19:45
Close or remove topic please, case solved. Items are here. My mistake (shame shame)

**Comment by ozarmidrashim** [comment] 2015-12-12 12:09
Update. Looked extensively through the item interface and item handlers. There is one case of guaranteed item loss - if you sell an item or stack of items to the NPC, which you then buy back in its entirety. The item's association in the database is broken and it will be lost after a restart.

**Comment by Paninii** [comment] 2015-12-18 21:12
i wouldn't say anything, but since its the 2nd time i loose a pretty "expensive" item, i'll add this here.
Now i lost my Devastator shoulders that were in my backpack on my Marauder Tinteling.  It also had a +18 talisman inserted (if i remember)

**Comment by Evildoor** [comment] 2016-05-30 11:41
Amount of reports and whine about missing items lowered significantly since the time of this report and remaining ones can be explained (items bought just before the server going down, collateral damage of Ruin wipe, etc) - therefore, i presume that either issue found by Azarael was the source of the problem or someone fixed something else without mentioning it here. Closing.

**Closed by Evildoor** 2016-05-30 11:41 UTC
Labels: Item, Major
