### ISSUE TITLE
Thunderous blows damage 

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1162] opened 2015-08-26 17:41 UTC
There seems to be a huge difference in the damage the tool tip suggests and the actual damage of the ability.

**Comment by Starwhisper** [comment] 2015-08-27 21:25
I can confirm this. Thunderous blow hits for damage similar to Rend while the tooltip says it should hit for much more. Guillotine seems to have the same problem..

**Comment by Vigfuss** [comment] 2015-08-27 22:37
I can confirm this as well, TB is hitting for very low damage.

**Comment by milosxe** [comment] 2015-08-28 19:34
There's also another issue with this skill. Keep in mind that I tested it in PvE. When you hit the target it does dmg first and debuffs wounds later. It should be the other way around. Or maybe not, it just feels that the dmg/wounds debuff formula for this skill is wrong. This way as it works now if the dmg that is done to target is less than the initial debuff, his HP will go to 100% and all that dmg will be wasted.

**Comment by Evildoor** [comment] 2015-09-18 20:05
Tested TB today, damage seems fair (2 points difference from tooltip).
Interaction of damage and wounds debuff - i don't know how exactly this should work, but if there is an error then i believe it to be the problem for all wounds debuffing skills. In that case it should be reported separately by someone who knows more about the debuff mechanics and can explain in details how it should work. I'm closing this issue, since it is about certain skill's damage, not debuff.

**Closed by Evildoor** 2015-09-18 20:05 UTC
