### ISSUE TITLE
Guild heraldry Cloak/Gold

### ISSUE THREAD

**Issue by usermagnesia** [WarEmu/WarBugs#13723] opened 2019-03-25 21:37 UTC
I've tryied to set up a guild heraldry. The game taker me 10 gold but change only the colour but not the symbol. Then I've tryied to do  it a second time and it took me 200 gold with no change in heraldry. I would like to fix this and to have my money back. TY

**Comment by Lheana** [comment] 2019-03-26 11:05
Duplicate of #13722

**Closed by Lheana** 2019-03-26 11:05 UTC
