### ISSUE TITLE
Blackguard knockdown

### ISSUE THREAD

**Issue by zabis** [WarEmu/WarBugs#1816] opened 2015-11-10 19:50 UTC
If you use the ability after it has unhighlighted itself, it will go on cooldown and the enemy will not be knocked down.

**Comment by Evildoor** [comment] 2015-11-11 08:29
I've noticed no such bug playing BG during last weeks and neither did my friend. Just now, after reading this report, i logged on and tried to reproduce it on mobs, with no success. In most cases skill either hit or told me to block something. One time it got on cooldown without effect, but the cooldown was reset immediately. Therefore, if there is a bug here then it has some sort of condition to trigger.

**Comment by ozarmidrashim** [comment] 2015-11-11 10:56
I'd like to add that if you're able to use the ability successfully when it's greyed out on the client, there's nothing I can do about it - sounds like a client bug.

**Comment by zabis** [comment] 2015-11-11 21:03
I wonder if it's a lag issue, being that I am across the ocean from the server.

**Comment by Evildoor** [comment] 2015-11-26 11:47
Closing since we failed to tie it to a specific skill (BG knockdown) in any way, and if it is a general issue with lags and server-client interaction, then @ozarmidrashim explained above that we cannot fix it.

**Closed by Evildoor** 2015-11-26 11:47 UTC
Labels: Ability, Could Not Reproduce
