### ISSUE TITLE
Purchased Mastery Tactics - Unavailable (Sorceress and Witch Elf)

### ISSUE THREAD

**Issue by Breshada** [WarEmu/WarBugs#14354] opened 2019-06-05 18:28 UTC
![Bugreport1](https://user-images.githubusercontent.com/51418372/58980315-03cf2380-879e-11e9-9e0b-c5bbe40c89c0.PNG)
![Bugreport2](https://user-images.githubusercontent.com/51418372/58980325-0d588b80-879e-11e9-9371-21311e96615a.PNG)
![Bugreport3](https://user-images.githubusercontent.com/51418372/58980332-12b5d600-879e-11e9-8e0a-aac71e4a177b.PNG)

I have a Sorceress that is Level 16 Renown Rank 17. I have purchased "Vision of Domination" tactic from the mastery tree and equipped it in my tactic bar. However the tactic is "redded-out" and says not available at this level but I am higher than the required level 15 and I have purchased it appropriately and equipped it. 

**Expected behavior and actual behavior:**
The expected behavior is being able to use the tactic that I purchased. The actual behavior is it sits in the tactic slot "redded-out" without giving the benefit of the ability. 

**Steps to reproduce the problem:**
I have tried relogging, closing the launcher and game completely, unseating the tactic and re-seating it. Nothing changes. This happens with "Frenzied Mayhem" on Witch Elf as well. No amount of relogging fixes this. I cannot use mastery tactics that are purchased. This is game-breaking. 

**Testing Screenshots/Videos/Evidences (always needed):**
Screen shots of the Sorceress tree, tactics window, and seated version of the tactic as it is "redded-out."

**Comment by sioding** [comment] 2019-06-05 18:32
Duplicate of #13675

**Closed by sioding** 2019-06-05 18:32 UTC
