### ISSUE TITLE
Issues stacking items in crafting and regular bags

### ISSUE THREAD

**Issue by goodblade** [WarEmu/WarBugs#13963] opened 2019-04-28 03:13 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
When attempting to re stack items in your bag it will not allow you to stack items and you get a warning stating you cant equip stacked items

**Steps to reproduce the problem:**
Took stack of liniments and attempted to stack two stacks together and got the warning had to put it in my guild vault and pull it back out to stack them also couldn't stack stabilizers or even move some armor pot ingredients from main back pack to crafting back pack 

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/50064298/56858028-b27b7b00-6939-11e9-9291-99cb81516bfc.png)

**Comment by sioding** [comment] 2019-04-28 06:49
Duplicate of #13958

**Closed by sioding** 2019-04-28 06:49 UTC
