### ISSUE TITLE
Can't add crafting items for Talisman

### ISSUE THREAD

**Issue by amnesia271** [WarEmu/WarBugs#11458] opened 2018-03-15 16:14 UTC
First some background:
I took up talisman crafting on 2 of my characters, my slayer is working with no issues. However my runepriest Character name: Brbrolledheal is unable to continue crafting talismans. This is taking form in the below descriptions.

Expected behavior and actual behavior:

Add dust/essence/curio to crafting window via right click or drag and drop. 

I can add **fragments** and **containers** to the crafting window, however when I attempt to add dust/essence/curio I am not able to. Right clicking does not populate the window and drag and dropping does not work either. When attempting to add dust/essence/curio the chat pane does not throw out any errors. 

Steps to reproduce the problem:

Open talisman making window from skills
Add container/fragment
attempt to add crafting items (Curio, dust, essence) 
These cannot be added to the crafting window

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-03-15 18:44
Duplicate of #10088

**Closed by sioding** 2018-03-15 18:44 UTC

**Comment by amnesia271** [comment] 2018-03-15 21:13
Hi Sioding I understand that this appears to be a duplicate however a relog doesn't fix the issue.
