### ISSUE TITLE
Chosen Auras

### ISSUE THREAD

**Issue by Zlatish** [WarEmu/WarBugs#14038] opened 2019-05-07 14:37 UTC
Class: Chosen

Skill: Auras

Issue: Hot bar indicates 3 active chaos auras, however portrait buffs show more than 3 active auras if cycled through.
![ChosenBug](https://user-images.githubusercontent.com/50371683/57308280-fb6fc400-70dd-11e9-8f06-10b2503c605a.png)

User: Yorgin

**Comment by sioding** [comment] 2019-05-07 16:42
Duplicate of #13794

**Closed by sioding** 2019-05-07 16:42 UTC
