### ISSUE TITLE
Destro Keep! Order Lord!

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#14548] opened 2019-07-08 23:19 UTC
Destro locked zone but Order lord doesnt  think so) He killed everyone who died near keep and respawn. 
You respawn and die) agane and agane, agane and agane....)

 
![Vicgrimm_003](https://user-images.githubusercontent.com/51807854/60848249-85c3c980-a1ee-11e9-8171-8bd886380c1e.jpg)
![Vicgrimm_006](https://user-images.githubusercontent.com/51807854/60848268-98d69980-a1ee-11e9-8660-16532204e4c6.jpg)

**Comment by sioding** [comment] 2019-07-09 08:51
Duplicate of #14467

**Closed by sioding** 2019-07-09 08:51 UTC
