### ISSUE TITLE
HIGH ELF CH6 easy PQ

### ISSUE THREAD

**Issue by iwka53** [WarEmu/WarBugs#14631] opened 2019-07-23 08:47 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by iwka53** [comment] 2019-07-23 08:48
stage 2 bugged..thornes cant be collected :(

**Comment by Lheana** [comment] 2019-07-24 11:01
You talk about PQ 'Broken Spirits'. So duplicate of #14613. This has been fixed with the patch of yesterday.

**Closed by Lheana** 2019-07-24 11:01 UTC
Labels: Database, Public Quests
