### ISSUE TITLE
T4 Dark Elf Epic Quest cannot be completed

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#19042] opened 2021-05-25 00:44 UTC
**Expected behavior and actual behavior:**
On Step 12 of Epic Quest per RoR Wiki  the npc called "Keeper of the Way" must be killed to collect a key, then take the portal to top of tower to finish quest line.   The "Keeper of the Way" npc is nowhere to be found.  I have done this quest several times and I know exactly where he is suppose to be and he is not there, thus cannot finish the quest line.

**Steps to reproduce the problem:**
I tried to relog and also closed client, searched Bugtracker for reported issue and found nothing.  Waited about 10 minutes at site hoping npc will spawn and nothing.

**Testing Screenshots/Videos/Evidences (always needed):**

![Ravjek_000](https://user-images.githubusercontent.com/66458029/119423230-ad738c00-bcb7-11eb-8d4b-d38e4ba6d4e9.jpg)

**Comment by Lheana** [comment] 2021-05-27 15:34
Duplicate of #16938

**Closed by Lheana** 2021-05-27 15:34 UTC
Labels: NPC, Public Quests
