### ISSUE TITLE
Quests gone

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#10476] opened 2017-09-21 06:40 UTC
Since the last 2 patches I'm having lots of problems in game. More lags and crashes than usual. Strange things are happening like first on my DOK all my quests were gone, luckily 2 days later all was back. Now I'm having the same problem on my Squigherder, alle quests were gone but also my complete inventory (inventory luckily came back the next day, but quests were still gone). 
What I've done so far: deleted the game completely, made a new clean install. Used as little addons as possible, used the 4GB patch and all the other tips to avoid lag and such. Do  I still have to wait for a server reboot to (hopefully) fix it?

**Comment by Lheana** [comment] 2017-09-21 08:47
Why this title? I don't see any link between your title and your problem...

**Comment by wiscel** [comment] 2017-09-22 07:19
I've editted the opening title, but it didnt seem to have saved it

**Comment by Morksezstop** [comment] 2017-10-22 18:40
my all quests and quest history is gone. For example i got beastlord jewelery and was on 20 squig quest. Now the kill quest is gone and i could get beastlord jewelery quest again. That is true for all non repeatable quests, ive done 4 scaven quests now i could done them again, prolly take second ring.

**Comment by Ghostcrowler** [comment] 2017-10-23 19:44
same here friday all my quests gone and until now they dont come back ... GM says server restart is needed for fixing this bug buuuut the homepage says ... Up since: 2017-10-23 10:07:41 ... so Server restart was today?

**Comment by Morksezstop** [comment] 2017-10-24 18:04
well for me server restart done the job and quests are back. The problem occur when/if the game crash while loading the character.

**Comment by sioding** [comment] 2018-03-27 16:26
Duplicate of #2001

**Closed by sioding** 2018-03-27 16:26 UTC
Labels: Crazy stuff
