### ISSUE TITLE
Throat Bite and Brutal Pounce bug damage :

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#12560] opened 2018-11-10 01:17 UTC
Throat Bite and Brutal Pounce bug damage :

BP does 200 damage on the target dummy - Damage according to skill description 512
TB does 133 damage on the target dummy - Damage according to skill description 440

Attack target dummy

https://github.com/WarEmu/WarBugs/issues/12335

![sans titre](https://user-images.githubusercontent.com/43276959/48295726-07602d80-e48f-11e8-930a-b88c1c384e7a.png)
![sans titre3](https://user-images.githubusercontent.com/43276959/48295730-0deea500-e48f-11e8-95fb-bfb13139fcd0.png)

**Comment by sioding** [comment] 2018-11-10 09:08
Duplicate of #12335

**Closed by sioding** 2018-11-10 09:08 UTC
