### ISSUE TITLE
Unusable/Uninteractable Gates in Altdorf After Finishing Scenario

### ISSUE THREAD

**Issue by SchismBlacksoul85** [WarEmu/WarBugs#11197] opened 2018-01-22 23:31 UTC
I just encountered a very strange situation that I hadn't seen before, after returning to Altdorf after a SC (was already there before entering the SC, it wasn't like I was ported there after finishing). I had been standing in the War Quarter when the SC que popped, went in, completed the game, zoned back to where I was before ... only this time there was no option to click on and interact with the main gate leading out of the War Quarter. It's like it was just a wall.

So then I backtracked, thinking I could bypass that central gate by going down one of the side gates and going around. Those gates were interactable, in that the cursor changed to indicate that I COULD interact with them ... but actually right-clicking the gates made nothing happen. Logging out and logging back in had no change on either of the gates, still the same situation as before.

**Comment by Lheana** [comment] 2020-02-22 21:24
Duplicate of #9444

**Closed by Lheana** 2020-02-22 21:24 UTC
Labels: Sourcecode, World Object
