### ISSUE TITLE
Erupting Blast Potion bypasses LoS

### ISSUE THREAD

**Issue by Morrdread** [WarEmu/WarBugs#13647] opened 2019-03-14 16:07 UTC
The blast potion is a ranged AoE attack, as such it should follow Ranged LoS rules?
Last night I used them in a fort attack and was able to throw one through a wall. I tried again after the 5 min cooldown, and it happened a second time.

**Comment by sioding** [comment] 2019-03-14 17:23
Duplicate of #11483

**Closed by sioding** 2019-03-14 17:23 UTC
