### ISSUE TITLE
Apothecary multiple items stacking

### ISSUE THREAD

**Issue by Ballsh** [WarEmu/WarBugs#10945] opened 2017-12-03 11:48 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I get multiple items both different frags and containers stacking in bag which does not allow me to craft.When i can craft i can make maybe 2 or 3 potions and then have to relog because the apothecary maker wont accept anything.Wow i have made it to level 50 but i cant use level 25 containers or frags. 

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2017-12-03 11:54
Duplicate of #10088

**Closed by sioding** 2017-12-03 11:54 UTC
