### ISSUE TITLE
The Grudges of Karak Drazh!

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12412] opened 2018-10-06 16:17 UTC
This quest is active.  The Particulars Section of the tome entry is incorrect. Killing/looting Speezy will not complete quest. The Map marker is correct but Speezy is not there. The named mob should be Flayskin Edcarver.  You have to kill/loot him quick because the Muck Pen PQ mobs attack and kill him. 

![gunnr_001](https://user-images.githubusercontent.com/42098334/46573291-cee1a700-c958-11e8-9ccd-de174a10c197.jpg)
![gunnr_000](https://user-images.githubusercontent.com/42098334/46573292-d43ef180-c958-11e8-9625-d289c4875c26.jpg)

**Comment by sioding** [comment] 2018-10-06 16:59
Duplicate of #11642

**Closed by sioding** 2018-10-06 16:59 UTC
