### ISSUE TITLE
Graphics, players with furnitures (tables, tubes, ...)

### ISSUE THREAD

**Issue by superzeros** [WarEmu/WarBugs#4428] opened 2016-02-20 01:35 UTC
For 2 days, we can see from time to time players naked (that's usual) BUT with like... A giand table stuck on them. Or a big tube, or something. Meeting that issue from time to time is quite funny, but today a guildmate sees that on EVERYONE depending on where he stands (either no char bugs, or some, or all).

Voidmaster told me he didn't hear about this and adviced me to come here.

Anyone?

**Comment by Tholkienn** [comment] 2016-02-20 08:14
I see some too, like an Ork who is fighting with a table...

**Comment by Lileldys** [comment] 2016-02-20 11:15
![pearlnecklace_004](https://cloud.githubusercontent.com/assets/13259775/13196332/ee92639e-d7c2-11e5-9778-aa024ce01aee.jpg)
Here's a pic. I have only seen this issue with Blackguards currently.
When with S&B, they get a tube, and with a 2H a table. I don't know what weapons or armour items are causing this though.

**Comment by noisestorm** [comment] 2016-02-20 13:45
Each time you see a player with such an item, tell him or her to report this here. And give them a friendly reminder that they are most likely abusing bugged items to get those 'skins' - they arent supposed to have those obviously. Since i doubt that those items are normal items they'd use in the first place, but items they actively search for from some lowlvl useless Inf reward or similar, they're knowlingly abusing it. If they do not _want_ to report it, send their names to a GM to let him investigate it

**Comment by Torquemadra** [comment] 2016-02-20 15:04
I believe the players concerned with this bug cannot see the problem themselves, this is not a bugged item skin being applied as an alternate appearance. It is under investigation.

**Comment by Tiggonos** [comment] 2016-02-22 02:55
![antigonos_018](https://cloud.githubusercontent.com/assets/13809443/13208331/09206bb0-d918-11e5-9155-99cd448a9fce.jpg)

It seems its a bound to player bug. that player i saw with the thing on the head on different scenarios.

**Comment by Tholkienn** [comment] 2016-02-23 11:56
http://img15.hostingpics.net/pics/930980Superplumeau006.jpg

this one is very funny

**Comment by Lileldys** [comment] 2016-02-23 12:14
Is this issue linked to Guild Banners? Just inspected Snip, and the player that Torquemadra shows in pictures have Guild Banners equiped.

**Comment by Luth-RoR** [comment] 2016-07-02 20:35
Should be fixed.

**Closed by Luth-RoR** 2016-07-02 20:35 UTC
Labels: Database, Item
