### ISSUE TITLE
apothecary bugg with super critical additives

### ISSUE THREAD

**Issue by Lecker79** [WarEmu/WarBugs#14409] opened 2019-06-13 00:48 UTC
Hey GMs,

Seems that "Porcine bile" isnt working in apothecary, unable to combine it into any brews. Can't seem to find any info on the forums about it.

Porcine Bile is an additive for apothecary slot giving +% super critical chance on creating potions

Unable to add to Apothecary window, have tried using different level Biles with different lvl vials and all ingredients to no avail.

Last i remember it working was approx. 1 month ago, havent made many potions since then.

https://user-images.githubusercontent.com/51767622/59395617-342f4700-8dc8-11e9-857d-1d920227b496.jpg

**Comment by sioding** [comment] 2019-06-13 06:18
Duplicate of #7740

**Closed by sioding** 2019-06-13 06:18 UTC
