### ISSUE TITLE
[Ability] Buff stacking does not work

### ISSUE THREAD

**Issue by Reggaewaldo** [WarEmu/WarBugs#1671] opened 2015-10-16 10:22 UTC
Buff stacking does not work. Basicaly buffs that increase the same stats does not stack. If i have 2 buffs increasing strength only the stongest buff will be counted.

I.e IB [Ancestors Fury] and KotBS [Press the attack] or IB [Guarding Attack] with WP [Prayer of Absolution] does not stack, only the effect that gives the most + to a single stat is calculated according to Paperdoll. Also tried with buffs to notice difference when hitting mobs, no difference there so tested and verified.

On Live I'm almost 100% possitive that buffs and debuffs stacked.

**Comment by Evildoor** [comment] 2015-10-16 10:33
Uh, i have to disagree. IIRC, in most cases buffs/debuffs were not stacking. Yes, this makes Ancestors Fury's Strength part questionable since IB has Inspiring blow. For the same reason in T4 almost nobody used armor Covenant/Prayer because everyone (except for classes who can buff armor without losing anything, like IB) had armor potion active 24/7. I can't say that i 100% like this behaviour (really, KotBS/Chosen + IB/BG + RP/Zealot in a party and RP/Zealot can't give IB/BG any useful Rune/Mark) and maybe some improvements can be done here, but IIRC, it was this way on live, so it's a balance issue, not a bug.

**Comment by ozarmidrashim** [comment] 2015-10-16 11:33
Highly dubious.

When I first implemented the combat code, and was ready to push it to live, I had to delay because multiple forum users (as well as the client's character screen) told me that buffs do not stack with each other. The client will correctly show any buffs that are meant to stack.

The emu's stacking groups are as follows:

Standard Buff
Morale Buff
Tactics
Exceptions

The rules within the groups are as follows:

Buff: Highest
Morale Buff: Highest
Tactics: All stack
Exceptions: All stack

Then the contributions of each group are summed into the stack value.

**Comment by Evildoor** [comment] 2015-10-16 11:47
@ozarmidrashim , i agree with your scheme. When i said "buffs/debuffs do not stack" i meant only buffs/debuffs from abilities like those mentioned in my or @Reggaewaldo 's post.

**Comment by ozarmidrashim** [comment] 2015-10-16 11:55
Indeed. My post was directed towards the OP.

**Comment by Reggaewaldo** [comment] 2015-10-16 19:01
In that case I stand correct. Let us look at this later from a balance perspective instead then.

**Comment by Evildoor** [comment] 2015-12-03 13:05
As i said above, I support the idea that this mechanism should be reworked, but it will be a serious balance overhaul, and it's not a bug anyway. Closing.

**Closed by Evildoor** 2015-12-03 13:05 UTC
Labels: Ability, Dubious
