### ISSUE TITLE
Armor reduces damage by more than 75%

### ISSUE THREAD

**Issue by komar9220** [WarEmu/WarBugs#12485] opened 2018-10-23 06:46 UTC
Expected behavior and actual behavior:

Armor reduces damage by more than 75%

Steps to reproduce the problem:

results:
3138 (71.3%) - 155 damage 
3829 (87%) - 110
4769 (108.4%) - 84 and 91

Screenshots/Videos or archive.org evidences:

![johngod_002](https://user-images.githubusercontent.com/44377813/47340865-2f3a4d80-d6a8-11e8-9125-9ce4656c1f54.jpg)
![johngod_004](https://user-images.githubusercontent.com/44377813/47340866-2fd2e400-d6a8-11e8-8281-7a29146eef87.jpg)
![johngod_008](https://user-images.githubusercontent.com/44377813/47340867-2fd2e400-d6a8-11e8-8dc4-a052df859d55.jpg)
![ni9d2qkh6uq](https://user-images.githubusercontent.com/44377813/47340877-395c4c00-d6a8-11e8-90f6-bf43615435d1.jpg)

**Comment by Kweedko** [comment] 2018-10-23 08:02
Do you use toughness in your calculations?

**Comment by Nfkillz** [comment] 2018-10-23 08:21
and enemy's weapon skill

**Comment by Kweedko** [comment] 2018-10-23 08:30
> and enemy's weapon skill

Yes decreases the total % of armor so on 120% armor with 50% WS armor ignore - it's gonna be 60%

But on 200% armor with WS 50% - it's gonna be 75% cause 200/2 = 100 -> to hardcap 75%

**Comment by Ramasee** [comment] 2018-10-23 12:18
Alright so in order for me to check your claim; I need to know the weapon dps of equivalant, his strength, his weapon skill, and your toughness.

**Comment by Natherul** [comment] 2018-10-27 16:36
Unless there is a specific case where its misbehaving (there is multiple paths of code that damage calc can take) armor mitigation is capped at 75%. I just followed down one of the paths to make sure. As pointed out there are more factors that needs to be taken into account here.

**Comment by sioding** [comment] 2018-11-09 07:00
No answers since 13 days. I will close this report here. If the OP thinks the issue is still a valid one, please retest it with considering all the additional informations you got here to make sure a dev can reproduce it.

**Closed by sioding** 2018-11-09 07:00 UTC
Labels: 2 Week Ultimatum, Combat Mechanics, Confirmation Request, Source Code
