### ISSUE TITLE
White Lion morale bug 1

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#7565] opened 2016-08-31 20:13 UTC
Hello got an issue here when my pet hit any kind of target my character dont get any morale.

**Comment by Soulwhisper** [comment] 2016-08-31 21:01
If im right you shouldnt get any.

**Comment by DUSKANGEL** [comment] 2016-09-01 10:39
eheh so my enemy will get morale and i am not?>

**Comment by sioding** [comment] 2017-10-24 10:37
Duplicate of #10603

**Closed by sioding** 2017-10-24 10:37 UTC
Labels: Combat Mechanics
