### ISSUE TITLE
You Got Nuffin'/Bolstering Enchant

### ISSUE THREAD

**Issue by Ashton0007** [WarEmu/WarBugs#12240] opened 2018-08-31 17:14 UTC
Seems the BO Heal tactic does not scale with willpower while the SM one does. The BO one also cannot Crit while the SM one CAN. (have 100% tested this info and it is correct) 
Seems the SM one is much stronger due to these minor differences. Not sure if this is working as intended or if this is a minor bug

**Comment by sioding** [comment] 2018-09-01 06:30
If you have tested it - please provide some screenshots.

**Comment by Ashton0007** [comment] 2018-09-02 04:42
I can do that But its going to take a lot of screenshots to prove that something cant crit while the other can, no? The willpower claim I can get in 4 screens, showing before willpower, and after on both classes.

**Comment by sioding** [comment] 2018-09-03 06:49
Well - how do you think we would reproduce it - testing means a lot of time invest i know.

**Comment by sioding** [comment] 2018-09-19 10:57
No screens since 16 days. close

**Comment by Scophis** [comment] 2018-09-27 14:40
The scaling or better saying not scaling with WP can be seen here 

![ygn-wp](https://user-images.githubusercontent.com/40274248/46153435-71bc6600-c273-11e8-97e3-38a3b6b3be98.jpg)

The healing though scales with the masterypoints invested into the used bellow
![ygn-treee-heal](https://user-images.githubusercontent.com/40274248/46153498-8d277100-c273-11e8-83e0-1e507d255e99.jpg)

Didn't see YGN crit while farmig/testing. 
![ygn-heal](https://user-images.githubusercontent.com/40274248/46153581-b811c500-c273-11e8-9af3-6be0bcb2cb7e.jpg)
If needed i could provide longer datasheets, but I guess this should be enough to beginn with^^^

(Sadly I don't have a SM, gonna ask a guildy to help out with that)

**Comment by bozzax** [comment] 2019-04-19 14:33
There is another issue with it scales off the bellow you use not how many pts you have in the boss tree.

**Comment by grunbag** [comment] 2019-04-19 14:46
Should it crit and scale with WP @bozzax?

**Comment by bozzax** [comment] 2019-04-19 17:41
https://www.youtube.com/watch?v=5y8uT2pq6pw

My bet it shouldn't crit but I'm not 100%

**Comment by grunbag** [comment] 2019-04-19 20:17
Fixed for next patch

**Comment by sioding** [comment] 2019-04-28 06:47
Fixed with patch from 27.04.2019

**Closed by sioding** 2019-04-28 06:47 UTC
Labels: Ability, Fix Pending
