### ISSUE TITLE
BL quest - second stage - 1 BL Token missing

### ISSUE THREAD

**Issue by Olari-Prop** [WarEmu/WarBugs#16405] opened 2020-04-16 16:58 UTC
I've an Issue with BL quest, second stage. I asked around and no one has an answer and I found no topic in Forum. A quests (don't know wich one) doesn't gave me the last token I need in order to take the pocket item. No quests are available in every zone to do them once more, don’t know what to do.. I have 4 / 5 tokens in my backpack. I’m sure that I’ve done everything correctly.
I rly need that book beacause of the spec I choose, and I have no problem in redoing the quest eventually. Wich solutions do you have for me?

**Comment by Kaelang** [comment] 2020-04-18 00:05
If you finish all of the BL quests, including the final hand-in, then you'll have enough tokens for the pocket item. Pretty much every level 40 is running the item and there's still a tonne of groups who are LFG to run the circuit. Could you have missed a boss and/or not handed in the final quest?

**Comment by Olari-Prop** [comment] 2020-04-18 15:14
I've checked twice, no quests in my book are available. Then i check every of the 5 Npc's directly on place. Still no quests available to take. I've all the 5 set pieces (so the first stage it's ok) but only 4 BL tokens.

I've talked recently with other players and we strongly suppose that I've lost one of the token because of a restart of the server. The restart reset one of my token but the quest it's now completed, so I don't have a chance to redo the quest again.

Apparently I'm not the only one who had that kind of problem before with the BL quest, II stage.

**Comment by Kaelang** [comment] 2020-04-19 15:55
As you mentioned, it is highly likely a server restart caused this issue and that this is not actually a bug within the game. I'm going to go ahead and close this bug report for the time being.

Thanks.

**Closed by Kaelang** 2020-04-19 15:55 UTC

**Comment by Olari-Prop** [comment] 2020-04-20 08:56
I trust you if you tell me that's not a bug and I thank you very much for answering me twice.

But still, what I'm suppose to do? I'm sorry to say that, I don't want to sound arrogant to you at all, but the topic from my perspective isn't closed at all :)
I've understood that isn't a GM's topic (I posted about that on the forum too), nor a bug as you said, but still is a big and collective problem.

That's just some of the post I recently found doing some research about that topic in forum:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=27723!
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=36935
https://www.returnofreckoning.com/forum/viewtopic.php?t=24890

And a lot more in the bug-tracker. Unanswered and closed like mine.

I was asking myself: is difficult, from a Devs point of view, to make the SECOND part of the quest-line (the killing one that give you BL token) a REPEATABLE quest, instead of a only one-time quest ?
I think there will be no bad consequences at all, even if want to take profit from that. The reward (pocket item) it's a bind to pickup item, so you cannot sell it in AH or exchange it with other players and you cannot equip it twice on your pg, because of the same name. 
Besides, the amount of gold and exp that you receive from repeating this quest-line it's nothing in comparison with other rvr quests/ PQ's, which are more accessible and rewarding.
I think that this will solve my/our issue once and for all.

Let me know, i will wait ;) thx again and I hope my English it's understandable!

**Comment by Olari-Prop** [comment] 2020-04-20 09:43
I trust you if you tell me that's not a bug and I thank you very much for answering me twice.

Then, I'm sorry to say that, I don't want to sound arrogant to you at all, but the topic from my perspective isn't closed at all :)
It's clear to me now that isn't a GM's topic nor a bug as you said, but still is a big and collective problem. 
I posted about that issue in an already open topic on the forum at: 
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37522)

That's just some of the posts I recently found doing some research:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=27723!
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=36935
https://www.returnofreckoning.com/forum/viewtopic.php?t=24890
And a lot more in the bug-tracker. Unanswered and closed like mine. I just needed to know how to orientate my research.

I was asking myself: is difficult, from the Dev's point of view, to make the SECOND part of the quest-line (the killing one that give you BL token) a REPEATABLE quest, instead of a only one-time quest ?
I think there will be no bad consequences at all, even if want to take profit from that: the reward so called "pocket item" it's a bind to pickup item, so you cannot sell it in AH or exchange it with other players and you cannot equip it twice on your pg, because of the same name.
Besides, the amount of gold and exp that you receive from repeating this quest-line it's nothing in comparison with other rvr quests/ PQ's, which are more accessible and rewarding.
I believe that this will solve my/our issue once and for all.

I will create a new topic eventually if this one was incomplete because I do care a lot about that. The entire game is based on farming equip and equipping your pg and make it stronger, useful and beautiful!

Let me know, i will wait ;) many thanks again and I hope my English is understandable!

**Comment by Kaelang** [comment] 2020-04-20 11:06
Hey!

Don't get me wrong - I do see the issue you're facing and appreciate the concerns. However, if we delve somewhat deeper into this, the actual quest and triggers are working. The problem here is the server crash which caused a rollback at the same time you handed the quest in. 

The quest at this time is not coded to be repeatable, so although you lost the reward, the quest is working correctly by not allowing you to take it again.

I appreciate you pooling the resources together to bring this issue to light however this would be best suited for the Suggestions and Feedback forum. Which, as you have linked, there is already a thread there for.

The bugtracker is here specifically to identify broken game features. My response is that the Beastlord quest line is working as intended, but an unfortunate crash has generated the problem. The team are consistently working on stabilising and improving the RoR server. 

The team review Suggestions posted on the Forums and if we feel that the quest should be recoded moving forward into a Repeatable quest to stop things like this re-occuring in the future, it may be addressed moving forward. 

Thank you for understanding.

**Comment by Olari-Prop** [comment] 2020-04-20 11:50
Got it! I will surely consider in posting a note on "Feedback" as you suggest. Maybe it will trigger something.

I think It's not just about me at that point, I already forgot the possibility to have my pocket-item back ^^ my concern are mainly focused on a general issue of people losing equip, which is a nightmare in a game like this one.

At the same time I understand completely that you/we are performing stability issue and you're working hard on that. I thank you for that!

said so,
thx a lot, again : )
