### ISSUE TITLE
report manufacturing jobs bug

### ISSUE THREAD

**Issue by Rokatord** [WarEmu/WarBugs#12360] opened 2018-09-23 13:43 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Talismans and potions should be produced quickly one behind the other.

Talisman production and planting has a bug. If you put all the ingredients in the respective places in a row and then you want to make talismans or potions "fast", the profession starts to bug.
If you make "fast" you can not put ingredients back in and have to sign up again.

Steps to reproduce the problem:

Fill in all seats and start the production quickly.

![wholamli_005](https://user-images.githubusercontent.com/43446066/45928645-4968fa80-bf47-11e8-9d31-4e03bc16b0f2.jpg)

Best regards from Rokatord

**Comment by sioding** [comment] 2018-09-23 14:32
Duplicate of #7993

**Closed by sioding** 2018-09-23 14:32 UTC
