### ISSUE TITLE
Spec Mastery Poiont always gone

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11131] opened 2018-01-11 09:43 UTC
Hi there,
after any lvl-up and change any gear in any slot my spent mastery point ( Engeneer: Tree 1 ) in sniper was gone and i have to respent it. 
Incl: Engeneers Turrets won't fire and have to recast.
Maybe a feature or a bug.

**Comment by sioding** [comment] 2018-01-11 09:54
Duplicate of #7024

**Closed by sioding** 2018-01-11 09:54 UTC
