### ISSUE TITLE
"Friendly" Grimbeard Station PQ NPCs attacking order players

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#12271] opened 2018-09-06 19:48 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Dwarf NPCs at the Grimbeard Station PQ in BFP are attacking order players who come near them.  They continue to con blue rather than red and we are unable to damage them but they can certainly damage us.  Affects at least two types of NPCS, Railhands and whatever the guards are called.

Steps to reproduce the problem:

Walk close to the NPCs and they should attack.  My tank groupmate did not think he was catching them with AOE or Challenge but that may still be a possibility.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/16654707/45181213-b07f7300-b215-11e8-9d66-e13be27ad8a6.png)
![image](https://user-images.githubusercontent.com/16654707/45181247-c8ef8d80-b215-11e8-8c04-5f1cb6afce9b.png)

**Comment by Lheana** [comment] 2020-02-22 16:18
Duplicate of #9880

**Closed by Lheana** 2020-02-22 16:18 UTC
Labels: NPC, Sourcecode
