### ISSUE TITLE
[Shaman] Healing weapon

### ISSUE THREAD

**Issue by cfabr** [WarEmu/WarBugs#14141] opened 2019-05-20 15:14 UTC
![Hudiz_001](https://user-images.githubusercontent.com/50782391/58031903-b7d77a00-7b21-11e9-94b7-1490ed287920.jpg)
![Hudiz_002](https://user-images.githubusercontent.com/50782391/58031909-ba39d400-7b21-11e9-905d-cff153a1c2ff.jpg)

I know this issue has already been taken up in here and thought fixed, but the oppressor healing staff for shamans are still not working. As you can see on second picture the staff-tag is in red, which means i cant use it.

**Comment by sioding** [comment] 2019-05-20 16:52
Duplicate of #14026

**Closed by sioding** 2019-05-20 16:52 UTC
Labels: Database, Item
