### ISSUE TITLE
Game crashes after entering the scenarios.

### ISSUE THREAD

**Issue by Rokatord** [WarEmu/WarBugs#12519] opened 2018-10-31 03:35 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

My game crashes every time I enter scenarios.

Steps to reproduce the problem:

Download the game: https://www.returnofreckoning.com/join.php and register for scenarios. If it does, they will do it and the error will occur.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-10-31 06:51
Duplicate of #12512

**Closed by sioding** 2018-10-31 06:51 UTC
