### ISSUE TITLE
(WP skill bug) "Sacrifice" don't work in any dungeons.

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#14176] opened 2019-05-25 10:00 UTC
As i tested, the warrior priest's "path of grace" new skill: "Sacrifice" can not heal group mates in any dungeons (gunbad, city crypt and tunnel).

The "Sacrifice" only deals dmg to the caster but haven't heal group mates in dungeons.

The skill works on RVR, SC, and PVE, but in dungeon its not work. 

Please fix it, 

Thanks a lot to the ROR team.

**Comment by sioding** [comment] 2019-05-25 10:05
Duplicate of #11846 
Other bility - but the same reason - you can flag yourself for rvr and it works. but no need for a second report. i put it on the report we already have for another channeling ability that only works while being rvr flagged

**Closed by sioding** 2019-05-25 10:05 UTC
