### ISSUE TITLE
Massive Loot Bag - Dok Karaz

### ISSUE THREAD

**Issue by jordanlcain** [WarEmu/WarBugs#12016] opened 2018-07-09 23:36 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Received massive loot bag in mail from Dok Karaz - level 18 Ironbreaker, received black orc obliterator bodyplate
![grimnthor_008](https://user-images.githubusercontent.com/22715345/42481224-1ef07d60-8396-11e8-8132-1a3b625bccde.jpg)
Haven't accepted yet

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment] 2018-07-12 16:25
Have you changed your char? Like you left your BO to log your IB?

**Comment by jordanlcain** [comment] 2018-07-12 16:29
I haven't touched my BO or Slayer characters for awhile, I created them to view some static meshes in the world for inspiration a few months ago I believe. I just recently re-downloaded the client a week or so ago and have only played my IB since

**Comment by sioding** [comment] 2019-04-06 07:42
Duplicate of #11739

**Closed by sioding** 2019-04-06 07:42 UTC
