### ISSUE TITLE
Gold bag from keep bugged

### ISSUE THREAD

**Issue by PonokefaloS91** [WarEmu/WarBugs#12379] opened 2018-09-26 13:12 UTC
hello , i just won a gold bag from keep def at HP emp t3 on my squig herder and i got 16rank gloves for engi (obliterator work gloves) my ingame name is Buno
![buno_000](https://user-images.githubusercontent.com/43609747/46082100-ed9cac80-c1a6-11e8-96b4-bf74d94063d5.jpg)

**Comment by sioding** [comment] 2018-09-27 08:12
Duplicate of #11739

**Closed by sioding** 2018-09-27 08:12 UTC
