### ISSUE TITLE
Blast Potion ticks proc Procs

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#16276] opened 2020-04-07 09:25 UTC
I dont know if this is intended but it higly favors some classes over others. On my WE the dot ticks also proc my kisses and weaponprocs and i assume it would also proc dok cov and sorc dmg add.
![WAR-64 2020-04-07 11-15-56](https://user-images.githubusercontent.com/45398873/78652724-63b4c000-78c2-11ea-8da6-00060d78bff5.png)

**Comment by Kaelang** [comment] 2020-04-19 23:32
Duplicate of https://github.com/WarEmu/WarBugs/issues/11441.

**Closed by Kaelang** 2020-04-19 23:32 UTC
