### ISSUE TITLE
[Healers] Permanent Heal Debuff

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12679] opened 2018-11-21 02:33 UTC
Expected behavior and actual behavior:
Any heal debuff should not be permanent.
Some abilities or combinations of abilities with tactics makes permanent heal debuff on character, only relog fix it.

Steps to reproduce the problem:
I would try stack heal debuffs from Sorc, Magus, SH, WE and see if they will make permanent heal debuff.

Screenshots/Videos or archive.org evidences:
![xergoam_019](https://user-images.githubusercontent.com/37849311/48815248-1ae87f80-ed3e-11e8-87e5-84e39b799dc6.jpg)

no tactics still perma heal debuff
![xergoam_020](https://user-images.githubusercontent.com/37849311/48815251-1c19ac80-ed3e-11e8-8b6c-0e9ab1d59edc.jpg)

fixed after relog
![xergoam_021](https://user-images.githubusercontent.com/37849311/48815254-1de37000-ed3e-11e8-9a93-b5e0af964c60.jpg)

**Comment by sioding** [comment] 2018-11-21 08:09
Duplicate of #12344

**Closed by sioding** 2018-11-21 08:09 UTC

**Comment by XmatXergon** [comment] 2018-11-21 08:32
@sioding yes, but other topic is closed for comments so i cannot provide more screenshots or data... thats why i made new topic...

**Comment by sioding** [comment] 2018-11-21 09:15
Thx @XmatXergon  - i opened the other issue again
