### ISSUE TITLE
Ironbreaker's ability "Shield sweep" bug. Grudge's regain not working as intended

### ISSUE THREAD

**Issue by Balinorr** [WarEmu/WarBugs#16674] opened 2020-05-05 03:01 UTC
Hello.

I want to report that the grudge's regain of the ability "Shield Sweep" of the ironbreaker is not working as proper, and it never did. If the skill costs 25 grudge and you regain 10 grudge for every target you hit up to three targets ,than you must have at the end 30 grudge (10x3=30), 35 if you use the tactic "rising anger" (10x3 + 5 = 35). Instead at the end you have only 10 grudge, 15 if you have "rising anger". It appears that the skill counts only the first target for the grudge's regain calculation.

Here the video i made for evidences: https://www.youtube.com/watch?v=lxIwLsGOq8Q

**Comment by Kaelang** [comment] 2020-05-05 13:20
Duplicate of https://github.com/WarEmu/WarBugs/issues/15634.

**Closed by Kaelang** 2020-05-05 13:20 UTC
