### ISSUE TITLE
AoE Skills through the Wall in Maw

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#16677] opened 2020-05-05 12:21 UTC
**Can you any skills dmg/pull through the wall**

**Steps to reproduce the problem:**
1. Maw
2. 2nd fllor
3. Use any AoE skills like BW/Magus/Engie through the wall and enemy will be hitted same as you.

**Testing Screenshots/Videos/Evidences (always needed):**

![Septin_004](https://user-images.githubusercontent.com/8436809/81065429-1e48da00-8ee4-11ea-9a0a-4a195ded315d.jpg)

**Comment by igvgithb** [comment] 2020-05-05 13:02
This also works on destro side in the Maw and the corner of Butcher's pass. I've tested with several chosen abilities and raze and all have gone through. I'm not sure about challenge, since I can't inspect people on the other side to test it out.

**Comment by CyphDK** [comment] 2020-05-05 13:10
I made a few recordings of Magus Rift consistently pulling people through walls.
1: https://youtu.be/2YxOGMDkhCA
2: https://youtu.be/ZRq53QZqPIk

**Comment by Kaelang** [comment] 2020-05-05 13:18
Duplicate of https://github.com/WarEmu/WarBugs/issues/16657.

**Closed by Kaelang** 2020-05-05 13:18 UTC
