### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 10 - Logrin's Forge

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11321] opened 2018-02-18 00:16 UTC
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 10 - Logrin's Forge

In Logrin's Forge (left side, destruction; right side, order), there are two platforms by the walls both before and after the Battle Objective (see screenshots). To get on the one (left side, destruction (right side, order)) - first platform on the right before the Battle Objective), jump onto the highest barrel unmounted. Position your character just at the edge of the barrel (backed up from the platform) to get a running leap. Use a mount or "Flee" to accomplish this leap. Upon this platform, you can use rDPS to harass your enemy by the Battle Objective. Additionally, upon this platform, you can stray in the back of the platform to avoid damage by going behind the steampunk-like obstructions.

![anonymous_009](https://user-images.githubusercontent.com/19481783/36346889-2366ae28-1406-11e8-9c40-812981cd07a5.jpg)
![anonymous_010](https://user-images.githubusercontent.com/19481783/36346890-237ea7c6-1406-11e8-956b-80d126c655a5.jpg)
![anonymous_011](https://user-images.githubusercontent.com/19481783/36346891-239454d6-1406-11e8-8e50-b996eead375f.jpg)
![anonymous_012](https://user-images.githubusercontent.com/19481783/36346892-23a9f3c2-1406-11e8-9f96-2d56188132cd.jpg)
![anonymous_013](https://user-images.githubusercontent.com/19481783/36346893-23c0716a-1406-11e8-8a21-94f00313505c.jpg)
![anonymous_014](https://user-images.githubusercontent.com/19481783/36346894-23d4ab1c-1406-11e8-865b-c75a897d814a.jpg)
![anonymous_015](https://user-images.githubusercontent.com/19481783/36346895-23e96796-1406-11e8-9c8a-eefddaffdf0f.jpg)
![anonymous_016](https://user-images.githubusercontent.com/19481783/36346896-29168938-1406-11e8-9c37-4327210bae0b.jpg)
![anonymous_017](https://user-images.githubusercontent.com/19481783/36346897-292c3b52-1406-11e8-836d-f12d70b896a3.jpg)
![anonymous_018](https://user-images.githubusercontent.com/19481783/36346898-29418f66-1406-11e8-83f6-adca2c44ee8b.jpg)
![anonymous_019](https://user-images.githubusercontent.com/19481783/36346899-29579de2-1406-11e8-9d59-6200687bce05.jpg)

To get to the one (right side, order (left side, destruction)), simply jump onto the highest crate unmounted. Position your character just at the edge of the crate (backed up from the platform) to get a running leap. You do not need to use a mount or "Flee" to accomplish this leap. As stated above, this platform provides all the same advantages as the other. In addition with this platform, however, even though you can climb up both of the steampunk-like obstructions, with this one specifically, if you leap on the circular object, then onto pipe ejecting from the circular object, onto the square-like object with the rolled chain, lastly onto the dual pipes in the very corner - you have a strategic advantage point over many players if they are in your point of range and you can do very high amounts of damage to these players.

![anonymous_206](https://user-images.githubusercontent.com/19481783/36346902-40f004da-1406-11e8-8b2c-f8a615fcee3f.jpg)
![anonymous_207](https://user-images.githubusercontent.com/19481783/36346903-4105c838-1406-11e8-8346-9b7ec6699917.jpg)
![anonymous_208](https://user-images.githubusercontent.com/19481783/36346904-444cb560-1406-11e8-8964-fd3775830168.jpg)
![anonymous_209](https://user-images.githubusercontent.com/19481783/36346905-4464ebb2-1406-11e8-89cc-c86a74b2d978.jpg)
![anonymous_210](https://user-images.githubusercontent.com/19481783/36346906-4479e99a-1406-11e8-8534-12468ce880c4.jpg)
![anonymous_211](https://user-images.githubusercontent.com/19481783/36346907-448eafa6-1406-11e8-9a2b-2025617d6049.jpg)
![anonymous_212](https://user-images.githubusercontent.com/19481783/36346908-44a9aa90-1406-11e8-8067-6b4aa845675a.jpg)

Both of these platforms can be reached by both Destruction or Order forces. I added this one because may be the severity of this to whomever sees it as what, the platforms that replicate these on the opposite side of the map (since this map is somewhat mirrored), the platforms on the other side are blocked off unlike these on this side.

More to come...

**Comment by sioding** [comment] 2018-02-18 06:24
Duplicate of #11316

**Comment by sioding** [comment] 2018-02-18 06:24
Duplicate of #10262

**Closed by sioding** 2018-02-18 06:24 UTC

**Comment by sioding** [comment] 2018-02-18 06:29
Duplicate of #10262
