### ISSUE TITLE
GO 'Explosive Barrel' (Dragon's Blessing PQ) Thunder Mountain

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12089] opened 2018-07-27 02:20 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
expected - i think the barrel is supposed to be destroyed
actual - sometimes the barrel is destroyed then error given.
other times the barrel came close to death then stop taking damage.
"NullReferenceException was thrown from SpawnNPCFromGO.  This object will be destroyed."

Steps to reproduce the problem:
Dragon's Blessing PQ TM (dwarf)

Screenshots/Videos or archive.org evidences:

https://image.ibb.co/gFSKb8/barrel.png

**Comment by Lheana** [comment] 2018-07-27 10:40
The issue is real, but it does not prevent from completing the PQ as you have to destroy GOs 'Dragon Bones' to complete the first stage.

**Comment by sioding** [comment] 2018-07-28 08:13
fixed with patch from 27.07.2018

**Closed by sioding** 2018-07-28 08:13 UTC
Labels: Database, Fix Pending, World Object
