### ISSUE TITLE
[Interface] order and destruction chatting

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#328] opened 2014-07-23 17:56 UTC
Players from different realms can communicate with each other in the /say channel. This cannot be right.

People are setting up up fights and pushing/capping their reknown all day long... in fights where only one guy attacks and the other one doesn't even defend himself.

In case this server should even go live, you really have to do are rank/reknown reset.

**Comment by Evildoor** [comment] 2015-12-03 12:27
According to Azarael on forum, this can be fixed with 1 variable in server config. Regardless of the current state of the issue, this indicates that it is not a bug, but a feature that can be turned on/off. And there are reasons why crossrealm chat is allowed for now. Closing.

**Closed by Evildoor** 2015-12-03 12:27 UTC
Labels: Cannot Fix Yet
