### ISSUE TITLE
Tok time played is around 154 days ... but since something broke show 34415 days...

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11581] opened 2018-04-10 05:55 UTC
![thorbolt_175](https://user-images.githubusercontent.com/16274785/38538507-7e27ef82-3c94-11e8-8167-7646e4573ddc.jpg)

**Comment by sioding** [comment] 2018-04-10 06:31
Duplicate of #10421

**Closed by sioding** 2018-04-10 06:31 UTC
