### ISSUE TITLE
Potent Rejuvenating Draughts do not display AP restoration vaule.

### ISSUE THREAD

**Issue by Coffeecakes** [WarEmu/WarBugs#11688] opened 2018-04-29 07:06 UTC
Expected behavior and actual behavior: Like all other AP restoration potions, Potent Rejuvenation Draughts should display the AP they restore on their tooltip. Currently they do not display this value, leaving the area blank.

Steps to reproduce the problem: Hover over a Potent Rejuvenating Draught at any time.

Screenshots/Videos or archive.org evidences: 
https://imgur.com/a/0oJNsUR

**Comment by sioding** [comment] 2018-04-29 09:53
Duplicate of #10923

**Closed by sioding** 2018-04-29 09:53 UTC
