### ISSUE TITLE
Gunbad Mid (Could be other wings)

### ISSUE THREAD

**Issue by Adeno89** [WarEmu/WarBugs#16640] opened 2020-05-03 18:09 UTC
On the end boss 'Ard Ta Feed in the mid wing
you are able to release if you die and you respawn in the same room. Allowing the group to respawn and continue to kill the boss if any group member dies. 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-05-03 18:56
Duplicate of https://github.com/WarEmu/WarBugs/issues/16579.

**Closed by Kaelang** 2020-05-03 18:56 UTC
