### ISSUE TITLE
Charm/Tome

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#5285] opened 2016-04-10 15:14 UTC
Hello,

While I was equiping a new book, on my WP, I found out that the book was handle, by the character, upside down. I thought it might be just my character or my book but after looking at some other player, its the same. It's not a big issue, but it's kinda weird to give Sigmar's blessing with words upside down hah :)

Here are pictures 

(Mezaki is me and the other one is another player I checked in Altdorf)

Keep up the good work !

![mezaki_001](https://cloud.githubusercontent.com/assets/16641170/14411112/477a2552-ff0d-11e5-938f-5658febe42eb.jpg)
![mezaki_000](https://cloud.githubusercontent.com/assets/16641170/14411113/477b5698-ff0d-11e5-8638-05b727de0d03.jpg)

**Comment by Evildoor** [comment] 2016-04-10 17:07
If this affects all books then doubt that we can do anything here...

**Comment by genisaurus** [comment] 2016-04-12 18:30
Closing, not a bug with the server.

**Closed by genisaurus** 2016-04-12 18:30 UTC
Labels: Dubious
