### ISSUE TITLE
Destruction Sentinel Talisman Vendor: Only offering Ironbreaker Talismans

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18305] opened 2021-01-07 10:43 UTC
When sorting by useable items, he seemingly sells nothing...
![Bjarki_015](https://user-images.githubusercontent.com/53709160/103883449-84be7180-50dd-11eb-9479-315736edd918.jpg)

... but when showing all, he only sells Ironbreaker versions.
![Bjarki_016](https://user-images.githubusercontent.com/53709160/103883524-9c95f580-50dd-11eb-939b-536f53805fc3.jpg)

**Comment by Lithenir** [comment] 2021-01-07 18:22
Same for the Order vendor

**Comment by Acerexx** [comment] 2021-01-07 18:43
yep, bug for both sides, reported yesterday on here

**Comment by Lheana** [comment] 2021-01-10 14:16
Duplicate of #18296

**Closed by Lheana** 2021-01-10 14:16 UTC
