### ISSUE TITLE
Tor Anroc permament slow from lava (even after quitting the sc)

### ISSUE THREAD

**Issue by sniperseal** [WarEmu/WarBugs#12595] opened 2018-11-16 20:23 UTC
After falling into the lava in the Tor Anroc scenario, i found myself perma-slowed, even after the scenario ended. It was the second fall in the lava in the scanario so it might be something related to that.

**Comment by sioding** [comment] 2018-11-16 21:10
Duplicate of #12472

**Closed by sioding** 2018-11-16 21:10 UTC
