### ISSUE TITLE
Irregular Solo Ranked SC doesn't end the Scenario correctly

### ISSUE THREAD

**Issue by avalus** [WarEmu/WarBugs#16572] opened 2020-04-29 21:40 UTC
**Expected behavior and actual behavior:**

When an irregular (less or more than 6 players/team) Ranked SC is over, it should leave the scenario & disband the group.
At the moment, it ports you out, but the system considers you're still inside the scenario / combat, preventing you from requeuing or even leaving the game without crashing it.

**Steps to reproduce the problem:**

Let the system end an irregular Solo Ranked SC.

**Testing Screenshots/Videos/Evidences (always needed):**

![Enraptured_003](https://user-images.githubusercontent.com/6005224/80649548-8cb81300-8a72-11ea-91f3-664459ab6228.jpg)

**Edit**: additional information: logging out/crashing the game doesn't give _Quitter!_ debuff on relog

**Comment by Kaelang** [comment] 2020-04-30 13:39
This is a duplicate of https://github.com/WarEmu/WarBugs/issues/16562.

Closing.

**Closed by Kaelang** 2020-04-30 13:39 UTC
