### ISSUE TITLE
Stuck in Inevitable City/Dangerous Territory

### ISSUE THREAD

**Issue by Mezzkresh** [WarEmu/WarBugs#6185] opened 2016-05-18 18:01 UTC
Hey guys,

I´m currently playing a Black Orc lvl 24 and I right-clicked a portal while I was strolling around in the Inevitable City, which was supposed to teleport me to "Dangerous Territory" (If this has been an bugged issue before, I would like to clarify- the destination was not named on the portal.). Now, the terrain does not load, instead I am stuck in the order loggin lobby, with only my Black orc being listed in the foreground. If I click PLAY, the game freezes completely.

I would appreciate some help, guys, since this is my main char and, well, it´s pretty messed up....
I have some screenshots to illustrate my suffering.

![screenshot_003](https://cloud.githubusercontent.com/assets/19435237/15369518/381cd19c-1d33-11e6-8e1d-8d082f515663.jpg)

![screenshot_000](https://cloud.githubusercontent.com/assets/19435237/15369497/2378d01a-1d33-11e6-8869-6bc725fe6fa0.jpg)
![screenshot_001](https://cloud.githubusercontent.com/assets/19435237/15369500/250e158e-1d33-11e6-9537-5b0bb9fd446e.jpg)

Sincerely,

Richard

**Comment by Evildoor** [comment] 2016-05-18 18:08
Location of the portal? Also, use support forums and / or ask for GM help. Bugtracker does not deals with individual problems, so this ticket will at best lead to the portal fix or disable.

**Comment by Mezzkresh** [comment] 2016-05-24 11:34
GM´s are sending out messages that neither are they the personal advice channel, nor should players report bugs to them. This said bug has infected 3 of my chars now, a Zealot (19) and a Choppa (18). It is getting so bad, that I need up to ten or more login attempts to actually get in the game. I have not been at the same place/ portal with my Zealot or my Choppa as I was with my Black Orc, but I´m afraid this is a problem that is beginning to slowly spread through my whole account. I will notify the GMs, hope I don´t get smashed for it. Anyway, here are further screenshots of my "contaminated" chars, displayed at the Order page and the game freezing and crashing shortly after.

![screenshot_005](https://cloud.githubusercontent.com/assets/19435237/15502302/6faad0da-21b3-11e6-9c58-9c78813eadce.jpg)
![screenshot_004](https://cloud.githubusercontent.com/assets/19435237/15502310/7240db5a-21b3-11e6-8f3f-cb100ef52298.jpg)

**Comment by Mezzkresh** [comment] 2016-05-24 11:47
Edit: here is the exact location where all these problems started. I know,this might not belong here any longer.But if someone else is reading this, it might help: 

![cyrilfiggis_001](https://cloud.githubusercontent.com/assets/19435237/15502690/e55f952a-21b5-11e6-9508-f9e66ef5946c.jpg)
![cyrilfiggis_000](https://cloud.githubusercontent.com/assets/19435237/15502708/f5909c00-21b5-11e6-8a88-956edc753956.jpg)

(P.S.: It just got my Disciple of Khaine (12) too :(, can´t log in anymore... )

**Comment by Evildoor** [comment] 2016-05-24 12:50
Had this problem a week ago on my BO (but i had not used the portal, i simply crashed in a SC), /stuck during loading screen solved it for me. If GMs say that they cannot help you then use support forums.

**Comment by Mezzkresh** [comment] 2016-05-24 14:58
I have created a post there, thanks for the advice! However, /stuck does not help.

**Comment by Mezzkresh** [comment] 2016-05-27 16:20
Dropped it in there three days ago. Apparently, no one seems to give a crap. I´m at the end of the road, half of my chars are unplayable and not a single individual seems to be able or willing to help me...

**Comment by Evildoor** [comment] 2016-06-02 12:30
I presume that this was not caused by portal, just a random problem which somehow persists in your case despite /stuck and other things. Therefore, i'm closing this report (per my comment above, bugtracker does not deals with individual problems) and you should wait for response on forum. I feel your pain, but there is nothing i can do.

**Closed by Evildoor** 2016-06-02 12:30 UTC
Labels: Confirmation Request
