### ISSUE TITLE
Killing does not count Wyvern Matriarch on live event 

### ISSUE THREAD

**Issue by Gimmen** [WarEmu/WarBugs#16377] opened 2020-04-14 05:08 UTC
I killed Wyvern  5 or 6 times. 
Last time:
1. I myself found her.
2. I myself gathered a group and was a leader.
3. I made the last blow and did not use the pet.

Farlanda
![Farlanda_212](https://user-images.githubusercontent.com/36737290/79188196-133fe400-7e27-11ea-8729-a35cc361cd0b.jpg)
![Farlanda_213](https://user-images.githubusercontent.com/36737290/79188218-205cd300-7e27-11ea-89a3-aadfe7dec7a0.jpg)

 character name
I attach screenshots

**Comment by Vayra** [comment] 2020-04-14 07:52
Yep, seems like credit goes to a random party member. I had a group of friends 3 manning them and after 4 kills only I had gotten credit, at the 5th our tank got credit. It needs to be fixed to grant group credit or at least make sure credit goes to someone who doesn't already have it.

**Comment by Gimmen** [comment] 2020-04-14 09:40
Another similar situation today
![Farlanda_214](https://user-images.githubusercontent.com/36737290/79210152-13eb7100-7e4d-11ea-94f9-873df9dbba89.jpg)
![Farlanda_215](https://user-images.githubusercontent.com/36737290/79210174-1fd73300-7e4d-11ea-99df-42864753636e.jpg)

**Comment by Lheana** [comment] 2020-04-14 18:59
Duplicate of #16353

**Closed by Lheana** 2020-04-14 18:59 UTC
