### ISSUE TITLE
Scenario bug

### ISSUE THREAD

**Issue by Krokodeilos** [WarEmu/WarBugs#11648] opened 2018-04-21 18:46 UTC
Died during a scenario and could not respawn or even get a res. That was till end of scenario . 
![krokodeilos_006](https://user-images.githubusercontent.com/38592305/39087696-79b3fe74-45ad-11e8-8c74-e622026d89eb.jpg)

**Comment by sioding** [comment] 2018-04-21 20:10
Duplicate of #10682

**Closed by sioding** 2018-04-21 20:10 UTC
