### ISSUE TITLE
Rooting Out Corruption Quest

### ISSUE THREAD

**Issue by Bigolcrities** [WarEmu/WarBugs#1560] opened 2015-10-01 04:38 UTC
The Rooting out Corruption quest has you go to the innkeeper in Bohsenfels.  Innkeeper Bischof is nowhere to be found.  The inn, ie the building next to the mailbox door is unclickable if this it the inn.  Can you spawn the npc outside the inn if there is an issue with the building?

**Comment by Reggaewaldo** [comment] 2015-10-01 04:47
Duplicate of #1243 , We are currently working on getting the door fixed.

Closing.

**Closed by Reggaewaldo** 2015-10-01 04:47 UTC
Labels: Database, Low Priority, Quests, World Object
