### ISSUE TITLE
Can't buy medallion and emblem items in stack >1. 

### ISSUE THREAD

**Issue by Barbazol** [WarEmu/WarBugs#10897] opened 2017-11-22 20:08 UTC
Tried to buy another class's items in stack for salvaging (because it had needed stat).

Tried to buy 8 items at a time, after veryfing that i will never be available to use it all my medallions were gone and no items appeared. 
Checked on another medallion intendants too, doesn't work (another level items). And on another amounts more then one. At the end checked it on my own class's items - same result.

Also checked the same procedure on emblem items sellers.

If you try to buy one item at a time - it works of course.

Wasted enough low and high level medallions and emblems. 

Though it works normally with emblem and medallion packs in stacks (1 officer = 5 soldier, 5 = 25).

**Comment by sioding** [comment] 2017-11-22 21:04
Duplicate of #10703

**Closed by sioding** 2017-11-22 21:04 UTC
