### ISSUE TITLE
DoK Covenant of Tenacity

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12821] opened 2018-12-07 03:39 UTC
Expected behavior and actual behavior:
my Covenant of Tenacity is not increasing armor as much as it is supposed to.

Screenshots/Videos or archive.org evidences:
without it
![image](https://user-images.githubusercontent.com/44329952/49626381-3ccd3d80-f99f-11e8-8327-0cdb497b9145.png)

with it
![image](https://user-images.githubusercontent.com/44329952/49626395-4d7db380-f99f-11e8-9669-73f1a8ed1791.png)

**Comment by sioding** [comment] 2018-12-07 06:47
let me guess: you have used a armor pot?

**Comment by Xicoz** [comment] 2018-12-07 23:54
yes sir I did

**Comment by Torquemadra** [comment] 2018-12-08 01:14
it doesnt stack with armour potions, whichever is greater will be the value you gain

**Comment by sioding** [comment] 2018-12-08 09:32
So you got your answer - its not a bug - i close this report here.

**Closed by sioding** 2018-12-08 09:32 UTC
Labels: 2 Week Ultimatum, Confirmation Request
