### ISSUE TITLE
Order keep jumping to five star from zero in 3 minutes

### ISSUE THREAD

**Issue by Tyrpak** [WarEmu/WarBugs#11232] opened 2018-01-29 15:42 UTC
Expected behavior and actual behavior:
Yesterday evening Avelorn produced strange behaviour in RVR: Destro had an unsuccessful siege of the order keep, both doors were taken down. Destro had all 4 BOs and 3 stars.
Then order took 2 BOs, which caused the server to give them 1 star in around a minute, followed by closing of the door, where it jumped immediately to 3 stars, and still with only 2 BOs, 4 complete, than 5 stars, in less than 3 minutes.
The bugs followed: order had multiple rams deployed. While destro lost 2 rams crossing the zone, order had no such problem...
In the end after one of the times order hit destro keeps door, the server locked the zone for stalemate, with order victory.

**Comment by sioding** [comment] 2018-01-29 15:45
Duplicate of #11033

**Closed by sioding** 2018-01-29 15:45 UTC
