### ISSUE TITLE
Great Weapon Ironbreaker

### ISSUE THREAD

**Issue by Mastodonicus** [WarEmu/WarBugs#1998] opened 2015-11-27 06:04 UTC
I have a great axe from a quest reward in badlands that is not registering as a great weapon to trigger talents and abilities. I cannot use Cave in as the game is not registering that I have a great weapon equipped for example. I've tried swapping it on and off and relogging.

![mastosaurus_001](https://cloud.githubusercontent.com/assets/16042188/11434934/75733d66-94a2-11e5-86c8-6ecd9151e583.jpg)

**Comment by Meralors** [comment] 2015-11-28 09:28
I checked on dev and the axe is a great weapon and you can use skill that require great weapons.
Maybe it will be fixed with next patch.

**Comment by Evildoor** [comment] 2015-12-18 13:09
Closing since @Meralors have tested this and we can't do much if it's impossible to reproduce the bug.

**Closed by Evildoor** 2015-12-18 13:09 UTC
Labels: Could Not Reproduce, Database, Item
