### ISSUE TITLE
Festering Arrow Owerpowered

### ISSUE THREAD

**Issue by cervaes** [WarEmu/WarBugs#2123] opened 2015-12-05 08:24 UTC
Sorry to write this ticket, but i think its not normal what happening here with festering arrows!
I dont even remember festering arrow critted on live (lvl 40) 4700, but now i see every SW opening with this skill and critting 4000-5000 . I cant eved defend against, because it is my whole hp!
You think its good so?

**Comment by Tesq** [comment] 2015-12-05 09:30
4k? i saw 2x2k crit fest arrow in row on my dok some days ago (3 shoot down without being able to do nothing). but i never saw 4k x single fest arrow atm, on live at rr90-100 there was  screen of a mara hitted for crit 9k with out Trivial Blow.

**Comment by cervaes** [comment] 2015-12-05 09:37
I will take a screenshot next time. But i remember Otmolet crits me last night 4600 or so.

**Comment by ozarmidrashim** [comment] 2015-12-05 12:28
Assume 600 BS post-Toughness mitigation.

FA base rank 31: ~724
Cast time 3, damage scaling 1 => (600/5) * 3 = 360

Weapon DPS: 42.0 + (42.0 * 0.46) * 3 ~= 100

724 + 360 + 100 = 1184:

Critical hit * 1.5 = 1776
Unshakable Focus * 2 = 3552

Hmm...

**Comment by milosxe** [comment] 2015-12-05 12:45
Don't forget the Vengeance of Nagarythe buff.

Are you sure that's how UF works? I thought that it only doubled base dmg. Don't take my word for it, but iirc if my crit without UF was for lets say 1k, it never gave me 2k with UF but less on same target.
I'll have to look into it.

**Comment by cervaes** [comment] 2015-12-05 12:46
Here is a pic for a lvl 26 SW festering crit:http://imageshack.com/a/img907/1297/qDr8ot.jpg
And what happens if he is lvl 31 and max gear?

**Comment by ozarmidrashim** [comment] 2015-12-05 12:58
You may be right, milosxe:

http://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=879#p10393

**Comment by Tesq** [comment] 2015-12-05 15:10
it woul matter in reality but it of course go that way, the problem if fest arrow always was that it have no % reduction and so his damage stack too much better then it supose to do.
Anything that ingore a 100% of a thing can easily go out of hands, expecially if the hit came from no where and have no real counter (cos dodge it's a counter only when a chosen have a permanent hold the line due to ap regen).

**Comment by Qrazy** [comment] 2015-12-05 15:22
FA has a 110ft range, not 150. It also requires a M2 AND a crit to reach those numbers.

**Comment by Evildoor** [comment] 2015-12-05 15:23
I agree with @Tesq. Is Festering Arrow + Enchanted Arrows too strong? Yes. But it is balance issue, not a bug, so should be discussed on forums. Closing.

**Closed by Evildoor** 2015-12-05 15:23 UTC
Labels: Confirmation Request
