### ISSUE TITLE
Guild Heraldry Reserved But Was Never Touched

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#12479] opened 2018-10-22 07:51 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Expected to reach guild rank 10 and create a Guild Heraldry. Actual behavior of heraldry link is and has always been reserved thus causing it not to work. No one but guild leader has access to Heraldry and he has not touched it.

Steps to reproduce the problem:
Create a guild get it to level 10

Screenshots/Videos or archive.org evidences:

![onemantankwall_005](https://user-images.githubusercontent.com/43802105/47282500-26148800-d5a5-11e8-9159-5aa9a2aaab31.jpg)
![onemantankwall_006](https://user-images.githubusercontent.com/43802105/47282539-4c3a2800-d5a5-11e8-9077-cdae933b2264.jpg)

**Comment by sioding** [comment] 2018-10-22 15:58
Duplicate of #10417

I bring this together with the linked report. Yes we have a heraldry problem, but its not in the top10 of the priority list. Thanks for the report anyway - we will get on it if its the for it.

**Closed by sioding** 2018-10-22 15:58 UTC
