### ISSUE TITLE
Talisman of armor 164 missing of the backpack

### ISSUE THREAD

**Issue by Diskete** [WarEmu/WarBugs#16140] opened 2020-03-29 13:39 UTC
Hello, I have a problem, I have crafted a talisman of armor with a purple fragment of lv 200 and made me a superior talisman of mastersmith of 164, but it is not in my inventory,  in the chat log it appears as if a superior talisman of mastersmith has been created but it is not in the inventory.
Unfortunately I couldn't do a screenshot because I restarted to see if the problem was solved but it will be easily checked by looking at my account logs.
The name of my char is Dizparate.

Regards.

**Comment by Kaelang** [comment] 2020-04-19 23:00
Do you have screenshots of the chat as well as your inventory? And any further steps to help replicating this issue?

**Comment by Diskete** [comment] 2020-04-20 00:14
I didn't take any screenshots, but when I made the talisman I had a full inventory.

**Comment by Kaelang** [comment] 2020-04-20 01:47
Sounds like a duplicate of https://github.com/WarEmu/WarBugs/issues/9122.

Will mention this report in the original.

**Closed by Kaelang** 2020-04-20 01:47 UTC
Labels: 2 Week Ultimatum, Confirmation Request
