### ISSUE TITLE
Skaven Cloak not working as appearance!

### ISSUE THREAD

**Issue by highhold** [WarEmu/WarBugs#19266] opened 2021-06-30 05:21 UTC
--> An item from quite a long ago: 
![Skaven Cloak](https://user-images.githubusercontent.com/23463427/123905726-392ca800-d949-11eb-8d8f-f10dfec40941.png)
 doesn't have its appearance working properly for others, only when i actually equip the item it shows the correct appearance!

**Expected behavior** : appearance should show for everyone.
**Actual behavior**: Appearance only shows for me.

**Steps to reproduce the problem**: Use the Skaven Cloak as appearance!

**Testing Screenshots/Videos/Evidences (always needed):**
Friend's Perspective : 
![IB Cloak (Friend's view)](https://user-images.githubusercontent.com/23463427/123905483-d1765d00-d948-11eb-9775-21d79eac9066.png)

My perspective : 
![IB Cloak (my view)](https://user-images.githubusercontent.com/23463427/123905859-7f820700-d949-11eb-95ff-cf3bff56ce9d.png)

Also tested on my other characters and it had the same result!

**Comment by lilimx** [comment] 2021-06-30 07:15
Hey,

thank you for your ticket.
Quick question your friend was on the same realm as you?

**Comment by highhold** [comment] 2021-06-30 07:50
> 
> 
> Hey,
> 
> thank you for your ticket.
> Quick question your friend was on the same realm as you?

Oh, we were in the same Realm, yes!

**Comment by CrimsonFenris** [comment] 2021-07-02 17:15
Confirmed issue with a guildie, see sceenshots from each player's perspective : 
![Appearance_bug_Feon](https://user-images.githubusercontent.com/40425011/124308465-9dc64d80-db69-11eb-9f53-1a64b72b055f.jpg)
![Appearance_bug_Kapla](https://user-images.githubusercontent.com/40425011/124308480-a1f26b00-db69-11eb-8c9a-c557e9bd3c32.jpg)

Other items shows correctly for appearance (WH have the Onslaught body on top of the Sov, for instance), only cloak's appearances seem affected.

**Comment by highhold** [comment] 2021-07-05 17:17
> 
> 
> Confirmed issue with a guildie, see sceenshots from each player's perspective :
> ![Appearance_bug_Feon](https://user-images.githubusercontent.com/40425011/124308465-9dc64d80-db69-11eb-9f53-1a64b72b055f.jpg)
> ![Appearance_bug_Kapla](https://user-images.githubusercontent.com/40425011/124308480-a1f26b00-db69-11eb-8c9a-c557e9bd3c32.jpg)
> 
> Other items shows correctly for appearance (WH have the Onslaught body on top of the Sov, for instance), only cloak's appearances seem affected.

Yes! i noticed a lot of ppl with cloaks appearances that do not show what it should, maybe its a general cloak problem ?

**Comment by redwolf777x** [comment] 2021-08-08 10:38
This applies to dyes on most sov cloaks also, with it only showing on your client and vanilla colours for other people

**Comment by dalen** [comment] 2021-09-14 07:40
duplicate of #18556

**Closed by dalen** 2021-09-14 07:40 UTC
Labels: Item, Visual
