### ISSUE TITLE
T3 RVR Purple bag did not arrive in mail

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#9469] opened 2017-04-14 16:07 UTC
Hello,

I was playing on my Slayer Dugald today and we took the zone BFP/Badlands in T3 and i won a purple bag, it did not arrive in the mail.

All i can add to the circumstance is that i was holding supplies when the zone locked and then proceeded to High pass by flight master, so maybe one of those things effected it, i don't expect to get my bag but thought you should know.

**Comment by Luth-RoR** [comment] 2017-04-23 14:00
Do you know if you were in the loading screen when the timer of the chast ran out?

**Comment by IxanderousI** [comment] 2017-04-25 12:45
Yes i believe i was, the thing is, i have noticed that the bags sometimes arrives before the timer is finished so, i think i already started to suspect something was up before taking the flight master.

**Comment by Luth-RoR** [comment] 2017-04-25 15:55
Just asking because https://github.com/WarEmu/WarBugs/issues/7638
Maybe others who won but never got a bag per mail can remember and post here wether they ported to a different location or not.

**Comment by IxanderousI** [comment] 2017-04-25 17:10
Yeah, the only significance was that i was carrying supplies when the zone locked and then ported to highpass but i think i was already suspicious of it not arriving before porting because it typically tends to arrive toughly 15 seconds before the timer runs out for me.

**Comment by ShoxRethgor** [comment] 2017-04-25 22:14
Had the Same thing Happen in T4 CW Zone Lock last night. Won a green bag and it never got mailed. It was a guild run and I flew to Alt so i can get my bag and warrant to complete my Seer Set before we moved to next zone.

**Comment by sioding** [comment] 2017-10-20 11:21
Duplicate of #10279

**Closed by sioding** 2017-10-20 11:21 UTC
Labels: Confirmation Request
