### ISSUE TITLE
All the quests were deleted

### ISSUE THREAD

**Issue by Likkusya89** [WarEmu/WarBugs#15423] opened 2020-01-05 17:58 UTC
Today after restart all my quests were deleted. So i need to do for example Gundbad 3 times again. Even if i've made it already 2 times. 
Nickname Likkusya

**Comment by raptrr** [comment] 2020-01-05 18:10
Does the ToK got reset as well?

**Comment by Likkusya89** [comment] 2020-01-05 18:12
Yes. All the ToK



Отправлено из мобильной Почты Mail.ru


воскресенье, 5 января 2020 г., 21:10 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by raptrr** [comment] 2020-01-05 18:13
Duplicate of #15371

**Closed by raptrr** 2020-01-05 18:13 UTC
Labels: Tome of Knowledge

**Comment by Likkusya89** [comment] 2020-01-05 18:15
So what should I do? 



Отправлено из мобильной Почты Mail.ru


воскресенье, 5 января 2020 г., 21:13 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by raptrr** [comment] 2020-01-05 18:17
There is nothing you can do right now, it might fix itself on restart / server restart. More I cannot tell right now
