### ISSUE TITLE
No Renown XP after locking Caledor

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13416] opened 2019-02-20 09:04 UTC
Order side locked Caledor just now and there is no renown xp reward for locking, Only a bag roll

**Comment by bugsformount8** [comment] 2019-02-20 09:08
Apparently you don't get any metals or seals also

**Comment by bugsformount8** [comment] 2019-02-20 09:10
Also last note, I'm sure you don't get XP and rewards for locking Black Crag also. I'll confirm if and when we lock BC

**Comment by sioding** [comment] 2019-02-20 12:25
I merge these two reports cause it seems to be an iessie for all zones before the fortress
Duplicate of #13413

**Closed by sioding** 2019-02-20 12:25 UTC
