### ISSUE TITLE
Influence ticks during Altar of Madness PQ 1 stage

### ISSUE THREAD

**Issue by Melisandrea** [WarEmu/WarBugs#9768] opened 2017-06-05 12:34 UTC
During starting stage Altar of Madness PQ (empire ch22) sometimes u get like 2-3 ( each 150 influ) influence ticks after killing just 1 mob.

**Comment by Razielhell** [comment] 2017-06-05 14:28
> Hargrim
> - Added functionality that allows counting multiple NPCs for the same stage of PQ. More work for DB team.
Maybe this?

**Comment by grunbag** [comment] 2017-06-07 14:02
Might be fixed on next patch

**Comment by Gnashspike** [comment] 2017-06-11 12:44
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Melisandrea [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UA3NLMERTSADTEDFABHMJZSML76AFMAH4XVTD7DQBVG2IEDQRQ32LZGNAQACXEFN6FKPYAKMBJSBIVOVTGSSDH4UML4W2AN6OBBHL5HIICACVEIKQAOYAOQAEYAAYAAGAAWAKJR5AF2QCNIA3RSIC4JIOLYQREAAQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 05:43:18 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp i6si1596017ybj.485 - gsmtp:
    retry timeout exceeded

**Comment by Razielhell** [comment] 2017-10-14 12:44
CLosing then.

**Closed by Razielhell** 2017-10-14 12:44 UTC
Labels: Confirmation Request, Database, Public Quests
