### ISSUE TITLE
Goblin Green Dye - Multiple Versions

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#20571] opened 2022-11-23 05:33 UTC
**Expected behavior and actual behavior:**
Goblin Green Dyes will stack.  Three unique stacks of less than 40 items will not combine.

**Steps to reproduce the problem:**
Placing items in personal bags and dividing stacks will not combine.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tag_010](https://user-images.githubusercontent.com/38359697/203475108-87a5aeeb-bfd2-4289-a77a-4f467e07a2d8.jpg)

**Comment by lilimx** [comment] 2022-11-23 06:33
Hey,

Im a bit confused. Could you do some pics of the other 2 stacks as well.

**Comment by Purveyorofhamsters** [comment] 2022-11-23 14:31
I think the issue is that there are 3 different types of Goblin Green dye, they look the same, but they do not stack.

Does the video help?

https://user-images.githubusercontent.com/116272122/203572404-6df5d551-e228-4367-950c-b4b4bcac73cf.mp4

**Comment by bosli42** [comment] 2022-11-24 20:58
there are other dyes that are duplicates with different item IDs, but I think some of them got fixed in the recent changes to dyes.
do /debug and post the different item IDs of the same greens for easy fix

**Comment by tog89** [comment] 2022-11-24 22:48
How do I get debug to show item ids?  It only shows the Window Slot Number.

**Comment by bosli42** [comment] 2022-11-24 22:50
you have to link the item in chat and open the item popup, then hover over it and the debug window will show you the item ID

**Comment by tog89** [comment] 2022-11-24 23:20
Thanks,  Items ids in debug are:

EA_ItemLinkWindow188904
EA_ItemLinkWindow188924
EA_ItemLinkWindow188953

**Comment by lilimx** [comment] 2022-11-25 06:36
Hey,

Already talked to Ekalime. He will check that later.

**Comment by ekalime** [comment] 2023-02-17 20:02
It isn't a pretty solution, but dyes with IDs  188924 and 188953 decay into 188904. This will allow them all to stack. If the item was in a bank vault it'll say 'decays in 1s' and theoretically have its old ID until you move it (into your bag, into another bank slot)

**Comment by lilimx** [comment] 2023-02-26 18:02
Fixed with patch 24/02/2023

**Closed by lilimx** 2023-02-26 18:02 UTC
Labels: Database, Item, Fix Pending
