### ISSUE TITLE
quest npc missing

### ISSUE THREAD

**Issue by bobeer86** [WarEmu/WarBugs#1455] opened 2015-09-19 23:50 UTC
ostland, destro wc - 150kill quest npc is missing, cant turn in or take this is war quest

**Comment by Evildoor** [comment] 2015-09-20 07:36
Confirmed. Order NPC is present, Destro NPC is missing.

**Comment by Reggaewaldo** [comment] 2015-09-20 09:11
This has been resolved now, probably after a server restart since the error is not DB related.

This can be closed.

**Comment by Evildoor** [comment] 2015-09-23 16:36
Reopening this, since now Coris Bladeborn is missing in the same warcamp, and i do believe that this is the same problem.

**Comment by Evildoor** [comment] 2015-09-23 17:35
Well, he is back now, after restart, but i think we should understand the cause of this problem before closing it.

**Comment by Reggaewaldo** [comment] 2015-09-30 05:16
I have now deleted his spawn, then readed it to the DB. Hopefully this will have some effect. What I'm guessing is hapening is that the server does not pull him from the DB, this is rather strange but hopefully this should fix that issue if it's related to the DB entry of his spawn.

Now we will keep this open for a while until we have confirmed working.

**Comment by Evildoor** [comment] 2015-09-30 07:25
Another guess - when i've seen Coris for the last time, he was lvl 1, unlike most other NPC, and he also stands somewhat close to the warcamp edge. Maybe he was sniped by some order player, and just has a long respawn time? (it's just a guess, i've not tested if this is possible or not)

**Comment by Reggaewaldo** [comment] 2015-10-02 08:24
In that case it's most likely that it's a DB issue. I would have to recreate him in that case since it might be that the row in the DB is not correctly refered to after som runtime. Did you notice if he was wearing armor when he was lvl 1 ?

**Comment by Evildoor** [comment] 2015-10-02 09:25
He was, IIRC. Checked now - yes, he is lvl 1 and wears armor.

**Comment by Reggaewaldo** [comment] 2015-10-02 09:55
I'm in on the live server checkin him now. He is actualy level 1 in the DB. So i changed that to reflect the other NPC's

**Closed** 2015-10-02 09:55 UTC
Labels: Database, Fix Pending, NPC
