### ISSUE TITLE
[quest]Time Ta Rally - broken item reference

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11046] opened 2017-12-23 18:42 UTC
Nothing important. There's just a broken item reference in the description. I assume the quest objective was removed but not the quest itself.

![time_ta_rally2](https://user-images.githubusercontent.com/13544944/34321891-42ddf4d2-e819-11e7-840d-14d9544fbf58.PNG)

**Comment by Tyramissoux** [comment] 2017-12-23 18:44
argh...remove this. Just saw a ticket for a quest like that. My bad.

**Comment by sioding** [comment] 2017-12-23 18:51
Duplicate of #11018

**Closed by sioding** 2017-12-23 18:51 UTC

**Comment by Lheana** [comment] 2017-12-23 18:53
In fact this is not exactly the same quest. I assume this one is for destro and the other for order. Thus the questID are not the same.

**Comment by sioding** [comment] 2017-12-23 21:10
thumbs up - this report is linked on the other - even if this one is destro and the other is order i don´t think we need two reports for this
