### ISSUE TITLE
Scenario flags bug

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#3787] opened 2016-01-16 17:54 UTC
Sorry the screenshot didn't save. But there's a bug of some sort in this scenario that allows you to prevent the flag from being capped by a side, nobody on the flag except Destro, the flag bugs out and caps to order then can't be de-capped.  I'll try and get another screenshot if I see it happen again.

**Comment by gittoaster** [comment] 2016-01-17 00:29
It kind of sounds similar to the bug when a dead person doesn't release but he continues to build the Objective while dead.  Did u notice any bodies there?

**Comment by vove-RoR** [comment] 2016-01-17 12:55
I am not sure if this is what you are talking about but if it is it is only visual.

Happened few times to me, flag was ours but standing on it caused he progress bar to empty and refill again. This is only visual and you get regular amount of the points over time and you don't receive the points for capture.

It looks like you would be able to recap the BO you have already capped.

**Comment by Luranni** [comment] 2016-01-22 10:49
No there were no points being gained from the flag.

**Comment by tutti13** [comment] 2016-01-25 20:10
Same issue occurs also in other scenarios. Workshop-Flag in Reikland factory was capped by destru and we coulnd't recap it.

**Comment by vove-RoR** [comment] 2016-01-30 16:18
It happened to me yesterday in Gates of Ekrund playing as destro and I can confirm it was only visual. We couldn't recap our flag, on map BO appeared as controlled by Order, the flag on the bo was also blue.

Basically Order controlled 1 point and the "bugged" one. Destro controlled mid only (that's how it appeared on map). Yet we were receiving more points than Order did and eventually won the match, thus I am sure the point we couldn't cap was already marked as ours and only appeared as belonging to Order.

It seems to be same issue as the one happening with BOs in RvR when you cap BO as Order and on map it appears as assaulted by Destruction, it also prints a message that the forces of Destruction were the ones to cap it, not Order which is extremely confusing.

Not counting the confusion it causes it doesn't affect the gameplay that much.

**Comment by tutti13** [comment] 2016-01-30 17:16
No, the bug we are talking about is not only visual. 

We lost Temple of Isha several times because the flag could not be tapped although we were dominating destru and stood around the flag.

Yet destru won as the flag ticked for them.

**Comment by Torquemadra** [comment] 2016-02-15 02:41
Also seeing this on occasion, opposition controlled flag, no enemies around, bar rises as if control is to be relinquished and nothing happens, control remains with the opposition realm. No opposition players living or dead in the vicinity.

**Comment by Evildoor** [comment] 2016-06-02 16:24
Possibly connected with lags / packet corruption / something like that. Had this bug today, there was a KotBS on a point who lagged for some time, then he disappeared and message was written that he disconnected uncleanly. After that, point was impossible to capture for destro, and captured itself for the order side when destro left it.

**Comment by runebbb** [comment] 2016-08-26 23:54
just adding this 
![baroz_007](https://cloud.githubusercontent.com/assets/20157418/18023409/29b2b800-6bf9-11e6-8a89-1e697db26693.jpg)

**Closed** 2022-10-26 10:53 UTC
Labels: Scenarios
