### ISSUE TITLE
No scouting credit for Ice Hearth Crossing in Kadrin Valley

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18871] opened 2021-04-20 19:36 UTC
**Expected behavior and actual behavior:**

Trying to do the scouting quests for Ice Hearth Crossing in KV (and the repeatable one for all 4), I can't get credit for Ice Hearth Crossing. Roaming all around the flag, every inch of the cave doesn't give credit.

**Steps to reproduce the problem:**

1. Pick up the destro scouting quests in KV: Feets in Da Snow! and Get Data Stunty Tunnel!
2. Go to the Ice Hearth Crossing battlefield objective, see whether you can find a location that gives you credit for scouting, because I couldn't

It's hard to get a good screenshot to show this, but here's one showing me on the map with the quest still not cleared.
![Screen Shot 2021-04-20 at 3 29 32 PM](https://user-images.githubusercontent.com/77587188/115453172-5298d180-a1ed-11eb-89e6-c32d04ddb096.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Delegator2** [comment] 2021-04-20 21:24
Additional screenshots showing me on the flag and in the upper right you can see that I haven't received quest credit. 
![Screen Shot 2021-04-20 at 4 52 45 PM](https://user-images.githubusercontent.com/77587188/115465912-4ae12900-a1fd-11eb-9cf8-da47d4c99898.png)
![Screen Shot 2021-04-20 at 4 52 36 PM](https://user-images.githubusercontent.com/77587188/115465914-4c125600-a1fd-11eb-905d-99fe0085a4ca.png)

**Comment by MissHazard2006** [comment] 2021-04-22 04:04
Had same issue

**Comment by Lheana** [comment] 2021-04-26 14:42
Duplicate of #18591

**Closed by Lheana** 2021-04-26 14:42 UTC
