### ISSUE TITLE
set brawler

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12572] opened 2018-11-11 22:31 UTC
Expected behavior and actual behavior:

excpected when wearing the three brawler jewels to have stats activate +4 morale

actual behavior nothing happen
i tryed to move the place of the jewels but nothing happens either

Steps to reproduce the problem:

wear the 3 jewels

![capture d ecran 32](https://user-images.githubusercontent.com/44948395/48319097-9d1fc800-e609-11e8-8a7b-8b66e74e73da.png)
![capture d ecran 33](https://user-images.githubusercontent.com/44948395/48319098-9d1fc800-e609-11e8-9cfa-7b5c8dec0984.png)
![capture d ecran 34](https://user-images.githubusercontent.com/44948395/48319099-9d1fc800-e609-11e8-927c-63161b4a1ac8.png)

Screenshots/Videos or archive.org evidences:

**Comment by Oceanman69** [comment] 2018-11-12 01:19
i tryed without addons same result
other friends got the same problem

**Comment by Oceanman69** [comment] 2018-11-12 02:42
and bug only with the brawler set

**Comment by Kaelang** [comment] 2020-04-22 00:05
This is a bug - but not in the sense of this report.

The edited language files are stopping the client from realising that you have the 3 piece set worn. Although visibly, you do not see the set bonus in effect, if you type .getstats and review, you will notice that sets do come into effect.

I am going to close this for now as someone previously has confirmed the set is working as intended.

**Closed by Kaelang** 2020-04-22 00:05 UTC
