### ISSUE TITLE
[Magus] Incorrect % displayed on tooltip for daemons

### ISSUE THREAD

**Issue by R3xz** [WarEmu/WarBugs#16335] opened 2020-04-10 07:03 UTC
![Screenshot_4](https://user-images.githubusercontent.com/8356666/78970163-87902580-7abd-11ea-8860-6055e29e5499.png)

All magus pets are showing half the damage % boost (20% instead of 40%) in the tooltip, even though the damage buff shows 40% at 8 stacks. Hopefully get fixed soon to prevent confusion to newer players.

**Comment by Kaelang** [comment] 2020-04-19 16:43
Duplicate of https://github.com/WarEmu/WarBugs/issues/13094.

**Closed by Kaelang** 2020-04-19 16:43 UTC
