### ISSUE TITLE
Gold Bag Reward : Witch Hunter given Chosen gear

### ISSUE THREAD

**Issue by ArrDub** [WarEmu/WarBugs#14638] opened 2019-07-24 19:44 UTC
![Whirly_000](https://user-images.githubusercontent.com/19254092/61823784-54174900-ae11-11e9-9ab9-cb989c639c2e.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

My Level 17 Witch Hunter received a gold bag reward from RvR.  
Inside was a CHOSEN chest piece.   See screenshot.

**Steps to reproduce the problem:**

Unknown

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment] 2019-07-24 19:52
Duplicate of #11739

**Closed by sioding** 2019-07-24 19:52 UTC
