### ISSUE TITLE
Dolgrund's Cairn  Supply

### ISSUE THREAD

**Issue by Svenalld** [WarEmu/WarBugs#16099] opened 2020-03-25 11:45 UTC
**Expected behavior and actual behavior:**

The supplies for Dolgrund's cairn in Kadrin Valley are spawining in the ground , cant pick them up, can pick them up sometimes if the box spawns far enough out of the ground

**Steps to reproduce the problem:**

Capture the flag and wait for supplies to respawn

**Testing Screenshots/Videos/Evidences (always needed):**

![Capture](https://user-images.githubusercontent.com/62649544/77533018-01a19700-6e8e-11ea-8cfb-ba6e6ab0a7d5.PNG)

**Comment by dalen** [comment] 2020-04-06 11:26
Duplicate of https://github.com/WarEmu/WarBugs/issues/14767

**Closed by dalen** 2020-04-06 11:26 UTC
