### ISSUE TITLE
A Lord's Game/Griffon Gate PQ malfunction

### ISSUE THREAD

**Issue by Antarchus** [WarEmu/WarBugs#11054] opened 2017-12-25 02:48 UTC
At Griffon Gate PQ in Shadowlands, there are no Griffon Guards or Defenders (needed to continue Lord's Game epic quest).  There are also no Eagle Claws available to advance the PQ.

**Comment by sioding** [comment] 2017-12-25 06:52
Duplicate of #10862

**Closed by sioding** 2017-12-25 06:52 UTC
