### ISSUE TITLE
War Mount

### ISSUE THREAD

**Issue by Hourglass1** [WarEmu/WarBugs#12510] opened 2018-10-28 21:18 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Summon mount upon using ability. 
Actual behavior is that no mount is summoned.

Steps to reproduce the problem:
After I completed the LOTD quest, whenever I pressed the summon ability (=), a mount is not summoned. It does not give me an error, but it does not show the cast bar for the ability either.
It is a 100 gold mount and I am a level 38 magus named Hourglass. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-10-29 18:59
Duplicate of #12184

**Closed by sioding** 2018-10-29 18:59 UTC
