### ISSUE TITLE
[Zealot] Tzeentch's Cordial

### ISSUE THREAD

**Issue by alubert** [WarEmu/WarBugs#14190] opened 2019-05-26 10:57 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Tzeentch's Cordial dont crit at all after pach.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment] 2019-05-26 11:44
Please add your testing screenshots

**Comment by alubert** [comment] 2019-05-26 14:19
![Hurubek_000](https://user-images.githubusercontent.com/51048211/58383027-f497eb00-7fd1-11e9-952d-b2d69c999351.jpg)

**Comment by sioding** [comment] 2019-05-28 08:26
Duplicate of #14243

**Closed by sioding** 2019-05-28 08:26 UTC
Labels: 2 Week Ultimatum, Confirmation Request

**Comment by Ghatisgob** [comment] 2019-05-28 20:02
I tested it also and the HoT never crits
