### ISSUE TITLE
blastpotions do not obey line of sight

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#13161] opened 2019-01-17 19:51 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Blasting post can be cast through walls, clip atatched in IC through wall but equialy easy to throw them through keep walls at defenders in range
Expected behavior and actual behavior:

Basting pots should not be able to be cast through walls

Steps to reproduce the problem:

target enemy behind a wall in range and throw the pot

Screenshots/Videos or archive.org evidences:
for easy i took video in IC rather than at a keep

https://youtu.be/XGBvEdh_IPQ

**Comment by sioding** [comment] 2019-01-18 06:59
The video isn´t available. Can you please reupload it ?

**Comment by gittoaster** [comment] 2019-01-18 17:46
I confirmed.
screenshoted
https://ibb.co/6Xvz9bj

**Comment by sioding** [comment] 2019-01-19 16:32
Shit - just saw another open report for it. So i will close this one bu its merged with the older one - your screenshots and the video is helpful and will be seen when a dev pulls this ticket.

**Comment by sioding** [comment] 2019-01-19 16:32
Duplicate of #11483

**Closed by sioding** 2019-01-19 16:32 UTC
Labels: 2 Week Ultimatum, Confirmation Request
