### ISSUE TITLE
Beastlord Token

### ISSUE THREAD

**Issue by stealthc98** [WarEmu/WarBugs#16158] opened 2020-03-31 02:55 UTC
Class: Black Orc
Char:  Whutang
BL token disappeared after server restart.  Have visited all quest NPCs, and no quests are available.  Can post pics of having all gear but the pocket ofc.  I post this in hope in the future you get the capability to restore items and/or quests.  Maybe even add a repeatable kill quest to one or all for the coins.

**Comment by Kaelang** [comment] 2020-04-19 20:19
Currently there is no restoration feature in place. As the Beastlord Quest line is working as intended, I'm going to go ahead and close this report.

**Closed by Kaelang** 2020-04-19 20:19 UTC

**Comment by stealthc98** [comment] 2020-04-24 13:23
The questline may be working as intended, but server stability is not.  At the time of this incident there was a crash and a rollback deleting one of my coins, and the quest is now unattainable as it has already been completed.  A simple solution would be to make the kill quests repeatable.  I understand that you do not possess the power to restore items and/or quests.  I was hoping this would stay open in hopes that the repeatable quest option would be implemented.

**Comment by Kaelang** [comment] 2020-04-24 13:36
Appreciate the reply - the Bugtracker is here for live issues and in-game problems. The server stability / crash is not technically a bug, it's a project that is being worked on consistently as each patch comes through. 

We know that the crashes cause problems like this and the focus is currently on making sure there aren't crashes to stop this happening.

The suggestion is a good one, however the Bugtracker isn't the place for suggestions, your best bet is using the forums here: https://www.returnofreckoning.com/forum/viewforum.php?f=15
