### ISSUE TITLE
Nordenwatch SC:  Fortress Flag is bugged

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1913] opened 2015-11-23 16:48 UTC
Fortress flag does not uncap from the initial side that takes it.  (I.e. order take the flag at beginning of SC - it can not be uncapped and taken by other team.  Bugged and stays order taken despite entire destro group standing on it alone for 2 mins).

**Comment by Evildoor** [comment] 2015-12-08 10:54
It seems that this has some kind of condition, because i've played numerous Nordenwatchs after this report and Fortress was behaving properly.

**Comment by Evildoor** [comment] 2015-12-22 11:08
Closing until someone provides information how to reproduce it.

**Closed by Evildoor** 2015-12-22 11:08 UTC
Labels: Could Not Reproduce, Scenarios
