### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 1 - Logrin's Forge

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11290] opened 2018-02-13 05:00 UTC
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 1 - Logrin's Forge (platform)

In Logrin's Forge, on the pathway (left side; destruction --- right side; order), there is a raised platform against a wall just before the Battle Objective. You can reach this platform by jumping onto the barrels on the back side of it. With a mount or using "Flee", you can scale onto the platform. This platform gives ranged DPS and healers an advantage over the objective, and a safe haven to fade away from having damage dealt. Among being on the platform, you can essentially climb onto the pipes, also giving an advantage point if you climb high enough, your casting may not be noticed by enemies.

This platform on (right side; destruction --- left side; order) is already blocked off.

![anonymous_009](https://user-images.githubusercontent.com/19481783/36134136-0bbb69b8-1040-11e8-8006-b37fbbb5c5c0.jpg)
![anonymous_010](https://user-images.githubusercontent.com/19481783/36134137-0bd16d80-1040-11e8-869a-3257ef57058c.jpg)
![anonymous_011](https://user-images.githubusercontent.com/19481783/36134138-0be8366e-1040-11e8-8ea4-03d927ab4aca.jpg)
![anonymous_012](https://user-images.githubusercontent.com/19481783/36134139-0bfd6b60-1040-11e8-8dd6-2332fea20a75.jpg)
![anonymous_013](https://user-images.githubusercontent.com/19481783/36134140-0c122622-1040-11e8-93e1-e27ced58e335.jpg)
![anonymous_014](https://user-images.githubusercontent.com/19481783/36134141-0c273e22-1040-11e8-8e93-0a1ff29a5d3f.jpg)
![anonymous_017](https://user-images.githubusercontent.com/19481783/36134146-160b63e6-1040-11e8-929a-fd5bf68312d1.jpg)
![anonymous_018](https://user-images.githubusercontent.com/19481783/36134147-16219170-1040-11e8-8295-ed6ffa4c5187.jpg)
![anonymous_019](https://user-images.githubusercontent.com/19481783/36134148-163908e6-1040-11e8-8156-de96918a9a84.jpg)

More to come...

**Comment by sioding** [comment] 2018-02-13 07:44
Duplicate of #10262

**Closed by sioding** 2018-02-13 07:44 UTC
