### ISSUE TITLE
Faith is Madness Epic Quest... no Knight

### ISSUE THREAD

**Issue by Wyvernmoon** [WarEmu/WarBugs#18565] opened 2021-02-28 20:54 UTC
Faith is Madness Epic quest in Chaos Wastes.... killed the 8 mobs and couldn't find Knight.  Abandoned quest, regot it... tried finding Knight before killing 8 mobs... still nothing.  
![Image1](https://user-images.githubusercontent.com/41122586/109433215-3b074e80-79dd-11eb-8a64-1d18a26b88ad.jpg)

**Comment by MaxHayman** [comment] 2021-03-02 10:14
Duplicate of https://github.com/WarEmu/WarBugs/issues/18569

**Closed by MaxHayman** 2021-03-02 10:14 UTC
