### ISSUE TITLE
Gold bag loot bug

### ISSUE THREAD

**Issue by amikgni** [WarEmu/WarBugs#13214] opened 2019-01-27 18:31 UTC
I play AM. In my gold loot bag i,ve got sorcerer chest
[url=https://www.noelshack.com/2019-04-7-1548613883-berthe-000.jpg][img]https://image.noelshack.com/minis/2019/04/7/1548613883-berthe-000.png[/img][/url]

**Comment by sioding** [comment] 2019-01-27 18:35
Duplicate of #11739

**Closed by sioding** 2019-01-27 18:35 UTC
