### ISSUE TITLE
Talisman Making Bugged

### ISSUE THREAD

**Issue by StirlingScott** [WarEmu/WarBugs#10971] opened 2017-12-09 02:09 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

I had a lvl 25 fragment (step below Deviant Warding Brand) that would not apply to the talisman making menu so I deleted it. Once I deleted the fragment, for some reason I could no longer add anything to the talisman making menu now. I tried reloading and this didn't work.

Steps to reproduce the problem:
Find a lvl 25 Fragment (step below Deviant Warding Brand - forget the name). If it can't be applied to the menu, delete it and then try to add any material to the talisman making menu. This is what I believed happened but not 100% sure

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2017-12-09 06:39
Duplicate of #10088

**Closed by sioding** 2017-12-09 06:39 UTC
