### ISSUE TITLE
Tactic in 4th slot not being applied

### ISSUE THREAD

**Issue by malexcauthen** [WarEmu/WarBugs#15857] opened 2020-03-02 21:07 UTC
Dealing with a particularly frustrating bug that has been game breaking for me as it is significantly inhibiting my character at times. After doing some testing I have determined that tactics that get slotted in the 4th tactic slot do not always work. It seems like anytime I fly somewhere, or zone into an instance such as a city or scenario my 4th tactic stops working most of the time. If I want the tactic to work, I have to remember to re-apply the tactic each time. I have tested it across multiple tactics on the Ironbreaker.

**Expected behavior and actual behavior:**
The tactics I'm currently running and testing against:
- Punishing Knock
- Ancestral Inheritance
- Rugged
- Sweet Revenge

Essentially I expect all of the tactics slotted to work as described by the game. What I am actually seeing is that the tactic that gets slotted last does not always work. 

I will show examples of Ancestral Inheritance, and Rugged not working when slotted last. That being said I've seen similar behavior with Punishing Knock where it is not cursing my target with a heal debuff, and Sweet Revenge not increasing my crit over 50 grudge.

1. Ancestral Inheritance

I have just flown to a new zone. The below screenshot shows my character window and the output of .getstats. Notice that my armor is only 3.6k. I am wearing 4 piece invader (helm, chest, gloves, boots), 2 piece oppressor (shoulders, belt), and 1 piece sov (cape). 

![Zakgrin_007](https://user-images.githubusercontent.com/55412017/75716291-8258e300-5c94-11ea-9c0c-219c3991a794.jpg)

After reslotting the tactic my armor jumps up to 4.3k which is what is should be. 
![Zakgrin_008](https://user-images.githubusercontent.com/55412017/75716460-d5329a80-5c94-11ea-8162-f473108b6158.jpg)

2. Rugged

I have again flown to a new zone. Notice that it is currently slotted as the 4th tactic and my toughness is only 489 instead of 649 shown in the above pictures.
![Zakgrin_009](https://user-images.githubusercontent.com/55412017/75716591-1fb41700-5c95-11ea-81b5-758d7fd85667.jpg)

**Steps to reproduce the problem:**
Slot 4 tactics. Fly to a new zone, or go into an instance. Determine if all tactics are working properly (sometimes they work other times they don't).

Let me know if you need more information or examples. I appreciate the help.

**Comment by raptrr** [comment] 2020-03-02 21:16
I will have a deeper look into this tomorrow

**Comment by Tazo83** [comment] 2020-03-03 00:28
i can confirm this as am facing the same issue in my squiq tactic Territorial aggressive  and some other tactic and the way to fix it is after each loading screen i have to change the tactic and re apply it to make sure its working

**Comment by raptrr** [comment] 2020-03-03 17:26
Tried on my RP and Engi, could not reproduce it today. Gonna ask some people to try it as well.
@Tazo83 your mentioned issue is a different one, as it drops the tactics itself.
If you can provide more information as well, please do so with screenshots as well.

**Comment by malexcauthen** [comment] 2020-03-05 21:53
@raptrr The behavior Tazo83 is mentioning is very similar to my own. One other bit of information I can provide that may be useful is that when I take my weapons off to ultimately switch from 2h to s&b or vice-versa, one of my tactics is getting replaced with Long-Held Grudge. It could be that this is also happening when I change zones, but the UI isn't reflecting those changes. 

I am running the latest version of VinnyUI. Is it possible that the mods in that pack could be doing something weird with my tactics?

**Comment by Tazo83** [comment] 2020-03-06 04:26
most time it happens to me if am not using page 1 in tactic i will try to record something maybe this weekend

**Comment by raptrr** [comment] 2020-03-07 09:05
Ok, thanks for the new info. I will have a deeper look into it

**Comment by funnytroll** [comment] 2020-03-10 14:36
Have the same bug but its bugged for me when i equip item from backpack,do rel.
Its start bugged when i try check if this tactic work
https://youtu.be/sFN9EsLOjmg

**Comment by Kabucoror** [comment] 2020-04-03 14:08
It seems like it's IB exclusive. Happens to mine aswell. My workaround is reslotting 4th tactic after every zone swap and I use a visual one so I get remembered.

**Comment by Balinorr** [comment] 2020-04-03 16:29
Same as me as Ironbreaker. Plus whenever i log in the game all tactics have disappeared

**Comment by malexcauthen** [comment] 2020-04-24 01:15
@raptrr Is there any news on this issue. I have spoken with a long list of IBs in-game, and it seems to be a fairly common issue.

**Comment by Kaelang** [comment] 2020-04-24 01:16
@malexcauthen hey - when an update is given on a specific ticket, one of the staff members will typically come in and help explain the situation.

At this time, there doesn't look to be any evident advancement on this specific issue, but I'll keep an eye as it progressed and keep the ticket updated.

**Comment by malexcauthen** [comment] 2020-04-24 01:20
@Kaelang appreciate it!

**Comment by Tamtam-RoR** [comment] 2020-05-25 01:25
I've got the same issue and I suspect this being caused by ClosetGoblin addon.
Do you guys experiencing this problem have this addon installed at least once?

**Comment by Balinorr** [comment] 2020-05-25 13:23
> I've got the same issue and I suspect this being caused by ClosetGoblin addon.
> Do you guys experiencing this problem have this addon installed at least once?

I' ve always had this bug from the beginning and i've never installed this addon. So no, it's not an addon's fault

**Comment by joschika77** [comment] 2020-06-17 18:04
Hello, 

How is the status regarding this bugs? I have the same issues as described above. 
It's a IB issue i think. I had ClosetGoblin installed, just to know. But now i deleted the interface + user folders and replaced them with empty folders. 
I also deleted all tactics slots, relogging, set 1 tactics in slot 1, relogging. The result is an empty tactic slot. The tactic is there but not visuelly. I have to click to Slot 1 again. Its really strange.

**Comment by Brizhul** [comment] 2020-06-30 09:40
I've had this same issue with tactic slot 4 not working and my tactics resetting to the 1st tactics set when logging off/logging in on my Ironbreaker since I first made the character a while ago (I had absolutely no addons installed during most of that time playing the character, only installed addons just recently.. So it's definitely not an addon issue).

It's a real pain to deal with changing to another tactics set and back again every time I teleport into a dungeon, scenario, RvR zone, or if I get disconnected and reconnect again (Which causes me to be stuck using the 1st tactics set.. For example, if I disconnect in Fort and reconnect, I'd be engaged in combat). And if you forget to switch tactics sets back and forth, which I do far too often than not, you're left with a missing tactic or a completely different set (being the 1st tactics set).. Which REALLY sucks when you're relying on a specific tactic for your build to work.

- I can confirm that this is an Ironbreaker specific issue.

- I can confirm that when switching weapons from 2h to SnB (or vice versa), the slot 1 tactic in your current tactics set selected is changed to 'Long-Held Grudge', even if there was a different tactic selected in slot 1.

- I can confirm that having the 1st tactics set active, then logging off, your 1st tactics set will appear as a blank tactics set upon logging back in.

I hope this issue will be fixed in the near future.. It's a constant, frustrating experience.

**Comment by lilimx** [comment] 2021-06-01 09:27
Hey,

so it looks like it has been fixed. If you still experience the issue, pls let me know and we will check it again.

**Closed by lilimx** 2021-06-01 09:27 UTC
Labels: Ability, Combat Mechanics, Could Not Reproduce
