### ISSUE TITLE
[Epic Quest] T2 DE 

### ISSUE THREAD

**Issue by Kroatan** [WarEmu/WarBugs#13492] opened 2019-02-26 16:26 UTC
T2 Epic Quest DE 
step 12 Shadowland no need of monsters
~7600 ~61000

**Comment by Lheana** [comment] 2019-02-26 16:42
I don't understand your report sorry.

**Comment by sioding** [comment] 2019-02-26 18:36
me too. Can you please bring in more information to your report? Otherwise no dev is able to take care of it. Thanks.

**Comment by Tallanvor1** [comment] 2019-02-26 20:22
Griffon gate pq still isnt working

**Comment by Lheana** [comment] 2019-02-26 21:32
Duplicate of/related to #10862

**Closed by Lheana** 2019-02-26 21:32 UTC
Labels: 2 Week Ultimatum, Confirmation Request
