### ISSUE TITLE
Reikwald fort bug text?

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16535] opened 2020-04-28 06:13 UTC
As per the screenshot, not sure what's going on, but I got a reservation and this message:
![11111](https://user-images.githubusercontent.com/26847385/80453179-18df1300-896b-11ea-8eb7-1e6b2a5cf38f.png)

Cheers!
Tes

**Comment by Kaelang** [comment] 2020-04-28 13:45
Duplicate of https://github.com/WarEmu/WarBugs/issues/16409.

**Closed by Kaelang** 2020-04-28 13:45 UTC
