### ISSUE TITLE
[RP] Ability: Oath Rune of Sanctuary

### ISSUE THREAD

**Issue by SenatorGrimm** [WarEmu/WarBugs#14729] opened 2019-08-05 22:26 UTC
If the RP buffs himself with this Rune, gets killed and declines the self-revive the buff is removed.
According to the description it should only be removed if the self-revive is accepted.
Only noticed it in Scenarios - however there it is particularly annoying as you tend to die more often and with the 10min cooldown you are unable to play for large parts with the additional toughness this buff provides.

**Comment by sioding** [comment] 2019-08-06 15:25
Duplicate of #13187

**Closed by sioding** 2019-08-06 15:25 UTC
