### ISSUE TITLE
Zone locks not giving rewards

### ISSUE THREAD

**Issue by JackMinn** [WarEmu/WarBugs#13526] opened 2019-03-02 20:55 UTC
**Expected behavior and actual behavior:**
There have been several zone locks in the recent days that simply give 0 rewards to myself, my party members and others complaining in the zone. The issue developed sometime after the introduction of forts into the game. 

**Steps to reproduce the problem:**
I typically see this happen if the zone before a fort locks (aka CW locks by Order), however I am inclined to say that it also happens in t2/t3 zones (but unconfirmed, I can definitely confirm it for t4 zones).

**Screenshots/Videos or archive.org evidences:**
Cannot really prove much with a screenshot, the absence of a zone lock tick doesnt prove much as I could just as easily have scrolled up the chat. However it definitely happens.

**Comment by sioding** [comment] 2019-03-03 05:45
Duplicate of #13413

**Closed by sioding** 2019-03-03 05:45 UTC
