### ISSUE TITLE
Focused Mending / Stay Focused! activation bug on KOTBS

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16085] opened 2020-03-24 13:41 UTC
**Expected behavior and actual behavior:**

Activating Stay Focused with Focused Mending - expecting it to stay on until deactivation
Actual - stayed on for about a second or two then self-deactivate, therefore removing the aura

**Steps to reproduce the problem:**

Unclear, seems to be random, had successes in the past trying to reequip perk and skill, however failed to overcome problem with the same solution at this given moment

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/62215736/77431822-595de500-6e31-11ea-8cb9-f181e2d45960.png)

**Comment by Snifflebutts** [comment] 2020-03-24 13:44
This issue seems to affect ONLY "Stay Focused!" to fix it, i have to turn on and off all of my auras and trying it over and over again constantly until the issue is fixed. This entire process could take up to 5-10 minutes, and potentially disruptive during gameplay.

**Comment by Snifflebutts** [comment] 2020-03-24 13:50
The issue can reoccur after being fixed, and sometimes could take up to a few minutes before being deactivated without the user's input. Seems like the amount of KOTBS in the same party is a strong culprit due to the prequency it takes place when having more than 1 Ktobs in the same party.

**Comment by Snifflebutts** [comment] 2020-03-30 02:07
The bug can also occur even when you have the other knights in any other party but within the same warband, you sometimes can activate it again and have it stayed on for awhile as long as you stay out of range of the other knights whom may have stay focused activated.

**Comment by SilverWF** [comment] 2020-05-04 18:15
Stay Focused aura + Focused Mending tactic turns off, when you got another KOBS with that aura, but without that tactic
So, you couldn't turn it on - you got error "Aura spread failure ..."
You can run far away from other KOBS and turn your improved aura safely.
But at the time you are coming to his aura area, your aura turns off.

**Comment by Kaelang** [comment] 2020-05-16 16:25
Had no issue keeping this aura running with and without the Stay Focused aura. 

Please provide additional replication notes if you still believe there is an issue here. For now - closing this as looks to be working as intended.

**Closed by Kaelang** 2020-05-16 16:25 UTC
Labels: Ability

**Comment by Kornaker** [comment] 2022-04-29 08:49
Still Bug in 2022, when you switch map in RVR or go on Scenario, you some time have the aura which stop proccing ( for minutes ) and sometimes you can't activate any aura anymore . Only solution is Deco/Reco.
Only have the issue when with Focused Mending tactic. Didn't notice without.

**Comment by lilimx** [comment] 2022-04-29 11:38
Hey,

this issue was closed 2 years ago. Please open a new ticket.
