### ISSUE TITLE
Quest: Organ Solo - Organ Gun that has to be used/shot is loud as hell 

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#15904] opened 2020-03-06 21:55 UTC
Expected behavior and actual behavior: 
The Organ Gun from the Quest Organ Solo in Barak Varr
(Quest giver: Master Smith Jordsson) has to be clicked/loaded so it will shoot. It would then play a Sound for it be fired. It should be a normal Organ Gun sound, but the sound Volume of the shot is 
way to loud. To be more precise, it almost gave me a heart attack and tinnitus. 

Steps to reproduce the problem: 
Do the Quest Organ Solo in Barak Varr 49152 / 57351 from quest giver Master Smith Jordsson.
Click the Organ Gun and get your Headset and your ears blasted away.

Testing Screenshots/Videos/Evidences (always needed): 
![Grolllinger_002](https://user-images.githubusercontent.com/54162117/76125575-68553280-5ffd-11ea-90e0-70eb25fbd1cd.jpg)

![Grolllinger_003](https://user-images.githubusercontent.com/54162117/76125594-6e4b1380-5ffd-11ea-8aae-479125ee8da2.jpg)

**Comment by bosli42** [comment] 2020-03-07 00:42
Can confirm, I remember doing this while leveling. Unforgettable.

**Comment by Lheana** [comment] 2020-03-07 15:04
Duplicate of #14055

**Closed by Lheana** 2020-03-07 15:04 UTC
Labels: Client, World Object
