### ISSUE TITLE
Order Undone still broke

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15953] opened 2020-03-11 21:35 UTC
**Expected behavior and actual behavior:**

Suppose to give credit for winning scenario will full guild 6 man but doesn't give credit on completion. Tested with different group setups to no avail.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2020-03-15 12:23
Duplicate of #15591

**Closed by Lheana** 2020-03-15 12:23 UTC
