### ISSUE TITLE
Mist unable to crit

### ISSUE THREAD

**Issue by Dirox-Hirox** [WarEmu/WarBugs#16586] opened 2020-04-30 06:16 UTC
After the patch on 29/04/2020 that converted dissolving mist to DoT damage instead of direct damage, it is no longer able to critically hit.

**Comment by Yedraw** [comment] 2020-05-01 21:23
Any ETA on a possible fix for this?
It's a big deal for AOE Mag's DPS.

**Comment by Yedraw** [comment] 2020-05-03 22:52
??????

**Comment by Kaelang** [comment] 2020-05-03 23:05
There's 1,889 open reports. If we was to respond to every bump giving ETA's, nothing would ever get done.

It will get fixed when someone gets around to looking at it.

**Comment by Yedraw** [comment] 2020-05-03 23:12
Copy, thank you.

**Comment by wargrimnir** [comment] 2020-05-09 18:22
This is correct. The shared command for mist/napalm/blasting pots was intentionally changed to deal DOT damage. Direct damage causing procs from these abilities as well as triggering reflected damage were larger issues than losing the ability to crit. What you're asking for now is a balance change to increase their DOT damage, not a bug fix.

**Closed by wargrimnir** 2020-05-09 18:22 UTC
Labels: Ability

**Comment by RoR-Zomega** [comment] 2020-05-09 21:26
Warg I don't understand this. Damage over time effects can crit and still not trigger direct damage effects, much like heal over time effects can crit and not trigger direct healing effects. Examples using the only career I have to test:

Zealot: Demon Spittle (aoe DOT) with heal debuff tactic (triggers on crit). Demon Spittle can happily crit and it won't trigger the tactic.

Zealot: Tzeentch's Cordial (single-target HOT) with Blessing of Chaos (+25% heals, triggers on crit heal). Tzeentch's Cordial can crit and when it does so, it doesn't trigger the tactic or any others that trigger on crit heals.

I understand changing Mists/Napalm/Blasting to be indirect damage, but why does this change also mean they also need to lose the ability to crit when the game already has indirect crits that don't proc effects?
