### ISSUE TITLE
Apothecary Level Issue

### ISSUE THREAD

**Issue by Hiftem** [WarEmu/WarBugs#12820] opened 2018-12-07 03:12 UTC
Am using Apothecary to make heal potions.  Level 25 components and 50 level components are creating level 5 heal potions.  I had the same thing happen with Toughness and Willpower potions using the higher level components.  I noticed issue #4077 seems to be similar from back in 2016.
![stalkerr_000](https://user-images.githubusercontent.com/41247260/49625530-80be4380-f99b-11e8-8447-861fc0b1b0cb.jpg)
![stalkerr_001](https://user-images.githubusercontent.com/41247260/49625531-8156da00-f99b-11e8-8525-1f5b5b4ed835.jpg)

This is happening on my level 67 Apothecary toon on Order (Stalkerr)

Please advise.
Thanks

**Comment by sioding** [comment] 2018-12-07 06:48
Duplicate of #1644

**Closed by sioding** 2018-12-07 06:48 UTC
