### ISSUE TITLE
Brittle Beardweed Level 25 Crafting Issue

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11558] opened 2018-04-06 11:33 UTC
Expected behavior and actual behavior:

That Brittle Beardweed level 25 with bottle and stabiliser will make a meager strength potion.
Instead, it produces "Another Junk", an item that cannot be sold, but I have to destroy by dragging out of my backpack.
Critical Success when attempting to make potions using this ingredient creates Potent Fleeting Potion of Pith.
Update 06/04/18 13:00: The same is happening with the level 50 ingredient.

Steps to reproduce the problem:
Allow for the coding to recognise that a standard potion has been produced rather than Another Junk.

Screenshots/Videos or archive.org evidences:

![ithilsyn_164](https://user-images.githubusercontent.com/22262165/38419022-a3003f22-3996-11e8-8017-d45c6da7bb83.jpg)

![ithilsyn_165](https://user-images.githubusercontent.com/22262165/38419036-b7f6dbca-3996-11e8-9a26-121253d0f553.jpg)

![ithilsyn_166](https://user-images.githubusercontent.com/22262165/38419047-c2d71708-3996-11e8-8a93-f2ce86077473.jpg)

**Comment by Senthoi** [comment] 2018-04-06 12:00
Update: The same is happening with the level 50 ingredient.

**Comment by sioding** [comment] 2018-04-06 12:12
Duplicate of #10660

**Closed by sioding** 2018-04-06 12:12 UTC

**Comment by Senthoi** [comment] 2018-04-06 12:41
Thanks sioding, didn't come up in the search before I raised this.
