### ISSUE TITLE
Fall through Dwarf Warcamp Thundermountain

### ISSUE THREAD

**Issue by ctesjbuvf1** [WarEmu/WarBugs#20834] opened 2023-04-07 14:53 UTC
**Expected behavior and actual behavior:**
When you leave the Dwarf Warcamp going for the pve section of the map you disappear trough the floor i tried all angles to get out its impossible.

**Steps to reproduce the problem:**
Leaving the Dwarf Warcamp towards PvE section.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment] 2023-04-07 16:27
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by geezereur** [comment] 2023-04-08 07:34
I also fall through the ground in Reikland pve area on my magus and I think it was because my new mount as soon as I changed mount i never fall trough again.

**Comment by CrimsonFenris** [comment] 2023-04-08 13:16
Got this issue with another player in the warband (was incomplete with about 18-20 people) :
- Leader asked to switch from High Pass (iirc) to Badlands.
- My slayer and another AM took the flight master
- both were teleported into foggy undermap, probably somewhere in the world (map didnt show anything, just "map not available"). I briefly saw my fellow AM in front of me, running on invisible ground.
- I used war report to get back to HP ; my character reappeared dead with resurrect prompt, and a 15min PvE debuff after that.
- No issue after that for me.
- The other AM folk had trouble getting out (I suppose no WR available), restarting game didnt fix the issue, he had to ask a GM to teleport him (iirc).

**Comment by MaxHayman** [comment] 2023-04-12 23:32
Should be fixed. Please reopen if that is not the case.

**Closed by MaxHayman** 2023-04-12 23:32 UTC
Labels: Confirmation Request, 2 Week Ultimatum
