### ISSUE TITLE
Prize of War quest - Noble's Chest object

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14677] opened 2019-07-29 03:47 UTC
Expected behavior and actual behavior:
It's a minor issue. This Noble's Chest had a health bar when I got to it, I "killed" it, but everything on the quest worked alright.

Steps to reproduce the problem:
You find it by going to the Shrine of Lore, or House of Lore, as they say in the dialogues.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_003](https://user-images.githubusercontent.com/53320075/62020705-6808d500-b19a-11e9-8226-a6e3b670d6d8.jpg)
![Austherus_004](https://user-images.githubusercontent.com/53320075/62020706-6808d500-b19a-11e9-8bd9-f1346a6f74e9.jpg)

**Comment by Lheana** [comment] 2019-07-29 09:36
I could not reproduce it, because the object is not attackable. And nothing prevents from completing the quest, so I close it.

**Closed by Lheana** 2019-07-29 09:36 UTC
