### ISSUE TITLE
Cleansing an Empire Quest in Talabecland

### ISSUE THREAD

**Issue by SPRVatis** [WarEmu/WarBugs#15450] opened 2020-01-09 04:02 UTC
The final stage you are supposed to Find an Iron box, a pyre, a cage and a rack. They are all missing so you can not complete the quest and get the next step.

**Comment by Rantric** [comment] 2020-01-09 14:42
https://github.com/WarEmu/WarBugs/issues/15441

noticed that as well lol

**Comment by Lheana** [comment] 2020-01-09 17:40
Duplicate of #15441

**Closed by Lheana** 2020-01-09 17:40 UTC
