### ISSUE TITLE
No NPCs on Map/Minimap

### ISSUE THREAD

**Issue by fagio1989** [WarEmu/WarBugs#13101] opened 2019-01-09 03:22 UTC
BUG: You don't see any NPC on the map, even party/wb.

Solution: There's a bug in the quest "Pub Crawler" of this Xmas Event, if you don't finish it (you don't drink all the beers in IC) and log out, you'll be not able to see the NPCs anymore.

Abandon it you will spot just the "mail" in the map.

Do /rel and relog, solved.

**Comment by sioding** [comment] 2019-01-09 06:49
Duplicate of #12923

**Closed by sioding** 2019-01-09 06:49 UTC
