### ISSUE TITLE
T3 inf WE cloak changed to BG

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#4207] opened 2016-02-02 15:30 UTC
![zireael_005](https://cloud.githubusercontent.com/assets/13823154/12754107/436b1246-c9ca-11e5-9dbd-21e81712045a.jpg)

**Comment by Styrkarr** [comment] 2016-02-02 17:56
The WE cloak is "Ghrond's Fright Shawl". "Greatcloak" is for BG. It was a bug which was fixed with the last patch.

Maybe ask a GM to change this item with the real WE one.

**Comment by MKorin** [comment] 2016-02-02 18:22
but there is reduced chance to be dodged in Ghrond's Fright Shawl... for WE?

**Comment by Styrkarr** [comment] 2016-02-02 18:39
I think it's an old stat (as engi/SH item with strength instead of balistic skill).

I changed it  to %parry_strikethrough.

**Comment by MKorin** [comment] 2016-02-02 19:53
cool, thx

**Comment by Evildoor** [comment] 2016-02-03 05:32
Not a bug, but collateral damage caused by bug fixing. Closing.

**Closed by Evildoor** 2016-02-03 05:32 UTC
Labels: Database, Item

**Comment by mursie** [comment] 2016-02-10 16:41
I notice you are closing these and saying it is collateral dmg.  CAn you elaborate on this?  Does this mean that it will not be fixed?  That if you have a ring that has now changed career you are SoL?  Just curious what your statement means

**Comment by Evildoor** [comment] 2016-02-10 17:04
> Maybe ask a GM to change this item with the real WE one.
