### ISSUE TITLE
Strange client behaviour

### ISSUE THREAD

**Issue by Morngrim** [WarEmu/WarBugs#11068] opened 2017-12-28 18:57 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When i was login tonight with my RP my client froze and end it task. 

When i logged back to War i saw that i dont have mail with yesterday medals, but its not the case. 

That lead me to check the quests and than I saw that i didnt have any, bullocks but I can leave with it. Wanted to start the 2nd stages of BL quest, those with the token for guide (i didnt retrieved them yesterday), and when I interact with Praag quest giver he offered me the 1st stage of it. Quest with killing Ursine, with a helm as reward, which I already am wearing. Dont know if its a Issue, but someone can use it to get higher mats and abuse it. 

Steps to reproduce the problem:
Dont know, checked all rest of my alts, and they are fine. 

Screenshots/Videos or archive.org evidences:
https://ibb.co/iutmjw

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2017-12-29 08:05
Duplicate of #10421

**Closed by sioding** 2017-12-29 08:05 UTC
