### ISSUE TITLE
The Price of Survival, in Ellyrion

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#19032] opened 2021-05-22 09:40 UTC
Quest Waypoint: Kill Karthrian Sedt.

This NPC is not located on the map in this area. I searched for a long time and couldn't find the kill target.

**Comment by Lheana** [comment] 2021-05-23 14:16
Duplicate of #16938
Karthrian Sedt was a bit far from his normal location. I killed him and he is back - for now - to his place.

**Closed by Lheana** 2021-05-23 14:16 UTC

**Comment by Ramessu** [comment] 2021-05-23 21:03
Thank you. I was able to complete the quest with your help.
