### ISSUE TITLE
Live Event page in Tome of Knowledge is living it's own life

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18166] opened 2020-11-29 20:17 UTC
This page
![image](https://user-images.githubusercontent.com/75143494/100552546-30c3a000-3288-11eb-96c8-d85261d2bdb4.png)
is switching automatically back to
![image](https://user-images.githubusercontent.com/75143494/100552555-3de08f00-3288-11eb-8679-7138d3d00672.png)

It's possessed by a daemon :)

**Comment by Lheana** [comment] 2020-11-29 21:26
Duplicate of #18106

**Closed by Lheana** 2020-11-29 21:26 UTC
