### ISSUE TITLE
[Tooltip] Zealot tooltip-values don't match when HoD is off

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13518] opened 2019-03-02 11:50 UTC
![test_hod_off](https://user-images.githubusercontent.com/40274248/53681322-2c033e00-3ce8-11e9-98e7-929b213df068.jpg) No tactics equipped

As you can see, the tooltips don't match neither the healing nor the dmg dealt while Harbinger of Doom is turned off.
If you turn HoD on both values match. (can provide screens if needed)
_Note: you have to reequip some of your gear to update the tooltips after switching HoD on/off_

**Comment by grunbag** [comment] 2019-03-02 12:01
Are you sure the tooltip on your sceeenshit have not been generated when you had HoD activated ?

**Comment by Scophis** [comment] 2019-03-02 12:08
![foc](https://user-images.githubusercontent.com/40274248/53681603-27d91f80-3cec-11e9-8846-0865e9322ca7.jpg)
Yep^^

**Comment by grunbag** [comment] 2019-03-02 12:14
Flash of chaos haven’t been touched

**Comment by Scophis** [comment] 2019-03-02 12:17
It was just an example. I can provide all complete screens to the shown values, but I thought that would only clutter the post. 

![scourge](https://user-images.githubusercontent.com/40274248/53681695-7d61fc00-3ced-11e9-8a4b-157fbc3c9726.jpg)

**Comment by grunbag** [comment] 2019-03-02 12:40
i don't  have this issue . so something you equiped make it wrong

![scourge](https://user-images.githubusercontent.com/24207191/53681932-a932b100-3cf0-11e9-811c-8398d7514bcd.png)

**Comment by Scophis** [comment] 2019-03-02 12:58
Found it.
If I wear gear with INT on it, the Tooltip with HoD off is wrong. If I only use gear with WIL it matches (heal and dmg).

**Comment by grunbag** [comment] 2019-03-02 13:13
So stat scale is wrong . I’ll check that thanks

**Comment by grunbag** [comment] 2019-03-03 20:35
After dig into it , the issue is not DB or stat , just tooltip that update itself like if HoD was activated . So it’s only a visual issue , damage should be fine when HoD is activated . We will try to update the code to make the tooltip work as intended

**Comment by grunbag** [comment] 2019-07-30 11:37
Fixed with next patch

**Comment by sioding** [comment] 2019-08-03 13:34
Fixed with patch from 03.08.2019

**Closed by sioding** 2019-08-03 13:34 UTC
Labels: Ability, Fix Pending, Tooltip

**Comment by RoR-Zomega** [comment] 2020-04-14 23:14
This is broken again BTW. Toggling HoD on and off and on and off (etc) doesn't update the tooltips.
