### ISSUE TITLE
Git to da choppa can pull players from higher ground

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11886] opened 2018-06-14 02:06 UTC
Expected behavior and actual behavior:
Git to da choppa should not pull players from higher ground according to global magus/engi/mara/wl pull abilities.

Proof : just try to pull any kind of player in higher ground.

**Comment by sioding** [comment] 2018-06-14 18:46
Duplicate of #11874
Even when the other issue said: pulls through the walls - its said it pulls from above - this is why i close this one.

**Closed by sioding** 2018-06-14 18:46 UTC
