### ISSUE TITLE
Quest: a sticky situation

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11431] opened 2018-03-08 12:35 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Free Gavin won't work, Pre-q to kill the spiders are ok and well done. The step to free him won't do anything. Cocoon is touchable and killable, Gavin comes free but won't count to the queststep.

Steps to reproduce the problem:
I tried the step 2 times, First to click only the cocoon, second to kill the cocoon and free Gavin. In both situations his animation is infront the destroid cocoon und irst wave then run. No count for the queststep anytime.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-03-08 16:15
Duplicate of #11301

**Closed by sioding** 2018-03-08 16:15 UTC
