### ISSUE TITLE
Bug in Empire chapter 1 Quest

### ISSUE THREAD

**Issue by Favestus** [WarEmu/WarBugs#18787] opened 2021-04-06 12:21 UTC
Hi, i met a bug in the quest "Flame return" / Retour de flammes, in Empire chapter 1. This is the quest where you have to use empire canon in order to destroy Hellcanons on the Hill. The issue is that even after destroying 2 canons as requested, the quest is not completed. Thank you for your help and especially thanks for making the game live again! :) 

**Expected behavior and actual behavior:**
Hi, i met a bug in the quest "Flame return" / Retour de flammes, in Empire chapter 1. This is the quest where you have to use empire canon in order to destroy Hellcanons on the Hill. The issue is that even after destroying 2 canons as requested, the quest is not completed

**Steps to reproduce the problem:** Accept the quest "Retour de flammes" from NPC Viktor RIESE in Empire Chapter 1. Try to destroy the Hell canons.

**Testing Screenshots/Videos/Evidences (always needed):**
 I apologize, it seems i'm unable to collect screenshots of the game (i'm unable to find the file).

**Comment by Favestus** [comment] 2021-04-06 16:01
I dont know if this can help but i think the correct translation for the quest name would be "Backfire".

**Comment by Lheana** [comment] 2021-04-06 16:37
Duplicate of #18769

**Closed by Lheana** 2021-04-06 16:37 UTC
