### ISSUE TITLE
Lair of Old Oozeback 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4009] opened 2016-01-26 08:58 UTC
Lair Boss is missing in Marshes of Madness.
![lair location](https://cloud.githubusercontent.com/assets/16864486/12576355/bb9f44f8-c41b-11e5-8c65-7216f7e8a87d.jpg)
![location of the lair](https://cloud.githubusercontent.com/assets/16864486/12576350/ac426986-c41b-11e5-9f06-0edefba72891.jpg)

The Lair is located in the southwest region of the Fetid Bog directly west of the southern most area of water on the map. The Lair is in the mountains and is reached by jumping up a set of rock outcrops which form a stairway.

Approx coords 25037,60518

**Comment by DanaBloodkiss** [comment] 2016-01-26 13:24
Fixed in the next patch. Though he will not have any loot because he was not in our Database and I had to create him O.o thanks for the report!When you find loottables tell me!

**Comment by Torquemadra** [comment] 2016-01-26 15:19
http://warhammeronline.wikia.com/wiki/Old_Oozeback

Confirmed Drops

Drops 1-3 Rank 36 Rare BOP Boots per kill.

Destruction

    Oozing Footwraps
    Oozing Bloodwades
    Oozing Thighbinds
    Oozing Feetsplate
    Oozing Wardshoes are BOP Boots per kill.

**Comment by Soulwhisper** [comment] 2016-01-26 17:38
I cant find any on the net unfortunately. Maybe we will need some help on that. It looks like all T4 lairs have wrong drops.

**Comment by Soulwhisper** [comment] 2016-01-26 19:19
(BLUE ITEM)
Oozing Steeltoes
Boots
Light Armor
172 Armor
Bound to player
+35 Wounds
+14 Initiative
+81 Spiritual Resistance
+81 Corporeal Resistance
+1 Empty Talisman Slot
Minimum Rank : 36
Skill : Light Armor

**Comment by DanaBloodkiss** [comment] 2016-01-27 13:36
Added thank you very much.

**Closed** 2016-01-27 14:38 UTC
Labels: Database, Fix Pending, NPC

**Comment by Soulwhisper** [comment] 2016-01-27 14:48
He is a rank 40 though.You made him 41. Just to know. It doesnt matter yet as long as T4 is down.

**Comment by DanaBloodkiss** [comment] 2016-01-27 14:51
I have to set him to Level 40-41 otherwise when I use 40 - 40 he will be Level 39 or level 40.

**Comment by Soulwhisper** [comment] 2016-01-28 12:25
I think its better to be set on 39-40...as many of T4 lairs are 39 Level.

**Comment by DanaBloodkiss** [comment] 2016-01-28 12:45
Changed it to 40 - 40 we will see what happens :)

**Comment by Soulwhisper** [comment] 2016-01-28 13:02
@DanaBloodkiss Nice :)
