### ISSUE TITLE
[Quest] BO-Scouting quests in elf t2 autocomplet

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14873] opened 2019-09-01 07:54 UTC
The quests to scout the four BOs in Elf T2 are completed on accepting them. 

![Zkyr_010](https://user-images.githubusercontent.com/40274248/64073445-440b4880-cc9e-11e9-9211-8382d3734db9.jpg)

(It seems it was mentioned some time ago, but was closed due to no response #4438)

**Comment by Lheana** [comment] 2019-09-01 12:31
Duplicate of #6872

**Closed by Lheana** 2019-09-01 12:31 UTC
