### ISSUE TITLE
fort crash - respawn in inaccessible area

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#18624] opened 2021-03-11 21:22 UTC
every time i crash in fort i respawn in area behind all invisible walls, i cant get out, only port to city or unstuck so i loose all medals, contribution and reservation, because its impossible to get back in 5 min

contacted gm with this problem, his answer was really helpful "[Wicced] tells you: we are not a taxi service"

![image](https://user-images.githubusercontent.com/49390790/110856254-b4455200-82b7-11eb-8961-6184d96f9f86.png)

**Comment by Lheana** [comment] 2021-03-21 17:23
Duplicate of #18464

**Closed by Lheana** 2021-03-21 17:23 UTC
Labels: Fortresses
