### ISSUE TITLE
Khaine's Refreshment

### ISSUE THREAD

**Issue by korwrath** [WarEmu/WarBugs#11794] opened 2018-05-22 06:13 UTC
The Disciple of Khaine ability "Khaine's Refreshment" is not working, at least on my DoK.  When 'used' it does not use any soul essence, heal any allied players, or move the casting bar to indicate it is being cast, it does give the animation.

**Comment by sioding** [comment] 2018-05-22 13:45
Duplicate of #11741

**Closed by sioding** 2018-05-22 13:45 UTC
Labels: Ability
