### ISSUE TITLE
Gunbad's boss in left wing Foul Mouf issue

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#11140] opened 2018-01-12 19:43 UTC
in 3 stage his usable "discusting home" doesn't respawn, which after clicking starting boss stage.

![carsen_000](https://user-images.githubusercontent.com/31020540/34892347-ff2b88cc-f7e9-11e7-87f7-92049aab0190.jpg)

**Comment by Nfkillz** [comment] 2018-01-13 03:48
https://github.com/WarEmu/WarBugs/issues/11134

**Comment by sioding** [comment] 2018-01-13 06:54
Duplicate of #11134

**Closed by sioding** 2018-01-13 06:54 UTC
