### ISSUE TITLE
Guild Tab not Working #2

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#13378] opened 2019-02-16 09:50 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: When I log in any of my toons the Guild tab only shows the I'm the only one in the guild and the only one on atm

Steps to reproduce the problem: Log in any of my toons and hit the Guild tad it dosn't show any guild member in the guild but the toon I have logged in atm

Screenshots/Videos or archive.org evidences: sorry don;t know how to do a screenshot

**Comment by sioding** [comment] 2019-02-16 09:50
Duplicate of #13377

**Closed by sioding** 2019-02-16 09:50 UTC
