### ISSUE TITLE
 Quest Stalker of the Void can't be completed (Fix still needed)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12280] opened 2018-09-07 19:45 UTC
https://github.com/WarEmu/WarBugs/issues/12182
Issue is till not solved, corpse is interactable now, but it gives you grey quest item ring, which is not shown in inventory after looting it and does not check quest on pic\corpse interaction.
![veszal_048](https://user-images.githubusercontent.com/42712833/45239936-a6ca3e00-b2ef-11e8-9655-66f5838646b1.jpg)

**Comment by sioding** [comment] 2018-09-08 07:08
Duplicate of #12182

**Comment by Lheana** [comment] 2018-09-08 10:16
Works fine for me.
![anabo_000](https://user-images.githubusercontent.com/11537611/45253057-03b20c80-b361-11e8-8395-39965b5c8178.jpg)

You know that Quest Items go into Quest Items section of your inventory, right?

**Comment by Rockalypse** [comment] 2018-09-08 11:57
Yeah, I know that. Quest items does not drop to iventory as I said.
![veszal_049](https://user-images.githubusercontent.com/42712833/45253932-82b23f80-b377-11e8-8aff-a9f5dadac123.jpg)

**Comment by Lheana** [comment] 2018-09-08 12:00
Do you right-click on it to loot it when you have the window opened after interacting with the GO?

**Comment by Rockalypse** [comment] 2018-09-08 18:10
Steps I perform:
1) take quest
2) head to corpse
3) righclick on corpse (loot windows with ring opens)
4) right click on ring (loot window closes)
5) nothing apears in inventory

**Comment by Lheana** [comment] 2018-09-08 20:14
Don't know what you are doing wrong, but I tried several times, with different chars, and on live just now, I even could have it several times...
![anaehll_388](https://user-images.githubusercontent.com/11537611/45258219-7bf5ed80-b3b4-11e8-9947-27ed76989e1f.jpg)

**Comment by Rockalypse** [comment] 2018-09-09 10:07
I think I understand how this Bug works.
Just figured it out on other items - I had 4 rows of crafting items filled and tried to buy Cloudy water. Money were taken by vendor but it did not apear in inventory! It gives me an idea of slots in quest\crafting inventory that can be filled but cannot be seen.

So, when I first done it quest I had alot of quest items (like full 8-10 rows - I was farming chrace lions (27:25 Chrace) for Butchering and they dropped pelts in quest inventory (5 in stack)). So as my inventory was filled to its visible cappacity - quest Item for this quest was looted, but was placed in unregistered zone of 10+ row, now as I deleted pelts (thought that quest may be does not work due to inventory overflow) - ring is till there, so when I try to loot it it just stacks in that zone that I cannot see.

**Comment by sioding** [comment] 2018-09-09 10:51
Just a little question - are you using the filters on the bagpacks?

**Comment by Rockalypse** [comment] 2018-09-09 13:43
What filters?

**Comment by Rockalypse** [comment] 2018-09-09 13:59
Just tried to use BagOMatic addon - it helped with crafting items, but there is no option there to sort quest items.

**Comment by sioding** [comment] 2018-09-09 14:27
OK - thanks for the feedback - so i will close his here. Have a nice WAR :)

**Comment by Rockalypse** [comment] 2018-09-09 14:28
Thank you guys! Sorry if taking too much of your time.

**Closed by sioding** 2018-09-09 14:27 UTC
Labels: 2 Week Ultimatum, Confirmation Request
