### ISSUE TITLE
Too many mastery points available at level 29

### ISSUE THREAD

**Issue by igvgithb** [WarEmu/WarBugs#16893] opened 2020-05-20 19:06 UTC
I have experienced an issue where I have unlocked way more mastery points (a total of 30) on lvl 29. I encountered this issue while trying to respec as I was in queue for a scenario. I believe I already got a pop before I respecialized.

![image](https://user-images.githubusercontent.com/62517057/82486359-01fc8e00-9add-11ea-81af-410395757152.png)

![image](https://user-images.githubusercontent.com/62517057/82486379-0759d880-9add-11ea-92ee-2b150646e0dd.png)

Note that I have all 15 levels in path of agony, along with 4 abilities, as well as 9+1 in path of calamity. You can tell I have all 4 abilities (shades of death, impending doom, echo of power and hand of ruin) unlocked in the hotbar in the middle of the screen. 

Character name: Heloise, 29 sorc

**Comment by Kaelang** [comment] 2020-05-20 19:07
Thanks - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16886.

**Closed by Kaelang** 2020-05-20 19:07 UTC
