### ISSUE TITLE
Stairs Bug Kadrintal

### ISSUE THREAD

**Issue by Hinicha** [WarEmu/WarBugs#14900] opened 2019-09-08 12:33 UTC
Destro Keep in Kadrintal the stairs on a Tower is buggie.
if you are in the keep, the 6th Tower on the Wall from the main door on the right side.

<img width="1920" alt="Warhammer buggie stairs" src="https://user-images.githubusercontent.com/55036580/64488215-94a61700-d245-11e9-95ac-7976909d8b1f.png">

**Comment by sioding** [comment] 2019-09-08 12:35
Duplicate of #14166

**Closed by sioding** 2019-09-08 12:35 UTC
