### ISSUE TITLE
[Choppa] Shrug it Off

### ISSUE THREAD

**Issue by danissrv** [WarEmu/WarBugs#1484] opened 2015-09-22 13:38 UTC
After last update this doesn't work correctly most of the time or at all.It doesn't remove slows etc

**Comment by Evildoor** [comment] 2015-09-22 13:46
Seems similar to https://github.com/WarEmu/WarBugs/issues/1482
Maybe other similar MDPS skills have the same problem?

**Comment by ozarmidrashim** [comment] 2015-09-22 14:09
Duplicate of 1482

**Closed by ozarmidrashim** 2015-09-22 14:09 UTC
Labels: Ability
