### ISSUE TITLE
Problem with Genesis jewlry set

### ISSUE THREAD

**Issue by Nafloin** [WarEmu/WarBugs#16454] opened 2020-04-21 18:15 UTC
Got 3 pieces of the jewlery set of Genesis (the one for DPS for my WH)

But i don t have the set bonus for the 2 pieces and 3 pieces on my WH Nafloin

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-04-21 18:22
Please can you screenshot the items purchased, and equipped.

**Comment by Nafloin** [comment] 2020-04-21 18:27
![47BBE779-40CA-4C29-8250-3F2E13089250](https://user-images.githubusercontent.com/64092484/79900401-7543af00-840e-11ea-80c4-ecd2ba6ec196.jpeg)
![08E815A6-A080-4FFB-9432-7240587377B2](https://user-images.githubusercontent.com/64092484/79900407-783e9f80-840e-11ea-99cd-6a33d21a6f91.jpeg)
![7112BC00-881E-48C3-88E1-E8F7751D43F7](https://user-images.githubusercontent.com/64092484/79900415-7aa0f980-840e-11ea-9062-79fc739d0cab.jpeg)

**Comment by Kaelang** [comment] 2020-04-21 18:30
Could be something to do with the names of the items being in French and set items in English. (See item name French, set name English).

Can you do a .getstats report of your 'Force' before and after equipping two pieces to see if the +37 is being added?

**Comment by Kaelang** [comment] 2020-04-21 18:32
Taken from a similar report: "The set bonus should still apply. However the client won't as we aren't sending set information translated yet."

Using .getstats should highlight the set is infact working - I'll keep this open for confirmation.

**Comment by Nafloin** [comment] 2020-04-21 18:33
sorry whats a .gstats ?

**Comment by Kaelang** [comment] 2020-04-21 18:35
> sorry whats a .gstats ?

Using the command .getstats shows an accurate representation of stat changes. If you type this in-game without the bonus equipped, and then with the bonus equipped, you should see the set bonus reflected with your stats.

**Comment by Nafloin** [comment] 2020-04-21 18:38
![072BBAF5-2190-49E3-AFDB-4754E27986F9](https://user-images.githubusercontent.com/64092484/79901381-0cf5cd00-8410-11ea-9485-fbad0252ca56.jpeg)
![Uploading A2E4BDB0-A072-4AD5-B9F6-526880AEC0C1.jpeg…]()

**Comment by Kaelang** [comment] 2020-04-21 18:48
I believe you was part-way through uploading your second image, but it did not come through.

**Comment by Nafloin** [comment] 2020-04-21 19:06
![F752787C-1FC8-4265-B6FA-A83C6D185BE8](https://user-images.githubusercontent.com/64092484/79903689-cd30e480-8413-11ea-85a0-b77263cc2bb7.jpeg)

**Comment by Kaelang** [comment] 2020-04-21 19:16
Thanks for this - I've just done some quick maths the two items give you a total of 42 strength. The difference between the three items being unequipped and equipped is 79 strength.

Therefore the set bonus of 37 strength is working as intended, it's just a visual issue due to the set bonus' translation. 

Closing this for now as set bonus is working as intended.

**Closed by Kaelang** 2020-04-21 19:16 UTC
Labels: 2 Week Ultimatum, Confirmation Request
