### ISSUE TITLE
"Notched Work Gloves of Fortification" reward for "Love Lost" wrong item icon

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#121] opened 2014-05-10 19:29 UTC
There is an incorrect item icon for one of the rewards on the quest "Love Lost".

The item reward is some gloves but it does not display a glove icon.

![wrong item icon](https://cloud.githubusercontent.com/assets/7492543/2936894/4eacc4cc-d879-11e3-8f5e-bf21928c9e70.png)

**Comment by Reggaewaldo** [comment] 2015-09-21 07:54
The items have been reworked since the post and now it rewards weapons. The weapons are working as intended.

Closing.

**Closed by Reggaewaldo** 2015-09-21 07:54 UTC
Labels: Database, Item, Low Priority
