### ISSUE TITLE
Punt behind machine inside Steamtank Plant

### ISSUE THREAD

**Issue by zabis** [WarEmu/WarBugs#11289] opened 2018-02-12 15:43 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Steps to reproduce the problem: If you line up your opponent with that back wall, you are able to punt him between the wall and the machine, trapping them there for the entire scenario, or until they die.

Screenshots/Videos or archive.org evidences:

https://imgur.com/a/D2K1r

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment] 2018-02-13 07:53
Duplicate of #9520

**Closed by sioding** 2018-02-13 07:53 UTC
Labels: Database, Map/Area, Scenarios
