### ISSUE TITLE
Glowing sprite issue.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#1968] opened 2015-11-25 17:37 UTC
I am posting this bug for a friend, he is unable to post on here so I am posting in his stead.

"At random times during game play character and object models will become completely white and radiant, occasionally only showing back pieces of player models. This problem started occurring after T3 release.

The white models seem to only occur in specific named places such as BO's, PQ's, WC's, or other places on the map with a specified significance. However, once I or anyone else leave these areas the character models return to normal.

I have tried to following to fix the issue:

- Delete cache folders
- Power cycle modem/router
- Reset my wireless adapter
- Direct connection
- Update drivers (they were already up-to-date)
- Relogging/Crashing game when the issue occurs
- Power cycling my PC

Below is a picture of what I experience.

http://i.imgur.com/O2L5uzl.jpg

After the small bug fix yesterday morning (23/11/2015) the issue was not as severe but I did not think to screenshot to show a comparison.

It does not effect my games performance or cause crashing. However, it is difficult to identify friendly and enemy players which causes confusion on the battlefield as well as giving me a headache lol."

**Comment by Luth-RoR** [comment] 2016-07-02 12:15
Issue with Sildurs sweetFX mod and "lightmaps" switched on in the game.
Should be
a) fixed by the creator now (forum)
b) not a bug at all (completely clientside)

**Closed by Luth-RoR** 2016-07-02 12:15 UTC
Labels: Visual
