### ISSUE TITLE
Item not working when clicking on it for quest

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#20516] opened 2022-10-28 21:39 UTC
**Expected behavior and actual behavior:**
To complete the quest "Gud Eatz!" on destro side for the pocket item, the last item to click is not working.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Ceithin_084](https://user-images.githubusercontent.com/25305100/198737325-1362113d-1470-4f24-a9a2-e4513f45eadc.jpg)

**Comment by Rubyeclipse-war** [comment] 2022-10-28 21:42
Thanks for the ticket - just to confirm, did you wait a minute or two and confirm it wasn't someone else also using it just before you?

I believe this item has a cooldown on use, so your party should be able to use it for group credit, but if another player uses it just before you, you'll have to wait a bit to get the credit.

**Comment by Ghatisgob** [comment] 2022-10-28 22:23
Sorry i forgot to be more specific. 
Yes we did wait more than 10mins next to it, in case we missed it.  
I also tried to abandon the quest and start again, without success.

**Comment by AnacardoSH** [comment] 2022-10-29 10:08
I got the same problem and donno how to solve it

**Comment by Rubyeclipse-war** [comment] 2022-10-29 18:58
I've tested this now on the live server and also on dev, but it seems to work for me on both sides.

@Ghatisgob, @AnacardoSH, do you mind abandoning this quest and re-taking it again? Please let me know if that fixes the issue.

**Comment by Ghatisgob** [comment] 2022-10-30 14:12
@Rubyeclipse-war @AnacardoSH 
I tested what you said. I abandoned once again and retake it. It worked fine but this time i first clicked on the Wyvern Drops and not the other one.

**Comment by Rubyeclipse-war** [comment] 2022-11-13 19:04
Since we've been unable to reproduce this on our side, and confirmed that it does work properly for most people, including those bugged if they abandon and retake the quest, I'm going to leave this open for 14 days in case anyone has any other info that may help us understand what causes it. After that, the ticket will auto-close. Thank you!

**Comment by lilimx** [comment] 2022-11-30 19:10
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.

**Closed by lilimx** 2022-11-30 19:10 UTC
Labels: Database, Quests, 2 Week Ultimatum
