### ISSUE TITLE
Magus Glacier Blue Disk

### ISSUE THREAD

**Issue by Tephin** [WarEmu/WarBugs#12416] opened 2018-10-07 00:40 UTC
My 60% mount that I just bought today unfortunately wont work in the lake or in scs. I didn't test with other 60% mounts as I don't have the cash to buy another, however I did test that my 50% still works just fine. 

In addition to not being able to summon it it also has a smoke trail behind me as I use it when I am able to mount up (in the city or warcamps).

**Comment by sioding** [comment] 2018-10-07 08:30
Duplicate of #12184

**Closed by sioding** 2018-10-07 08:30 UTC
