### ISSUE TITLE
Guild bug

### ISSUE THREAD

**Issue by sirgregor** [WarEmu/WarBugs#11192] opened 2018-01-22 12:39 UTC
https://ru.files.fm/u/bbjus4n5

Do not set the guild emblem on the cloak / banners of the guild.
Gold (100g) in stock, guild level 21 (20+), the selected parameters are not saved. The text of the error is displayed (in the image in the attachment)

**Comment by sioding** [comment] 2018-01-22 14:29
Duplicate of #4409

**Closed by sioding** 2018-01-22 14:29 UTC
