### ISSUE TITLE
Backpeddling doesn't cancel mounting up. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16206] opened 2020-04-02 21:39 UTC
**Expected behavior and actual behavior:**

When you move on your character, you should cancel your mount summon. However, if you backpeddle, or even diagonally backwards walk, your mount will still be summoned. 

**Steps to reproduce the problem:**

Start your mount cast, and start walking backwards with S or the down key. 

![image](https://user-images.githubusercontent.com/60117106/78302445-b7c24c00-7532-11ea-93a3-ebbbce295fbc.png)

**Comment by Lheana** [comment] 2020-04-03 10:48
Duplicate of #16136

**Closed by Lheana** 2020-04-03 10:48 UTC
