### ISSUE TITLE
Apostle's Tome of Devotion bugged

### ISSUE THREAD

**Issue by skattefar89** [WarEmu/WarBugs#18913] opened 2021-04-28 10:34 UTC
Apostle's Tome of Devotion does not gein any fury

**Comment by bloodmasked** [comment] 2021-04-30 02:30
#18512

#17435

Already known for some time. The solution is to leave combat, unequip and re-equip the chalice or book until it starts working again.

**Comment by Lheana** [comment] 2021-05-01 14:54
Duplicate of #18512

**Closed by Lheana** 2021-05-01 14:54 UTC
