### ISSUE TITLE
The boundless "mirroring"

### ISSUE THREAD

**Issue by popolacarotte** [WarEmu/WarBugs#5255] opened 2016-04-09 11:11 UTC
Well, I opened the Auction Hall to buy an Axe for my Slayer Reroll.

And what a surprise.

Just take a look at what I found

[b]Dwarf 2H[/b]
[url=http://www.hostingpics.net/viewer.php?id=185411Dwarf2H2.jpg][img]http://img15.hostingpics.net/pics/185411Dwarf2H2.jpg[/img][/url]

Take a look at this beauty, badass hu ?

I also found this one, 
[url=http://www.hostingpics.net/viewer.php?id=526169Dwarf2H1.jpg][img]http://img15.hostingpics.net/pics/526169Dwarf2H1.jpg[/img][/url]
But we already know this one right ?

[b]Orc 2H[/b]

[url=http://www.hostingpics.net/viewer.php?id=501004Orcs2H.jpg][img]http://img15.hostingpics.net/pics/501004Orcs2H.jpg[/img][/url]

Not really the same since the Dps is shittier.

Can somebody explain why such difference ? Or why I NEVER found the "TrollSplitter" mirror ?
Or fix this joke ? I don't know.

[b]Bonus - For shit and giggles[/b]
[b]White Lion 2H[/b]

[url=http://www.hostingpics.net/viewer.php?id=500057WL2H.jpg][img]http://img15.hostingpics.net/pics/500057WL2H.jpg[/img][/url]
Outclassing the Trollsplitter in many way, for some reasons...
2.9 Speed. The same as a 1h axe. Wow.

No wonder why they shit on every one.

**Comment by Ryanfawkez** [comment] 2016-04-09 11:18
Not a bug. Closing.

**Closed by Ryanfawkez** 2016-04-09 11:18 UTC
