### ISSUE TITLE
Tactic Oppressing Blows issue

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#11006] opened 2017-12-16 16:13 UTC
In recent patch it says that "Tactic Oppressing Blows now additionally causes the melee channel ability Relentless to deal Spiritual damage". However, critical hit bonus disapeared.

**Comment by sioding** [comment] 2017-12-16 18:24
Duplicate of #11004

**Closed by sioding** 2017-12-16 18:24 UTC
