### ISSUE TITLE
[Tactic] Keep It Comin' bug; dead while alive

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#11473] opened 2018-03-18 11:24 UTC
In doomfist crater my Keep it Comin' activated and i rezzed, then died while still alive. I had an active health bar and was being healed and damaged but could not move or activate any abilities and there was no option to rez.

- Skurrga Eadcleava of da Black Toof Clan

Screenshots/Videos or archive.org evidences:

<img width="960" alt="self rez death" src="https://user-images.githubusercontent.com/37393516/37565298-3ba23650-2a7d-11e8-8581-13a9f40d60b1.png">

**Comment by sioding** [comment] 2018-03-18 12:13
Duplicate of #10682

**Closed by sioding** 2018-03-18 12:13 UTC
