### ISSUE TITLE
Warrior Priest Divine Strike - Not healing for damage dealt

### ISSUE THREAD

**Issue by FAmeloon** [WarEmu/WarBugs#12889] opened 2018-12-21 03:25 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Divine Strike isn't healing for 100% of the damage done, instead only healing for 1/3 or 1/4 of the damage done.

Steps to reproduce the problem:
Unsure. I levelled my Warrior Priest to Tier 2, and brought her into ORvR. Helped in taking two keeps, and noticed my healing procs when hitting with Divine Strike were consistently 1/3 or 1/4 of the healing that they should be doing with the damage I was outputting. There were no healing debuffs on, nor anything that would reduce the amount of healing put out by my attack.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-21 07:37
Duplicate of #12658

**Closed by sioding** 2018-12-21 07:37 UTC
