### ISSUE TITLE
[Fortress] couldn't join Fortress even with reserved spot

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#13583] opened 2019-03-09 20:23 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Despite reservations, I could not enter the portal. I was right on time at the portal.

**Screenshots/Videos or archive.org evidences:**
![Lillet_098](https://user-images.githubusercontent.com/23266079/54076910-407ba380-42b1-11e9-9b09-93bdeca6832c.jpg)
![Lillet_099](https://user-images.githubusercontent.com/23266079/54076924-6f921500-42b1-11e9-91c3-5009a0303c45.jpg)

**Comment by sioding** [comment] 2019-03-10 06:17
Duplicate of #13536

**Closed by sioding** 2019-03-10 06:17 UTC
Labels: Fortresses, Sourcecode
