### ISSUE TITLE
Soup is Good Food - Mysterious Meat

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#11852] opened 2018-06-09 11:23 UTC
Issue with killing the mysterious meat. The mob is unkillable. 

Not sure if we're doing this incorrect and we're meant to take down the keep before killing them.

MDPS stealth and pulled the mob on the top floor but cannot kill it on top floor or on bottom.

![lileldys_065](https://user-images.githubusercontent.com/13259775/41190957-a7ba5e64-6bdf-11e8-80d6-ccec1af7c063.jpg)

**Comment by Lileldys** [comment] 2018-06-09 20:57
I get that the zone requires to be open, but the zones aren't always open, meaning you cant progress without.

**Comment by sioding** [comment] 2018-06-12 17:34
Duplicate of #11883

**Closed by sioding** 2018-06-12 17:34 UTC
Labels: Database, NPC, Quests

**Comment by NorKalli** [comment] 2018-06-12 17:59
the purpose of this step is to require you to partake in a keep siege, MDPS sneaking in is not the intention.  Quest isn't meant to be able to be breezed through. :)
