### ISSUE TITLE
No roll and no bag after zone lock

### ISSUE THREAD

**Issue by Akirg** [WarEmu/WarBugs#10851] opened 2017-11-18 09:25 UTC
Hello i was TP  from WC to MS when it's lock.
Before i participated to kill some player (valide in the kill quest) and make damage on the enemy keep lord.
![poupinette_003](https://user-images.githubusercontent.com/33703701/32978867-ce39435a-cc4a-11e7-863d-35c095686db6.jpg)

**Comment by sioding** [comment] 2017-11-18 09:26
#10851

**Comment by sioding** [comment] 2017-11-18 09:27
Duplicate of #10828

**Closed by sioding** 2017-11-18 09:26 UTC
