### ISSUE TITLE
Mara's Hands

### ISSUE THREAD

**Issue by Judart** [WarEmu/WarBugs#953] opened 2015-07-10 15:44 UTC
Mara's hand buffs(Gift of Savagery and ather) not proс when you throw ax and not burst when you put points in mastery path.

**Comment by ozarmidrashim** [comment] 2015-07-11 07:29
"Mara's hand buffs(Gift of Savagery and ather) not proс when you throw ax"

This was changed deliberately.

**Comment by Judart** [comment] 2015-07-11 12:45
http://www.youtube.com/watch?v=VkVWnyGgxcM

**Comment by ozarmidrashim** [comment] 2015-07-11 18:04
Yes. I don't care how it was in live; this was changed *deliberately*, and will be general for all melee classes to prevent exactly the kind of cheese shown in that video.

**Comment by Silentguard** [comment] 2015-07-12 02:59
Than you should remove kiss proc from WE dagger throw.

**Comment by Judart** [comment] 2015-07-12 08:34
So I don't know what I can report more. If you don't care about live WAR every bug can be changed deliberately. I thought you doing game Warhammer online but seems not.

**Comment by noisestorm** [comment] 2015-07-12 12:10
> I thought you doing game Warhammer online but seems not. 
Stop being a faggot. Report what you find out to be a bug - if something gets, due to its obviously inbalance, changed you will hear that. There is no reason to adapt every
bullshit mythic implemented in Warhammer.

**Comment by Judart** [comment] 2015-07-12 13:05
Every mythic bullshit it's part of favorite mmo and which we all so like. But this fix start destroy one part. It was one of op feature of mara and now it's gone. And stop insult me pig for expression my views.

**Comment by ozarmidrashim** [comment] 2015-07-12 15:46
"Than you should remove kiss proc from WE dagger throw."

Done.

"Every mythic bullshit it's part of favorite mmo and which we all so like."

Nah not all of us like easymode and bullshit.

**Comment by Judart** [comment] 2015-07-12 16:56
Easy mod? You think befor fix me just run and kill every orders by throw axes? :D Ok ok thx for attention my friends.  Bless you Raven god, Orders. ;)

**Comment by Evildoor** [comment] 2015-07-12 19:22
Well, since the changes were already made - can we also do the same with DoK/WP? And i'm talking about raw damage as well as covenant/prayer procs. Unlike throwing axes/knives/whatever, Fist of Khaine/Judgement scaled from STR in official WHO, so its damage was pretty high, which was lame.

**Comment by Thorgatin** [comment] 2015-07-12 19:24
The new code is designed, that there should be no proccs from axethrows. Any exception should be a bug afaik.

**Comment by Silentguard** [comment] 2015-07-13 03:29
Prayers and covenants was designed to buff melee and ranged classes, not melee only. BTW Fist of Khaine and Judgement is melee attacks.

**Comment by ozarmidrashim** [comment] 2015-07-13 10:37
Per Silentguard. The intent is to prevent melee classes from activating their own procs, whether class-internal or item-based, from throwing axes.

**Comment by Evildoor** [comment] 2015-09-17 17:56
Closing since this is a change which was made by developers's decision.

**Closed by Evildoor** 2015-09-17 17:56 UTC

**Comment by Zealote** [comment] 2016-06-30 09:23
Seems this crap's back - throw axe is proccing stuff again.

**Comment by Luth-RoR** [comment] 2016-06-30 12:19
It was reverted a few months ago because some full-time mara complained about it on the forum and it was against the "no-balance-changes-before-T4" policy.
