### ISSUE TITLE
Vaul's Buffer tactic unusable at my level

### ISSUE THREAD

**Issue by RonRonaldJeremy** [WarEmu/WarBugs#12104] opened 2018-07-29 18:13 UTC
Expected behavior and actual behavior:
 As far as I am aware Vaul's buffer tactic was recently lowered to 7th level of Path of Vaul but the game still thinks that its still at rank 11 so it just blocks it

Steps to reproduce the problem:
 Pick Vaul's Buffer tactic while having level lower than 27 (at 27th level you've got enough mastery points to unlock tactic at 11th rank of Path of Vaul *old place of tactic*)

Screenshots/Videos or archive.org evidences:

![bazingga_012](https://user-images.githubusercontent.com/41800675/43369300-ccda60a0-936b-11e8-996a-b25ee041bda5.jpg)

**Comment by sioding** [comment] 2018-07-29 19:29
Duplicate of #12100

**Closed by sioding** 2018-07-29 19:29 UTC
