### ISSUE TITLE
Renown Ability (Vigor) not working.

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1523] opened 2015-09-25 00:39 UTC
Vigor doesn't increase your wounds like it suppose to. Don't know if other stat increasers are also bugged or not.
http://s28.postimg.org/z282zoan1/Puddlez_028.jpg

**Comment by xyeppp** [comment] 2015-09-25 09:25
Un-equip anything with wounds and equip it back, your HP will now properly update to reflect the renown training.

**Comment by Evildoor** [comment] 2015-09-25 10:36
Hmmm. https://github.com/WarEmu/WarBugs/issues/1489 says about hotfix solving this problem, but comment here makes me think that it was relog caused by that hotfix rather than hotfix itself. Ok, let's do it this way - @magter3001 , can you please try @xyeppp 's solution and post here if it fixed your problem or not? If yes, then i'll close this issue and update https://github.com/WarEmu/WarBugs/issues/1489 about this.

**Comment by magter3001** [comment] 2015-09-25 18:55
@xyeppp, that fixed it, thanks. Still a bug though because it requires you to do that :)

**Comment by Evildoor** [comment] 2015-09-25 19:11
Hmmm, strange. Tried this myself, sometimes even hitting a mob with an ability (not affecting wounds, i tested this on IB. More like any ability which affects your character sheet - armor buff, for example) is enough to update your stats. Bug is not visual, if you take enough damage to nullify your basic hp (without wounds from vigor) without updating your stats you die.

**Comment by Evildoor** [comment] 2015-12-19 11:16
Seems to be almost fixed as of 18.12.2015 - after small delay, wounds appear and HP change properly.

**Closed by Evildoor** 2015-12-19 11:16 UTC
Labels: Emulator
