### ISSUE TITLE
Squig herder range of skils

### ISSUE THREAD

**Issue by Wachlarz** [WarEmu/WarBugs#18693] opened 2021-03-21 10:14 UTC
From last patch my rshy shoot from more range then sorc. I think old tac (shoot wif da wind) give range + gas squig givs range.

**Comment by lilimx** [comment] 2021-07-07 07:45
Hey,

Does this issue still persits?
I've tried to reproduce it, but it looks like that everything works as intended

**Comment by lilimx** [comment] 2021-07-21 10:41
Hey,

im closing this ticket now due to no feedback.

**Closed by lilimx** 2021-07-21 10:41 UTC
Labels: 2 Week Ultimatum, Confirmation Request
