### ISSUE TITLE
I have killed 38 Matriarchs during the event. I have 0 kill credit for the event. Please fix this already. The event ends tomorrow.

### ISSUE THREAD

**Issue by Twicckk** [WarEmu/WarBugs#16394] opened 2020-04-15 18:16 UTC
![image](https://user-images.githubusercontent.com/63669306/79372144-2a5ffe00-7f1b-11ea-847a-81899f04281e.png)

38 matriarchs, that is constantly looking for a group since day 2 of the event. This has been a huge waste of time for a lot of people. Can't yall just universally flag the credit?

thirty freaking eight. It shouldn't be this retarded for a tank to participate in an event :(

**Comment by GhostOntro** [comment] 2020-04-15 18:42
Same here. 20 + kills in all combos. Getting the KB, tagging her 1rst, being the one cracking the egg that contains her, not being the one cracking the egg that contains her, you name it. No credit.

**Comment by Lheana** [comment] 2020-04-15 19:28
Duplicate of #16353

**Closed by Lheana** 2020-04-15 19:28 UTC
