### ISSUE TITLE
Mastery respec

### ISSUE THREAD

**Issue by Shiftseven** [WarEmu/WarBugs#11908] opened 2018-06-18 14:37 UTC
Expected behavior and actual behavior:

I'm in Altdorf trying to respec my mastery points. When I hit respecialize it says "5 gold 80 silver" even though I havent respeced earlier. I click respec and nothing happens with my mastery points, they're still the same but the money is taking from my bags.

Steps to reproduce the problem:

I'm standing close to the Trainer Arno, and when I hit the button it says that I need to get closer to the trainer, so I guess that's the problem. The thing is that it half worked since it took my gold but didnt give me a respec. 

Screenshots/Videos or archive.org evidences:

No video of this but I'll gladly help anyway I can to make the game better.

Kind regards

**Comment by sioding** [comment] 2018-06-18 15:58
Duplicate of #11583 

Tried it on my own - and sorry not reproducable. Could be something when the server is not be in a stable situation. But if there is no errormessage and we are not able to repriduce it - we can not fix it.

**Closed by sioding** 2018-06-18 15:58 UTC
