### ISSUE TITLE
Cant do that whilst carrying a standard ?

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#8322] opened 2016-11-13 01:49 UTC
getting this message OSD when im using my shadow warrior

*Cant do that whilst carrying a standard *

i cant be the only one surely?

in short,spiral fletched arrow assigned to a hotkey then assigned to mouse button,upon multiple use of this ability in combat or PVE,the above message will regularly display on screen.i dont have a standard equiped or otherwise.and cant seem to repilicate it on other toons with a similar key bind set up.
is this known to anyone else?

**Comment by Luth-RoR** [comment] 2016-11-13 08:08
I never heard of it before.

**Comment by Simmox** [comment] 2016-11-13 10:41
ok i will try and experiment a bit more to see if i can be more specific on how it triggers

**Comment by Ellenwe** [comment] 2016-11-15 15:13
I have this issue only on my shadow warrior too. I have noticed this message only with "Split arrow" tactic (this tactic is for AoE spiral arrow). 

Hope it can help...

**Comment by Luth-RoR** [comment] 2016-11-15 17:52
I couldn't reproduce this on the dev server (new level 40 SW with tactic and SFA spam. Do you have any addons installed?

**Comment by Simmox** [comment] 2016-11-16 03:33
yea i do,quite a few
the usual suspects
squared and its assets
buffhead
potionbar
wsct
i shall disable a few one at a time and see if i can aquire it
its very difficult to reproduce but i can regularly in one specific spot in BC,farming the 4 wyverns near oathbearers WC.
i have SFA assigned to slot 3 and assigned one of my mouse buttons to emulate a 3 press

**Comment by Simmox** [comment] 2016-11-23 08:32
you know,i dont know about the other fella,but, cant get this to happen anymore,i tried for several hours on and off the other nite and couldnt get it to trigger.
patch mustve fixed it by coinicidence

**Comment by Luth-RoR** [comment] 2016-11-24 20:02
K, closing then.

**Closed by Luth-RoR** 2016-11-24 20:02 UTC
Labels: Confirmation Request
