### ISSUE TITLE
Scaven quest

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#10598] opened 2017-10-14 21:30 UTC
It seems impossible to finish [Raising The Empire Banner] and complete the last of scavens quests. After BO changes whatever i do at verentane tower it doesnt count as captured for the quest sake so no progression past that

**Comment by sioding** [comment] 2017-10-14 21:49
Duplicate of #10533

**Closed by sioding** 2017-10-14 21:49 UTC
