### ISSUE TITLE
Gunbad bugs: 1:cant get the reward after i got 3 kill of the boss, 2: the mid wing last sqing bug

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#14142] opened 2019-05-20 15:43 UTC
We found 2 bugs in the gunbad:

1: we cant get the reward after we got 3 kill of the boss,

this is the reply in the report of the gunbad's bug post:
https://github.com/WarEmu/WarBugs/issues/12850

2: The mid wing last boss spawned egg which can not destroy. (The boss can heal himself by eggs)

**Comment by sioding** [comment] 2019-05-20 16:51
Duplicate of #12850

**Closed by sioding** 2019-05-20 16:51 UTC
