### ISSUE TITLE
Cannot move Stacked Items to and from bank.

### ISSUE THREAD

**Issue by Evilbenji821** [WarEmu/WarBugs#13961] opened 2019-04-28 00:26 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Stacked items to move to and from bank/inv. 
Error occurs "Cannot equip an item thts stacked. Please report this to the bugtracker."

**Steps to reproduce the problem:**
Move stacked items to and from, doesn't matter if consumable, trash items, crafting material (just stacked).

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/50061449/56856518-5a894800-692a-11e9-8b6c-5bf484b20638.png)

**Comment by sioding** [comment] 2019-04-28 06:48
Duplicate of #13958

**Closed by sioding** 2019-04-28 06:48 UTC
