### ISSUE TITLE
Re: Ticket - The Threat Revealed #7534

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11475] opened 2018-03-19 04:38 UTC
Ticket 7534 from 2016 is still opened but appears abandoned, with no assignee.

Quest: The Threat Revealed

Quest text says slay guards and retrieve keys from wardens to free captive elves.
Step tasks are "Uthorin Cage Sentries 9/9" and "Ellyrian Captives 0/3"

In a copse of trees at about 49k, 57.6k there is a slave wagon surrounded by many Uthorin Warden and Uthorin Cage Sentry. Killing the sentries gives credit but killing the wardens does not earn any keys. No a side note, I've recently deleted (a few quests ago)about 40 quest item gor horns from my quest backpack. While looking for keys I noticed 3 stacks of "Parchment" totaling 86 items had recently appeared after killing wardens. I'm not sure if that is related.

At this same slave wagon area there are "Ellyrian Prisoner"s in cages. They don't respond to interaction and the cages, though selectable, don't either...even after killing many wardens.

Near the perimeter of the map (Example at abot 51,970, 57410) target lake you can find Uthorin Dreadblades guarding Ellyrian Reavers that are ankle chained to stakes. Even after killing wardens these Reavers and their leg chains/stakes don't respond to interaction either.

**Comment by sioding** [comment] 2018-03-19 07:11
Duplicate of #7534

No Ticket is "abandoned" - as you can see more than thousand open ticket means: we do not kill tickets after a time. We will work on it -if there is some time....

**Closed by sioding** 2018-03-19 07:11 UTC
