### ISSUE TITLE
Guild Heraldry

### ISSUE THREAD

**Issue by Neil0r** [WarEmu/WarBugs#14256] opened 2019-05-29 09:37 UTC
1)
The text in the guild reward window is a bit misleading. The reservation (available at GR10) of a heraldry doesn't mean you can see it in any way after choosing one. This causes me (and others) to do it again and again. I've spent more than 200 Gold ... The popup about approximate costs was totally wrong, I had something like 1790 873676 or so :-)

2)
At GR15 the heraldry should be appear on the cloak. We are GR15 but it doesn't appear. The standard symbol of the 3 races our faction are shown.

3)
I'm hoping with GR20 the "Heraldry Reveal: Emblem" will fix everything.

**Comment by sioding** [comment] 2019-05-29 12:37
Duplicate of #9791

**Closed by sioding** 2019-05-29 12:37 UTC
