### ISSUE TITLE
[Quest] Scouting quest not being scouted

### ISSUE THREAD

**Issue by CptEdward** [WarEmu/WarBugs#18927] opened 2021-04-30 18:22 UTC
Hi, please find below what I think could be an bug. Could not find any feedback from ingame community.

Kind regards,

**Expected behavior and actual behavior:**
Expected : validation of the quest "Get Dat Stunty Tunnel!" in Kadrin Valey should be 1/1 if we visit the area near the flag and around.
Actual : scouting the area, near and far of the flag does have no effect on the quest

**Steps to reproduce the problem:**
Just pick the quest at the WarCamp "Zone d'baston de Krung" and go in the tunnel between "Jonction du Gromril" and "Chutes d'eau-sévère" in the flag area named "Croisement de Foyer-glacé", and run in the area to scout.

**Testing Screenshots/Videos/Evidences (always needed):**

![2](https://user-images.githubusercontent.com/59454916/116737495-952e8b00-a9f1-11eb-98f0-0997a0c84f62.PNG)
![3](https://user-images.githubusercontent.com/59454916/116737497-965fb800-a9f1-11eb-800a-f52aeba3c4f8.PNG)
![1](https://user-images.githubusercontent.com/59454916/116737500-965fb800-a9f1-11eb-82a8-7630dd23e77b.PNG)

**Comment by Lheana** [comment] 2021-05-01 14:52
Duplicate of #18591

**Closed by Lheana** 2021-05-01 14:52 UTC
