### ISSUE TITLE
Marauder - Gift of Brutality bonus not working

### ISSUE THREAD

**Issue by Joculari** [WarEmu/WarBugs#16055] opened 2020-03-21 13:52 UTC
**Expected behavior and actual behavior:**
Gift of Brutality mutation should give a 25% chance to give a 5 second buff that makes the Marauder strike the enemy with the offhand weapon with every attack made. For example Flail attacks the target twice so with the buff it should attack twice plus another two offhand attacks.
But the buff only seem to trigger on autoattacks which makes it fairly useless and severely weakens the supposed burst DPS mutation for Marauder.

**Steps to reproduce the problem:**
Simply attack a target dummy or enemy until the buff triggers then use any skill to deal damage, no damage from offhand attacks are shown on screen or in combat log on any skill or attack except autoattacks.
As seen in the images below when using Flail and Convulsive Slashing there are no extra offhand attacks with each hit on the target and it only seems to work with autoattacks.

**Testing Screenshots/Videos/Evidences (always needed):**

![Khorlac_002](https://user-images.githubusercontent.com/62059855/77227857-5c33ae00-6b83-11ea-9ee9-73b3fc7abd76.jpg)
![Khorlac_003](https://user-images.githubusercontent.com/62059855/77227860-60f86200-6b83-11ea-8bfc-f045ed73348a.jpg)

**Comment by Zunig** [comment] 2020-03-24 16:48
Off hand weapon swing relates to aa from offhand, not abilities. Every time you do aa your main hand guarantees hit, while your off hand have a chance to do it, for weaker dmg. 
Its same for every dual wield dps. Brut proc is only adding bonus chance to that secondary swing.

Wouldnt argue hovewer that this mutation proc is pretty weak considering your aa isnt affected by pb anymore.

**Comment by Kaelang** [comment] 2020-04-23 00:52
Closed as this looks to be working as intended.

**Closed by Kaelang** 2020-04-23 00:52 UTC
