### ISSUE TITLE
Loot Bag Won't Open

### ISSUE THREAD

**Issue by TheCustomTitan** [WarEmu/WarBugs#6840] opened 2016-06-16 04:02 UTC
I Won a purple bag for a long Keep Defense. It had a Shard Token in it. So, I went to see what loot was offered for it. 
I clicked on the vendor to view the items. While I was still in open view of the vendor, I had clicked on the bag to open it... But, of course, I inadvertently sold it.
I bought the bag back from the vendor but it would no longer open.

Can this be fixed?

**Comment by Ryanfawkez** [comment] 2016-06-17 08:57
Think selling the bag to vendor inadvertently wrecked it. I'm afraid it cannot be fixed.

**Comment by zak68** [comment] 2016-07-04 09:38
happened to me too; is it possible to flag it as "not sellable" or anything like that ?

**Comment by Zealote** [comment] 2016-08-06 22:48
Duplicate of #5392. This one's got the nice colourful labels though!

**Comment by Yellowpillow** [comment] 2016-08-17 00:42
same happens with any bag, golden, blue or green.

**Comment by stortzm** [comment] 2016-09-07 22:24
this has happened to me too
however, a PQ lootbag works after being bought back
only ones that broke for me are the RvR ones

**Closed** 2016-11-22 18:38 UTC
Labels: Cannot Fix Yet, Database, Item
