### ISSUE TITLE
Wh Bullets

### ISSUE THREAD

**Issue by rethmar** [WarEmu/WarBugs#20219] opened 2022-06-26 03:21 UTC
WH Bullets from different whs are debuffing intitive twice

**Comment by lilimx** [comment] 2022-06-26 07:47
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by rethmar** [comment] 2022-06-26 16:55
wh bullets debuff intitive once, non-stacking

wh bullets debuff intitive twice, stacking

attacked by 2 different whs

statdoll shos stats going from 250 to 89

**Comment by lilimx** [comment] 2022-06-26 17:50
Hey,

statdoll is no reliable source, use .getstat instead.,
Additional I need pictures or a clip that shows the issue.

**Comment by rethmar** [comment] 2022-06-26 19:10
yea, because i can reliably take a screenshot and know when 2 whs are gonna attack or use .getstats in the 10 secs they hit me right?

**Comment by lilimx** [comment] 2022-06-27 17:54
Hey,

please add screenshots

**Comment by Rubyeclipse-war** [comment] 2022-06-29 23:37
> yea, because i can reliably take a screenshot and know when 2 whs are gonna attack or use .getstats in the 10 secs they hit me right?

I can help you get two Witch Hunters online to proc this for you so you can gather the screenshot to add. You can message me on Discord at Rubyeclipse#3749 or mail Rubius on Order side.

**Comment by taccr** [comment] 2022-07-01 02:28
> statdoll shows stats going from 250 to 89

Since the statdoll shows initiative being reduced twice it can't really be a bug. If the client says it's that low then it is law and exactly like it was working back on live. You can check with .getstats if it is also stacking in the ror implementation but it can't be a bug. I agree however that it should not stack.

**Comment by Undrsiege** [comment] 2022-07-03 03:54
Yep seen this happen also.... Seems High priority to me to at least examine the ability in code.  I have not been able to use .getstats in combat..

**Comment by lilimx** [comment] 2022-07-03 07:32
Hey,

Im still missing a video or screenshots!

**Comment by Zomega-WAR** [comment] 2022-07-08 18:14
> Since the statdoll shows initiative being reduced twice it can't really be a bug.

The stats doll uses ability information in a client-side DB, which has known to be incorrect on live/ROR has become corrupted many times on ROR.

**Comment by rethmar** [comment] 2022-07-08 22:44
You cant take a screenshot when getting hit by 2 different whs in 10 secs because you cant .getstats when you target a enemy.

Make sense?

**Comment by lilimx** [comment] 2022-07-11 16:47
Hey,

so we hit the 15 days and I've got no proof...no screenshot or a video
I am closing this ticket now as we have not received any further information regarding the problem.

Please open a new ticket with proper evidences.

**Closed by lilimx** 2022-07-11 16:47 UTC
Labels: Confirmation Request, 2 Week Ultimatum
