### ISSUE TITLE
Fort Rewards Bugged

### ISSUE THREAD

**Issue by Azerreth** [WarEmu/WarBugs#13610] opened 2019-03-11 17:28 UTC
Last night destro(Where I was) Defended the Fell landing, and order was on the siege end of the battle. We went at it for quite a while and even with the respawn bug on our end, where we did not appear in the cages it proceeded to go back and forth. (Good fight all around.) However when we got to the end of the battle there were no rewards handed out, no medallions or bags to be seen.

To Top that off we had to book-bind to get out of the fort, which I Feel might be a bug seeing as like an SC it should remove you? I don't know it was my first fort siege, so I am unsure on how that portion worked but I am well aware we should at minimum get some sort of reward.

Im not sure if we will be compensated (I doubt it) by coins or something, but we were pretty bummed out and angry. Until the issue is fixed I suggested people avoid the forts; Because it offers nothing but an hour of being farmed if you're on the defense. (Not fun knowing there is no silver lining.) Im well aware the devs probably know about it, but I am unsure of the cause.

Im sorry to say I did not take any screenshots of it last night, I was tired and a bit tipsy so I logged after the fort siege as it was late where I was. Please fix this ASAP, I love this game and I really wana do the forts; I just can't justify doing them without a chance at a reward knowing there is no way to be compensated later because It would be sort of unfair.

**Comment by sioding** [comment] 2019-03-11 17:30
Duplicate of #13605

**Closed by sioding** 2019-03-11 17:30 UTC
