### ISSUE TITLE
[Quest] Destruction From Within

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14620] opened 2019-07-22 18:15 UTC
The sand object for this quest in the Chaos Wastes is missing in the quest area. The mobs tha it is to be used on are present. Image of the quest can be found here https://imgur.com/a/ajb1Eae .

**Comment by Lheana** [comment] 2019-11-13 18:13
Duplicate of #14365

**Closed by Lheana** 2019-11-13 18:13 UTC
Labels: Database, Quests
