### ISSUE TITLE
Serpent's Passage Drop Point Bugged From BW Aoe Spell

### ISSUE THREAD

**Issue by Lightsbane** [WarEmu/WarBugs#11109] opened 2018-01-08 06:25 UTC
###  *Serpent's Passage Drop Point Bugged From BW Aoe Spell Annihilate*

I was trying to stop destro from capping the part in Serpent's passage Racta had the part tried to cap
it and i used the spell annihilate to keep him in combat and stop the cap.

problem is the drop point disappeared and Racta could not cap the part. Racta asked me what happened and i said i used annihilate on him. I was not expecting for the drop point to disappear
i didnt manage to get any proof because i got killed, but Racta said he would report it too.

if its anything else i can do please contact me. i am mostly on my BW Flamea.

Thank you for your effort.
Lightsbane

**Comment by Natherul** [comment] 2018-01-08 10:22
cant seem to reproduce, can you please confirm that it was not a weird fluke?

**Comment by Lightsbane** [comment] 2018-01-08 19:08
Well it might be a fluke but it happened when Racta was capping the part. i used annihilate to interrupt the cap and the drop point disappeared. i will Ask Racta to check if he did the bug tracker report  or if he got screenshots at least you will get his point of view while he was capping.

**Comment by Lightsbane** [comment] 2018-01-08 19:38
So the spell rotation i was using is the standard for the spec i play Ignite, Slow boil,Boiling blood, spreading flames, detonate, firebreath,backdraft, scorched earth and annihilate the tactics i use are intel tactic,wildfire,explosive force and flashfire. i doudt that flashfire or the intel tactic triggered something like that, so it has to be something from the above spells. but i believe its either annihilate,scorched earth,spreading flames or backdraft or a tactic getting triggered.

**Comment by Natherul** [comment] 2018-05-28 07:09
Since we have been unable to replicate Im closing the ticket. Should you encounter this again please reopen this ticket by adding new data here.

**Closed by Natherul** 2018-05-28 07:09 UTC
Labels: Confirmation Request, Scenarios
