### ISSUE TITLE
RVR guild Quest after Claimed keep.

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#14595] opened 2019-07-16 15:26 UTC
Alright..it didnt counted again. We did what Natherul said about claim keep. We lost 160 golds ( Praag and Dragonwake )
theres the link:

https://media.discordapp.net/attachments/566350265842663425/600709215794888704/Nekkbraka_200.jpg

**Comment by sioding** [comment] 2019-07-17 17:30
Duplicate of #14569

**Closed by sioding** 2019-07-17 17:30 UTC
