### ISSUE TITLE
[Item] [Warsong] Knight Epic Proc (preservation) not working

### ISSUE THREAD

**Issue by DillPickle420** [WarEmu/WarBugs#14328] opened 2019-06-02 23:46 UTC
The +72 wounds proc from Preservation on the t4 epic quest item, Warsong, doesn't work. The preservation proc on conq armor still works.

**Comment by sioding** [comment] 2019-06-03 16:06
Duplicate of #14250

**Closed by sioding** 2019-06-03 16:06 UTC
