### ISSUE TITLE
[Morale 1 RDPS] Concealment doesnt protect from ticks of dots

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#12749] opened 2018-11-30 11:55 UTC
if you have some dots on you using m1 Concealment (100% dodge, disrupt for 7 sec) should protect you from dot ticks. All direct dmg and ticks dots should be dodged or disrupted.
Now this morale protects just from appliyng of dots and direct abilities.

**Comment by sioding** [comment] 2018-11-30 15:28
Duplicate of #11826

**Closed by sioding** 2018-11-30 15:28 UTC
