### ISSUE TITLE
Camera randomly stuck

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16379] opened 2020-04-14 06:58 UTC
**Expected behavior and actual behavior:**
Expected: Camera to follow the character
Actual: Randomly get stuck while the character still doing their things

**Steps to reproduce the problem:**
No clue, 2nd time this happened and both time didnt have anything in common

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=rZR2_AMyE68&feature=youtu.be

**Comment by Kaelang** [comment] 2020-04-19 16:31
Duplicate of https://github.com/WarEmu/WarBugs/issues/15340.

**Closed by Kaelang** 2020-04-19 16:31 UTC
