### ISSUE TITLE
Wrong Stat

### ISSUE THREAD

**Issue by Judart** [WarEmu/WarBugs#654] opened 2015-03-08 23:43 UTC
Bloody Bigloppa(Orc's both hands ax) has lower dps then ather both hands bloody wepon.
![begemot_058](https://cloud.githubusercontent.com/assets/11213529/6548354/7dfefdbe-c606-11e4-9d66-a6e7404e4d69.jpg)

**Comment by Evildoor** [comment] 2015-03-09 15:30
It seems that Bloody Deathaxe's 24.1 is also too low - Bloody Glaive and all Bloody staves have 24.7 dps. Gale Runner twohanders have exactly the same problem - Bigloppa has 19.5 dps, Deathaxe has 21.0, while Gale Runner's Glaive and staves have 21.8 dps.

**Comment by Evildoor** [comment] 2015-09-17 17:33
Problem still persists, so i'm reopening this, unless someone explains, why it was closed.

**Comment by Reggaewaldo** [comment] 2015-09-21 09:50
We currently don't have any source/hard fact on the wepons.
Therefore we are a bit unsure on how to handle this type of balancing as of now.

I will take this up with the other devs and return with a soloution.

**Comment by Reggaewaldo** [comment] 2015-09-27 16:12
I have started working on this but it's a bit tricky will come back when I have an update.

**Comment by Luth-RoR** [comment] 2016-07-18 23:38
Weapon DPS and attack speed seem to correlate often on weapons designed by mythic.
The 24.1 DPS weapon seems to be better, but the 22.4 DPS weapon should actually hits harder after 3.2 seconds. The first weapon hits more often though.
Closing this, as i guess it is now 
a) changed
or
b) considered working as intended

**Closed by Luth-RoR** 2016-07-18 23:38 UTC
Labels: Database, Item
