### ISSUE TITLE
Joining scenario teleported me to IC and UI changed as if i was logged out

### ISSUE THREAD

**Issue by andrasragany** [WarEmu/WarBugs#13908] opened 2019-04-18 05:55 UTC
![loggedoutui](https://user-images.githubusercontent.com/39407087/56339609-381b6000-61af-11e9-9fe2-2c26384428f4.png)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment] 2019-04-18 06:00
Duplicate of #11224

**Closed by sioding** 2019-04-18 06:00 UTC
