### ISSUE TITLE
incomming crit bug! OMG

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#19038] opened 2021-05-23 12:35 UTC
im WE and take full 1st tree (have trigger poison -80 initiative)! mara have 24,8 inc crit chance! im debuff him on iniativw 80! = stacked my 22crit chance+inc mara 24,8+(-80 init on me )=52.2! inc crit chance to mara from all players on 10 sec! OMG
bug=any debuff -initiative(have only 80init)+(chance crit player's stacked!)=incoming crit chance damage for all players attack dis mara! omg
![image](https://user-images.githubusercontent.com/45288988/119260206-37095800-bbeb-11eb-84fa-2464a2bdbeeb.png)
![image](https://user-images.githubusercontent.com/45288988/119260235-52746300-bbeb-11eb-81f1-69b34fdb41ec.png)
![image](https://user-images.githubusercontent.com/45288988/119260645-3376d080-bbed-11eb-8f75-3c10842e9a91.png)

**Comment by Rydiak** [comment] 2021-05-24 06:00
That Mara had nearly base Initiative.  Initiative is *very* important for reducing chance to be crit.  As your Initiative nears 0, your chance to be crit nears 100%.  This is not a bug, but the formula that RoR uses.

Please familiarize yourself with this interaction by using my Chance to be Crit calculator found here:  https://docs.google.com/spreadsheets/d/1PkSCa8VwIv9HhY2cpRSvIyUDS7r43aLl1s0Nax1XQV4/edit#gid=0

**Comment by xpander69** [comment] 2021-05-27 10:08
looks like not a bug.
feel free to comment if you think it is still a bug.
closing for now

**Closed by xpander69** 2021-05-27 10:08 UTC
