### ISSUE TITLE
Reikland Factory - Order Spawn Point - To the right of the dock, players get stuck

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#11594] opened 2018-04-13 05:42 UTC
When you load into Reikland Factory on Order, to the right of the dock, if you fall into the water you will get stuck and have to sit through the whole SC due to being stuck.

Put a rock to the right of the dock in the water area to avoid players getting stuck on the side of the dock in the water.

**Comment by sioding** [comment] 2018-04-13 05:52
Duplicate of #9520

**Closed by sioding** 2018-04-13 05:52 UTC
