### ISSUE TITLE
KotbS-Aura's bugged after Scenario if you don't turn em off before you leave the scenario.

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#15903] opened 2020-03-06 21:36 UTC
I was playing some scenarios on my 30+ KotbS today, because i wanted to push him to 40 on x2-Event. Unfortunately, after my first Scenario, my Auras were buggy and i wasn't able to activate or deactivate any of them. I'm not sure if it's a bolster-problem and if it affects lvl 40 characters aswell, but it is very annoying. I've asked around in advice chat and some guy told me that it happens to him aswell. He told me to deactivate all auras before leaving the scenario, only that prevents the bug. 

If you don't deactivate em, you're unable to activate/reactivate em. I would love to see a fix, because i love playing that class, it's just unplayable in a group with this bug.

cheers for all the work, appreciate it.

Puru

**Comment by raptrr** [comment] 2020-03-07 08:50
Duplicate of: https://github.com/WarEmu/WarBugs/issues/15903

**Closed by raptrr** 2020-03-07 08:50 UTC
Labels: Ability
