### ISSUE TITLE
Auction house window is not opening .

### ISSUE THREAD

**Issue by Enryle** [WarEmu/WarBugs#17940] opened 2020-10-14 18:22 UTC
Hi ,

nothing happen when I click on Auction House Npc , the window is not showing up.
I tried to run the updater but nothing happen
I tried the fix option in the launcher but nothing happen

**Comment by Kaelang** [comment] 2020-10-14 20:31
Have you updated / sorted your addons?

**Comment by Enryle** [comment] 2020-10-15 10:05
addons are updated
I also tried to desactivate them all
I tried a to open AH without any addon an the game basic UI but the window still don't pop up

**Comment by MaxHayman** [comment] 2020-10-19 00:34
This is caused by the folder permissions. Try moving the game to "C:\Games\Return of Reckoning" and starting and closing the launcher a couple of times.

**Comment by Enryle** [comment] 2020-10-19 17:47
Thank you it worked  ;)

**Closed** 2020-10-19 17:47 UTC
Labels: 2 Week Ultimatum, Confirmation Request
