### ISSUE TITLE
Essence Lash Bugged

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#14337] opened 2019-06-03 21:10 UTC
Today when playing in warband I was using Essence Lash on DoK and it hit for ridiculus high damage numbers for some strange reason. https://i.imgur.com/9rxPvno.png

My DoK is specced for healing and not dps, so why it hit for that much must be some kind of bug as it should not hit for that much.

Also, when I logged out and back in again the numbers seem to be back to normal.

**Comment by sioding** [comment] 2019-06-04 05:30
Duplicate of #14334

**Closed by sioding** 2019-06-04 05:30 UTC
