### ISSUE TITLE
Grimbeard Station friendly npc attack

### ISSUE THREAD

**Issue by monster1305** [WarEmu/WarBugs#13661] opened 2019-03-17 07:57 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

In Grimbeard Station PQ, (you play as order). Friendly npc's tend to attack the player for some reason. You can't hit them but they can hit you to death.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
![Ripguts_011](https://user-images.githubusercontent.com/48641801/54487136-158de280-48a3-11e9-85d6-9cf125ca0324.jpg)
![Ripguts_012](https://user-images.githubusercontent.com/48641801/54487137-158de280-48a3-11e9-95ed-b274cfc84da4.jpg)
![Ripguts_013](https://user-images.githubusercontent.com/48641801/54487138-158de280-48a3-11e9-8d18-70ddb1962a8b.jpg)

**Comment by sioding** [comment] 2019-03-17 08:28
Duplicate of #12271

**Closed by sioding** 2019-03-17 08:28 UTC
