### ISSUE TITLE
Funnel Essence - PVE Broken

### ISSUE THREAD

**Issue by Carnifex-Xiii** [WarEmu/WarBugs#13853] opened 2019-04-12 00:10 UTC
**Expected behavior and actual behavior:**
Funnel Essence should be able to heal myself or friendlies.
Funnel Essence is broken in chapter 20 Empire because it would NOT heal friendlies.
It does work in scenarios.

**Comment by sioding** [comment] 2019-04-12 04:55
Duplicate of #11846

**Closed by sioding** 2019-04-12 04:55 UTC
