### ISSUE TITLE
"Ghosting bug" in scenario.

### ISSUE THREAD

**Issue by finnir** [WarEmu/WarBugs#4116] opened 2016-01-29 18:16 UTC
I recently came across a really strange, and rather game breaking bug, although I don't understand what caused it. Here are the details: In a scenario (Gates of Ekrund) what seemed to be a lag spike occurred (no response to typing of chat etc - inclined to say was server side as my internet continued to work throughout or a bug itself) . This caused period of the scenario being empty (despite populated), players were noted as "distant", flags were unable to be captured (animation occurred however indicator remained neutral). After 1-2 minutes the scenario resumed, however I continued to be mounted and was unable to use any spells at all. Additionally, I was invisible to all players (like a ghost)! Despite this I was still able to gain renown, exp from other player deaths around me as well as kill quests recognising the player deaths. Once the scenario ended, however I was then able to interact with the game environment and use my player skills.

**Comment by noisestorm** [comment] 2016-01-29 19:47
Packet corruption that was able to resync again without throwing you off may cause the strangest of things. But the issue is already known so i'll close it

**Closed by noisestorm** 2016-01-29 19:47 UTC
