### ISSUE TITLE
Skaven quest missing/cannot pick it up

### ISSUE THREAD

**Issue by Phatzas** [WarEmu/WarBugs#9776] opened 2017-06-06 20:43 UTC
My main character Phatal, Black Orc of Destruction cannot get the skaven quest from the Herald/Chosen NPC. I cannot recall if I had picked it up and dropped it at some point or not but when I go to get it he has no quests for me and it is not in my quest ToK. I have tried sharing the quest from another player and it will not share either.

**Comment by Luth-RoR** [comment] 2017-06-07 07:47
You get only the starting quest from these NPCs. You probably did one or two steps and need to retake it from a different NPC.

**Comment by Gnashspike** [comment] 2017-06-12 20:53
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Phatzas [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBDIATPQCYAYBZIBXAMIYZ2QVLYASIKA5QFIKGEQETCY2MGEUTNLKYENMGACVVEDAADZYOIVMKEAVENT4ALMCDAQY34E5RKSVR67DCZE4KMEDQAA2QJJIAFZADYYBSMASWAITAGVQ2MZNAHWQC3IAXKIC3IRZKIVCRBIIAEAACA===@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 13:53:21 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp s6si2383642ywj.293 - gsmtp:
    retry timeout exceeded

**Comment by sioding** [comment] 2017-10-14 20:56
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)

**Closed by sioding** 2017-10-14 20:56 UTC
