### ISSUE TITLE
Resurrecting a player makes them disappear

### ISSUE THREAD

**Issue by Zeviun** [WarEmu/WarBugs#5087] opened 2016-03-28 19:33 UTC
When resurrecting a player they disappear completely from view (the character itself) and according to heal frame they are distant. After a while they do reappear. I'm not sure how many are affected by this; no one I spoke to seemed to recognized the issue. This has happened to me several times now for few days and seems to happen more often than not; to the point that I'd rather no longer resurrect anyone unless I really need to.  I'll be able to post a video of this later.

**Comment by Zeviun** [comment] 2016-03-28 21:30
Here is a vid: https://www.youtube.com/watch?v=3ZSPig1R6iE&feature=youtu.be

**Comment by kaey** [comment] 2016-03-28 21:40
I confirm this.
I think it only happens in scenarios and a bit at random, but should be easily reproducible.
Don't have a vid though, sorry.

**Comment by Lileldys** [comment] 2016-03-28 22:38
Happens in ORvR too

**Comment by Torquemadra** [comment] 2016-03-29 09:24
Happened to me once, unable to replicate.

**Comment by Chummi** [comment] 2016-03-31 11:14
happens to us everywhere - especially in battle for praag, should try it there. almost every play who got rezzed there is invisible for the rest of his group. can be fixed by swapping groups.

twitch.tv/stenchypow - somewhere in the replays of BoP you can see it, anyone of us dies usually to guards there. cant look for a timestance atm since i am at work :P

**Comment by muellerpeter** [comment] 2016-04-07 15:27
seems to be happening more frequently lately.  I've stopped taking res.

**Comment by Styrkarr** [comment] 2016-04-07 20:41
This issue is high priority. It completly break the team game when it occurs.

**Comment by ozarmidrashim** [comment] 2016-07-01 11:33
Dealt with a while back (fix for F_REQUEST_INIT_PLAYER)

**Closed by ozarmidrashim** 2016-07-01 11:33 UTC
Labels: Ability, Major
