### ISSUE TITLE
Squig Herder Melee Disarm Bug

### ISSUE THREAD

**Issue by Monzsta** [WarEmu/WarBugs#18438] opened 2021-02-01 19:41 UTC
Hi DEVs,

i think i found a new bug: The Disarm skill from MSH does not work anymore since arround 4 weeks now. i tested it in ORVR, SCs, PVE Mobs and Duels. It does no damage or disarms, just nothing only the animation triggers and the cooldown starts.

Maybe you can check that. 
greetings Monzta/Toghall

Thanks to you all for keeping the game alive, love it ;)

**Comment by Zydna** [comment] 2021-02-07 16:01
![image](https://user-images.githubusercontent.com/75143494/107152040-15e76900-6966-11eb-8ec8-7dbd9daa9338.png)

**Comment by lilimx** [comment] 2021-07-07 07:16
Hey,

thank you for your ticket.
I've tried to reproduce your bug but it works as intended.
If the issue still persists, please send more information.

**Comment by lilimx** [comment] 2021-07-20 19:09
Hey,

im closing this ticket now due to no feedback.

**Closed** 2021-07-20 19:32 UTC
