### ISSUE TITLE
Gold bag never came to my mailbox

### ISSUE THREAD

**Issue by Drunkenness** [WarEmu/WarBugs#10635] opened 2017-10-19 17:03 UTC
Hi, sorry to bother you with that but i won a gold bag from Kadrin Valley draw lock this morning (approximatly 9.45 am french hour) but it was never sent in my mailbox.
I think i could have an issue with my account because it's the 2nd time it happened for a total of 4 bags won.
I believe i play in bad hours because the Order is like stomped everytime and the only purpose to continue ORVR is trying to scratch a bag, but when it happened it is send 50% of the time wich is very frustrating.
My character name is Kadrak, i was the second in the participating at kadrin valley, i won the 1st bag with a score of 1410+.
Can you please check all the info and get me a refund? And if it's not possible can you please fix my mailbox? I dont think i'll continue to play if 50% of my rewards keeps vanishing.
Thx for your work and carry on !

**Comment by sioding** [comment] 2017-10-19 17:17
Duplicate of #10279 
Sorry to hear that - we are currently working on a new bag system. Hopefully it will be available soon™.
You won´t get a refund for this case. Sorry again.

**Closed by sioding** 2017-10-19 17:17 UTC
