### ISSUE TITLE
Salvaging dont working in "Runebough Branchwraith"

### ISSUE THREAD

**Issue by ursvamp** [WarEmu/WarBugs#4113] opened 2016-01-29 13:30 UTC
Runebough Branchwraith  cord (2,600 18,100) in saphery isnt working!

**Comment by genisaurus** [comment] 2016-01-29 18:11
Duplicate of https://github.com/WarEmu/WarBugs/issues/4046, closing

**Closed by genisaurus** 2016-01-29 18:11 UTC
Labels: Database
