### ISSUE TITLE
BLOODLORD ANDSPLATE NOT COUNTED INTO THE FULL SET

### ISSUE THREAD

**Issue by faktorfaktor** [WarEmu/WarBugs#14944] opened 2019-09-19 17:56 UTC
**Expected behavior and actual behavior:**
im wearing the full set i should get all the bonuses

**Steps to reproduce the problem:**
equip the full set and u dont get all the bonuses

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.imgur.com/WKEH1Ey.jpg

**Comment by sioding** [comment] 2019-09-19 18:04
Duplicate of #14917

**Closed by sioding** 2019-09-19 18:04 UTC
