### ISSUE TITLE
[Salvaging] Critical Failure

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1329] opened 2015-09-07 07:15 UTC
4-5 in a row on orange, 2 on yellow, not too much?

**Comment by Titoos** [comment] 2015-09-07 07:50
Its RNG so its never too much. 
But if Im correct on official even failure gave you chance to levelup. Which is good in terms of learning from mistakes.

**Comment by Radiantknight** [comment] 2015-09-07 12:33
Well, go for green to be safe, cheezus. Not a bug anyway

**Comment by magter3001** [comment] 2015-09-07 21:15
Titoos is correct, on Live you would level up even if you fail on orange and yellow salvageable items. Also RvR gear bought from vendors could be salvaged on Live.

**Comment by Evildoor** [comment] 2015-09-18 07:21
4-5 failures in a row is well within usual RNG unfairness. Difference with live implementation is another problem, and i'm sure devs are aware of it. Therefore, closing this.

**Closed by Evildoor** 2015-09-18 07:21 UTC
