### ISSUE TITLE
epic quest t3 elf bug

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12585] opened 2018-11-14 15:37 UTC
Expected behavior:

epic quest "control" in avelorn chapter 10
first step kill 10 bloody sun treechoppa

actual behavior:

don t work don t get the kill

Steps to reproduce the problem:

try epic quest t3 avelorn chapter 10 quest name: control

Screenshots/Videos or archive.org evidences:

**Comment by Oceanman69** [comment] 2018-11-14 15:43
we were grouped with a rune priest after degrouping we can have the kills

quest bug in a party

**Comment by Oceanman69** [comment] 2018-11-14 16:06
step two of epic quest we regroup slayer with rune priest
kill 5 raven blood boiler and 5 terrorguard
rune priest get the kills but not the slayer had to degroup again
tryed a deconnection reconection regroup still not working

PS: we did epic quest chain t3 empire start chap 10 "cleansing the empire" without any problems

**Comment by Lheana** [comment] 2020-04-04 13:36
Duplicate of #12470

**Closed by Lheana** 2020-04-04 13:36 UTC
