### ISSUE TITLE
cant rejoin fort after disco

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13528] opened 2019-03-02 22:32 UTC
Crash to desktop in Fort --> relog in  --> IC --> portal wont let me in again

so cant rejoin fort

**Comment by xaraxdestr** [comment] 2019-03-02 22:33
cant join portal solo nor in the orginal WB i had.

now i get the message "Your reservation for the fortress has expired"

**Comment by sioding** [comment] 2019-03-04 06:42
Duplicate of #13536

**Closed by sioding** 2019-03-04 06:42 UTC
Labels: Fortresses, Sourcecode
