### ISSUE TITLE
[Item] Battlebrew Backpack's explosive stout ability does not require LoS

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#14241] opened 2019-05-27 13:10 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

It can be thrown through any terrain, which is HUGE for melee characters who only have this and maybe one aoe group buff to build combat / maintain their morales

**Steps to reproduce the problem:**

Use battlebrew backpack on thing out of LoS(line of sight) and see

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/zGRz4ODROL0?t=14

**Comment by sioding** [comment] 2019-05-28 06:55
Duplicate of #11483

**Closed by sioding** 2019-05-28 06:55 UTC
