### ISSUE TITLE
Can't valid quest bo

### ISSUE THREAD

**Issue by anazarelle** [WarEmu/WarBugs#19011] opened 2021-05-20 18:38 UTC
Hello,
When i go on bo to valid the quest it's not work , the bo is Icecrossing in KV.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Spasiba_004](https://user-images.githubusercontent.com/44342201/119031398-56b23d80-b9ab-11eb-8b6c-3c1228338b2e.jpg)

**Comment by Lheana** [comment] 2021-05-23 11:41
Duplicate of #18591

**Closed by Lheana** 2021-05-23 11:41 UTC
