### ISSUE TITLE
[PETS WL SH] pets can not be sneered

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1740] opened 2015-10-27 06:00 UTC

**Comment by ozarmidrashim** [comment] 2015-10-27 09:37
If this is "snared", they can be snared, same as other NPCs. They're just faster than players are.

**Comment by Nfkillz** [comment] 2015-10-27 11:56
well made a test. Yes you are right. But why pets have 125 speed instead 100?

**Comment by ozarmidrashim** [comment] 2015-10-27 12:07
To compensate for pathing issues.

**Comment by Evildoor** [comment] 2015-10-29 11:33
Closing as not a bug.

**Closed by Evildoor** 2015-10-29 11:33 UTC
Labels: Ability
