### ISSUE TITLE
Pillaging

### ISSUE THREAD

**Issue by WildRuss** [WarEmu/WarBugs#13728] opened 2019-03-26 10:51 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by WildRuss** [comment] 2019-03-26 10:51
Cant click chests i have got 3 but not registering so seems bugged

**Comment by Lheana** [comment] 2019-03-26 11:19
Duplicate of #13711

**Closed by Lheana** 2019-03-26 11:19 UTC
Labels: Database, Quests

**Comment by Gwendis** [comment] 2019-03-26 21:04
Can confirm it, after chests reset, you can click on it, but you dont get the registed 3/3
