### ISSUE TITLE
Magus defensive genesis jewelry set is missing!  Can only use one piece.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#11011] opened 2017-12-17 04:35 UTC
I did a query for Magus and defensive genesis.  I don't see a bug.   I can buy two different sets for most of my toons but only see one piece for Magus for defensive set.  

The set is the undying genesis set.  I expect the magus to have a defensive set like other classes.

To reproduce - try to buy a complete undying defensive genesis set in IC.

Expected behavior and actual behavior:

![image](https://user-images.githubusercontent.com/18320036/34076587-b9c05f1e-e2b9-11e7-897c-ea952c844d59.png)

**Comment by timoteiz** [comment] 2017-12-17 07:53
Enginier is missing from that list as well, please have a look

**Comment by sioding** [comment] 2017-12-17 15:32
Duplicate of #10990

**Closed by sioding** 2017-12-17 15:32 UTC
Labels: Database, Item
