### ISSUE TITLE
KotBS Stay Focused Aura turning off

### ISSUE THREAD

**Issue by Tsypher** [WarEmu/WarBugs#16431] opened 2020-04-19 11:15 UTC
**Expected behavior and actual behavior:**
When in a party with another KotBS, both using the stay focused tactic, if one knight has the buff on and the other tank turns it on, it should still be on, acting similarly to all other auras. Stay Focused specifically turns itself off roughly a second after its turned on if you have the buff from another tank. If you turn it on and go near your other knight in the party, one of the buffs are turned off.
This means that if youre near another tank by aura activation and then separate, one of you has to spend a GCD turning it on again.

**Steps to reproduce the problem:**
Stand near a party member knight who has the buff. Turn yours on. Watch it get removed, unlike all other auras. Other auras are duplicated, but not stacked. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-04-19 15:40
Duplicate of https://github.com/WarEmu/WarBugs/issues/16085.

**Closed by Kaelang** 2020-04-19 15:40 UTC
Labels: Ability
