### ISSUE TITLE
[Quest] Breaking and Entering (Talabecland, destro) Interactable quest object usable multiple times

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13033] opened 2019-01-04 08:27 UTC
"Barrel of Cheap Cider" and "Basket of Fish" an be clicked multiple times to fulfill the objectives with only one item instead of having to find multiple of them.

![breaking and entering](https://user-images.githubusercontent.com/30193675/50679216-de799600-1002-11e9-837c-ec96dd0b4f67.jpg)

**Comment by Lheana** [comment] 2019-01-10 18:03
I could not reproduce this issue, I could only interact once with the GOs.

**Comment by Moragor** [comment] 2019-01-10 18:50
It seems this problem appears randomly. https://github.com/WarEmu/WarBugs/issues/13100 is basically about the same bug and I remember being able to use the kindlings repeatedly  with one char and only once with another.

**Comment by Lheana** [comment] 2019-01-10 19:35
Yes unconstant issue that can not be fixed by DBs

**Comment by Lheana** [comment] 2019-11-02 16:40
Fixed with patch of 02/11/2019.

**Closed by Lheana** 2019-11-02 16:40 UTC
Labels: Fix Pending, Quests, Sourcecode
