### ISSUE TITLE
Water barrier skip (Fell landing / shining way)

### ISSUE THREAD

**Issue by Fiscko** [WarEmu/WarBugs#13584] opened 2019-03-09 20:56 UTC
Hi,

Barrier can be skip by swimming across the barrier until reach the limit of the map ( the gods are Angry )

At this moment barrier disappear and we can fast return to the fortress zone before dying.

Works to north caledor zone and south eitaine zone.

**Screenshots/Videos or archive.org evidences:**

![Fiscko_002](https://user-images.githubusercontent.com/48393391/54077228-f3e69700-42b5-11e9-875d-caa3bf128b39.jpg)
![Fiscko_001](https://user-images.githubusercontent.com/48393391/54077233-fc3ed200-42b5-11e9-90fd-7593466784ba.jpg)
![Fiscko_003](https://user-images.githubusercontent.com/48393391/54077234-fea12c00-42b5-11e9-9e59-d2d7d5d68e15.jpg)
![Fiscko_004](https://user-images.githubusercontent.com/48393391/54077235-01038600-42b6-11e9-8b11-67028c36a9ef.jpg)

**Comment by sioding** [comment] 2019-03-10 06:11
Duplicate of #13567

**Closed by sioding** 2019-03-10 06:11 UTC
