### ISSUE TITLE
Can't Q for scenarios

### ISSUE THREAD

**Issue by BuzzShaman** [WarEmu/WarBugs#18718] opened 2021-03-28 00:56 UTC
Cant seem to Q for scens on any character.   have had the issue for about a week after being away from the game for 6+ months.  cant even right click the scenario button to check/uncheck particular scens to Q for.   have tried /reloadui, reparing the game through the launcher, disabling all addons, and even totally reinstalling the game.    some help with how to fix this would be wonderful.

don't have a screenshot as I'm not sure what it could show....

**Comment by Symbelmyne** [comment] 2021-03-28 10:20
can you check in layout editor is any element of UI overlaping SC queue button? Do you share same UI profile for all characters?

**Comment by BuzzShaman** [comment] 2021-03-30 02:08
yeah no overlap issues in the UI.   QQer addon, back when I had it installed before wiping all addons and re-installing, didn't work either.   Am currently downloading to reinstall yet again after scouring my PC for any leftover config files related to ROR not in the normal directory.

**Comment by Numeriku** [comment] 2021-03-30 08:05
I can confirm that i have the same issue as buzzshaman

**Comment by Numeriku** [comment] 2021-03-30 09:52
@BuzzShaman , found a fix for this, not sure why it happened, but i downloaded the torrent for the game again, make sure all the files are not read only and update ror again, after fully updated, i logged in and scenarios are fixed again.

**Comment by BuzzShaman** [comment] 2021-04-02 20:51
So after redownload ing and reinstalling the game a bunch of times, can now actually Q.   Issue now is the game crashes the moment I enter a scen.

**Comment by BuzzShaman** [comment] 2021-04-02 21:25
or, I should say, crashes the moment the scenario zone loads

**Comment by lilimx** [comment] 2021-05-29 13:11
Hey,

I'll close this because it's an install issue.

**Closed by lilimx** 2021-05-29 13:11 UTC
