### ISSUE TITLE
Unbalanced ranked match - finished by order victorious

### ISSUE THREAD

**Issue by DmitriyMaksimovich** [WarEmu/WarBugs#16550] opened 2020-04-29 14:24 UTC
![Caecilius_082](https://user-images.githubusercontent.com/46728779/80607454-30d39700-8a3e-11ea-86ab-9d5ca268e1a0.jpg)

Nobody leave, we were 4 against 6, the game started, the order killed the player and won.

**Comment by DmitriyMaksimovich** [comment] 2020-04-29 14:27
In statistics, the game was hit, but mmr did not fall

**Comment by Kaelang** [comment] 2020-04-29 14:30
The game was restarted based on the imbalance in players. This is working as intended. 

The check isn't every second, so if this happens and you're on the losing side - make sure not to wait for the reset. 

Closing.

**Closed by Kaelang** 2020-04-29 14:30 UTC
