### ISSUE TITLE
Backpack overflow item but backpack isn't full

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12357] opened 2018-09-23 06:09 UTC
I can't delete the item. So I got the message backpack is full but in fact I got room in backpack
![thorbolt_457](https://user-images.githubusercontent.com/16274785/45924751-d42a0500-bf07-11e8-82cd-a85bbf51625a.jpg)

Deleting, creating/switching to new UI layer, relogging/restarting don't fix the issue.

**Comment by Rokatord** [comment] 2018-09-23 08:14
Lay it in youre bank :-D that works

**Comment by sioding** [comment] 2018-09-23 12:12
Hey - good workaround - but not the way it should work.

**Comment by sioding** [comment] 2018-09-23 12:13
Duplicate of #11937 
I put this togeter with another backpack overflow report.

**Closed by sioding** 2018-09-23 12:13 UTC

**Comment by thorbolt80** [comment] 2018-10-22 04:15
I got this problem when I was inside Gunbad as  #11937
