### ISSUE TITLE
Bloodlord Claymore issue

### ISSUE THREAD

**Issue by dadkkak** [WarEmu/WarBugs#14513] opened 2019-07-02 23:08 UTC
Hey, just got the first inf weapon - Bloodlord Claymore - on Kotbs, but I can't equip it. I got full sentinel and can equip Bloodlord armor, but i'm missing gloves for the full ward. Is that a bug or I should be able to equip Claymore only when I complete the rest of BL armor? On WH I could get full BL before the 2 weaps, so I didn't have the chance to test it. Thanks

**Comment by sioding** [comment] 2019-07-03 06:35
Duplicate of #14496

**Closed by sioding** 2019-07-03 06:35 UTC
