### ISSUE TITLE
Reaping Field PQ stage 2 issue

### ISSUE THREAD

**Issue by Melisandrea** [WarEmu/WarBugs#9766] opened 2017-06-05 12:21 UTC
During stage II Reaping Field PQ (Empire Ch 21) Bloodhowlers Champions (lvl 33-34) getting aggro and fast killed from 4 Bloodletters (lvl 41 normal mob). Those autokills arent counted towards progress and players can have problem with finishing this stage in time (i finished it in last possible sec of time).

**Comment by Razielhell** [comment] 2017-06-05 14:32
Nice! Really good report!

**Comment by grunbag** [comment] 2017-06-07 13:48
Fixed on next patch

**Comment by Gnashspike** [comment] 2017-06-11 12:33
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Melisandrea [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UA3ICGEA4CGGBJMZQATXTMOBRE43BHGGEEBBRK5RD6YYQXC7SARKIUMJ5YGE2MFKQBR4CBJRBHYXBBFUCHAYBSYBGGOLDSEQ6BSMCJSEU2IABKIJREAJZAFYYCSMBCOAQTAKTQ4U4UAHXAC3QAXOISPBGIYJSBAEQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 05:33:22 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp c188si1543567ywd.229 - gsmtp:
    retry timeout exceeded

**Closed** 2017-06-17 08:12 UTC
Labels: Database, Fix Pending, NPC, Public Quests
