### ISSUE TITLE
Mount bug in Dragons Bane and Howling Gorge

### ISSUE THREAD

**Issue by Phloam** [WarEmu/WarBugs#16457] opened 2020-04-21 21:57 UTC
Hi, we found a mount related bug in Dragon's Bane and Howling Gorge Scenario.
In Dragon's Bane one can use the Wyvern mount to run with Dragon Beacon to flags.
In Howling Gorge the Wyvern mount can be used after picking up the bomb but there is no mount animation. It just looks like the toon runs with 60% speed. 

[https://imgshare.io/images/2020/04/21/Phloam_220.jpg](url)

Best regards
Officer Phloam of CYA

**Comment by Kaelang** [comment] 2020-04-21 22:01
Thanks for the report - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16427.

**Closed by Kaelang** 2020-04-21 22:01 UTC
