### ISSUE TITLE
Dok face bugged in combat [visual]

### ISSUE THREAD

**Issue by Diskete** [WarEmu/WarBugs#13835] opened 2019-04-10 11:46 UTC
Hello, I noticed that when entering combat, the face of the disciple of khaine this bugged, instead of the angry face that I had, appears one that seems to have mental retardation.

![Bayoneta_013](https://user-images.githubusercontent.com/19426036/55876034-f3803b00-5b96-11e9-8253-3f9165c4dc62.jpg)
![Bayoneta_014](https://user-images.githubusercontent.com/19426036/55876035-f3803b00-5b96-11e9-94b6-7fafe2ac8978.jpg)

**Comment by sioding** [comment] 2019-04-10 11:47
Duplicate of #12942

**Closed by sioding** 2019-04-10 11:47 UTC
