### ISSUE TITLE
Аttacked by friendly NPC Murdogh Shieldbearer/Thunderer

### ISSUE THREAD

**Issue by ner3ul** [WarEmu/WarBugs#13586] opened 2019-03-10 00:45 UTC
**Expected behavior and actual behavior:**
Actual - Murdogh Shieldbearer/Thunderer sometimes attack player if he fight near them.
Expected - they must be peacefull

**Steps to reproduce the problem:**
Fight near that NPC

**Screenshots/Videos or archive.org evidences:**
![Ugend_013](https://user-images.githubusercontent.com/13261124/54079057-83f00500-42e5-11e9-89bf-eb705387262e.jpg)
![Ugend_014](https://user-images.githubusercontent.com/13261124/54079061-86525f00-42e5-11e9-8dcc-3e750a7ac990.jpg)
![image](https://user-images.githubusercontent.com/13261124/54079087-26a88380-42e6-11e9-9f62-b459c6b64e3f.png)
![image](https://user-images.githubusercontent.com/13261124/54079106-c36b2100-42e6-11e9-9dac-c08ad3c9b949.png)

**Comment by Kabucoror** [comment] 2019-03-10 14:38
Seems nothing DB related

**Comment by Lheana** [comment] 2020-02-22 16:19
Duplicate of #9880

**Closed by Lheana** 2020-02-22 16:19 UTC
Labels: NPC, Sourcecode
