### ISSUE TITLE
No medals with locking zone destro side

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#1779] opened 2015-10-31 17:07 UTC
Like title says no medals u get on locking a zone

**Comment by Calarian** [comment] 2015-11-02 19:46
Was the Zone locked multiple times within a period? this would cause not getting a medallion.

**Comment by Areanda** [comment] 2015-11-03 11:55
Multiple time. ... no ofcourse not u lock a zone and its closed 30 min. But doesnt matter wich zone I dont get medals for a lock

**Comment by Calarian** [comment] 2015-11-03 20:05
Well i meant after it unlocks you can then re-lock it, if it was locked many times prior you wont get one

**Comment by Areanda** [comment] 2015-11-04 06:22
no i never get 1 even when i lock it after 30 min wating...to let zone re-open then cap the zone i still dont get the medals. also sometimes it takes 2 hours to cap a zone when there big fights and still wont get it when we lock those.

**Comment by Evildoor** [comment] 2015-11-05 10:34
I suspect that certain events following the introduction of Devastator set lead to removal of medallions from lock rewards, but i'm not a RVR player so i'm not sure. Anyone has clear info on this point? Devs?

**Comment by Renork** [comment] 2015-11-07 15:15
I tested this for you and its working just fine. If you relock the zone before allowing it to "reset" you do not get medallions. Not once did I not receive medallions on my toon, but I did wait for the zone to reset.

**Comment by Areanda** [comment] 2015-11-07 15:19
Would love to know how you did cause ive locked so many zones cant  even  count em never got any but so u say zone reset thats when u get the message zone open right. ..

**Comment by Renork** [comment] 2015-11-07 15:23
Easy, once you see the top right bar go back to "neutral" = IE not favoring destro or order, then you know the zone reset. I have full deci set on my wh that I started yesterday.

**Comment by Areanda** [comment] 2015-11-07 19:00
Funny u say in ya wh tried wot u said gained nothing on my choppa but thanks to for help ill wait for t3

**Comment by Areanda** [comment] 2015-11-08 12:04
Tried it again this time with a sorc not my choppa we locked elf this morning again not single medal.. funny to read for order it works but not destro side. .

**Comment by Evildoor** [comment] 2015-11-08 15:13
Something tells me that one of you, gentlemen, talks about T1 ("Full deci"), and other one about T2.

**Comment by Areanda** [comment] 2015-11-08 15:16
I talk about T2 buddy

**Comment by Evildoor** [comment] 2015-11-11 14:20
@Areanda, i know you do. But @Renork says that he has "Full deci"(mator), which is T1 set, IIRC. Therefore, if he really talks about T1 locks, i see a possible explanation to current situation: T1 locks work as before and reward medallions, so you can get decimator set. T2 locks reward no medallions, and this is not a bug but balance decision to prevent people from zerging empty keeps to get obliterator/devastator.

**Comment by Renork** [comment] 2015-11-11 18:59
Right.. I guess you can close this :>  T1 zone locks are working for both sides. The OP didn't know that it is intended for us not to get scout medallions for locking zones in t2, but now he knows.

**Closed** 2015-11-13 10:53 UTC
Labels: Confirmation Request, ORvR
