### ISSUE TITLE
Chaos Chapter 13 PQ Guts Out - Wrong participation. 

### ISSUE THREAD

**Issue by Thienri** [WarEmu/WarBugs#16848] opened 2020-05-16 13:34 UTC
So i was doing the Broken Men, Broken Blades cheeve for the cloak skin, i was farming the Kulian bone warriors/archers/mages and noticed i was getting influence from them. There was no discernable pattern to which particular mobs gave influence.

On the way i had to get past some densely packed ogre mobs around coords 23.35 and killed a few. A brief while later i had a pop saying I'd won a major lootbag in  the Chaos Chapter 13 PQ Guts Out. The only other player, a DoK named Akrecia won a green)

**Steps to reproduce the problem:**

Go to coords 23:35 and kill Ogres and Gnoblers. I used only basic engineer skills and no consumables or mission specific items like the xplodie potion.

![IMG_20200516_162332](https://user-images.githubusercontent.com/62931030/82121032-ddc64780-9792-11ea-882e-ceee5c087adb.jpg)
![IMG_20200516_162340](https://user-images.githubusercontent.com/62931030/82121034-e028a180-9792-11ea-81eb-b55eb5ab8257.jpg)

Unfortunately my pc borked the screenshots and i got a blanked out screen. I took these on my phone. The purple bag is currently sitting in my mailbox untouched (character is Gotzak).

**Comment by Lheana** [comment] 2020-07-02 11:23
Duplicate of #10445

**Closed by Lheana** 2020-07-02 11:23 UTC
Labels: Public Quests, Sourcecode
