### ISSUE TITLE
Sigmar's Shield

### ISSUE THREAD

**Issue by eherenreich** [WarEmu/WarBugs#12709] opened 2018-11-24 21:36 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

The expected behavior according to the info skill tap is 15 pts. pr. second. over a course of 7 seconds.

Actual behavior is that Its drains 15 pts. pr. second and also 10 pts. pr. hit.

Steps to reproduce the problem:

Apply the skill take damage and watch it drain, I used a standard mob from praag area, mob did 3 hits on me during the 7 seconds it's active.

I was at 250 pts. so start with and ended up with spending 105 pts. from the drain pr. second and 30 points from the 3 hits and my end result was I had 115 pts. left.

Screenshots/Videos or archive.org evidences:

Is this required ? hard to see the RF drain and posting a video requires I install fraps or something (please don't ask me to do that.)

**Comment by sioding** [comment] 2018-11-24 21:39
Duplicate of #12676

**Closed by sioding** 2018-11-24 21:39 UTC
