### ISSUE TITLE
Dismount

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#16592] opened 2020-04-30 12:22 UTC
Different characters dismount after a couple of seconds of riding.

**Comment by Horusaximand** [comment] 2020-04-30 13:05
In happens on steps or stairs in IC (check those between different zones in IC as well as Monolith)

**Comment by Kaelang** [comment] 2020-04-30 13:37
Hardly any information here. I'm not even sure what you're trying to tell me.

Screenshots / Videos etc please.

**Comment by Vayra** [comment] 2020-04-30 19:13
Don't have screenshots on hand, but whenever you cross into or out of the Apex in IC you get dismounted now. All gates leading in to the Apex, and in to the bank/AH areas.

**Comment by Kaelang** [comment] 2020-04-30 19:19
[General]

- You will now be dismounted when going on to objects or areas which do not allow you to be mounted such as inside certian buildings or inside caves/crypts.

This, currently, is intended. Albeit somewhat sensitive. I'll keep this open for two weeks to see if any changes are made, however this isn't necessarily a 'bug'.

**Comment by Vayra** [comment] 2020-04-30 19:23
Into bank/AH area I'll gladly accept is not a bug, but into the Apex area itself is definitely a bug. That's an area you should be able to ride through.

**Comment by Horusaximand** [comment] 2020-04-30 21:02
It happens when ypu climb on ANY ladder in IC as well as when you walk INSIDE the monolith.
![LADDER BUG](https://user-images.githubusercontent.com/20398365/80758804-0aa21a00-8b58-11ea-9d1a-3a54870f3eb5.png)

**Comment by Lheana** [comment] 2020-05-01 13:04
I see no issue in the examples you gave because that was that way on official. You were dismouted when entering or leaving the Apex because there are stairs, and you are not meant to be on mount when on some stairs.

**Comment by Vayra** [comment] 2020-05-01 14:08
You still get dismounted when going through the East/West entrance to Apex, which doe not have stairs. 

And even if it is intended, that is an extremely bad change and should be reverted on common sense grounds if nothing else. It makes it super annoying to move around in IC when you get dismounted moving between rally point and flight master.

**Comment by MaxHayman** [comment] 2020-05-01 14:19
@Vayra The objects which dismounted were what were marked by Mythic.

**Comment by Vayra** [comment] 2020-05-01 14:42
Isn't it possible to change which objects dismount? Because having a small area of dismounting between two other areas you can be mounted is not a good design. And imo is something that warrants the whole feature being put on hold until it can be fixed.

**Comment by Kaelang** [comment] 2020-05-01 14:57
I'm closing this issue as this is an intended change as per the patch notes previously commented.

If you believe this needs to be changed at all, please write a report in the Suggestions and Feedback section as currently this is working as intended.

Cheers.

**Closed by Kaelang** 2020-05-01 14:57 UTC
Labels: 2 Week Ultimatum, Confirmation Request
