### ISSUE TITLE
Public Quest BUG Duraz Dok Nv 39 Kadrin Valley   36K   31K

### ISSUE THREAD

**Issue by tifenn13** [WarEmu/WarBugs#12392] opened 2018-10-02 02:17 UTC
Hi,

The Public quest Duraz Dok at Kadrin valley is missing 2 champions at step 3. You need to kill 10 champion for going to final phase but they have only 8 in this place. We look everywhere and they just missing.. The time of the public quest is also bugued because at step 3 it's write : "5145"  nothing happend with the time remaining..  the number don't change till the time is other ( i think 8min like normal PQ ).

location : 36k  31k

![tifn_001](https://user-images.githubusercontent.com/43477313/46325741-09b2aa80-c5fa-11e8-9a71-110de3eda71d.jpg)

**Comment by sioding** [comment] 2018-10-02 08:34
Duplicate of #12359

**Closed by sioding** 2018-10-02 08:34 UTC
