### ISSUE TITLE
SW Bullseye tactic not working

### ISSUE THREAD

**Issue by Adelmar82** [WarEmu/WarBugs#15050] opened 2019-10-21 04:51 UTC
**Expected behavior and actual behavior:**
Tested Bullseye tactic and it is not granting the 20% crit on paper doll OR getstats. Was working on October 17th, 2019 last I noticed the crit increase. I can post screens if needed as it's easy to test.

**Steps to reproduce the problem:**

Slot Bullseye on SW, auto-attack any mob or (what I did) target dummy in the capital city until Bullseye procs, check .getstats

**Comment by sioding** [comment] 2019-10-21 06:02
Please add your testing screenshots

**Comment by Adelmar82** [comment] 2019-10-21 14:32
Test screenshots:
With Bullseye slotted and showing base stats unbuffed (30% ranged crit)-
![Contract_001](https://user-images.githubusercontent.com/56813277/67214006-a0f4c680-f3e4-11e9-944f-6361f9f9536a.jpg)

Bullseye procced and showing .getstats while under buff-
![Contract_003](https://user-images.githubusercontent.com/56813277/67214467-71928980-f3e5-11e9-99c7-4d8c55035d0b.jpg)

Ranged crit stays at 30% even while under the Bullseye proc

**Comment by arbich123** [comment] 2019-10-21 22:13
Your screenshot shows buff "critical hit rate 20". I don´t really play a SW, but assume you get +20% for melee and ranged crit attacks with tactic. You should actually check how often you crit, to prove your claim

**Comment by Adelmar82** [comment] 2019-10-22 03:05
@arbich123
Yes, it gives crit to both melee and ranged, and in this case it still gives crit to melee but doesn't add it to ranged (at least going by getstats). In the screenshot you'll see that my "ranged crit rate stays at 30% while under the buff, which should not be the case.
As for testing how many crits I get in a given timeframe, I didn't get a chance today to get on and test. The problem has been submitted with evidence, I'm sure that should be enough for the devs especially since it's easy to replicate.

**Comment by wargrimnir** [comment] 2019-10-31 13:25
I don't see any problem with the ability construction. If you're getting the 20% melee crit, you should be getting the 20% ranged crit as well. It's using the universal crit-up instead of a specific type.

**Comment by Adelmar82** [comment] 2019-10-31 22:13
@wargrimnir 
Okay, I wasn't aware that it used a universal buff. It just threw me off when I noticed the paperdoll no longer showing the increase then verifying it with getstats, but I trust your judgement. Thanks for checking regardless!

**Comment by Kaelang** [comment] 2020-05-16 16:53
Closing as working as intended.

**Closed by Kaelang** 2020-05-16 16:53 UTC
Labels: Ability
