### ISSUE TITLE
Unable to claim Kegs End event items

### ISSUE THREAD

**Issue by Regicyde** [WarEmu/WarBugs#12922] opened 2018-12-23 06:29 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Was able to claim Bugman Black Label Recipe but not Party Keg or Keg Tapper.

Steps to reproduce the problem:
Relogged and tried ... no change.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-23 09:12
Duplicate of #12912

**Closed by sioding** 2018-12-23 09:12 UTC
