### ISSUE TITLE
Destro accessing order warcamp in shadowlands

### ISSUE THREAD

**Issue by LordEpee** [WarEmu/WarBugs#19007] opened 2021-05-19 23:41 UTC
**Expected behavior and actual behavior:**
Respawn into a destro warcamp probably in either eataine or IC

**Steps to reproduce the problem:**
In Eataine, go to the orb behind a building in the chp 22 quest by the unique NPC "keeper of the ways", click on the orb to be ported on top of the building, click on the orb on top of the building to be ported to a unique area with a champion NPC. Behind the champion NPC right click the door to open and exit. You will be ported out of bounds within Eataine. Keep running south until you die from being out of bounds. Respawn. You will be put inside the order warcamp in the Shadowlands right by the healer as if you were on order.
![Ililil_001](https://user-images.githubusercontent.com/84482002/118898244-c522cd00-b8d1-11eb-9aad-c8be42355102.jpg)
![Ililil_002](https://user-images.githubusercontent.com/84482002/118898249-c7852700-b8d1-11eb-83bf-40ba2e4186fa.jpg)
![Ililil_003](https://user-images.githubusercontent.com/84482002/118898254-c81dbd80-b8d1-11eb-90fb-914b012e6911.jpg)
![Ililil_004](https://user-images.githubusercontent.com/84482002/118898260-c8b65400-b8d1-11eb-84a7-b684cb12fc48.jpg)
![Ililil_005](https://user-images.githubusercontent.com/84482002/118898263-c94eea80-b8d1-11eb-90a7-0cdb6c522d9f.jpg)
![Ililil_006](https://user-images.githubusercontent.com/84482002/118898267-c9e78100-b8d1-11eb-8db3-b68bf725ceb6.jpg)
![Ililil_007](https://user-images.githubusercontent.com/84482002/118898271-cb18ae00-b8d1-11eb-8771-3eea6c02c854.jpg)
![Ililil_008](https://user-images.githubusercontent.com/84482002/118898293-d7047000-b8d1-11eb-80cc-2c348d8e1fe6.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2021-05-23 11:44
Duplicate of #18746

**Closed by Lheana** 2021-05-23 11:44 UTC
