### ISSUE TITLE
Why is my Friends list saying its Full when I have no Friends?!?!?!

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#12739] opened 2018-11-27 22:49 UTC
An introduction:
<what the bug is and the effects it has or hasn't (if any)>
- My Friends list is literally empty except for those bugged out names I can't remove and for some reason I can't add any friends because it says its FULL.

Details:
<Detailed information regarding the bug and what the result is. This will include what the ACTUAL outcome should be (if it was working correctly).>
- The bug prevents me from adding any new people to be my friend because my friends list is apparently FULL.

Evidence:
<Generally I always include visual evidence of the bug. A screenshot or video as visual aid.>
- This Video shows that I can't add anyone into my friends list. In the Chat on the bottom left it keeps saying my list is full but I don't know why or how.
https://www.youtube.com/watch?v=CJfx2YM1ZPs

Additional Information:
<Anything I would feel would benefit the dev member reading my bug report>
- There is nothing else to add.

How to reproduce the bug:
<If the bug is something that requires an input from the user or a few steps to recreate it. I would write how to recreate the bug.>*
- I have no Idea how to break the friends list into thinking its full.

**Comment by sioding** [comment] 2018-11-28 09:55
Duplicate of #10386

**Closed by sioding** 2018-11-28 09:55 UTC
