### ISSUE TITLE
[DoK] Tactic "Bloodthirst"

### ISSUE THREAD

**Issue by vasia-buhoi** [WarEmu/WarBugs#20519] opened 2022-10-30 07:31 UTC
**Expected behavior and actual behavior:**
Covenant of Celerity with tactic "Bloodthirst" does more damage than the tooltip says

**Steps to reproduce the problem:**
Using abilities on mobs

**Testing Screenshots/Videos/Evidences (always needed):**

<a href="https://ibb.co/Qnrxq2B"><img src="https://i.ibb.co/hHDTnP5/unknown.png" alt="unknown" border="0"></a>

**Comment by Rydiak** [comment] 2022-10-30 15:27
Are you using Divine Fury and a Bloodlord weapon/shield by chance?

**Comment by vasia-buhoi** [comment] 2022-10-30 15:34
Yes. Divine Fury its work on dmg from covenants?

**Comment by Rydiak** [comment] 2022-10-30 15:57
You can close this ticket then.  Percentage damage increase sources buff the damage of auras.  This is not a bug.

**Closed** 2022-10-30 15:59 UTC
