### ISSUE TITLE
"Submit Poll to Kick Guild"

### ISSUE THREAD

**Issue by Nantroxss** [WarEmu/WarBugs#16685] opened 2020-05-06 11:55 UTC
**Expected behavior and actual behavior:**
Expected: Press the "Submit Poll to Kick Guild" to start an alliance poll to remove a guild from alliance.

Actual: Press the "Submit Poll to Kick Guild" answer yes on pop-up box and nothing happens (had 6 out of 9 guilds do the submit poll and nothing occurred and no notification of a poll).

**Steps to reproduce the problem:**
Have 3 guilds join an alliance, have 1 submit a poll to kick 1 of the 3 guilds.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment] 2020-05-06 12:01
Duplicate of https://github.com/WarEmu/WarBugs/issues/16429.

**Closed by Kaelang** 2020-05-06 12:01 UTC
