### ISSUE TITLE
[terrain] BlackCrag => ButcherPass

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13568] opened 2019-03-07 17:40 UTC
https://www.youtube.com/watch?v=AB8H9kRJdqI&feature=youtu.be

You can get to the Fort in the same way that is mentioned below, but jump to the other side

**Comment by sioding** [comment] 2019-03-07 19:56
Duplicate of #13561

**Closed by sioding** 2019-03-07 19:56 UTC
