### ISSUE TITLE
Some corpses do not disappear after butchering.

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#18865] opened 2021-04-20 01:22 UTC
I've noticed that **some** corpses do not disapear after you butcher them. 
The only place I butcher are bats in Reikland. I'm not sure if it is only that place that is affected or everywhere else as well.
Reikland has 5 bats, usually 1-2 of them disappear after butcehring, but the rest doesnt. You do get the materials, but the problem is that sometimes the auto-loot button does not butcher everything, so you have to manually click, and if they are stack on top of each other, it might be difficult to click on the corpse.

**Comment by bloodmasked** [comment] 2021-04-20 02:22
Butchering and salvaging is broken in general. In dungeon runs I have been unable to scavenge/butcher alot of corpses.

**Comment by Lheana** [comment] 2021-04-20 16:46
Duplicate of #18810

**Closed by Lheana** 2021-04-20 16:46 UTC
