### ISSUE TITLE
Shield Dok, Healing from Lifetap

### ISSUE THREAD

**Issue by Fumiik** [WarEmu/WarBugs#20375] opened 2022-08-27 10:24 UTC
Hello!
I wanted to maximize my output healing so i was going to the training dummy and hit him.
I cant se any of my healing i have done in the combat lock. Normal heal skills still working.
![Elbilo_021](https://user-images.githubusercontent.com/112246130/187026049-82222f67-c2fe-4e12-afee-6dbe738ec4a9.jpg)

greetings Fumiik

**Comment by Zomega-WAR** [comment] 2022-08-28 00:32
Lifetap heals don't show up if the person you are healing is at max health.

**Comment by Fumiik** [comment] 2022-08-28 07:00
Same Test with low life.
![Elbilo_022](https://user-images.githubusercontent.com/112246130/187061762-77855dd4-070f-4bd9-9aa1-542a4280145f.jpg)
Result is the same.

**Comment by Zomega-WAR** [comment] 2022-08-28 17:38
The result is not the same. The healing is now showing up as negative damage on you. Duplicate of bug https://github.com/WarEmu/WarBugs/issues/20289

**Comment by lilimx** [comment] 2022-08-29 11:45
Hey,

What Omega wrote.

**Closed by lilimx** 2022-08-29 11:45 UTC
