### ISSUE TITLE
Mail lasts only 2 days? 

### ISSUE THREAD

**Issue by Liciaa** [WarEmu/WarBugs#5051] opened 2016-03-26 00:40 UTC
Hello,

The mail i receive only seem to last two days for me. As u can see on the screenshot the mails i get that i open the same day expires just a day or two after. Dont think thats supposed to be like that? :P 

![mailfudged](https://cloud.githubusercontent.com/assets/18078882/14056949/86db0b60-f2f3-11e5-88d5-07b6c8410170.jpg)

**Comment by taccr** [comment] 2016-03-26 07:03
Pretty sure its:
Unread mails: 28days.
Read mails: 2days.

Can't find the news post for this atm.

**Comment by genisaurus** [comment] 2016-03-29 21:49
Closing, not a bug

**Closed by genisaurus** 2016-03-29 21:49 UTC
Labels: Mail
