### ISSUE TITLE
where are all my quests?

### ISSUE THREAD

**Issue by Remmingtonz** [WarEmu/WarBugs#11724] opened 2018-05-05 02:09 UTC
logged in today and all my quest across all my toons are gone, nothing on the HUD or in ToK3

Expected behavior and actual behavior:
should be showing on HuD and in Tome

Steps to reproduce the problem:
logged in to all my characters and I can pick up new quests, but wont boot the old one into existence

possibly same issue as #2001 

checked armory and wow: im an addict 

![image](https://user-images.githubusercontent.com/38742275/39658766-da54e872-506d-11e8-93f3-65569f70cc98.png)

Screenshots/Videos or archive.org evidences:

![alanahheals_000](https://user-images.githubusercontent.com/38742275/39658734-13be325e-506d-11e8-8014-7a1f59742104.jpg)
![anaerionz_008](https://user-images.githubusercontent.com/38742275/39658740-423a8f88-506d-11e8-9a66-e54e6e9bf214.jpg)

**Comment by Remmingtonz** [comment] 2018-05-05 02:53
also in checking the right side of my screen has had a stroke, unable to clock anything on the right hand side RoR, NPCs. have to rotate the map in order to select anything (RoR) still has issues but eh. what ya gunna do right? :/

**Comment by sioding** [comment] 2018-05-05 02:57
Duplicate of #2001

**Closed by sioding** 2018-05-05 02:57 UTC
