### ISSUE TITLE
[item] Destruction item drops available to Order characters

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#60] opened 2014-05-08 14:31 UTC
I have come across destruction item drops in order areas. I know there are some in Nordland. But up until now I've not come across any.

I found this in Ostland. I know it's out of the immediate area we are currently working on but I wanted to raise this, first and foremost. 

If I find any in Nordland, I will update with the area it dropped.

![chaos item](https://cloud.githubusercontent.com/assets/7492543/2916631/51d059a6-d6bd-11e3-8199-183477adf4f9.png)

**Comment by ozarmidrashim** [comment] 2015-05-29 10:57
Partially fixed in next patch (for generic gear drops.)

**Comment by milosxe** [comment] 2015-09-22 18:38
Cross faction drops are fixed now, unless it's working for some items as intended.

**Closed by milosxe** 2015-09-22 18:38 UTC
Labels: Item, Medium Priority
