### ISSUE TITLE
Sorc, tactic, chilling gust

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14180] opened 2019-05-25 13:05 UTC
Still doesn't crit nor is effected by Dark Magic:

https://youtu.be/C9DOXE-z_EE
https://youtu.be/LgtSK-3Kylg

PS: Still does the wrong dmg, now is 472 instead of 457.

**Comment by sioding** [comment] 2019-05-25 13:44
Duplicate of #14164

**Closed by sioding** 2019-05-25 13:44 UTC

**Comment by TheOGScav** [comment] 2019-05-25 15:58
Dark Magic is NOT mentioned in previous ticket.
