### ISSUE TITLE
Dot commands not working

### ISSUE THREAD

**Issue by Sosaqa** [WarEmu/WarBugs#11990] opened 2018-07-05 10:32 UTC
As title says dot commands not working for me. 
.rvr
.u
.unlock
It is account specific issue, becouse at 2rd one commands works well.
I tried basic things like deleting cache folder\disable addons\deleting setting profile folder.

**Comment by sioding** [comment] 2018-07-05 10:50
Any errormessages from the system? screenshots for it?

**Comment by Natherul** [comment] 2018-07-05 10:55
I have identified an error that may be the cause of this. I would like some more information however since this is happening to a very small number of players.

What localization do you play on? whats the character name? how do you enter the commands?

**Comment by Sosaqa** [comment] 2018-07-05 11:01
Recorded video 
https://puu.sh/ARgO4/9691e428da.flv

**Comment by Natherul** [comment] 2018-07-05 11:06
thank you, Ill look into it.

**Comment by Natherul** [comment] 2018-07-05 14:06
I have been unable to replicate the issue but I have addressed the error that was thrown. If the issue persist after the next patch please to notify me here and the ticket will be reopened. (Sio is going to close it on patch day since its fix pending)

**Comment by Natherul** [comment] 2018-07-05 16:09
sadly we have found a deeper issue with this, can you please contact me over discord?

**Comment by Sosaqa** [comment] 2018-07-05 17:38
Sure, but i cant find where is link for discord.

**Comment by Natherul** [comment] 2018-07-05 17:50
https://discord.gg/G9jDWgv

**Comment by Natherul** [comment] 2018-07-06 22:22
did a quick check on your account just now on the first of 2 restarts and commands were working. If you have continued issues comment on this ticket again

**Closed by Natherul** 2018-07-06 22:22 UTC
Labels: Fix Pending, Source Code
