### ISSUE TITLE
Quest 'silent shores'

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5202] opened 2016-04-06 06:21 UTC
High elves. Ch.1 Quest 'silent shores' Objectives can't be completed. Zones can't be scouted.

**Comment by ellionkeman** [comment] 2016-04-06 08:06
UPD. You can continue with teh quest without completing objectives. This NPC accept quest as finished one and give you second part.
![ulallas_002](https://cloud.githubusercontent.com/assets/18136746/14309870/9c9e57e8-fbe7-11e5-952d-141230e1b7bb.jpg)

**Comment by StaH84** [comment] 2019-04-17 19:30
*Expected beahvior:*

Step 1:
1. Tooltip:
* Southern Shoals Scouted 0/1
* Central Shoals Scouted 0/1
* Northern Shoals Scouted 0/1

2. Since AFAIK it is not possible to trigger the quest objective just by entering the area, I suggest creating a quest item i.e Spyglass or something and trigger the quest onjectives by using the item. It works on Poder keg quest with a dwarf in High elf Chapter 1.

Step 2:
Tooltip:
Quest Waypoint
* Speak with Haladhrel Stenbrow 0/1

Step 3:
Tooltip:
Quest Waypoint
* Speak with Morithwen Nightwhisper 0/1

*Actual behavior:*

Steps 1 and 2 are connected and You only need to speak with  Haladhrel Stenbrow
Step 3 remains.

To reproduce:

Take and follow the quest:

Screenshots:

![Gwarnhil_005](https://user-images.githubusercontent.com/18528095/56315440-ff03d100-6157-11e9-98a8-3749cb5783a9.jpg)
![Gwarnhil_027](https://user-images.githubusercontent.com/18528095/56315446-01fec180-6158-11e9-8eaa-3c1e29b9145d.jpg)

**Comment by Lheana** [comment] 2019-06-15 15:33
Workaround has been made. Will be on live with next patch.

**Comment by sioding** [comment] 2019-06-23 13:56
fixed with patch from 22.6.2019

**Closed by sioding** 2019-06-23 13:56 UTC
Labels: Database, Fix Pending, Quests
