### ISSUE TITLE
Permanent outgoing heal debuff

### ISSUE THREAD

**Issue by Grognir** [WarEmu/WarBugs#12463] opened 2018-10-17 10:57 UTC
Expected behavior and actual behavior:
Outgoing 50% heal debuff sometimes remains permanently whereas the duration should be limited to some seconds, and no debuff icon on the character. It cannot be removed even by typing /rel or changing area. Only possibility to see it is to look at the combat chat log, and only possibility to remove is to deconnect the account and reconnect again.

Steps to reproduce the problem:
Very hard to describe the condition to reproduce it, it seems very closed to the permanent snare issue we had already experienced. It happened to me either in rvr or scenario, and sometimes several times in the same evening.

Screenshots/Videos or archive.org evidences:
If you keep some log files, it was applied on my character "Grognur" in game (Rune Priest order side) the 17 october 2018 just before my last deconnexion during the night at around 00:30 am

**Comment by Grognir** [comment] 2018-10-17 11:30
Related to ticket https://github.com/WarEmu/WarBugs/issues/12344

**Comment by sioding** [comment] 2018-10-17 17:02
Thanks for linking the ticket. So this one will be closed. It won´t help to have more than one open ticket for one issue.
Duplicate of #12344

**Closed by sioding** 2018-10-17 17:02 UTC
