### ISSUE TITLE
Stone Troll Crossing (FLAG BUG)

### ISSUE THREAD

**Issue by moist666** [WarEmu/WarBugs#14724] opened 2019-08-04 23:10 UTC
Hello sorry it's me again Moisstt this time with a real bug though.... take a look.

Stone Troll Crossing flag is not appearing after reset. 

https://www.dropbox.com/s/i7px321n2y8tygc/bug%202.mp4?dl=0

**Comment by Lheana** [comment] 2019-08-05 09:20
Duplicate of #9542

**Closed by Lheana** 2019-08-05 09:20 UTC
