### ISSUE TITLE
wounds debuff

### ISSUE THREAD

**Issue by ufthakk** [WarEmu/WarBugs#18477] opened 2021-02-09 14:43 UTC
[woundsdb.zip](https://github.com/WarEmu/WarBugs/files/5952969/woundsdb.zip)

**Expected behavior and actual behavior:when i die i can't interact with healers to clear wounds debuff its the same for all my destro toons.**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment] 2021-06-14 20:40
hey,

what is in this zip? And are you using the addon "HealAll"?

**Comment by lilimx** [comment] 2021-07-01 06:56
Hey,

im going to close this ticket now.
If you are the opinion the issue is still up, please open a new ticket with a proper descirption and some screenshots.

**Closed by lilimx** 2021-07-01 06:56 UTC
Labels: 2 Week Ultimatum, Confirmation Request
