### ISSUE TITLE
DoK with squig-herding skills

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#14616] opened 2019-07-22 09:56 UTC
**Expected behavior and actual behavior:**
I was cultivating in IC when I saw a DoK that had a squig following her like it was her own!

**Steps to reproduce the problem:**
After a little bit of digging I found out that the Velenium is in the same lvl-range of scenarios that this DoK is, maybe some bug ocurred and the squig found a new master in the scenario (?)...

I also suspect it might be related to the new darkelf class that it was being developed (Beastmaster), some bits of the code might have found its way into the active server (?)
This is purely speculative on my part, please watch the video.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=JEP3eZz4zJM

**Comment by Scophis** [comment] 2019-07-22 10:18
There are Squig vanity pets (iirc they are called Fartysquigs). You can check them out in the south of IC, near the armor vendors. Most of them are obtainable during events. They are just decorations, and can't be summoned in RvR or while being infight. 
That's probably what you saw.

**Comment by Scophis** [comment] 2019-07-22 10:21
Forget the part above. Didn't see your YT-Link. My bad.

Can't edit on mobile

**Comment by grunbag** [comment] 2019-07-22 11:00
Its a horned squig and definitely no intended to have a DoK summon it

**Comment by grunbag** [comment] 2019-07-31 11:59
Can’t reproduce closing it’s probably due to lag and crash then relog on another char

**Closed by grunbag** 2019-07-31 11:59 UTC
Labels: Ability, Dubious
