### ISSUE TITLE
Order Chapter 1 PQ not completing.

### ISSUE THREAD

**Issue by Naelar** [WarEmu/WarBugs#15817] opened 2020-02-27 03:08 UTC
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
This happened last night, as well.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment] 2020-02-27 18:42
I need more details: Which PQ? What happened exactly?

**Comment by dalen** [comment] 2020-03-02 15:00
Likely it is due to the "Nordland Peasant" mobs near the PQ getting the killing blow on the boss. A fix for this is pending.

**Comment by dalen** [comment] 2020-03-02 17:06
Also duplicate of https://github.com/WarEmu/WarBugs/issues/12685

**Closed by dalen** 2020-03-02 17:06 UTC
Labels: 2 Week Ultimatum, Confirmation Request, Database, Fix Pending, Public Quests
