### ISSUE TITLE
[Night of Murder // 2022] Event Cloak - Does not appear

### ISSUE THREAD

**Issue by ojoaop** [WarEmu/WarBugs#19808] opened 2022-02-12 03:14 UTC
**Expected behavior and actual behavior:** The appearance may work when I use the event cloak or I put it on Appearance spot. Problem is: it isn't working (how you can see on images)

**Steps to reproduce the problem:** finish the event quest and chose the Harvest cloak, try to use.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/97126301/153694501-671ed508-1847-4014-a55f-382e86fe9c2a.png)
![image](https://user-images.githubusercontent.com/97126301/153694588-8f6f49e5-f243-4958-aabe-98d939789810.png)

**Comment by lilimx** [comment] 2022-02-12 09:30
Hey,

you already tried the repair function?

**Comment by ojoaop** [comment] 2022-02-12 10:54
Hey!

yes, tried Repair, Relog, Disable/Enable effects…

**Comment by lilimx** [comment] 2022-02-12 16:53
Hey,

either something is broken, maybe it's an issue with the russian language package that affext something or, it's really a bug

**Comment by ojoaop** [comment] 2022-02-12 17:20
Hi,

ok, I’ll uninstall the game and install again, but I don’t use Russian language. I use English.

**Comment by lilimx** [comment] 2022-02-12 19:34
sorry....for some reason I thought there were cyrillic signs.....big brain lag

**Comment by lilimx** [comment] 2022-02-14 18:15
hey,

just to be sure, is it possible for you to join the RoR discord? 
the link: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044

poke me in #technical-advice

**Comment by lilimx** [comment] 2022-02-14 19:22
Note:

Checked his files, they are okay. But for now, he is the only one with this issue and I can't reproduce it.

**Comment by Kaelang** [comment] 2022-07-21 23:22
Works for me - and looks good in DB.

Going to close this, if it's an isolated case it's probably file related - and if it's simply this one piece of data that's corrupted you likely won't be able to tell from the sizes.

**Closed by Kaelang** 2022-07-21 23:22 UTC
Labels: Item, Confirmation Request, Visual, Events
