### ISSUE TITLE
Opt Out of Bags Resets with each PQ stage

### ISSUE THREAD

**Issue by epowell1021** [WarEmu/WarBugs#11561] opened 2018-04-07 13:27 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Opt out of bags selected when PQ started. Player still won gold bag according to scoreboard screen, but looted blue bag. Opt out option found to reset with each advancement of PQ stage at Chaos Ruin PQ in Hard Pass. Have not checked to see if this is case at other PQs. 

Steps to reproduce the problem:

Opt out of bag, Advance PQ stage, look at Opt out options

Screenshots/Videos or archive.org evidences:

None taken yet

**Comment by sioding** [comment] 2018-04-07 17:15
Duplicate of #10422

**Closed by sioding** 2018-04-07 17:15 UTC
