### ISSUE TITLE
Can't Get credit for Matriarch Kill for event.

### ISSUE THREAD

**Issue by Twicckk** [WarEmu/WarBugs#16387] opened 2020-04-14 18:29 UTC
I have killed 38 Matrirachs and still have no credit.

I'm not sure if it requires a deathblow or what, from what I have seen deathblows seem to get credit for the quest and nobody else. From my observations most of the time the person to get credit was a DPS, which lines up the the theory it only goes to those with a deathblow.

Even if it were given to a random person in the party I must be the unluckiest person on the planet because statistically I would think between a random distribution of 38 kills I would at least get credit for 1 of them.

Please fix this. I feel like I have wasted a ton of time just trying to finish it with there being no realistic way of finishing it. I feel bamboozled.

**Comment by Lheana** [comment] 2020-04-14 18:59
Duplicate of #16353

**Closed by Lheana** 2020-04-14 18:59 UTC
