### ISSUE TITLE
Auction career filter: Chosen

### ISSUE THREAD

**Issue by 13jack13** [WarEmu/WarBugs#4357] opened 2016-02-14 12:42 UTC
If you select Chosen as filter for sorting auction items, Zealot charms appears listed. No big deal, but now you know. Thanks guys for the great work.

**Comment by Evildoor** [comment] 2016-02-14 13:25
Are doing a search as a Zealot?

**Comment by Xodiack** [comment] 2016-02-14 17:58
No, I get the same as Jack. 
Items that is used for Zealot appears in the AH list when selecting Chosen only.

**Comment by 13jack13** [comment] 2016-02-14 18:57
As Chosen, with chosen career only selected.

**Comment by Evildoor** [comment] 2016-02-15 08:11
This happens because charms are not explicitly restricted to Zealot (they have race restriction, and only chaos career which can use them is Zealot). Same happens, for example, with KotBS (you get WP books shown to you). I see two possible solutions:
1) Fix this for entire item type (WP books are shown to KotBS, but WH pistols are not, even though both item types only have "Empire", "Off Hand" and "Pistol"/"Charm" restrictions, which hints that there is some kind of hidden difference).
2) If 1 is impossible, then this can be fixed by adding class restriction to ALL relevant items which can be sold on AH, but i doubt that anyone should waste their time doing so, since the problem is trivial and can be easily avoided using filters.

**Comment by Kaelang** [comment] 2020-09-24 14:12
This should have since been fixed.

**Closed by Kaelang** 2020-09-24 14:12 UTC
Labels: Item, Trivial
