### ISSUE TITLE
[Non-Gamebreaking][Visual Bug]Marauder Path of Monstrosity tactical Hulking Brute

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#16512] opened 2020-04-26 07:47 UTC
**Expected behavior and actual behavior:**

not showing initiative on character stat screen and on stance it says only increasing toughness
https://streamable.com/70ped0

but shows additional initiative on  .getstats screen.

https://streamable.com/975uqe

**Comment by Kaelang** [comment] 2020-04-26 12:27
The .getstats function is the best option when checking if skills are updating correctly. I appreciate you testing this ability using both. 

This ability looks to be working as intended and so I'll close this thread.

The team are aware of the character sheet not updating correctly in certain circumstances.

**Comment by grunbag** [comment] 2020-04-26 13:09
I leave those open cause u can update stat doll

**Closed** 2021-08-22 18:48 UTC
Labels: Ability
