### ISSUE TITLE
Rift/Magnet in t3

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#1843] opened 2015-11-19 13:15 UTC
This is not really a bug report, but a combination of both. So, there has been a lot talk lately about rift. If I understand correctly, doors do not follow the same rules for "los" currently.  So, theoretically you could have 2-3 engs or magi rift through the door and eliminate people attacking the door. 

So, would it be possible to disable rift until siege or door los fixes are implemented? 

You know what they say...prevention is the best medicine :X

**Comment by Evildoor** [comment] 2015-11-19 13:24
If it is a report about doors being transparent to AoE, then it is a duplicate of #931. If it is a suggestion to improve balance of the game by disabling aoe pulls until #931 is fixed then it is not a bug and belongs to forums. Closing.

**Closed by Evildoor** 2015-11-19 13:24 UTC
