### ISSUE TITLE
Mail icon Bugged

### ISSUE THREAD

**Issue by Veath58** [WarEmu/WarBugs#13548] opened 2019-03-05 02:25 UTC
Small bug, nothing to big but still a bug none the less. When making a purchase from the Auction house, and opening the mail, the mail icon still shows below my mini map. just wanted to point it out.

Thanks
-Failbird

**Comment by sioding** [comment] 2019-03-05 07:18
Duplicate of #1109

**Closed by sioding** 2019-03-05 07:18 UTC
