### ISSUE TITLE
I lost hours of progress for relogging

### ISSUE THREAD

**Issue by bossnass87** [WarEmu/WarBugs#15452] opened 2020-01-10 04:07 UTC
I exited the game and logged back in to find my character had rolled back hours of progress. I was an inch away from level 14 and I rolled to lvl 7 with 68% xp. I lost a lot of renown ranks too. I also lost almost all my gold. For some reason, I still have all the items in my bags that I had on me when this rollback happened, which is proof of my previous higher levels.

Character name Rektumusboom, currently lvl 7 engineer, as can be seen in the attached picture.

https://i.imgur.com/qSMdonq.jpg

**Comment by Cryolesion** [comment] 2020-01-10 13:45
I was also rolled back from level 10 to level 5, everything was rolled back including gold, items etc.

**Comment by raptrr** [comment] 2020-01-10 18:21
Duplicate of #15434

**Closed by raptrr** 2020-01-10 18:21 UTC
