### ISSUE TITLE
[WP] Apostle's Tome of Reverence possibly wrong stats

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#14138] opened 2019-05-20 13:40 UTC
**Expected behavior and actual behavior:**

Compared to the RR45 SC Apostle's Tome of Glory the new RR61 ones' stats seem to be too low (less Wounds and healing power), plus the +AP bonus may be not intended since crit reduction is missing. 

**Screenshots/Videos or archive.org evidences:**
![Unbenannt](https://user-images.githubusercontent.com/21637631/58026095-0848da80-7b16-11e9-8dbc-79ef0fe158ec.png)

**Comment by sioding** [comment] 2019-05-20 17:10
Duplicate of #14131

**Closed by sioding** 2019-05-20 17:10 UTC
Labels: Database, Item
