### ISSUE TITLE
[Beastlord] Reward Token 4/5

### ISSUE THREAD

**Issue by AmakusaROR** [WarEmu/WarBugs#15695] opened 2020-02-15 13:30 UTC
Hi i have done all the the Beastlord Quests and i miss one Token, so im stuck at 4/5 and cant repeat the quest. This problem isnt new since ive done that a couple of months ago.
What can i do now? Charname: Kenshin

**Comment by Lheana** [comment] 2020-02-18 18:28
Duplicate of #10721

**Closed by Lheana** 2020-02-18 18:28 UTC
Labels: Item, Quests
