### ISSUE TITLE
City Siege Stage 3 - Players Duplicating and UI not working properly..

### ISSUE THREAD

**Issue by Scottx125** [WarEmu/WarBugs#20573] opened 2022-11-24 20:23 UTC
**Expected behavior and actual behavior:**
UI should show allies nearby and allow them to be targeted for healing and players should not be duplicating and acting as if they're not in range or dead. What actually happens is players appear to duplicate at times with one of them running around and the other standing still. Then the UI gets confused because 2 versions of the same person exist and doesn't allow you to target them through clicking via the warband frames, preventing you from doing anything targeted via the warband UI.

**Steps to reproduce the problem:**
Play city sieges as a 24man.

*Evidence*
![Seiigfrid_153](https://user-images.githubusercontent.com/31070452/203858875-59ef2a2a-0ebe-40b0-b80e-bb315da6c60d.jpg)
![Seiigfrid_152](https://user-images.githubusercontent.com/31070452/203858879-b3b2ffe8-ca97-4a75-8094-44e125d2c507.jpg)
More will come later, it's part of a twitch stream and it's currently processing.

**Comment by bosli42** [comment] 2022-11-24 20:28
duplicate of #20489 please merge

**Comment by Scottx125** [comment] 2022-11-24 20:33
Thanks bosil, looks like the same issue.

**Closed** 2022-11-24 20:40 UTC
