### ISSUE TITLE
Squig Herder - Outa my Way makes own pet agro

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#12216] opened 2018-08-26 19:13 UTC
When Outa my Way is cast own pets starts attacking the squig herder 

Steps to reproduce the problem:
Flag for pvp, summon pet, use outa my way

**Comment by sioding** [comment] 2018-08-27 07:17
Any screens/video?

**Comment by Culdu** [comment] 2018-08-28 17:53
![petattack](https://user-images.githubusercontent.com/14928735/44740929-f9d81000-aafb-11e8-9a1b-84f65fff871d.png)

**Comment by Binkies** [comment] 2018-12-12 18:20
I believe the issue is actually caused by the **'Ere, Squiggy!** Tactic that can be obtained in the _Path of Bouncin'_ Mastery Tree.

I leveled my SH and had been playing him only with the other 2 Mastery Specs, and never saw this happen. After recently swapping to the Bouncin' Spec it started.

To reproduce:

- Obtain and use the **'Ere, Squiggy!** Tactic
- Get hit by any mob
- Pet will eventually start attacking you as well

The Screenshot attached is the combat log from testing this theory by getting hit by a low-level mob.
![petattackbug](https://user-images.githubusercontent.com/45829268/49889856-95be2b00-fe10-11e8-8b22-95fb579ba175.jpg)

**Comment by Natherul** [comment] 2018-12-12 19:08
was indeed ere squiggy. 

Thanks for excellent information. I have isolated the issue and committed a fix thats pending for the next patch

**Comment by sioding** [comment] 2018-12-15 13:38
fixed with patch from 15.12.2018

**Closed by sioding** 2018-12-15 13:38 UTC
Labels: Ability, Fix Pending
