### ISSUE TITLE
Crashed from SC to main menu with character logged in

### ISSUE THREAD

**Issue by MidiDEVS** [WarEmu/WarBugs#14417] opened 2019-06-14 01:40 UTC
Just Crashed into the main menu, after ending the Stonetroll Crossing SC.

The client brought me to the main menu with my character in the background, logged in.

I restarted the client and the problem was fixed.

![Lyzshiry_009](https://user-images.githubusercontent.com/13495078/59477493-a8fc9280-8e55-11e9-9b37-40c1cca370fa.jpg)

**Comment by sioding** [comment] 2019-06-14 06:56
Duplicate of #11224

**Closed by sioding** 2019-06-14 06:56 UTC
