### ISSUE TITLE
Holmsteinn Revisited PQ Broken

### ISSUE THREAD

**Issue by mainframe0651** [WarEmu/WarBugs#11780] opened 2018-05-18 18:33 UTC
Holmsteinn Revisited public quest in Norsca is broken. The required item to advance past stage 1 have not shown up nor have the Nordland NPCs which also stops the quest Deadly Task from being completed. It has been like this for ~24h.

**Comment by sioding** [comment] 2018-05-18 20:29
Duplicate of #10862
Sorry but you have to wait until Server restart

**Closed by sioding** 2018-05-18 20:29 UTC

**Comment by CatraioPT** [comment] 2019-08-03 17:47
After recent patch this PQ is bugged. Might look into it.
