### ISSUE TITLE
(Standard) Able to mount and Port with standard buffs being effective

### ISSUE THREAD

**Issue by Toshutkidup** [WarEmu/WarBugs#13105] opened 2019-01-09 12:51 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: The expected was when you use the standard you wouldnt be able to then mount , keep buffs on your character or port to different zone and keep buffs active. 

Steps to reproduce the problem: Equip your standard, then mount. Standard will go away visually however you keep the buffs. and you get your mount speed. You can also then port to a different zone and still keep buffs. 

Screenshots/Videos or archive.org evidences:
https://youtu.be/UCnEtZqIII4

**Comment by sioding** [comment] 2019-01-09 17:15
Duplicate of #13088

**Closed by sioding** 2019-01-09 17:15 UTC
