### ISSUE TITLE
PVE quest : Bandit's bane : mobs kills not counted when in a group

### ISSUE THREAD

**Issue by Jerloldrartolf** [WarEmu/WarBugs#14254] opened 2019-05-28 18:08 UTC
**Expected behavior and actual behavior:**
Bandit's bane quest
Expected - Kill darkwood bandit when in a party - Kill count should increment i.e. 0/6 to 1/6 etc.
Actual - Kill count does not increment when in a group.

**Steps to reproduce the problem:**
join a party and kill bandits.
Look at required to complete quest.
as per screen shot, standing over a dead body with description of darkwood bandit, note the quest requirements in HUD.

**Testing Screenshots/Videos/Evidences (always needed):**
![after kill in a paryt](https://user-images.githubusercontent.com/48033566/58501254-dd94fc80-817b-11e9-874a-86bd71c3a9ab.png)
![before kill in a paryt](https://user-images.githubusercontent.com/48033566/58501255-dd94fc80-817b-11e9-939a-2a6759a4c570.png)

**Comment by CrimsonFenris** [comment] 2019-05-28 19:58
Happens when at least one of group member already completed the quest, or is not in same stage as all others.

**Comment by Hargrim** [comment] 2019-05-28 21:11
Should be fixed after patch on Saturday 01.06.2019.

**Comment by Lheana** [comment] 2020-02-16 20:18
#12470

**Closed by Lheana** 2020-02-16 20:18 UTC

**Comment by Alfi9169** [comment] 2021-04-08 10:52
The problem is that you have to kill 6 bandits to count the baskets and when you pick up a basket it counts it as the death of the bandit you need.
