### ISSUE TITLE
Dark elf sorcerer special emote

### ISSUE THREAD

**Issue by roxyrevolver** [WarEmu/WarBugs#14699] opened 2019-07-31 18:06 UTC
The special emote for dark elf sorcerer is messed up . You can see the wire frame of the effect and the animation gets stuck even if you go into battle or ride your mount . The only way to end the animation is to exit the game

**Comment by roxyrevolver** [comment] 2019-07-31 18:07
The special emote for dark elf sorcerer is messed up . You can see the wire frame of the effect and the animation gets stuck even if you go into battle or ride your mount . The only way to end the animation is to exit the game

**Comment by sioding** [comment] 2019-07-31 19:10
Duplicate of #8129

**Closed by sioding** 2019-07-31 19:10 UTC
