### ISSUE TITLE
Tome of Knowlegde - Events Tab

### ISSUE THREAD

**Issue by martialiss** [WarEmu/WarBugs#18141] opened 2020-11-28 06:39 UTC
**Expected behavior and actual behavior:**
In the Tome of Knowledge, once you have clicked on the current live event, the view always jumps back to the general events tab.
This is not critical, but a bit annoying. nd this has been the case for several patches.

**Steps to reproduce the problem:**
Open Tome of Knowlegde. Click on the event tab. Click on the current live event.
Then it automatically jumps back to the previous view after approx. 7 seconds, sometimes even after 2 seconds.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/75132461/100495482-8dba3b80-314c-11eb-9c23-85eeef6a3488.png)

**Comment by Lheana** [comment] 2020-11-29 14:27
Duplicate of #18106

**Closed by Lheana** 2020-11-29 14:27 UTC
