### ISSUE TITLE
Encounter in progress(bloodsworth enclave)

### ISSUE THREAD

**Issue by FixitFastah** [WarEmu/WarBugs#12607] opened 2018-11-17 22:40 UTC
![glubz_043](https://user-images.githubusercontent.com/45132446/48666397-44e13e00-eac1-11e8-9d72-827b806f4990.jpg)

We went into the enclave, killed 2 bosses, then someone had to leave. We found another player, but he could not enter and got the message: encounter in progress. So we went all out and tried if we could enter again together. Now we have the same message, even after a relog(suggested by a GM) we get that same message. The only one that can enter now is the one that last entered the group.(in a new dungeon)

**Comment by sioding** [comment] 2018-11-18 08:14
Duplicate of #12606

**Closed by sioding** 2018-11-18 08:14 UTC
