### ISSUE TITLE
Not receiving any renown points from any Open World kills or Scenario completions

### ISSUE THREAD

**Issue by Ulvengard** [WarEmu/WarBugs#18918] opened 2021-04-29 05:38 UTC
**Expected behavior and actual behavior:**
Not receiving renown points from any open world kills or from Scenarios. 

**Steps to reproduce the problem:**
Killing any enemy in open world results in no renown points rewarded.  Completing a Scenario results in no renown points rewarded.  I have been leveling from level 3 to my current level 10 solely from PvP (open world and Scenarios) and I am still Renown Rank 0 with 0 renown points accumulated.

I have tried this on 2 different computers and RoR installations and am getting the same Renown Points bug on this character.

This character was created new today at around 12:30pm Pacific Standard Time.

**Testing Screenshots/Videos/Evidences (always needed):**
![Current Renown Rank](https://user-images.githubusercontent.com/83389076/116506560-650cae00-a872-11eb-8f92-8c7b15a60753.jpg)

![RvR Kill Count](https://user-images.githubusercontent.com/83389076/116506574-6a69f880-a872-11eb-8b49-be3b8b66fb72.jpg)

![RvR Achievments](https://user-images.githubusercontent.com/83389076/116506586-6dfd7f80-a872-11eb-9db8-b4359bef9cfc.jpg)

**Comment by xpander69** [comment] 2021-04-29 09:06
duplicate of https://github.com/WarEmu/WarBugs/issues/18915

**Comment by MaxHayman** [comment] 2021-04-29 16:42
Fixed

**Closed by MaxHayman** 2021-04-29 16:42 UTC
Labels: Fix Pending
