### ISSUE TITLE
Gates of Ekrund - Strategic hideout

### ISSUE THREAD

**Issue by VAGAMUNDO** [WarEmu/WarBugs#19572] opened 2021-11-07 17:35 UTC
Hello I was playing with my main character Aikiescudo and I came across this
you just have to climb that hill
![Aikiescudo_000](https://user-images.githubusercontent.com/93868124/140655194-c1f6dfbc-5bc9-439e-af9a-0d852094a742.jpg)
![Aikiescudo_006](https://user-images.githubusercontent.com/93868124/140655212-a1694469-3008-4009-aeed-6c9544b3d764.jpg)
![Aikiescudo_010](https://user-images.githubusercontent.com/93868124/140655213-8f69826b-c272-4b53-a178-070b945c9694.jpg)

It is possible to go off the map to escape enemies and ensure a game with 0 kills
possible to stand on the flag using this method
![Aikiescudo_011](https://user-images.githubusercontent.com/93868124/140655298-cfb28e53-0acc-4280-87d4-271f4e3b077a.jpg)
![Aikiescudo_012](https://user-images.githubusercontent.com/93868124/140655299-9d6f2670-34b5-4dd6-9a51-310167d8f4a8.jpg)

It is possible to go off the map and look for strategic positions to attack among other strange things

![Aikiescudo_001](https://user-images.githubusercontent.com/93868124/140655360-89b58d50-3b84-449d-86d1-7e3b28f5b525.jpg)
![Aikiescudo_014](https://user-images.githubusercontent.com/93868124/140655362-b9caf327-e68a-4748-ac1d-93b5c92d5613.jpg)
![Aikiescudo_015](https://user-images.githubusercontent.com/93868124/140655363-a5f2656e-46d8-4d59-8919-7a088768f2fd.jpg)
![Aikiescudo_016](https://user-images.githubusercontent.com/93868124/140655364-04fa1fda-0ef9-44c6-b2e0-3e15dab5e4f6.jpg)
![Aikiescudo_017](https://user-images.githubusercontent.com/93868124/140655365-6a4c202f-325b-444d-8b0c-338d9e5374ca.jpg)

It is possible to attack from a safe place using this method

![Aikiescudo_007](https://user-images.githubusercontent.com/93868124/140655450-fb27c181-be29-412f-9b11-d69cb501ff56.jpg)
![Aikiescudo_008](https://user-images.githubusercontent.com/93868124/140655452-cc9d9d1b-14e9-493a-8c6f-1b320b5fe5d7.jpg)
![Aikiescudo_011](https://user-images.githubusercontent.com/93868124/140655486-a32612da-2401-4742-9acf-c84b4eac29e0.jpg)
![Aikiescudo_013](https://user-images.githubusercontent.com/93868124/140655490-5ccaee9c-761b-4cc4-88e1-609243af67e9.jpg)

**Comment by Lheana** [comment] 2021-11-14 15:26
Even though I could not reproduce it, the way should be blocked with next patch.

**Comment by lilimx** [comment] 2021-11-20 14:04
fixed with patch 20/11/2021

**Closed by lilimx** 2021-11-20 14:04 UTC
Labels: Scenarios, Fix Pending, Map/Area
