### ISSUE TITLE
Lair bosses loot tables.

### ISSUE THREAD

**Issue by Cr3nshaw** [WarEmu/WarBugs#518] opened 2014-12-31 00:47 UTC
Both bosses drop dessie gear for order and vice versa. These are some of items needing fixing.

Destruction:

Skinflayer of the Lady
Daemonstaff of the Lady
Direblade of the Lady
Cleava of the Lady
Choppa of the Lady
Makhaira of the Lady
Xiphos of the Lady

Order:

Longbow of the Lady
Runestaff of the Lady
Battlehammer of the Lady
Greataxe of the Lady
Windstaff of the Lady
Longsword of the Lady
Greatsword of the Lady
Mallet of the Lady
Long Rifle of the Lady
Rapier of the Lady
Greatstaff of the Lady

**Comment by Evildoor** [comment] 2015-09-18 10:31
I'm not sure if the loot tables for the bosses are 100% correct, but i do believe they are more or less working. Closing unless someone provides more info.

**Comment by Evildoor** [comment] 2015-12-07 08:06
Still bugged according to #2188.

**Comment by genisaurus** [comment] 2016-01-20 18:43
Lair boss drops are overridden in the code, and that code does not account for faction. Working as intended, until the new loot system is finished. Closing this issue.

**Closed by genisaurus** 2016-01-20 18:43 UTC
Labels: Database, NPC
