### ISSUE TITLE
[PQ] Fireforge's Camp, Stage 1 (The Badlands, destro) only 2 Supply Crates attackable

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14219] opened 2019-05-26 22:55 UTC
Out of the 10-ish supply crates in the area only two are actually attackable which forces one to wait for respawn over and over.

![fireforges camp](https://user-images.githubusercontent.com/30193675/58388079-043b2200-801a-11e9-81a0-b0b0e58a43c0.jpg)

**Comment by Lheana** [comment] 2019-06-04 14:12
Duplicate of #14044

**Closed by Lheana** 2019-06-04 14:12 UTC
Labels: Database, Public Quests
