### ISSUE TITLE
Karak Karag outer wall LoS issue

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#15971] opened 2020-03-14 12:45 UTC
**Expected behavior and actual behavior:**
This might be the same underlying issue as the oil targeting issue (#15969), but on the defensive side. The gatehouse has a much larger LoS blocking area than the model would suggest. My zealot was standing on the wall trying to heal someone clearly in sight on the ground inside the wall but was out of LoS due to the gatehouse model and occlusion box not matching up. See screenshots below. 
Expected behavior is to be able to heal someone clearly in your line of sight. 

**Steps to reproduce the problem:**
Stand where I was on the screenshots below and try to heal someone standing below with the gatehouse wall close by. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Cruzealot_007](https://user-images.githubusercontent.com/1183293/76682157-eadf8280-65f9-11ea-94f3-e4524721de62.jpg)
![Cruzealot_006](https://user-images.githubusercontent.com/1183293/76682160-ed41dc80-65f9-11ea-9d68-d8da94315138.jpg)

**Comment by raptrr** [comment] 2020-03-15 15:52
Duplicate of https://github.com/WarEmu/WarBugs/issues/15675

**Closed by raptrr** 2020-03-15 15:52 UTC
Labels: Map/Area, ORvR
