### ISSUE TITLE
Perma Snare after/and in Tor Anroc/Caledor Woods

### ISSUE THREAD

**Issue by Rincevvind** [WarEmu/WarBugs#12472] opened 2018-10-19 23:27 UTC
In Toc Anoc scenario when IB snare and punt you into lava you become permasnared until relog. Even after scenario end.

Expected behavior and actual behavior:
obliviously expected behavior - no permasnare effect.  

Steps to reproduce the problem:
Expected 3 times as WE. not sure about other classes.
1)Be WE
2)Get snared and punted into lava by IB

Screenshots/Videos or archive.org evidences:

**Comment by Morksezstop** [comment] 2018-10-21 12:57
i got the bug as order player twice when kd and punted from bg and kd and punted from chosen.
I am not sure but both times i got slowed and then land on lava, it seems that trigger the bug
The second time i check my stats and got unusual entry, i hope that help

<a href="https://ibb.co/mEikML"><img src="https://preview.ibb.co/kg7C1L/Gemmio-018.jpg" alt="Gemmio-018" border="0"></a><br /><a target='_blank' href='https://babynamesetc.com/animal'>what's a baby zebra called</a><br />

**Comment by Rincevvind** [comment] 2018-10-21 18:37
Well i seen messages by other WE's only.
Also i never experienced it with Kobts/SM, but maybe i wasn't snared.

**Comment by loodit** [comment] 2018-10-21 19:51
This bug is not specifically applied to lava. I am a WE and get perma snared in caledor woods too. 3 times so far.

**Comment by NabaroNya** [comment] 2018-10-23 06:37
Antisnare abilites make lava snare endless. Relog fix it. Tested on my WH and WE.

**Comment by Morksezstop** [comment] 2018-10-23 09:06
But I got that on rp and I didnt used focused mind afaik

**Comment by Morksezstop** [comment] 2018-10-24 18:06
Ok. After some testing i find the root of the problem.
The bug occur when player use snare immune skill/moral while in lava. I tested it at lava at pve zone with rp. i just reach m2, use FM and enter at lava, after i go out i get prema snare that i could remove by dying or relog. There is some bug at the code when u try to ignore lava slow with slow immunity skills/morals.

PS No idea how did u got that bug at caledor woods BUT it is possible the bug to occur when using snare immune skill/moral when slowed by some other aoe slow that cant be ignored by slow immunity skills

**Comment by Natherul** [comment] 2018-10-28 18:15
with next hotfix/path there will be a change on how lava snare is handled. After said update please report back if it still is an issue and if so exactly what lead to it.

**Comment by Marawo** [comment] 2018-11-04 12:32
![zahla_000](https://user-images.githubusercontent.com/29643742/47964162-dd91ab80-e035-11e8-8a79-ac92cc907985.jpg)
I didn't use any snare immunities, no Focus of Mind either. Top left corner the very first icon says "LAVA".
Bug still persists.

**Comment by Natherul** [comment] 2018-11-04 12:39
even more changes to the handling is coming next patch and further may be needed still as I got some information last night that may or may not be the cause in some cases:
https://github.com/WarEmu/WarBugs/issues/12521

**Comment by Natherul** [comment] 2018-11-07 10:47
also most likely related to 
https://github.com/WarEmu/WarBugs/issues/12540
another change will happen today to see if it improves. Found a system that used a legacy way of changing speed which may or may not be the cause of this issue.

**Comment by Natherul** [comment] 2018-11-09 16:43
please advice if this is still happening after last change.

**Comment by NabaroNya** [comment] 2018-11-09 21:17
It happened to me and my friends, when falling into lava I take a speeddebuff from Ironbreaker and die in lava(college SC). Resurrected with a permaslow.

**Comment by anarchypark** [comment] 2018-11-14 03:13
i think, dying exact same time when snare debuff off is cause of perma snare.
i could reproduce lava snare by walking out of lava right when dying.
in SC i found getting perma snare when i die at the lava edge.
tested in TM lava. i got perma snare after 5 attempt.

also i had perma snare from skill.
debuff icon timer was on 0s.

though i have bad ping, 300ms
timing might differ for EU players.
hope it helps.

**Comment by Natherul** [comment] 2018-12-12 19:50
I have just committed another attempt to fixing this issue. So please let me know if its still an issue AFTER next patch

**Comment by Natherul** [comment] 2018-12-27 09:36
Sorry if I sound like a broken record but has this happened since the last patch where I reworked the buff systems backbone?

**Comment by anarchypark** [comment] 2019-01-08 09:19
tested today and couldn't reproduce perma snare at lava.
ty for fix though tor anroc SC will be more accurate test i think.

**Comment by Natherul** [comment] 2019-01-08 10:34
thank you. Ill consider this fixed then. If the issue arises again please comment back here. Thanks for the report

**Closed by Natherul** 2019-01-08 10:34 UTC
Labels: Sourcecode
