### ISSUE TITLE
Energy of Vaul and Penetrating Siphon

### ISSUE THREAD

**Issue by Flavor-burst** [WarEmu/WarBugs#14516] opened 2019-07-03 16:04 UTC
**Expected behavior and actual behavior:**
Energy of Vaul is stated to have a 5 second cd (both on the tooltip in game, and the career builder), but is actually an 8 second CD. 

Also, Penetrating Siphon seems to work with Energy of Vaul, it doesn't seem to impact Balance Essence. You are still able to cast on the move, and there is no spirit damage added to Balance Essence when you have Penetrating Siphon slotted.

Additionally, the passage in the tactics description "When casting this ability, you will focus your power into ensuring a hit rather than for maximum damage" is a little nebulous. It should probably read something like "When casting this ability, you will focus your power into ensuring a hit rather than landing a critical hit", since you are unable to crit with Energy of Vaul.

That said, you are able to crit on Energy of Vaul with Penetrating Siphon slotted.

Of note: Energy of Vaul's static heal value and the spirit damage of Penetrating Siphon are both still displayed as 0 on the tooltips.

**Steps to reproduce the problem:**

Hit test dummies with and without tactics equipped.

**Testing Screenshots/Videos/Evidences (always needed):**

~8 second CD on Energy of Vaul
![image](https://user-images.githubusercontent.com/39884574/60606028-93a9c280-9d88-11e9-85e5-a0872561e3a5.png)

Balance Essence damage with Penetrating Siphon slotted
![image](https://user-images.githubusercontent.com/39884574/60606200-eb482e00-9d88-11e9-95d4-53b1df158fc2.png)

Balance Essence damage without Penetrating Siphon slotted
![image](https://user-images.githubusercontent.com/39884574/60606294-1468be80-9d89-11e9-9bc6-ed5ea877bad0.png)

Casting Balance Essence with Penetrating Siphon slotted while moving
![image](https://user-images.githubusercontent.com/39884574/60606572-98bb4180-9d89-11e9-8488-86162c1bc702.png)

Energy of Vaul crits (with Penetrating Siphon slotted)
![image](https://user-images.githubusercontent.com/39884574/60606676-c902e000-9d89-11e9-8f6c-c50767935da7.png)

**Comment by sioding** [comment] 2019-07-13 10:52
fixed with patch from 13.07.2019

**Closed by sioding** 2019-07-13 10:52 UTC
Labels: Ability, Fix Pending

**Comment by Flavor-burst** [comment] 2019-07-14 06:02
After the patch I have tested this and Balance of Essence should basically be removed from the tooltip for Penetrating Siphon, as it (still) does not effect it in any way. 

Additionally, I still think that my recommendation for adjusting the tooltip to what I have stated previous holds merit, since people still seem confused about how this tactic works, as shown in this thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=76&t=32610

**Comment by grunbag** [comment] 2019-07-14 08:10
We rewrote the tooltip already . I’ll check for balance essence

**Comment by Kaloell** [comment] 2020-06-20 17:15
Kinda curious, how did the check go?
Its still in the game as of today.

**Comment by Denteron** [comment] 2020-11-29 12:52
The problem is still actual, I tested this recently.
