### ISSUE TITLE
Empire T3 Epic Quest Cleansing an Empire - step 16 - Broken quest

### ISSUE THREAD

**Issue by Drayne69** [WarEmu/WarBugs#16281] opened 2020-04-07 14:33 UTC
The task:  Click on 3 different cage around the village at 33k/45k.

Return to Lucius Hausen when complete. 

Need to find some stuff at the cages and carts.

The bug: There is no quest items, we searched the whole are, but there is nothing. Some people say the same. We think the quest items missing from the game/quest.

**Comment by Lheana** [comment] 2020-04-07 16:21
Duplicate of #15441

**Closed by Lheana** 2020-04-07 16:21 UTC
