### ISSUE TITLE
Green Cleanin' and Scrub Ya Gud! Shaman Cleanse Missing Interaction

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#16486] opened 2020-04-23 22:33 UTC
**Expected behavior and actual behavior:**
Expected from tooltip of Green Cleanin': "If Greener N' Cleaner successfully removes an effect" it will put a HoT on that ally, this will affect any ally, party member or random. Scrub Ya Gud! tactic says "Any time you use 'this cleanse' on an ally, you will additionally remove one Curse or Ailment from all groupmates within 50 feet of them".  Expected behavior would be for the cleanse to remove a curse from an ally, from the groupmates around said ally, and then give them all HoTs cause it removed a curse or ailment.  Actual Behavior is that it removes the curse from the ally and groupmates but doesnt attach HoT to the groupmates, just the target ally.

**Steps to reproduce the problem:**
Stand near a groupmate and both get cursed/ailment, then with both tactics attached, cleanse one of them, both will cleanse but only target will get HoT.

**Testing Screenshots/Videos/Evidences (always needed):**

Hard to put screenshot mid fight, or find spot with reliable ailments/curses but can try hardest if absolutely needed

**Comment by grunbag** [comment] 2020-04-23 22:37
The tactic give an additional effect , but it’s not a duplicate of greener n cleaner. Everything work as intended here

**Closed by grunbag** 2020-04-23 22:37 UTC
