### ISSUE TITLE
MAgus pet

### ISSUE THREAD

**Issue by Daknallbomb** [WarEmu/WarBugs#6221] opened 2016-05-20 06:54 UTC
magus pet dessaper after last change log  very often 
and the pet makes an error massage . it says ingame nullreferenceexeption was trown the objekt will be destroyed

**Comment by ozarmidrashim** [comment] 2016-05-20 11:15
Closing as dupe of #6211 which I posted to head off these reports.

**Closed by ozarmidrashim** 2016-05-20 11:15 UTC
Labels: Ability
