### ISSUE TITLE
[Tactic] Rugged appears red?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14980] opened 2019-09-29 02:08 UTC
An introduction:
The tactic rugged is now level 16 why does it appear red as if I cannot use it even though I still can?

Details:
It shouldn't be red...

Evidence:
https://youtu.be/6TfQRmjWjuQ

Additional Information:
N/A

How to reproduce the bug:
N/A

**Comment by Scophis** [comment] 2019-09-29 09:03
It was stated in the patchnote-thread by Natherul: 
"Red icons will still work and we have identified where the issue is but its not fixed yet" 
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=33459&start=10#p376659

**Comment by Natherul** [comment] 2019-10-29 13:36
fix coming next client patch

**Comment by Natherul** [comment] 2019-11-03 17:34
should be fixed by now

**Closed by Natherul** 2019-11-03 17:34 UTC
Labels: Fix Pending, Sourcecode
