### ISSUE TITLE
Marauder Impale 

### ISSUE THREAD

**Issue by Nicoltepps** [WarEmu/WarBugs#5553] opened 2016-04-28 14:30 UTC
I noticed that the Marauder's "Impale" ability animation is not correct. Normally, he will thrust with his sword arm, but currently he flails about. I love the original animation for impale, and would very much like to see it return. :D

**Comment by Evildoor** [comment] 2016-04-28 14:41
Do you have a weapon equipped in off hand?

**Comment by Nicoltepps** [comment] 2016-04-28 15:50
Im not sure. I'm assuming he does, but suppose i do and suppose i don't. Which would be the problem?

**Comment by Evildoor** [comment] 2016-04-28 16:15
Having no offhand weapon changes Marauder's animations, even while mutated. Impale is flailing with mainhand weapon if you have no offhand.

**Comment by Nicoltepps** [comment] 2016-04-28 16:17
That's very helpful. Now that you mention it, I remember that being a problem for me in live. Thank you very much for your help!

**Comment by Evildoor** [comment] 2016-04-28 16:18
Closing as not a bug then.

**Closed by Evildoor** 2016-04-28 16:18 UTC
Labels: Confirmation Request
