### ISSUE TITLE
The Glory of Ulthuan bugged

### ISSUE THREAD

**Issue by Fenixfree** [WarEmu/WarBugs#11202] opened 2018-01-23 12:06 UTC
Quest in Elyrion - The glory of Ulthuan  is bugged.After killing all 9 guards required by the quest the cages with captives are still unable to open and free 3 captives. No keys drop from wardens.

**Comment by sioding** [comment] 2018-01-23 15:42
Duplicate of #11202

**Comment by sioding** [comment] 2018-01-23 15:42
Duplicate of #4833

**Closed by sioding** 2018-01-23 15:42 UTC
