### ISSUE TITLE
Guild Recall Scroll cooldown

### ISSUE THREAD

**Issue by georgehabadasher** [WarEmu/WarBugs#7387] opened 2016-08-23 14:13 UTC
The guild recall scroll's cooldown was 5 minutes on live.  Here it's 30 minutes for whatever reason.  I didn't see it in the 'intended changes from live' thread so I'm assuming it's a DB bug.

**Comment by georgehabadasher** [comment] 2016-09-16 03:46
I see it was assigned to "styrkarrr" does that mean it's being worked on or does it still need confirmation?  I've watched a lot of old youtube videos trying to find guild scrolls on CD, but haven't found any yet (which would suggest that the 5 minute cooldown is accurate).

**Comment by Luth-RoR** [comment] 2016-09-16 12:25
There are some changes on RoR made with intention. I don't know if it's a bug or intended.

**Comment by georgehabadasher** [comment] 2016-09-17 04:40
I didn't see it in the "Intentional Changes from Live" thread, although that might not be comprehensive.  Either way, can you confirm that I don't need to keep looking for confirmation?

**Comment by Luth-RoR** [comment] 2016-09-17 08:39
It's more a confirmation request for devs, if it works as intended or not atm.

**Comment by Kaelang** [comment] 2020-04-23 02:25
No confirmation was provided - I'm going to close this report for now.

**Closed by Kaelang** 2020-04-23 02:25 UTC
Labels: Confirmation Request, Database
