### ISSUE TITLE
Influnce from lock in T1 RvR zones is not counted

### ISSUE THREAD

**Issue by mousias** [WarEmu/WarBugs#11775] opened 2018-05-17 19:22 UTC
Expected behavior and actual behavior:
After the lock while the Influnce is reported normally in the log, is not added in your character progress. This happens in all T1 zones when locking, i 've checked only when loosing.

Steps to reproduce the problem:
Nothing to add here, you just wait for the lock on a loosing side.

**Comment by sioding** [comment] 2018-05-18 07:26
Duplicate of #9438

**Closed by sioding** 2018-05-18 07:26 UTC
