### ISSUE TITLE
T1 Dwarf Advanced reward bugged. (Not selectable)

### ISSUE THREAD

**Issue by CreepFingers** [WarEmu/WarBugs#12834] opened 2018-12-10 16:34 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Select reward.  Reward not selectable

Steps to reproduce the problem:
relogged, still not selectable

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-12-10 19:15
Hm - sorry not enough informations. T1 Dwarf is a good start. Do we speak about RvR Influence or a chapter influence ? And if yes - which chapter?  Can you please add more informations?

**Comment by CreepFingers** [comment] 2018-12-11 17:04
Witch Hunter
________________________________

**Comment by Lheana** [comment] 2020-02-20 17:50
Please provide a screenshot cause I don't understand what the issue is exactly.

**Comment by raptrr** [comment] 2020-03-07 09:06
No further information was give. Closing

**Closed by raptrr** 2020-03-07 09:06 UTC
Labels: 2 Week Ultimatum, Confirmation Request, Database, Item
