### ISSUE TITLE
Reikwald Fort Renown Bug

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#14273] opened 2019-05-30 00:14 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Expected 30k renown tick. Only got 408 renown, got the medallions and bag roll though.

**Steps to reproduce the problem:**
Unknown, typical renown bugs usually occur on super fast fort. But this fort lasted until the very end. Perhaps it has to do with the beginning and ending of fort? Or perhaps it has to do with order winning the chaos/empire fort? Regardless of attack/defense.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/58599454-fb2e9880-8245-11e9-9d50-237ff2cca4fb.png)

**Comment by STanli** [comment] 2019-05-30 04:34
Same problem but i also did not get bag roll

**Comment by STanli** [comment] 2019-05-30 04:34
Same problem but i also did not get bag roll

**Comment by sioding** [comment] 2019-05-30 05:55
Duplicate of #14139

**Closed by sioding** 2019-05-30 05:55 UTC
