### ISSUE TITLE
Public Quest Poisonwing Canyon (Black Craig - Dwarf) Contribution + bag-reward as destro

### ISSUE THREAD

**Issue by Akair2** [WarEmu/WarBugs#16530] opened 2020-04-27 21:25 UTC
Today while farming wyverns, i recieved contribution and a loot-bag from an order PQ despite being destro. Screenshots below. I should not be able to roll on PQs of a faction i dont belong to. 

Screenshots: 

![Lasciell_008](https://user-images.githubusercontent.com/64441447/80422243-239f9680-88de-11ea-99cd-03ca38f8220e.jpg)
![Lasciell_009](https://user-images.githubusercontent.com/64441447/80422245-24382d00-88de-11ea-84dd-10f1824441f0.jpg)

**Comment by Vayra** [comment] 2020-04-27 21:59
Haven't gotten a roll for that PQ myself yet, but have gotten a lot of influence on my BG while farming there. That shouldn't happen either.

**Comment by Lheana** [comment] 2020-07-02 11:23
Duplicate of #16530

**Closed by Lheana** 2020-07-02 11:23 UTC
Labels: Public Quests
