### ISSUE TITLE
A Lord's Game

### ISSUE THREAD

**Issue by Ashton008** [WarEmu/WarBugs#16396] opened 2020-04-15 20:21 UTC
Upon finishing this quest and receiving my Brutal Eadplate on my BO the server crashed and they fixxed. when i signed in the helm is gone and the quest is gone. can anyone restore item plz. i still currently have the chest piece.

**Comment by Ashton008** [comment] 2020-04-15 20:27
![Thazar_004](https://user-images.githubusercontent.com/63750638/79385046-921f4480-7f2d-11ea-8823-e12dde17cca0.jpg)
![Thazar_003](https://user-images.githubusercontent.com/63750638/79385055-95b2cb80-7f2d-11ea-9290-66b2b8fac877.jpg)

**Comment by Garnerr** [comment] 2020-04-15 23:58
You can try using this trick. https://github.com/WarEmu/WarBugs/issues/11128

**Comment by Kaelang** [comment] 2020-04-19 15:57
You highlighted that the quest ended, and a reward was given, indicating the quest is working as intended. Although I appreciate the server restart causing an issue with a lost item, this is not necessarily a bug and therefore I'm going to close this issue.

**Closed by Kaelang** 2020-04-19 15:57 UTC
Labels: Item, Quests

**Comment by Ashton008** [comment] 2020-04-21 18:00
Well how would i be able to obtain the item. I asked a GM and they told me i had to bug report to get my item back...
    On Sunday, April 19, 2020, 10:58:10 AM CDT, Kaelang <notifications@github.com> wrote:  
 
 


You highlighted that the quest ended, and a reward was given, indicating the quest is working as intended. Although I appreciate the server restart causing an issue with a lost item, this is not necessarily a bug and therefore I'm going to close this issue.

**Comment by Kaelang** [comment] 2020-04-21 18:09
Appreciate the frustration with lost items however the team don't return / refund items lost.

**Comment by Ashton008** [comment] 2020-04-23 19:18
is there a way i can redo the quest then?
    On Tuesday, April 21, 2020, 01:09:56 PM CDT, Kaelang <notifications@github.com> wrote:  
 
 


Appreciate the frustration with lost items however the team don't return / refund items lost.

**Comment by Ashton008** [comment] 2020-04-23 19:19
Never mind i see there was a trick sent to me. this doesnt reset any of my progress for PVE instances like GB/BB/BE/BS right?
    On Thursday, April 23, 2020, 02:18:30 PM CDT, Ashton Mayfield <ashton.mayfield@yahoo.com> wrote:  
 
  is there a way i can redo the quest then?
    On Tuesday, April 21, 2020, 01:09:56 PM CDT, Kaelang <notifications@github.com> wrote:  
 
 


Appreciate the frustration with lost items however the team don't return / refund items lost.

**Comment by Lheana** [comment] 2020-04-23 19:36
PM me on Discord.
