### ISSUE TITLE
[Epic Quest] T2 Dark Elfs Stage19

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12266] opened 2018-09-05 13:04 UTC
Expected behavior and actual behavior:
Epic Quests should not be stuck in PQ (quoted by wargrimnir), in this example you have to finish 1st stage of PQ Tor Elyn in Ellyrion which means kill 100 mobs to advance to stage 2 so you can kill 3 champs for Epic Quest, not to mention that you also have to score killblow on it which means, it doesnt work well with group.

Steps to reproduce the problem:
Follow EQ DE T2.
I would suggest separate spawn for Champs to finish EQ.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-09-12 06:27
Duplicate of #12180

**Closed by sioding** 2018-09-12 06:27 UTC
Labels: Database, Quests
