### ISSUE TITLE
Daemon's Gate

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#5704] opened 2016-05-08 19:32 UTC
Quest ID 30512,Objld=57857 0 of 1

**Comment by Evildoor** [comment] 2016-05-09 06:10
quest name?

**Comment by Zaxx0nd** [comment] 2016-05-09 17:13
Daemon’s Gate.  It’s a Travel Quest.

**Comment by Bionicpt** [comment] 2016-05-23 21:07
Quest name: Daemon's Gate
Location: Reikland (empire)

Emil Drechsler is the npc to kill. He is there but, upon kill, it does NOT give credit , hence quest cannot be completed.

**Comment by Gakvar** [comment] 2016-09-18 08:01
After killing Emil Dreshsler this quest chain continues into a Temple loaded with daemons where we're supposed to find Walram Keppel. Quest completes when he's killed but there is nowhere in the Temple or nearby nubs to turn it in or continue to further quests.

**Comment by lennip** [comment] 2016-10-30 19:47
Hi, I wanted to add more info about this quest, as the problem described by Gavkar still exists. Walram Keppel should not be a killable character, but instead he should be a (dead) quest giver. Clicking on his body should complete the current quest and activate the following quest in the chain, which consists of further exploring the monastery, killing 6 Warrior Magus  and getting the Corrupted Tome.

Complete quest chain with texts, tasks and related mobs or objects can be found here: [http://marrek.blog113.fc2.com/blog-entry-831.html](http://marrek.blog113.fc2.com/blog-entry-831.html)
(it also used to be on the old war.mmodb.com wiki but link does not work anymore)

**Comment by thorbolt80** [comment] 2017-07-16 16:48
Walram should not be a killable character. but a dead quest giver. Quest still broken.

**Comment by NorKalli** [comment] 2018-05-06 00:31
note to self - learn how to properly set questmarkers

**Comment by NorKalli** [comment] 2018-05-30 05:46
fixed this stage up to "30515" where "corrupting flamer" is supposed to spawn and attack player

**Comment by sioding** [comment] 2018-09-18 18:43
Fixed with patch from 18.09.2018

**Closed by sioding** 2018-09-18 18:43 UTC
Labels: Database, Fix Pending, Quests

**Comment by Thaodan** [comment] 2018-12-19 16:50
Now the brooch isn't clickable.

**Comment by Lheana** [comment] 2018-12-19 16:55
The brooch is an item, right?

**Comment by Thaodan** [comment] 2018-12-19 17:00
I think so. It should be at her body.

**Comment by Lheana** [comment] 2018-12-19 17:04
Have you looked in your quest inventory?

**Comment by Thaodan** [comment] 2018-12-21 17:53
Its in my inventory but isn't counted.

**Comment by Lheana** [comment] 2018-12-21 18:00
Try to abandon the quest and retake it

**Comment by Thaodan** [comment] 2018-12-21 18:13
Doesn't solve it.
The issue is that when accepting the Q you get the brooch in your inventory but that doesn't count..

**Comment by Thaodan** [comment] 2018-12-21 18:18
See these screenshots for more info:
https://thaodan.de/home/bidar/warhammer/screenshots/

**Comment by Lheana** [comment] 2018-12-21 18:18
You must examine it, so click on the item in your inventory

**Comment by Thaodan** [comment] 2018-12-21 18:22
So thats a workaround for not looting the womans body and taking it?

**Comment by Lheana** [comment] 2018-12-21 18:55
The quest will be changed when it will be possible.
