### ISSUE TITLE
Purchase of multiple/stack of (pvp)-stuff not added to inventory

### ISSUE THREAD

**Issue by Arlen88** [WarEmu/WarBugs#11736] opened 2018-05-08 11:10 UTC
The purchase of multiple/stack of pvp stuff (tested with Klad of the challenger for ironbreaker on a witchhunter) substracts the scout emblems but the items where not added to the inventory.

So, i had 1174 scouts's emblems and tried to buy a stack of 20 klads. After the 'unusable confirmation dialog, the scout emblems where substracted correctly (174 afterwards) but no klads where added to inventory.

Tested it again with Irongaunts afterwards -> same effect.
Tested it again with Obliterator Shankboots -> same effect

**Comment by sioding** [comment] 2018-05-08 11:46
Duplicate of #10703

**Closed by sioding** 2018-05-08 11:46 UTC
