### ISSUE TITLE
Black Orc- You Got Nuffin' scaling

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12656] opened 2018-11-20 09:02 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Black Orc tactic You Got Nuffin' is intended to heal group for X health where X is scaling with mastery points spent in Path of Boss. Currently You Got Nuffin' does not scale with Path of Boss, instead it will scale with active War Bellow. 

Example: Black Orc spec: 13 brawler, 0 toughest, 9 boss.
While using warbellow from brawler YGN will heal for 96 hp each tick, while using warbellow from toughest YGN heals 67 a tick, using warbellow from boss YGN will heal 87 a tick.

Steps to reproduce the problem:
Make YGN scale with Path of da Boss.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-11-20 13:41
Duplicate of #6113

**Closed by sioding** 2018-11-20 13:41 UTC
Labels: Ability
