### ISSUE TITLE
Dark Elf Ch7 no Basic reward for Influence

### ISSUE THREAD

**Issue by LuminaNocte** [WarEmu/WarBugs#17475] opened 2020-08-08 12:36 UTC
No Basic reward for the dark elf ch7 inflence in the shadowlands

![missingfirstreward](https://user-images.githubusercontent.com/69389829/89710545-79c3b180-d984-11ea-88f2-27674e65bbb4.PNG)

**Comment by Lheana** [comment] 2020-08-08 12:52
Duplicate of #10205

**Closed by Lheana** 2020-08-08 12:52 UTC
