### ISSUE TITLE
Recieved Fort loot without being in the Fort.

### ISSUE THREAD

**Issue by Juckaaa** [WarEmu/WarBugs#13622] opened 2019-03-12 13:20 UTC
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I was trying to get into Fort by clicking the portal into Butchers pass. I did not get into fort at any stage. Logicly I should not get any rewards from the fort battle.

But for some reason i recieved reward from fighting in the Fort in the sum of 75k renown and 4 invader medallions and i also got to participate in the fort loot rolls.

didnt win any bags though.

**Steps to reproduce the problem:**

Get fort battle.
Dont have a reserved slot.
Spam click portal.

**Screenshots/Videos or archive.org evidences:**
![Desktop Screenshot 2019 03 12 - 14 17 17 63](https://user-images.githubusercontent.com/43181769/54203177-f9b8c400-44d1-11e9-9325-50395a3b0207.png)

**Comment by sioding** [comment] 2019-03-12 18:38
Duplicate of #13618

**Closed by sioding** 2019-03-12 18:38 UTC
Labels: Fortresses, Sourcecode
