### ISSUE TITLE
[ Marauder ] Wave of Terror Ability

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#8438] opened 2016-11-22 08:24 UTC
http://waronlinebuilder.org/#career=mar;0;13;0;;13:;;;0:0:0:0:

Tooltip says; Ability prevents all morale regeneration for 5 seconds.

Morale gain still continues with "Bolstering Boon [AM Morale Tactic]" and "Embrace the Flames [BW Morale Tactic] "

**Comment by Haojun-Phalanx** [comment] 2016-12-13 12:16
Here's the confirmation. Ability working without morale tactic.
![hao_014](https://cloud.githubusercontent.com/assets/23129933/21140033/936660a4-c13e-11e6-9fbd-8b8a98742260.jpg)

With morale tactic of BW, morale gain still continues:
![hao_000](https://cloud.githubusercontent.com/assets/23129933/21140044/a86a2620-c13e-11e6-8c15-6476f8e01828.jpg)
![hao_002](https://cloud.githubusercontent.com/assets/23129933/21140052/af397bae-c13e-11e6-9076-dc30d2e1e1af.jpg)

**Comment by Luth-RoR** [comment] 2016-12-13 17:19
My guess is that both tactics do work as intended atm, as the _ability_ seems to affect normal morale gain but no _tactics_.
I'm trying to get Dev confirmation.

**Comment by Haojun-Phalanx** [comment] 2016-12-17 13:02
Tactics are working.

Wave of Terror not preventing offensive target morale gain with tactic.
Tooltip says "Tooltip says; Effected target can't regenerate morale for 5 seconds."

**Comment by Blaqwar** [comment] 2016-12-17 13:42
Note the wording, regenerate (as in natural regeneration) versus generate (additionally create morale). Granted though, Mythic hasn't been always accurate with tooltip descriptions. I guess this issue could use a source from the live servers, I'll see if I can dig something up.

**Comment by Luth-RoR** [comment] 2016-12-18 08:39
Maybe it has been changed intentionally, as all tactics and abilities that modify morale gain work according to the RoR mechanic now. 
_
The value of any ability, morale or tactic component that modifies Morale is multiplied by the above morale scaler divided by 3.6. This means that morale pumps and drains only use their tooltip value when the morale scaler is the maximum of 3.6x._
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16694

That means that any tactic/ability that prevents _all_ morale gain would be 100% effective regardless how many enemies around.

**Comment by Haojun-Phalanx** [comment] 2016-12-19 09:30
Maybe patched who knows, we need confirmation.
WoT isn't morale drain btw.

**Comment by Kaelang** [comment] 2020-09-24 14:16
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.

**Closed by Kaelang** 2020-09-24 14:16 UTC
Labels: Ability, Confirmation Request
