### ISSUE TITLE
Guild Heraldry Reservation bugged

### ISSUE THREAD

**Issue by FAmeloon** [WarEmu/WarBugs#13022] opened 2019-01-03 18:26 UTC
Expected behavior and actual behavior:
As the Guild Leader of Spanish Inquisition, Rank 10 Guild, I attempt to set our Guild Heraldry from rewards tab. The button is not grayed out, I can edit the entire heraldry, but when I go to confirm it gives me a message along the lines of "Saving this Heraldry is permanent and will cost you 01704. Do you really want to save?" I click on Yes, and nothing happens. The Reserve Heraldry button is not grayed out, the Heraldry is not set, it remains the basic Heraldry.
![guildheraldry](https://user-images.githubusercontent.com/45919568/50654519-7b84f200-0f63-11e9-90f2-333a2bf4259f.png)

**Comment by sioding** [comment] 2019-01-03 18:34
Duplicate of #10417

**Closed by sioding** 2019-01-03 18:34 UTC

**Comment by FAmeloon** [comment] 2019-01-03 18:53
So, is there a fix to this?

**Comment by sioding** [comment] 2019-01-03 18:55
Click the duplicate report. It´s not needed to have multiple reports for the same issue.
