### ISSUE TITLE
[Quest] Distillation of Hate, A Lords' Game

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#13336] opened 2019-02-10 07:01 UTC
Distillation of Hate
quest mob is not targetable or lootable.
mob is Ellyrion Steed.

A Lords' Game
almost at last stage.
mission is kill Ellyrian Archer 8, Ellyrian Commander 3 at the Tor Elyr PQ.
there is only 2 archers and 0 commander at 1st stage.
have to kill 100 mobs for next stage.
not sure it's intended but i thought epic quest should not related to PQ stages?

**Comment by Scophis** [comment] 2019-02-10 09:12
See #12180

**Comment by sioding** [comment] 2019-02-10 09:15
meh - overseen - thanks to @Scophis 
Duplicate of #12180

**Closed by sioding** 2019-02-10 09:15 UTC
Labels: Database, Quests
