### ISSUE TITLE
20/05/2021 patch archmage bugs

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#19018] opened 2021-05-21 06:20 UTC
**Expected behavior and actual behavior:**
After the patch Lambent Aura doesn't build Force stack and Drain Magic doesn't work at all.
In particular ,Drain Magic doesn't apply the debuff (it doesn't apprea neither on buffhead nor on buff list in the health bar) and you receive no AP from it. I tried casting it on some player/mob and then using Flee. I had no AP untill the nomal regeneration kicked in.
I'm sorry to rport two bug at once, I'm in a bit of a hurry.
**Steps to reproduce the problem:**
Use the skills

**Testing Screenshots/Videos/Evidences (always needed):**
I will produce some SS/video later if I have time

**Comment by Antaiii** [comment] 2021-05-21 08:13
Lambent aura does not work on multiple people when you use it on yourself, only on others (not sure if this is intended or not).
Bolstering boon does not seem to work at all. And I can confirm Drain magic does not work either.

**Comment by CornerbackAC** [comment] 2021-05-22 11:25
Can confirm that Lambent Aura doesn't work on others when you use it on yourself.

**Comment by toncio12** [comment] 2021-05-22 14:40
I also can confirm:

Ey Quit Bleeding (shaman hot) does not apply on allies when u cast it on yourself. Same problem as AM.
Dont know if it intended to be this way or it is a bug.

**Comment by xpander69** [comment] 2021-05-27 11:25
related: https://github.com/WarEmu/WarBugs/issues/19009

**Comment by xpander69** [comment] 2021-05-27 11:35
closing this, since its mirror duplicate of this https://github.com/WarEmu/WarBugs/issues/19009

**Closed by xpander69** 2021-05-27 11:35 UTC
Labels: Ability
