### ISSUE TITLE
Altar of Madness PQ champion is missing

### ISSUE THREAD

**Issue by Melisandrea** [WarEmu/WarBugs#9767] opened 2017-06-05 12:28 UTC
During stage 4 Altar of Madness PQ (Empire ch 22) Vhergaal the Fatebringer is missing (maybie under altar?). I checked terrain around and no sign.

**Comment by Razielhell** [comment] 2017-06-05 14:43
Also Stage 2 is skipped.

**Comment by grunbag** [comment] 2017-06-07 13:59
Fixed on next patch

**Comment by Gnashspike** [comment] 2017-06-11 12:31
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Melisandrea [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBTIBWQVQDKSWCAFMABEABKBW2QEQQMBIV3BAWGA2Y2SBOMKACGPJDMQCLKJLSDARRQRSIM5T72UV7DR6EFAYJDJZLIMJHBFSBDPBZRQ4CAAWBCDAAD4ADXABHQAGYAB4AFWBSPQYC6MBLGASWM2DKM4CWKEVQICQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 05:30:48 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp d187si1535174ywf.366 - gsmtp:
    retry timeout exceeded

**Comment by Luth-RoR** [comment] 2017-06-12 07:47
Dude, can you please stop sending emails to Github and instead login via browser, just as virtually everyone else?

**Comment by grunbag** [comment] 2017-06-12 12:05
this one should be locked. no more bug

**Closed** 2017-06-12 12:30 UTC
Labels: Database, NPC, Public Quests
