### ISSUE TITLE
All quests since the beginning of the game... they all reset...

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11580] opened 2018-04-10 05:38 UTC
All the quests have done for years they all reset. Unlog/log change nothing. So I am able to do again all quests of the game. All the quests I have done turn green.

![thorbolt_174](https://user-images.githubusercontent.com/16274785/38538000-1efa1d8e-3c92-11e8-9ece-f9c148b41f15.jpg)

**Comment by sioding** [comment] 2018-04-10 06:31
Duplicate of #10421

Sorry @thorbolt80 that you ran into that bug....

**Closed by sioding** 2018-04-10 06:31 UTC
