### ISSUE TITLE
Black Crag PQ Hard- Skargor da Traitor

### ISSUE THREAD

**Issue by Strykhaven** [WarEmu/WarBugs#11177] opened 2018-01-21 13:43 UTC
Hello Lheana, good day RoR Team!
First of all, thank you for all of the work and effort you are putting into keeping our favorite game alive!

Issue: Black Crag PQ Hard- Skargor da Traitor

Expected behavior and actual behavior:

Expected: Kill count per Mob in PQ = 1
acutal: Kill count per Mob = 3

Steps to reproduce the problem:

kill mob (group= DoK, Choppa, Chosen, Mara

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Strykhaven** [comment] 2018-01-21 13:48
Pardon, it even counts as 5 sometimes

**Comment by sioding** [comment] 2018-01-21 14:35
Duplicate of #11161

**Closed by sioding** 2018-01-21 14:35 UTC
