### ISSUE TITLE
Login issues are back 

### ISSUE THREAD

**Issue by Oculta** [WarEmu/WarBugs#13807] opened 2019-04-06 16:53 UTC
Login issues are back again ... after character creation we are going back on server/or character screen.

Pls check maybe iam not alone.

Thx

Edit: Now i cant login with any other character ... 

btw: nice patch

**Comment by Oculta** [comment] 2019-04-06 16:54
Now i cant login with any other character ...

**Comment by Oculta** [comment] 2019-04-06 16:58
![screenshot_001](https://user-images.githubusercontent.com/31412693/55672666-f2e95b00-589d-11e9-9ae5-b6dcd009d6c4.jpg)

**Comment by sioding** [comment] 2019-04-07 05:41
Duplicate of #13776

**Closed by sioding** 2019-04-07 05:41 UTC
