### ISSUE TITLE
Promise of Power quest easier than it should be

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14664] opened 2019-07-27 23:03 UTC
Expected behavior and actual behavior:
The tooltip says you must assist with the completion of a stage of the PQ, but killing a single enemy completes the quest.

Steps to reproduce the problem:
In Norsca, destruction side, have the quest active and kill one of the enemies at the PQ's area.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_000](https://user-images.githubusercontent.com/53320075/62000290-a2467980-b0a9-11e9-9378-37e3a53e752c.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62000291-a2467980-b0a9-11e9-84ae-b1a48edb16ed.jpg)

**Comment by Lheana** [comment] 2019-07-28 20:37
Duplicate of #431

**Closed by Lheana** 2019-07-28 20:37 UTC
Labels: Database, Quests
