### ISSUE TITLE
Quest "On the brink of chaos" Chp 15-16 Empire

### ISSUE THREAD

**Issue by Falkenmayer** [WarEmu/WarBugs#11919] opened 2018-06-21 17:16 UTC
The rewards given by this long quest to the class KotBS are a 2 handed greatsword and a "2 handed Greatshield". That greatshield is actually a 2 handed dwarven greatxe with shield stats
 and broken animations.

Screenshots/Videos or archive.org evidences:
http://subefotos.com/ver/?f253863b30095e218c92d3d57e3ee8d9o.jpg
http://subefotos.com/ver/?00a52eb872d4a6eb672c312eb9487e9do.jpg

**Comment by sioding** [comment] 2018-06-28 17:05
Duplicate of #11960

**Closed by sioding** 2018-06-28 17:05 UTC
Labels: Database, Item
