### ISSUE TITLE
Tome of Knowledge - Blank Quest List

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#12200] opened 2018-08-23 11:39 UTC
Expected behavior and actual behavior: all my quests are gone from ToK, and I can't complete any of them that I previously had.

Steps to reproduce the problem: unkown

Screenshots/Videos or archive.org evidences:
![xalzius_007](https://user-images.githubusercontent.com/41837044/44523383-e979fc80-a6d9-11e8-8024-c5ff1ad017bf.jpg)

**Comment by sioding** [comment] 2018-08-23 12:06
Thias is a known problem we can not fix atm. Seems to be sad for you - but you have to get the quests again.
Duplicate of #2001

**Closed by sioding** 2018-08-23 12:06 UTC
