### ISSUE TITLE
Marauder stance buff not shown anymore 

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#18424] opened 2021-01-29 21:36 UTC
**Expected behavior and actual behavior:**
The marauder stance buff is not shown anymore in the buff bar.

**Steps to reproduce the problem:**
Use any marauder stance :-)

**Testing Screenshots/Videos/Evidences (always needed):**

![WAR-64 2021-01-29 22-31-57](https://user-images.githubusercontent.com/16682919/106329671-27ec4c00-6282-11eb-8a18-caed7ae7a2ae.png)

**Comment by lilimx** [comment] 2021-06-26 09:53
Hey,

thank you for your ticket.
But it looks fine on my end. Maybe an addon issue?
Can't reproduce it.

Is it still a thing?

**Comment by lilimx** [comment] 2021-07-10 09:27
Hey,

im going to close this ticket now due to no feedback.

**Closed by lilimx** 2021-07-10 09:27 UTC
Labels: 2 Week Ultimatum, Confirmation Request
