### ISSUE TITLE
Inventory disappeared after disconnection of the game

### ISSUE THREAD

**Issue by Gaulwon** [WarEmu/WarBugs#4918] opened 2016-03-13 13:01 UTC
Last night, suffered a disconnection of the game; when I reentered discovered that almost all the content of my inventory and my personal bank had disappeared (mount, pots and all material apothecary and cultivator).

**Comment by rraveen** [comment] 2016-03-13 16:02
I have the same issue. I was in the middle of scenario and was kicked during the hotfix.  When the server came back up, I had lost my book of binding, 10G horse, tons of talisman, and potions.

**Comment by bene1986** [comment] 2016-03-13 16:08
I have this issue too !
I was kicked during a hotfix and when i came back into game my whole inventory was gone. 

There is literally nothing left :-(

**Comment by taccr** [comment] 2016-03-13 16:28
This is not a bug.
There was an item handler error after the first patch affecting everyone who logged in after that.

Most of your items (if not all) should be at the vendor buyback.

**Comment by bene1986** [comment] 2016-03-13 16:30
I can not interact with a vendor.

**Comment by rraveen** [comment] 2016-03-13 17:12
So we have to pay money to get back all our items that was caused by the game.  Don't see where that is right.

**Comment by taccr** [comment] 2016-03-13 17:14
Big Alpha on the front page. Be happy that the server is in the state it currently is.
People make mistakes.

**Comment by bene1986** [comment] 2016-03-13 17:17
i can't buy anything back.

Vendor is broken for me

**Comment by rraveen** [comment] 2016-03-13 17:56
I understand people make mistakes, I work in IT and understand patches don't always go right, but you don't make the population suffer because of those mistakes.

**Comment by Gaulwon** [comment] 2016-03-13 18:23
I can´t interact with vendors...

**Comment by Gaulwon** [comment] 2016-03-14 22:32
I still can't interact with vendors and my inventory remain the same: any solution?

**Comment by Evildoor** [comment] 2016-03-15 08:21
http://www.returnofreckoning.com/forum/viewforum.php?f=5
According to several topics here, you should PM a GM. Therefore, bugtracker is a wrong place for this problem, so i'm closing this.

**Closed by Evildoor** 2016-03-15 08:21 UTC
