### ISSUE TITLE
Apothecary bug

### ISSUE THREAD

**Issue by Setthariel** [WarEmu/WarBugs#10778] opened 2017-11-06 13:58 UTC
https://youtu.be/CYEQtLCzLUg 

I have bad English, so, just use bandicam to cap all process and results for Apothecary...

In 2 words about bug: 
Instead of potions, creates Another Junk :(

**Comment by sioding** [comment] 2018-01-28 17:24
Duplicate of #10660

**Closed by sioding** 2018-01-28 17:24 UTC
Labels: Crafting
