### ISSUE TITLE
City siege bag

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#15661] opened 2020-02-10 14:39 UTC
Hi !

Today doing my first city siege. I win green bags in all stage. I can loot the bag from 1st stage but 2nd and 3rd stage cant loot bag .Thx for answer nad/or repairing .

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment] 2020-02-13 16:01
Duplicate of https://github.com/WarEmu/WarBugs/issues/15660

**Closed by dalen** 2020-02-13 16:01 UTC
Labels: City Siege, Item
