### ISSUE TITLE
Mail missing after a crash

### ISSUE THREAD

**Issue by Kordie** [WarEmu/WarBugs#10061] opened 2017-07-30 05:14 UTC
Sent some crafting mats to my TM and upon logging out got the buttons but no chars or background. Restarted the client and while the crash was fixed my mail has gone missing. My T4 go hear for gold quests seem to have reset also.
Actually all the quests i had started in my quest log are gone completely.

**Comment by sioding** [comment] 2018-04-07 09:25
Duplicate of #10421

**Closed by sioding** 2018-04-07 09:25 UTC
Labels: Database, Dubious, Mail, Quests
