### ISSUE TITLE
Stealth + scenario's bug.

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10966] opened 2017-12-07 16:40 UTC
If I enter a scenario while in stealth i will spawn with my ''stealth'' skillbar and will not be able to use skills untill I stealth and de-stealth again to fix it.

Going in or out of scenarios creates the same outcome.

Stealth > go in scenario > get bugged.

**Comment by Morksezstop** [comment] 2017-12-07 18:05
That happens everytime when facing a loading screen while stealthed, most common that occure loading in or out of sc. To fix it u should wait cd of the skill then go stealthed again and disable it to recover the normal skill bar. It is super annoying esp loading out at orvr

**Comment by HKMFNADO** [comment] 2017-12-07 18:32
Yea, to fix it u can just go back in stealth and out of it, it burns a CD though, if you exit a scenario and u are in the middle of the fight, or if u enter one that already started u will blow your most important CD.

I thought I'd report it as I'm sure it can be fixed.

**Comment by Nfkillz** [comment] 2017-12-08 07:42
this bug already was reported

https://github.com/WarEmu/WarBugs/issues/9619

**Comment by sioding** [comment] 2017-12-08 11:24
hm @Nfkillz has betta search skillz than me. ;) thx @Nfkillz

**Comment by sioding** [comment] 2017-12-08 11:25
Duplicate of #9619

**Closed by sioding** 2017-12-08 11:25 UTC
Labels: Ability
