### ISSUE TITLE
{Quest} Wyrmbraker last step bugged

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#15773] opened 2020-02-23 14:04 UTC
**Expected behavior and actual behavior:**
Last step requires going in to a pool and using an item to summon an npc, as shown in the screenshot, the "use" part is completed but the "enter" part does not and the mob does not spawn, so we can't kill him.
(We try to clear the public quest but the second stage seems also bugged)
We try to drop the quest and take it again with the same result.
 (you have to drop the item or everytime you get the quest you end up with one more item than before,
- droping the quest does not clear the item from the backpack 
- and also taking the quest does not check if you have already that item in the backpack. 

Idk if this can be a separated bug report for this quest since is a different issue but is on the same step)

**Steps to reproduce the problem:**
Do the quest line of this quest until the last step, goto the pool, use the item.

**Testing Screenshots/Videos/Evidences (always needed):**

![imagen](https://user-images.githubusercontent.com/17686095/75113248-6332d380-564c-11ea-83f4-ef839bf2e869.png)

**Comment by Kabucoror** [comment] 2020-02-23 14:11
Duplicate of #12982

**Closed by Kabucoror** 2020-02-23 14:11 UTC
