### ISSUE TITLE
Big bug at Gunbad.

### ISSUE THREAD

**Issue by Florcituzz** [WarEmu/WarBugs#13865] opened 2019-04-13 10:59 UTC
**Expected behavior and actual behavior:**
So we killed the boss of the last PQ at Gunbad, and it bug, as you can see in the image, it didn't count, and we cant take the reward, so big bug, knowing it's not a fast dungeon.

**Steps to reproduce the problem:**
Go to the last PQ on mid gunbad and kill the boss.

![bug](https://user-images.githubusercontent.com/48547251/56078741-fc088980-5dc1-11e9-88f7-da208b5170c3.png)

**Comment by sioding** [comment] 2019-04-13 11:17
Duplicate of #13563

**Closed by sioding** 2019-04-13 11:17 UTC

**Comment by Errunok** [comment] 2019-06-13 19:56
i had a similiar it counted for me but wasn't able too loot the bag and didn't got any mail with bag

**Comment by Errunok** [comment] 2019-06-13 19:56
today around 20:15

**Comment by Bejkon** [comment] 2019-08-21 21:31
not a re-report.

With this one the porblem is that the boss has add NPCs turning friendly as part of the encounter, and they then start attacking the boss. If one of the NPCs get the killing blow on the hero, the PQ stage doesnt finish and thus you cant get into the acual wing end-boss without eitehr waiting for 45min or have RNG on your side when it comes to that killing blow.

/Bejk
