### ISSUE TITLE
Tok order side chapter 21 high elf "buying time" 2 item are missing in basic influence reward and 1 item in advance influence reward

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10004] opened 2017-07-21 18:31 UTC
Tok order side chapter 21 high elf "the call of time" 2 item are missing in basic influence reward and 1 item in advance influence reward

The reward should be the choice between 2 potions for basic influence reward

for advance reward don't know what kind of item.. may be shoulder

**Comment by Lheana** [comment] 2020-02-20 20:35
Duplicate of #7270

**Closed by Lheana** 2020-02-20 20:35 UTC
Labels: Database, Item
