### ISSUE TITLE
Minor spelling issues with dye vendor

### ISSUE THREAD

**Issue by 0xAB51NTH** [WarEmu/WarBugs#20918] opened 2023-05-19 20:04 UTC
**Expected behavior and actual behavior:**
Expected: The names of dyes are correctly spelt and there are no doubles.
Acutal: Some dyes have typos and one dye is twice on the list

**Steps to reproduce the problem:**
1: go to event very special dye vendor
2: Look at the list of dyes

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://github.com/WarEmu/WarBugs/assets/47013267/83ce76b5-bf5e-4251-8022-549531f6869c)
![image](https://github.com/WarEmu/WarBugs/assets/47013267/23b9dc4e-efb6-4cf8-998d-0f021f76a4f7)

Oh also Ostagoth grey is possibly wrong color/wrong name as its blue but in game name and icon suggest grey
![image](https://github.com/WarEmu/WarBugs/assets/47013267/03acd66b-7095-4ec1-92c6-e82244df9d88)
![image](https://github.com/WarEmu/WarBugs/assets/47013267/5bcf651b-be83-4926-8779-52886d71739c)

**Comment by Rubyeclipse-war** [comment] 2023-05-22 05:32
Thanks for the ticket! Quick fixes on the way include:

*Templar Grey found its missing E
*One of the Tuetogen Blue dyes was actually Jutones Blue, it just had the wrong name. This has also been fixed.

For the third color, it's as intended. Thanks again for the ticket!

**Comment by lilimx** [comment] 2023-05-31 20:04
This has been fixed with patch 29/05/2023

**Closed by lilimx** 2023-05-31 20:04 UTC
Labels: Database, Fix Pending
