### ISSUE TITLE
logrin's forge

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#12689] opened 2018-11-23 09:57 UTC
Playing logrin's Forge and both the Hammer and Anvil kept disappearing. See screen shot

![lf_sc_01](https://user-images.githubusercontent.com/44948480/48937471-21c1ee80-ef06-11e8-8f62-a53a3ae3fcaf.jpg)

**Comment by sioding** [comment] 2018-11-23 11:31
scenario objects aren´t working fine atm. will be fixed next patch.

**Comment by sioding** [comment] 2018-11-23 11:32
Duplicate of #12678

**Closed by sioding** 2018-11-23 11:32 UTC
