### ISSUE TITLE
Bloody sun raida's attack allies 

### ISSUE THREAD

**Issue by kmelesh** [WarEmu/WarBugs#14826] opened 2019-08-23 12:12 UTC
Near greenskin chapter 11 where you have to kill oathbearer stormguard for the will of the warboss quest there are friendly mobs called bloody sun raida's that will attack allies and you cant target them back in self defense becuase they are marked as friendly 

screenshot proof:

https://i.imgur.com/5YQGVeo.png

**Comment by Lheana** [comment] 2019-08-25 10:33
Duplicate of #9880

**Closed by Lheana** 2019-08-25 10:33 UTC
Labels: Database, NPC
