### ISSUE TITLE
Level 13 Rare back gear has race restriction

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5610] opened 2016-05-02 06:22 UTC
Harrier capes (lvl 13 blue capes) have race restrictions. Not all combinations are available to all races leaving them without option. The restriction should be removed. 

![screen shot 2016-05-02 at 07 18 38](https://cloud.githubusercontent.com/assets/18053736/14948295/8e903898-1036-11e6-94bb-a120bffcfb68.png)
![screen shot 2016-05-02 at 07 18 58](https://cloud.githubusercontent.com/assets/18053736/14948298/8eb4ce2e-1036-11e6-8e39-a431382031cb.png)
![screen shot 2016-05-02 at 07 17 24](https://cloud.githubusercontent.com/assets/18053736/14948296/8eb2e744-1036-11e6-94d1-11029b3b190a.png)
![screen shot 2016-05-02 at 07 17 57](https://cloud.githubusercontent.com/assets/18053736/14948299/8eb4dd74-1036-11e6-8d3c-689aafb70084.png)
![screen shot 2016-05-02 at 07 19 11](https://cloud.githubusercontent.com/assets/18053736/14948300/8eb7fbb2-1036-11e6-92b7-8447f27784bb.png)
![screen shot 2016-05-02 at 07 19 29](https://cloud.githubusercontent.com/assets/18053736/14948297/8eb428d4-1036-11e6-94bc-8fd8ef958984.png)

**Comment by Evildoor** [comment] 2016-05-02 07:30
Not sure if this is a bug.

**Comment by Dobrodushny** [comment] 2016-05-02 12:01
This is not a bug, it was on live too.

**Comment by MerryGitmas** [comment] 2016-05-02 14:37
Considering that these capes are a direct upgrade from Pillager's capes, that have no class restrictions, it should be considered as such. 
Moreover with this setup, Empire would not have an option for Thoughness+Wounds, Elfs would not have Will or Int or Str options and Dwarfs would not have Ballistic, Str or Thoughness options

**Comment by Ryanfawkez** [comment] 2016-05-03 10:34
Yes, from this combination of 6 cloaks, you'd be right to say that every race is restricted in a certain way. However, there is a cloak for each individual class, given there are 4 different cloaks for each race. Gale-runner's cloaks suffer from the same race restriction. It will not be removed until consensus on the matter has been reached to generalise all RvR/PvE dropped capes to the same baseline of having no racial restriction.

**Comment by Evildoor** [comment] 2016-05-16 10:27
Closing as not a bug per

> It will not be removed until consensus on the matter has been reached to generalise all RvR/PvE dropped capes to the same baseline of having no racial restriction.

**Closed by Evildoor** 2016-05-16 10:27 UTC
Labels: Dubious
