### ISSUE TITLE
[Engineer] No ablilties on turrets

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#16495] opened 2020-04-24 13:25 UTC
If you spawn the same turret 2 times, for the second time it'll spawn with no abilities. At first I thought it was just a visual bug, but no, the turret has no abilities, just autoattack.
To fix this you should spawn the same turret again (for the 3rd time), but again, if you respawn it (for the 4th time) it'd again have 0 abilities.
If you'd spawn a broken turret and use Redeploy, it'd still be broken.
If you'd spawn a normal turret and use Redeploy, it'd still be normal.

![Bug](https://funkyimg.com/i/34eVu.png)

**Comment by Kaelang** [comment] 2020-04-24 14:05
Hi - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16472.

**Closed by Kaelang** 2020-04-24 14:05 UTC
