### ISSUE TITLE
Epic Quest : Honorable Deceit

### ISSUE THREAD

**Issue by Kruelistik** [WarEmu/WarBugs#15327] opened 2019-12-20 02:04 UTC
Kill high elves throughout the Jade Strand of Avelorn.
Veteran Seablade
Shining Truespear
Shining Swiftarrow.

Can't seem to get any credit for killing these mobs that are needed to complete the quest.

**Comment by Lheana** [comment] 2019-12-21 16:19
Screenshot please

**Comment by Kruelistik** [comment] 2019-12-21 16:59
When I was grouped with another person on the same quest path, it wasn't updating or granting credit for the kills. I just went out there solo to take screenshots and I was able to get credit for the kills. Sorry for any inconvenience.

**Comment by Lheana** [comment] 2020-02-16 20:18
Duplicate of #12470

**Closed by Lheana** 2020-02-16 20:18 UTC
Labels: Quests, Sourcecode
