### ISSUE TITLE
Scenario misload/port error

### ISSUE THREAD

**Issue by KasperHawker** [WarEmu/WarBugs#11519] opened 2018-03-27 14:58 UTC
Hi Chaps,

Tried to join Caledor Woods SC, after loading screen this is what i got:

![bug](https://user-images.githubusercontent.com/36804013/37975548-7e68ca9c-31d7-11e8-8078-297b7fb66345.JPG)
![bug2](https://user-images.githubusercontent.com/36804013/37975549-7e84c8a0-31d7-11e8-8eb8-299dbefdb582.JPG)
![bug3](https://user-images.githubusercontent.com/36804013/37975550-7e9f6f5c-31d7-11e8-8331-f3a6728eb22e.JPG)

No sure the cause, but i was both in the game and at the same time the loading page.

**Comment by sioding** [comment] 2018-03-27 16:28
Duplicate of #10753

**Closed by sioding** 2018-03-27 16:28 UTC
