### ISSUE TITLE
Stucked in ranked game!

### ISSUE THREAD

**Issue by Milvus24** [WarEmu/WarBugs#16479] opened 2020-04-23 12:37 UTC
We got stucked in a ranked game (solo) after we had the points to win! We (the order side) maged to get 500 points around 4-5 min in the game and after that the match not finished it continued. Even after the timer hit 0:00 its not finished. After about 10 minutes our misery ended i got teleported back to Nordland but no rewards for victory no mmr increase nothing! 
![Milvu_016](https://user-images.githubusercontent.com/64205033/80099526-7d166700-8566-11ea-8e91-0748fa51a4d6.jpg)
![Milvu_017](https://user-images.githubusercontent.com/64205033/80099530-7f78c100-8566-11ea-9b9c-5eaa10d964dd.jpg)
![Milvu_018](https://user-images.githubusercontent.com/64205033/80099533-80a9ee00-8566-11ea-8788-6127b5a6be44.jpg)

**Comment by Kaelang** [comment] 2020-04-23 12:38
This is a duplicate of https://github.com/WarEmu/WarBugs/issues/16473.

There is a fix pending for this issue, for the time being, we suggest not queuing into Ranked SC's.

**Closed by Kaelang** 2020-04-23 12:38 UTC
