### ISSUE TITLE
WL: Throat Bite and Brutal Pounce do less damage as expected

### ISSUE THREAD

**Issue by Mausini** [WarEmu/WarBugs#12335] opened 2018-09-18 20:16 UTC
Expected behavior and actual behavior:
TB does 128 damage on the target dummy - Damage according to skill description 408
BP does 190 damage on the target dummy - Damage according to skill description 480

Steps to reproduce the problem:
Use any stance
Summon Lion
Attack target dummy
Look on damage log 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment] 2018-09-19 10:54
Can you please add screens on your next report?

**Comment by admaska2** [comment] 2018-11-10 00:49
I would report this Bug to !

BP does 200 damage on the target dummy - Damage according to skill description 512
TB does 133 damage on the target dummy - Damage according to skill description 440

Attack target dummy

![azeyune_063](https://user-images.githubusercontent.com/43276959/48295226-55befd80-e48a-11e8-884d-ba342360376d.jpg)

**Comment by admaska2** [comment] 2018-11-10 00:50
I would report this Bug to !

BP does 200 damage on the target dummy - Damage according to skill description 512
TB does 133 damage on the target dummy - Damage according to skill description 440

Attack target dummy

![sans titre](https://user-images.githubusercontent.com/43276959/48295297-fad9d600-e48a-11e8-982b-58db934335fa.png)

**Comment by admaska2** [comment] 2018-11-10 00:56
![sans titre3](https://user-images.githubusercontent.com/43276959/48295405-cfa3b680-e48b-11e8-81d0-16d8dd7e3465.png)

**Comment by sioding** [comment] 2019-01-27 12:03
Duplicate of #13207

**Closed by sioding** 2019-01-27 12:03 UTC
Labels: Ability
