### ISSUE TITLE
[Marauder] - Ferocious Assault

### ISSUE THREAD

**Issue by Juckaaa** [WarEmu/WarBugs#12299] opened 2018-09-11 18:08 UTC
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

I was unable to locate any report on this issue and when I did .ab changelist to check if marauder has undergone any specific changes i got the message; This career has not undergone any changes.

Breakdown of my Marauders mastery points; I have Maxed out Savagery Tree & I have 6 points invested in Brutality tree for Guillotine. I have NO mastery points in Path of Monstrosity. Ferocious Assault is a core ability in Path of Monstrosity.

Expected behavior and actual behavior:

Ferocious Assault tooltip; Increases your Strength and Toughness by 125 for 10 seconds

What actually happens when you activate it ; Increases your strength by 630 (!) and Toughness by 352 (!) for 20 seconds.

Steps to reproduce the problem:

Be rank 40, Have Path of Savagery maxed out. Activate Ferocious Assault.

Seems a tad bit overpowered.

Cheers!

Screenshots/Videos or archive.org evidences:

![skarmklipp 2018-09-11 20 01 31](https://user-images.githubusercontent.com/43181769/45378375-8eaf3300-b5fd-11e8-9889-b4afc8e9f299.png)

![skarmklipp 2018-09-11 20 05 37](https://user-images.githubusercontent.com/43181769/45378595-2a40a380-b5fe-11e8-8af6-0c5b2bc600c8.png)

**Comment by sioding** [comment] 2018-09-11 19:56
Duplicate of #12225

**Closed by sioding** 2018-09-11 19:56 UTC
