### ISSUE TITLE
[QUEST] [T4 EPIC] [GREENSKIN] [MINOR] Mising map marker in intermediate step

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15779] opened 2020-02-23 18:28 UTC
**Expected behavior and actual behavior:**

Granted that is explained in the quest tooltip and not very important, but seems kind of odd that this step has no map marker at all, making it kind of difficult to track if you don't follow up fast.

**Steps to reproduce the problem:**

Reach the step seen in the shot.

**Testing Screenshots/Videos/Evidences (always needed):**
![Dathenor_001](https://user-images.githubusercontent.com/50114048/75117555-4efdcf00-566a-11ea-8019-4fa3241a9238.jpg)

**Comment by Lheana** [comment] 2020-02-23 20:18
Duplicate of #14223

**Closed by Lheana** 2020-02-23 20:18 UTC
