### ISSUE TITLE
[Quests] Objects only counts if ungrouped

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#13825] opened 2019-04-09 00:23 UTC
The following quests in Altdorf sewers do not work properly: "Tasty morsels", "Poor Gustav!", "Rat eat rat", "Spotting trouble", "Rat man?". None of these count kills for quest npc's, if you are in group. It only counts if you kill solo, but in sewers it is almost impossible.

I have these quests and tried it for many of my characters, at least 6, in different types of group. Different levels, different classes, different conditions (my kill, another group member kill, pet kill). It doesn't work at all, except you are solo.

**Comment by sioding** [comment] 2019-04-09 11:01
I will move this report from the special quests away to be more general cause we have this problem for more than these special ones.

**Comment by sioding** [comment] 2019-04-09 11:34
Duplicate of #12470

**Closed by sioding** 2019-04-09 11:34 UTC
Labels: Quests, Sourcecode
