### ISSUE TITLE
road bug IC

### ISSUE THREAD

**Issue by Alby1312** [WarEmu/WarBugs#16555] opened 2020-04-29 17:27 UTC
road bug Inevitable city 
![bug 1](https://user-images.githubusercontent.com/63458229/80626908-b462a780-8a81-11ea-96c8-0e1e628d9c14.jpg)

**Comment by Kaelang** [comment] 2020-04-29 17:28
I'm going to take a guess and suggest you're trying to show me the character that is stuck in the terrain. In which case, this is a duplicate of here: https://github.com/WarEmu/WarBugs/issues/16496

Please provide more information next time as to what you're trying to report. If I didn't know about this crack beforehand, I'd have absolutely nothing to go off here.

Closed.

**Closed by Kaelang** 2020-04-29 17:28 UTC
