### ISSUE TITLE
Changing any item resets the mastery point set bonus on T4 sets

### ISSUE THREAD

**Issue by Brigamartis** [WarEmu/WarBugs#7024] opened 2016-06-30 19:40 UTC
Since about two weeks ago the skill barrage keeps disappearing from my skill list and I have to go career vendor and buy it back. Minor point I know, but just thought I,d let you know.

**Comment by Zealote** [comment] 2016-06-30 20:23
There's a bug at the moment where if you have an extra mastery point from an armour set bonus, whenever you change your gear you lost the specced ability and get the point back, so have to spend it again. Is that what's happening here?

**Comment by Luth-RoR** [comment] 2016-07-01 18:51
If it is due to switching gear around/loosing the full set bonus: that is not a bug and can't be solved otherwise. 
Solution: install the addon like posted above.

**Comment by Zealote** [comment] 2016-07-01 19:03
> If it is due to switching gear around/loosing the full set bonus: that is not a bug and can't be solved otherwise.
> Solution: install the addon like posted above.

Just to clarify, this happens when you change *any* gear. I can understand it not being considered a bug if you removed one of the armour set pieces (since you've lost the bonus), but when it's an unrelated item, that seems like a bug. Unless I've misunderstood you.

**Comment by Luth-RoR** [comment] 2016-07-01 19:06
I see.

**Comment by Vayra** [comment] 2018-03-25 07:57
The workaround for this bug no longer works as of last patch (disabled anywhere training).

**Comment by Natherul** [comment] 2018-04-19 12:27
This is half fixed with the next patch, it will not remove mastery when switching non set items anymore. I am still working on making it be more intelligent but its a step in the right direction.

**Comment by Natherul** [comment] 2018-11-09 16:04
this is fixed since some time ago provided you dont loose the prerequisite point

**Closed by Natherul** 2018-11-09 16:04 UTC
Labels: Item, Source Code
