### ISSUE TITLE
Can take quest from enemy lords

### ISSUE THREAD

**Issue by MozartKaktus** [WarEmu/WarBugs#17661] opened 2020-08-29 11:38 UTC
I can take quest from enemy lords

![Annotation 2020-08-29 133659](https://user-images.githubusercontent.com/70328284/91635941-df8fe000-e9fc-11ea-9d0f-cf417148f0a7.png)

**Comment by Lheana** [comment] 2020-08-29 11:59
Duplicate of #17503

**Closed by Lheana** 2020-08-29 11:59 UTC
