### ISSUE TITLE
[Quest] Return Fire

### ISSUE THREAD

**Issue by Fellipe92** [WarEmu/WarBugs#18864] opened 2021-04-20 00:09 UTC
The quest "Return Fire" from the Nordland Empire campaing is buged. The Raven Hellcannons wich we are supposed to destroy using the Empire Cannon, aren't counting as a kill after you destroy It. And I can confirm It is a general bug since not only me have this issue, I ask other players in the quest area about this problem, as of today, none in the starting empire zone are able to complete this quest.

(I don't have a screenshot of the problem since It would take a video to "prove" the problem).

That is a major issue since this quest is a main history line quest and without it we can't progress in the game main questchain.

Please help!

**Comment by Lheana** [comment] 2021-04-20 16:45
Duplicate of #18769

**Closed by Lheana** 2021-04-20 16:45 UTC
