### ISSUE TITLE
[Shaman and AM] Hot casted on yourself doesnt apply to others

### ISSUE THREAD

**Issue by toncio12** [WarEmu/WarBugs#19034] opened 2021-05-22 14:52 UTC
**Expected behavior and actual behavior:**
When you cast the hot "Lambent Aura" [AM] or "Ey, Quit Bleedin" [Shaman] on YOURSELF, it doenst apply to other allies.
The hot works fine when you cast on anyone else.

**Steps to reproduce the problem:**
Cast "Lambent Aura" [AM] or "Ey, Quit Bleedin" [Shaman] on yourself with someone near and check if the hot applied to them.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/84630798/119230723-db0fd800-baf3-11eb-9a1e-d95e10c9a2b1.png)

**Comment by xpander69** [comment] 2021-05-27 11:34
duplicate of https://github.com/WarEmu/WarBugs/issues/19009 and https://github.com/WarEmu/WarBugs/issues/19018

**Closed by xpander69** 2021-05-27 11:34 UTC
Labels: Ability
